### ISSUE TITLE
Cursor problem in output destination mapping

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1003]
Mám problém s psaním v Output Mapping destination. Dám kurzor doprostřed slova, začnu psát a po prvním napsaném znaku mi kursor skočí nakonec.

![price monitoring 2017-05-04 17-36-58](https://cloud.githubusercontent.com/assets/12933713/25711942/8271a822-30f0-11e7-80ce-38f443469299.jpg)

![price monitoring 2017-05-04 17-39-19](https://cloud.githubusercontent.com/assets/12933713/25711997/ac87ff62-30f0-11e7-9211-abc47b3c64bd.jpg)

**Comment by odinuv** [comment]
Related https://github.com/keboola/kbc-ui/issues/976
