### ISSUE TITLE
Google Sheet Writer - deleted tables

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1008]
Deleted tables are not show in the configuration - they canot be removed from configuration by the user:

- create configuration
- add two tables
- go to storage and remove one table
- only one table is shown and the configuration cannot be run

**Comment by kacurez** [comment]
malo by to byt fixnute https://github.com/keboola/kbc-ui/commit/2836c92f60f0aa83215d297ad2af38f617abb134
