### ISSUE TITLE
Maintainer can't change name of organization

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1016]
Jako maintainer nemám šanci změnit název organizace. Jediná možnost je založit novou organizaci a projekt(y) tam přehodit.
![r d keboola connection 2017-05-17 15-15-51](https://cloud.githubusercontent.com/assets/12933713/26155555/df49fa54-3b13-11e7-884d-59bd7b80957e.jpg)

**Comment by pivnicek** [comment]
@Matejkys Cau,  no, tohle neni mozny pres UI.  Musime to udelat pres API.  Poslat prosim na support.
