### ISSUE TITLE
Job start N/A for some time

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1017]
![image](https://cloud.githubusercontent.com/assets/4319320/26159590/476014ce-3b1f-11e7-8c6f-bf7dc32e44b8.png)

it does switch to "a few seconds ago" eventually but is N/A for ~20seconds

**Comment by natocTo** [comment]
@odinuv Tady nevím zda je to furt aktuální, zda se něco nezměnilo.

Koukám na implementaci a vlevo pod emailem je čas trvání (duration) a vpravo je kdy to "skončilo" (endTime). Takže start tam není nikde.

Mohl by se tam buď použít ten startTime teda, ten by měl být dostupný vždy. 
Případně by tam šla upravit ta hláška dokud konečný čas není k dispozici ("not finished yet" nebo cokoli)

**Comment by odinuv** [comment]
jo, to je asi fixed, anebo to mozna byla blbost uz od zacatku, uz nevim :)
