### ISSUE TITLE
snowflake writer layout

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1018]
![image](https://cloud.githubusercontent.com/assets/903531/26235879/cbd28daa-3c6d-11e7-8b1d-aae8e9221aba.png)

**Comment by ujovlado** [comment]
toto som som asi pokazil pri update reactu, menil som tam malicko markup kvoli warningom, kuknem to

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/issues/1024

**Comment by ujovlado** [comment]
fixnem to dnes
