### ISSUE TITLE
Credentials na Snowflake bez https

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1020]
snowflake writer vrací link na snowflake bez https - zase jsem narazil na klienta, kterýmu se jejich web nenačte (https://connection.keboola.com/admin/projects/1490/writers/keboola.wr-db-snowflake/276078680/credentials) - stačí tam imho dávat https://keboola.snowf...

**Comment by kacurez** [comment]
nebolo by lepsie aby to vracal provisioning s https namiesto toho aby to priprdlo az ui? ked to je vlastne rest api..alebo sa tam da pripojit aj cez iny protokol?

**Comment by Halama** [comment]
to si nemyslim, tim by se rozbila hromada veci, kdyz to das do odbcs tak to nepojede.

**Comment by Halama** [comment]
takze staci tam dat proste https, uz jsem to tak fixoval tusim u sandboxu, takze tady by to melo byt stejne.

**Comment by kacurez** [comment]
ok pripravim fix

**Comment by kacurez** [comment]
este ma napadlo co ak nastane opacny pripad, tj klient to da do odbcs? :)
ale to je malo pravdepodobne a asi mu dojde ze to ma dat bez https

**Comment by Halama** [comment]
no pockat, v tom host zustane normalne host jenom.

**Comment by Halama** [comment]
jo aha koukam ze u writeru je to trochu jinak, tak tam at je ten host jako link a to https je jenom v adrese.

**Comment by kacurez** [comment]
jasne, predpokladam ze to iste plati aj pre non provisioned snowflake credentials - tj uzivatel to zadava bez https ale ui mu to zobrazi ako link s https v adrese
