### ISSUE TITLE
default transformation backend

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1022]
should be equal to default storage backend

**Comment by kacurez** [comment]
https://keboola.productboard.com/feature-board/6271-planning/features/484217

**Comment by ujovlado** [comment]
Toto vieme fixnut rychlo, spravim to.

**Comment by ujovlado** [comment]
Este debata:

- https://keboola.slack.com/archives/C02CFRNRD/p1499319766747853
- https://keboola.slack.com/archives/C0308KGPP/p1465974511000092
