### ISSUE TITLE
Python/R/OpenRefine transformation jobs (in list)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1027]
Should display info about configuration/row in job list ~/detail~.

**Comment by ujovlado** [comment]
@natocTo prohodil som ti teda aj toto.

Mam len k tomu 2 veci:

- kludne mozes vytiaahnut tu funkciu na ziskanie configId niekde vyssie
- urcite staci ked to bude ako v tom predoslom issue - len s jobov, ktore mam v store (mohla by tam nastat race condition, ze akurat nemam nacitany ten parent job v store, no to by som neriesil)

**Comment by natocTo** [comment]
Jo jasné. O tom druhém vím no, že hledám jen v tom co zrovna mám.
