### ISSUE TITLE
google drive/google sheets writer review

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1029]
- funkcne je to v poriadku. Poprosil som @janmichek o ux review. 
tu su linky k komponentam:
https://connection.keboola.com/admin/projects/PROJECT_ID/writers/keboola.wr-google-drive
https://connection.keboola.com/admin/projects/PROJECT_ID/writers/keboola.wr-google-sheets

Zaujimalo by nas ci je konfiguracny proces pochopitelny tj ma tabulku v kbc a chcem ju dostat do svojho google drive. Vieme ze by to mohlo byt lepsie co by bolo asi na detailnejsiu analyzu a tomu by som teraz vyhol ak je to mozne. Mozno skor vypichnut potencionalne problemy a pasti :)

diky!

**Comment by Halama** [comment]
Místo `Upload` bych dal `Run`:
![image](https://cloud.githubusercontent.com/assets/903531/26547873/6b3ddf24-4471-11e7-931f-2a3688c23d38.png)

**Comment by Halama** [comment]
Co znamená tahle věc v logu?:):
![image](https://cloud.githubusercontent.com/assets/903531/26548027/47ccf3b2-4472-11e7-9b47-0c274d25e30d.png)

**Comment by janmichek** [comment]
Projel jsem to a celkove mi ten pruchod pripada srozumitelny. Nema cenu asi do toho ted vic vrtat, kdyz komponenty probehnou sjednocenim.
Mam k tomu par veci:

- nejvic mi asi mrska ze to ovladani je v tabech (ocekavam wizard)
Nemuzu se ale vratit kliknutim na tab, jenom pres tlacitka next/prev.
Nicmene ted tab vypada aktivne ( na hover se zmeni kurzor) ale nefunguje (options -> destinations)
Takze - at to nevypada jako taby, nebo at taby funguji na click

dale:
- 'Cancel' v modalu bych presunul doprava. Tri moznosti vedle sebe uz clovek musi premyslet
- Ruzne velke labely ve formulari
- nektere labely ma na konci textu dvojtecku
- label 'days' mi neprijde srozumitelny. Vidim tam neco jako 'update period'
- ruzne vysoky input vs select

**Comment by janmichek** [comment]
U tohoto tlacitka mi neni uplne jasny ze si tim muzu vybrat slozku na gdrive

**Comment by kacurez** [comment]
@janmichek dik, suhlasim, este k tvojej poznamke ohladom tabov dodam obrazok - aktivny tab je Destination ale da sa kliknut na Action a potom to vypada nasledovne:
![image](https://cloud.githubusercontent.com/assets/1412120/26550262/217044fc-447d-11e7-9486-cef6ecc64d6e.png)
cc @MiroCillik

**Comment by janmichek** [comment]
Me na to kliknout prave nejde, jenom se to zmeni na hover stav. Obecne mi ale vadi ze to vypada jak taby a ovlada se to jinak

**Comment by MiroCillik** [comment]
Cool, diky za feedback, do nejakeho velkeho prepisu sa zatial pustat nejdem, ale skusim fixnut aspon nejake drobnosti, pripadne vyhodim tie taby a bude to normalny wizard.

**Comment by kacurez** [comment]
zavriem, v pripade potreby sa urobi nova ux issue k tomuto
