### ISSUE TITLE
Tableau Writer output filename extension

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#1033]
Když se filename zadá s příponou .tde, tak vytvořený soubor v Tableau serveru má příponu zdvojenou. V Tableau server writeru se žádná přípona nepřidává, tzn. že to tam připojí navíc Tableau při uploadu. Možná by stačilo v tom output filename inputu nevynucovat příponu?

**Comment by kacurez** [comment]
jednu priponu tam vzdy dotlaci tde exporter:
https://github.com/keboola/tde-exporter/blob/master/src/main.py#L68
urcite sa to posiela s jednou priponou takze to tam priprdne Tableau pri uploadu ako pises.

**Comment by ujovlado** [comment]
Od nas to ide s jednou priponou, takze by som to tu zavrel. Navyse to nie je bug v UI.
