### ISSUE TITLE
job z detailu jobu zůstává v listu jobů 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1036]
Když jdu z detailu jobu na list jobů, tak job z detailu je vidět v seznamu jobů, i když by tam neměl patřit (např. je starší)

![image](https://cloud.githubusercontent.com/assets/497675/26782525/531f1132-49f4-11e7-9b00-ec19fd7a51ab.png)

**Comment by Halama** [comment]
Funguje to úplně debinlně! Nedá se tomu věřit pokud člověk filtruje a ty joby se mění a jednou za čas něco proklikne.
Např:
![image](https://user-images.githubusercontent.com/903531/29019010-886f753a-7b5d-11e7-9c34-46e4c0a826d7.png)

**Comment by Halama** [comment]
Před reloadem celé stránky:
![image](https://user-images.githubusercontent.com/903531/29019040-a3f8c09a-7b5d-11e7-82d3-db6606cb90f7.png)

Po reloadu:
![image](https://user-images.githubusercontent.com/903531/29019057-b1c95d7e-7b5d-11e7-8ce2-4cb49ec9b27c.png)

**Comment by kacurez** [comment]
problem je tu: https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/jobs/stores/JobsStore.coffee#L109
a v mylnej predstave na ui ze api call load jobs vracia diff jobov. 

priklad:
pustil som viac jobov a nechal ui zobrazovat iba waiting joby:
![image](https://user-images.githubusercontent.com/1412120/29024015-6aed6720-7b70-11e7-8853-5c497a3e3b11.png)
po case samozrejme vsetky joby dobehli ako succes takze api call load jobs s filtrom status:waiting vracal prazdny zoznam:
GET https://syrup.keboola.com/queue/jobs?q=status%3Awaiting&limit=50&offset=0&include=metrics
`response: []`
a po mergeIn sa na ui nezmenilo nic..

riesenim je naviac pollovat vsetky non terminated joby ktore ui vidi v store. Imho by sa to malo dat jednym api callom s filtrom ktory bude obsahovat jobIds neskoncenych jobov. A potom zafunguje mergeIn tak ako ma.
