### ISSUE TITLE
Update in app migrations

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#1038]
Migrace podporovaný dev portálem se syncují do Connection tak, že appka dostane jako obvykle flag `deprecated` a navíc jí v `data` přibude `replacementApp`, tj. id appky na kterou se má zmigrovat. (U appek deprekovaných bez náhrady tam být ale nemusí, tak by se v tom případě - a v případě že nejde o nějaký ten starý typ migrace ze sys bucketů - neměl zobrazit migrační button.)

Při volání migrační tooly by se pak v `parameters` namísto `component` měl zadat `origin` (tj. id deprekované appky) a `destination` (t.j. id nové appky z `replacementApp`).

**Comment by JakubMatejka** [comment]
Ještě by bylo dobrý do toho boxu o deprekování dopsat, že konfigurace bude zmigrována automaticky kromě šifrovaných parametrů a případnýho oauthu. Třeba něco jako:
"The configuration will be migrated automatically except for enrypted values which need to be entered manually again. If the app uses oAuth you will have to authorize it again too."

**Comment by kacurez** [comment]
ok urobim nato novu ui komponentu - tu staru radsej nebudem ohybat
