### ISSUE TITLE
Better info about sandbox expiry

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1039]
Tento uzivatel byl zmaten informaci ktera je uvedena v Sandboxovym modalu. 

https://keboola.zendesk.com/agent/tickets/6793

Reálně se dýlka sandboxu počítá podle toho, kdy naposled uživatel otevřel stránku sandboxu v projektu. přihlášení do DB zjišťovat neumíme.
 Navrhovane reseni je: misto varovani (14 dni) udelat countdown, emailova notifikace o vyprseni

**Comment by ondrejhlavacek** [comment]
Mezikrok by mohl bejt zobrazovat `touch` atribut z provisioningu. O prodlužování/vypršení se v budoucnu bude starat workspaces api.
