### ISSUE TITLE
defining primary key columns bug

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1042]
If you write primary key columns in output mapping (and the output table doesn't exist yet) a subtle bug exist - when you separate the columns with a comma, they render as separate columns. However the output mapping thinks it is one column containing comma. Here's an example

<img width="883" alt="screen shot 2017-06-12 at 10 57 01" src="https://user-images.githubusercontent.com/8642344/27026405-e76300b0-4f5d-11e7-9176-c69ae138d297.png">

1. Create a transformation  
2. in the output mapping primary key columns field write  "column1, column2" (that is `column1<comma><space>column2`). This renders as two separate columns, however acts as being literally written "column1, column2"
3. run transformation
4. See error (below) imo 
<img width="920" alt="screen shot 2017-06-12 at 11 03 00" src="https://user-images.githubusercontent.com/8642344/27026640-be57e45a-4f5e-11e7-8e87-fe9084fa2a8f.png">

Feel free to ask for additional explanation, quite hard to describe.

**Comment by kacurez** [comment]
Problem is that the second column value being typed as `<space>column2` is not trimmed :
![image](https://user-images.githubusercontent.com/1412120/27572462-ac1ea7a6-5b3e-11e7-868d-496b55e3e956.png)
