### ISSUE TITLE
Redshift writer - copy configuration breaks credentials

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1048]
Potom co jsem si zkopíroval konfiguraci Redshift writeru s vlastními credentials, tak credentials původní konfigurace přestali fungovat a nové taky nefungovali.
Vrací to:
![image](https://user-images.githubusercontent.com/903531/27217370-e188000e-5279-11e7-8e70-b2fbd4b838e3.png)

**Comment by kacurez** [comment]
aky host url maju tie credentials? Vyzera ze ui vyhodnotilo ze su to provisioning credentials(podla url hosta) a snazilo sa ich nacitat cez projekt v ktorom neni zapnuty redshift. To ze sa to stalo az po zkopirovani je divne..

**Comment by Halama** [comment]
do te doby nez jsem tu konfiguraci zkopiroval do nove tak se zobrazovali v poradku.
Aha, tak ne, nove se to opet rozbilo.
Znamena to asi ze uz se na ne nemuzu vratit.
https://connection.keboola.com/admin/projects/2703/writers/keboola.wr-redshift-v2/289011092

**Comment by Halama** [comment]
host sapi-44-default.cmizbsfmzc6w.us-east-1.redshift.amazonaws.com

**Comment by Halama** [comment]
Job když spustím tak jede správně, jenom se na ty credentials už nedostanu, takže asi problém v UI.

**Comment by kacurez** [comment]
jj je to chyba v ui, podla hosta to vyhodnoti ako provisioning credentials:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/wr-db/react/pages/credentials/Credentials.coffee#237
nastastie sa to deje len "nam" pretoze nikto iny nema vlastne credentials zhodne s provisioning crefentials
