### ISSUE TITLE
[UX] Empty values as null checkbox 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1063]
martin [7:19 AM] 
on si myslel že to zaškrtne globálně a nastaví

[7:19] 
>Ahoj,
>
>pravdepodobne som narazil na bug. Na input mappingu sa snazim nastavit "Convert empty values to null" avsak ked to zaskrtnem, ulozim, tak sa to nastavenie neulozi.
>
>Ono sa to naozaj neulozi (nie len v UX), lebo vyfailuje aj load
>
>Pozriete sa na to, prosim?

[7:22] 
>Aha! Tak urcite by som to tlacitko Add dal pod uroven toho checkboxu, alebo lepsie to vymyslel :)
>
>Diks, Matus

[7:27] 
založim na to pak issue, ted už budu muset odběhnout

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/pull/1064

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/27955554-a9ea1856-6315-11e7-8518-bfa023dc8743.png)

Tady posilam navrh jak to vidim:
Nasel jsem 3 veci ktery mi prijdou matouci
1) jak pise Matus - vsechny vlastnosti sloupce nejsou v jedny rade. To je asi nejvic matouci
2) aby to bylo jeste jasnejsi, tu vlastnost bych zobrazil az kdyz vyberes cokoliv (Vodevr)  v prvnim selectu. Stejne te nulove hodnoty zajimaji az kdyz zacnes stourat v sloupcich.
3) to je spis hypoteza - trochu mi vadi ze dalsi vlastnost nastavujes jinym ovladacim prvkem. Zkusil bych to dat taky do selectu misto checkboxu. Takhle je to pripadne i rozsiritelnejsi. TIm se i objasni ze je to vlastnost a ne jednorazova akce.

Mozna to ma trochu downside ze nevim jestli se to na tu jednu radku vejde. CO myslis?

**Comment by ondrejhlavacek** [comment]
@janmichek díky za postřehy

Do jednoho řádku se to bohužel nevejde, už současnej stav je dost na hraně, navíc ten placeholder uvnitř říká akorát `Empty v`... :-(

Navíc možnosti `""` a `null` nejsou technicky správně, pro číselný datový typy to je `0` a `null`.

**Comment by kacurez** [comment]
a co tak swapnut ten null checkbox s tlacitkom `Add`?

![image](https://user-images.githubusercontent.com/1412120/28016030-35319ab0-65a5-11e7-9414-bf4c50801e27.png)

alebo s tlacitkom `Add` napravo
![image](https://user-images.githubusercontent.com/1412120/28016149-bbd29088-65a5-11e7-87b4-e0f3a81e9839.png)

**Comment by janmichek** [comment]
@kacurez Bylo by to krasny, ale tohle se taky nevejde na jednu radku. Ten obsah radku je dost promenlivej. Zrovna k tomu neco pisu... mmnt

**Comment by janmichek** [comment]
Celkove to neni v dobrym stavu. Ten modal je tu nestastnej, nedava mi smysl ho pouzivat pro tak velkej crud/form.
Dalo by se nejak snadno tenhle modal predelat na podstranku abychom meli dost mista? Tim se to vyresi.

ALternativne nabizim tadyten muj vytvor v plny sirce + dalsi promenlivy obsah zalomit na dalsi radku. Coz samozrejmne nevyresi tu nejvic matouci chybu. 

Ok budiz uvedeno v selectu `0` a `null`, to byl jen nacrt.

**Comment by kacurez** [comment]
este rozmyslam nad tym textom `Convert empty values to null` - technicky sa tomu hovori ze datovy typ je `nullable` tak by stacilo text toho checkboxu zkratit na `nullable` + pridat tooltip s povodny textom a tym sa to zmesti do `xs-1` kontajneru co je v tom riadku rovnaka velkost kontajneru ako ma tlacitko `Add` - Navyse sucet velkosti kontajnerov v tom riadku je 11(aj pre redshift) tj este tam je maly priestor :)

inac suhlasim ze na ten modal je toho az moc vela(co postupom casu narastlo) a zasluzi si samostatnu stranku

**Comment by ondrejhlavacek** [comment]
Nj, `nullable` jsme řešili s Marcem a došli jsme k tomu, že `nullable` se to jmenovat nesmí. Interně jsem tomu někde říkal `nullify`, ale jinak se to i v parametrech api callu jmenuje `convertEmptyValuesToNull`. 

`nullable` říká, že ve sloupci může být `null`. Všechny naše datový typy jsou `nullable`, ale neumíme do nich `null` dát, protože se nepřenese přes CSV (https://tools.ietf.org/html/rfc4180). 

Co kdyby to bylo `[ ] null`? 

![image](https://user-images.githubusercontent.com/497675/28041192-4e55f144-657d-11e7-91b8-89cb7ac39b08.png)

Otazníček se tam už bohužel nevejde (`xs-1`), tak by to musel bejt holej tooltip a ten nikde použitej nemáme. :-(

Jinak souhlas, že tohle se do modalu vůbec nehodí a měla by to bejt samostatná stránka!

**Comment by ujovlado** [comment]
alebo to oddelit vizualne uplne (cez `well`), aby bolo jasne, ze je to samostatna cast, napr:

![screenshot_2017-07-10_23-48-58](https://user-images.githubusercontent.com/419849/28041621-71bb5212-65ca-11e7-94b6-598e9af5f73d.png)

**Comment by kacurez** [comment]
`Null` s otaznickom sa mi tam podarilo dostat bez zalomenia. 

![image](https://user-images.githubusercontent.com/1412120/28049326-36004354-6629-11e7-8880-ed0d7fd391a7.png)

ako som pisal sucet velkosti kontajnerov v tom riadku je 11(xs-11), ak sa vyhodi Add button(xs-1) tak je tam priestor pre kontajner o velkosti `xs-2` do coho sa null s otaznickom v pohode zmesti. :)
Cez ten well to tiez nevyzera spatne :)

Inac rovnaky Null s tooltipom sa pouziva aj v db writeroch.

**Comment by Halama** [comment]
rychle jsem to prolitl a ta Vladova verze stim wellem mi prijde dobra

**Comment by ondrejhlavacek** [comment]
@kacurez tady je součet 12 - https://github.com/keboola/kbc-ui/blob/convert-empty-values-to-null-ux-fix/src/scripts/modules/transformations/react/components/mapping/input/RedshiftDataTypesAddForm.coffee#L67

U ostatních to fixnu, ale u Redshiftu se to prostě nevleze. Well je super, udělám to tak.

**Comment by ondrejhlavacek** [comment]
Díkec

![image](http://g.recordit.co/2KbL1k7drQ.gif)

**Comment by ondrejhlavacek** [comment]
Dál bych to neřešil, můžem pak zkusit dalších pár změn v https://github.com/keboola/kbc-ui/pull/881
