### ISSUE TITLE
Snowflake Writer - nejde zkopírovat heslo

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1066]
Tady https://connection.keboola.com/admin/projects/2741/writers/keboola.wr-db-snowflake/293286246/credentials vidím snowflake credentials a nejde je zkopírovat - u hesla schází clipboard button. Nejde tak writer použít, pokud se k datům má něco dalšího připojit.

![image](https://user-images.githubusercontent.com/1427901/28083622-4699d43a-6676-11e7-9a2b-0caa2578f9e9.png)

**Comment by ondrejhlavacek** [comment]
Jdu hnedka fixnout, to je blbý.

**Comment by ondrejhlavacek** [comment]
@padak to není bug, ale featura. Heslo, který uživatel vloží ručně, šifrujeme a UI ho neumí rozšifrovat. Clipboard button je tam teda zbytečnej.

**Comment by padak** [comment]
@ondrejhlavacek potřebuju vyzkoušet jak se pro Mall chová EU snowflake. Takže jsem založil v EU projekt a v něm Keboola Snowflake Writer, ze kterého jsem to heslo ručně nastavil do US projektu #2741. Nicméně v EU to je úplně stejné a to mi generovala KBC (https://connection.eu-central-1.keboola.com/admin/projects/11/writers/keboola.wr-db-snowflake/163260/credentials).

**Comment by ondrejhlavacek** [comment]
Jo, tak to bude špatně detekce stacku, mmt.

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/28085805-ab38758a-6631-11e7-8a78-949830bdc0e1.png)

fixed by 9d7a3dcaedb45e966b29b5cd3472e9825dfc3f4d

**Comment by ondrejhlavacek** [comment]
Btw nedoporučuju míchat stacky KBC a instance Snowflake, může to nasekat v UI docela paseku.
