### ISSUE TITLE
Overview of deprecated stuff

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#1075]
Display a warning with a list of deprecated components/backends/features on project overview page.

- For components, it could call https://connection.keboola.com/v2/storage/components, to get a list of components in the project and get the deprecated ones. List of deprecated components will be hardcoded in the UI.

- Similarly for backends and features.

- Each item will contain a link to migration instructions and possibly a date, when the deprecated component will be migrated automatically or disabled.

**Comment by MiroCillik** [comment]
![screen shot 2017-08-21 at 14 14 26](https://user-images.githubusercontent.com/1488015/29518838-50832882-867b-11e7-88e8-6d5017d3d5a6.png)

**Comment by ujovlado** [comment]
> Similarly for backends and features.

@MiroCillik pls, tu este budeme dorabat tuto cast? alebo je to uz ready tak ako je to momentalne v produkcii?

**Comment by MiroCillik** [comment]
@ujovlado dorobil by som to, este to treba trochu domysliet. S tymi backendami hlavne. Chcel si to tu zavriet co? :)

**Comment by ujovlado** [comment]
ano, ano, robim priebezne cistku a toto bol kandidat ... ale ze si to ty, este to tu necham :stuck_out_tongue:
