### ISSUE TITLE
ukazovat šedivě disabled projekty

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#108]

**Comment by Halama** [comment]
@JakubMatejka Můžu poprosit o dostylování?
V markupu to vypadá takhle:

![image](https://cloud.githubusercontent.com/assets/903531/8076303/17fd43f2-0f4b-11e5-8c6b-9056b69ef27d.png)

V devel režimu je jeden projek označený jako disabled.

**Comment by Halama** [comment]
Chce to vyzkoušet ve zobrazení v rámci projektu i v samotném seznamu projektů.
