### ISSUE TITLE
component configuration documentation link

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1088]
Bylo by dobrý zobrazovat link na dokumentaci všude kde je nastavený.
Tohle (`keboola.ag-geocoding`) je bez toho nenakonfigurovatelný. Pritom s timhle https://help.keboola.com/extractors/other/geocoding-augmentation/ uplne v pohode.
![image](https://user-images.githubusercontent.com/903531/29352620-b774b67c-8267-11e7-816a-4158109ee40f.png)

**Comment by odinuv** [comment]
pokud ma komponenta `configurationSchema` nezobrazuje se `documentationUrl`, ma to byt popsany v `configruationDescription`

**Comment by Halama** [comment]
no to tam sice je. Ale jak mam treba vedet ze dou output mappingu mam napsat `result.csv` :)

**Comment by Halama** [comment]
jeste se tam teda da dat configurationDescription, na to jsem hodil issue ze nejde nastavit v dev-portal ui. Imho ale by ten link na tu doc mohl byt vsude kde to dokumentaci ma. 
Pro veci bez custom ui imho nutnost.

**Comment by Halama** [comment]
kazdopadne ten description tam pak dopním https://github.com/keboola/developer-portal-ui/issues/222#issuecomment-322699688

**Comment by kacurez** [comment]
zo zdrojaku je zrejme ze link na dokumentaciu sa nezobrazuje pre komponenty ktore maju `configurationSchema ` (ako napr `keboola.ag-geocoding`) 
Zaroven z toho vyplyva ze nato aby sa zobrazil `configurationDescription`(editHelp) musi mat komponenta definovanu `documentationUrl` co mi pride trocha divne(asi mi tu nieco unika).

https://github.com/keboola/kbc-ui/blob/c3b2c17d2525ca581aa373e6f04a62d29d6ac04f/src/scripts/modules/components/react/components/Configuration.jsx#L66-L83

**Comment by ondrejhlavacek** [comment]
keboola.ex-gmail je třeba úplně zoufalej. na https://help.keboola.com/extractors/communication/gmail/ má krásnej popis, ale v UI link není a celkově je to bez toho zoufale obludný.

**Comment by ujovlado** [comment]
v detaile komponenty to uz mame cez badge #1899 ... zatial ale neviem, kde by sme to umiestnili v detaile konfiguracie

**Comment by Halama** [comment]
Dnes jsem zas narazil na ten GeoCoding který bez toho nedám https://help.keboola.com/extractors/other/geocoding-augmentation/

**Comment by Halama** [comment]
Přesunul jsem tu dokumentaci částečně do configuration description a myslím že to je docela dobrý.

**Comment by natocTo** [comment]
Mrknu ještě na to.
