### ISSUE TITLE
show that processors are present in configuration

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1091]
until we have a proper UI to configure processor - show at least that they are configured (via API) in a particular configuration (ideally with `documentationUrl` of the processor for more info)

**Comment by ondrejhlavacek** [comment]
nebude lepší už rovnou vyřešit, aby tam byl nějakej JSON vstup (v modalu třeba)?

**Comment by ondrejhlavacek** [comment]
dlouhodobě bych asi ani nic jinýho pro procesory (který nebudou obalený komplexním UIčkem) nedělal...

**Comment by odinuv** [comment]
no klidne

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/pull/1099
