### ISSUE TITLE
adding primary key in db extractors

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1092]
![image](https://user-images.githubusercontent.com/497675/29472519-0864ea50-8409-11e7-9a23-51f1985da7e9.png)

the tooltip should say something like `Add primary key column "abc"`

**Comment by pivnicek** [comment]
just saw this, will change it in https://github.com/keboola/kbc-ui/pull/1097

**Comment by ondrejhlavacek** [comment]
okay! thanks!
