### ISSUE TITLE
Runnig orchestration can't change notifications

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1095]
Pokud bezici Orchestraci zmenim adresy pro notifikace a ulozim vidim ulozene - vse dle ocekacani.
Kdyz ale orchestrace dobehne, zmeni se nastaveni notifikaci na puvodni.

Navrhovane reseni:
Pokud zmenim notifikace v prubehu behu orchestrace, mel bych dostat hlasku  "the change will take effect with the next orchestration run" a postarat se o to aby to tak skutecne fungovalo a nevracelo se to do puvodniho nastaveni

**Comment by ErikZigo** [comment]
Spis to bude vec orchestratoru. Kouknu na to.

**Comment by ErikZigo** [comment]
On pri skonceni uklada metadata o dobehlem jobu k orchestraci. A pritom asi prepise to nastaveni.
Coz je zvlastni, myslel jsem ze ORM tam posila jen update zmen a ne celyho radku.

**Comment by ErikZigo** [comment]
Nastesti se tyka zrejme opravdu jen nastaveni notifikaci. Vytvorim issue primu pod orchestratorem

**Comment by ErikZigo** [comment]
Tohle zavru, pokracovat budu v tomhle issue https://github.com/keboola/orchestrator-bundle/issues/40
