### ISSUE TITLE
TryKeboolaWizard Lesson 2 - Loading Data

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1096]
Previest uzivatela zalozenim snowflake ex db configu, nakonfigurovat ho a pustit. Zmeny stavu aplikaciu(vytvoril konfig, zadal credentials..) sa budu sledovat podla dispatchnutych flux akcii a stavu store(hlavne installed components config store). Podla toho vieme vyrendrovat jednotlive napovedy wizard modalu v ten spravny moment.

Problemy: 
- 1. ako zistim ci si uzivatel uz zalozil konfig alebo ho tam mal predtym - napada ma nechat ho natvrdo vytvorit konfig s menom `demo` a ked tam bude tak brat ze uz ho vytvoril a odnavigovat ho dalej.
- 2. Credentials k snowfalke demo db - Uzivatel dostane credentials zobrazene vo wizardu alebo bokom? Tie by sa kazdopadne nemali natvrdo zahardkodovat do zdrojaku...

**Comment by janmichek** [comment]
Pripada mi jenodussi ta prvni moznost, ale do vseho nevidim

**Comment by pivnicek** [comment]
tyjo, mam rychle dokoncit tohle: https://github.com/keboola/db-extractor-common/issues/9

**Comment by kacurez** [comment]
@pivnicek I will not make changes to ex db ui. When you are done with your update we will just change text in the wizard modal or something like that, so not a big deal ;)

**Comment by kacurez** [comment]
Je pripravena lekcia Load Data ktora prevedie uzivatela nakonfigurovanim ex db snowflake extraktoru. Este bude treba doladit detaily ale nepustam sa do toho kym nebude nejaky komplexnejsi feedback.

Zaroven som dorobil moznost prepnut step wizard modalu po dispatchnutu zadanej akcie priamo v `lessons.js` ako napr:

```
{...
        'link': 'extractors',
        'nextStepDispatchAction': {type: COMPONENTS_NEW_CONFIGURATION_SAVE_SUCCESS, componentId: 'keboola.ex-db-snowflake'},
        'isNavigationVisible': true,

...}
```
po dispatchnuti akcie ktora obsahuje rovnake properties a values ako zadane v `nextStepDispatchAction` sa modal posunie o krok dalej(podla toho co je zadane v lessons.js) 
Tymto sposobom si zistim ze user zalozil novu konfiguraciu extraktora. Vzdy sa to nejak da nakombinovat cez jednu dispatch akciu, tj nebude treba sledovat sekvenciu akcii.

- credentials k `demo` snowflake db su natvrdo zadratovane v zdrojaku:
https://github.com/keboola/kbc-ui/blob/0a191933dcb912b52b5f810a4a2bd6fb18fb9ecf/src/scripts/modules/try-mode/WizardLessons.js#L132-L136
Rovnako to je popisane aj v https://help.keboola.com/tutorial/load/database/

tu to zatvaram.

**Comment by janmichek** [comment]
@kacurez diky za detailni predani. Prebiram, prozkoumam pripadne se ptam.
