### ISSUE TITLE
Prompt before leaving page with unsaved config

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1098]
**Scenario:**
I am working on a transformation/component configuration in the built-in editor. 
I missclick and close the browser window or click on some link.
The changes are automatically saved. This pollutes the config history, you have to reopen the window, and can't use the "reset" button to restore to the previous state. 

It's not a big deal, you can always return to previous state somehow, but I think it would be more pleasant to implement a pop up asking if `you are sure you want to leave? There are unsaved data in the editor`or something along theses lines rather than auto saving and closing the window.

**Comment by kacurez** [comment]
> I missclick and close the browser window or click on some link. The changes are automatically saved.

@pocin I can not reproduce this behaviour at all, can you describe it in details please?

**Comment by pocin** [comment]
Now I feel stupid. The changes are not saved, the editing session is "cached" and restored when you return. Sorry @kacurez, I misinterpreted that
