### ISSUE TITLE
Nepoužívat font ikonky pro komponenty které nemají vlastní

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#110]
Chová se to jinak než obrázek a pak to rozhazuje inline edit apod.
Naházíme je do S3.

Bude potřeba vyexportovat tyhle ikonky jako transparentní PNG 32px a 64px asi v černý?

![image](https://cloud.githubusercontent.com/assets/903531/8077517/c30be3ec-0f56-11e5-8d26-0213f3c92ca1.png)

O nahrání do S3 a zapojení do app se pak postarám.

**Comment by JakubMatejka** [comment]
Tady jsou

![extractor-64](https://cloud.githubusercontent.com/assets/215660/8079238/89ce01b6-0f63-11e5-924e-2e9c4c81120f.png)
![extractor](https://cloud.githubusercontent.com/assets/215660/8079239/89e8f368-0f63-11e5-985f-ae3561777707.png)
![transformation-64](https://cloud.githubusercontent.com/assets/215660/8079241/89f5a338-0f63-11e5-8368-ad14ce6b0b64.png)
![transformation](https://cloud.githubusercontent.com/assets/215660/8079243/89f5fa36-0f63-11e5-8995-2a3a27abdfeb.png)
![writer-64](https://cloud.githubusercontent.com/assets/215660/8079240/89f3250e-0f63-11e5-8257-57e969641e02.png)
![writer](https://cloud.githubusercontent.com/assets/215660/8079242/89f5bab2-0f63-11e5-938f-a722482111df.png)
