### ISSUE TITLE
Output mapping Docker - don't allow 1:N mappings

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#1107]
Viz https://github.com/keboola/output-mapping/issues/2

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/36035972-d657531a-0db8-11e8-8fbf-c11e777ced2f.png)

takhle nějak by to stačilo? udělal jsem to zatím jen u transformací.
