### ISSUE TITLE
Db extractors - test credentials disabled in static screen

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1112]
Proč je ve statickém režimu tlačítok test credentials deaktivované?
Mělo by být aktivované pokud jsou credentials zadané. Stejně to funguje u db writerů.
![image](https://user-images.githubusercontent.com/903531/30059858-2d52b8c4-9241-11e7-8866-8d4babcd7f8e.png)

**Comment by pivnicek** [comment]
solved by https://github.com/keboola/kbc-ui/commit/7864aec1a49a3516e64a9cd3cbf940c4e8ad9c67 in https://github.com/keboola/kbc-ui/pull/1097
