### ISSUE TITLE
can't save sql code in transformation

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1115]
Not sure If I am going insane, but when I tried to save this sql code into a transformation in one paste:
```sql

```
I couldn't save it.
When I copy & paste it in chunks

```sql
```

```sql
```

**Comment by kacurez** [comment]
@pocin the sql code samples you provided are empty, at least that is what I see. Maybe it got lost somehow, can you please repost it?

**Comment by pocin** [comment]
Oops, I composed the message and then I decided to not post it, but I probably misclicked and it posted anyway.

I can't reproduce it anymore, but here's a gif (15MB) showing it in action if you were curious.
https://www.dropbox.com/s/9dnmdi2cugycx36/transformations_fail.gif?dl=0

In the gif I eventually paste different dummy sql code, but It ended up working with chunking the original larger sql. 

Anyway, it's not relevant anymore, sorry for the false alarm!

**Comment by ondrejhlavacek** [comment]
@pocin Thanks for sharing. We have found and fixed a bug which showed exactly the same behavior earlier this week so I believe it's why it's working now.

Just to make sure, the bug happened when there was an escaped character in the SQL query, eg `SELECT "\n";`

**Comment by pocin** [comment]
Oh cool. 

This is the sql for reference (should be more or less acurate, maybe I am missing a whitespace/empty newline here or there). afaik it didn't contain escaped `\n`

```sql
-- this contains "duplicates" i.e one patron buys multiple tickets for the same show
CREATE OR REPLACE VIEW YESTERDAY_SHOWS_DUP AS
select 
  ord."order_id",
  ord."product_id",
  ord."patron_id",
  prod."name",
  pat."first_name",
  pat."last_name",
  pat."email"
from "db_order" ord
left join "db_product" prod
on ord."product_id"=prod."product_id"
left join "db_patron" pat
on ord."patron_id"=pat."patron_id"
where 
    ord."product_id" IN (
      select p."product_id" 
      from "db_product" p
      where p."show_date"=DATEADD(DAY, -1, CURRENT_DATE()))
    AND
    ord."code"='purchase'
    AND "email" IS NOT NULL;

-- this is deduplicated, one row, one patron (== one show)
CREATE OR REPLACE VIEW YESTERDAY_SHOWS_FINAL AS
select y.* from 
   (select max("order_id") "order_id" 
    from yesterday_shows_dup
    group by "patron_id") y_unique
left join yesterday_shows_dup y
on y_unique."order_id"=y."order_id";

-- this is fed to the subscription classifier
CREATE VIEW PATRONS_FOR_SUBSCRIPTION_RECO AS 
select * 
from "db_patron" 
where "patron_id" IN (select "patron_id" from YESTERDAY_SHOWS_FINAL);
```
