### ISSUE TITLE
Buttons in subscription form for orchestrator notifications are missing text

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#1117]
![notifications 2017-09-07 12-13-01](https://user-images.githubusercontent.com/215660/30158603-11d41df0-93c6-11e7-8bcf-793f6c79667a.png)

**Comment by janmichek** [comment]
aha, opraveno tady https://github.com/keboola/kbc-ui/pull/1119 vsiml jsem si toho nezavazne na tobe xD
