### ISSUE TITLE
default queries/scripts for transformations

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1118]
@odinuv stejně jako pro procesory můžeme i pro transformace zobrazovat placeholder/empty value. pomůžeš mi nahodit nějaký pro `python` a `R`? OpenRefine, MySQL, Redshift a Snowflake nabouchám.

**Comment by ondrejhlavacek** [comment]
openrefine
```json
[
  {
    "op": "core/text-transform",
    "engineConfig": {
      "mode": "row-based"
    },
    "columnName": "myColumn",
    "expression": "grel:toNumber(value)",
    "onError": "keep-original",
    "repeat": false
  }
]
```

**Comment by ondrejhlavacek** [comment]
mysql
```sql
CREATE VIEW `out` AS SELECT * FROM `data`;
```

redshift
```sql
CREATE VIEW "out" AS SELECT * FROM "data";
```
mysql
```sql
CREATE VIEW "out" AS SELECT * FROM "data";
```

**Comment by Halama** [comment]
Možná by něco podobného pomohlo i s tím OM. když by třeba po založení měla tuhle query a k tomu OM -> výstupní bucket tr / out. nebo něco takovýho...

**Comment by odinuv** [comment]
no kdyby se te to pri zalozeni R/Python transformace zeptalo na jednu vstupni a jednu vystupni tabulku, tak by tam mohlo byt tohle:

```
input_data <- read.csv(file = "in/tables/input.csv");
result <- input_data
write.csv(result, file = "out/tables/output.csv", row.names = FALSE)
```

s tim, ze to vygeneruje IM - zadana tabulka -> 'input.csv' a OM - 'ouptut.csv' -> zadana tabulka

**Comment by odinuv** [comment]
pro python
```
import csv

with open('in/tables/input.csv', mode='rt', encoding='utf-8') as in_file, open('out/tables/output.csv', mode='wt', encoding='utf-8') as out_file:
    lazy_lines = (line.replace('\0', '') for line in in_file)
    reader = csv.DictReader(lazy_lines, lineterminator='\n')
    writer = csv.DictWriter(out_file, fieldnames=reader.fieldnames, lineterminator='\n')
    writer.writeheader()

    for row in reader:
        # do something and write row
        writer.writerow(row)
```

**Comment by ondrejhlavacek** [comment]
s IM bych to vůbec nespojoval, jenom bych do kodu doplnil komentář, že si to máš nahradit věcma z input/output mappingu. `import csv` v pythonu jde bez includování package?

**Comment by odinuv** [comment]
no to je prave otazka proc to nespojit s IM/OM, to se tyka i tech SQL transformaci, podle me to tomu hodne prida. Jj `csv` je systemovej package, ten se jen importuje a neinstaluje

**Comment by ondrejhlavacek** [comment]
@odinuv bavili jsme se o tom na večeři s Martinama a přijde nám to dost složitý. Imho by stačil nějakej vzorovej input/output s inline komentářem. Jinak hrozí totiž hrozný zmatení, nevím, jak se chovat v situaci, že si naklikám 2 IM a vidím, jak se mi to mění v kódu, pak do kódu šáhnu (tím to přestane bejt prázdnej default) a další přidání IM už nic neudělá. Imho asi jednodušší to mít genericky (a s popiskama jako v dokumentaci).

**Comment by odinuv** [comment]
ja jsem resil to co psal @janmichek do PB a prijde me, ze je to ono - samozrejme se to tyka jen vytvareni nove transformace! Proste je to template transformace, kterej krome skriptu obsahuje i IM a OM. Cili jeste jednou - predstav si, ze kliknes na "New Transformation" a zobrazi se formular, kde zadas:
- jmeno
- typ
- 1 vstupni tabulku
- 1 vystupni tabulku
a kdyz das "Create" tak te to hodi na transformaci, ve ktere si muzes delat co chces (nic se s nicim nesynchronizuje) a ta je hned spustitelna!

Jinak komentare do skriptu samozrejme muzem dat tak jako tak.

**Comment by ondrejhlavacek** [comment]
@odinuv ok, tak tohle je trochu jiná situace a to bych klidně dodělal do toho zjednodušenýho ui transformací?

**Comment by odinuv** [comment]
no uz jsem trochu vypad z toho, co bude zjednoduseny UI transformaci, ale stejne me prijde, ze tohle je aplikovatelny vsude, ale jako nechcu to nejak brzdit - jestli muzes skripty udelat hned, tak je udelej. Proste mi to prijde polovicaty, protoze kdyz tomu jako user moc nerozumim a uvidim `CREATE VIEW "out" AS SELECT * FROM "data";` tak stejne nebudu vedet jak nastavit IM/OM

**Comment by ondrejhlavacek** [comment]
tohle bylo vyloženě myšlený jako jsme dělali ten empty default pro procesory. ten `SELECT` je sám o sobě bezzubej, ale jeden inline comment to může vyjastnit

```sql
-- replace data with a table from input mapping and out with a table in output mapping 
CREATE VIEW "out" AS SELECT * FROM "data";
```

a pro R třeba
```rscript
# replace in/tables/input.csv with a csv file specified in input mapping
input_data <- read.csv(file = "in/tables/input.csv");
result <- input_data
# replace out/tables/output.csv with a file specified in output mapping
write.csv(result, file = "out/tables/output.csv", row.names = FALSE)
```

**Comment by odinuv** [comment]
jo jasne, btw radsi:
```
-- replace "data" with a table from input mapping and "out" with a table in output mapping 
CREATE VIEW "out" AS SELECT * FROM "data";
```

**Comment by ondrejhlavacek** [comment]
(jsem tam ty texty nahodil narychlo, bude to chtít vypimpit)

**Comment by ondrejhlavacek** [comment]
hotovo
