### ISSUE TITLE
[transformations] restore does not reload configs properly

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1121]
možná to bude souviset s těma reloadama, co jsme řešili při mazání transformace. u ostatních komponent se to afaik neděje

![image](https://user-images.githubusercontent.com/497675/30164708-b6be1c64-93dd-11e7-99df-7a1ea8332c18.png)

**Comment by Halama** [comment]
není to to samý jak tohle https://github.com/keboola/kbc-ui/issues/1094 ?

**Comment by ondrejhlavacek** [comment]
to asi bude
