### ISSUE TITLE
TypeError: r is null

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1123]
https://sentry.io/keboola/keboola-connection-ui/issues/344353742/

```
TypeError: r is null
  at None (blob:https://connection.keboola.com/37df0cf7-354d-264b-b99f-900a33078c9a:1)
```

**Comment by ondrejhlavacek** [comment]
https://sentry.io/keboola/keboola-connection-ui/issues/351803157/

**Comment by ondrejhlavacek** [comment]
A tohle je zavřený proč?

**Comment by ujovlado** [comment]
Nie je to vsetko ta ista issue?

**Comment by ujovlado** [comment]
https://sentry.io/keboola/keboola-connection-ui/issues/351803157/ tom fixol v tom PR.

**Comment by ujovlado** [comment]
https://sentry.io/keboola/keboola-connection-ui/issues/344353742/ bude imho to iste a v Sentry to vidim ako resolved

**Comment by ondrejhlavacek** [comment]
No, nalinkoval jsem to v Sentry k sobě, to bude chyba. Podle textu mi to ale nesedí. Až se to objeví znovu, tak na to mrknem.
