### ISSUE TITLE
Custom science app files input mapping not rendering

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1128]
example here https://connection.keboola.com/admin/projects/2594/applications/dca-custom-science-python/316044785

"pics or didnt happen" here:
![screen shot 2017-09-08 at 16 52 30](https://user-images.githubusercontent.com/8642344/30217408-55605ef8-94b6-11e7-8bdc-1bbc14cb5af0.png)

**Comment by ujovlado** [comment]
@pocin how was the configuration created?

I see input files like:
```js
{query: "***.joblib.dat"}
```
which is AFAIK not supported in UI.

**Comment by ujovlado** [comment]
@pocin ok, got it, we'll fix this soon.

**Comment by ujovlado** [comment]
@pocin it's fixed, I'm sorry it took so long
