### ISSUE TITLE
Description link text

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1139]
![image](https://user-images.githubusercontent.com/569139/30434577-f0e8a348-9967-11e7-97d5-709370496dd8.png)

I don't think `configuration` is very user friendly here.  I'd suggest `Add a description`

**Comment by pivnicek** [comment]
or to be more state-friendly `Description` alone with the edit icon could be enough here.  It is obvious imho what is being described.

**Comment by ondrejhlavacek** [comment]
I was about to ask about this... Okay!
