### ISSUE TITLE
Graphs download - empty page

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1140]
![image](https://user-images.githubusercontent.com/903531/30474064-ae519044-9a02-11e7-8699-fec27ead7dcf.png)

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/30474079-c09ec96a-9a02-11e7-9389-d49094b551db.png)

**Comment by Halama** [comment]
Chrome to už nepodporuje přes data-url https://developers.google.com/web/updates/2017/06/chrome-60-deprecations

**Comment by Halama** [comment]
asi bych to zatím dal pryč.

**Comment by ondrejhlavacek** [comment]
Jo. Bude v nový konzoli něco podobnýho?

**Comment by ondrejhlavacek** [comment]
Nemusí to imho bejt tak složitý, stačí třeba 1-2 levely...

**Comment by Halama** [comment]
grafy tam budou urcite. Tím dát pryč jsem myslel jenom to download tlačítko které nefunguje.

**Comment by ondrejhlavacek** [comment]
jj jasně, to jsem pochopil :-)

**Comment by Halama** [comment]
Imho to ted v browseru obejit nejde. Pošlu PR na kbc-ui a sapi konzoli.

**Comment by ondrejhlavacek** [comment]
pokud jsem to pochopil dobře, tak by to mohl bejt embeddovanej obrázek na nějaký prázdný stránce (right click, save as)

> The data: scheme will still work for resources loaded by a page.

**Comment by Halama** [comment]
jo to by asi šlo.

**Comment by ondrejhlavacek** [comment]
Ještě se to musí odstranit v Storage API konzoli

![image](https://user-images.githubusercontent.com/497675/31069054-f9c9d44a-a75a-11e7-8f80-2faa222392d7.png)

**Comment by ujovlado** [comment]
Doriesim to tu: 
https://github.com/keboola/storage-api-console/issues/32

**Comment by tomasfejfar** [comment]
var width = 2000;
var height = 2000;

viewboxWidth = 5000;
viewboxHeight = 5000;

var svg = document.getElementById('svgGraph');
svg.setAttribute('width', width);
svg.setAttribute('height', height);
svg.setAttribute("viewBox", "0 0 "+viewboxWidth+ ' ' + viewboxHeight);
var img = new Image();
var canvas = document.createElement('canvas');
canvas.setAttribute('width', width);
canvas.setAttribute('height', height);
// get svg data
var xml = new XMLSerializer().serializeToString(svg);

// make it base64
var svg64 = btoa(unescape(encodeURIComponent(xml)));
var b64Start = 'data:image/svg+xml;base64,';

// prepend a "header"
var image64 = b64Start + svg64;

// set it as the source of the img element
img.src = image64;

document.body.appendChild(canvas);

// draw the image onto the canvas
canvas.getContext('2d').drawImage(img, 0, 0, width, height);



var dt = canvas.toDataURL('image/png'); // << this fails in IE/Edge...
dt = dt.replace(/^data:image\/[^;]*/, 'data:application/octet-stream');
dt = dt.replace(/^data:application\/octet-stream/, 'data:application/octet-stream;headers=Content-Disposition%3A%20attachment%3B%20filename=Canvas.png');
document.location = dt;



Jsem vložil do konzole v chromu...
