### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1142]
eg gmail extractor (https://connection.keboola.com/admin/projects/232/extractors/keboola.ex-gmail) has documentation url filled out, but it's not visible anywhere

![image](https://user-images.githubusercontent.com/497675/30497463-39d27534-9a53-11e7-85d0-5b5a14e15387.png)

![image](https://user-images.githubusercontent.com/497675/30497470-403a1c1a-9a53-11e7-976f-910668437d18.png)

![image](https://user-images.githubusercontent.com/497675/30497480-463c3a62-9a53-11e7-9dbb-963e4a678ab7.png)

I have no idea where/how to configure it and the JSON schema is super ugly.

**Comment by Halama** [comment]
souvisí s https://github.com/keboola/kbc-ui/issues/1088

**Comment by ondrejhlavacek** [comment]
jo, dupicate, mažu
