### ISSUE TITLE
Remove  UIS/support of deleted components

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1146]
Pomalu se konečně mažou staré syrup komponenty. Tím pádem už bude možné odstranit jejich kod z UI nebo to zjednodušit tam kde UI podporovalo obě varianty. 
Smazané komponenty hážu sem https://github.com/keboola/docker-bundle/issues/52#issuecomment-330436516

---
EDIT: vlado

Tasky:

- [x] `ex-google-drive`
- [x] `ex-google-analytics`
- [x] `ex-db`

**Comment by ujovlado** [comment]
Na toto sa tesim :tada:

**Comment by ujovlado** [comment]
Tie 3 co sa dali zmazat, uz su zmazane
