### ISSUE TITLE
logical table identifier - get rid of tableIds

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1147]
Teraz ked mame tabulky tagovane podla komponent a konfigov, by imho bolo dobre sa zamysliet nad ux lepsim identifikatorom tabulky a tym sa zbavit tableId ktore sa pouziva teraz. Myslim to co sa bude zobrazovat, ale ukladat sa stale bude tableId.
Mne osobne dava zmysel identifier `[Component Icon] Component Name/ Config Name/ Table Name` vid mock stranky jobu:
![image](https://user-images.githubusercontent.com/1412120/30578080-52683c5c-9d12-11e7-88aa-549644395811.png)

**Comment by ondrejhlavacek** [comment]
Ještě by bylo super, kdyby ten config byl klikací taky :-)

**Comment by ujovlado** [comment]
Celkom sa mi to paci, ale myslim, ze to sedi len na Transformacie. Vo ostatnych joboch (extractory, writery a pod. tam bude potom asi stale ta ista ikonka, nie?) - teda ak spravne chapem, ze ikonky maju byt kvoli tomu aby som vedel odkial to je.

Ta dalsia vec, ze jeden riadok bude vlastne zlozeny z 3 odkazov mi pride dost matuca. Napr. zrovna tu (ako je screenshot) by to znamenalo, ze su tam 3 odkazy (ktore vyzeraju ako jeden) a podla toho ci klikenm vlavo/vpravo/na stred ma to presmeruje inde. To by bolo este treba premysliet.

**Comment by kacurez** [comment]
U extraktorov to moc zmysel nedava ale u jobov writeru to imho naopak dava zmysel - vidis vystup ktorej transformacie sa niekam posiela..to iste pre apky ako napr geneea. Dalej by sa to mohlo hodit v samotnych konfigoch writerov/transformacii/apiek. 

stymi odkazmi suhlasim ze by to trebalo premysliet, preto to tu pisem :)

**Comment by pivnicek** [comment]
I may have made a duplicate https://github.com/keboola/kbc-ui/issues/1127

**Comment by kacurez** [comment]
to myslim ze sa riesi v ramci novej konzoli tak tu to zatvorim
