### ISSUE TITLE
Tune "Deprecated components" and "Over quota" styles

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1158]
Debatovali sme s Jackom a vzislo z toho este par uprav:

- [x] Zvacsit riadkovanie
- [x] Upravit "hover state"
- [x] Zarovnanie (tu myslim mozeme zatial zvoli kompromis a spravit to konzistentne so zvyskom UI - t.j. kludne paddingy podla tej spodnej casti)

Potom sme sa este dohodli, ze by sa upravil background na jednotlivych castiach.

- [x] Uprava backgroundu

---

Zarovnanie:
![kbc-ui-v1 2017-09-20 11-45-20](https://user-images.githubusercontent.com/419849/30653244-ddd99ec0-9e2a-11e7-889c-4e3c69dfb066.png)

Riadkovanie:
![syrup - overview 2017-09-20 11-53-17](https://user-images.githubusercontent.com/419849/30653322-1374a8ea-9e2b-11e7-8719-18cb0faa9357.png)

Hover state:
![kbc-ui-v1 2017-09-20 11-54-04](https://user-images.githubusercontent.com/419849/30653332-19b6196e-9e2b-11e7-8909-e8c05c7ddd3f.png)

**Comment by ujovlado** [comment]
A uprava backroundu:
![screenshot_2017-09-20_17-47-47](https://user-images.githubusercontent.com/419849/30653624-dc18ac60-9e2b-11e7-8f1b-e5762bd1da6b.png)

Je to aj v Invision.

**Comment by janmichek** [comment]
@ujovlado tady to mam hotove, zkoukni to prosim. Checknul jsem se na to na vice projektech i na vice detailech komponent.
+ jsem pridelal styl migration row jak jsme resili https://projects.invisionapp.com/d/main#/console/11550405/254315208/preview

**Comment by ujovlado** [comment]
ok, kuknem to ... ten migration row som ale myslel, ze doriesim tu: https://github.com/keboola/kbc-ui/issues/1160, neva

**Comment by janmichek** [comment]
moment, jeste nemerguj, koukam ze mi unikla jeste jedna vec ... hned to bude

**Comment by janmichek** [comment]
poreseno
