### ISSUE TITLE
Job Error Message Typos

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1159]
![image](https://user-images.githubusercontent.com/497675/30681305-2dfc8ab4-9ea5-11e7-87f4-658b71cee4fe.png)

Status, Message, Exception ID

**Comment by ondrejhlavacek** [comment]
Je to uložený u jobu, budem muset zjistit, jak se to tam dostalo.

**Comment by ondrejhlavacek** [comment]
souvisí s https://github.com/keboola/transformation-bundle/issues/82

**Comment by MiroCillik** [comment]
Fronta tam ulozi output toho processu https://github.com/keboola/syrup-queue/blob/master/Strategy/LegacyStrategy.php#L96

Takze teoreticky, keby ten output bol json, mohol by sa najprv spracovat a potom ulozit do Jobu tak ako pri "normalnom" skonceni jobu:
https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L222

**Comment by ujovlado** [comment]
Zatvaram, toto nie je issue UIcka ;)
