### ISSUE TITLE
transformace - nejde editovat desc transformace

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#116]

**Comment by ondrejhlavacek** [comment]
přes  http://docs.keboolatransformationapi.apiary.io/#put-%2Ftrasformation%2Fconfigs%2F%7BbucketId%7D%2Fitems%2F%7BtransformationId%7D%2F%7Bproperty%7D

**Comment by Halama** [comment]
edituje se v rámci celé transformace
