### ISSUE TITLE
Indicate when query is not valid and cannot be saved

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1172]
Mozno nieco taketo?

![peek 2017-09-25 20-46](https://user-images.githubusercontent.com/419849/30825377-09ab8a48-a233-11e7-9389-eca2d277989f.gif)

**Comment by Halama** [comment]
to mi mozna prijde az moc takovy "agresivni". co to jenom napsat nejak vedel toho save buttonu?

**Comment by ujovlado** [comment]
no je to kus naprd, lebo to mas v podstate cely cas cervene ... skusim este to co pises

**Comment by ondrejhlavacek** [comment]
To, že to nejde uložit, není chyba query, ta se nijak nevaliduje. Je to chyba v regexu, že nedokáže tu query zpracovat. Předpokládám
a) že se to děje jen u SQL, který nedává smysl
b) a že uživatel nesmyslný SQL ukládat nechce
tak jsem to ignoroval a jenom jsem disabloval Save button, protože to uložit nemůžeme (ukládají se splitnuté query). K tomu můžem napsat jenom něco ve smyslu *We're unable to process this query*, o validnosti nemůže být řeč.
