### ISSUE TITLE
Bring back "sticky buttons" for queries edit

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1177]
Looks like it was accidentally removed in #902

**Comment by ondrejhlavacek** [comment]
please no sticky buttons!

odstranil jsem je, protože na stránce může bejt víc rozeditovanejch polí naráz a to s konceptem sticky buttons nejde dohromady.

**Comment by ujovlado** [comment]
A kde mame taky pripad, ze ich je tam viac? Tak potom ich vyhodme odvsadial.

Ale zrovna na queries edit sa to imho hodilo ...

**Comment by ujovlado** [comment]
No ono to tak prave bolo:
![screenshot_2017-09-26_17-39-35](https://user-images.githubusercontent.com/419849/30869541-b454d43c-a2e1-11e7-95a1-75ca48c71d1a.png)

Je to trosku omrd spravit to spravne, no myslim, ze posledne sme k tomu boli blizko. :)

**Comment by ondrejhlavacek** [comment]
Tenhle myslím zůstával vidět i když textarea zmizela. Byl fixovanej pomocí `position: absolute; top: 70px;` vzhledem ke kontejneru appky, ne toho kontejneru s CodeMirrorem.

**Comment by ujovlado** [comment]
Jo, to sa da doladit, uz to vidim:
![screenshot_2017-09-26_17-41-33](https://user-images.githubusercontent.com/419849/30869736-3ccff35a-a2e2-11e7-9dcc-d8ee04a4523c.png)

**Comment by ondrejhlavacek** [comment]
Podíval bych se, jestli třeba na to není nějaký lepší řešení - může se scrollovat v té textaree, může tam bejt tlačítko, co sbalí/rozbalí textareu, abys dosáhl na tlačítko...

**Comment by ujovlado** [comment]
Scroll v textarea som akurat kukal, ma to tak Github. To by sme vedeli spravit hned. Nerozbije to ale potom linkovanie na konkretne queries (scrollovat v textarea na konkretny riadok moze omrd)

**Comment by Halama** [comment]
chybelo to nekomu?

**Comment by ondrejhlavacek** [comment]
Vladovi? :-)

**Comment by ujovlado** [comment]
Nie nie, ide mi len o konzistenciu - nech to nie je raz tak a raz tak. Vsimol som si to nahodou, ked som prechadzal stare issue a doplo mi, ze som to tam nevidel, kde som vcera riesil bug s tymi queries :)

**Comment by ujovlado** [comment]
Kludne to vyhodim zo zvysnych miest v dalsom PR, vratane kniznice ;) ok?

**Comment by ujovlado** [comment]
Dalsia vec je, ze mame tie save buttony nad formularmi, co je tiez pekny mindfuck :-D A ak by bol dole, mozno nemusime riesit sticky buttons, ked nad tym uvazujem.

**Comment by ondrejhlavacek** [comment]
To bych řešil asi bokem a case by case. Můžou bejt buttony na obou místech třeba.
