### ISSUE TITLE
Broken event list layout (text overflow)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1182]
Zda sa mi, ze toto sme nemali rozbite

![screenshot_2017-09-27_21-33-56](https://user-images.githubusercontent.com/419849/30933759-c651e054-a3cb-11e7-8f4f-ea800f29897c.png)

**Comment by Halama** [comment]
jj mam pocit ze se tam neco trochu zmenitlo, imho ani ty paddingy kolem te event tabulky nebyly tak velke

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/30933936-50031d40-a3cc-11e7-9b7f-2e10dcb4e915.png)

**Comment by janmichek** [comment]
postaram se o to

**Comment by janmichek** [comment]
_ s tim text overflow to je snadny - uz mam fix, jeste to testuju.
- se zarovnanim, tam bude asi vic prace, zatim to moc neštimuje. 
Souhlas, že předtim bylo to zarovnání jiné, protože byl špatně použitý bootstrap (.col bez .row) tak jsme na to byli zvyklí jak to vypadá s tou chybou. Chce to pojmout nějak globálněji a vyscreenovat víc stránek. 
![image](https://user-images.githubusercontent.com/15363559/31618729-0cb166f2-b293-11e7-9386-20224096c672.png)
