### ISSUE TITLE
Get rid of job IDs

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1187]
Related to: https://github.com/keboola/kbc-ui/pull/1183, comment: https://github.com/keboola/kbc-ui/pull/1183#issue-261590443

---

Chceme sa zbavit v UI vsetkych IDckiek jobov. Tak ako bolo pisane v tom issue vyssie, neprinasa to ziadnu info. Co zatial nemame je iny identifikator jobu, no asi ho ani netreba a bude stacit zmenit poriadie stlpcov.

### job list - standard
![screenshot_2017-10-04_09-40-19](https://user-images.githubusercontent.com/419849/31164743-b332d13c-a8e8-11e7-91ee-a9bc328c8b5f.png)

### job detail - standard
![screenshot_2017-10-04_09-40-57](https://user-images.githubusercontent.com/419849/31164754-bed5ae7e-a8e8-11e7-9f77-788cafbed2bd.png)

### job list - orchestracie
![screenshot_2017-10-04_09-42-05](https://user-images.githubusercontent.com/419849/31164767-c8b99e0a-a8e8-11e7-8f00-d62f90c81331.png)

### job detail - orchestracie
![screenshot_2017-10-04_09-42-55](https://user-images.githubusercontent.com/419849/31164779-d594e77e-a8e8-11e7-872d-2c0381fa2d9b.png)

### recent jobs - komponenta (vpravo v detaile)

![screenshot_2017-10-04_09-43-40](https://user-images.githubusercontent.com/419849/31164791-e3dcad58-a8e8-11e7-858c-32d5807e2e07.png)

**Comment by ujovlado** [comment]
Ako problemove vidim:

- detaily jobov (zatial neviem, co by sme dali namiesto IDcka)
- detail jobu v orchestraciach - panel vlavo ... ak zmizne ID uz tam toho moc neostane

**Comment by ujovlado** [comment]
cc: @jancermak

**Comment by ujovlado** [comment]
Viem si predstavit, ze pre list jobov, by to stacilo preusporiadat:

###  job list - standard

![screenshot_2017-10-04_09-54-14](https://user-images.githubusercontent.com/419849/31165119-1d38db48-a8ea-11e7-9555-045e0bf2c14d.png)

### job list - orchestracia

**Comment by ujovlado** [comment]
Panel vlavo, v detaile orchestracie by sa dal vyriesit takto:

![screenshot_2017-10-04_10-05-59](https://user-images.githubusercontent.com/419849/31165518-b2cf7738-a8eb-11e7-90a9-ed0c5e11baa8.png)

**Comment by ujovlado** [comment]
No a "recent jobs - komponenta (vpravo v detaile)" je myslim cajk, tam staci vyhodit to id, ako bolov povodnom issue.

**Comment by Halama** [comment]
Kdyz jsem si  s tim hral tak jsem to ID v detailu jobu nechaval ale mozna to je blbost no.

**Comment by Halama** [comment]
Stejne to delame napr. v eventech v seznamu jeji id neukazujeme ale v detailu jo.

**Comment by ujovlado** [comment]
@Halama s tym eventami je to dobry postreh, tak to mozeme dat rovnako, bude to aspon konzistentne. To IDcko asi v detaile dava vyznam (proste ked sa ta "entita" zaujima, si v jej detaile a mas viac info).

Takze to mozem hned upravit ako pisem v https://github.com/keboola/kbc-ui/issues/1187#issuecomment-334078660 a https://github.com/keboola/kbc-ui/issues/1187#issuecomment-334080219 ... a ak Jack pride s dalsim vylepsenim, mozeme pridat ;)

**Comment by ujovlado** [comment]
@jancermak zatial sme to vyhodili len zo zoznamov a malicko preusporiadali ... v detailoch to asi zatial ostane  tak ako piseme v https://github.com/keboola/kbc-ui/issues/1187#issuecomment-335014628

**Comment by janmichek** [comment]
Souhlas ze to zbytecne zabira misto.
Uzivatelsky me napada ... nevyhledava nekdo podle IDs?
Napada me treba ID nezobrazovat, ale mit moznost podle nej porad vyhledavat.

**Comment by odinuv** [comment]
pokud je vyhledani jobu potreba jen k tomu, abysme se dostali na detail konkretniho jobu, tak by se to asi dalo resit jinak
