### ISSUE TITLE
KBC v EU - Storage konzole a importní joby

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1190]
V EU neukazuje Storage konzole u importního jobu odkaz na data v S3 
![image](https://user-images.githubusercontent.com/1427901/31246480-cd5642c6-aa0d-11e7-8336-3ff524ffb1e6.png)

Zkouším to na tabulce z MySQL Extraktoru [zde](https://connection.eu-central-1.keboola.com/admin/projects/19/storage#/tables/in.c-keboola-ex-db-mysql.Games).

**Comment by Halama** [comment]
Potvrzuju chování. Vypadá to to na backend issue file storage.

**Comment by Halama** [comment]
Fixnuto, objeví se i zpětně ty nalinkované soubory.
