### ISSUE TITLE
Test credentials glitch

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1196]
Test credentials se nějak změnilo a přijde mi to dost hnusný. Předím tam nic neskákalo, ted když to spustím tak to odskočí a nad tím se objeví ten loader.
![oct-08-2017 13-26-31](https://user-images.githubusercontent.com/903531/31316383-59fa896a-ac2c-11e7-845a-765afe67749d.gif)

**Comment by ujovlado** [comment]
To odskocenie som si neuvedomil, ale ze by to kvoli tomu bolo extra hnusne si nemyslim :)

Mozem to fixnut dvoma sposobmi:

- dam ten loader a message pod buttony (podobne to vlastne bolo predtym)
- alebo nahradim buttony pocas loadovania tym loaderom (co by imho bolo spravne chovanie, lebo stejne su pocas loadovania/cakania ako disabled)

**Comment by Halama** [comment]
Me to hned prastilo do oci uz poprve kdyz jsem to zkusil ale nestihl jsem dat issue.
Imho by to nemelo skakat kdyz to neni nutne. Mozna by tam jenom mohl byt pripraveny prostor na ten loader a status a bude to ok?

**Comment by Halama** [comment]
V Lookeru se to hodi pod to jak jsme to meli predtim tak bych to tak asi nechal.
To nahrazeni buttonu loadere/vysledkem se na to imho nehodi protoze pak to budes chtit treba pustit znova atd.

**Comment by ujovlado** [comment]
Ok, tak to dam pod. S tym druhym riesenim by bola vacsia piplacka, lebo by sme museli checkovat kedy form dirty a pod, jo ...
