### ISSUE TITLE
Move "tokens" section to "User & Settings" section, under new tab.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1201]
Mala by pribudnut nova polozka do "settings menu", tokens:

![screenshot_2017-11-13_22-08-42](https://user-images.githubusercontent.com/419849/32749313-4c7ff950-c8bf-11e7-86d3-545adde573f0.png)

Spravil by som to na niekolko casti (idealne samostatnych PRs) a posledna cast bude obsahovat aj zobrazenie polozky v menu.

### 1. Zoznam tokenov

- Tabulka, kde je zoznam vsetkych tokenov
- Mali by tam by stlpce: name, created, expires, can read all files a component access (`full` alebo `custom`) a bucket permissions (`full` alebo `custom`)
- Akcie nad tokenom (stlpce na konci): refresh tokenu, zmazanie tokenu (pripadne aj skopirovanie) a link na detail (co moze byt asi modal)
- Hore nad tabulkou vpravo zeleny button na pridanie tokenu
- Super by bolo tiez pridat label `yours` k mojmu "master" tokenu aby si hned vedel, ktory mas hladat, ked ho ides kopirovat

### 2. Pridanie tokenu

- To moze byt vlastne ako doteraz
- Co ma tam ale sere je, ze v tom modale je zoznam bucketov (to vieme spravit imho lepsie, napr. nejako po jednom alebo tak) - myslim si, ze bud das niekomu full alebo vyberes par bucketov.

### 3. Detail tokenu

- Spravil by  som to cez modal (po kliknuti na btn detail v "akciach")
- Po otvoreni modalu by si videl nazov tokenu, jeho detaily (tie veci z riadku) a navyse bucket permissions a pripadne aj component access ak nejaky bol a nie je `all`

---

Veci, co som si nie isty:

- Eventy tokenu. Chceme ich? Imho to sluzi skor na debug.
- Send token. To vobec neviem posudit ako velmi a ci sa to pouziva.

**Comment by kacurez** [comment]
tu to by som si zobral, +- mi to je jasne, ci este nieco treba vediet k tomu?

**Comment by ujovlado** [comment]
updatnem popis toho issue a ked tak to predebatujeme :)

**Comment by ujovlado** [comment]
@kacurez popis updatnuty ... zajtra sa mozeme k tomu pobavit viac ked tak

**Comment by kacurez** [comment]
mne to je nateraz jasne, nepride mi zeby sme tam bolo treba nieco predebatovat. Ale ak myslis ze treba tak kludne mozme, inac to teda zacnem implementovat a ked sa seknem na niecom tak sa ozvem ;)

**Comment by ujovlado** [comment]
Ok, tam som si nie isty tymi 2 vecami (send token a eventy). To ale staci na konci.

**Comment by ujovlado** [comment]
Jo, este som zabudol, ze idealne ked to bude vlastny "modul" so svojim store a pod. Nedratoval by som to do `limits` alebo tak.

**Comment by kacurez** [comment]
si poznacim co sample dat:
![image](https://user-images.githubusercontent.com/1412120/32787616-46e8df0a-c957-11e7-9354-037e7cb9a50d.png)
