### ISSUE TITLE
IO Mapping modals - autofocus

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1205]
První položka by se měla automaticky zafocusovat abych mohl rovnou vybírat, to by mělo platit pro všechny modaly. Takhle je to hrozně otravný.

![oct-11-2017 09-38-04](https://user-images.githubusercontent.com/903531/31427544-f2001670-ae67-11e7-83bc-9849e4a4ee09.gif)

**Comment by janmichek** [comment]
@ujovlado o tohle se muzu postarat. Pripadne me prihod k issue
