### ISSUE TITLE
Project Overview - expiration info is missing

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1212]
Project is expiring tomorrow, but overview page has no info about it (https://monosnap.com/file/9mUuvKugXaPxKi4nPQs0teoFLu1fTO).

**Comment by Halama** [comment]
potvrzuju. @MiroCillik nezmizelo to s tema upravama co si tam delal kvuli deprecated komponentam?

**Comment by MiroCillik** [comment]
@Halama nemyslim si, ale pozriem na to!

**Comment by MiroCillik** [comment]
Spis to bude tymito podmienkami tu https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/home/react/Index.jsx#L76

**Comment by janmichek** [comment]
ups, tak to pujde asi za mnou... poresim co nejdriv

**Comment by janmichek** [comment]
opraveno.
+ jsem revertnul i styly tech background icon. @ujovlado psal si ze pro jistotu prekopavas pouziti "calc" v background-size. Jsem si jistej ze je to cisty reseni, vracim to zpatky.  Koukam na to ve FF i CHrome a nicemu to nevadi.

**Comment by ujovlado** [comment]
> Jsem si jistej ze je to cisty reseni, vracim to zpatky. Koukam na to ve FF i CHrome a nicemu to nevadi.

@janmichek ked to vsade funguje, tak super. Viem ale, ze posledne som riesil s @kacurez problem, ze `calc` nefungovalo dobre v Safari. Navyse, `background-position: calc(~"100% - 27px") 28px` mi prislo zbytocne komplikovane, ked mozem spravit padding a backgrund jednoducho (`0 100%`) zarovnat doprava.
