### ISSUE TITLE
Duration of cancelled jobs in orchestration is still counting

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#1223]
![job 325242796 2017-10-20 09-29-06](https://user-images.githubusercontent.com/215660/31809718-2e7c7e28-b579-11e7-97d8-65d225a42e25.png)

**Comment by janmichek** [comment]
@JakubMatejka Zatim to nemuzu potvrdit, chova se to dle ocekavani. CHvilku jsem s tim experimentoval, chybu se mi nedarilo replikovat. Jakej je vlastne rozdil mezi 'cancelled' a 'terminated'? Orchestraci o stejnym vysledku statusu se mi zatim nepovedlo provest. Indicie vitany.

**Comment by JakubMatejka** [comment]
Nevím, no. Taky se mi to nedaří moc nasimulovat. Ale našel jsem ten původní případ a řekl bych, že se to tam pořád točí? (akorát že je tam "more than 24 hours", tak už se to na pohled nemění): https://connection.keboola.com/admin/projects/1322/orchestrations/197339732/jobs/325242796 Ten rozdíl mezi cancelled a terminated úplně jistě nevím. ;o) Zkus se zeptat ve Slacku v #docker-runner ;o)

**Comment by janmichek** [comment]
@JakubMatejka  Nevim, jestli jsem na to ten nejpovolanejsi, ale budiz. Hele a normalne do toho projektu muzu vlizt, jo? Co tam mam uvest jako reason?

**Comment by JakubMatejka** [comment]
Hele, zřejmě je to dost edge case, klidně to tu zavřeme než se ozve někdo další.

**Comment by odinuv** [comment]
asi by bylo dobry podivat se jestli neni neco atypickyho v tom jobu, ja nevim podle ceho to UI posuzuje ze ma prestat pocitat, ale mozna to tam chybi. Me to normalne dela, ze to pri terminovani pocita cas a pak se to vrati (jakmile pochopi, ze ten job uz je mrtvej)

**Comment by odinuv** [comment]
tj, tim jsem chtel rict, ze to neni podle stavu, ale podle neceho jinyho mozna `isFinished` ?

**Comment by kacurez** [comment]
imo by to chcelo nerendrovat Duration v pripade ze job je cancelled:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/orchestrations/react/pages/orchestration-job-detail/JobTasks.coffee#L59

problem bude mozno tu:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/react/common/Duration.coffee#L50
ak neni zadany endtime(co u takto terminovanych jobov asi neni) tak to stale pocita.

**Comment by natocTo** [comment]
Koukám toto se již neděje. "Total Duration" se mi zastavilo po ukončení jobu.
