### ISSUE TITLE
S3 extraktor a hlavičky

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1228]
Bych dost potřeboval, aby S3-ex uměl importovat data, co nemaj hlavičky. Restbox to dělal tak, že si stáhnul tabulku ze SAPI a použil její hlavičku. Celkem bych to i dělal tak, že hlavičku definuju v cfg extraktoru. :-*

**Comment by ondrejhlavacek** [comment]
Procesor, co naleje hlavičky do manifestu nebo použít https://github.com/keboola/processor-headers

**Comment by ondrejhlavacek** [comment]
closed by https://github.com/keboola/processor-create-manifest
nasadí se to s novým UI
