### ISSUE TITLE
Bug Copying a Transformation Bucket

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1233]
http://recordit.co/jWfunf7pKE

Transformation > Bucket > Versions
Copy To New Configuration
Go To The New Configuration

**Comment by ondrejhlavacek** [comment]
Nedaří se mi to nasimulovat lokálně

**Comment by ujovlado** [comment]
Myslim, ze je to preto, lebo `INSTALLED_COMPONENTS_CONFIGSDATA_LOAD_SUCCESS` dobehne az po `ROUTER_ROUTE_CHANGE_SUCCESS` ... 

No a tu sa snazime nacitat title:
https://github.com/keboola/kbc-ui/blob/3457cbe52f6cc5627337e3eb8d752c4a95910196/src/scripts/modules/transformations/Routes.coffee#L44

Nasimulovat sa to da tak, ze si nastavis Network Throttling v chrome. (napr. na 10kb). Potom sa to deje aj lokalne ;)

![screenshot_2017-10-27_19-27-11](https://user-images.githubusercontent.com/419849/32116952-d914112e-bb4c-11e7-9353-da8c3e128775.png)

**Comment by ondrejhlavacek** [comment]
@ujovlado jasny, je to tak. Už jsem na to pakrat narazil. Co bys navrhoval? Asi jediný vhodný mi přijde serializace těch requestů.

**Comment by ondrejhlavacek** [comment]
Ah, to už tam je a bylo tam typo!
