### ISSUE TITLE
gdwr - přiřazení datumové dimenze ke sloupci

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#124]
Nebylo by lepší udělat tu tabulku klikací a po kliknutí dimenzi rovnou vybrat? (tzn. oddělat sloupec Selected a tlačítko Choose)

![development_-_table_out_c-test_ciselnik_cenik3](https://cloud.githubusercontent.com/assets/215660/8105639/1fc737e6-103b-11e5-962c-5551e7e107b1.png)

**Comment by Halama** [comment]
Zatím jsem alespon pofixoval to rohozený radio
![image](https://cloud.githubusercontent.com/assets/903531/8106519/3c8b50ea-1042-11e5-914c-67e1346f551f.png)

Ten výběr rovnou klikem by asi šel ale nějak ozačené která je zrovna přiřazená by tam taky mělo jít vidět. Můžeš to měnit.

**Comment by Halama** [comment]
dělám čistku, zatím zavírám
