### ISSUE TITLE
Nastavení nových "change since" v mappingu

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1247]
Crashl mi load do Snowflake na chybě ([job](https://connection.eu-central-1.keboola.com/admin/projects/19/jobs/186851)) 

```
Cannot set both parameters 'days' and 'changed_since'.
```

Tak to zkoumám hlouběji a našel jsem tohle ([tabulka](https://connection.eu-central-1.keboola.com/admin/projects/19/writers/keboola.wr-db-snowflake/169145/table/in.c-keboola-ex-db-mysql.countries)):

![image](https://user-images.githubusercontent.com/1427901/32315446-6ee8c916-bfac-11e7-8375-298b6facf6f5.png)

Po rychlém klikání jsem přišel na to, že se UI nechce vzdát těch předchozích nastavení a "1 day" tam prostě bude i kdyby trakaře padaly :) Tady je video: http://take.ms/Yc9TV

**Comment by ondrejhlavacek** [comment]
tohle jsem přesně řešil, co to je za komponentu? Snowflake writer?

**Comment by padak** [comment]
Ano! Snowflake Writer.
