### ISSUE TITLE
Refactor Index component

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1248]
`src/scripts/modules/home/react/Index.jsx`

Ked som sa v tom trosku vrtal, je to tam trosku sprasene s tymi states. Mixuje sa tam `initial state` a `state from stores`. ~Takisto je tam myslim naprd `componentDidMount`, lebo tu poskytuje mixin (podobne aj `inital state`).~

**Comment by janmichek** [comment]
Mas nejaky odkaz na 'best practices', abych treba vedel co se pouziva na co? Me to moc nerika a urcite bych to pouzil spatne kdybych psal neco noveho?

**Comment by janmichek** [comment]
@ujovlado

**Comment by ujovlado** [comment]
Som sa unahlil (vid updatnuty komentar), lebo som tam nieco potreboval dorobit a hadzalo to kopec warningov. :roll_eyes: 

Uz sme to za ten mesiac kus pomenili a vlastne je tam divne len ze `initial state` nacitava zo stores -> lepsie je ked je to v `state from stores`. To fixnem hned.

Best practices su rozne, da sa zacat v nasom readme:
https://github.com/keboola/kbc-ui#react-components-best-practices
