### ISSUE TITLE
gdwr - divný řazení sloupců v detailu tabulky

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#125]

**Comment by JakubMatejka** [comment]
Ono je to ještě jednou v "name", pokud bys to mohl seřadit podle toho (dokonce je to tam snad kvůli tomu javascriptu):
![gooddata_writer_paw](https://cloud.githubusercontent.com/assets/215660/8106571/a07fd33c-1042-11e5-9bbf-6ef58849a016.png)

**Comment by Halama** [comment]
to mi právě ale moc nepomůže, v moment kdy to iteruju už to je rozházený, pomohlo by tam číslo pořadí.

**Comment by Halama** [comment]
ještě to teda prozkoumám

**Comment by Halama** [comment]
tak ještě ne uplně ale vyřeším to na frontendu :)

**Comment by JakubMatejka** [comment]
To číslo s pořadím tam dát můžu, to není problém. (myslíš jako `order: 0` atd., jo? Nebo do klíčů toho pole?)

**Comment by Halama** [comment]
Už je to vyřešené celé, nakonec se to nějak povedlo, takže to už není potřeba. díky
