### ISSUE TITLE
Show particular query in MySQL extractor error 

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1250]
Když padne extrakce z MySQL na chybné query, bylo by super vědět, o jakou se jedná. Jinak musí člověk do jobu a hledat nejbližší předchozí event, kdy se nějaká query pouštěla.
![job 328348323 2017-11-04 10-43-54](https://user-images.githubusercontent.com/12933713/32404300-765d1808-c14d-11e7-8245-1aa673b84a25.png)

**Comment by pivnicek** [comment]
Cheers @Matejkys ,  there is an issue for this here: https://github.com/keboola/db-extractor-common/issues/23  so I'll close this one.  Thanks for the report!

**Comment by pivnicek** [comment]
@Matejkys just FYI, the mysql extractor has been updated now to display the query name in the failure messages.
