### ISSUE TITLE
Incremental load vs date filter u SNFLK writeru

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1251]
Eva z Gamee opakovaně přeskakuje date filter ve Snowflake Writeru. Efekt je, že dělá vlastně full loady a zbytečně jí to trvá:
![image](https://user-images.githubusercontent.com/1427901/32413582-8a88f4ec-c214-11e7-80b5-ec81a8f12592.png)

Chodím a přenastavuju to po ní na 
![image](https://user-images.githubusercontent.com/1427901/32413587-9924611c-c214-11e7-9f11-454afcaef9bc.png)

Nenapadlo by tě, @kacurez , jak to spojit dohromady, aby při nastavení inkrementálního zápisu vybíral user i date filter?

**Comment by padak** [comment]
úplně nejlepší by samozřejmě bylo, kdyby si to ten rozdíl našlo samo - tady se do toho nemotají žádný sandboxy a bordely - prostě když to bylo naposledy spuštěný včera v 10 a doběhlo to OK, tak chci přírůstky za období "now()-včera v 10".

**Comment by kacurez** [comment]
Mne pride ze s Incrementalnym zapisom vzdy nastavujes 3 resp. 2 veci: 
0. Incremental checkbox
1. Primary Key
2. Date Filter

Napada ma zjednodit tieto 3 veci do jedneho formulara ktory by sa otvoril po kliku na `Setup Incremental Write` button.

Inac suhlas ze by to mohlo byt automaticky resp adaptivne, je to popisane v PB ake featura docker runneru:
https://keboola.productboard.com/inbox/features/100882/detail
