### ISSUE TITLE
Errored orchestration but transformation still in processing state.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1252]
![screenshot_2017-11-05_12-11-30](https://user-images.githubusercontent.com/419849/32414241-c4c94694-c222-11e7-96d3-db29c2a7bc18.png)

**Comment by ujovlado** [comment]
Transformation phase remained in "processing" but job itself ended with success.

**Comment by Halama** [comment]
We should get rid off this jobs caching with new orchestrator. I am for won't fix now.

**Comment by ujovlado** [comment]
Ok, I'll leave it as is.
