### ISSUE TITLE
(EU) CSV Import: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1255]
Cannot upload CSV files in EU

![image](https://user-images.githubusercontent.com/497675/32540457-0c95cc6c-c46d-11e7-8c7b-dc87f168ae6f.png)

**Comment by Halama** [comment]
Myslím si že to bude o nastavení to S3 klienta v UI.

**Comment by ondrejhlavacek** [comment]
jj, už to mám hotový

**Comment by ondrejhlavacek** [comment]
`signatureVersion: v4` funguje ve všech regionech
