### ISSUE TITLE
Add refresh button

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1260]
In case I just added few tables (e.g. in my src db), there can be a refresh button.

![screenshot_2017-11-09_16-38-40](https://user-images.githubusercontent.com/419849/32614066-ae968fd8-c56c-11e7-8ebb-46b6a8e9aef0.png)

Related to #1097

**Comment by ujovlado** [comment]
It's a minor thing, but it can help in few cases. We can discuss it later. (after main issue is merged)

**Comment by pivnicek** [comment]
Good idea!

**Comment by ujovlado** [comment]
Proposal:

![screenshot_2017-11-10_12-08-34](https://user-images.githubusercontent.com/419849/32655891-eb94b72c-c60f-11e7-92a7-b78d0762a22b.png)

**Comment by Halama** [comment]
tvl, ten zelenej reload teda nevim :)

**Comment by ujovlado** [comment]
To doladime :) Mozno by stacil text "Reload"

**Comment by pivnicek** [comment]
could be a simple link in the help text.  It won't be necessary very often, so doesn't need to be so prominent.

treba:
```
Select the tables you'd like to import to autogenerate your configuration.
You can edit them later at any time.  Not seeing your newest tables? (Reload) the tables list.
```
