### ISSUE TITLE
Remove "go back to list of tables" btn?

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1263]
We discussed at offsite, that this button should be removed.

![screenshot_2017-11-09_20-59-28](https://user-images.githubusercontent.com/419849/32626989-3c1572ec-c591-11e7-90c1-a8f1f33fcbfa.png)

- It's a pattern which we do not use anywhere in UI.
- There's already a navigation in header (breadcrumbs)

Related to: #1161

**Comment by pivnicek** [comment]
I agree with @Halama's comment here https://github.com/keboola/kbc-ui/pull/1097#issuecomment-335813499 that best would be to redirect to index on credentials save
