### ISSUE TITLE
New DB ex - UI glitch

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1264]
Pro zadání credentials vyžaduje extraktor zadat jméno databáze (já ji například neznám přesně z paměti). 
![image](https://user-images.githubusercontent.com/1427901/32631831-bdb8ec60-c5a1-11e7-915a-6d59952e2769.png)

Když ji zadám, můžu uložit credentials a pak mě to nabídne vylistovat tabulky ze všech dostupných databází:
![image](https://user-images.githubusercontent.com/1427901/32632000-48978026-c5a2-11e7-8ca6-be5d829c9407.png)

Tohle je "pat" a to pole "Database" bych udělal nepovinné.

**Comment by pivnicek** [comment]
Going to make the database parameter optional, as requested: https://github.com/keboola/db-extractor-mysql/issues/19

If it is not set, there should be a warning in the SQL editor in advanced mode that specifying schema is required when no database parameter supplied.
