### ISSUE TITLE
Ex Google drive - non-consistent list ui

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1269]
Ukazuje to takovouhle divnost:
![image](https://user-images.githubusercontent.com/903531/32662891-562a2e66-c62c-11e7-959c-9d25258ab50d.png)

Mělo by vypadat jako tady:

![image](https://user-images.githubusercontent.com/903531/32663002-b8ee9faa-c62c-11e7-8049-c9497e33d75b.png)

**Comment by ujovlado** [comment]
Fixed in #1286 

![screenshot_2017-11-16_20-36-44](https://user-images.githubusercontent.com/419849/32911911-e1924e62-cb0d-11e7-9be8-4e6c16f5e7f7.png)
