### ISSUE TITLE
Menu uživatele

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#127]
![image](https://cloud.githubusercontent.com/assets/1427901/8108496/0b3144e6-1051-11e5-93a6-538d92617a89.png)

**Comment by Halama** [comment]
jedna ze 2 věcí co čeká na dostylování

**Comment by Halama** [comment]
Máme nakresleno:
![image](https://cloud.githubusercontent.com/assets/903531/8333241/6e8c0846-1a92-11e5-97d5-81ee336e5306.png)

**Comment by Halama** [comment]
@JakubMatejka o zprovoznění se pak asi postarám až bude nařezáno
