### ISSUE TITLE
Tune guide mode (part 2)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1271]
Doriesit:

- [ ] L1, L4, L5 konci whitescreenem 
- [ ] L4 - udelat vizualizaci vysledku / interaktivni graf
- [ ] prozkoumat co se da udelat s 'prechody' aby to nebylo tak vizualne trhany 
- [ ] animace step next/back
- [ ] predat Jackovi k validaci UX a priprave user testovani
- [ ] odstranit nebo vylepsit 'Buttonlike' featuru
...
- [x] prechod 3.5 -> 3.6 zpusobi error
- [x] doublechecknout errory v Sentry 
- [x] prepinanie kroku s5 hadze nejaky error `charAt`
- [x] storage events - fix pretekani obsahu [1366x768]
- [x] dodat schemata od Hanky / Jacka
- [x] zmensit padding-top textu na guide-desk
- [x] L2 prilis vysoky intro obsah, nevejde se na 1366x768
- [x] zavretie modalu zo sekcie storage (hodi to err, lebo v storage nie je router)

**Comment by janmichek** [comment]
jenom Technicka: Muzem to odted nazyvat "Guide mode" ? at to neni takova schyza. Mame co jsme chteli, ne? .)

**Comment by janmichek** [comment]
prislusna vetev zde -> https://github.com/keboola/kbc-ui/tree/tune-guide-mode-part2

**Comment by janmichek** [comment]
TESTNOUT PO MERGI DO PRODUKCE
- [ ] zavretie modalu zo sekcie storage

**Comment by janmichek** [comment]
@ujovlado prosimte jsem trochu zaseklej na par vecech ohledne routovani.
Tocim se kolem toho ze v devu to routuje a provadi stepama ok, bez chyb v konzoli.
Potom na ostry to crashuje v urcitejch mistech. Nenapada me lepsi napad nez testovat a pushovat zmeny hned na produkci. Na devu nepoznam co pak bude / nebude fungovat.
Konkretni dotaz: nevim jak routovat na zakladni stranku RoutesStore.getRouter().transitionTo('home'); - kdyz dosdim 'home',  '/', nebo '' tak to bud nefunguje, nebo funguje s errorem.

Konkretni dotaz 2: prechod z kroku 3.2. na 3.3. zpusobi na produkci tuhle chybu. Nevim co se s tim ma 
 delat, pls help. https://sentry.io/keboola/keboola-connection-ui/issues/407554016/
na devu pak 

> warning.js:45 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the NewTransformationBucket component.

Nejakej out of the box napad by mi pomohl. Dekuju

**Comment by janmichek** [comment]
https://github.com/keboola/kbc-ui/pull/1290 mergnuto

**Comment by janmichek** [comment]
pokracujeme tady https://github.com/keboola/kbc-ui/issues/1298
