### ISSUE TITLE
MSSQL DB EX - rozbité UI

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1273]
Při advanced mode je UI MSSQL úplně rozbité:
![image](https://user-images.githubusercontent.com/1427901/32674471-ac1ff4dc-c653-11e7-83d1-03ae3ea92bab.png)

Vidět je to tady: https://connection.keboola.com/admin/projects/2598/extractors/keboola.ex-db-mssql/275057560/query/18851

**Comment by ujovlado** [comment]
Kuknem

**Comment by padak** [comment]
a na PGSQL taky (https://connection.keboola.com/admin/projects/976/extractors/keboola.ex-db-pgsql/329464826/query/9538)

**Comment by ujovlado** [comment]
@padak je to fixed, nasadil som starsiu verziu ... refreshni si pls.

**Comment by ujovlado** [comment]
Hotfixed by #1275. Systematickejsie to poriesime v inom issue.
