### ISSUE TITLE
GD Writer - Optimise SLI

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1277]
Píšeme tam, že je "disabled", ale není to pravda - normálně to jde pustit. Dřív bylo nutný vlízt na to s SHIFTem. Vyprd bych se na to a napsal tam, že je to "danger operation" a ať si to rozmyslíš. Aktuální znění je zavádějící

![image](https://user-images.githubusercontent.com/1427901/32704174-2e78658c-c801-11e7-94e7-025312f49e8d.png)

**Comment by ujovlado** [comment]
@padak takto by stacilo?

![screenshot_2017-11-13_11-35-26](https://user-images.githubusercontent.com/419849/32721432-c44db8c2-c866-11e7-9b7e-b0ebbd4b6e23.png)

**Comment by padak** [comment]
Pokud to není přes nějakej flag, tak mě to dokonce dovoluje zapnout i bez SHIFTu. Ten text je ok! Upravíš to, prosím? @ujovlado

**Comment by ujovlado** [comment]
@padak co bolo prosim to "zapnut so shiftom" ... ziadne take obmedzenie tam nevidim

**Comment by padak** [comment]
@ujovlado dřív to bylo tak, že jsi to nemohl zmáčknout - proto tam bylo "partially disabled". tlačítko fungovalo jen, pokud jsi do toho menu přišel se zmáčklým shiftem. takovej hack...
