### ISSUE TITLE
Integrate Indigo UI v1

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1278]
Tu budem spisovat veci co este treba k integracii. Pravdepodobne to budem riesit iterativne - ked na nieco pridem, dofixujeme to v `indigo-ui` a skusime loadnut sem, a tak dookola az to bude ready.

Az to bude pripravene, zacneme s updatnmi `indigo-ui` a pisanim prvych component (to uz sa bude trackovat asi tam).

cc: @janmichek

**Comment by ujovlado** [comment]
OK, podarilo sa mi to nejako naloadovat, pomenil som tam nejake cesty, nieco som zakomentoval a build zbehol.

Je to ale rozbite, tu je par screenshotov:

![screenshot_2017-11-13_17-18-03](https://user-images.githubusercontent.com/419849/32735993-a3d88484-c896-11e7-8bbd-84b8ebb2471b.png)

![screenshot_2017-11-13_17-18-38](https://user-images.githubusercontent.com/419849/32736013-b54471c4-c896-11e7-8203-d942557bf56a.png)

![screenshot_2017-11-13_17-19-11](https://user-images.githubusercontent.com/419849/32736041-c9f40698-c896-11e7-9024-98301cf0d6e6.png)

![screenshot_2017-11-13_17-22-10](https://user-images.githubusercontent.com/419849/32736228-33ef89be-c897-11e7-9259-17edb1e47442.png)


(nepastujem sem screenshot z kazdej stranky)

**Comment by ujovlado** [comment]
Rozmyslam, co s tym, ci to ideme pofixovat alebo zobereme `kbc-bootstrap` (ktora je najblizsie connection), oznacime to ako v2 a veci z mastru indigo-ui zacneme postupne a kontrolovane preklapat tam.

**Comment by janmichek** [comment]
Jasne, nemyslel jsem si ze pri nahozeni novy verze to bude hezky xD ale odpichnem se od toho. Uplne nedokazu posoudit co bude jednodussi cesta bez vyzouseni. Napadlo me ale ve styleguide udelat podstranku 'bootstrap components' kde budou jen klasicky bs komponenty bez modifikace. Na jednom miste aby se to dalo snadneji vizualne validovat.

**Comment by janmichek** [comment]
CO mam konkretne udelat pro to, abych to videl jako na tech screenech?

**Comment by ujovlado** [comment]
> CO mam konkretne udelat pro to, abych to videl jako na tech screenech?

@janmichek checkoutni si branch `upgrade-to-indigo-ui-v1`, potom daj `yarn instal` ... potom ti to vyhodi nejake errory ohladom zlych ciest k obrazkom (v less suboroch `@keboola/indigo-ui`), tie riadky zakomentuj  napriek tomu, ze su v node_modules

**Comment by ujovlado** [comment]
Ja prave rozmyslam nad tou v2. Vyhoda je, ze este tam nie su napisane ziadne komponenty. T.j. master branch by sme mohli pouzit ako zaklad/sablonu, z ktorej budeme vychadzat a postupne to pripravovat a posielat rovno do kbc-ui.

**Comment by ujovlado** [comment]
Presnejsie:
- z `kbc-bootstrap` by sa stal novy master (dalej by sme tagovali ako `v2`)
- z mastru by sa stalo `v1` -> to by bola spominana sablona
- do noveho mastra (byvaly `kbc-bootstrap`), by sme zacali preklapat po malych castiach z v1

**Comment by ujovlado** [comment]
^ Imho je to asi jediny sposob, ako si to dokazeme odkontrolovat a nic nerozbit. Ak budeme pokracovat v mastri a dalej sa odklanat od aktualnej verzie - nebude moc sanca to spravit dobre a urcite nieco rozbijeme. Navyse, kym sa to odladi, bude to strasne dlho trvat.

**Comment by ujovlado** [comment]
> Napadlo me ale ve styleguide udelat podstranku 'bootstrap components' kde budou jen klasicky bs komponenty bez modifikace. Na jednom miste aby se to dalo snadneji vizualne validovat.

^ toto spravime, bavili sme sa uz niekedy davno o tom s Mirom.

**Comment by ujovlado** [comment]
Doriesime v https://github.com/keboola/indigo-ui/issues/26
