### ISSUE TITLE
stránka maintainera

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#128]
Na stránce maintainera není možné přepínat na jiné maintainery - dřív to šlo, bylo to docela šikovný

**Comment by Halama** [comment]
jo stranky maintaineru a organizaci je ta druha vec co ceka na dostylovani, to prepinani se tam pak snad vrati

**Comment by Halama** [comment]
Máme nakresleno:
![image](https://cloud.githubusercontent.com/assets/903531/8333177/2b6cedfa-1a92-11e5-8c05-afea30828e1e.png)
