### ISSUE TITLE
výpis organizací

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#129]
vypadá divně, jak je nalepený úplně v levo na boxíku

![image](https://cloud.githubusercontent.com/assets/1427901/8108619/d8124ec4-1051-11e5-8dcf-9e92b7cc546a.png)

**Comment by Halama** [comment]
Máme nakresleno:
![image](https://cloud.githubusercontent.com/assets/903531/8333177/2b6cedfa-1a92-11e5-8c05-afea30828e1e.png)

**Comment by Halama** [comment]
hotovo
