### ISSUE TITLE
Weird PK behavior in ex-db-generic (query editor)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1295]
Related to #1289 (since I found it there).

@pivnicek what's the difference between `simplePk` and `advancedPk` here?

https://github.com/keboola/kbc-ui/blob/3c7d77149925656f46d803a650e10b3f81f67043/src/scripts/modules/ex-db-generic/react/components/QueryEditor.jsx#L43

It is causing inconsistency in PK when switching between modes (advanced vs normal).

Shouldn't we handle it in single state value (e.g. `primaryKey`)?

**Comment by ujovlado** [comment]
I'm asking because both `simplePk` and `advancedPk` are set from same prop:
```js
this.props.query.get('primaryKey')
```

**Comment by pivnicek** [comment]
ah, that is for remembering primary key in the different edit mode.  So when you switch mode it has the right PK according to selected table or written query.  
I suppose we can get rid of it, and leave it to the user to make sure that the PK is correct.  Could be more trouble than necessary.

**Comment by ujovlado** [comment]
@pivnicek ok, so it'll be easy to refactor it to single state value (that `primaryKey` I mentioned) - since it's the query for the same table. No matter mode is advance or simple, user cannot have different PK for same table.

ok, I will change it ;)

**Comment by pivnicek** [comment]
@ujovlado Well, the idea was that when they write a query they may want to make a different PK for the output table.  But I think I agree, I was probably trying to be too clever with it:)
