### ISSUE TITLE
Tune guide mode part3

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1298]
- [x] chyba pri vytvoreni transformace L3.3. Click na 'Create Transformation' zareaguje az podruhe PROD ONLY
- [x] 2.7 route to storage Storage
- [x] Next step pada u  L3.2, 3.3, 3.4
- [x] odstranit 'Buttonlike' featuru
- [x] co se da udelat s 'prechody' aby to nebylo tak vizualne trhany - animace?
- [x] predat na validaci a user testy Jackovi
- [x] L4 vizualizace vysledku
- [x] L1, L4, L5 konci whitescreenem
- [x] L1 krok zpet na step 1 => whitescreen PROD ONLY
- [x] gratulacni chobotnice jen na konci posledni lekce
- [x] zavreny modal na Storage routuje spatne
- [x] storage events - fix pretekani obsahu [1366x768]

**Comment by janmichek** [comment]
@ujovlado Snzaim se vyresit to spatny routovani na zakladni stranku. Dokazal bys mi poradit jaka je spravna routa na tuto stranku?  RoutesStore.getRouter().transitionTo(???); evidentne to neni 'home', '/' ani ''.
Potom jsem v tech tascich hore oznacil 'PROD ONLY' kde je ruzny chovani na produkci / lokalu. Nemam moznost to nijak debugovat. Muzes mi poradit, jak na to?

**Comment by ujovlado** [comment]
@janmichek kuknem sa.

**Comment by ujovlado** [comment]
Malo by sa to fixnut tymto: 18741572de0271d337970c4bf03070b0c56fc514

Ked kuknes do `routes.js`, je tam meno tej routy:
https://github.com/keboola/kbc-ui/blob/18741572de0271d337970c4bf03070b0c56fc514/src/scripts/routes.js#L20

Neskumal som, co tam interne ten router robi, vyzera to, ze zadanim `/` to matchlo ako absolutnu URL a potom to nechcelo ficat.

**Comment by ujovlado** [comment]
Takze to vali. :tada:

**Comment by ujovlado** [comment]
Vrtam sa tam este kvoli tomu "Create Transformation" a myslim, ze by sme to dispatchovanie mohli kusok prerobit. Nefunguje to tam pravdepodobne preto, lebo v tom store sa robi transitionTo a transformacia po jej vytvoreni tiez redirectuje na detail (a asi sa to pobije a router ostane v stave, ze len zacal - `ROUTER_CHANGE_STAERT` ... neskumam zatial preco).

Navyse, robit nejake redirectovanie pripadne manipulaciu store na zaciatku tej funkcie a nie v tom switchi je dost prasacina.

https://github.com/keboola/kbc-ui/blob/18741572de0271d337970c4bf03070b0c56fc514/src/scripts/modules/guide-mode/stores/WizardStore.js#L73-L85

**Comment by janmichek** [comment]
pokracujeme tady https://github.com/keboola/kbc-ui/issues/1318
