### ISSUE TITLE
"ř" in cfg description

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1306]
Pokud napíšu "ř" do popisu:

![image](https://user-images.githubusercontent.com/1427901/33167933-7194da44-d03f-11e7-92d6-a3341ff10a1b.png)

uloží se to jako "?":

![image](https://user-images.githubusercontent.com/1427901/33167946-7a0eb8c0-d03f-11e7-8452-56715459bcbe.png)

(https://connection.eu-central-1.keboola.com/admin/projects/34/extractors/keboola.ex-db-mssql/211761)

**Comment by Halama** [comment]
tvl, to je hodně divný, mrknu

**Comment by Halama** [comment]
vypadá to že to dělá jenom v EU, bude to věc backendu, vyřeším

**Comment by Halama** [comment]
Je to fixnutý, bylo to pouze v EU a jenom u jedné tabulky https://github.com/keboola/connection/commit/3708d4ccedaf721dad986114fad245e731ed9c72

Teď už po novém uložení to bude ok.

**Comment by Halama** [comment]
ještě bysme časem teda mohli přejít na utf8_mb4 aby šlo používat 💩
