### ISSUE TITLE
Orchestration job detail - styling

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1307]
There shouldn't be padding between tab content:
![image](https://user-images.githubusercontent.com/903531/33171516-ac8bb64c-d04c-11e7-8028-151fd0513ed7.png)

It should look like this:
![image](https://user-images.githubusercontent.com/903531/33171542-c9e91946-d04c-11e7-8876-0fbdd45e2767.png)

**Comment by janmichek** [comment]
@ondrejhlavacek Cau, koukam ze to souvisi s tvoji zmenou https://github.com/keboola/kbc-ui/commit/6522838c17f1a5cfd89c4698d82a8ed5e6eb776b
Nechci to jen tak sproste vysmahnout, predpokladam ze ten styl ma nejaky vyznam. Doporucuju to nejak sikovne oclassovat a styl izolovat. Jestli chces help, tak se ozvi. Nedokazu zkontrolovat tvoji zmenu. Dik

**Comment by ondrejhlavacek** [comment]
@janmichek o jakej styl se jedná? nebo jakej less fajl/komponenta? Nějak mi to nic neříká a v tom commitu jsem detail jobu snad nestyloval

**Comment by janmichek** [comment]
Nejde to prolinkovat z toho commitu. Je to styl '.kbc-main .tab-pane'

**Comment by ondrejhlavacek** [comment]
Aha! Jsem myslel, že se ten styl nemůže dostat mimo scope komponenty, kde byl načtenej. Jde o komponentu `keboola.csv-import`, k její konfiguraci není potřeba nic, je to hloupý importovadlo CSVček z disku. Klidne to odtamtud vysmahni a pofixuj jak je potřeba, jen aby to bylo vizuálně konzistentní / pěkný, jinak je mi to jedno, v CSS jsem totální amatér :-/

**Comment by janmichek** [comment]
V kbc, to neni udelany tak ze includnuty styl skrz komponentu ti ji izoluje.  Ten styl se pouziva v s3-ex , takze uplne vysmazit ho nechci. Proste jsem si poradil .]

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/34205419-83bce2fe-e582-11e7-8438-5c14d2a4fd66.png)
