### ISSUE TITLE
výpis projektů - groupování podle maintainera

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#131]
asi to moc lidí neřeší, protože nejsou přes víc maintainerů, ale zgroupovat je by bylo super - podobně jako když přesouvám projekt do jiné organizace, tak tam vidím maintainery.

**Comment by Halama** [comment]
jo tohle pak dotáhnem, nedávám to ale mezi issue které potřebujeme k releasu. Zatím na tom teda nedělám

**Comment by Halama** [comment]
zavírám, pak si to můžeš založit v AJ :)
