### ISSUE TITLE
Table preview - db extractor query - page not found

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1315]
![table-preview](https://user-images.githubusercontent.com/903531/33214702-4bf1ee5a-d12d-11e7-8d05-1158f8726082.gif)

**Comment by kacurez** [comment]
pozriem sa nato, asi viem cim to je

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/commit/5c87d3415172de8b849fa5dcd21dd32526cf1813
