### ISSUE TITLE
GoodData Extraktor je v pravo rozsypanej

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#132]
![image](https://cloud.githubusercontent.com/assets/1427901/8108985/6a86f514-1054-11e5-92a0-2d013e19e9b2.png)

**Comment by padak** [comment]
a pro "loading wheel" používá jinej vizuál než jinde (tady se točí šipky, jinde běhají kolečka)
![image](https://cloud.githubusercontent.com/assets/1427901/8108995/80985668-1054-11e5-801f-d51bf4de7536.png)

**Comment by Halama** [comment]
diky, rozsypanost fixnem. Tu nekonistenci az prepisem extraktoru do noveho ui. Tohle stare ui v novem tam se jenom snazime aby to nebylo rozsypane a jakz takz to sedelo se zbytkem ale zadne upravy v tom vetsinou nedelame (krome toho aby to spravne linkovalo apod.) Rikame tomu legacy app, nejaky cas tam jeste budou. Podle pouzivanosti se budou nahrazovat novymi.

**Comment by padak** [comment]
v pohodě! já prostě hlásím co vidím :) Dávalo by vám smysl, nějak ty "stará apky" identifikovat?

**Comment by Halama** [comment]
koukám že tohle rozhození se děje i ve starém ui, zkusím jestli to půjde jednoduše fixnout.

**Comment by Halama** [comment]
@padak Jak si to myslel tou identifikací?

**Comment by Halama** [comment]
rozsypani je fixnuty

**Comment by padak** [comment]
identifikovat - že by měly u sebe třeba černou pásku přes ikonku - že je to stará apka a bude obnovená
