### ISSUE TITLE
List of DB tables goes out of white section

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1322]
Having longer list of configured tables, few of them goes over screen

![image](https://user-images.githubusercontent.com/1427901/33314981-99b5673e-d42f-11e7-837e-d74ec76c4a6e.png)

**Comment by padak** [comment]
(https://connection.eu-central-1.keboola.com/admin/projects/34/extractors/keboola.ex-db-mssql/209807/query/49369)

**Comment by pivnicek** [comment]
Duplicate https://github.com/keboola/kbc-ui/issues/1265
