### ISSUE TITLE
Cannot scroll new table preview page content!

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1333]
![image](https://user-images.githubusercontent.com/903531/33331566-386eeb7a-d462-11e7-9a60-0f8910d20001.png)

**Comment by kacurez** [comment]
hmm to je divne, som si na 99,9% isty ze to predtym slo. Nerozbilo sa to nejakymi upravami css ktore nedavno prebehli?

**Comment by kacurez** [comment]
tak potvrdzujem ze to neslo ani predtym, fu este dobre ze tam mam tu stotinku istoty :D
mam pripraveny fix kde bude v divoch nad tabulkami:
`style={{'max-height': '80vh', overflow: 'auto'}}`

dam to zatial ako PR pretoze ten bug vidime len my co mame `ui-devel-preview` featuru
