### ISSUE TITLE
Tune ex-db-generic

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1336]
From https://github.com/keboola/kbc-ui/issues/1319#issuecomment-347847125

- Remove tabs
- Change position of Save button on credentials page

![screenshot_2017-11-29_13-39-41](https://user-images.githubusercontent.com/419849/33375672-f872c10a-d50a-11e7-9a29-7fbee51417d9.png)

**Comment by ErikZigo** [comment]
Nic jinyho s tim asi v tuhle chvili udelat nejde. Mit tam ty tlacitka a zalozky vypada by vypadalo jeste hur.

**Comment by ujovlado** [comment]
Kedze to SSL sa tyka len MySQL a vacsina to aj tak nepouziva, je to myslim ok ;)

**Comment by ErikZigo** [comment]
Delam na tom https://github.com/keboola/kbc-ui/pull/1339
Potrebuju jeste fixnout mongo ex ui

**Comment by ErikZigo** [comment]
@ujovlado tohle uz je nasazeny tak to muzes zavrit

**Comment by ujovlado** [comment]
Jasne, ok ... som zvyknuty, ze sa to zatvara s mergnutim PR, tam to asi nebolo.

**Comment by ujovlado** [comment]
Fixed in #1339
