### ISSUE TITLE
Extractor icons align

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1344]
![image](https://user-images.githubusercontent.com/4319320/33485398-7f8f05f8-d6a6-11e7-9464-d66a75f7d56c.png)

podle starych screenshotu to driv bylo vicemene zarovnane

**Comment by Halama** [comment]
To je tím že se do short description píšou nesmysly

**Comment by odinuv** [comment]
no tak nesmysly ani tak ne, spis dlouhy, ale stejne to driv nebylo tak spatny, anebo to jen tak kazi ten hubspot?

**Comment by ondrejhlavacek** [comment]
když se změní zarovnání stylu buňky z `vertical-align: bottom` na `vertical-align: top`

![image](https://user-images.githubusercontent.com/497675/36028762-818ce722-0da0-11e8-84a7-e15b430bcc5d.png)

**Comment by ujovlado** [comment]
To mozeme doriesit napr. flexboxom a dat button tak aby bol vzdy dole ...  vid. devportal https://components.keboola.com/components

**Comment by ondrejhlavacek** [comment]
Tak jsem zatím udělal teda prasáckej PR :-)
