### ISSUE TITLE
followup of config rows react implementation ideas 

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1346]
Tymto reaguje na predstavu o config rows navrhovanu v slacku tu:
https://keboola.slack.com/archives/C02J3DKH3/p1512129153000150
povodne som to tam chcel napisat ako komentar ale stymi prikladmi sa mi to trocha nafuklo :)

#### 1. Nepotrebna rows property
imho property `rows` pre `ConfigRowTable` nie je potreba. Ak si predstavim ako by to napr vypadalo pre google drive, tak v jeho Index.jsx module bude nieco ako:

```jsx
render() {
  return (
    <ConfigRowTable
      configId={this.state.configId}
      componentId="keboole.ex-google-drive"
      configRowItemElement={this.renderConfigRow}
      headers={['Document / Sheet', 'Output Table', '']}
      />      

  );
}
```
rows(aka zoznam config rows) si ConfigRowTable interne nacita z InstalledComponentsStore inac sa to bude musiet nacitat v gdrive Index.jsx ale vlastne nic stym robit nebude len preda do props ConfigRowTable. Jedine blbost je ze na stranke gdrive Index.jsx bude musiet ostat ten mixin na zmenu InstalledComponents store. 

Podobne by som do configRowItemElement nepredaval `configId` a `componentId` pretoze tie bude ta custom gdrive komponenta vzdy vediet. 

#### 2. configRowItemElement ako jednoduche pole mappingov
Do ConfigRowTable by stacilo dodat len array mappingov rows(rowsMappings property) pre headers tj pre gdrive by to vypadalo nasledovne:

```jsx
render() {
  return (
    <ConfigRowTable
      configId={this.state.configId}
      componentId="keboole.ex-google-drive"
      headers={['Document / Sheet', 'Output Table']}
      rowsMappings={[row => `${row.get('document')} / ${row.get('title')}`, row => row.get('tableId') ]}     
      />      
  );
}
```

a v ConfigRowTable render table body by bolo nasledovne:
https://github.com/keboola/kbc-ui/blob/f11a2fabdbd7a69bd363e80afebf8f943688f30a/src/scripts/modules/components/react/components/ConfigRowTable.jsx#L55

```jsx
<div className="tbody">
  {this.state.rows.map( row =>
    <div className="tr">
      {this.props.rowsMappings.map(mapRowFn =>
        <div className="td">
          {mapRowFn(row)}
        </div>)}
      <div className="td">
        {this.renderActionButtons()}
      </div>  
    </div>

  )}
</div>
```
takze `rowsMappings` prop je pole funkcii ktore vracaju react elementy. Ich poradie je zname pri pouziti ConfigRowTable v gdrive/Index.jsx a nemusi sa nijak explicitne riesit.  Tym "ja" ako programator ui kbc komponenty vobec nemusim riesit a poznat strukturu ConfigRowTable. Tiez nemusim riesit action buttony(run, disable, delete). Mozno tam nieco prehliadam ale fakt mi pride ze toto uplne staci :)

#### 3. Link na detail stranky config rowu ako property ConfigRowTable
Dalsiu property do ConfigRowTable odporucam `linkToRowParams` tj fce ktora vrati parametre pre link na detail config rowu(napr u google analytics je detail na vlastnej stranke). 
gdrive priklad: 

```jsx
<ConfigRowTable
  linkToRowParams={row => ({to: 'query-detail'}, params: {queryId: row.get('queryId')})}
  ... />
``` 

Takze v ConfigRowTable by potom nebolde `<div className="tr">...` ale 

```jsx
<Link to={this.props.linToRowParams(row).to} params={this.props.linkToRowParams(row).params}> ... </Link>
```

#my2cents #peace

**Comment by ondrejhlavacek** [comment]
Díky za komenty!

1) No, chtěl jsem komponenty držet co nejvíc izolovaný od storů. Představ si, že komponenta bude součástí nějakýho style guide a budeš muset mockovat store místo toho, abys mu data jednoduše předal přes props. Tak nějak mi přijde načítat data ze storů co nejdřív a pak je předávat dolů jako nejčistší (pokud to nezavání nějakým argument passing peklem).

2) Nemáš tam náhodou pomotaný `row` a `column`? Trochu mi to ztěžuje to pochopit :-). Mapping je zajímavej nápad, ale co když tam budeš chtít dát nějakej rich content? Ale to asi půjde, vyzkouším

3) Jasně! To tam přijde dodělat, postupuju po atomickejch funkčních inkrementech, řádky ještě nejsou klikací :-).

**Comment by kacurez** [comment]
1. jj rozumiem, pre mockovanie to bude lepsie predavat cez props. Stejne sa v index.jsx komponente store pouzije aj na ine veci okrem predavania dat pre ConfigRowTable takze asi to nema zmysel riesit inak.

2. Nazval som to trocha nestastne no.. :) Je to teda `ColumnsMapping` pre row tabulky. Obsahuje pole fci z ktorych kazda vrati React komponentu pre jeden stlpec riadku tabulky co moze byt akykolvek kontent. Dolezite je ze sa do toho nezanasa struktura ConfigRowTable tj nutnost rendrovat napr `<div className="td">...` element

3. Jasne to pride na rad az ked sa bude riesit detail riadku. Este k tomu dodam/poznacim aby sa nezabudlo ze este byva moznost editacie cez modal. Takze by asi bola prop ktora urci typ detailu('link', 'modal', 'none') a k nej dalsia prop s parametrami.

**Comment by ondrejhlavacek** [comment]
ad 3. Forcnul bych sjednocení a detail bude vždy podstránka. Pokud to má být cokoliv jinýho, ať si to napíše komplet sám. Proběhne to ještě celý UX kolečkem, tak tam bude možnost tohle napadnout.

**Comment by ondrejhlavacek** [comment]
Zatím teda tohle zavírám, příště to asi můžem klidně psát do PR?
