### ISSUE TITLE
Guide mode internal feedback

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1349]
- [ ] Reset lekce - napr kdyz otevru a zavru browser
- [ ] na Storage je spatne cesta k images . Napr L1.3
- [ ] na L3.3 Nejde vykopirovat text z jendoho modalu do druheho (neprekvapive) - Chrome Issue
- [ ] naprogramovat distribuci Guide Mode jak navrhuje Odin ->   try.keboola.com -> zadas promokod -> vytvori to novy projekt s expiraci 2dny // Ale bacha jak se promenou v Academy

- [ ] NICE2HAVE: pojmenovat sloupecky v tabulkach tak, aby byl kod v query lidem snaz srozumitelny
- [ ] NICE2HAVE: Premyslet posledni screen - nadpis, dat lidem vedet ze je to konec lekce, gamifikovat (dle nakresu)
- [ ] NICE2HAVE:  jeste vic vytunit UX, animace, gamifikace. Zkratka to udelat zabavnejsi
- [ ] NICE2HAVE: refaktorizace kodu WizardModal

**Comment by odinuv** [comment]
- [ ] moc se me nelibi "prev step", chapu, ze "previous step" je dlouhy -> nemohlo by to byt jen "previous" a "next" ?
- [ ]  lesson 2: Note: Your own projects won’t be affected by this in any way. -> ta poznamka je divna, nemohli bysme ji dat proste pryc?
- [ ] 2.2. e.g., My database extractor, -> e.g., <em>My database extractor</em>, + nemohlo by to byt neco kratsiho :) (treba "My really first snowflake database extractor configuration" :D nebo "Demo"/"Guide")
- [ ] 2.3. "provide a password and other credentials" -> nemelo by to byt spis "provide the database credentials" ?
- [ ] 2.7. - linkovat na https://help.keboola.com/extractors/ misto https://help.keboola.com/overview/#extractors 
- [ ] 3.2 dtto 2.2.
- [ ] 3.4 "copy and paste" -> pridat "overwrite" - dneska uz tam mame default obsah transformace
- [ ] 3.6 "In the section Jobs, " -> "In the Jobs section" ?
- [ ] 3.7. chybi - "click next step "
- [ ] 3.8 - "Tableu" -> "Tableau Desktop" je to produkt, pridat link jako ve 4.2, spatny link na  https://help.keboola.com/tutorial/load/
- [ ] 4.1 - "Lesson 3,and" - chybi mezera
- [ ] 4.2. dtto 2.2.
- [ ] 4.3. COUNTRY/string, -> misto lomitka neco jinyho, treba sipku?
- [ ] 4.4. v "To run the writer, click  Export tables to TDE." - to zalamuje tecku
- [ ] 5.4 - "select your Snowflake extractor" -> mozna "select your Snowflake extractor configuration" ? nevim, je to zase dlouhy

**Comment by odinuv** [comment]
co se tyce distribuce guide mode - tak by to melo byt pres neco jako try.keboola.com - zadas promokod a vytvori to novy prazdny projekt s expiraci 2dny

**Comment by janmichek** [comment]
@odinuv dik za feedback, s vetsinou souhlas. Dobry postrehy. Tady mam par poznamek

> lesson 2: Note: Your own projects won’t be affected by this in any way. -> ta poznamka je divna, nemohli bysme ji dat proste pryc?
Ted kdyz vime ze GM bude v novym projektu, tak to ma smyslu. experimentalne davam pryc, uvidime co to udela. 

>  2.2. e.g., My database extractor
ok, fajn napad. dal jsem vsude _Guide component_ . V Jobs by se potom vsechno jmenovalo 'Guide' kdyby jsme to chteli takhle superkraty

> 5.4 - "select your Snowflake extractor" 
Vzhledem k malo obsahu v nabidce nechavam pojmenovani jak je. Asi to neni technicky uplne presny, ale je mi jasny na co kliknout

**Comment by hhanova** [comment]
ad 2.2. e.g., My database extractor
   ok, fajn napad. dal jsem vsude Guide component . V Jobs by se potom vsechno jmenovalo 'Guide' 
   kdyby jsme to chteli takhle superkraty

- a co to zkratit na My extractor, My transformation a My writer... Pojmenovat vsechno stejne (Guide component) mi neprijde uplne nejlepsi, Chtela jsem, aby i z nazvu konfigurace bylo lidem jasny, co presne delaji a aby tam bylo to "MY ...", ze je to neco, co bude jenom jejich a ze si to tvori uplne sami. 

ad  3.6 "In the section Jobs, " -> "In the Jobs section" ? 
- to je v pořádku tak i tak

ad  3.4 "copy and paste" -> pridat "overwrite" - dneska uz tam mame default obsah transformace
- navrhuju: 
Queries — to create your output table,  copy the following code and replace the default text with it.

**Comment by odinuv** [comment]
@hhanova  no me se to `my` moc nelibi - ono v tom to, ze bysme chteli, aby si lidi pojmenovavali veci podle toho co obsahuji nebo k cemu slouzi. Kdyz pak ten clovek prijde do ostreho projektu a pojmenuje si konfiguraci extractoru "my extractor" tak je v tom ultra chaos, cili proc lidi ucit neco co rozhodne nechcem aby delali.

Ze je to pojmenovany stejne by nemelo vadit - melo by byt videt z kontextu o co se jedna (pokud neni, je to chyba) - podle stejne logiky nepojmenovavame komponenty "Mailchimp extractor", ale jen "Mailchimp" (protoze extractor je videt z kontextu)

**Comment by janmichek** [comment]
Vyjadril jsem se spatne. Ty popisky jsem opravil na _Guide extractor_, _Guide transformation_, ... atd

ad Queries -> pouziju tu vetu co pise Hanka.

**Comment by hhanova** [comment]
ok, rozumim

**Comment by janmichek** [comment]
feedbacky od Jacka https://projects.invisionapp.com/share/27EXDXLMN

**Comment by janmichek** [comment]
@ujovlado potreboval bych prosim poradit. Chci udelat aby byl wizard po prenacteni stranky zavreny. Modal se otevre pouze po kliknuti na polozku ze seznamu akci.

**Comment by ujovlado** [comment]
@janmichek takze chces aby sa odignoroval ten stav, co je v local storage a po reloade apky bol vzdy zavrety, ano?

**Comment by janmichek** [comment]
Jo, nedari si mi ten storage nasetovat driv nez ho dostanu.

**Comment by ujovlado** [comment]
ok, uz chapem, skusim sa pozriet

**Comment by janmichek** [comment]
Jeste jsem objevil ze na Storage (L1.3) se nezobrazuje obrazek.
Na storage ApplicationStore.getScriptsBasePath() vraci undefined. Normalne vraci prazdny string. Zatim nevim co s tim

**Comment by ujovlado** [comment]
@janmichek no, dumal som nad tym ale obavam sa, ze to nie je moc riesitelne. Ten state sme davali do local storage aby sa zachoval aj ked prechadzas do Storage sekcie.

Ak to, ci je modal otvoreny/zavrety, presuniem do state tej komponenty (co by vyriesilo tuto issue), tak potom to stratim v Storage, pretoze tam prebieha nacitanie apky znovu -> t.j. po prechode zo storage (alebo do storage) sa apka nacita znovu (vlastne to iste ako reload) a modal by ostal zavrety.

**Comment by ujovlado** [comment]
> Jeste jsem objevil ze na Storage (L1.3) se nezobrazuje obrazek.
> Na storage ApplicationStore.getScriptsBasePath() vraci undefined. Normalne vraci prazdny string. Zatim nevim co s tim

toto skusim tiez preskumat, tam bude predpokladam problem s tym, ze ten obrazok tam nie je dostupny ... uvidime

**Comment by ujovlado** [comment]
> naprogramovat distribuci Guide Mode jak navrhuje Odin -> try.keboola.com -> zadas promokod -> vytvori to novy projekt s expiraci 2dny // Ale bacha jak se promenou v Academy

@janmichek na tomto myslim (zatial) netreba programovat nic ... staci ak sa o tom zacneme bavit viac podrobnejsie, ako si to predstavujeme. Napr. ci bude existovat nejaky "staly" promo kod pre guide mode a pod. A ci popri tomu maju fungovat aj ine promo kody cez try.keboola.com a pod. Co sa backendu tyka, je to myslim pripravene a je mozne vytvorit sablonu projektu, ktora bude mat guide mode zapnuty.

**Comment by janmichek** [comment]
Ok, cool. Chapu

**Comment by ujovlado** [comment]
Ten obrazok fixnut pojde (vid linknuty issue), bude to ale treba upravit aj na backende, pretoze v Storage nie je dostupny `ApplicationStore`.

**Comment by janmichek** [comment]
Pokracujeme tady https://github.com/keboola/kbc-ui/issues/1401
