### ISSUE TITLE
Input mapping long names overflow and hides buttons

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1354]
![screen shot 2017-12-05 at 15 59 09](https://user-images.githubusercontent.com/8642344/33596068-5df25242-d9d5-11e7-991a-5f3a0ac64c4e.png)

**Comment by ondrejhlavacek** [comment]
@pocin what browser/os do you use? tried to reproduce this bug and it's displaying correctly for me.

![image](https://user-images.githubusercontent.com/497675/36028594-ee7d40ee-0d9f-11e8-8425-8dc82f3a2c02.png)

**Comment by pocin** [comment]
Yeah, it's ok now. Was Firefox on macOS

**Comment by pocin** [comment]
Ok it's still there:
<img width="1121" alt="screen shot 2018-02-16 at 09 09 30" src="https://user-images.githubusercontent.com/8642344/36298602-38136cac-12f9-11e8-81d4-0cd9c41b13c3.png">

try something of this size as tablename `in.c-pocin-ex-mailchimp-export-api-326210279.6399667ed4_unsubscribed_None`

`MacOS HighSierra 10.13.3`

`Firefox 58.0.2`

Works ok in `Chrome Version 64.0.3282.167`

**Comment by natocTo** [comment]
```
word-break: break-word;
```

Není podporované třeba ve Firefoxu, co jsem koukal. Jako fallback by se tam měl použít `break-all`. Nebo to vyřešit jinak. Poslal jsem update to [Indiga](https://github.com/keboola/indigo-ui/pull/307), pokud se příjme upravím pak tuto případy v KBC-UI.
