### ISSUE TITLE
Archive or deprecate unused repos

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1356]
Zbavme se techto pokusu o styleguidy. Je to akorat matouci.
- [x] http://kbc-bootstrap-jakub-devel.keboola.com/examples/ sundal bych to ze subdomeny
- [x] https://github.com/keboola/kbc-style-guide-bundle
- [x] https://github.com/keboola/kbc-react-components // casem i toto, delame na tom

**Comment by ujovlado** [comment]
zostavajuce `kbc-react-components` archivovane, zatvaram
