### ISSUE TITLE
výpis tranformací

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#136]
Na slevomatu (https://connection.keboola.com/admin/projects/226/transformations/bucket/sys.c-tr-main) je divně široký:

![image](https://cloud.githubusercontent.com/assets/1427901/8110128/f4de0cc4-105a-11e5-8501-86b362a32430.png)

v shared configu (https://connection.keboola.com/admin/projects/258/transformations/bucket/sys.c-tr-kbcinternalstats) vypadá super:

![image](https://cloud.githubusercontent.com/assets/1427901/8110138/fe4aa754-105a-11e5-9380-5105515f49cd.png)

**Comment by ondrejhlavacek** [comment]
@padak ideálně bych výpis transformací udělal jako výpis extraktorů + konfigurací.

**Comment by padak** [comment]
to by bylo totální peklo - podívej se na rohli.cz nebo slevomat.cz - na layout stránky s extraktorama, kde máš tipicky pár věci, je v tapi imho moc položek

**Comment by ondrejhlavacek** [comment]
@padak @Halama @JakubMatejka bylo by něco takovýhodle průchozí? Nevím moc jak to líp udělat - fixovat šířku tabulky nejde, pokud to budu chtít mockovat bez tabulky, ale aby to mělo stejný vzhled jako tabulky seznamů, tak to bych se osypal to udělat (ty tabulky maj spoustu fíčur), takže bych se klonil k tomu to vizuálně udělat podobně jako ve writeru. 

![screen shot 2015-06-15 at 14 24 33](https://cloud.githubusercontent.com/assets/497675/8171109/4dfb69a2-136a-11e5-82ac-b094d7db7645.png)

Pro porovnání - takhle vypadá stejná stránka v současným vzhledu

![screen shot 2015-06-15 at 14 24 41](https://cloud.githubusercontent.com/assets/497675/8171110/525e4e92-136a-11e5-9b8a-758791a52c47.png)

**Comment by ondrejhlavacek** [comment]
(branch `transformationbucket`)

**Comment by JakubMatejka** [comment]
Jestli jde jen o ty ikonky tak to fixnu. (Upravil jsem csska aby šlo na sloupce tabulek používat grid třídy `.col-*`)

**Comment by JakubMatejka** [comment]
Může být?
![development_-_bucket_sys_c-tr-main](https://cloud.githubusercontent.com/assets/215660/8177723/d698433c-1407-11e5-98a7-33c967a19efb.png)

**Comment by ondrejhlavacek** [comment]
@JakubMatejka super, díky!
