### ISSUE TITLE
(ex-db-generic) default table name -> lowercase

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1361]
![image](https://user-images.githubusercontent.com/569139/33653887-b3ff5bd2-da6e-11e7-8bde-358e46d88a38.png)

**Comment by janmichek** [comment]
could be relevant to this issue ->https://keboola.slack.com/archives/C5CLTL7MK/p1511786033000312 seems like its the screen from the transformation of Guide Mode

**Comment by ujovlado** [comment]
@janmichek we discussed it in `#db-extractor` on Slack.
