### ISSUE TITLE
Replace remaining usages of TabbedArea and TabPane from KbcBootstrap proxy

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1365]
Related to: https://github.com/keboola/indigo-ui/issues/59

Je ich asi 19, mozeme to pouzit napriamo, aby to nevzbudzovalo dojem, ze sa pouziva nieco deprecated.

![screenshot_2017-12-07_13-01-29](https://user-images.githubusercontent.com/419849/33714323-d125d566-db4e-11e7-9beb-9aa57ebde382.png)

**Comment by janmichek** [comment]
Fajn, klido jsem to mohl udelat. Nemam toho moc na praci .]
