### ISSUE TITLE
detail transformace - graf

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#137]
Jak se nově vypisuje graf úplně nejvejš a nejde schovat, je celá transformace úplně mimo obrazovku. Ten tabulátorovej koncept mi přišel lepší - když je to velké, vypadá to třeba takhle (https://connection.keboola.com/admin/projects/226/transformations/bucket/sys.c-tr-main):

![screen shot 2015-06-11 at 16 59 17](https://cloud.githubusercontent.com/assets/1427901/8110251/820651d8-105b-11e5-94a8-bc5b3ee8b441.png)

Otázka - prošel tenhle layout nějakým evolučním procesem? Za mě je to trochu nepohodlný... Úplně jiné by bylo, kdyby to bylo defaultně schované jako třeba "Storage" v jobech.

**Comment by Halama** [comment]
S tím grafem zkusíme něco udělat třeba do panelu jak říkáš. Jinak to že to je vidět všechno najednou nebo se zascrollováním je imho mnohem lepší než neustále přepínat taby. Na ty taby byly různý tickety v zendesku tuším.

**Comment by padak** [comment]
no já nevím. na taby si stěžoval Adam, kterej je pro mě největší dement a nejmín fér poskytovatel feedbacku. jediny objektivně blbě na tom bylo, že když jsi psal output mapping, tak jsi neviděl SQL, ve kterém bys opsal jméno tabulky. Jinak to bylo podstatně přehlednější - měl jsi prostě kontexty, ve kterejch klikáš. Napíšu o feedback pár lidem.

**Comment by Halama** [comment]
mě ty taby vadily právě z toho důvodu co jsi popsal. Myslím že jsem na to ale netlačil aby se to měnilo. Víc k tomu bude vědět @ondrejhlavacek

**Comment by ondrejhlavacek** [comment]
@Halama Pokud se o tom chcem dál bavit, vyhoďme to z toho Public release milestone, jinak se to zase sekne. Na taby si stěžoval TTčko + Adam. Evolucí to neprošlo, vrátil jsem to do původního jednotabovýho layoutu. Graf by mohl bejt defaultně sbalenej a rozbalit se na tlačítko nebo tak něco (nějakej overlay do modalu na víc prostoru?).

**Comment by padak** [comment]
za mě je to cesta zpět - u jednoduchých transformací to nevadí (že nevidíš jednu tabulku co chceš opsat do out mappingu) a u složitých je to podstatně hůř použitelné - graf tě tak často nezajímá, mapping needituješ, ale zabírá obrazovku. Schovat někam graf je určitě lepší, pokud nesouhlasíte s tabama :)
