### ISSUE TITLE
Combination of SSL and SSH in MySQL ext.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1370]
Current situation:

- combination of SSH and SSL will cause "CN mismatch" since we're connecting to localhost/127.0.0.1

We should:

- Add note that combination of both will not work.

Or:

- Wait until "CN check" can be turned off (https://github.com/keboola/db-extractor-mysql/issues/7#issuecomment-350699928) and add note that user should turn off "CN check" to use both SSL and SSH

Or (which I like the most):

- Do not allow user to check both SSL and SSH

**Comment by ErikZigo** [comment]
Ja se priklanim k posledni variante.
