### ISSUE TITLE
Transformace - výpis queries

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#138]
Je docela super, jak se to musí celý editovat. Postrádám ale pattern, kdy dřív stačilo kliknout do SQL a dát `cmd+a` a zkopíroval jsem si to celé do sql klienta. Teď to takhle snadno nejde. Mohlo by bejt super v tom read-only výpisu u čísla každý query ikonku co to zkopíruje do schránky + třeba někde nahoře možnost zkopírovat do schránky všechen kód.

![image](https://cloud.githubusercontent.com/assets/1427901/8110382/31f29930-105c-11e5-976e-23f018388131.png)

**Comment by ondrejhlavacek** [comment]
Copy to clipboard by šlo!
