### ISSUE TITLE
transformace - závislosti

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#139]
[Tady](https://connection.keboola.com/admin/projects/226/transformations/bucket/sys.c-tr-main/transformation/dailytargetsprocess) je závislá transformace, ale není vidět. Zobrazí se až když dám EDIT.

**Comment by ondrejhlavacek** [comment]
@padak Část se závislejma a závisejícíma transformacema jsem vyhodil, protože duplikuje informace, co vidíš v grafu. https://www.evernote.com/l/AAWxE3u6DAhDwbjBlC43WBr0R_vQTLF9ayM

Myslíš, že by to mělo bejt zpět?

**Comment by padak** [comment]
já myslím, že to není moc přehledný. zjistit, jestli je závislost na "salestargets_init" je docela tricky. v tom grafu je toho víc než bys pro takovej pohled potřeboval. navíc pokud ho do defaultu schováme, nebudeš to mít na očích. pro mě například je docela důležitý vědět, jestli makám na něčem co má vliv na okolí - pokud ano, jsem nervózní, pokud ne, vím že mám jasnej píseček.
