### ISSUE TITLE
broken ex mongo query detail page

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1392]
vytvoril som si jednoduchu query a potom z indexu do nej vliezol:
https://connection.keboola.com/admin/projects/219/extractors/keboola.ex-mongodb/339893702/query/76104

![image](https://user-images.githubusercontent.com/1412120/34198003-05f0ee9c-e569-11e7-9586-8be78274133b.png)

![image](https://user-images.githubusercontent.com/1412120/34198088-6425cbf4-e569-11e7-82df-b9aeb7714267.png)

pada to na tomto:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/ex-db-generic/react/pages/query-detail/QueryNav.jsx#L46

**Comment by ujovlado** [comment]
tvl, toto je fail, ze nam to uslo ...

**Comment by ujovlado** [comment]
idem to fixnut teda
