### ISSUE TITLE
Wrong identifier quotation character in Oracle DB extractor query suggestion

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1396]
Když založím novou query v Oracle DB ex a dám Advanced mode, v nápovědě je uveden jako quotation mark backtick, ale ORACLE potřebuje double quotes -> mate to uživatele.
![query 2017-12-20 16-00-01](https://user-images.githubusercontent.com/12933713/34213379-593be38c-e59f-11e7-8958-7ecf3b68de98.png)

**Comment by pivnicek** [comment]
Good point!  Most DBs actually use the `"`.  The placeholder text should be db specific.  Cheers!
