### ISSUE TITLE
transformace - procedury

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#140]
[Tady](https://connection.keboola.com/admin/projects/226/transformations/bucket/sys.c-tr-main/transformation/dailytargetsprocess) varujeme že nepodporujeme funkce a procedury - přitom to není pravda - funguje to a lidi to používaj (minimálně Slevomat a GetChart). Navrhuju to vyhodit a nepsat o tom. Pokud to má důvod a jsou s tím problémy, udělal bych na to článek ve wiki a odsud ho linkoval.

![image](https://cloud.githubusercontent.com/assets/1427901/8110473/c4e969e4-105c-11e5-9e1a-f5e2a21e578a.png)

**Comment by ondrejhlavacek** [comment]
@padak a co napsat *Use at your own risk.*? 

Problém byl v tom, že ve starších verzích RDS vůbec nefungovaly (a teď už teda jo), v Redshiftu funkční nejsou vůbec. 

Obecně mi jde o hygienu práce a nějakej level obtížnosti, co tam člověk vytváří.  Procedury umožňujou vykonávat věci, který jsou úplně neoptimalizovaný, vytvářej nekonečný smyčky, blbě se to benchmarkuje. 

To, co tam v tý proceduře dělají, uděláš úplně jednoduše bez procedury (pomocí předgenerovanýho číselníku) nebo třeba v Rku.

Ukaž mi další procedury a funkce, jestli tam bude něco, co nejde nahradit.

**Comment by padak** [comment]
všechno jde nahradi :) já bych neřešil proč to někdo dělá (nicméně třeba [tady](https://connection.keboola.com/admin/projects/547/transformations/bucket/sys.c-tr-smartemailing/transformation/funnel-ss) týpek jede na funkcích).

Jsem pro "use at your own risk!" :)

**Comment by ondrejhlavacek** [comment]
Hm, tady to dává smysl. Můžu pro to zanést podporu v TAPI (bude to mazat funkce a procedury v databázi při initu, aby se to nemuselo dělat ručně). Když TAPI server (nebo sandbox) jel ještě na RDS, tak to nešlo - RDS uživatelský funkce nepodporuje.

**Comment by padak** [comment]
Ok!
Dne 15. 6. 2015 21:43 napsal uživatel "Ondřej Hlaváček" <
notifications@github.com>:

**Comment by ondrejhlavacek** [comment]
Dám zatím *Use at your own risk." a tu podporu do TODO.
