### ISSUE TITLE
Distribuce guide mode

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1402]
Tady promysleme jak distribuovat guide mode a naprogramujme to.
Ja osobne se k tomu asi nijak kompetentne nevyjadrim.

Vyjadrovali se k tomu @odinuv a @ujovlado 

Odin navrhuje ->  try.keboola.com -> zadas promokod -> vytvori to novy projekt s expiraci 2dny 

TFko taky navrhuje sloucit obsah Academy s Guide wizardem (predstavuju si to jako rozsireni nebo upravu obsahu). Nevim jestli je to nejak relevantni.

Jakmile projde tenhle PR, je vse ready k pouziti https://github.com/keboola/kbc-ui/issues/1386

**Comment by odinuv** [comment]
TF academii jsem jeste nevidel, ale predpokladam, ze je tam toho vic nez v GM, jestli je tam nejaky netrvialni mnozstvi obsahu, tak si nedovedu predstavit jak by se to updatovalo

**Comment by janmichek** [comment]
Probehne k tomu talk 10/1 zatim nic konkretniho nemame
https://github.com/keboola/kbc-ui/issues/1377

**Comment by ujovlado** [comment]
Osobne by som sa na nejake zlucovanie s Academy vykaslal, pretoze sa to moze cele predlzit o niekolko mesiacov, a nakoniec zistime, ze mame mackopsa, ktory nie je moc pouzitelny.

Imho je teraz Guide Mode v relativne dobrom stave a isiel by som cestou try.keboola.com (alebo to mozem cele skopirovat a vznikne guide.keboola.com, kde zadas promo kod a vytvori ti projekt). 

Pripadne sa to da osefovat aj standardnymi promo kodmi -> tam je ale nevyhoda, ze clovek sa musi registrovat sam.

**Comment by janmichek** [comment]
Jasne, pripadny slucovani az v dalsi verzi, potom co bude Guide Mode nejakou dobu v produkci. Pripadne napady prosim piste do #1377.

Predpokladam ze se domluvite na tom jak naprgat distribuci a udelate to. Ja k tomu asi nemam moc co poradit

**Comment by ujovlado** [comment]
Jasne, ten backend je vlastne vyrieseny (ak tam nevymyslime nieco extra, mozeme to pripravit skoro). Potrebujem ale vediet aj iny nazor, z hladiska UX, ako si myslime/myslis, ze by to bolo pre usera najlepsie.

Paci sa mi, ze pride na stranku, zada meno, email, kod a ostatne sa stane samo .... takze by som siel tou cestou. Ak nema nikto nic proti (alebo lepsi napad), zacnem to tak pripravovat.

**Comment by padak** [comment]
Já bych to docela viděl jako že novej user v Keboole - bez ohledu na kanál kudy se k projektu dostane - prostě vidí Guide mode = on. Takže když pozvu novýho týpka do Slevomatu, přijde mu pozvánka, založí si účet a vleze do projektu, tak to vidí. Bylo by super, kdyby to mohl zavřít a později se k tomu vrátit. Sám jsem to teď neviděl, ale core idea je vysvětlit co má před sebou. 

Pokud je v guide mode nějakej interaktivní obsah, co by mohl Slevomatí (či jinej) projekt zničit, tak bych novýmu userovi zobrazil info o tom, že je takovejhle onboarding projekt, kde si může hrát a poslal ho na try.keboola.com s promokodem. 

TFkovu KBC Academy bych s tím přiliš teď taky nespojoval. Jen bych si dal bacha na to, aby to moc spolu nekolidovalo.

**Comment by odinuv** [comment]
@padak to uz jsme zavrhli na offsitu - guide mode v neprazdnym projektu je peklo, protoze nevis co tam je a ruzny instrukce nejdou splnit - takze druha moznost

**Comment by padak** [comment]
ok, rozumím! tak pak by bylo fajn o něm říct novejm lidem, co přijdou jinou než "naší" cestou.

**Comment by janmichek** [comment]
Cau, v jakym je tohle stavu? Neprijde mi ze by tu vzniklo nejake zadani, nebo ze na tom nekdo dela .] Takze se ozyvam a prudim

**Comment by odinuv** [comment]
"zadani" neexistuje a existovat nebude, to uz by sis mohl zvyknout :). Jinak vlado na slacku nekde psal, ze try.keboola.com upravi

**Comment by janmichek** [comment]
Chapu, to nebyla uplne moje pointa, jenom jsem chtel aby to nezapadlo. Co se ma stat ohledne tohoto tematu, poprosim piste sem - kontextove k tasku.

**Comment by janmichek** [comment]
V jakym je tohle stavu, prosim? @ujovlado

**Comment by ujovlado** [comment]
Trosku to zapadlo, hned ako mi skonci Zendesk week, vrhol by som sa na to.

**Comment by ujovlado** [comment]
Toto tu zavrem, lebo je to ready.

Co sa este bude riesit:

- mala zmena designu: https://github.com/keboola/indigo-ui/issues/101 (distribuciu to ale neblokuje)
- akonahle sa rozhodneme to dat public, trebe mergnut PR na connection pridavajuci moznost vypnutia/zapnutia Guide Mode

**Comment by odinuv** [comment]
@ujovlado ja bych to mergnul a dal public
