### ISSUE TITLE
add field "Input table" for Apify extractor to tha last step of Setup crawle

### ISSUE THREAD

**Issue by drobnikj** [keboola/kbc-ui#1409]
To the last step of Setup crawler wizard of Apify extractor we need to add field "Input table". Same field as in "Input table" in Geneea app, see:
https://ibb.co/jLti4w

We discussed it with @kacurez on slack..

**Comment by kacurez** [comment]
@drobnikj couple of questions:
1. is it optional parameter?
2. provide description - what is table used for? so user knows its purpose
3. are there any constraints? like it has to have a primary key set or particular column name, naming convention..

**Comment by drobnikj** [comment]
1. yes, it is optional parameter
2. Description: Data from input will be push to crawler, where you can access them though Apify keyvalue store. Keyvalue store ID will be save to customData attribute.
3. no, there aren't constraints. We just need push data to crawler and process them in crawler.
