### ISSUE TITLE
Přepínání mezi projekty - udržení komponenty

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#141]
V novém UI pokud jsem v Transformacích a přepnu se do jiného projektu, tak mě to hodí na overview. Ve starém to drželo aktivní komponentu. Nějak jsem si na to zvykl - né nutně je to samozřejmě blbě.

**Comment by Halama** [comment]
Jo tohle věc u které jsem si nebyl jistej jestli tam vůbec má být nebo ne, tak jsem si řekl že to udělám až se někdo ozve.

**Comment by padak** [comment]
to dává smysl! nechme to!

**Comment by Halama** [comment]
počkáme až teda ozve ještě někdo kromě tebe ok?

**Comment by padak** [comment]
Jj

Sent from mobile
Dne 12. 6. 2015 4:12 PM napsal uživatel "Martin Halamíček" <
notifications@github.com>:
