### ISSUE TITLE
Display executed config version in job detail

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1414]
It would be nice if the config version that was executed were shown on the details page of the job.
Would help with troubleshooting/debugging.

**Comment by odinuv** [comment]
if it would help it, docker-runner can return it in job result (it's already traced and logged)

**Comment by pivnicek** [comment]
yeah, that would be great!

**Comment by odinuv** [comment]
solved by https://github.com/keboola/docker-bundle/commit/beaf6f13ea4cd9b770f4d642618a5af10d198be5
