### ISSUE TITLE
[dbWriter] Check consistency of config wrt source table

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1415]
Ideally the UI should warn the user that his config does not match that of the source table (ie. the source table has been altered somehow, columns removed etc...)

Currently the job fails when it tries to import from SAPI.

**Comment by Halama** [comment]
https://keboola.slack.com/archives/C06BK8K1Q/p1519369748000206

**Comment by Halama** [comment]
Now when the column is deleted in storage, it remains in writer config and user has no clue what to do with it. It is not even shown in UI. 
Deleted columns should be still listed in the UI and somehow marked as invalid, and user should be able to delete them.

There is a same situation for writer tables, which we solved this way:
![image](https://user-images.githubusercontent.com/903531/36588287-f32853c0-1887-11e8-8e62-a3edc32424bd.png)
