### ISSUE TITLE
Feature Request: quick search

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#142]
Do výpisu tabulek GD Writeru i do výpisu Transformací (top overview) bych dal quicksearch, jako když děláš input mapping nebo filtruješ SAPI tabulky v Storage.

![image](https://cloud.githubusercontent.com/assets/1427901/8111142/5c97c5bc-1060-11e5-9e0e-d1a2aaee9fb3.png)

**Comment by padak** [comment]
[Tady](https://connection.keboola.com/admin/projects/226/writers/gooddata-writer/devel) jich je 62 a už by to hodně pomohlo...

**Comment by ondrejhlavacek** [comment]
Nad tímhle už jsem přemýšlel a snažil se doptat tady - https://trello.com/c/XcY41wrS/152-quicksearch-field-in-tapi-transformation-list

Transformace jsou teď řešený jinak - víc hierarchicky: Stránka se seznamem bucketů => stránka se seznamem transformací => Detail transformace. Tj. quicksearch může hledat jen v tý svojí úrovni. Writer to takhle hierarchizovaný nemá a míchá jednotlivý konfigurace se seznamem jejich tabulek na jednu stránku, což znemožňuje poslat odkaz na jednu konfiguraci, vždy pouze na celý writer a tu konfiguraci si musíš doklikat sám. 

Potřebu quicksearche asi chápu, rád bych taky sjednotil procházení v hierarchii (už teď na to máme 3 různý styly: writer, transformace, extraktory), pomohl by ten quicksearch kdyby uměl hledat jen v aktuálním seznamu, nebo potřebuješ, aby se uměl zanořit (transformace i writer ty podřazený položky naštěstí teď znají)? Kterej z těch dvou přístupů writer/transformace (nezávisle na tom vyhledávání) vám přijde lepší?

CC @Halama @JakubMatejka @padak @kacurez

**Comment by Halama** [comment]
3 různý styly imho nevaděj. Přemýšlím že bych ten quicksearch zkusil dodělat do writeru.

**Comment by padak** [comment]
Mě přišlo úplně super jak to bylo dřív - jedna stránka a v ní jsi rychle proklikal a našel co hledáš - a k tomu scházel jen quick search. Dneska je to tak, že musíš všechny buckety rozklikat do novýho tabu a tam se dívat jestli je tam to co hledáš.

**Comment by Halama** [comment]
Zatím jsem to udělal pro writer, zkuste na to mrknout.
![image](https://cloud.githubusercontent.com/assets/903531/8210420/3060f7dc-1512-11e5-88fc-ec0594793241.png)

**Comment by ondrejhlavacek** [comment]
Jo, to vypadá super, udělám to stejně na transformacích a ta hlavička bude ještě klikací a povede na detail bucketu!

**Comment by Halama** [comment]
nebude ta klikaci hlavicka matouci?

**Comment by Halama** [comment]
clovek by cekal ze se to rozbali asi

**Comment by ondrejhlavacek** [comment]
NOJO sakra ... ale pak kde třeba zobrazit popisek bucketu? A kde ho editovat? :-/

**Comment by Halama** [comment]
hmm tak to nevim :)

**Comment by padak** [comment]
co to přesně prohledává? dal jsem "carts" a dostal jsem tohle:

![image](https://cloud.githubusercontent.com/assets/1427901/8228345/48561ad8-15ae-11e5-9c00-5c670c7de969.png)

([tady](https://connection.keboola.com/admin/projects/489/writers/gooddata-writer/Main))

**Comment by Halama** [comment]
je to fuzzy search stejně jako jinde. Bere to sekvenci znaků za sebou. Asi to bude chtít nějak poladit ještě. piCker_tARgetTS

**Comment by padak** [comment]
wow, to je docela cool :) Zkusi jsem `amorders` a funguje to vlastně super :-)

**Comment by ondrejhlavacek** [comment]
hotovo i pro transformace
