### ISSUE TITLE
TAPI mi ukazuje bucket co neexistuje v SYS

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#143]
V projektu [zde](https://connection.keboola.com/admin/projects/478/transformations) mi sys.c-tr-testsalek bucket háže error:

 ![image](https://cloud.githubusercontent.com/assets/1427901/8118872/eae317dc-1091-11e5-97bd-d2da91caf0e0.png)

(link na PT [tady](https://papertrailapp.com/groups/23635/events?q=transformation-2fe9d8aaaea4879a5fc9b1e398cd678e))

**Comment by Halama** [comment]
nekdo ten bucket smazal primo z konzole asi takze tam zustala konfigurace, tu jsem ted smazal pres API
