### ISSUE TITLE
Weird buttons after token is refreshed

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1432]
![image](https://user-images.githubusercontent.com/4319320/34852902-4fbda8e2-f731-11e7-96b0-22fa4a85b627.png)

cancel and refresh don't make any sense here, they suggest that the token was on really refreshed yet.
`Ok` would  be better

**Comment by kacurez** [comment]
There is a message saying `Token has been refreshed..` so imo it's clear what happened. If you click on Refresh button again it will refresh again..
There is a similar behaviour in Authorization modal when generating external link, after the link gets generated the button caption Generate Link changes to Regenerate Link:
![image](https://user-images.githubusercontent.com/1412120/34864984-12eb3d58-f777-11e7-9a7f-0626a91de84a.png)

If there should be a change I would suggest to either:
1. Hide refresh button and rename cancel button to "Close"
or
2. Rename refresh button to "Refresh again"

**Comment by ujovlado** [comment]
I would vote for “refresh again” if we decide to keep it this way. Otherwise I prefer Odin’s solution. I don’t know about situation when you need to refresh token which was refreshed few minutes ago.

**Comment by Halama** [comment]
I am also for Odins solution. It is a same situation as in sandbox create:
![image](https://user-images.githubusercontent.com/903531/34866986-c672a35a-f77e-11e7-9488-22c4be3a9298.png)

**Comment by kacurez** [comment]
what is Odins solution actually?its not clear to me, he suggested: 
>`Ok` would be better

so rename refresh button to Ok or rename Cancel button to Ok and hide other?

**Comment by Halama** [comment]
Leave there only Close button like in sandbox create

**Comment by kacurez** [comment]
ok I thought its something different than what I suggested :)
>Hide refresh button and rename cancel button to "Close"

**Comment by Halama** [comment]
aha to jsem necetl to bylo pod obrazkem :)
