### ISSUE TITLE
TAPI SANDBOX 

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#144]
po spuštění se vrací link na job místo okna co ukazuje jak se sandbox připravuje. Nezjistím tak například jaký jsou sandbox credentials, apod.

**Comment by ondrejhlavacek** [comment]
@padak To je tak záměrně. Credentials na sandbox zjistíš bokem a pokud je už máš (90% času), tak se nemění a nemusíš nic dělat. Ale asi by šly ty credentials rovnou ukázat v tom okně voleb na vytváření sandboxu, co myslíš?

**Comment by padak** [comment]
já se bez nich nikdy neobejdu. přepínám projekty a potřebuju vědět jakej sandbox mám použít. navíc vždycky koukám na to jak to jede, protože to třeba nemusí doběhnout, atd. takhle dám vyrobit sandbox, nevím kam se připojit (nemám ani info o tom, že jsou moje credentials smazaný - což můžeme udělat) a nemám jak se dozvědět že je sandbox hotovej - takže musím vždycky otevřít job v druhým okně.

kompromis (pokud tohle dává smysl - pro mě je to krok zpět) by mohl bejt něco jako když pustím ve starým UI ručně orchestrátor, tak mi nabídne jít do jobů:
![image](https://cloud.githubusercontent.com/assets/1427901/8138768/15283a24-114e-11e5-9ca8-49363e7accf6.png)

**Comment by Halama** [comment]
jo tohle nějak vyřešíme ty credentials bys tam určitě měl vidět, mělo by tě to vést. Modaly se ale snažím celkově potlačit a nechávám je jenom jako confirm.

**Comment by padak** [comment]
Jen doplnění kontextu - já nejdu primárně pro credentials, ale pro jméno DB ve který to mám najít. Navíc aktuálně tam credentials nejsou. Možná jsem blbej, ale menu co mi ukázalo credentials tam nikde nevidím - ha, jmenuje se to "Sandbox" a je to nahoře.

**Comment by Halama** [comment]
Nacpal bych to asi k tomu jobu (jako nový panel) nebo zase ted zpět do toho modalu. V detailu té transformace by asi link na sandbox stránku mohl zůstat? Na té stránce bych asi alespoň trochu popsal nebo odkázat k čemu sandbox je.

**Comment by ondrejhlavacek** [comment]
Credentials můžu nechat načíst v tom modalu, ale určitě ho nechci nechávat otevřený, abys mohl sledovat jeho průběh. Mělo by se to srazit někam na stranu, a tam bys měl vidět svoje aktuální joby. Do té doby, než to bude, tam dám ten checkbox "go to job detail".

**Comment by Halama** [comment]
ten checkbox je dost hrozna vec, stejne nic neresi ne? Ty credentials by se mohly ukazovat v detailu jobu ne, na nejakem novem accordionu?

**Comment by ondrejhlavacek** [comment]
No v současný době, kdy je to celý v modalu, máš všechno na jednom místě. vybereš si režim sandboxu, vidíš credentials a kdy to doběhlo, nemusíš nikam odcházet. S tím, jak chceme ty modaly vyhodit, je potřeba zjednodušit uživateli přístup k těm věcěm, který měl před tím po ruce. 

Vidím tyhle nástroje 

- credentials

a) zobrazit je v modalu při nastavování režimu sandboxu - to je pro mě asi nejvíc jednoduchý a jsou vždy aktuální
b) zobrazit je v detailu jobu - problém je perzistence - ty credentials nejsou ve vazbě na job, vedlo by to k tomu, že bych si mohl myslet, že výsledek jobu bude pod těmahle credentials navždy (zatímco fskutečnosti se přepíšou dalším jobem). mohl bych teda v tapi udělat jedno extra pole na jméno databáze, ale to je takový polovičatě ošklivý řešení. 

- stav jobu

1) checkbox, kterej tě po zavření okna přenese na detail jobu/seznam jobů - hnus, ale můžeš hned sledovat stav jobu a nemusíš čekat na zelený pruh a znova klikat
2) někde po straně zobrazit běžící joby - ideálka, ale to zatím nemáme

Co myslíte?

**Comment by ondrejhlavacek** [comment]
Zkouším zatím a) 

![development_-_transformations___bucket_sys_c-tr-testsuite___transformation_redshift](https://cloud.githubusercontent.com/assets/497675/8195363/faccd554-1436-11e5-8406-c1cf09d59a00.png)

**Comment by ondrejhlavacek** [comment]
Tak zatím to mám takhle...

![screen shot 2015-06-16 at 15 48 28](https://cloud.githubusercontent.com/assets/497675/8196289/2b5c304a-143f-11e5-95b3-95661f218902.png)

Nejsem si teda jistej, jestli je to dobrý... Ať se snažím vymyslet cokoliv, je to nějakej bastl. Nápady?

Tohle se kdyžtak dá revertovat commitama 4bbc7744be180e2092ffb9e30e942a0781289f85 a 17f5bad58f44c29eb694e903b166725f63b1866c.

**Comment by Halama** [comment]
Nic moc mě nenapadá. Bud to  nechat takhle nebo to udělat tak jak to bylo ve starém.
