### ISSUE TITLE
manage token name not required

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1440]
![image](https://user-images.githubusercontent.com/4319320/34993411-97ecc3d0-fad0-11e7-8983-0c83ce0947a5.png)

fails after the dialog is closed

**Comment by ondrejhlavacek** [comment]
Nerozumím?

**Comment by odinuv** [comment]
je na backendu povinny a v UI neni (nebo obracene)

**Comment by ondrejhlavacek** [comment]
Prázdnej form nejde odeslat

![image](https://user-images.githubusercontent.com/497675/36028825-d0431ee0-0da0-11e8-8166-a727aa1bdb2c.png)

A jestli je v UI povinný a na backendu není, tak to nemá co vyhazovat chyby

**Comment by odinuv** [comment]
hmm, tak uz asi nevim
