### ISSUE TITLE
organization editable

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1442]
admins have editable organization in project settings, but it is not and never will be editable

![image](https://user-images.githubusercontent.com/4319320/35016007-1d2dc68e-fb17-11e7-8685-340f4bc51cec.png)

**Comment by pivnicek** [comment]
huh, I think I did that on purpose.  Had a few requests to change project's organization

**Comment by odinuv** [comment]
i think it can be done only via manage api, so i believe it can never work on that page

**Comment by pivnicek** [comment]
I dunno, I think you can,  https://github.com/keboola/connection/blob/master/application/modules/admin/controllers/ProjectsController.php#L655
Have you tried it?
It is only available to maintainers/supers I think.

**Comment by pivnicek** [comment]
lol, well there doesn't seem to be any organizations in the dropdown when I try it 

![image](https://user-images.githubusercontent.com/569139/35017136-da3634ce-fb1b-11e7-837b-a8303fd93987.png)

It will only work for maintainers

**Comment by pivnicek** [comment]
original issue: https://github.com/keboola/kbc-ui/issues/1016

**Comment by pivnicek** [comment]
re: empty organization dropdown: https://github.com/keboola/connection/issues/880

**Comment by pivnicek** [comment]
so imho making the edit button available to only maintainers would solve this and https://github.com/keboola/connection/issues/880

**Comment by Halama** [comment]
fix bude dnes nasazeny
