### ISSUE TITLE
unauthorized access

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1443]
make the logo clickable or add a link to provide a way to get home

![image](https://user-images.githubusercontent.com/4319320/35016573-8178012a-fb19-11e7-9f49-fdb537d313c8.png)

**Comment by pivnicek** [comment]
this applies to 404 too

**Comment by Halama** [comment]
yes it should be clickable on all pages like
![image](https://user-images.githubusercontent.com/903531/35335176-1070f5f2-0115-11e8-9783-0766948d6adf.png)
