### ISSUE TITLE
Token wording confusing

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1445]
"Make sure to copy it, you won't be able to see it again" - since the "Send Token" feature is there, it doesn't make much sense. Also we shoud encourage people to send the token instead of copying it somewhere, so maybe display the "send token" button there ?

**Comment by kacurez** [comment]
pre refresh tokenu: Admin token sa neda poslat takze tam to copy to clipboard musi byt. Naviac send token otvara dalsi modal co z refresh modalu pojde blbo.
pre prave vytvoreny token: tam by sa to dalo, tj dat moznost copy it or send it -> otvori modal
