### ISSUE TITLE
Disable "delete rows" if incremental is turned off in transformations output mapping

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1447]
It's pointless and can be confusing.

**Comment by Halama** [comment]
Ještě řešíme jestli ta feature celkově vůbec dává smysl https://keboola.slack.com/archives/C02CGRFH8/p1516268128000307

**Comment by ondrejhlavacek** [comment]
Dál bych to asi evidoval tady. Udělám rychlej research, jestli se to v nějakejch konfiguracích používá.

**Comment by ondrejhlavacek** [comment]
Docela hojně to používaj transformace (47 výskytů v US, 1 v EU), podle letmýho checku konfigurace to vypadá, že tomu i rozumí (jsou to inkrementy). Docker appky to naproti tomu nepoužívaj, jenom ve dvou případech Matúš a Viktor Šohájek (US), v EU 0.

Writer 

https://connection.keboola.com/admin/projects/258/writers/keboola.wr-db-snowflake/347859096

Queries (hodně nahrubo)

```sql
# Configs are only docker apps
CREATE VIEW "parsable_us_configs" AS SELECT *
FROM "us-configs"
WHERE CHECK_JSON("configuration") IS NULL;


SELECT
    *
FROM 
    "parsable_us_configs" c,
    LATERAL FLATTEN(input => PARSE_JSON(c."configuration"):"storage":"output", path => 'tables') outputTables,
    LATERAL FLATTEN(input => PARSE_JSON(outputTables.value), path => 'delete_where_values') deleteWhereValues
WHERE 
    "isDeleted" = 0
;

# Rows are only transformations
CREATE VIEW "parsable_us_rows" AS SELECT *
FROM "us-rows"
WHERE CHECK_JSON("configuration") IS NULL;

SELECT
    *
FROM 
    "parsable_us_rows" c,
    LATERAL FLATTEN(input => PARSE_JSON(c."configuration"):"output") outputTables
WHERE 
    "configurationVersion_to" = ''
    AND outputTables.VALUE:"deleteWhereColumn" != ''
;

# Configs are only docker apps
CREATE VIEW "parsable_eu_configs" AS SELECT *
FROM "eu-configs"
WHERE CHECK_JSON("configuration") IS NULL;

SELECT
    *
FROM 
    "parsable_eu_configs" c,
    LATERAL FLATTEN(input => PARSE_JSON(c."configuration"):"storage":"output", path => 'tables') outputTables,
    LATERAL FLATTEN(input => PARSE_JSON(outputTables.value), path => 'delete_where_values') deleteWhereValues
WHERE 
    "isDeleted" = 0
;

# Rows are only transformations
CREATE VIEW "parsable_eu_rows" AS SELECT *
FROM "eu-rows"
WHERE CHECK_JSON("configuration") IS NULL;

SELECT
    *
FROM 
    "parsable_eu_rows" c,
    LATERAL FLATTEN(input => PARSE_JSON(c."configuration"):"output") outputTables
WHERE 
    "configurationVersion_to" = ''
    AND outputTables.VALUE:"deleteWhereColumn" != ''
;
```

**Comment by ondrejhlavacek** [comment]
V docker appkách to teda asi po vyřešení těch 2 případů můžeme kompletně vypnout, ale pokud chceme přehazovat transformace do docker appek, tak to možná nebude tak horký :-). Nějaký návrhy, co s tím? Mám se zkusit ozvat pár projektům a zjistit use case a jestli nejde vyřešit jinak?

**Comment by ujovlado** [comment]
Nefixnut to teda v UI? T.j. kym nezaskrtnem "Incremental" nebudem mat moznost editovat "Delete rows"

**Comment by ondrejhlavacek** [comment]
Skrýt nebo jenom disablovat? To by asi šlo.

**Comment by ujovlado** [comment]
Imho by bolo lepsie skryt to, no neviem ako by to vyzeralo. Vyskusal by som to a uvidi sa.
