### ISSUE TITLE
Display token age

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1448]
from when it was refreshed, not created - so its like aws:

![image](https://user-images.githubusercontent.com/4319320/35105117-1ce79a56-fc6b-11e7-93f6-6623cf54062b.png)

**Comment by kacurez** [comment]
there is no support for that on the backend i.e no `refreshed` timestamp property

**Comment by Halama** [comment]
Až bude [tenhle job](https://travis-ci.com/keboola/connection/builds/67735783) zelenej tak to bude nasazené na backendu.
