### ISSUE TITLE
Search v KBC

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1449]
In extractors, try to search for "ftp" - you'll get tons of results, but almost all of them doesn't match to search query

http://take.ms/5szCR

**Comment by janmichek** [comment]
Souhlas, ten fuzzy search mi tam taky prijde v tomto pripade zbytecny. Na druhou stranu nejaka tolerance by byla fajn. Napr query 'word' najde Google Adwords

**Comment by ondrejhlavacek** [comment]
Asi by stačilo vypnout fuzzy pro description a další fieldy a nechat tam jenom name/shortDesc. Mrknu na to.

**Comment by ondrejhlavacek** [comment]
https://keboola.productboard.com/inbox/notes/1120169

**Comment by ondrejhlavacek** [comment]
Hraju si s tím a zkusil jsem nahodit `fuzzaldrin`, kterej umí výsledky skórovat.

Aktuální vyhledávání používá fuzzy na `name` a `description` (shortDesc), zkusil jsem upravenej search podle

```
      fuzzy.match(filter, component.get('name')) ||
        (fuzzaldrin.score(description, filter) > 0.09) ||
        description.indexOf(filter) >= 0
```
tj. 
- `fuzzy` na `name`
- `fuzzaldrin` s vysokým skóre na `description`
- přímej match filtru na `description`

Resulty:

![image](https://user-images.githubusercontent.com/497675/35330892-893a02ae-0105-11e8-9c23-efc385d78dbb.png)

![image](https://user-images.githubusercontent.com/497675/35330895-8ff44348-0105-11e8-96cf-f5ede5f35652.png)

![image](https://user-images.githubusercontent.com/497675/35330899-955611e0-0105-11e8-8299-8d9454bec8c3.png)

Tady `fuzzaldrin` zařídí, že tam mailkit zůstává, i když fuzzy na `name`  nematchne a v description přímo string `email` není.

Pokud snížím citlivost `fuzzaldrin` na 0.08, tak se výsedek `ftp` searche změní na 

![image](https://user-images.githubusercontent.com/497675/35330929-b08c6efa-0105-11e8-905e-8b6b13a462fe.png)

a je tam první false positive. Takže bych nechal spíš vyšší hranici, pokud nenajdeme nějakej příklad, kde to je špatně. 

Dost by tomu pomohly nějaký tags/keywords, který by nebyly vidět, ale který by byly součástí searche. 

K hraní v PR https://github.com/keboola/kbc-ui/pull/1451 nebo v branchi `unfuzzy-search`.

**Comment by odinuv** [comment]
za me radsi at je tam min false positives, ted to na `snow` vrati 15 extractoru :/

**Comment by ondrejhlavacek** [comment]
`snow` by teď vrátil

![image](https://user-images.githubusercontent.com/497675/35332226-8fa55c2e-010a-11e8-897b-85a0745299ee.png)
