### ISSUE TITLE
Close table detail with ESC

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1465]
Tahle stránka se tváří jako modal, má vpravo nahoře `x`, takže bych čekla, že jde zavřít ESCapem.

![image](https://user-images.githubusercontent.com/497675/35572057-0da72b84-05d4-11e8-8ea4-5b873c646a86.png)

**Comment by kacurez** [comment]
Funguje to ale musis dat tomu dialog focus tj kdekolvek kliknut, co uznavam ze neni ono. Chce to dalsi debug..
