### ISSUE TITLE
UI Pigeon Feedback

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1469]
TBA

**Comment by Halama** [comment]
V tech popiscích např. emailu by bylo dobrý víc popsat k čemu to je. Místo `Email address generated by Pigeon.` něco jako `Sem posílejte emaily s CSV přílohou. Nově přijaté emaily budou naimportovány do storage po každém spuštění`.

**Comment by Halama** [comment]
Trochu mě tam mátlo to pořadí a míchání editovatelných/neditovatelných věcí. Bylo by super kdyby z toho nějakým způsobem na první pohled bylo jasné jak to funguje. Tzn. 1. pošlu mail s přílohou na vygenerovanou adresu. 2. spustím extractor a mám data

Nějaký moje pokusy, co myslíte?
btw. chybí tam ještě ten primární klíč.

![image](https://user-images.githubusercontent.com/903531/35679979-32deb008-0759-11e8-92e4-2a29be3ef864.png)


![image](https://user-images.githubusercontent.com/903531/35679451-6234d140-0757-11e8-9bd2-9f0a18fe5518.png)

**Comment by janmichek** [comment]
S tim poradim / flow je to dobrej point. Ja uz jsem se nad tim ani nedokazal zamyslet jako user, kdyz jsem do toho cumel porad :D 
Jenom bych to prohodil, protoze 1. nastavim, 2. posilam, 3. pouzivam vysledek. Sekce 'Import Settings' mi prijde vystizna. Jeste premyslim jak pojmenovat ty dalsi 2. Jestli dohromady / zvlast. Dejte mi chvili ...

**Comment by janmichek** [comment]
Myslel jsem to takhle, ale ted kdyz vidim kolik je tam tech popisku tak vizualne je do docela bordel.
![image](https://user-images.githubusercontent.com/15363559/35682287-75df9f1e-0760-11e8-9208-b39360462a3c.png)

**Comment by Halama** [comment]
To je mozna zas az moc roztristeny a ten email by imho mel byt na prvnim miste. Mozna bude stacit to jak jsem daval na prvnim screenu. Takze v podstate jenom presunout du destination table do toho formu. 
A doladit ty popisky.

**Comment by Halama** [comment]
Ten delimiter a enclosure jsou advance veci a nemuseli by vlastne byt tolik videt. Nemame nejakou novou skryvaci komponentu? Mam pocit ze neco takoveho probehlo.

**Comment by janmichek** [comment]
JJ tady https://camo.githubusercontent.com/72d9ad3d32ae589ced68af0508e307168ca91c12/687474703a2f2f672e7265636f726469742e636f2f7256586a496f744a354f2e676966

**Comment by Halama** [comment]
Ty jo to by mozna slo. Nahore v prvni radku email a destination ktere se nedaji menit. 
A druhy radek by byla tahle komponenta s titlem "Import Settings".

**Comment by janmichek** [comment]
@kacurez  muzes se prosimte postarat o napojeni Primary Key? Front jsem k tomu 
 prave udelal. Nedokazal jsem z predchzi verze extraktoru vykoukat na co ten PK je, takze ani nevim co napsat do helpu a placeholderu. Diky! https://github.com/keboola/kbc-ui/commit/49b472affdce51b2c67316441cd4cb60d3259208

**Comment by janmichek** [comment]
Jeste chci udelat aby ta sipka signalizovala rozbaleny / zabaleny stav + aby se po ulozeni zabalilo nastaveni. Uz to dneska nestiham ./ Jinak myslim posun 
![token error](https://user-images.githubusercontent.com/15363559/35804122-b3262276-0a76-11e8-8f1c-c52c9d2678a6.gif)

**Comment by kacurez** [comment]
zda sa ze pigeon nepodporuje PK takze zatial nemoze byt na ui, vytvoril som nato issue(cc @JakubMatejka )
https://github.com/keboola/pigeon/issues/12

**Comment by Halama** [comment]
ty jo, rekl bych ze dobry podle toho screenu

**Comment by Halama** [comment]
jinak PK, incremental se nastavuje skoro u kazdeho extractoru, tak ty help texty zkopiruj odtamtud. Kdyz jsem na to koukal minuly tyden tak je to na tolika mistech ze by se to imho dalo vytahnout do komponent.

**Comment by Halama** [comment]
Např. Simple S3 extractor
![image](https://user-images.githubusercontent.com/903531/35818540-a991abd4-0aa0-11e8-81cf-1f2930842ce6.png)

Db (MySQL) extractor
![image](https://user-images.githubusercontent.com/903531/35818596-cadd93f2-0aa0-11e8-9f02-242b8aa130db.png)

CSV Import
![image](https://user-images.githubusercontent.com/903531/35818623-dd5bdaca-0aa0-11e8-8926-9c9c15407678.png)

a asi i dalsi

**Comment by janmichek** [comment]
Dodelal jsem Primary Key input podle examplu (Select + help block text + placeholder) s dummy funkcema k napojeni.
Zasek jsem se na tom chovani rozbalovatka (dynamicka ikona + zavreni po savnuti). Nedari se mi vypropagovat ty props/state promeny aby to fungovalo. Navrhuju to nechat zatim s timhle hloupejsim chovanim, nepripada mi to jako blocker. Najlos na ten zabalovaci form generickou funkci ktera je soucasti s3-aws-ex. Jeste to ale neni ready k rebasnuti, bylo by to pak podmineny nasazenim s3-aws-ex. Co myslite?

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/36037276-970b5176-0dbc-11e8-9eaf-99c7e433eca6.png)

Udělal bych to jako obyč text bez odrážek. 

Nefunguje mi přidání Primary Key. Píše to

```
warning.js:45 Warning: 
Failed propType: 
Invalid prop `primaryKey` of type `object` supplied to `ConfigurationForm`, 
expected `string`. Check the render method of `Index`.
```

![image](https://user-images.githubusercontent.com/497675/36037419-0161da18-0dbd-11e8-8a31-f7b3dd822a1a.png)

Zvládlo by se dát všechno na jedno účaří s labelama? Klidně později, ale bylo by to krásně čistý.

Co mít destination / imported table editovatelnou jako u CSV Importu? U komponent, ze kterejch leze jen jeden soubor, by to asi bylo fajn, ať si to lidi můžou pojmenovat libovolně.

![image](https://user-images.githubusercontent.com/497675/36037580-75331e02-0dbd-11e8-9a11-e044afc5a453.png)

**Comment by ondrejhlavacek** [comment]
Jinak mi to přijde dobrý, ten accordion je možná fajn takhle od boku, takový čistčí než CSV Import, kde to je furt otevřený.

**Comment by Halama** [comment]
pigeon prave vubec neresi jmeno tabulky a uzivatel to taky nemusi resit proste vzdy vrati jednu, stejne jako dark sky.

**Comment by Halama** [comment]
a PK se asi musi dodelat na backendu

**Comment by ondrejhlavacek** [comment]
Na backendu? Nefunguej v UI, backend jsem vůbec neřešil :-)

**Comment by Halama** [comment]
aha tak v ui by teda fungovat mel:)

**Comment by ondrejhlavacek** [comment]
Takže každá konfigurace dark sky a pigeonu si udělá vlastní bucket, ve kterým bude tabulka `data`? To není úplně dobrý pro vyhledávání nebo nějakou organizaci. Ale jsem pro konzistenci, takže pokud se na to shodnem, tak bych možnost vložit CSV do custom tabulky taky vyhodil a nechal tam default.

**Comment by ondrejhlavacek** [comment]
Neměl by zobáček accordionu reagovat na stav? Je furt dolů

![](http://g.recordit.co/1vy4puBtpc.gif)

**Comment by ujovlado** [comment]
Este 2 veci:

1. dvojity label (riesili sme aj v #1291)

```diff
diff --git a/src/scripts/modules/ex-pigeon/react/ConfigurationForm.jsx b/src/scripts/modules/ex-pigeon/react/ConfigurationForm.jsx
index 7e7fe21..9a60b0b 100644
--- a/src/scripts/modules/ex-pigeon/react/ConfigurationForm.jsx
+++ b/src/scripts/modules/ex-pigeon/react/ConfigurationForm.jsx
@@ -80,10 +80,7 @@ export default React.createClass({
           </Col>
         </FormGroup>
         <FormGroup>
-          <Col componentClass={ControlLabel} sm={4}>
-            Incremental
-          </Col>
-          <Col sm={8}>
+          <Col sm={8} smPush={4}>
             <Checkbox
               checked={this.props.incremental}
               onChange={this.onChangeIncremental}>
```

2. Je tam nadpis "Imported table" ... no este to len konfigurujem, nic som nespustil, tak neviem preco by tam malo byt, ze uz je importovana - chcelo by to imho zmenit na nieco rozumnejsie.

**Comment by janmichek** [comment]
> Udělal bych to jako obyč text bez odrážek.
ano, jem pro normalni text. me ten styl (velkej padding) listu taky vadi. Jedina moznost je tomu dat custom style, cehoz se naopak chceme zbavit.

> Nefunguje mi přidání Primary Key. Píše to
psal jsem ze je to pripraveny k napojeni tady https://github.com/keboola/kbc-ui/issues/1469#issuecomment-363296828 Jak je to teda s tim PK? @Halama  @JakubMatejka  Resime tyden jestli extractor ma/nema PK. Ja nedokazu posoudit, pls rozseknete to. Velkej tajem .] je na to issue tady https://github.com/keboola/pigeon/issues/12

> Zvládlo by se dát všechno na jedno účaří s labelama? Klidně později, ale bylo by to krásně čistý.
Nevim kam tim miris :) to je predmetem sjednocovani na kterym ted delam. Tenhle problem maji preci vsechny formulare napric aplikaci. Nerad bych na to seslal cutom styly. Takze odpoved je: ano, pozdeji.

> Neměl by zobáček accordionu reagovat na stav? Je furt dolů
@ondrejhlavacek ano prosim, porad mi tady https://github.com/keboola/kbc-ui/issues/1469#issuecomment-363296828

> nadpis "Imported table"
Zmenim na Output table. Ja to vykopiroval z Jobu.

![image](https://user-images.githubusercontent.com/15363559/36082781-d0d83026-0fac-11e8-8990-45bf02febcb6.png)

Mame na to issue, ten koncept neni uplne fajn. Pripisuju tvuj postreh s namingem. Doresime tady. https://github.com/keboola/indigo-ui/issues/93

> dvojity label 
Uvaha za tim byla nasledujici: Vzal jsem krajni priklad, ze budeme chtit pro volbu/skatulku vice checkboxu. Zatim to nemam kde dokumentovat, tak rozumim vasemu wtf. Jestli vam to prijde zbytecny, a staci na to Select, ten label odstranim.

![image](https://user-images.githubusercontent.com/15363559/36083307-40e4300a-0fb1-11e8-9fc0-aa17987748c6.png)

**Comment by janmichek** [comment]
help block na plain text DONE, 
'Imported table' -> 'Output table' DONE,
Incremental layout DONE - pokud se vam teda nelibi muj navrh. Zatim ten koncept davam do supliku

![image](https://user-images.githubusercontent.com/15363559/36083892-311d1e32-0fb8-11e8-8c2b-ea37967b0404.png)

**Comment by ondrejhlavacek** [comment]
Je ten incremental label za checkboxem tučně? Z toho screenu to pořádně nevidím.

**Comment by janmichek** [comment]
je to zazoomovany aby se to veslo na obrazovku -> na screenshot. Neres to .]

**Comment by ondrejhlavacek** [comment]
zobáček - https://github.com/keboola/kbc-ui/blob/2271f415047310e4b649954460f07fa877cc18fb/src/scripts/react/common/ConfigRows/Credentials.jsx#L86-L103

**Comment by janmichek** [comment]
@ondrejhlavacek https://github.com/keboola/kbc-ui/issues/1469#issuecomment-364911166
Ten kod jsem nasel a nechal se inspirovat. Jak jsem psal, nepodarilo se mi tu promennou 'isActive' vypropagovat vys, ale dam tomu jeste pokus.
Dalsi otazka byla, jestli nepockat na dokonceni tvyho konceptu extractoru a pak ho znovupouzit pro ex-pigeon, protoze vlastne duplikuju tvoji praci.

**Comment by ondrejhlavacek** [comment]
to záleží, pokud by používal config rows, tak jo, pokud ne, tak bych ho udělal solo.

**Comment by ondrejhlavacek** [comment]
Šipečku jsem dodělal, uložil jsem to do state React komponenty, pokud bys to chtěl uložit do globálního `localState`, dej vědět, předělám to, takhle to podle mě stačí.

**Comment by JakubMatejka** [comment]
Pardón za delší odpověď, bojoval jsem s tím, že mi nechodily notifikace. ;o( Podpora primárního klíče tam je (viz. https://github.com/keboola/pigeon/issues/12). Na žádný změny konceptů prosím nečekat, ať se to zbytečně neodsouvá donekonečna. Včera už bylo pozdě. ;o))

**Comment by kacurez** [comment]
@janmichek chces pomoct stym primary key alebo to skusis sam? je tam este nieco nacom to stoji, zeby som mohol popripade pomoct?

**Comment by janmichek** [comment]
@kacurez diky za nabidku. Dam tomu napojeni ted hodinu, kdybych se ztratil, ozvu se.

**Comment by janmichek** [comment]
Nemel by byt problem, predtim tam nebyla ta datova struktura, tak jsem mohl jenom fantazirovat, kam se to uklada.

**Comment by janmichek** [comment]
@kacurez 
zkus mi jeste poradit nez bych to na tebe hodil.
kdyz zadam PK 'id' tak mi extrakce zfailuje na 

> Output mapping does not match destination table: primary key 'id' does not match '' in 'in.c-keboola-ex-pigeon-355815644.data'.

pritom ve Storage jasne vidim ze tam takovej sloupec 'id' je.
Extrakce bez PK je ok.

**Comment by kacurez** [comment]
imo to znamena ze zapisujes do existujucej tabulky ktora nema nastaveny pk na stlpec id. Dodatocne nastavit pk cez output mapping sa neda. Takze to je imho ok. Skus v storage konzoli nastavit pk na ten stlpec a pust to znovu.
V skratke: ak tabulka existuje tak jej pk v storage sa musi rovnat pk ulozenom v konfigu pigeona.

**Comment by janmichek** [comment]
ok, pravdu mas. TO chovani je trochu divny, ale kdyz rikas ze je to ok .]
zkusil jsem i slozeny PK a funguje

**Comment by janmichek** [comment]
Za me je to ready, jeste pls checknete

Tady je PR https://github.com/keboola/kbc-ui/pull/1484
