### ISSUE TITLE
TAPI description

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#147]
Nebudu se dávat screenshot, když je to public, ale [tady ve starém UI](https://connection.keboola.com/admin/projects-new/444/transformations#/transformations/sys.c-tr-shionogi.concur-1) je vidět jak si někdo naformátoval popisek a [tady v novém](https://connection.keboola.com/admin/projects/444/transformations/bucket/sys.c-tr-shionogi/transformation/concur-1) to je stripnutý (=najednou blbě čitelný).

**Comment by Halama** [comment]
týká se u ostatní descriptions
