### ISSUE TITLE
kacurez ready to engage

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1470]
Toto je zoznam ui temat zoradenych podla priority ktorym sa planujem venovat, a ktore povazujem ze niesu zabrate alebo on-hold kvoli niecomu/niekomu. Vytvoril som to ako issue aby sme sa otom mohli bavit, pretoze pocitam ze tento zoznam sa bude menit. Nieco z toho staci naimplemntovat, a nieco najprv zanalyzovat, vydiskutovat alebo pozbierat podklady, spisat a naimplementovat. 

- [x] transformation output mapping (pr done, waiting for review) https://github.com/keboola/kbc-ui/issues/1466
- [x] table preview - show component origin (pr done, waiting for review) https://github.com/keboola/kbc-ui/issues/1488
- [x] get rid of static state from json editor
- [x] gooddata writer ui
- [ ] basic component dependencies graph

https://github.com/keboola/kbc-ui/issues/1488

Privitam dalsie napady...

**Comment by Halama** [comment]
tohle ti nestaci? :)

**Comment by ondrejhlavacek** [comment]
Ten dependecies graph je to vizuální zobrazení toku dat mezi tabulkama a komponentama? S tím bude souviset tohle - https://github.com/keboola/transformation-bundle/issues/94

**Comment by kacurez** [comment]
@Halama staci len to pisem zhruba ako to vidim a chcem mat istotu(formou pripadneho feedbacku) ze to je cajk predtym nez sa do niecoho pustim ;)

@ondrejhlavacek jj budem sledovat tu issue, alebo ak to uz mate nejak rozhodene tak sa do toho nebudem zbytocne montovat, mam to v zozname na neskor(later :))

**Comment by ondrejhlavacek** [comment]
@kacurez pokud jsi to chtěl překreslovat na frontendu, tak teď je asi ideální čas, můžete se dohodnout, do jaký struktury to má to api nastavit, aby to nemuselo bejt všechno zpětně kompatibilní.

**Comment by janmichek** [comment]
@kacurez hele mel bys vyhledove cas sjednocovat UI komponenty? koukam ze se chylis ke konci xD Predstava je, ze bys vymenoval komponenty, ktery zdokumentuju v Indigu a budeme to ladit

**Comment by kacurez** [comment]
@janmichek to by sa malo robit priebezne a nie plosne naraz ci? Myslim tym ze sucastou kazdej vacsej upravy ui by malo byt vyextrahovanie komponent do indiga pretoze sa pritom riesi dany "ux" problem komplexne do hlbky a tym sa zaroven zvaliduje vyuzitie komponent. Prechadzat cele ui do sirky a vyberat to zvlast mi pride a neefektivne.

**Comment by janmichek** [comment]
Urcite souhlas, nemam ted zadny megapack ui komponent k vymene. Budu to tak salamovat s prihlednutim k tomu co by opravdu pomohlo uzivatelum v ovladani aplikace. Pripravim si konkretne co bych chtel a muzem to spolecne v pondeli zvalidovat

**Comment by janmichek** [comment]
Nasel jsem tyhle 3 veci, na ktery bys mohl mrknout

**Comment by janmichek** [comment]
@kacurez  Nasel jsem tyhle 3 veci na ktery bys mohl mrknout:
Novy detail orchestrace - castecne se to resilo tady. Vetsi vec https://github.com/keboola/kbc-ui/issues/1800

2. tohle, az bych na to pripravil demo https://github.com/keboola/indigo-ui/issues/180

3. pomoc s vymenou ikon, najit vhodny zpusob sizovani a implementace https://github.com/keboola/indigo-ui/issues/178

az budes mit cas, tak se stav. Vysvetlim ti to podrobneji. 
Nebo alternativne muzes mrknout sem https://github.com/orgs/keboola/projects/14 a sem https://github.com/keboola/indigo-ui/issues kdyby ti neco prislo zajimavy

**Comment by kacurez** [comment]
@janmichek gooddata writer ui este neni dokoncene takze dalej pokracujem natom. Potom tam mam v pipeline reviziu fb ex = fixy/featury co sa nahromadili za poslednu dobu, to je uprava docker komponenty + ui.
Z toho co pises:
1. by sa dala
2-5 ma moc nezaujali. 
6. tam sa stale caka na Jacka(vid moj posledny koment v tom PR) ale kedze niesu ziadne tlaky na dotiahnutie tak sa nato asi vybodnem a poriesi sa to az s novou konzolou. 

V ui sa okrem ineho sustredim na odstranenie coffee scriptu pretoze nam tam vznika technologicky dlh. Takze oto lepsie ked je issue s ktorou sa nejaky kus coffee scriptu odstrani (ui gooddata writer/ orchestraci / konzola..)

**Comment by janmichek** [comment]
Fajnovy, diky za zajem. Brzy sepisu issue, jeste to chci trochu projackovat.

**Comment by janmichek** [comment]
Nasel jsem jeden engagement pro tebe .] Vcera o tom zrovna mluvili GG a jeho parta. Nevidim duvod to nemit https://github.com/keboola/kbc-ui/issues/1547
