### ISSUE TITLE
TAPI - SQL kod vytejká ven

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#148]
[Tady](https://connection.keboola.com/admin/projects/478/transformations/bucket/sys.c-tr-tes-pd/transformation/ccs) je vidět SQL, které vylejzá z okraje ven.

![image](https://cloud.githubusercontent.com/assets/1427901/8138598/8fb37634-114c-11e5-9100-49124c8e8eb0.png)

**Comment by Halama** [comment]
@ondrejhlavacek dělá to ten table layout, pokud nad tím vyhodím class `table` začne to fungovat
