### ISSUE TITLE
Guide Mode DB update

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1483]
![image](https://user-images.githubusercontent.com/497675/36152633-f2d2d756-10cb-11e8-8191-4a281188da87.png)

1) všechny tabulky a sloupce změnit na lowercase, je možný použít snake case (`person_per_car`) nebo (upper) camel case (`PersonPerCar`), je jedno co z toho, ale mělo by to bejt konzistentní pro celej Guide Mode. 

![image](https://user-images.githubusercontent.com/497675/36152743-50d861c2-10cc-11e8-9527-f27935af12fa.png)

2) Tabulku `CARS` přejmenovat na `CountriesCarsCount`, sloupce na `Name` a `TotalCarsCount`

![image](https://user-images.githubusercontent.com/497675/36152872-bd471b32-10cc-11e8-955d-58638aff56cf.png)

3) Tabulku `POPULATION` přejmenovat na `CountriesPopulation`, sloupce na `Name`, `Population`

4) V transformaci spočtená metriku `PERSON_PER_CAR` bych použil spíš obrácenou `CarsPerCapita`

**Comment by janmichek** [comment]
@ondrejhlavacek  zkousel jsem to prejmenovani. Nikde jsem nenasel zpusob ALTER, ale zkusil jsem to hacknout tak, ze naklonuju a potom smazu puvodni. Nicmene mi to automaticky uppercasuje. Nejaky napad? 
![token error](https://user-images.githubusercontent.com/15363559/36184057-e0901e12-1131-11e8-97dc-0b9b145bb8f3.gif)

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/36194671-f2988002-116a-11e8-9d62-116a178ea72b.png)

tyjo, už vidím, že se to povedlo? pokud něco takovýho nejde, tak je tam vždy `SHOW SQL`, kde to jde ručně upravit a jdou tam přidat double quotes `"` a napsat to malejma. bez double quotes se všechno převádí na velký

**Comment by janmichek** [comment]
jj, zrovna na tom delam.
KOukam ze je to dost nekonzistentni, tak asi poresim rovnou vsechno, ne?
Od odina mam zelenou ze to muzu prejmenovat, jen pak musim upravit dokumentaci

![image](https://user-images.githubusercontent.com/15363559/36195086-8df03dc8-116c-11e8-9ac5-8af6a3054d5a.png)

**Comment by ondrejhlavacek** [comment]
Klidně bych řešil jen ty tabulky pro Guide Mode (ty do Opportunity nešahaj, ne?), ať si nepřiděláváš práci.

**Comment by janmichek** [comment]
Jasny, moc jsem se rozvasnil, vratil jsem zpet

**Comment by janmichek** [comment]
@ondrejhlavacek  jaj, se zastrelim. Kdyz to projizdim v GM tak jsem zjistil ze tabulku 'countries_population' to ulozi do Storage jako 'countries-population' takze pak vznikne podobny nekonzistentni wtf. Prosim porad mi co navrhujes, nebo pripadne jestli si ten task nechces prevzit. Uplne nejsem SQL kral, klidne se tim prokousu, ale zabere mi to neumerne casu. Zakladni idea je aby ten query vypadal konzistentne notaci a user nemusel zbytecne premyslet proc je to tak. Diky

**Comment by ondrejhlavacek** [comment]
Sakra! To mi nedošlo :-( v tom případě bych změnil jen `snake_case` na `kebab-case` a je to v pohodě. Tohle se sice uživatelům bude úplně běžně dít, ale asi bych je tím teď nezatěžoval. 

Klidně to proklikám a změním - je potřeba to ještě někde měnit kromě contentu v UI?

**Comment by ondrejhlavacek** [comment]
Kua, ale to je nějaká blbost, tabulky s podtržítkama by to mělo umět normálně naimportovat, jdu se na to mrknout.

![image](https://user-images.githubusercontent.com/497675/36247592-d819eb24-1234-11e8-9d3b-a116fb5f49c2.png)

**Comment by ondrejhlavacek** [comment]
Dělá to UI, to bych teda teď nemodifikoval a jenom by se mohly tabulky v DB přejmenovat na `kebab-case`, to by mělo pak bejt co nejvíc straightforward. Dej vědět, jestli to mám udělat.

**Comment by janmichek** [comment]
ok, jdu na kebab xD

**Comment by janmichek** [comment]
@ondrejhlavacek help me, pls.

Nakonec mi z toho vylezl tenhle funkcni prikaz, bylo potreba mixovat notaci, kvuli tomu jak se to uklada. Takze mi z toho vylezl nasledujici query:

`CREATE TABLE "cars-population" AS SELECT "countries-cars-count".*, "countries-population"."population", ("countries-population"."population" / "countries-cars-count"."total_cars_count") AS "cars_per_capita" FROM "countries-cars-count" JOIN "countries-population" ON "countries-cars-count"."country" = "countries-population"."name"`

coz problem nevyresilo, tak ja nevim co s tim?

to uz rovnou muzu nechat tu puvodni verzi po fixu
https://github.com/keboola/kbc-ui/pull/1482/commits/a57c77e98921c79890f9f96512dee7cb4a9b9b2f

**Comment by ondrejhlavacek** [comment]
dá se to zdrcnout do tohodle, ověřeno, funguje:

```sql
SELECT 
    "name",
    "population", 
    ("population" / "total-cars-count") AS "cars-per-capita" 
FROM "countries-cars-count" 
JOIN "countries-population" 
    ON "country" = "name";
```
pokud jsou sloupce v FROM + JOIN unikátní, není třeba je prefixovat názvem tabulky.

**Comment by janmichek** [comment]
@ondrejhlavacek Query is not valid ./ jdu zkoumat proc to nejde

**Comment by janmichek** [comment]
V tom Snowflake worksheetu to funguje, ale v kbc mi to hazi 'Query is not valid'. Prepsal jsem uvozovky na ty sikmy - databazovy. Online SQL validator rika, ze ok, ale v KBC mi to porad nebere.

**Comment by janmichek** [comment]
Podezrivam z toho ze UI nejak meni notaci - autocasuje nebo meni oddelovace. Zatim jsem na to neprisel, zkousim

**Comment by janmichek** [comment]
Tak nevim, poprvy jsem kvuli tomu realne pouzil sandbox, kde jsem si odladil notaci a pak ten samej query v KBC stejne nefunguje xD

**Comment by janmichek** [comment]
Nenapada me nic lepsiho nez prejmenovat zpet nazvy sloupcu a tabulek na puvodni. Ten query je zbytecne slozity, ale aspon funguje

**Comment by ondrejhlavacek** [comment]
Ve středu se k tomu můžu dostat a pořešit to, ladil jsem to přímo v db,
loop s extraktorem jsem nedělal, pardon, můžu tomu dát ještě pokus. Dej
vědět kdyžtak

**Comment by janmichek** [comment]
Uz fakt nerozumim nicemu. Poladil jsem si sql a funguje mi v ostrem kbc. Na lokalu to nefunguje, prestoze jsem prave rebasnul, tak nevim co je spravne. Jsem na SQL fakt marnej.

**Comment by ondrejhlavacek** [comment]
@janmichek lokálně myslíš lokální UI?

**Comment by janmichek** [comment]
Ano

**Comment by ujovlado** [comment]
@janmichek zahod potom tu branch, uz je to v mastri, malo by to ficat normalne ...
