### ISSUE TITLE
show details ala Jack

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1485]
vyplynulo z debaty v https://github.com/keboola/indigo-ui/issues/85
Tyka sa to vsetkych IM/OM modalov, popripade by sa tento koncept dal rozsisirt aj na ine "custom" settings dialogy.

### Jackov Navrh
![image](https://user-images.githubusercontent.com/1412120/36239961-f4b7ee34-1248-11e8-8d0c-1a1b6150753e.png)

### Sucasny Stav

![image](https://user-images.githubusercontent.com/1412120/36239972-1c346b9a-1249-11e8-94db-a060df41e8f3.png)

**Comment by janmichek** [comment]
Abych to mohl udelat bez hackovani, dle prikladu:
https://react-bootstrap.github.io/components/panel/#panels-collapsible

je potreba updatnout kbc i indigo na novou verzi react-bootstrap https://github.com/react-bootstrap/react-bootstrap/releases/tag/v0.32.1-docs.0 

Cvicne jsem updatnul v kbc, bude potreba upravit vic veci s updatem. Nezbyva nez se do toho pustit.

**Comment by ujovlado** [comment]
@janmichek je nutne to robit cez ten panel? mne pride, ze sa to na to nehodi, ved panel v tom modale pouzity predsa nie je, ci?

**Comment by ujovlado** [comment]
Tym chcem povedat, ze to v pohode dame cez lokalny state toho modalu.

**Comment by janmichek** [comment]
@ujovlado 
Domnivam se ze na skryti obsahu jsou v BS 2  komponenty - Tabs a (collapsible) Panel.
Tabs se na to nehodi, Panel mi pripada idealni - poskytuje to nejaky animace, accessability, ...
Staci dostylovat header.
Ten state muze stejne ovladat show/hide Panelu.
 Chces udelat neco simple jako :

```
If @showDetails 
   div ...

```

?

Tim bychom tvorili custom alternativu Panelu.
Napis mi teda co navrhujes?

**Comment by ujovlado** [comment]
Ano, myslel som to v podstate tak ako pises.

Panel sa mi nepacil len preto, ze tam treba nasledne riesit tie styles (resetovat panel header resp. aj panel body).

Kludne by to mohla byt nasa komponenta “ShowDetails”, ktora by mala props `children` a `show`.

Nieco ako:

```js
<div>
  {props.show ? (<div className=“text-center”><i className=“fa fa-chevron-up” /> Hide details</div>) : (<div className=“text-center”><i className=“fa fa-chevron-down” /> Show details</div>)
  {props.show ? props.children : null}
</div>
```

Ale ak je to na panel lepsi, spravme to cez neho.

**Comment by janmichek** [comment]
Myslim ze stejne by bylo potreba to aspon zakladne nastylovat. + treba pridat animaci, at je to trochu prehlednejsi co se deje. Nakonec by z toho byla komponenta kterou bysme stejne chteli znovupouzit = nekam kodifikovat.
V panel-body si myslim ze se nemusi nic prestylovavat.
Pripada mi legit, mit vlastni modifikaci panelu.
Udelam demo do Indiga.

**Comment by janmichek** [comment]
UI demo jsem pripravil zde https://github.com/keboola/indigo-ui/tree/show-details-panel

![token error](https://user-images.githubusercontent.com/15363559/37320610-d60b2db2-2674-11e8-8352-4cf81531663d.gif)

**Comment by ujovlado** [comment]
Len som sa chcel vyhnut tomu stylovaniu (ak sa to dalo bez neho). Ale nemam proti tomu nic, vyzera to fajn. Ak je to ready, kludne z toho sprav PR v indigo-ui, mozeme to rovno poslat von. Este si teda over, ze to pofici, tak ako si zelas v modale -> tam to vo finale bude.

**Comment by janmichek** [comment]
Nejdriv tomu musi predchazet upgrade na novej react-bootstrap.  https://github.com/keboola/kbc-ui/issues/1510
Dostylovavat by se muselo v obou pripadech.
Jasny, pred nasazenim overim

**Comment by janmichek** [comment]
Nejdriv bude potreba releasnout styly z indiga.
@ujovlado podivas se na to, prosim?

**Comment by janmichek** [comment]
Jeste udelam upravu dle Jackova postrehu - dynamicky label Show / Hide Details

**Comment by janmichek** [comment]
Poreseno + pridana hover modra barva
