### ISSUE TITLE
align modal form labels to the right ala Jack

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1486]
Jack to nastrelil v jednom zo svojich navrhov(v https://github.com/keboola/indigo-ui/issues/85), imho to vyzera lepsie, ale bude to treba prerobit vo vsetkych modaloch

### Jackov Navrh
![image](https://user-images.githubusercontent.com/1412120/36240099-ec374ba0-1249-11e8-9512-1cfa48538232.png)

**Comment by janmichek** [comment]
Tohle ted delat nebudu, az v ramci sjednocovani forms. Nechci ted vytvaret dalsi entropii .]
