### ISSUE TITLE
Track Guide Mode users

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1489]
Chceme videt jak uzivatele prochazeji nebo pripadne zasekavaji GM.
Mame na to v KBC Hotjar.
Jack vi jak s tim pracovat.
Pokud na to budes potrebovat nejaky priznak, kontaktuj nejspis @ujovlado .

Je jedno jestli budeme trackovat vsechny uzivatele a pak to vyfiltrujeme, nebo sledovat jen uzivatele se zapnutym GM.

**Comment by janmichek** [comment]
@jancermak Hoja, napis mi prosim nejaky status k tomuto issue

**Comment by ujovlado** [comment]
Vcera som sa o tom bavil s Jackom.

Par info:

- nemusi to ist nutne za mnou, je to vec, ktora sa zobrazuje podla feature v connection `hotjar-enabled`
- ten kod, co sa tam zobrazuje asi treba skontrolovat (napr. account id alebo co to vlastne je) - nech tie stats padaju tam kde maju (https://github.com/search?q=org%3Akeboola+hotjar-enabled&type=Code)
- padla otazka, ci to, ze takto trackujeme userov mame v TOS (ale vyzera, ze je to len v layoute projektu)
- nie som si uplne isty, ci sa da zalozit projekt, ktory bude mat vopred nastavene nejake features (to mozem spisat do issue)

**Comment by janmichek** [comment]
> nemusi to ist nutne za mnou, je to vec, ktora sa zobrazuje podla feature v connection 

Aha, cool. Nevedel jsem ze je na to prepinatko. Myslel jsem ze se to zapina v hotjaru globalne.


> ten kod, co sa tam zobrazuje asi treba skontrolovat

To nejspis bude na @jancermak pripadne me kontaktuj, pokud nevis


> padla otazka, ci to, ze takto trackujeme userov mame v TOS

Nedokazu posoudit, uz jsi to resil @jancermak ?


> este je otazne, kde vsade ten kod moze byt (ale vyzera, ze je to len v layoute projektu)

znamena to ze by to nahravalo jen v KBC ale ne v Connection (Storage) ?

**Comment by ujovlado** [comment]
@janmichek treba to nieco odo mna okrem issue na Connection, ktory je tu linknuty? Myslim, ze sme sa bavili, ze to nie je horuce a moze to ist vonku aj bez toho.

**Comment by jancermak** [comment]
Ola,

mam pristup od Padaka do hotjar.com

Kod kterym by mel byt v connectionu je:

`
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:307057,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>`

**Comment by ujovlado** [comment]
Ten kod som pozeral, taky isty je v connection.

**Comment by ujovlado** [comment]
Toto je v connection:

```html
<!-- Hotjar Tracking Code for http://keboola.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:307057,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

**Comment by ujovlado** [comment]
Akurat som volal s @jancermak , kedze sa jedna o testovacie projekty, pravdepodobne by sme TOS riesit nemuseli -> nahrava to len co sa deje v Guide Mode. (cc @padak )

Na otestovanie instalacie Hotjar to pre Jacka zapnem manualne (tu feature).

Dalej sa caka na doimplementovanie feature v Connection, co je tu linknuta.

**Comment by ujovlado** [comment]
Tak este toto: https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies

**Comment by ujovlado** [comment]
@jancermak ten hotjar by ti uz mal ficat, pridali sme spominane CSP

**Comment by jancermak** [comment]
hotjar pro 4472 funguje, nahrava to korektne

**Comment by ujovlado** [comment]
Technicky je to ready. Momentalne sme zastali na tom, ze to treba dat userovi nejako vediet a pravdepodobne updatnut Terms of service / Privacy policy. Viac sa pise v tom issue: https://github.com/keboola/connection/issues/1248

**Comment by janmichek** [comment]
No, muzu se na to podivat, ale nikdy jsem to nedelal xD nejsem pravnik

**Comment by janmichek** [comment]
Update po konzultaci s padakem:
Pod prihlasovacim formem dame jednouduchou vetu s odkazem na Hotjar podminky s pred checknutym checkboxem.
Kdyz nezacheckne checkbox, nedostane se dal.
Coz casem bude potreba upravit dle GDPR, uzivatel muze dal, ale bez trackovani.

**Comment by janmichek** [comment]
@ujovlado jj, bomby. je to podle predstav .] Link bych nasmeroval na https://www.hotjar.com/legal nebo na mainpage  www.hotjar.com . Zatim je to prazdny

**Comment by ujovlado** [comment]
Je to nasadene. Projekty vzniknute cez try.keboola.com a kod `guide-mode` uz maju `hotjar-enabled` zapnutu.

![screenshot_2018-05-04_16-52-15](https://user-images.githubusercontent.com/419849/39634660-acf1710a-4fbb-11e8-9786-0817ee79a49c.png)

**Comment by janmichek** [comment]
bomby, dik. Budu sledovat co se deje
