### ISSUE TITLE
orchestrator - manualní run

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#149]
ve starém ui nabízel orchestrátor při puštění jít na joby:
![image](https://cloud.githubusercontent.com/assets/1427901/8138785/36a9fb9c-114e-11e5-8c1b-5c72a5229124.png)
 
v novém to není - vyloženě mě to netrápí, ale vlastně mi to přišlo šikovný #fyi

**Comment by Halama** [comment]
taky bych počkal jestli se s tím ještě někdo ozve. Nedával jsem to tam záměrně.
