### ISSUE TITLE
menu uživatele - zalejzá pod hlavní obsah

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#150]
Tohle je překryté:
![image](https://cloud.githubusercontent.com/assets/1427901/8139252/6188fdb4-1152-11e5-8489-2725ede0018e.png)

**Comment by Halama** [comment]
@JakubMatejka dělá to v moment kdy to levý menu je odscrollovaný. Není to teda závislý na šířce okna ale jeho výšce.

**Comment by JakubMatejka** [comment]
To vím, nic jsem s tím nedělal než to dostanem nakreslený. Ale fixnul jsem to aspoň dočasně tak aby bylo vidět.
