### ISSUE TITLE
Guide Mode - Failing transformation + Missing scroll bar

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1506]
Pokud nic nepřepisuji (což je účelem) v nastavení Snowflake extractoru a pokračuji transformací, ta padne, protože tabulky ve Storage nejsou pojmenované velkými písmeny a sloupce v tabulkách taky ne:
![job 361984618 2018-03-02 14-43-51](https://user-images.githubusercontent.com/12933713/36901685-513c115e-1e28-11e8-8ab6-aa3b6d671c6c.png)
https://connection.keboola.com/admin/projects/4054/jobs/361984618

Předtím je ještě silně matoucí lekce 3.4, kdy se okno vpravo tváří tak, že nastavím Input/Outpu mapping a mám vystaráno. Přesně pod tím ale začíná ještě Queries. Bohužel napravo není vidět scrollbar, který by mi napověděl, že tohle není vše:
![guide mode test - transformations 2018-03-02 14-45-45](https://user-images.githubusercontent.com/12933713/36901790-9d59363e-1e28-11e8-91dd-b43fa5152cce.png)

**Comment by janmichek** [comment]
@Matejkys Caj, jo stim query to vim a resim to.

S tim scrollbarem, to nevidis jenom na tomhle kroku, nebo scrollbar nevidis vubec nikde? Predpokladam ze pouzivas Chrome na Macu. To je mi divny.

**Comment by Matejkys** [comment]
@janmichek jo, chrome na macu. Scrollbar se vždycky schová, když nescrolluju.

**Comment by janmichek** [comment]
@Matejkys Mrkni se prosim v chromu -> odkazem: chrome://flags -> Overlay Scrollbar.
Jakou tam mas hodnotu? Spravne by melo byt 'default'

**Comment by janmichek** [comment]
@Matejkys a co hlavni okno browseru? Tam se ti to taky shovava?

**Comment by Matejkys** [comment]
@janmichek Takový flag vůbec nemám k dispozici. Nicméně jsem problém našel. Schovávání scrollbaru jsem měl nastavené přímo na kompu :)
