### ISSUE TITLE
Nejde mazat cfg extraktorů

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#151]
ve starém ui bylo DELETE tlacitko, v novém nic podobného nevidím

**Comment by Halama** [comment]
má ho každá komponenta ve svém detailu, pro ty které nemají ui vůbec uděláme nějaké generic ve kterém to bude

**Comment by Halama** [comment]
souvisí s #83

**Comment by Halama** [comment]
Extraktory bez ui už mají dummy ui detailu, takže jdou mazat, spouštět a přejmenovávat.
