### ISSUE TITLE
update react-bootstrap 

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1510]
na verzi v0.32.1

**Comment by janmichek** [comment]
delam na tom tady https://github.com/keboola/kbc-ui/tree/janmichek-upgrade-react-bootstrap

**Comment by ujovlado** [comment]
Pozeram, ze tam bol celkom velky BC break. Ides teda prerobit vsetky usages Panelu?

BTW, nikto myslim nepozera kod v branchi, nespravis z toho rovno PR, kde sa to bude "trackovat"?

**Comment by janmichek** [comment]
Je toho vic, zatim nemuzu prijit na to proc to vyhazuje ruzny chyby  pri otevreni modalu. Muzu udelat PR, no prob

**Comment by janmichek** [comment]
https://github.com/keboola/kbc-ui/pull/1536

**Comment by janmichek** [comment]
Moc jsem s tim nepohnul. Ty chybovy hlasky po otevreni modalu me akorat matou a nevim odkud zacit. Par ukazek :

![vystrizek](https://user-images.githubusercontent.com/15363559/37506267-596ab9a4-28e9-11e8-84c4-f09891189c01.JPG)

![vystrizek2](https://user-images.githubusercontent.com/15363559/37506268-59b1225e-28e9-11e8-833e-41a0b4e8bb64.JPG)

![vystrizek3](https://user-images.githubusercontent.com/15363559/37506269-59f3a566-28e9-11e8-9288-4487c849376a.JPG)

**Comment by ujovlado** [comment]
Ok, kukal som to, vyzera to na problem s touto zmenou (https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md):

> Feature: Switch to react-transition-group for Transition components

Takze to len tak neupdatneme, pokial nebudeme mat React 15.

**Comment by ujovlado** [comment]
Dalsia vec, ze ak chces prepisat to pouzitie Panel komponenty, prichystaj si hodne casu.

Skusil som to napr. pre "Project Power", tu je diff:

```diff
--- a/src/scripts/modules/billing/react/UsageByMonth.jsx
+++ b/src/scripts/modules/billing/react/UsageByMonth.jsx
@@ -4,7 +4,7 @@ import moment from 'moment';
 import MetricsApi from '../MetricsApi';
 import CreditSize from '../../../react/common/CreditSize';
 import ComponentsStore from '../../components/stores/ComponentsStore';
-import {Table, Panel} from 'react-bootstrap';
+import {Table, Panel, PanelGroup} from 'react-bootstrap';
 import ComponentName from './../../../react/common/ComponentName';
 import ComponentIcon from './../../../react/common/ComponentIcon';
 import {componentIoSummary} from './Index';
@@ -75,28 +75,41 @@ export default React.createClass({
             {' to '}
             {moment(this.state.dates.dateTo).format('MMM D, YYYY')}
           </h3>
-          {this.state.metricsData.map((item, index) => {
-            if (!item.get('components').isEmpty()) {
-              return (
-                <Panel collapsible={true}
-                       defaultExpanded={index === 0}
-                       header={this.daySummary(item)}
-                       key={item.get('dateFrom') + '-' + item.get('dateTo')}>
-                  <Table fill className="table">
-                    <tbody>
-                      {List([item.get('components').sort(sortComponentsByStorageIoDesc).map(this.dayComponents)])}
-                    </tbody>
-                  </Table>
-                </Panel>
-              );
-            } else {
-              return (
-                <Panel collapsible={true} header={this.daySummary(item)} key={item.get('dateFrom') + '-' + item.get('dateTo')}>
-                  N/A
-                </Panel>
-              );
-            }
-          })}
+          <PanelGroup accordion id="modules-billing-react-usage-by-month" defaultActiveKey={0}>
+            {this.state.metricsData.map((item, index) => {
+              if (!item.get('components').isEmpty()) {
+                return (
+                  <Panel key={item.get('dateFrom') + '-' + item.get('dateTo')} eventKey={index}>
+                    <Panel.Heading>
+                      <Panel.Title toggle>{this.daySummary(item)}</Panel.Title>
+                    </Panel.Heading>
+                    <Panel.Collapse>
+                      <Panel.Body>
+                        <Table fill className="table">
+                          <tbody>
+                            {List([item.get('components').sort(sortComponentsByStorageIoDesc).map(this.dayComponents)])}
+                          </tbody>
+                        </Table>
+                      </Panel.Body>
+                    </Panel.Collapse>
+                  </Panel>
+                );
+              } else {
+                return (
+                  <Panel key={item.get('dateFrom') + '-' + item.get('dateTo')} eventKey={index}>
+                    <Panel.Heading>
+                      <Panel.Title toggle>{this.daySummary(item)}</Panel.Title>
+                    </Panel.Heading>
+                    <Panel.Collapse>
+                      <Panel.Body>
+                        N/A
+                      </Panel.Body>
+                    </Panel.Collapse>
+                  </Panel>
+                );
+              }
+            })}
+          </PanelGroup>
         </div>
       );
     }
```

A ze by to vyzeralo pekne sa neda povedat:

![screenshot_2018-03-26_21-31-23](https://user-images.githubusercontent.com/419849/37928420-0f1cac8e-313d-11e8-9b16-04b8884a8c55.png)

... cize by si to ziadalo dalsie zmeny nepriec aplikaciou.

Panel, ak spravne kukam sa pouziva na ~50 miestach.

**Comment by ujovlado** [comment]
Cize #1485 by sme mohli spravit jednoduchym sposobom, ako som povodne navrhoval. Je to vec max jedneho dna, nie update na tyzdne.

**Comment by janmichek** [comment]
Fajnovy, dik za prozkoumani issue. Jasny no, s tim se ted srat nebudem, hrozne prace.
Navrhuju to reseni udelat stejne jako predtim pres Panel, jenom se starym markupem. Je to zmeneny hned.
vyhody uz jsme resili, popsal jsem tady https://github.com/keboola/kbc-ui/issues/1485#issuecomment-372519385

**Comment by ujovlado** [comment]
ok, np, tu to teda zavrem
