### ISSUE TITLE
CSV Importer: link to curl import

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#1523]
CSV Importer is not the best solution for uploading larger files as it has 10 minutes timeout etc.

We should direct the user to the documentation, to import larger files using curl:
https://developers.keboola.com/integrate/storage/api/importer/

A nice to have feature would be to generate that curl command directly in the UI.

**Comment by Halama** [comment]
Taky by bylo dobrý zjistit proč jsme to nastavili zrovna na tech 10 min, imho by neměl být problém přes browser uploadnout i větší soubory. Zvlášt když přes uploader v konzoli mu to proběhlo bez problému.

**Comment by MiroCillik** [comment]
Tiez si myslim, ze by ten timeout mohol byt vacsi. Napr aj hodina. @ondrejhlavacek by to asi mal objasnit :) 
https://github.com/keboola/kbc-ui/blame/master/src/scripts/modules/csv-import/actionsProvisioning.js#L129

**Comment by ondrejhlavacek** [comment]
Tak to asi fakt bude jen soft limit, ať si to lidi naskriptujou nebo vyřešej jinak, když to bude něco většího.
