### ISSUE TITLE
Qlik, Looker, Mode - rewrite to Snowflake

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#1538]
These "fake" writers are now based on Redshift writer, lets switch it to Snowflake.

**Comment by padak** [comment]
PB https://keboola.productboard.com/feature-board/6271-planning/features/343797

**Comment by MiroCillik** [comment]
@padak robim cistku vo svojich issues. Co s tymto? Je to este potreba alebo sme koncept "fake" writerov zavrhli a proste pouzivame Snowflake writer?

**Comment by padak** [comment]
Jo, pryč!
