### ISSUE TITLE
inline edit v hlavičce - odsazení

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#155]
Tohle je taková prkotina kterou asi řešit nemusíme jenom se nad tím občas zaseknu.
Trochu mě bije do očí ta velká mezera která vznikla inline editem v hlavičce.
![image](https://cloud.githubusercontent.com/assets/903531/8178629/577b54c8-1410-11e5-88b9-6ea1076c8714.png)

Po hoveru:
![image](https://cloud.githubusercontent.com/assets/903531/8178643/76c5450a-1410-11e5-9ae4-6bc7967fe2a0.png)

Představuju si to nějak takhle:
![image](https://cloud.githubusercontent.com/assets/903531/8178669/caf443e2-1410-11e5-99e5-39618b7e234e.png)

A po hoveru by to teda vypadalo (něco takovýho je i v tom návrhu):
![image](https://cloud.githubusercontent.com/assets/903531/8178677/dc3c6f12-1410-11e5-8c24-1585a3889d58.png)

Pořád mi to přijde ale trochu divný, problém je asi v tom odsazení tou pomlčkou.

**Comment by JakubMatejka** [comment]
To by šlo. Akorát se při hoveru ta pomlčka schová pod pozadí, ale to by snad nemuselo vadit(?)
![development_-_extractors___database_-_tomas](https://cloud.githubusercontent.com/assets/215660/8201834/db1d404c-14d4-11e5-96be-bbaaab9a3641.png)

**Comment by Halama** [comment]
ono by šlo i udělat aby to jakoby zajelo pod ní, tak to myslím bylo v tom návrhu. Hrál jsem si s tím a ten screen jsem udělal tak že tomu editu jsem dal tuším záporný margin a té pomlčce pozici relative.

**Comment by JakubMatejka** [comment]
Jj. se z-indexem. Upravil jsem bootstrap, ale musíš tomu spanu s pomlčkou přidat `.kbc-inline-edit-dash`

**Comment by Halama** [comment]
ok. diky
