### ISSUE TITLE
deleteWhereOperator saved as empty string

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1554]
- Create new transformation
- create OM
- show details
- delete rows op is set to `in`

![image](https://user-images.githubusercontent.com/4319320/37570895-173d1f2c-2af6-11e8-9351-6a549ff52650.png)

- save the configuration
- it is saved with empty deletewhereop which is invalid:

![image](https://user-images.githubusercontent.com/4319320/37570917-4a586e16-2af6-11e8-9c3f-ea1d6c21916f.png)

**Comment by kacurez** [comment]
@odinuv plati to aj pre docker apky ktore do IM konfigu ukladaju `where_operator`(tj nie whereOperator ako u transformacii). Pretoze transformacie je vlastne ina apka a nemusi sa k tomu stavat rovnako.
Inac tych zmien bude potrebnych celkom dost, ten where_operator resp whereOperator je rozlezli a castokrat len rozkopirovany na viac miest. Tak sa chcem uistit nez sa do toho pustim.

**Comment by odinuv** [comment]
plati to hlavne pro docker appky a urcite to driv nedelalo - si to zkus, tedka kdyz chces u neceho zapnout incremental OM, tak se ti jebne konfigurace

**Comment by kacurez** [comment]
`tak se ti jebne konfigurace` - co to presne znamena? :)
ulozit sa mi to ulozilo a ked to pustim tak preide v pohode ako ma tj vystup sa do tabulky zapise inkrementalne.

**Comment by kacurez** [comment]
aha mmnt to som skusal snowflake transformaciu, tak este skusim python transformaciu(aka docker apku)

**Comment by odinuv** [comment]
jebne se = ulozi se tam `"delete_where_operator":""`, musi to byt docker appka s output mappingem

**Comment by kacurez** [comment]
pustil som si python transformaciu a zprava sa to ok tak ako predpokladam.
> jebne se = ulozi se tam "delete_where_operator":""

co sa tam ma potom ulozit? `null` alebo `eq`?

**Comment by kacurez** [comment]
pustil som transformaciu 2krat a vystupna tabulka spravne obsahuje 2x viac riadkov.
![image](https://user-images.githubusercontent.com/1412120/37600170-d8b96b48-2b86-11e8-88bb-6bf537cb8d25.png)

**Comment by odinuv** [comment]
ale ja nemluvim o transfomacich, ale o komponentach co maji OM, transformace to maji jinak (a stejne blbe). V UI vidis `eq`, takze by bylo fajn, aby se to tam ulozilo, jiank technicky to tam bud nema byt vubec nebo tam ma byt `eq` nebo `ne`

**Comment by odinuv** [comment]
pattern to neni, protoze je to jinak u where op a delete where op

![image](https://user-images.githubusercontent.com/4319320/37605330-3ca9cc04-2b93-11e8-92df-a0a339cb681e.png)

**Comment by odinuv** [comment]
config mas treba tu https://connection.keboola.com/admin/projects/578/applications/dca-custom-science-r/222872452

**Comment by kacurez** [comment]
mal som na mysli ux pattern - tj ze sa to z funkcneho hladiska sprava konzistentne. Ajked sa to v ui transformacii uklada inak tak je to potom poriesenie preprocessingom konfigu pocas runu transformacie.

U ostatnych komponent potvrdzujem ze to nefunguje a ze to pada, opravim.
 https://connection.keboola.com/admin/projects/578/applications/dca-custom-science-r/222872452

**Comment by ondrejhlavacek** [comment]
Upravoval jsem to chování tady - https://github.com/keboola/kbc-ui/pull/1528. Dělo se to, že pokud byl where operátor nastavenej na `EQ`, tak to uložilo prázdnej string. Tak je to fixnutý asi blbě. 

Podle mě by to mělo vždycky uložit default hodnotu `eq`. Když jsou prázdný `where column`, tak se ostatní hodnoty (`operator` a `values` ignorují).

**Comment by ondrejhlavacek** [comment]
U transformací to teda ukládá jak má zdá se 

![image](https://user-images.githubusercontent.com/497675/37618050-20ef57aa-2bb5-11e8-946e-ae2965a0e84a.png)

A PHP custom science mi to taky uložilo

![image](https://user-images.githubusercontent.com/497675/37618104-57bf69d2-2bb5-11e8-8ed2-b487cf8732cd.png)

Tyjo, to musí bejt něco windowsovskýho!

**Comment by odinuv** [comment]
To je neco jinyho tedka, ted kdyz zapnes incremental, tak to ulozi `delete_where_operator: ""`

**Comment by ondrejhlavacek** [comment]
@odinuv aha, ty to vůbec nevyplňuješ!

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/pull/1557 je imho správnej fix, @odinuv můžeš to ověřit?

**Comment by odinuv** [comment]
myslim, ze nez me se stahne a zbuilduje kbc-ui (uz to chrousta 15 minut), tak bude rychlejsi kdyz zkusis preulozit tu konfiguraci - https://connection.keboola.com/admin/projects/578/applications/dca-custom-science-r/222872452  :)

**Comment by ondrejhlavacek** [comment]
Přeuložit asi nepomůže, udělám druhou novou úplmě stejnou, ok?

**Comment by ondrejhlavacek** [comment]
@odinuv je to tam
