### ISSUE TITLE
moving table input in output mapping form

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1559]
![](https://api.monosnap.com/rpc/file/download?id=NoBdAElpHbcP68lfdzIfRzZDY73o5X)

- ještě jsem si všiml, že mezi těmi fieldy nejde přeskakovat tabulátorem

**Comment by kacurez** [comment]
ad preskovanie tabulatorov medzi fieldami - mne to funguje vid:
![inputtabulators](https://user-images.githubusercontent.com/1412120/37674171-7f0caa3c-2c72-11e8-94a5-44ec7c7a5994.gif)

**Comment by ondrejhlavacek** [comment]
ale z bucketu do tabulky už jsi nepřeskočil :-)

**Comment by ondrejhlavacek** [comment]
tak jsem tam těch dlouhejch stringů naházel víc

https://monosnap.com/file/92K9zjj2ga9bt4WvwctUPsSYy9BRHy

a) ten modrej popup selector pod bucketem se nezvětšuje s inputem
b) oba inputy vylezou někam do nesmyslu mimo modal
c) table name poskočí na novej řádek

nemyslím si, že nás z toho cokoliv pálí, ale možná je za tím skrytýho něco dalšího, tak pro jistotu reportuju. může nás to potrápit někde jinde, kde budou ty inputy víc natěsno

**Comment by ondrejhlavacek** [comment]
cc @ujovlado co myslíš?

**Comment by ujovlado** [comment]
kuknem sa, s tym flexboxom to bol moj napad. ked tak updatnem Tomasov PR
