### ISSUE TITLE
job event detail styles

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1584]
je to nějaký podivný

![image](https://user-images.githubusercontent.com/497675/37975449-a7525fb0-31df-11e8-9a31-2f2b009d6d52.png)

**Comment by Halama** [comment]
@ujovlado říkal že to ASAP fixne :)

**Comment by Halama** [comment]
https://keboola.slack.com/archives/C02J3DKH3/p1521647412000050

**Comment by Halama** [comment]
aha tak nerikal ASAP ale coskoro

**Comment by janmichek** [comment]
Prozatim jsem to hotfixnul tady https://github.com/keboola/kbc-ui/pull/1586

**Comment by ujovlado** [comment]
@janmichek super, dik za fix :+1:

**Comment by Halama** [comment]
parada

**Comment by ujovlado** [comment]
@janmichek ak sa to uz nebude prerabat na nieco lepsie, zavrime to :)

**Comment by janmichek** [comment]
Zkusim to udelat jeste lepe, tohle byl hotfix aby to tam nestrasilo

**Comment by Halama** [comment]
Objevila se ještě jedna divnost:
![image](https://user-images.githubusercontent.com/903531/38039428-8cfb5b66-32ad-11e8-81c9-1525aa95d5e2.png)

**Comment by Halama** [comment]
To samý se objeví při prvním načítání event

**Comment by janmichek** [comment]
V tech pullech jsem udelal stabilnejsi reseni detailu, sjednotil tabulky eventu na full-width a vyhodil styly pro spacing classy

![token error 3](https://user-images.githubusercontent.com/15363559/38069708-114dd41a-3318-11e8-83d4-6cdc9b7c57ff.gif)

**Comment by janmichek** [comment]
Ohledne tohoto:
https://github.com/keboola/kbc-ui/issues/1584#issuecomment-376929081

To bude vetsi zamrd a blbe se to debuguje.
Uz jsem neco podobnyho videl. Problem bude nejspis v tom ze se mixuje pouziti divu vedle sebe s classou .row a bez ni. Coz ted nema uplne snadny reseni.

![image](https://user-images.githubusercontent.com/15363559/38069796-9a014bde-3318-11e8-8b96-1e07c66f8cca.png)

zkusim z toho nejak elegantne vybruslit

**Comment by janmichek** [comment]
Na to cukani layoutu jsem vytvoril issue tady 
https://github.com/keboola/kbc-ui/issues/1595
Tohle muzete zatim mergnout.
