### ISSUE TITLE
Job list error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1585]
- jdu na detail jobu
- do parametru `q` v url doplním `processing`
- stránku reloaduju
- kliknu v breadcrumbs na `Jobs`

chyba se neobjeví v sentry!

![Alt text](https://monosnap.com/file/mumjbRj8s3dQ4zeW6aCT1Nl0oZzq6f.png)

**Comment by kacurez** [comment]
problem je v tom ze ked odides z JobDetail na Jobs stranku tak sa nacita novy zoznam jobov ktory sa ulozi do jobs store. V tom zozname sa uz nenachadza job z ktoreho detailu odchadzas. Tym ze sa zmeni jobs store tak sa na pico sekundu prerendruje job detail s `this.state.job === null` a potom to spadne.
Bohuzial to nacitavanie jobov je zapeklite a jedine riesenie vidim v oifovani job detail handlerov. pripravim PR.
