### ISSUE TITLE
Gradient v Description na Safari

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1597]
Vypadá podivně:
![image](https://user-images.githubusercontent.com/1427901/38080994-36199524-3343-11e8-8311-7752b54618f1.png)

**Comment by ujovlado** [comment]
@padak deje sa ti to este?

**Comment by janmichek** [comment]
@padak respektive se podivej pls na novou komponentu kde uz ten gradient je fixnuty tady https://indigo.keboola.com/?selectedKind=PanelWithDetails&selectedStory=Content%20preview&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by padak** [comment]
jj, na Safari mi to dělá pořád: https://monosnap.com/file/EW1LiZwJ8JeAImSNp9z29cP3scCbn3
viz tady https://connection.keboola.com/admin/projects/258/transformations/bucket/329722040/transformation/329722090

**Comment by janmichek** [comment]
Jiste ze .] v kbc to totis jeste neni nasazeny.
Zchecknul jsem to tady v kanclu s Mirem v Safari.

V KBC ten gradient vypada blbe - viz puvodni screen.
Nova verze kterou jsem nalinkoval https://indigo.keboola.com/?selectedKind=PanelWithDetails&selectedStory=Content%20preview&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel
uz v Safari vypada dobre.

Vyresi se to s nasazenim https://github.com/keboola/indigo-ui/issues/180

**Comment by janmichek** [comment]
Fixed
