### ISSUE TITLE
Do not hide table column in writer if column does not exist in storage

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1610]
Myslim, ze to tam mame trosku preinzinierovane a snazime sa tomu pridat UX, kde netreba.

Zo zendesku: https://keboola.zendesk.com/agent/tickets/8208

- Nastavim writer na tabulku, co ma dva stlpce: key1, key2
- Pustim writer, prebehne ok
- Idem do storage console, zmazem key2
- Vratim sa do writeru, zmizne stlpec key2 (! tu je ten fail, lebo ten stlpec nezmizne z konfiguracie)
- Pustim writer (vyfailuje)

Riesenie:

Podla mna by sme nemali skryvat tie stlpce. Pretoze potom UI neukazuje to co je v konfiguracii.

**Comment by Halama** [comment]
duplicate https://github.com/keboola/kbc-ui/issues/1415 ?

**Comment by Halama** [comment]
naposled se objevilo nedavno asi by bylo dobry nejak protlacit ten fix

**Comment by kacurez** [comment]
j tam sa to renderuje podla aktualneho zoznamu stlpcov tabulky a ten sa potom mapuje na zoznam ulozeny v konfigu. Pozriem sa nato
