### ISSUE TITLE
TAPI - editovatelný popisek transformace

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#162]

**Comment by Halama** [comment]
Chceš jí dělat editovatelnou samostatně?

**Comment by ondrejhlavacek** [comment]
Co myslíš? Po vzoru hromady jinejch míst...
Někde jsme se o tom bavili, zaregistroval jsem to jako bug a posílal k tomu odkaz na dokumentaci API, že na to je jednoduchej api call.

**Comment by Halama** [comment]
jj to jsem zakládal já, pak jsem si všiml že se edituje v rámci celku tak jsem to zavřel :) Ale asi jo bylo by dobrý to udělat stejně jak jinde

**Comment by ondrejhlavacek** [comment]
A vyndat to z tý velký editace nebo to nechat na obou místec?

**Comment by Halama** [comment]
nevím, to asi vyzkoušej jak se to bude chovat

**Comment by ondrejhlavacek** [comment]
Tak na to prdím, ono by v tý komponentě bylo hrozně moc překrejvajících se editačních stavů nebo děsnej overhead to zabalit do samostatný komponenty, `ComponentEditField` na to nejde použít, řešil bych to až to bude víc pálit.
