### ISSUE TITLE
Fix markup for ex-fb config. detail

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1620]
Due to wrong classes/markup a horizontal scrollbar is shown.

**Comment by janmichek** [comment]
Podobny problem je napr na keboola.wr-google-bigquery -> rows
zpusobeny timto stylem 
`.storage-table-columns-editor-wrapper`
@natocTo jestli na to muzes jeste mrknout, prosim.

**Comment by natocTo** [comment]
Podívám se na to a případně pošlu nové PR.
