### ISSUE TITLE
Failed validation causes missing edit icons in Application mappings

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1622]
Vzniklo to novu validaci, kterou jsem musel dopsat, aby fungovalo 'Show details'
Mam za to, ze jsme se o tom bavili, ale uz nevim jak to dopadlo. https://github.com/keboola/kbc-ui/pull/1591
Ja to nestiham opravovat, jestli mas cas, mrkni  @kacurez 

https://keboola.zendesk.com/agent/tickets/8246

Error. Check render() method of component 'TableInputMappingModal'. Error details: TypeError: Cannot read property 'has' of undefined

**Comment by kacurez** [comment]
ok mozem nato pozriet

**Comment by ondrejhlavacek** [comment]
@janmichek ideálně okamžitý rollback a v klidu pofixovat bokem

**Comment by kacurez** [comment]
uz to mam, je to celkom zapeklite, akurat nechapem cim to vzniklo, mi pride ze to tam je od zaciatku.
Len pre ilustraciu:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/stores/InstalledComponentsStore.coffee#L690-L707

mam prazdny `list = List()` a zavolam `list.set(2, someMap)` tak polozky 0 a 1 sa v tom liste nastavia na undefined ale react komponenta ocakava aspon Mapu
Mozno sa to zacalo spravat inak po update immutable ale nemyslim si. Pripravim PR.

**Comment by ondrejhlavacek** [comment]
to neva, že to už skoro máš, já se na to teď nepodívám (jedu za apify), takže to může ještě pěknejch pár hodin strašit v produkci. revertovat pls.

**Comment by kacurez** [comment]
revert `show details` nezabera, tj je to tam furt a ako som pisal neviem urcit cim to vzniklo
