### ISSUE TITLE
detail tabulky ve snowflake writeru - rename bug

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1627]
Browser bug:
https://keboola.zendesk.com/agent/tickets/8184

**Comment by ondrejhlavacek** [comment]
@janmichek odassignovávám se :-)

**Comment by ujovlado** [comment]
@janmichek pls, nie som z toho schopny rozsifrovat, ci sa to teda deje alebo nie 

> Zkousel jsem to v Edge.
> Je videt, ze kdyz kliknu na 'Save', tak dojde k prenacteni cely stranky a ta akce se vlastne neprovede.
> ZKousel jsem treba prejmenovani konfigurace. Tam se taky stane tenhle divnej reload, nicmene konfigurace se nakonec prejmenuje.
> 
> Jan

tak nakoniec sa to premenuje?

**Comment by ujovlado** [comment]
toto zavrem, nepodarilo sa nakoniec zistit ci to bol problem alebo nie
