### ISSUE TITLE
Link to config version in job

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1632]
now that config version is available in job result a link in ui is possible

**Comment by ujovlado** [comment]
Za config alebo radsej ako novy riadok?

![screenshot_2018-04-27_12-46-21](https://user-images.githubusercontent.com/419849/39359147-1212e6d4-4a19-11e8-822c-4bba14b249be.png)

vs.

![screenshot_2018-04-27_12-43-52](https://user-images.githubusercontent.com/419849/39359148-123899ec-4a19-11e8-8d45-822722f93923.png)

**Comment by Halama** [comment]
Byl bych pro variantu 2. A možná by stačilo `my currency rates` - `#2`

**Comment by ujovlado** [comment]
Tiez by som radsej 2. To slovicko "version" by som tam asi nechal, nech je jasne, ze sa jedna o verziu.

Takze napr. `my currency rates - Version #2`

**Comment by ujovlado** [comment]
Ale teraz pozeram, ze nemame nikde detail verzie ... to bude potom zbytocne.

**Comment by ujovlado** [comment]
Tym myslim, ze sa neda linkovat na konkretnu verziu, len na vsetky

**Comment by odinuv** [comment]
aha, to jsem si vubec nevsim :) ja na to koukal ocima API, kde to jde. Tak to bude asi slozitejsi co? -> PB?

**Comment by Halama** [comment]
Ale alespoň bysme tam tu verzi mohli dát zatím nelinkovatelnou?

**Comment by ujovlado** [comment]
@odinuv btw, nemohlo by to byt v tom resulte (alebo inde) hned po zalozenie jobu? teraz sa to tam objavi az po dobehnuti jobu.

**Comment by odinuv** [comment]
nemohlo, nejde to to tam rozumne dotlacit pres syrup a nejak vyrazneji upravovat syrup kvuli tomu ted myslim nema smysl
