### ISSUE TITLE
confusing build log

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1634]
Dlouho jsem nevedel co znamena tenhle whitescreen pri lokalnim spusteni kbc, doprovazeny hlaskou v konzoli.
![term 1](https://user-images.githubusercontent.com/15363559/38868490-74331d04-4247-11e8-8d13-37590013506d.JPG)

Matouci je totiz, ze konzole nakonci vypisu jako vysledek vypise VALID
![term 3](https://user-images.githubusercontent.com/15363559/38868543-aa78740e-4247-11e8-955e-733ccbea6332.JPG)

... ale o kilometr vyse, kdyz odscrolluju tak vidim, ze ne vsechno se zkompilovalo
![term 2](https://user-images.githubusercontent.com/15363559/38868605-e2955faa-4247-11e8-80c4-169de0f59333.JPG)

**Comment by ujovlado** [comment]
Toto by som zavrel, zatial to asi nebudeme riesit (mozno by pomohol upgrade webpacku alebo tak), nemame to moc ako ovplyvnit. Asi si staci zapamatat, ze ked je tam whitescreen, nieco nejde "skompilovat". Tiez som sa na tom raz osral, potom som to uz vedel.
