### ISSUE TITLE
SQL validation modal

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1639]
Validace s chybou

![image](https://user-images.githubusercontent.com/497675/38981663-3740748a-43c0-11e8-86c1-8073a7246dcd.png)

gif: http://take.ms/EFcNJ

Validace bez chyby

![image](https://user-images.githubusercontent.com/497675/38981676-3de5358c-43c0-11e8-9767-9381dd19fdff.png)

gif: http://take.ms/2CEV2

Modal Sandboxu transformace

gif: http://take.ms/2CEV2

### 1) Buttony

Po dokončení běhu nemá tlačítko Run žádný význam. Tady se disabluje, v sandboxu transformace například úplně zmizí.

Sandbox:

![image](https://user-images.githubusercontent.com/497675/38981854-a65ea170-43c0-11e8-8e71-9e8e312b880c.png)

SQL validation:

![image](https://user-images.githubusercontent.com/497675/38981938-d9a05bc8-43c0-11e8-95db-e0fe65b6e04d.png)

### 2) Indikace běhu

Sandbox modal tam má spinner

![image](https://user-images.githubusercontent.com/497675/38981701-4d95bf92-43c0-11e8-9fab-35b6822cd239.png)

Validace SQL má na tlačítku napsáno `Running`

![image](https://user-images.githubusercontent.com/497675/38981952-e43ac410-43c0-11e8-9732-b7ab24e71fcc.png)

### 3) Success

Sandbox tam má zelený zatržítko. Sice na blbým místě, ale je to možná lepší indikace, než suchej černej text.

Sandbox:

![image](https://user-images.githubusercontent.com/497675/38982062-2ac59d24-43c1-11e8-96f3-67c6eaa66ca5.png)

Validace:

![image](https://user-images.githubusercontent.com/497675/38981971-e9461018-43c0-11e8-8022-7f2d2070e804.png)

### 4) Barvy

Zelená vs modrá 

---

Poraďte, co s tím, sjednotil bych to.

Note to self: Všechno platí i pro sqldep graf modal.

**Comment by janmichek** [comment]
@ondrejhlavacek ok, podivame se na to na offsitu s @jancermak . Nejaky napady k tomu mam

**Comment by janmichek** [comment]
Zatim postrehy:

Je mozny ze nakonec ta SQL validace pujde do hajzlu s SQL Depem, ze?
U vysledku validace by bylo fajn, kdyby to fungovalo kontextove - kdyz vim na jaky radce query je chyba, tak to oznacim. 
Ostatni veci sjednotime a zdokumentejme, to je jasny.

**Comment by janmichek** [comment]
@ondrejhlavacek mozna je to malinko off, klido nahodim novou issue.
Chvilku jsem si hral s tou sql validaci

1) vyhodilo mi to ze mam chyby na radkach v query. Proklik jsem se tim linkem. Moje ocekavani bylo, ze mi to dropne kurzor na radku vyskytu chyby.

2) Potom je pitomy, ze kdyz se prolinknu z toho modalu, tak ze mi zmizi vsechny ty chybovky. Nebo navrhujes to znova re-validovat? Mozna s Jackem na neco prijdem .]

**Comment by ondrejhlavacek** [comment]
@janmichek 
1) chová se ti to jinak než tady? http://take.ms/8xBuM
2) nejsnadnější je imho re-validovat - pokud cokoliv změníš, výsledky přestanou platit, takže nemá moc význam si je držet. uznávám, že je to opruz, že ti to zmizí, ale validace není pomalá, tak snad neva si to prokliknout ještě jednou. možná lepší, než mít zobrazený výsledky, který povedou na špatný místa.

**Comment by janmichek** [comment]
@ondrejhlavacek 
1. Chova se to u me jinak. Uplne napoprvy, to oznacilo spravny radek, ted uz pokazdy jiny. Nedokazu to ani nasymulovat, nicmene to vypada jako bug. Url se zmeni dle kliknutyho vysledku, ale pak se oznaci jina radka
![gif](https://user-images.githubusercontent.com/15363559/39513989-4171736a-4df6-11e8-95bf-8295904a1cf7.gif)

2. chapu, no prob

**Comment by ondrejhlavacek** [comment]
@janmichek pošli pls link, mrknu

**Comment by ondrejhlavacek** [comment]
ale řekl bychm že to máš jako dost edge case, změň v každé query aspoň jeden znak, aby byla každá jiná, a bude to valit.

**Comment by janmichek** [comment]
https://connection.keboola.com/admin/projects/4659/transformations/bucket/387626417/transformation/387626432

**Comment by ondrejhlavacek** [comment]
Změnil jsem query a už to valí.

**Comment by janmichek** [comment]
jj koukam ze to pomohlo, to je asi ok. Predpokladam ze toto se v realnym pouziti nestane. Abych neprudil malo, tak nekde vsak koukam ze to pocitani radku se rozjede pokud mam v query editoru prazdnou radku. To vadi nebo ne?

**Comment by janmichek** [comment]
SIgnalizaci nacitani, vidime zatim na resesni pomoci nove komponenty (v budoucnosti znovupouzitelne) Loading button ( button s loaderem)

**Comment by ondrejhlavacek** [comment]
Prazdnej radek vadí, máš to někde k ukázání?

**Comment by janmichek** [comment]
NEjsem schopnej ti to ukazat, protoze se mi ta validace zasekla na jednom radku xD takze vzdycky ty validacni hlasky ukazou na stejnou

**Comment by ondrejhlavacek** [comment]
Tomu nerozumím, máš zase query stejný? Někde jsi to musel vidět,když sis toho všiml? Dá se vrátit dřívější verze.

**Comment by jancermak** [comment]
@ondrejhlavacek @janmichek 

— **video fungování** — http://take.ms/aAed2
— **protyp** — clicken si bitte — https://invis.io/WEIC9PQV92N#/296133764_1639_-_SQL_Validation_Modal

**Pravidla:**
 — btn RUN zelene
— po kliknuti na RUN (run zmizi) na jeho misto se posune CANCEL - vleve casti dole  jede honitko s informaci co se deje
—po skonceni — misto informace vlevo dole se ukaze vysledek OK / KO - v pravo se CANCEL zmeni na CLOSE

**Comment by jancermak** [comment]
![1639 sql validation modal- rules](https://user-images.githubusercontent.com/1826442/39821220-0a1ae402-53a8-11e8-932e-bae0ba7a49ce.png)

**Comment by janmichek** [comment]
Mam k tomu par postrehu
- pokud mozno udelejme to co nejobecneji, at potom muzem znoovupouzit vymysleny pattern.
- ukazoval jsi mi demo, ze kliknu na 'SQL validate' -> otevre se modal a uz se rovnou validuje (nemusim klikat na run.
- mluvili jsme o tom, ze bychom sli cestou loaderu v tlacitku - obsah a vzhled tlacitka se bude menit  v zavislosti na stavu. Coz se deje i dle tveho navrhu. Navic ale je jeste vlevo ten status. Ta vec vlevo se mi moc nelibi, pripada mi to jako nesystemovy reseni.
Vysledek validace bych cpal do tela modalu. Takovej nacrt jsi mi myslim ukazoval. Jeste to proberem.

**Comment by ondrejhlavacek** [comment]
@janmichek 

ad 2) tady je nutný potvrzení uživatele, odesílá data pryč, kde budou public dostupný a nechráněný, nemůžeme to udělat bez potvrzení.

**Comment by ondrejhlavacek** [comment]
do modalu dopsat, že se nekontroluje output mapping (ve storage) neexistujících tabulek - https://github.com/keboola/sqldep-analyzer/issues/10

**Comment by ondrejhlavacek** [comment]
@janmichek pustil bych se do toho, co tady navrhuje jack, nebo mám ještě počkat? ven to můžu pustit tak jako tak.

**Comment by janmichek** [comment]
@ondrejhlavacek chteli jsme to jeste projackovat, pripravit 2. verzi zpusobu ovladani (signalizace loadovani)

**Comment by ondrejhlavacek** [comment]
nechávám to teda teď "as is" a pouštím ven, stejnej design pattern je u transformačních sandboxů, tak tam by se to pak spláchlo oboje naráz, ok?

**Comment by janmichek** [comment]
Zatim ok, kdyz to bude znovupouzitej kod, nebude pak prob to vymenit. Hod nam sem potom prosim jenom nejakou noticku, ze to mame poresit a kde to najdem.

**Comment by ondrejhlavacek** [comment]
- validační modal: https://github.com/keboola/kbc-ui/blob/9d42b4a4a538f59efa1f09efbe03957010c1209c/src/scripts/modules/transformations/react/modals/ValidateQueriesModal.jsx
- sandbox modal: https://github.com/keboola/kbc-ui/blob/9d42b4a4a538f59efa1f09efbe03957010c1209c/src/scripts/modules/transformations/react/modals/CreateDockerSandboxModal.jsx

**Comment by ondrejhlavacek** [comment]
@padak tak to je na úplně vlastní issue, validační modal bych tím vůbec nezatěžoval, to je na jiný okno, můžeš tu issue založit?

**Comment by janmichek** [comment]
skoro bych navrhoval zacit vyscreenovavnim vsech loaderu v aplikaci. JDe o to sjednotit vizual i koncept

**Comment by jancermak** [comment]
Test bezi na teto URL — https://app.usabilityhub.com/do/6d7978dc0643/f8c2

**Comment by janmichek** [comment]
Sem davam odbocku, abychom nejdriv koukli co vlastne mame a zbytecne netvorili dalsi entropii - krmivo pro dalsi sjednocovani. 
https://github.com/keboola/indigo-ui/issues/186

**Comment by jancermak** [comment]
@janmichek — prikladam vysledek testu — https://app.usabilityhub.com/tests/6d7978dc0643/results/abe7b2982a06?%7B%22viewState%22:%7B%22isExpandedBySectionScreenshotId%22:%7B%22334345%22:true%7D%7D%7D

**Comment by ondrejhlavacek** [comment]
@janmichek jsem tu zpět, vyhrála varianta A, mám to protáhnout ještě nějak přes indigo (celej modal nebo loadery), nebo se do toho můžu pustit?

**Comment by janmichek** [comment]
Beru si teda za ukol to zvalidovat se stavajicim pouzitim vitezny koncept.
Konkretne jde o to jestli na levy dolni strane modalu nebude neco prekazet vypisu stavu.

**Comment by janmichek** [comment]
Prozkoumal jsem  pouziti vsech modalu v kbc.
Ten koncept pujde pouzit vsude, krome techto 2 modalu, kde jsou tlacitka umisteny vlevo (coz se da snadno presypat doprava).

https://github.com/keboola/kbc-ui/blob/84fe1ae7be1e114becc1fbe0b21ae95aa6f938dc/src/scripts/modules/sapi-events/sliced-files-downloader/Modal.jsx#L53

https://github.com/keboola/kbc-ui/blob/f515ea88aebb8a29422aa308cb6e1fc17bdfeae9/src/scripts/modules/transformations/react/modals/ConfigureSandboxModal.jsx#L21

Klidne muzeme pokrocit k implementaci, jenom by me zajimalo jestli mame vymysleny jak to pujde dohromady i s ostatnimy loadery / statusy @jancermak 
https://github.com/keboola/indigo-ui/issues/186

**Comment by janmichek** [comment]
muze souviset https://github.com/keboola/kbc-ui/issues/1700

**Comment by ondrejhlavacek** [comment]
@janmichek potřebuju pro to něco z indiga, nebo se do toho můžu pustit?

**Comment by janmichek** [comment]
Neni to zatim od nas pripraveny.
Chybi k tomu front / UI elemnty v indigu.
Vytvorili bychom dalsi novy koncept signalizace loadovani. Me by zajimalo jak to pujde dohromady se stavajicima https://github.com/keboola/indigo-ui/issues/186

**Comment by jancermak** [comment]
@janmichek  a @ondrejhlavacek 
Ahoj posilam navrh fungovani ukladani querry s validaci. 

**VIdeo:**
http://take.ms/7FACF

**Prototyp:**
https://invis.io/BFNT6XO2C8P#/317345832_-1639_-_SQL_Validation_Modal_V2_Copy

—
V návrhu mi chybi —  pripad pokud je erroru velke mnozstvi

**Comment by ondrejhlavacek** [comment]
Kůl, to se mi dost líbí!

1) Pokud bude errorů velké množství, tak můžou bejt collapsnutý pod `Show more`.
2) Není mi jasný, jestli se query uložily po nalezení errorů (zdá se, že ne, tak pak by to mělo bejt spíš `Validate & Save`?). Nevalidní SQL by nemělo překážet uložení, můžu to mít rozpracovaný a nebo validátor může zahlásit nějaký false positive. Nebo je to myšlený tak, že musím checkbox odškrtnout a uložit znovu? Technicky teď umíme pouze `Save & Validate`, to je na tlačítku správně.
3) Navazuje na 2. `Validate SQL` v akčních tlačítkách (pravej panel) zmizí? Jeho funkce bude furt potřeba (ale může to bejt udělaný jinak). Pokud navrhovaný `Validate & Save` validuje query při uložení, tak nemám možnost validovat query, kterou jsem needitoval. Můžu přijít do transformace, kterou uložil někdo jinej, a chci jí bez editace pouze zvalidovat. Pokud tam bude obojí, je to v pohodě a `Validate SQL` v pravým panelu bych disabloval v při rozeditované query.

**Comment by jancermak** [comment]
@ondrejhlavacek a @janmichek 

1) navrhnuto, je videt ve videu i v prototypu
2) procetl jsem si to co jsi napsal a sel bych taky tou cestou ze ulozime vzdy a pak ukazeme vysledek validace, zohlednil jsem to v protypu. Koukni na to jestli ti to sava smysl.
3)V pravym panelu dle toho co pises bych zachoval to tlacitko. Aby byla zachovana ta moznost validovat aniz bych musel sahat do kodu.
4) pridal jsem moznost zavrit okno s vypisem erroru
5) navazuji na 3) pokud provedu validaci pres tlacitko vpravo nahore, vyskocim mi modal a pokud se zobrazi chyby. Tak bych je po zavreni modalu ukazal v ramecku nad querry at o ten vypis neprijdu. Coz se ted deje. Proto jsem pridal i moznost zavirani toho vypisu chyb viz bod 4)

Video:
http://take.ms/Y6Gwj

Prototyp:
https://invis.io/BFNT6XO2C8P#/317345832_-1639_-_SQL_Validation_Modal_V2_Copy

**Comment by ondrejhlavacek** [comment]
Super!

Při `Validate & Save` se stejně bude muset zobrazit dialog, protože musíme užiavteli říct, že se budou odesílat informace pryč třetí straně. Co kdyby teda tlačítko v pravým panelu otevřelo modal a po odsouhlasení ho zavřelo a okno doscrollovalo ke Queries, kde by se zobrazilo potvrzení, že ze SQL validní nebo výpis errorů. V bodech:

1. Chybí potvrzení, že query jsou validní. Stačil by asi nějakej zelenej panel na stejný místo, jako jsou errory. Může za chvíli sám zmizet?
2. `Save & Validate` vyžaduje potvrzení modalem, že se odesílají data pryč (http://take.ms/dAvLp).
3. `Validate` vpravo se bude chovat stejně jako `Save & Validate` (modal s potvrzením, scroll na queries a výpis errorů nad queries), jen bez toho `Save`, tlačítko bude disabled, pokud jsou queries rozeditované.

**Comment by Halama** [comment]
Nemůžeme tu třetí stranu zahrnout do terms&conditions? stejně jako AWS, Snowflake a další ext. služby?

**Comment by padak** [comment]
Imho není nutný to dávat do "GDPR seznamů" SQLdep není subzpracovatel dat,
SQL kódy považujeme za metadata, který máme popsaný v TOS jako že patří nám.

**Comment by ondrejhlavacek** [comment]
Super, takže ty modály můžeme vyhodit?

**Comment by padak** [comment]
nezkoumal jsem to celý, ale určitě není nutný mít svolení k odeslání SQL do
SQLDep, tím bych nikoho neotravoval, stejně jako neřešíme NewRelic ani PT.

**Comment by Halama** [comment]
Jde o tenhle modal. V té nové verzi kde je tlačítko `save & validate` by ten modal s tím potvrzením že to jde pryč byl imho mega otravný když to může být uplně bez modalu.

![image](https://user-images.githubusercontent.com/903531/44945223-7d3b7f00-ade4-11e8-9b9d-180133984b3c.png)

**Comment by janmichek** [comment]
Fajn celkove jsem s Jackovym navrhem spoky. Chci to posunout: trochu zjednodusit user flow + znovupouzit stavajici komponenty.

![image](https://user-images.githubusercontent.com/15363559/45089397-4f1fad00-b10c-11e8-983d-2ef58af7bed8.png)


- snazil jsem se ovladaci prvky presunout na jedno misto. Napr" checkbox  -> button 'Ignore errors'- jednodussi na implementaci
- znovupouzivam stavajici komponenty (AlertBlock) pripadne jej muzem dostylovat.
- hodne erroru - zatim bych neresil zabalovani. Predpokladam ze eroru nebudou desitky. Pokud ano AlertBlock se bude dat zavrit tlacitkem 'Ignore errors' na vrchu
- otazka je jestli zobrazovat errory kdyz rovnou prijdu na detail transformace (needituju query) Pripadne na to mam minimalistickou verzi

**Comment by janmichek** [comment]
Prpadne minimalisticka verze ktera by se zobrazila po zobrazeni detailu (pred editaci).
Jde mi o to odlisit ze script je validni. To by nemelo zadny styl - bash style

![image](https://user-images.githubusercontent.com/15363559/45089803-ad00c480-b10d-11e8-8a28-31d5597e1e0c.png)

**Comment by ondrejhlavacek** [comment]
> snazil jsem se ovladaci prvky presunout na jedno misto. Napr" checkbox -> button 'Ignore errors'- jednodussi na implementaci

Hele, a co kdyby tam vůbec `Ignore errors` nebylo? Pokud se to uloží i když tam jsou chyby, tak není důvod je vlastně skrývat a defaultní akce by mohla být `Save & Validate` a žádnej checkbox ani další button by tam bejt nemusel. 

> hodne erroru - zatim bych neresil zabalovani. Predpokladam ze eroru nebudou desitky. Pokud ano AlertBlock se bude dat zavrit tlacitkem 'Ignore errors' na vrchu

Jo, ok!

> otazka je jestli zobrazovat errory kdyz rovnou prijdu na detail transformace (needituju query) 

To není špatnej nápad, tím bychom nepotřebovali tlačítko `Validate` v pravým panelu. Mohlo by se to pustit rovnou. Pokud by to někdo chtěl úplně vypnout pro celej projekt, tak to můžeme udělat třeba přes featuru.

> Prpadne minimalisticka verze ktera by se zobrazila po zobrazeni detailu (pred editaci). Jde mi o to odlisit ze script je validni. To by nemelo zadny styl - bash style

Pro tu minimalistickou verzi nevidím moc důvod - že tam jsou validační chyby je docela průser (pokud neberem v potaz, že to teďka háže false positives).

**Comment by janmichek** [comment]
- validace pri vstupu na detail transformace je asi blbost. Je mozny ze to par vterin bude trvat a akorat to bude blokovat uzivatele nebo? Mentalne tu ideu revertuju

- jsem pro to aby validace byla integralni soucasti detailu transformace. Pokud vsechno delas spravne - nepoznas v ui rozdil. Proto bych ani na button nedaval 'Validate & Save'. Validace probehne jen pri Savu, nebo mame nejaky duvod pro validovani ulozeneho query?

- Ano, teoreticky tam nemusi byt zadny zaviradlo error blocku

- OK, minmalni verzi neni potreba, kdyz nebudem uvazovat validaci pri prichodu na stranku.

- jeste muzeme pridat vetu ve smyslu: 'Ignoring errors will result in failed job, when running transformation'... ?

**Comment by ondrejhlavacek** [comment]
> validace pri vstupu na detail transformace je asi blbost. Je mozny ze to par vterin bude trvat a akorat to bude blokovat uzivatele nebo? Mentalne tu ideu revertuju

Nikoho to blokovat nebude, bude tam spinner a u toho něco jako `Validating queries`, můžeš klidně psát přes to. Než tam imho v okně transformace doskroluješ, bude zvalidováno. 

> jsem pro to aby validace byla integralni soucasti detailu transformace. Pokud vsechno delas spravne - nepoznas v ui rozdil. Proto bych ani na button nedaval 'Validate & Save'. Validace probehne jen pri Savu, nebo mame nejaky duvod pro validovani ulozeneho query?

Souhlas, dáš save, aktualizuje se alert okno s validací. Proto by tam mělo bejt asi už od začátku? viz ^^^

> Ano, teoreticky tam nemusi byt zadny zaviradlo error blocku

Jsem pro. 

> jeste muzeme pridat vetu ve smyslu: 'Ignoring errors will result in failed job, when running transformation'... ?

ok

**Comment by janmichek** [comment]
ok, zacnu implementovat MVP dle posledniho komentare ze soucasnych komponent.

**Comment by janmichek** [comment]
Mam to takhle pripraveny, s vytazenyma hodnotama do dummy statu, takze bych to ted otocil, jestli to muzes napojit. @ondrejhlavacek 
Ta klikaci funkce by vyuzit 'highlightQueryNumber'

![image](https://user-images.githubusercontent.com/15363559/45496347-84b04000-b775-11e8-9ceb-11a217c895c3.png)

**Comment by janmichek** [comment]
@ondrejhlavacek mohl by ses na to pls podivat, at to pripadne stihneme otocit?

**Comment by ondrejhlavacek** [comment]
@janmichek dík, takhle to vypadá super! 

Potřeboval bych ještě progres validace - nějakej loader v bloku? Když zmáčknu Save nebo přijdu na stránku...

> Kdyz nejsou zadny erory, tak ten blok zmizi. Validovat by to teda melo po kliku na Save a pri prichodu na stranku.

Pokud nenajdeme žádný validační chyby, dal bych tam zelenej blok, protože jinak ten loader tiše zmizí bez výsledku.

**Comment by janmichek** [comment]
Mno jak jsem psal - delal bych to minimalisticky.
Pokud vse delas spravne, nepoznas v UI rozdil - bash style.
Bude te to masirovat, jenom pokud tam budes mit chybu.
Loader uz tam je - v talcitku save. Ted to navic bude cekat na validaci + ulozeni.

**Comment by ondrejhlavacek** [comment]
Ten validační loader se save vůbec nesouvisí - validace proběhne až save dojede. Ok, jsem pro to zkusit bez validačního loaderu a bez validačního successu!

**Comment by janmichek** [comment]
Loader v Save buttonu by nedokazal obslouzit i cekani na validaci?

**Comment by ondrejhlavacek** [comment]
Imho je to blbost, protože by signalizoval dvě oddělený věci. Přišel bys na transformaci a rozjel by se ti Loader Save buttonu?

**Comment by janmichek** [comment]
Ano, to je dusledek integrace kterou jsem navrhnul. Ukladani a validace na 1 kliknuti. Prijdes na stranku a neco se deje, to je to co chceme udelat .] jestli je to teda technicky mozny

**Comment by ondrejhlavacek** [comment]
Mně to s tím buttonem přijde divný. Proto jsem nejdřív přemejšlel o loaderu / loader panelu u queries, kde se pak zobrazí errory. 

Když řekneme, že se validuje vždy, když to dává smysl, tak žádný tlačítko nepotřebuje, protože vždycky uvidí stav, ve kterým to dává smysl. Dokážeme celkem snadno říct, kdy se má validovat

- uživatel přijde na stránku
- uživatel uloží query
- uživatel změní input/output mapping
- uživatel změní requires

Po každý z těchhle akcí se SQL znovu validuje. Pak imho stačí (loader, succes a) výpis errorů. 

Teď mě ještě napadlo, že vlastně pokud mám rozdělaný neuložený queries, tak změna mappingu enbo requires ti ukáže errory něčeho, co na screenu nevidíš, takže bych to ještě rozšířil na podmínku, že

- pokud máš rozeditovanou query a měl bys jinou akcí validovat, tak se zvaliduje až po uložení nebo resetu queries

**Comment by janmichek** [comment]
Chtel jsem tohle naimplementovat jako MVP, aby to bylo v produkci a zakladne to fungovalo.
Dobre teda, budeme to muset predelat.

O moznosti rozeditovaneho query a validaci po zmene mappingu jsem nevedel. To budeme muset zohlednit novym zadani. Tohle moje reseni tim padem nevyhovuje.

**Comment by ondrejhlavacek** [comment]
Myslíš teda, že bez loaderu a success stavu to nedává smysl? Zbytek naimplementovat nebude tak obtižný, včetně tý podmínky.

**Comment by janmichek** [comment]
Snazim se znovoupouzivat stavajici UI koncepty a zroven zachovat uzivatelskou privetivost. Neni problem je vytvorit - to je zabavna cast. Mame spis opacny problem https://github.com/keboola/indigo-ui/issues/186 . Tak se to snazim vyresit uz v navrhu.

Pokud validace validuje i requires a mappingy, tak si mozna validacni blok lepe sedne nekde vyse na strance. Nevim.

**Comment by ondrejhlavacek** [comment]
Heh, tak to je dost dobrej postřeh. Ono to mappingy a requires fakt validuje - jsou to věci, který můžou ovlivnit, jaký SQL se může pustit (tabulky z input mappingů a předchozích transformací), validuje se pak i output mapping, jestli tabulka pro output mapping po dokončení transformace existuje.

**Comment by janmichek** [comment]
@ondrejhlavacek  Jenom chci overit:
Nepouzity mapping => neni error
Sql odkazujici se na neexistujici mapping => error

**Comment by ondrejhlavacek** [comment]
@janmichek obojí sedí!

**Comment by jancermak** [comment]
@najlos jen si overuju jakakoliv zmena v requries muze zpusobit nevalidni querry?

**Comment by jancermak** [comment]
@ondrejhlavacek @janmichek 

**video z upraveneho protypu:**
http://take.ms/SxXkR

**prototyp:**
https://invis.io/BFNT6XO2C8P

1. cast — fungovnai ukladani spojene s validovanim query, query se ulozi a pak probehne validace s vysledkem OK/KO
2.cast — fungovani validace - pokud sahnu do requires, smazu polozku input/output mappingu ktera muze byt pouzita v SQL nebo z edituju stavajici  input/output mapping tak ze mi narusi SQL querry.

2a) v prototypu je videt ze po provedeni zmeny, se vedle tlacitka [Saved] objevuje "Validating SQL...", informace o prave probihajici validaci (na tutom netrvam). Kdyz validace probehne OK hlaska zmizi, pokud validace KO - objevi se vypis erroru.

2b)  Pokud error ve validaci, ukazu vypis erroru ale protoze tento vypis pravdepodobne bude mimo viditelnou oblast, vyskoci mi nahore vpravo alert s informaci o nevalidni query - moznost ze po kliknuti zascroluje na cast querry kde je videt vypis erroru.

3 cast — chovani pokud mnoho erroru

**Comment by janmichek** [comment]
Diky za updatovany navrh @jancermak 

- Ja jsem pro variantu bez "Validating ...". V opacnym pripade vznikne otazka - proc to neukazuje "Saving ...". Je to dalsi UI koncept signalizace loadovani. Idealne pokud loader v buttonu muze udelat loading state pro validating + saving.

- Nejsem si jistej jak s tim nadpisem "Query saved, ...". Nikde tam nefiguruje slovo 'Validation'. Nemusi byt jasny o co jde. A ne vzdy se to triggeruje ukladanim query. Muj navrh vyse ^^^

- Ten vypis erroru ve flashmessagi asi nemusi byt. Chtel jsi aby to bylo vyditelny vzdy, vid? Nezkousil jsi pracovat s variantou ze AlertBlock by byl na vrchu stranky?

- bude potreba upravit trochu styly AlertBlocku aby pismo bylo cervene. Neni prob.

**Comment by ondrejhlavacek** [comment]
Červenou flashmessage umíme! :-)

**Comment by janmichek** [comment]
Dobre, necham se prekvapit, Sherlocku .]

**Comment by ondrejhlavacek** [comment]
Odpoj si internet a uvidíš :-)

**Comment by jancermak** [comment]
@janmichek v porad tvych bodu :-)

1) varianta bez validating textu vedle tlacitka - ok
2) text nadpisu v alertu - ok, dava mi smysl tam mit i info o ulozeni
3) flashmessage je v poradku, nechci davat alert na zacetek stranky (proc - dava smysl tam kde je v miste erroru). Vidis ji kdykoliv nezavisle na velikosti viewportu.
4) -
5) upravil jsem vzhled aby to sedelo s indigem
![image](https://user-images.githubusercontent.com/1826442/45962173-8d7bfe00-c020-11e8-8c9c-46d629ddeca7.png)

**Comment by janmichek** [comment]
@ondrejhlavacek  Za nas je to teda pripraveno k implementaci, shrnu ti to co je potreba:

- Validaci spustit po - ulozeni query, ulozeni/zmene mappingu, pridani / odebrani polozky v Requires. sql validaci
- alert flashmessage s textem "SQL Validation found N errors"
- klik na error -> zascrollovani na radek qery (pripadne zvyrazneni)
- ulozeni query obslouzit pres loader v Save/Saved buttonu. Obecne - pokud vse delas spravne, nepoznas rozdil - bash style.
- odebrat z leve nabidky nabidku validace
- hodne erroru zatim neresme

**Comment by ondrejhlavacek** [comment]
Super, dík, jak bude chvilka, pustím se do toho :-) (Nebo kdyby se na to našel někdo jinej... :-))

**Comment by janmichek** [comment]
@natocTo Kdybys chtel, muzes zkusit zaimplementovat toto dle myho predposledniho commentu. Ui elementy jsou dummy, jde o to je napojit s popsanym chovanim. Sam jsem si to uplne nedaval, takze kdyz nebudes vedet, nevadi.

**Comment by janmichek** [comment]
Odkladam si: kvuli tem stylum alert blocku bude potreba oprasit toto https://github.com/keboola/indigo-ui/pull/174 nedotahnul jsem to, protoze jsem se v tom nejak zamotal. Tak s odkladem to snad bude lepsi

**Comment by janmichek** [comment]
Mel by sis vystacit s predpripravenym dummy markupem v branchi + timto souhrnem ze zadani.
Vznikalo to tak organicky, tak by te ty commenty vyse mohly plest, protoze jsou outdated.
Kdyz nebudes vedet, radeji se ptej.

**Comment by natocTo** [comment]
Ok tak se hned zeptám. Čtu: `odebrat z leve nabidky nabidku validace` to je myšleno vpravo ta "Validate BETA"? Jinak teda model půjde pryč a bude to přímo u těch queries.

**Comment by janmichek** [comment]
Hups, z PRAVE nabidky vyhodit akci Validate SQL.
Nejspis ano, tak funkcionalita se bude muset presunout, to je to do ceho jsem nechtel zabrusovat .]

**Comment by natocTo** [comment]
Oki, díky za info.

**Comment by janmichek** [comment]
> To přijdu a budu klikat na nové inputy (input, output mapping) nebo mazat ty staré a pokaždé se mi bude pouštět nová a nová validace? Já do toho úplně nevidím, ale nejsou ty inputy, outputy potřebné pak pro tu samotnou query. Neměla by ta validace být spíš jen u toho. Je jasné že toto máte vyřešeno ale jak to mám implementovat, tak se radši ptám na vše.

Ano, v query pouzivas tabulky z mappingu.  POkud se odkazujes na nenamapovanou tabulku -> Error. Pokud mas namapovanou tabulku, ale v query ji nepouzijes -> neni to error.
Pokud je to slozity, tak zatim obsluhuj jen zmeny v query. Se zbytkem muze poradit, nebo prevzit @ondrejhlavacek 


> Tady budu asi vycházet z toho jak to bylo řešeno v tom modalu. Nebo tu to bude úplně jinak?

Ano, ta funkcionalita uz je naprgana, staci ji znovupouzit

**Comment by ondrejhlavacek** [comment]
Ideální by bylo, aby se validace pouštěla po každým uložení transformace nebo při příchodu na stránku - tj. při při jedné z následujících akcí

- uživatel přijde na stránku
- uživatel uloží query
- uživatel změní input/output mapping
- uživatel změní requires

(https://github.com/keboola/kbc-ui/issues/1639#issuecomment-422022871)

to by nemuselo bejt tak těžký dodělat do všech příslušnejch akcí případně to triggerovat eventama o úspěšným uložení?

**Comment by ondrejhlavacek** [comment]
přihodím refereni, nemohl jsem jí najít :-) 

https://github.com/keboola/kbc-ui/pull/2028

**Comment by natocTo** [comment]
To by mělo sedět až na ten první bod. 
Přes eventy nebo další store jsem to na začátku zkoušel, ale dělalo to problémy a bylo to i zbytečně složité. Pak jsem tam nahodit jiný jednoduší řešení kde akorát porovnávám starý a nový objekt. 
Tak dodělám pouštění při startu komponenty. Což se teda pustí hned jak někdo vytvoří novou transformaci.
