### ISSUE TITLE
keboola.ex-http neukazuje "last runs"

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1643]
Na pravo nejsou vidět joby
![image](https://user-images.githubusercontent.com/1427901/39087923-1249cc9a-45a9-11e8-8e4d-5feacf1dbcd8.png)

(https://connection.eu-central-1.keboola.com/admin/projects/141/extractors/keboola.ex-http/1143531/rows/1143534)

**Comment by ondrejhlavacek** [comment]
To se nezobrazuje nikde, ani u transformací a dalších komponent. Tady bych to zavřel, budem to muset vyřešit nějak globálně.
