### ISSUE TITLE
Align columns ordering between Storage and Components

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1645]
In storage, I have table X with col A,B,C. In DB writer, I see table X with col C,A,B. It would be great to align it for better user comfort.

(more details in https://keboola.zendesk.com/agent/tickets/8317)

P.

**Comment by Halama** [comment]
Nejspíše souvisí s https://github.com/keboola/connection/tree/7ce8c0ae7df380991b44896bcedf5900fb965391/docker/php-apache/snowflake

**Comment by ujovlado** [comment]
Mohli by sme to vo writeri zosortovat tak ako je to v storage, nie? Tie info tam su.

**Comment by Halama** [comment]
Objevilo se znovu nejspíš https://keboola.slack.com/archives/C0308KGPP/p1525256959000292 
@kacurez můžeš to prosím teda prozkoumat?

**Comment by ujovlado** [comment]
@Halama uz je na to PR, akurat ho pozeram

**Comment by pivnicek** [comment]
btw, tedko kazde sloupec z db extraktorama ma metadata `KBC.ordinalPosition`

**Comment by Halama** [comment]
aha, sorry to jsem přehlédl
