### ISSUE TITLE
hlavní menu scroll na windows

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#165]
![image](https://cloud.githubusercontent.com/assets/903531/8201855/0d8fd2e2-14d5-11e5-8107-1e125380d1f4.png)

S tímhle @JakubMatejka asi moc udělat nedokážeme co? Pamatuju si na custom scrollbar na OpenBrandu a bylo to dost peklo

**Comment by JakubMatejka** [comment]
No tvl. ;o) Je metoda s dvouma divama kdy vnější má `overflow:hidden` a vnitřní má větší šířku s tím scrollbarem který se tím pádem schová (http://stackoverflow.com/a/23336415/436706) ale nám se to tím celý rozhodí protože ten sidebar má `position:fixed`, flexibilní šířku a kdo ví co ještě. To je tak úkol pro nějakýho css mága spíš. ;os

**Comment by Halama** [comment]
jo asi bych se do toho nepouštěl, možná bude řešením nějaké jiné zobrazení na menším zařízení. To mi připomíná že mám Padákovi odpovědět na toho týpka co nabízel že by nám pomohl. Teď bych tohle teda asi neřešil.

**Comment by Halama** [comment]
Dost tady s tím dole všichni bojují s těmi scroll bary na tech mikro displejích :)
Možná tam hodit nějaký responsiv styl. Tohle jsem zkoušel v inspectoru:
![image](https://cloud.githubusercontent.com/assets/903531/8207292/b8b053c4-1500-11e5-9d35-f7e28b3b6152.png)

**Comment by JakubMatejka** [comment]
Jak to myslíš responsiv styl? Z toho screenshotu to asi nechápu ;o)

**Comment by Halama** [comment]
jako že by při určité výšce viewportu to tomu dalo jiný styl tomu v tom sidebaru. Na tom screenu jsem zmenšil fonty, padding a vyhodil ikonku uživatele aby to bylo na mac displeji bez scrollbaru.

**Comment by Halama** [comment]
bez té úpravy to vidím takhle
![image](https://cloud.githubusercontent.com/assets/903531/8207519/5226a6ba-1502-11e5-8ccf-9da6ecd656b3.png)

**Comment by JakubMatejka** [comment]
Jo, no, zeptej se spíš asi Martina. Už mi jednou vyčinil za to že jsem měl moc malý ty paddingy ;o)

**Comment by Halama** [comment]
@JakubMatejka Ta velikost a roztahanost je asi hlavni výtka většiny uživatelů. Teď jsem to ukazoval MK a taky mu prislo ze je to nejaky moc velky. Tady je jeho odpoved: "Tak jestli pujde jednodusse udelat nejaky zoom na cca 75% tak to bude asi nejlepsi reseni - ono by slo asi pripravit i variantu kde bude min white-space kolem elementu pro male rozliseni, ale to je asi zbytecne pracne ted." 

Vubec netusim jak moc je to realny nebo slozity tahle uprava. Nejvetsi problem je v tom levem menu ktere scrolluje na 1200x800
![image](https://cloud.githubusercontent.com/assets/903531/8328846/97337964-1a74-11e5-8840-b9cb64c152b3.png)

To leve menu by bylo asi taky dobry zafixovat na sirku, je zbytecne aby se roztahnovalo s sirkou celeho screenu.

Související issue #189 

Soupis toho co nejvíc vadilo analytikům a dával jsem MK #199 

Asi jsem tě moc nepotěšil :) kdyžtak můžeme dát nějaký call kdyby něco nebylo jasné nebo se spoj s MK
díky

**Comment by Halama** [comment]
trochu jsem si  s tim pohral v kbc-bootstrap a myslim ze to celkem pujde. To zitra zkusim dotahnout a nasadit s tim

**Comment by Halama** [comment]
fixnuto
