### ISSUE TITLE
OM - invalid bucket name

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1662]
when bucket name is not valid, there is no indication that it is the reason why OM cannot be created:

e.g. http://youtu.be/KRobJr3FCyE?hd=1 this is highly confusing

possible solutions:
- highlight invalid bucket name?
- don't juggle with dots?

**Comment by ondrejhlavacek** [comment]
co kdyby se rovnou webalizoval název bucketu i tabulky?

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/39967911-46d263ba-56c4-11e8-85f8-cea757f417aa.png)
