### ISSUE TITLE
Improve ex-db-generic credentials workflow

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1663]
When you save credentials it briefly shows static form which looks kind of sloppy.

When saving, it's best just to disable the individual form elements.

**Comment by pivnicek** [comment]
other comments from PR #1542  that are valid here:

https://github.com/keboola/kbc-ui/pull/1542#issuecomment-388073876
https://github.com/keboola/kbc-ui/pull/1542#issuecomment-388074230
https://github.com/keboola/kbc-ui/pull/1542#issuecomment-388067551

**Comment by pivnicek** [comment]
Also, remove ellipses

**Comment by ondrejhlavacek** [comment]
horizontal scrollbar https://github.com/keboola/kbc-ui/pull/1542#issuecomment-389175291

**Comment by pivnicek** [comment]
hmmm, that horizontal scrollbar shows up in some other places too: 
![image](https://user-images.githubusercontent.com/569139/40615113-bb4b0644-6285-11e8-8c82-c44824509015.png)

**Comment by pivnicek** [comment]
Changing `.kbc-main-content` to `overflow:hidden` gets rid of the scrollbar, but I'm not sure what over ramifications that change could have.  I think I'll move the scrollbar issue to Indigo
