### ISSUE TITLE
Storage - Data Sample text position

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#167]
Text should we aligned to the top of the row as in the previous version, so it's easier to read.

**Comment by padak** [comment]
Cti prosímtě starý issues co jsou otevřeny, než reportujes chyby. Pokud na
to nemáš čas, tak to zatím nepouzivej, prosim. Za nás to není dotestovany.

Sent from mobile
Dne 17. 6. 2015 11:13 AM napsal uživatel "Matejkys" <
notifications@github.com>:

**Comment by Halama** [comment]
@padak je to dotestovany, poslal jsem to analytikum k testu. Tohle je neco jineho nez MM reportoval predtim.

**Comment by Halama** [comment]
viz #ui kanal ve Slacku

**Comment by padak** [comment]
Aha!

Sent from mobile
Dne 17. 6. 2015 11:25 AM napsal uživatel "Martin Halamíček" <
notifications@github.com>:

**Comment by Matejkys** [comment]
Díky za zastání. Jinak k tomu byl původně screen, ale pak jsem ho dal na
Halamovu radu pryč, aby se tam neválely žádný klientský data (i když málo).
Ps: issues jsem si samozřejmě nejdřív prohlédl (otevřený)
