### ISSUE TITLE
keboola.wr-storage update

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1675]
- [x] trim inputs (https://github.com/keboola/kbc-ui/pull/1674#pullrequestreview-119973423)
- [x] add warning (https://keboola.slack.com/archives/C31U6BGJC/p1526320224000004?thread_ts=1526314546.000750&cid=C31U6BGJC)
- [x] split into separate sections
- [x] add filters (?)

**Comment by ujovlado** [comment]
Mozno teda, este jedna vec. Super by bolo, keby som ten bucket nemusel pisat manualne ale vybrat ho zo Selectu, kde je search. :) Tym padom by odpadlo to trimovanie

**Comment by ondrejhlavacek** [comment]
No, ten bucket by tam vlastně vůbec bejt neměl. 

> You need to provide a Storage token from the destination project which has write access to the target bucket only.

https://github.com/keboola/wr-storage/issues/6

**Comment by ondrejhlavacek** [comment]
A stejně tak bych tam ani nedával url na connection, ale dropdown s výběrem regionů, co myslíš?
