### ISSUE TITLE
Špatná kombinace barev u linků na job

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#168]
Když na mě vyskočí, že se třeba pustil upload do GD, text, a zejména link "here", se na pozadí hodně špatně čte.

![table out c-main finance 2015-06-17 11-36-46](https://cloud.githubusercontent.com/assets/12933713/8203970/b89f35b4-14e5-11e5-85f8-de34d94a7522.jpg)

**Comment by Halama** [comment]
@JakubMatejka  ten text i mimo link fakt není moc čitelnej. Tady https://www.dropbox.com/sh/6rbxc1erwfovsv3/AABq9nnnG6MeQ__Ni53rQMska/alerts_colors.psd?dl=0 mi to přijde lepší, možná to je fontem nebo je tam přecijenom tmavší?

**Comment by Matejkys** [comment]
Jo, je tam lepší kontrast a i trochu hutnější font. To už se mi čte líp.

**Comment by Matejkys** [comment]
A přidám k tomu i barvu menu ve Writeru. Ta modrá je asi všude moc světlá a zářivá a na tom světlém pozadí se čte opravdu zle.
![gooddata - okin_poc 2015-06-17 12-29-36](https://cloud.githubusercontent.com/assets/12933713/8204956/b4a9de8a-14ec-11e5-9233-f1d6a64f121a.jpg)

**Comment by JakubMatejka** [comment]
Menu ve Writeru by mělo být tučným fontem, to upravím. Jinak ten alert je podle mě správně. V tom psdčku nalevo to není jak to má vypadat, to je default styl Bootstrapu, napravo je to upravený Martinem.  Na mým i externím displeji to vypadá ok. ;o) Samozřejmě to ale nikdy nebude jako ve Photoshopu už proto že tam funguje úplně jinak antialiasing. Ten odkaz v alertu bych ale asi nechal stejnou barvou jako text, jen ho ztučnil a podtrhl. Ta modrá tam vypadá blbě.
