### ISSUE TITLE
Can't place underscore in name of my output table in TR output mapping

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1682]
KBC mi forcuje pomlčku místo podtržítka v názvu tabulky ve storage. Je to omezující.
![competition products 2018-05-15 23-17-01](https://user-images.githubusercontent.com/12933713/40084110-5b784676-5896-11e8-9bea-2bf3b2cb2317.png)

Když to bylo od začátku standardem v projektech, najednou se nuceně mění jmenné konvence.

**Comment by janmichek** [comment]
@Matejkys Zrovna tohle resime, melo jsme to uz reportovany. Co je za tebe idealni reseni?

**Comment by Matejkys** [comment]
@janmichek Nechat to tak, jak to bylo předtím, kdy mě KBC nenutila místo podtržítka (což patří mezi standard v databázích) použít pomlčku. Věřím, že za tou změnou nějaký důvod byl, ale žádný mě nenapadá :)
Hlavně když si nevymyslím svůj název tabulky, podrtržítka tam evidentně být mohou, takže to automatické přepsání na pomlčku nedává smysl.

**Comment by ujovlado** [comment]
Len pridam, ze sme to zmenili tu: https://github.com/keboola/kbc-ui/pull/1669 ... ten underscore by sme tam asi mohli povolit.

**Comment by ujovlado** [comment]
(samozrejme nie na zaciatku a na konci - kde to robi bordel)

**Comment by kacurez** [comment]
dostali sme nato dalsi ticket, tak ja sa to teraz pokusim fixnut a pripravim PR.
