### ISSUE TITLE
Output Mapping - Source to Destination

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1684]
Narazil jsem na tyto 2 veci, kdyz jsem prochazel UI

1. z uzivatelskyho hlediska by bylo privetivejsi, kdyby se kazdy znak z nazvu hned dostal do selectu destination table. Ne az kdyz dam focustout z inputu. Pro novacky neni jasny, co se tam deje.

2. Tady si dokazu predstavit, ze to muze byt slozitejsi, nebo to casti uzivatelu nemusi vyhovovat.  Jde o to ze kdyz napisu nazev, potom treba odmazu 2 znaky - nazev tabulky v destination se uz nezmeni.

![gif](https://user-images.githubusercontent.com/15363559/40108424-1d863da4-58fb-11e8-854f-8fcbbb2a0401.gif)

**Comment by kacurez** [comment]
Podla mna to ze sa nezmeni uz nastaveny destination po dodatocnej zmene source je spravne. Ak user edituje OM a zmeni source tak predpokladam ze destination chce nechat vacsinou nezmeneny aby mu ostala tabulka ktora sa doteraz plnila zo source. Ak sa zmeni destination tak vznikne nova tabulka a to by som radsej ponechal plne na userovi kedy sa zmeni destination. Preto som to urobil na focusout. 

Ak sa dohodneme ze vzdy so zmenou source sa zmeni aj destination bezohladu nato ci je vyplnene alebo nie tak ok ale som zato aby sa to viac prediskutovalo, najlepsie na slacku v uiux ci?

**Comment by ujovlado** [comment]
Tu suhlasim s @kacurez . Je to mozno menej UX friendly. No viem si predstavit ze user zmeni sql, potom zmeni tabulku no stale chce aby to slo do tej istej destination. Inac by to musel cele menit. ;)

Podobne sa to chovat napr. v db-extractoroch (tam som to pri prerabke prave fixoval). Ked zmenim meno query (moje interne pomenovanie), nijako to neovplyvni destination - co je super.

**Comment by kacurez** [comment]
este doplnim ze imo je spravne menit destination len ak je prazdny. Ak by sa automaticky vyplnoval prazdny destination pri zmene source tak to ide len na focusout pretoze v opacnom pripade by sa destiantion prestal vyplnovat po prvom vyplnenom pismene v source.

To by sa teoreticky dalo opravit tak ze na focusin source si zapamata ze desination je prazdny a potom po kazdom zadani pismena v source sa hned vyplni aj v destination. Ak destination na focusin-source neni prazdne tak sa nedeje nic.

**Comment by janmichek** [comment]
Jeste to vic rozvedu, celkove to ovladani neni konzistentni. Tohle je jen cast z toho. VYtvorim na to issue

**Comment by kacurez** [comment]
#### Create New Output Mapping
![omprefill](https://user-images.githubusercontent.com/1412120/42817628-ed4add34-89ce-11e8-9add-56a9f2cc0343.gif)
#### Edit existing Output Mapping
![editomnoprefill](https://user-images.githubusercontent.com/1412120/42817834-90cd6aee-89cf-11e8-96f9-78287378b835.gif)
