### ISSUE TITLE
OM controls tuning

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1685]
Sešlo se nám tady několik i protichůdných požadavků na vylepšení a při tom bylo nalezeno ne úplně korektní ovládání. Asi budeme chvíli diskutovat, než přijdeme s řešením. Tady to zanalyzujeme, jack pak přijde s uživatelskou flow pro různý případy. Následně implmentujeme.
Ocekavam kreativni reseni a ne seznam duvodu proc to nejde .]

***Požadavky na OM***
1 - https://github.com/keboola/indigo-ui/issues/134 - zadany nazev do Destination Table automaticky vyhazuje prvni "_" To je ok, jenom chceme o tom uzivatele notifikovat. Nejspise pomoci flashmessage, dokud nebudeme mit generickou validaci formu

2 - https://github.com/keboola/kbc-ui/issues/1682 - nevynucovat prepis underscore na pomlcku (neprvni znak). Pokud za tim neni zadny duvod, vyhodme to.

3 - vytunit ovladani

***Nedostatky***

4 - focusout - jednou znamena potvrzeni, jednou znamena cancel. Je to spis filozoficky. 
![focusout](https://user-images.githubusercontent.com/15363559/40121980-16eb9b42-5923-11e8-8397-1a5521e606eb.gif)

5 - force _underscore - Souvisi s 1). Prvni podtrzitko tam lze stejne procpat a ulozit, viz gif.
![bugunderscore](https://user-images.githubusercontent.com/15363559/40122235-a0d7fac6-5923-11e8-8f4b-f2aea2189aff.gif)

6 - force under_score - Souvisi s 2). Podtrzitko uprostred nazvu lze stejne procpat a ulozit, viz gif.
![bugunderscore2](https://user-images.githubusercontent.com/15363559/40122351-e3081c28-5923-11e8-8b43-33f0558c0da3.gif)

7 - neprepisuje se Source -> Destination Table. Souvisi s 4). Prepise se az po focusoutu. Mam za to ze v kbc tento pattern (focusout = save) nepouzivame. Vsimnul jsem si toho i pri testovani GM a ani nevim jakou bych k tomu mel dat instrukci. 
Typicka userflow: Otevru OM Modal -> Pisu nazev pro Source -> kouknu co me ceka dal ->zbyva vyplnit Destination Table -> vymyslim nazev pro D Table -> nazev jsem vymyslel, tak kliknu ze ho napisu -> aaaaha, ono se to vyplnuje automaticky.
Vyresilo by to prepisem po stisku klavesy jednotlivych znaku. Nejaky poznatky mame tady https://github.com/keboola/kbc-ui/issues/1684#issuecomment-389468624
![prepis](https://user-images.githubusercontent.com/15363559/40123049-822ed08e-5925-11e8-9656-ce5edf351bd3.gif)

8 - Zmena Source nazvu nezmeni nazev Destination Table - coz muze mit duvod. Diskutovali jsme zde https://github.com/keboola/kbc-ui/issues/1684#issuecomment-389461728

9 - nelze editovat entity v react-selectech. Me osobne to nevadi, Jackovi se to moc neliblo. Je potreba smazat a napsat znovu.

**Comment by ondrejhlavacek** [comment]
Proč jsme tu assignovaní všichni? :-)

5+6 jsou bugy, to opravíme, jasně.

Přidal bych ještě jeden kousek

10 - input v selectu na novou tabulku je kratší než select (platí i pro název bucketu)

http://take.ms/fk7mT

**Comment by janmichek** [comment]
@ondrejhlavacek  diky za dalsi podnet.
Sezval jsem sem vic lidi, abychom to probrali, nez se na to vrhneme. Jak je videt, prineslo to svoje ovoce

**Comment by kacurez** [comment]
este Marcus pise ze chce zachovat case sensitivitu tj povolit tabulky s velkymi pismenami.

**Comment by ondrejhlavacek** [comment]
@kacurez má pro to nějakej důvod kromě legacy kompatibility? @padak nenapadá tě něco?

**Comment by kacurez** [comment]
@ondrejhlavacek aky je vlastne dovod ze to az takto sprisnujeme pokial to na backendu preide? nerozumiem tomu alebo mi nieco unika..

**Comment by ondrejhlavacek** [comment]
Mohlo by to bejt treba zjednodušení?

**Comment by kacurez** [comment]
skor sa obavam ze tym uzivatelov nutime do komplikovanejsich rieseni - ze budu vytvarat tabulku v konzoli alebo cez klienta a potom v OM napoja na existujucu tabulku len kvoli tomu aby tam mali velke pismena..

**Comment by kacurez** [comment]
ale mozno si to radsej rozmyslia a zvolia jednoduchsi nazov :)

**Comment by padak** [comment]
Zahoďme ladění OM a pojďme řešit, aby se mohli tabulky jmenovat jakkoliv, stejně jako se "nějak" jmenuje samotná transformace. Vůbec bych se nezabejval podtržítkama - klidně ať je to ve storage jako "hatlamatlahash1234", protože user řekne, že se to jmenuje "Data Quality #23 from Žídek Mireček". 

Jinak za mě největší past je, že v existující transformaci dostaneš nově navrženej název novýho bucketu a pokud to do něj nechceš, protože to máš jinde, tak to dokola přepisuješ. Ten default bucket by měl jít přetížit, aby když jednou řekneš "chci to sem", tak to "sem" jsme ti pak nabízeli místo toho defaultu.

**Comment by Halama** [comment]
proč by se to ve storage jmenovalo jinak než to pojmenuješ?

**Comment by ondrejhlavacek** [comment]
To napojení na existující je dobrej point

**Comment by padak** [comment]
@Halama protože to tak funguje všude jinde. User dneska neřeší, pod jakým ID ukládáme jeho cfg - tak stejně tak nedává smysl, aby řešil, jak si fyzicky pojmenováváme data v našem storage. Pokud budeme tabulky přejmenovávat, budeme muset ve starejch cfg tyhle změny reflektovat (existuje transformace co pracuje s "uzivatele" a pak to někdo o 1/2 roku později přejmenuje na "users" a transformace failne).

**Comment by Halama** [comment]
@padak jo to je prece  zrejmy. jenom jsem na to narazel ze do toho tahas nejaky interni id, vnirni pojmenovani apod, to s tim vubec nesouvisi a jsou to implementacni detaily nedulezity pro to jak se to chova na venek.

O tomhle preci mluvim uz dlouho a za me je to nejdulezitejsi vec k dotazeni z features. Je ale potreba aby se toho nekdo ujal a rozepsal to co to vsechno bude obnaset.  Vubec neresme nejake vnitrni veci, bavme se o tom jenom z pohledu API a uzivatele.

Ve strucnosti si myslim ze by to melo byt takhle:

Tabulka ma nejake id to muze byt cokoliv (v ui se vubec NIKDE nezobrazuje), potom ma nejake jmeno to vidis v UI vsude a muzes ho menit. Ve vsech konfiguracich (transformace, writery)  je naopak jako reference tabulky jeji id. To same plati pro buckety. 

U bucketu a tabulek je to myslim v pohode u sloupcu to bude komplikovanejsi protoze u nich ted typicky zadne mapovani neni. Napr. v IM transformace u tabulky mas jeji id (vidis friendly jmeno) -> jmeno v transformaci. Pokud zmenis jeji friendly jmeno v sapi transformace ti pojede protoze pujde porad o stejnou tabulku a jeji jmeno v samotne transformaci zustane stejne. U sloupcu ale tohle chybi tam je to vzdy 1:1, nejak mi prijde ze tady by se to spis dalo resit realnym prejmenovanim sloupce tzn. uz sloupcu by nebylo id + jmeno ale stale jenom jmeno ktere je zaroven identifikator. Mozna je ale divny ze by se to chovalo jinak a bylo by lepsi to domyslet tak aby se to chovalo konzistente...

**Comment by kacurez** [comment]
To pomenovanie tabuliek by bolo najlepsie zaviest s novou konzolou, tam je nato najlepsi priestor.

**Comment by kacurez** [comment]
@ondrejhlavacek ako stym case sensitive pomenovanim OM? Ja osobne v tom stale nevidim problem takze by som to povolil. No ak vtom je nejaky problem tak by bolo dobre spisat preco atd a pripravit canned response pre zendesk alebo dat na status. (cc @ErikZigo )

**Comment by ondrejhlavacek** [comment]
@kacurez ok!

**Comment by kacurez** [comment]
ok tak pripravim fix do toho PR s underscore

**Comment by janmichek** [comment]
Tohle je hotovy?

**Comment by janmichek** [comment]
Pripichavam vizualni / koncepcni reseni k bodu 5. 
https://github.com/keboola/indigo-ui/issues/134

**Comment by janmichek** [comment]
@kacurez Delal jsi na tomto neco, pls? pripadne to muzeme zaktualizovat, vyhodit, pretavit do konkretnich issues.

**Comment by kacurez** [comment]
@janmichek pamatam sa ze som riesil nieco s podtrzitkom a case sensitivitu a mam zato ze to je +- v kompaktnom stave.
este z toho by sa mohlo poriesit:
- autmaticke vyplnovanie prazdneho destination pri pisani source(bod 7) (kludne poriesim)
- editovatelny react-select(bod 9) - tam sa trocha obavam ze to cez react-select nepojde a sa bude musiet pouzit ina komponenta(autosuggest)?

**Comment by janmichek** [comment]
Dik za update. Kdy zas zavitas do kanclu? Na chvili bych si na to chtel sednout a procistit to, rozebrat si zbyly issues, pripadne neco vyhodit.

**Comment by kacurez** [comment]
ok mozme, zajtra som v kancli dnes som mal train office :)

**Comment by janmichek** [comment]
Revize a update issues:
1 - vyreseno validaci on the fly - nestava se uz magic pri vytvoreni OM
2 - vyreseno - mapping dovoli psat i pomlcky
3 - vyreseno
4 - vyreseno
5 - poresit aby nebylo mozny procpat podtrzitko pres volbu 'create new table _____test'
6 - vyreseno
7 - vyreseno
8 - vyreseno
9 - napad dobry, ale zas nam to tolik nevadim. zatim neresime.
10 - stylovaci vec, to si beru ja

Kacurez fixne bod c.5
Ja si beru tu stylovacku bod c.10

Issue tim padem zaviram
