### ISSUE TITLE
Deprecated component - migration alert

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1698]
![image](https://user-images.githubusercontent.com/497675/40309443-cd56a0ea-5d09-11e8-913c-aca09d910472.png)

tlačítko `Proceed to Migration` by nemělo bejt tak nalepený na textu, samostatnej paragraf

**Comment by janmichek** [comment]
To ano, podivam se na to.

**Comment by janmichek** [comment]
@ondrejhlavacek fixed.

Byla to moje chyba, rozvasnil jsem se s markupem v Indigu a pak jsem zpetne jsem to neupravil v KBC.
Jeste zitra podrobne chceknu, jestle je vse dle predlohy https://indigo.keboola.com/?selectedKind=AlertBlock&selectedStory=Recommended%20contents&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel
