### ISSUE TITLE
config rows ui

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1699]
- [x] odstranit normalizaci / backward/forward kompatibilitu z wr-storage a řešit to bokem
- [x] ostranit root onload a onsave, všechny funkce pracují s kompletím configem/localstate a výsledek se merguje (https://github.com/keboola/kbc-ui/pull/1718)
- [x] vyřešit zpětnou kompatibilitu při přidávání parametru (PR https://github.com/keboola/kbc-ui/pull/1763)
- [x] oncreate vrací configuration (https://github.com/keboola/kbc-ui/pull/1718#issuecomment-391634458, https://github.com/keboola/kbc-ui/pull/1750)
- [x] json editor i pro config (zpětná kompatibilita s beta komponentama) (#1717) (PR #1751)
- [x] sync akce (wr-storage)
- [x] testy (k columns editoru, https://github.com/keboola/kbc-ui/pull/1718#issuecomment-391769750)
- [ ] naming konvence - sjednotit aby názvy obsahovaly co to je (funkce, objekt, ...), co obsahuje (configuration/configuration row), aby byla správně v kontextu (ColumnMapping => StorageTableColumnMapping)
- [ ] custom config name pro writery? buď custom fce, nebo do name config row předat jen tablename.
- [ ] helper pro testy, `*.spec.js` se furt dokola kopírují

**Comment by ondrejhlavacek** [comment]
https://keboola.slack.com/archives/C02J3DKH3/p1526630087000199

**Comment by ondrejhlavacek** [comment]
mergování procesorů: komponenta si určí, jaký pořadí procesorů má mít a to se pak po mergi sesortuje

https://keboola.slack.com/archives/C03JBGZDG/p1527682099000199

**Comment by kacurez** [comment]
### ad ` vyřešit zpětnou kompatibilitu při přidávání parametru`
Zamyslel som sa nadtym a napadlo ma nasledovne:
Kazda sekce bude mat moznost definovat okrem onSave, onLoad.. aj funkciu **onConform**(popripade iny nazov) ako:
 ```js
onConform: (configuration) => conformedConfiguration //default identita tj len vrati configuration
```

V `parseBySections` kazda onLoad fce dostane conformed config ktory sa zostavi mergom vysledkov z onConform(config) pre kazdu sekci tj vo vysledku sa nevola `parseSectionFn(configuration, tables)` ale `parseSectionFn(conformedConfiguration, tables)`

```js
function conformBySections(sectionsConformFn, configuration) {
  return sectionsConformFn
    .reduce((memo, conformSectionFn) => {
      const conformedSectionConfig = conformSectionFn(configuration);
      return memo.mergeDeep(conformedSectionConfig);
    }, configuration);
}

function parseBySections(sectionsParseFn, sectionsConformFn, configuration) {
  const tables = TablesStore.getAll();
  const conformedConfiguration = conformBySections(sectionsConformFn, configuration);
  const sectionsParsed = sectionsParseFn.map(parseSectionFn => parseSectionFn(conformedConfiguration, tables));
  return sectionsParsed;
}

}
```

priklad onConform funkce:
```js
function onConform(configuration) {
  return configuration
    .setIn(['parameters', 'checkbox'], configuration.getIn(['parameters', 'checkbox'], false));
}
```

onConform sa moze pouzit aj v **createEmptyConfiguration** nasledovne:
```js
function createEmptyConfiguration(name, webalizedName) {
  return onConform(createConfiguration((Immutable.fromJS({name: webalizedName})));
}
```
alebo upravit createEmptyConfiguration v sections.js aby volalo onConform zakazdym podobne ako parseBySections.

#### `isParsableConfiguration`

```js
export default function(configuration, parseFunction, createFunction, conformFunction) {
  if (configuration.isEmpty()) {
    return true;
  }
  const parsed = parseFunction(configuration);
  const reconstructed = createFunction(parsed);
  return Immutable.is(conformFunction(configuration), reconstructed);
}
```
kde conformFunction je conformBySections z sections.js

#### Vyhody
1. vyriesi to problem so spätnou kompatibilitou
2. defaulty configu na jednom mieste
3. ziadne zlozite ify :)

#### Nevyhody
1. definicia defaultov v onConform cez setIn a getIn je mozno trocha neprehladna. Viem si predstavit ze by sa k tomu dorobil helper takze by to mohlo vyzerat napr:

```js
function onConform(configuration) {
  return conformHelper
    .setDefault(configuration, ['parameters', 'checkbox'], false)
    .setDefault(configuration, ['parameters', 'otherKey'], 'some value')
    .configuration;
}
```
2. `conformBySections` kde sa robi mergeDeep moze byt problem napr pri odstanovani niektorych klucov v mape. **Moznou alternativou je nerobit onConform pre kazdu sekci** ale globalne na jednom mieste pre cely config. Takze kazdy row resp. root configuration bude mat jednu globalnu onConform fci. 

#### Pomenovanie
Nazval som to `onConform` ale nebranim sa inemu pomenovaniu, napr onNormalize..?



ci?

**Comment by ondrejhlavacek** [comment]
super! trochu víc se mi líbí varianta, že by `onConform` zpracovávala celou konfiguraci, protože se má pouštět ještě před `onLoad`/`parse`, kde se z jednoho configu stávají sekce. ale zase může bejt šikovný si jí rozdělit na menší části - nedokážu se teď sám rozhodnout :-) 

nebude tam problém s (deep)mergem, když jedna sekce odstraní nějaký klíč a druhá ho zaignoruje (zůstane tam), tak ten (deep)merge klíč taky nechá. => tj je asi lepší mít jednu fci globálně.

```js
function parseBySections(sectionsParseFn, conformFn, configuration) {
  const tables = TablesStore.getAll();
  const conformedConfiguration = conformFn(configuration);
  const sectionsParsed = sectionsParseFn.map(parseSectionFn => parseSectionFn(conformedConfiguration, tables));
  return sectionsParsed;
}
```

- `createEmptyConfiguration` by `onConform` používat neměla, `onSave` musí vždy vrátit aktuální platný stav.

**Comment by kacurez** [comment]
jj tiez si myslim ze mat tu fci globalne je lepsie. Tak ja nahodim PR a uvidime, okrem testov by tam nemalo byt vela kodu.

**Comment by ondrejhlavacek** [comment]
pustil bych se do něčeho dalšího, ale počkám radši na merge #1763 a #1750

**Comment by kacurez** [comment]
^^detto: uz su mergnute, tak ja zacnem testami k columns editoru a potom sa vratim k ui gooddata writer v3

**Comment by ondrejhlavacek** [comment]
jj, obojí mergnuto, můžem pokračovat (jsem teda teď po uši v infrastruktuře). pak bych začal dělat ty sync akce nebo bych rychle vysmrk ui k storage extraktoru / s3 writeru (nebo to zkusím nabídnout někomu jinýmu)

**Comment by ondrejhlavacek** [comment]
vrtám se v bigquery writeru a vidím

 - [ ] chybějící testy pro všechny `adapters`
 - [ ] `helpers/Constants.js` => `helpers/constants.js`
 - [ ] test pro `helpers/getInitialShowAdvanced.js` (je to blbost, ale je tam tolik těch double `!!` a ORů, že bych to asi nechtěl nějak zásadněji upravovat)
 - [ ] rozházet `parseParameters` a `createConfigParameters` do samostatnejch souborů a přidat testy

(budu updatovat post s dalšíma nálezama)

**Comment by kacurez** [comment]
- ad `constants/Constants` to by sme si mali ujasnit, napr pod `modules/configurations` zlozkou vidim 3 z 4 constants modulov s velkym pociatocnym pismenom. Vzbytku ui je to odhadom 80% ako `Constants`
- zbytok jasny

**Comment by ondrejhlavacek** [comment]
@kacurez dobrá poznámka, vyhodit!

**Comment by ondrejhlavacek** [comment]
když dojdu na detail row writeru a tabulka neexistuje, tak to hodí error

![image](https://user-images.githubusercontent.com/497675/42261314-1bbdedee-7f68-11e8-8280-9d9032114fb6.png)

**Comment by kacurez** [comment]
aha ja som pocital ze tabulka bude vzdy existovat ale vlastne nemusi, teraz ako to fixnut - stale zobrazit nakonfigurovane stlpce + niekde alert ze tabulka neexistuje(asi v pravom stlpci table preview).

**Comment by ondrejhlavacek** [comment]
jj, zobrazit zkonfigurované sloupce. na alert bych se zatím vybodl? nemáme ho ani jinde...

**Comment by ondrejhlavacek** [comment]
v listu ti to může ukázat, že tabulka neexistuje, v detailu by mohl bejt taky link na storage tabulku, tam by se to ohandlovalo. v preview by teda taky vlastně mělo bejt napsaný, že tabulka neexistuje.

**Comment by kacurez** [comment]
jasne bez alertu a poriesi sa to cez table/data preview

**Comment by ondrejhlavacek** [comment]
první runda komentářů, teď k UI, ke kódu se dostanu později

![image](https://user-images.githubusercontent.com/497675/42263821-674e0f8a-7f6f-11e8-9cdd-2981c76dba15.png)

![image](https://user-images.githubusercontent.com/497675/42264343-aa926290-7f70-11e8-8ec4-78006f3bc7d9.png)

- v detailu chybí `StorageApiLinkEx` na cílovou tabulku (tím se vyřeší neexistence tabulky, ta komponenta by to měla sama o sobě nějak signalizovat)
- trochu mi to nesedí vizuálně, nedokážu teď říct jak, ale zkusím popsat, co bych zkusil, jak se to bude tvářit
   1) nepoužívat malý inputy, ty jsem chvíli používal, ale vypadaj blbě, navíc ne všechny inputy to umí (react-select)
   2) mezi inputama mezeru, ať nejsou nalepený na sebe, místa je tam dost
   3) zarovnat všechny buňky nahoru - aby vedla jasná linka od názvu sloupce, přes jeho první input až po content preview (http://take.ms/ZvK4l), pomůže to v orientaci (možná to bude vypadat blbě?)
   4) zarovnat buňky a jejich hlavičky doleva (kromě content preview, to by mohlo bejt vpravo?), zkusil bych to včetně labelů inputů
   5) sekce nejsou od sebe nějak vizuálně oddělený
   6) Load Type má takový modrý pozadí? zdá se mi to?
   7) `[ ] Show Identifiers` v hlavičce tabulky vypadá divně, ještě jak je to zarovnaný na střed. nevím jak to udělat jinak, hrozně se mi líbí nový `Show More`, ale nic takovýho tam nenarvem. určitě bych to vyhodil ven z hlavičky sloupce a posunul to na úroveň celý tabulky
   8) nešlo by nějak udělat sloupec s preview ještě užší (třeba bez hlavičky sloupce, nebo s ikonkou místo textu?), ideálně fixní šířka?
   9) nešlo by udělat sloupec s názvem sloupce fixně širokej, abychom věděli, že pro sloupec preferences vždycky bude dostatek místa (když je dlouhej název sloupce, dost se zúží)

**Comment by kacurez** [comment]
j +- suhlas, ale mohol by si ten komentar pls hodit sem? https://github.com/keboola/kbc-ui/issues/1671
tyka sa to vlastne len gooddata writer ui tak nech sa to nemiesa s obecnym config rows :)

**Comment by ondrejhlavacek** [comment]
no něco se týká i obecných věcí, třeba ten Load Type s modrým pozadím, show identifiers, zarovnání buňek atd, ne?

**Comment by ondrejhlavacek** [comment]
už vím, co mi přišlo tak divný, ten form není horizontal. zkusím některý věci pořešit v bigquery writeru (aniž bych zasahoval do config rows ui) a uvidíš, jak to bude vypadat

**Comment by kacurez** [comment]
> no něco se týká i obecných věcí, třeba ten Load Type s modrým pozadím, show identifiers, zarovnání buňek atd, ne?

Berem to tak ze kod je pod `gooddata writer v3` zlozkou a vychadzam z toho designu specifickeho pre gooddata writer. Nebral som to ze by sa to potom pouzilo aj na ostatne ui, ale asi moze. Load type je redesign stareho gd writeru("legacy design"), imo by sa tam hodilo nieco ako maju transformace v input mappingu (changed in last)

> ad modry load type

Ja to modre nevidim :) pouziva sa tam collapsible section tj napr to iste ako u credentials s3 extraktoru.

> ad stylovanie

S form(inputs/select) v tabulke columns editoru som docela bojoval. Ten layout mi vysiel ako najlepsi kompromis. Suhlasim stym co pises ale asi to bude chciet hodne custom stylovania. Ak sa ti to podari vylepsit v bigquery wr tak super, rad to potom prekopcim do gd writeru.

**Comment by ondrejhlavacek** [comment]
přidal jsem novou položku: helper pro testy, *.spec.js se furt dokola kopírují

**Comment by ondrejhlavacek** [comment]
naming konvence jsem navrhnul v https://github.com/keboola/kbc-ui/pull/2548 a zbytek věcí bych tady nechal bejt, nikoho to zatím netrápí, uzavřel bych to a eventuelně se k tomu vrátil později. asi bych jen doklepl toto - https://github.com/keboola/kbc-ui/issues/3283
