### ISSUE TITLE
uneven select input height

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1704]
![image](https://user-images.githubusercontent.com/497675/40365447-dd5b686a-5dd4-11e8-95b4-4d078e6828e6.png)

**Comment by janmichek** [comment]
Toho jsem si vsimnul hned pri prvnim pouziti kbc .]
Samotna zmena je na par radku, ale zkontrolovat to nebude easy.
Registruju to a pocitam s tim v ramci sjednocovani formularovych prvku. Zatim na to ani nemam issue

**Comment by natocTo** [comment]
@janmichek nezavírali jsme včera něco podobného? Jedu po labelu bug, a toto mi přijde, že je podobné co včera. Díky za prověření.

**Comment by janmichek** [comment]
jo, bylo to vyreseny tady v tom PR https://github.com/keboola/indigo-ui/pull/206
