### ISSUE TITLE
opening input mapping modal error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1705]
```
warning.js:45 Warning: 
Failed propType: Required prop `value` was not specified in `Constructor`. 
Check the render method of `InputMappingRowRedshiftEditor`.
```

http://take.ms/PdamQ

i ve snowflake a docker transformacích. udělá to jen jednou, pak je potřeba reloadovat stránku

**Comment by ujovlado** [comment]
Toto je problem `SapiTableSelector`, pretoze ked nemas input mapping (vytvaras novy), tak sa tam posielam `Map()` no a `get('source')` vracia myslim `undefined`. Fixnem to tym, ze tam poslem prazdny string. Je to minor vec.

**Comment by ujovlado** [comment]
No a `SapiTableSelector` ma prop `value` required.
