### ISSUE TITLE
move "+ New table" button next to search bar

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1709]
- plati pre vsetky config rows ui
- sucasny stav:

![image](https://user-images.githubusercontent.com/1412120/40368545-5c245bfa-5ddc-11e8-8d6e-32ac44dc5dde.png)

- jackov navrh:

![image](https://user-images.githubusercontent.com/1412120/40368498-40414cea-5ddc-11e8-8749-0c1a4d3196dd.png)

**Comment by janmichek** [comment]
Ok, cool. Zkusme to. Kdybys nevedel jak stylovat dej vedet. Je to nova vec, jsem zvedav, jak to bude vypadat.

**Comment by janmichek** [comment]
@ondrejhlavacek jj mas to tam

**Comment by ondrejhlavacek** [comment]
@janmichek 

zobrazuje se mi to takhle

![image](https://user-images.githubusercontent.com/497675/40725439-bc75d3ba-6423-11e8-993a-7849fbb41a8e.png)
