### ISSUE TITLE
job detail params styl

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#171]
Vyzera to nejak divne:
https://www.evernote.com/l/ABzMc2iwnDBBq4ArhBszveW3TLBwClRD4rEB/image.png

**Comment by Halama** [comment]
@JakubMatejka dělá to mirovi protože má nějak obskurně nastavený mac. Každopádně pokud se odstraní tahle direktiva z kbc-bootstrap https://github.com/keboola/kbc-bootstrap/blob/4b60846e243eb3e686e7dc2b067294eb45aff7e3/less/panels.less#L72 tak to funguje. Nejspíš si měl ale nějaký důvod pro to přidání toho `overflow: scroll;`

Jinak je to General nastavení v OSX a sekce Show scroll bars 
![image](https://cloud.githubusercontent.com/assets/903531/8206739/7f16bbd4-14fc-11e5-8866-ed635e2caa81.png)

Mě to dělá na always, mirovi na tu první variantu.

**Comment by JakubMatejka** [comment]
Ach jo, předpokládám že na Windowsech to bude taky všude. Dával jsem to tam kvůli tomu když jsou parameters n. result u jobu moc dlouhý aby nepřetíkaly stránku. Původně to bylo takto:
![development_-_jobs__](https://cloud.githubusercontent.com/assets/215660/8207003/8d9483d8-14fe-11e5-9376-18ddf943de6a.png)

Ale asi to `overflow:scroll` teda zruším a dám tam `overflow:hidden`. Stejně takový nějaký dlouhý hashe nikdo číst nebude(?)

**Comment by Halama** [comment]
@JakubMatejka Tohle je asi to samy. Dělá to u Giulliana na windowsech.
![image](https://cloud.githubusercontent.com/assets/903531/8281738/325f241e-18eb-11e5-979d-5ab39e3bf624.png)

Asi tam dej teda to `overflow:hidden`
