### ISSUE TITLE
Input automapping UI

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1719]
Zadani vzniklo tady https://keboola.slack.com/archives/C0LM9SK6K/p1527078116000382

Vetsina uzivatelu chce automapping + moznost si nejaky datovy typ editovat.
Nedefinovany datatyp = default = VARCHAR.

Navrhujeme nasledujici user flow -> otevru IM modal -> vyberu tabulku -> otevru Show Details -> Nacte se mi tabulka nazvu sloupcu, ktera se hned provede automapping -> sloupce bez metadat budou VARCHAR -> v tabulce mam i moznost editovat datovy typ

Pripadne muzeme vytvorit i dalsi prototypy ovladani.

**Comment by janmichek** [comment]
https://github.com/keboola/kbc-ui/pull/1676#issuecomment-391381437

**Comment by pivnicek** [comment]
parent issue #1677

**Comment by jancermak** [comment]
Poznamka pro me: Nakreslit Marcovi (viz nase premitani v pičrůmu)

**Comment by pivnicek** [comment]
@jancermak zatim to vypada tahkle
![image 15](https://user-images.githubusercontent.com/569139/40725222-2a982830-6423-11e8-9fea-e658f4ee1abd.png)

**Comment by jancermak** [comment]
@pivnicek , @janmichek  — navrh upravy
![1719 input automapping ui copy](https://user-images.githubusercontent.com/1826442/41650755-1b75c1fc-747f-11e8-855b-58c7b28a4abe.png)

**Comment by janmichek** [comment]
I am cool with the visual sketch. Only thing that needs to be solved on my side is to make modal scrollable, because there may be long list of columns. @pivnicek let us now if you have any suggestions, or approve it to implementation

**Comment by janmichek** [comment]
That 'Data types' section is ment to be visible when you click 'Show Details', or should be visible regardless of Show Detail section?

**Comment by janmichek** [comment]
Also let us know about some edge cases if there are any, eg: empty states, exceptions, warnings, ...

**Comment by pivnicek** [comment]
@janmichek 

1) I've tried it with a table with ~ 30 columns and the current behaviour is that the modal scrolls (without scrollbar) over the background which I think is ok.
2) The datatypes section remains behind the `Show Details` like it does currently.
3) There may be some exceptions etc... (if an invalid length is given for example)

@jancermak Diky!  libi si mi to.  jedine vec je ze jeste ten label pro `empty values` je treba trochu dlouhe.  premyslim se na nejake jine label.

**Comment by jancermak** [comment]
@pivnicek @janmichek 
viz. predchozi — some idea about "convert empty values to null" — show this sentens only on hover...
![1719 input automapping ui copy 2](https://user-images.githubusercontent.com/1826442/42868607-1230661a-8a73-11e8-9f7e-cc956a0dbe86.png)

**Comment by pivnicek** [comment]
@jancermak jo, nebo co treba na tooltip?  (and keep the header of course at the top)

**Comment by jancermak** [comment]
@pivnicek  if we can fix table header - its not neccessary  to show text on row hover. (it's nice to have because we have on the right side space)
Tooltip on checkbox is possible.

**Comment by janmichek** [comment]
Hover mi pripada jako dobry koncept. Neni to tak vizualne tezky, zaroven to vidis, kdyz to opravdu hledas

**Comment by janmichek** [comment]
Do fixed headeru bych se ted nepoustel. Uzivatelsky je to samozrejme super, ale je tezky to odladit a musi se to promyslet. Potom je to tezko rozsiritelny.

**Comment by jancermak** [comment]
OK lets do this way
![image](https://user-images.githubusercontent.com/1826442/42871838-9870c848-8a7b-11e8-9ed7-69234adc30fb.png)

**Comment by ujovlado** [comment]
Fixed in #1676
