### ISSUE TITLE
Replace keboola.svg icon by component from indigo-ui

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1720]
Related to: #1660 

Malo by to uz ist v pohode takto:

```js
import { Icon } from '@keboola/indigo-ui';
...
<Icon.Keboola />

```
cc @janmichek

**Comment by janmichek** [comment]
Bomba, dik. vyzkousim

**Comment by janmichek** [comment]
dup https://github.com/keboola/indigo-ui/issues/172

**Comment by janmichek** [comment]
Pripraveno v PR, funguje skvele.
Poznatek z implementace: bude potreba poresit sizing.
Zatim presne nevim jak to udelat - navrhuju zacit replpacovat v kbc ikony za icon set a ono se ukaze, jaky zpusob vyhovuje. Zkusim k tomu neco nacist. Vytvorim si na to issue.
