### ISSUE TITLE
Use ComponentName component for displaying component name (and type)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1723]

**Comment by ujovlado** [comment]
@janmichek suvisi to spolu len okrajovo - v ramci tohto issue som chcel depreacted komponentam pridat suffix ` (deprecated)` (tak ako to bolo povodne ale simulovane cez component name). Potom sme sa ale dohodli, ze to netreba kedze je na to badge.

**Comment by janmichek** [comment]
Muzu pro to neco udelat, nebo ne?
