### ISSUE TITLE
Badges ComponentBadge cisteji

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1736]
- ComponentBadge cisteji
- logika renderovani - rozdeli na 2 komponenty -pro detail a Novou komponentu ( zrejmne i deail konfiguraci https://github.com/keboola/kbc-ui/issues/1735)
- odstrabit css hack https://github.com/keboola/kbc-ui/blob/9ac18ef77f661f2c0ad7505369a6227be01d197d/src/scripts/modules/components/react/components/NewComponentSelection.less#L11
https://github.com/keboola/kbc-ui/pull/1660#issuecomment-391664625

**Comment by janmichek** [comment]
https://github.com/keboola/kbc-ui/issues/1464#issuecomment-392465046

**Comment by ujovlado** [comment]
Fixed in #1741
