### ISSUE TITLE
handle weird configurations gracefully

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1738]
https://connection.keboola.com/admin/projects/395/extractors/docker-config-encrypt-verify
config created by api, but the UI should not break completely

![image](https://user-images.githubusercontent.com/4319320/40647913-65fdc570-632d-11e8-93f5-e14c4afb6453.png)

**Comment by ujovlado** [comment]
@odinuv what about "generic docker ui" flag? Shouldn't be set? The only flag set to this component is `legacyHasRun`

**Comment by odinuv** [comment]
no idea, but this is list of configurations, not detail

**Comment by ujovlado** [comment]
Ok, I'll try to set that flag to component

**Comment by ujovlado** [comment]
It helped. I think we can close this. Or not? Would you like to fix that view even if `genericDockerUI` is not set?

**Comment by odinuv** [comment]
i still think it should not break the *list* of configurations, depends how many components are there without that flag - do it as you wish :)

**Comment by ujovlado** [comment]
tvl, tak ono to vyzera, ze to suvisi s tymto: https://github.com/keboola/developer-portal/issues/204

pretoze vyhodil som ten `genericDockerUI` a uz to rozbite nie je :-D (ale tu komponentu som predtym zmenil z `other` na `application` ... no uz to neviem vratit s5, api to nepodporuje :-D
