### ISSUE TITLE
URL v grafech?

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#174]
@martin hm! Něco podobnýho by se hodilo v grafech. Tam jsou url taky zahardcodovany a navíc se teď budou migrovat

O jaký grafy se jedná myslel jsem že url se generují na frontendu? Pokud to dělá backend tak to vyřešíme stejně jako u toho orchestrátoru.

**Comment by Halama** [comment]
Aha už to vidím
![image](https://cloud.githubusercontent.com/assets/903531/8226957/7a41497e-15a3-11e5-884a-7653c4f9e156.png)

**Comment by Halama** [comment]
Graf writeru
![image](https://cloud.githubusercontent.com/assets/903531/8226974/9e762bb6-15a3-11e5-9560-83a9dadb7978.png)

**Comment by Halama** [comment]
Graf tabulky
![image](https://cloud.githubusercontent.com/assets/903531/8227034/07671fa4-15a4-11e5-8b71-bef8588966e8.png)

**Comment by Halama** [comment]
Ty URL by se ale klidně mohli skládat na frontendu ne? na základe type a node?

**Comment by ondrejhlavacek** [comment]
Teď už jo, ve starým UI to moc nešlo (neznal jsem id projektu).

**Comment by ondrejhlavacek** [comment]
Zase by bylo potřeba, aby si to drželo zpětnou kompatibilitu než se starý UI vypne.

**Comment by Halama** [comment]
tak ze starým ui je to funkční a pokud se budou generovat url na frontendu tak se na tom nic nezmění. Jenom se bojím že např. u transformací bude chybět informace o bucketu,

**Comment by ondrejhlavacek** [comment]
Ty url přicházejí generovaný z backendu, pro jejich sestavení spousta věcí
chybí, ale ty muzu poslat extra, to je docela dobrej nápad

**Comment by Halama** [comment]
Mít tam nějakou hashmapu s těmi proměnnými které by pak na frontendu člověk jenom poslal to template třeba jako `/admin/projects-new/&&projectId&&/orchestrations#/jobs/&&jobId&&"` by bylo super.
Tenhle formát jsem koukám zvolil blbě, to nepodporuje underscore template, to bych ještě upravil.

**Comment by ondrejhlavacek** [comment]
Tak možná by stačilo hodit to do parametrů Link

**Comment by Halama** [comment]
to by nefungovalo pro linky ven na starý appky, ikdyž možná takový vlastně žádný nejsou

**Comment by ondrejhlavacek** [comment]
V grafu ne

**Comment by Halama** [comment]
pošleš mi tam teda ty data?

**Comment by ondrejhlavacek** [comment]
Ha, ja to v issues na mě na do aktuálního milestonu nenašel! Můžeš mi to
přiřadit prosím?

**Comment by ondrejhlavacek** [comment]
@Halama takhle nějak? https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/transformations/react/pages/transformation-graph/Graph.coffee#L28

(zatím to mockuju z dat, co z backendu dodávám, pak backend, minimálně pro transformace, upravím).

Ale nevím jak pro storage - přes template tady - https://github.com/keboola/kbc-ui/blob/master/index.html#L121 ?

A ve starý storage appce, co je embeddnutá do novýho UI (netuším moc jak), už vůbec nevím.

**Comment by Halama** [comment]
@ondrejhlavacek ja myslel ze to prave posle backend, tohle hackovani idcek v ui se mi moc nelibi

**Comment by Halama** [comment]
jsem myslel ze se prvni upravi backend a pak uicka. Do te storage ty template dodam stejne jako do noveho kde budou potreba.

**Comment by ondrejhlavacek** [comment]
@Halama jak to myslíš? Píšu, že je to mock, abych si ujasnit, jak to má bejt a co potrebuju za data. Nevím jak s tou konzolí...

**Comment by Halama** [comment]
no data jsou potreba takový aby sel sestavit ten link

**Comment by Halama** [comment]
takze u transformace se objevi `bucketId` a `transformationId` a u writeru asi `config` a `table`

**Comment by ondrejhlavacek** [comment]
No já právě nevím, jak ho sestavit (konzole) - v routeru jsem to nenašel.

**Comment by ondrejhlavacek** [comment]
No tohle je mi jasný :-)

**Comment by Halama** [comment]
nerozumim, jde mi jenom o to aby to poslal backend v ui to vyresim

**Comment by Halama** [comment]
"No já právě nevím, jak ho sestavit (konzole) - v routeru jsem to nenašel." myslis jak sestavit link v sapi konzoli?

**Comment by ondrejhlavacek** [comment]
Ok, pro Storage teda jen id tabulky?

**Comment by Halama** [comment]
jo

**Comment by ondrejhlavacek** [comment]
Data jsou vidět tady

![screen shot 2015-06-23 at 17 44 47](https://cloud.githubusercontent.com/assets/497675/8320490/90fc02ae-19d0-11e5-8415-5d402465f4e6.png)

a používá se to takto

https://github.com/keboola/kbc-ui/blob/f9dda12ad1c541f9757a228a4faaa8137fc73c08/src/scripts/modules/transformations/react/pages/transformation-graph/Graph.coffee#L29

V tomhle grafu chybí odkazy na storage, pak jsou ještě grafy ve writeru a v konzoli (konzole už data dostává, writer se bude muset modifikovat)

**Comment by Halama** [comment]
Transformační graf hotovej, u writeru čekám na backend, jdu na konzoli.

**Comment by Halama** [comment]
Uff tak dostat do do konzole byl slušnej porod :) Ale je to tam! Funguje to tak že pro nový UI tam KBC injecte url templaty a konzole je použije. Pokud konzole nedostane ty templaty tak použije linky které dostane z backendu. 

Přijde mi ale že to nezobrazuje writery, můžeš to nějak ověřit?

**Comment by Halama** [comment]
Zbývá to teda dodat do grafu writeru.
