### ISSUE TITLE
transformace - chyby při nastavení input mapping

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#176]
https://errorception.com/projects/54e3526a24f538015600008c/errors/5582c8ebfef012911baa3439

**Comment by Halama** [comment]
dělá při přidávání sloupce

**Comment by Halama** [comment]
Konfigurační api nevrací columns input mappingu i když jsou nastavené

**Comment by ondrejhlavacek** [comment]
Řekl bych, že vyřešeno přes to cachování.

**Comment by Halama** [comment]
dělá pořád, fixnu

**Comment by ondrejhlavacek** [comment]
Tak mi to nech, jenom mi zkus prosím popsat, kde to dělá, zkoušel jsem to a
nepovedlo se mi to

**Comment by Halama** [comment]
dělá to v moment kdy nastavím index input mappingu a pak chci nastavit sloupce, tam to chcípne na
![image](https://cloud.githubusercontent.com/assets/903531/8249312/14b4a2f6-1669-11e5-9fe4-4dfa03f7699f.png)

**Comment by Halama** [comment]
to klidně fixnu, to bude nějaká blbost

**Comment by ondrejhlavacek** [comment]
Aha! Cajk, ja myslel že to je chyba backendu :-) ráno fixnu
