### ISSUE TITLE
Show that OM is being incremental

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1765]
cause there is no way to tell unless you click twice:

![image](https://user-images.githubusercontent.com/4319320/40938020-d186e0d4-6840-11e8-8f9e-5b2739caa685.png)

**Comment by odinuv** [comment]
Podobna vec s filtrem https://keboola.zendesk.com/agent/tickets/8582 na writeru
Podle me bysme meli mit univerzalni ikonky pro inkrementalni a filtrovany load ven/dovnitr, aby clovek vedel, ze se mu tam tabulka nemusi nahrat cela.

**Comment by janmichek** [comment]
Ok, souhlas. 
Zatim jsem na to nenasel vhodnou ikonu mezi nasim packem nebo font awesome. Nebo si klidne neco necham doporucit.
Pripadne bych teda poprosil @jancermak at nam takovou svg ikonu pripravi.
Moje predstava je jednoducha ikona schodu, ale v kreativite se meze nekladou .]

**Comment by janmichek** [comment]
Zatim je jednoduchy reseni pridelat vedle ostatnich labelu, label 'incremental'. Domnivame se, ze k ty ikone by byl stejne potreba tooltip o co jde.

**Comment by odinuv** [comment]
tak treba tooltip `Incremental load`, kdybys tam chtel neco fakt delsiho tak https://help.keboola.com/storage/tables/#incremental-loading

**Comment by janmichek** [comment]
Myslim ze 'Incremental' je dostatecne vystizny, neni nutny to natahovat .] Budu rad kdyz se to tam vejde i tak, potrebuju to ozkouset na realnym obsahu.

**Comment by janmichek** [comment]
Screeny s pouzitim v realnym obsahu. Takhle je to simple reseni.

![image](https://user-images.githubusercontent.com/15363559/43600965-5840df02-968c-11e8-8b26-61ba224b1e15.png)

![image](https://user-images.githubusercontent.com/15363559/43600996-6af5cafe-968c-11e8-8c77-f3b55d10f070.png)

**Comment by ujovlado** [comment]
len pre info ... kde sa da vidiet tak prva cast, kde to zobrazuje aj backend? nejako sa mi to nedari naklikat

**Comment by ujovlado** [comment]
ok, mam to
