### ISSUE TITLE
Snowflake writer deleted columns

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1774]
- configure snowflake driver
- delete column from the source table
- run the writer configuration (fails as expected -> good)
- edit the configuration, now it doesn't show the deleted columns (the entire table needs te be removed and added)

the UI should show union of table columns and configured columns

**Comment by kacurez** [comment]
hmm presne toto sme nedavno fixovali, pozriem sa nato

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/pull/1611

**Comment by kacurez** [comment]
@odinuv nedari sa mi to podla toho postupu nasimulovat. Zmazane stlpce sa presunu uplne na spodok tabulky, mozno si ich klient nevsimol.

**Comment by odinuv** [comment]
tak to je divny, zkousel jsem to a taky me to delalo, jdu to vyzkouset jeste jednou

**Comment by odinuv** [comment]
hmm, je to fakt tak, asi jsem musel mit nejakej vypadek :/
