### ISSUE TITLE
Rewrite from coffee to js/jsx

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1775]
Check progress here: https://ujovlado.github.io/kbc-ui-coffee (updated daily).

The best way how to rewrite coffee to jsx w/o pain: https://500.keboola.com/the-worry-free-way-to-convert-coffeescript-to-jsx-ad5fe3b1e8ba. Basically you write test (snapshot) with coffee file, then create new js/jsx file with coffee converted to jsx and tests should still pass.

Tips:

- don't forget to check imports (if coffee file is importing default export from js/jsx, it has to be specified).
- last line in coffee file is "returned", make sure you remove returns when they're not necessary 
- If component is very simple it can rewritten to functional component.
- do not refactor too much, only rewrite (if something is very wrong, file an issue)

Further reading:

- https://github.com/decaffeinate/decaffeinate (convert to js from command line)
- https://blog.bugsnag.com/converting-a-large-react-codebase-from-coffeescript-to-es6/ (if we try to automate, this can help)

Test / Mock / Snapshot examples:
- https://github.com/keboola/kbc-ui/commit/6a8f5b75ebde3ecbd623c8faf3f09312a9ac8a4f
- comments in this issue: https://github.com/keboola/kbc-ui/pull/1991

### Rewrites by modules (part 1):

- [x] 54 src/scripts/modules/orchestrations
- [x] 23 src/scripts/modules/gooddata-writer (:warning: robit ako posledne)
- [x] 5 src/scripts/modules/provisioning
- [x] 13 src/scripts/modules/jobs
- [x] 1 src/scripts/modules/app-geneea-nlp-analysis
- [x] 17 src/scripts/modules/tde-exporter
- [x] 1 src/scripts/modules/geneea-nlp-analysis-v2 
- [x] 2 src/scripts/modules/ex-google-bigquery 
- [x] 2 src/scripts/modules/oauth-v2 
- [x] 5 src/scripts/modules/wr-dropbox - for deletion #2023 
- [x] 1 src/scripts/modules/ex-mongodb 
- [x] 1 src/scripts/modules/google-utils 
- [x] 8 src/scripts/modules/wr-google-drive-old (will be deleted soon - we'll see)

### Rewrites of common components (part 2):

- [x] 57 src/scripts/modules/components

### Transformations (part 3):

- [x] 1 src/scripts/modules/transformations
- [x] 2 src/scripts/modules/transformations/stores
- [x] 1 src/scripts/modules/transformations/react/modals
- [x] 10 src/scripts/modules/transformations/react/components/mapping/input (rozdelit min. na 2 PR)
- [x] 4 src/scripts/modules/transformations/react/components/mapping
- [x] 16 src/scripts/modules/transformations/react/components (rozdelit min. na 3 PR)
- [x] 6 src/scripts/modules/transformations/react/pages/transformation-detail
- [x] 1 src/scripts/modules/transformations/react/pages/transformation-bucket
- [x] 3 src/scripts/modules/transformations/react/pages/transformations-index 
- [x] 3 src/scripts/modules/transformations/react/pages/transformation-graph

### Database Writers (part 4):

~:warning: treba zistit v akom stave je ten novy wr-db-geberic~ nakoniec sme sa dohodli, ze to prepiseme bez ohladu na stav

- [x] 4 src/scripts/modules/wr-db/templates/
- [x] 4 src/scripts/modules/wr-db/
- [x] 1 src/scripts/modules/wr-db/react/components
- [x] 5 src/scripts/modules/wr-db/react/pages/table
- [x] 2 src/scripts/modules/wr-db/react/pages/credentials
- [x] 2 src/scripts/modules/wr-db/react/pages/index

**Comment by ujovlado** [comment]
Priebezne budem doplnat, ked narazim na dobrych kandidatov, 4 ci 5 z nich uz dlhsie caka tu: https://github.com/keboola/kbc-ui/tree/vlado-refactor-few-components-to-jsx-1

**Comment by kacurez** [comment]
"pridavam" sa do issue :)

imho nie vzdy sa daju napisat snapshot testy aby 100% pokryli render. Zvlast u komponent s komplexnymi datovymi strukturami v props. 

Niektore komponenty mozu ist rovno do indigo-ui nie? Niektore sa deprekuju(napr prepis gooddata writer ui)

**Comment by ujovlado** [comment]
> imho nie vzdy sa daju napisat snapshot testy aby 100% pokryli render. Zvlast u komponent s komplexnymi datovymi strukturami v props.

no prave ked je to vsetko robene cez props tak je to easy a malo by sa to dat napisat. Skor sa obavam, ze niekedy je dost zlozite namockovat state.

> Niektore komponenty mozu ist rovno do indigo-ui nie? Niektore sa deprekuju(napr prepis gooddata writer ui)

Jasne, nieco by asi slo ... ked take komponenty najdeme, mozeme to prejst. Uz ked budu prepisane do jsx, prehodit je to brnkacka.

**Comment by ujovlado** [comment]
Este k tomu state. Neviem ako sa da otestovat komponenta, ktora ma zmenit render po zmene state. Tam som to myslim robil tak, ze som napisat viac testov a obabral som to tym, ze vzdy bol iny initial state.

**Comment by kacurez** [comment]
> Skor sa obavam, ze niekedy je dost zlozite namockovat state.

jj to som mal na mysli, ze neni lahke namockovat state, tiez sa v tom mozes pomylit a vo vyslednom rendri si toho nemusis vsimnut

**Comment by ujovlado** [comment]
^ Pripravene dalsie 3 casti

**Comment by ujovlado** [comment]
V #1912 som skusil vykopnut dalsie podporne nastroje ktore urychlia prepis ... kludne to ked tak skuste (cc @kacurez @ondrejhlavacek ) ... navod: https://github.com/keboola/kbc-ui/blob/master/CODEMOD.md

**Comment by ujovlado** [comment]
Bavili sme sa s Tomasom, ze by sme to skusili pustit na vsetky zvysne .coffee a uvidi sa.

**Comment by ujovlado** [comment]
Pocet .coffee files podla modulov
```
     54 src/scripts/modules/orchestrations
     23 src/scripts/modules/gooddata-writer
      5 src/scripts/modules/provisioning
     13 src/scripts/modules/jobs
      1 src/scripts/modules/app-geneea-nlp-analysis
     17 src/scripts/modules/tde-exporter
      1 src/scripts/modules/geneea-nlp-analysis-v2
     57 src/scripts/modules/components
      2 src/scripts/modules/ex-google-bigquery
     47 src/scripts/modules/transformations
      2 src/scripts/modules/oauth-v2
      5 src/scripts/modules/wr-dropbox
     18 src/scripts/modules/wr-db
      1 src/scripts/modules/ex-mongodb
      1 src/scripts/modules/google-utils
      8 src/scripts/modules/wr-google-drive-old
```

**Comment by ujovlado** [comment]
^ skopcim to do popisu issue a pridam kto to riesi

**Comment by natocTo** [comment]
Mrknu na *src/scripts/modules/google-utils* pokud to není deprecated.

**Comment by ujovlado** [comment]
@natocTo potom kludne ten provisioning, nie je tam toho moc, malo by to ist lahko.

**Comment by ujovlado** [comment]
@natocTo pridal/rozpisal som tam dalsie 2 casti. Najvacsi zmysel asi dava pustit sa do `wr-db` (cast 4.). Po prepise tam budu vlastne ready dalsie issues (zbavenie sa statickych stavov a pod.).

**Comment by ujovlado** [comment]
Po wr-db by asi davalo zmysel pustit sa do transformacii. Tam ti s tym viem urcite pomoc - je toho kopa. Nasledne orchestracie (este som nerozpisal, tiez viem pomoct).

Uvidime ako to pojde, po tychto troch castiach co spominam (wr-db, transf., orch) budeme mat vlastne takmer polovicu za sebou a mozeme prehodnotit, ci to ideme doklepnut (prepisat aj zvysok) alebo dava vacsi zmysel dat si pauzu.

**Comment by natocTo** [comment]
Dobře, pustím se do *wr-db*.

**Comment by ujovlado** [comment]
Takze `wr-db` uz je komplet js :tada:

**Comment by natocTo** [comment]
Transformations a Orchestrations by mělo být naposíláno. Bylo toho dost, tak je možný, že se někde něco přehlédlo. Kdyžtak doplním až se to zjistí.

Bude se tady nějak pokračovat? Respektive zda se mám pustit do nějakého dalšího modulu nebo mrknout na něco jiného.

**Comment by ujovlado** [comment]
> Bude se tady nějak pokračovat? Respektive zda se mám pustit do nějakého dalšího modulu nebo mrknout na něco jiného.

Toto zalezi trosku aj na tebe ... ci to ideme dorobit alebo chces dat pauzu.

Ale navrhoval by som pockat kym sa dostane do produkcie vsetko co si riesil doteraz a potom pokracoval. Tie reviews nejdu az tak rychlo ako by som chcel, no musime byt pri tom dost opatrni.

Toto je zrovna vec, co neprinasa ziadnu hodnotu pre uzivatela, takze to robim opatrnejsie. Z mojho pohladu je horsie nieco rozbit pri refaktoringu ako pri pridavani novej featury.

**Comment by natocTo** [comment]
OK. Pauzu pak nepotřebuji, ale souhlasím že je dobré počkat na to co je teď.
Já i teď se snažil udělat třeba 3 PR na převod a pak odpo zas hledal jiné chyby nebo opravovat jiné věci.

**Comment by ujovlado** [comment]
Aj `transformations` uz kompletne v js :tada:

**Comment by kacurez** [comment]
@ujovlado @natocTo  skusil by som teraz zbuchat nieco zo https://github.com/keboola/kbc-ui/tree/master/src/scripts/modules/components/stores - konkretne InstalledComponentsStore
je to ok?

**Comment by ujovlado** [comment]
Jasne, cokolvek na co nie je PR, je vhodne. Hlavne to moc v ramci prepisu neprerebaj :)

**Comment by ujovlado** [comment]
Este sem pridam, ako som to zvykol kontrolovat. Skripty predpokladaju, ze idem po zlozkach.

Toto som si pustal na mastri:
```
decaffeinate --loose-includes --loose-default-params --loose-for-expressions --loose-for-of --use-js-modules *.coffee
chown -R 1000:1000 .
find . -maxdepth 1 -type f -name "*.coffee" | awk -F . '{print "mv ."$2".js ."$2".raw.js"}' | sh
jscodeshift -t /code/codemod/transforms/dom-factories-calls-to-calls-with-react-dom-prefix.js *.raw.js
jscodeshift -t /code/react-codemod/transforms/React-DOM-to-react-dom-factories.js *.raw.js
jscodeshift -t /code/react-codemod/transforms/create-element-to-jsx.js *.raw.js
```

Pred prvym spustenim `jscodeshift` som este manualne dopisoval `React.createElement` tam kde bola komponenta pouzita pomocou `React.createFactory`.

Potom som uz len porovnaval "moje" `raw.js` oproti novym `js`.

**Comment by ujovlado** [comment]
To s tym `React.createElement` doplnim do navodu.

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/blob/master/CODEMOD.md#5-make-sure-there-are-no-reactcreatefactory

**Comment by ujovlado** [comment]
Uff, `orchestrations` kompletne v js :1st_place_medal: :tada: :100: :cake:

**Comment by ujovlado** [comment]
```
vlado@yoda:~/workspace/keboola/kbc-ui$ find src/scripts/modules/ -type f -name "*.coffee" | awk -F "/" '{print $1"/"$2"/"$3"/"$4}' | uniq -c
     23 src/scripts/modules/gooddata-writer
     12 src/scripts/modules/jobs
     16 src/scripts/modules/tde-exporter
     57 src/scripts/modules/components
     10 src/scripts/modules/transformations
      8 src/scripts/modules/wr-google-drive-old
```

pozeram, ze v transformaciach tam este nieco ostalo :)

**Comment by ujovlado** [comment]
@natocTo vidim, ze si zacal riesit dalsie ... nedoriazil by si tie transformacie? tam ich ostalo 10 (je to asi na mna, pri tom rozbijani na casti som asi prehliadol folder).

**Comment by natocTo** [comment]
Jo tak taky mrknu.

**Comment by ujovlado** [comment]
Jobs uz je tiez kompletne v .js(x) :bomb: :cake: :fire:

**Comment by ujovlado** [comment]
```
vlado@yoda:~/workspace/keboola/kbc-ui$ find src/scripts/modules/ -type f -name "*.coffee" | awk -F "/" '{print $1"/"$2"/"$3"/"$4}' | uniq -c
     21 src/scripts/modules/gooddata-writer
     16 src/scripts/modules/tde-exporter
     53 src/scripts/modules/components
      8 src/scripts/modules/wr-google-drive-old
```

**Comment by ujovlado** [comment]
```
find src/scripts/modules/ -type f -name "*.coffee" | awk -F "/" '{print $1"/"$2"/"$3"/"$4}' | uniq -c
     21 src/scripts/modules/gooddata-writer
     12 src/scripts/modules/components
      8 src/scripts/modules/wr-google-drive-old
```

**Comment by ujovlado** [comment]
`wr-google-drive-old` spravim, potom si mozeme nejako rozdelit `components`. A nakoniec bude treba spravit aj `gooddata-writer` - dovtedy sa este syncneme.

**Comment by natocTo** [comment]
`components` zítra převedu

**Comment by ujovlado** [comment]
Uz len stary gooddata writer :bomb: 

```
find src/scripts/modules/ -type f -name "*.coffee" | awk -F "/" '{print $1"/"$2"/"$3"/"$4}' | uniq -c
     21 src/scripts/modules/gooddata-writer
```
a rozmyslam, ci to rovno nesplachnem :)

**Comment by ujovlado** [comment]
^ gooddata-writer zbuchnem teda ja.
