### ISSUE TITLE
Component badges - Alpha confusion

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#1776]
Flag `Alpha` s popisem `This extractor is private.` mi přijde dost matoucí.
Mají ho všechny komponenty které nejsou public tzn. listované v seznamu komponent na přidání.
Tím pádem ho mají třeba i deprecated komponenty nebo interní a "privátní" komponenty.

Řešením by mohlo být ho přejmenovat na `Unsupported` - `This extractor is not supported`.
https://keboola.slack.com/archives/C0JHHB3JA/p1528217488000574

**Comment by ujovlado** [comment]
K tomuto mi napadla este jedna vec. Ked je komponenta deprecated, nebudeme zobrazovat, ze je alpha a bude to vyriesene.

Pretoze zvacsa je ten flow takyto:
- private (flag: alpha) :arrow_right:  public :arrow_right:  deprecated + private (flag: deprecated)

**Comment by janmichek** [comment]
Jakym zpusobem to budes implementovat?
vidim 2 moznosti:
- logika v ui - zobrazovaci podminka, zatim tam zadna neni.
- properties na strane dat - zobrazi se badges podle vlastnosti, logika se resi v backendu.

**Comment by odinuv** [comment]
"This extractor is not supported mi evokuje, ze nie je dana komponenta vobec podporovana - t.j. moze sa mi zdat, ze vobec nefunguje" -> vsak presne tak to je

nekomplikoval bych to zavadenim dalsi logiky, to zase bude problem vysvetlit 3rd party vyvojarum, pojdme tomu dat treba lepsi text - badge bude "Unsupported" a tooltip muze byt treba:
- "This component is not recommended for production use"

**Comment by ujovlado** [comment]
Kuknite ked tak nalinkovany PR ... ono to nie je zavadzanie nejake dalsej komplikovanej logiky. Len nezobrazit "alpha", ked je to "deprecated". Mylim, ze to tak aj robime a nemoze sa asi stat, ze je nieco deprecated a zaroven public. (aj v devportali, ked das deprecate, stane sa to public)

Zvolil by som teda kombinaciu. To co robim v tom PR + zmena textu ako navrhuje @odinuv.

**Comment by ujovlado** [comment]
Este k tomu "Unsupported"... to moze teda vyzerat dost sproste, pretoze tam budes mat (pri nasich komponentach) "Support for this extractor is provided by Keboola." a hned pod tym badge "Unsupported" ;)

**Comment by ujovlado** [comment]
Takze ak zmenit ten text, tak este na nieco lepsie asi ... alebo to proste nekomplikujme. A zmenim len "Alpha" na "Private" a bude to 1:1 s API a pokoj.

**Comment by ujovlado** [comment]
Aj tak je to divne, ako sa pise v tomto issue, ze "Alpha" a potom vysvetlenie "Private"

**Comment by ujovlado** [comment]
Upravim ten PR :)

**Comment by odinuv** [comment]
no to private jsme tam nechteli, protoze to evokuje, ze tu komponentu treba nemuze nikdo jinej pouzivat, coz je blbost, ona je proste public. V terminologii Youtube by to bylo "Unlisted". 

Ja si myslim, ze chceme, aby to vypadalo "blbe" protoze, kdyz pouzivas private komponentu tak si musis byt vedom toho, ze tam muzou byt unnananouced bc breaky, ze se to muze kdykoliv vydrbat a pritom u toho vubec nemusi byt nastaveny Beta flag, podle me je to "Unsupported" nejpresnejsi.

**Comment by Halama** [comment]
`private` budou mít až reálné private komponenty které půjdou spouštět jen v projektech pro které budou povolené.

**Comment by ujovlado** [comment]
ale potom to bude ukazovat toto  (ako pisem v https://github.com/keboola/kbc-ui/issues/1776#issuecomment-398330820)

![screenshot_2018-06-19_13-38-58](https://user-images.githubusercontent.com/419849/41595226-53515d34-73c6-11e8-8f4d-fc40280d14b5.png)

**Comment by Halama** [comment]
a proč některé badge jsou textové a některé jen ikonky?

**Comment by odinuv** [comment]
@ujovlado a cemu to vadi? me to prijde uplne v pohode

**Comment by ujovlado** [comment]
no ze v jednom riadku pises o supporte a v druhom, ze je unsupported

**Comment by odinuv** [comment]
vsak, ano napis nam (ne nekomu jinymu), ale taky ti klidne reknem soryjako

**Comment by ujovlado** [comment]
pride mi, ze tam miesame dve veci ... `private` sa pouziva ked je komponenta vo vyvoji ... ale zaroven, ked je deprecated a nema sa zobrazovat. preto som navrhoval nezobrazit unsupported, ked uz je deprecated.

**Comment by ujovlado** [comment]
mozno by sme to este mohli prejst s Hankou

**Comment by odinuv** [comment]
i deprecated komponenta je unsupported

a dobre, tak dejme tomu, ze se to private/unsupported nebude zobrazovat pro deprecated komponenty, potom ti nebude "unsupported" vadit nebo co bys tam dal?

**Comment by janmichek** [comment]
Ted uz asi nedokazu prispet do diskuze. Zacal bych u toho co vse vlastne chceme uzivateli komunikovat a to pak pretavil v badges s popisky :)

**Comment by ujovlado** [comment]
> a dobre, tak dejme tomu, ze se to private/unsupported nebude zobrazovat pro deprecated komponenty, potom ti nebude "unsupported" vadit nebo co bys tam dal?

no v takomto pripadne by tam mohlo ostat to Alpha, pretoze aj ked sa to zobrazi pre nase komponenty coi maju `private`, nebude tam napisany blud supported/unsupported.

mne nevadi, ze sa ten konkretny label vola Unsupported - vadi mi, ze si to protireci s tou dalsou castou.

**Comment by ujovlado** [comment]
Ok, ked uz sa vrtam v badges, rozstrelim este toto.

Namiesto `Alpha - This extractor is private.` tam dam zatial `Experimental - This component is not recommended for production use`.

Ci sa ma/nema zobrazit naraz deprecated + private mozeme poriesit potom. Cielom tohto issue bolo zrusit alpha - je to matuce.
