### ISSUE TITLE
Fix importing blank table

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1781]
mam v azure db prazdnou tabulku kterou bych potreboval dostat do kbc, ale extraktor ji nechce naimportovat 

https://connection.keboola.com/admin/projects/2594/jobs/405092338

https://keboola.zendesk.com/agent/tickets/8611

**Comment by odinuv** [comment]
jak to souvisi s UI?

**Comment by pivnicek** [comment]
I've moved it to here https://github.com/keboola/db-extractor-common/issues/60

Thanks @janmichek
