### ISSUE TITLE
documentation link 

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#1782]
show documentation link also somewhere on the configuration list page

/extractors/keboola.ex-facebook/405165555
has
![image](https://user-images.githubusercontent.com/4319320/41347390-cb029166-6f09-11e8-8de3-65e43c1178e7.png)

/extractors/keboola.ex-facebook has nothing

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C0A5ZK1LY/p1528749916000039

**Comment by ujovlado** [comment]
Shouldn't be enough to add Documentation link to component's "Long Description"?

**Comment by ujovlado** [comment]
Potom mi napada este nieco taketo:

![screenshot_2018-06-18_15-58-36](https://user-images.githubusercontent.com/419849/41540455-9a84b720-7310-11e8-9486-f1840988373a.png)

Ale ak to ideme pridat globalne pre vsetky komponenty, nech to este preiterujeme s @janmichek

**Comment by odinuv** [comment]
v longdescription je to naprd, jednou to bude na zacatku jednou nakonci, jednou jako link, jednou jako "more info" bude to chaoticky a duplikuje to informaci kterou uz mame - v editaci konfigurace se ten odkaz zobrazuje, at se ten stejny zobrazuje i nekde na seznamu konfiguraci

**Comment by odinuv** [comment]
taky se to neukazuje u keboola.ex-youtube i kdyz to ma documentation url nastaveny

![image](https://user-images.githubusercontent.com/4319320/41608352-9dafd000-73e8-11e8-8032-401074c11cd6.png)

**Comment by ujovlado** [comment]
@odinuv to je ale ina issue ... nemiesajme to asi

**Comment by ujovlado** [comment]
este ked som sa nad tym zamyslel, to co navrhujem vyssie je kravina - lepsie je to mat uz v konfiguracii ... na detaile komponenty to imho aj tak nikto necita.

**Comment by kacurez** [comment]
ex-facebook ma dokumentacny link lebo jeho ui je custom tak som to tam dal natvrdo. Inac komponenty. 
U generickych ui ak ma komponenta `configurationSchema` tak sa link nezobrazi:
uz sa to riesilo tu https://github.com/keboola/kbc-ui/issues/1088

**Comment by ujovlado** [comment]
no a k badges este patri toto ... uz som mam rozrobene cca z pred mesiaca, dotiahnem aj to
