### ISSUE TITLE
Show details of OM premanently

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1784]
Vyzobnutý návrh z Marcusova ticketu.
https://keboola.zendesk.com/agent/tickets/8619

would be nice to show all the details (rather than having to "show details" it) in the output mapping.

The only additional details there are, are Primary Key and Incremental. To me, Primary Key should pretty much always be set, and is best practice. Also its a good prompt for the user so that its kind of like "did you remember to set up your primary key?" type of thing.

**Analýza**

Navrhuje úpravu OM, zrusit sekci Show details.
Dodavam, ze vsechny 4 backendy maji pod Show details stejny obsah (tedy Incremental a PK)
Za me tam zas neni tolik obsahu, takze po vizualni strance to ten modal unese xD a vlastne mi to dava smysl.
Ta druha vec co navrhuje (prompt) se mi moc nelibi.

Nechavam k diskuzi, klido to zavreme, jestli je to blbost. @kacurez  @odinuv  @Halama

**Comment by odinuv** [comment]
https://github.com/keboola/kbc-ui/issues/1765

**Comment by kacurez** [comment]
Zamna to je dobry napad, ten obsah sa tam zmesti ako pises :)
ad prompt - on tym mysli ze odstranenim show details to zaroven bude fungovat ako prompt.

**Comment by ujovlado** [comment]
Toto mozeme, myslim, rovno spravit. Ak tam je toho obsahu malo a usetri to jeden klik, som za. Spravim to.

To co spomina odin v #1765 je imho na dlhsie a treba to trosku prejst.
