### ISSUE TITLE
Output mapping: delete rows gets reset after unchecking incremental

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1797]
Vím, že delete rows option nedává smysl, pokud probíhá full load do výstupní tabulky, ale často někde máte incremental, jednorázově potřebujete přehrát všechna data a pak to na incremental vrátit. A v tu chvíli přijdete o nastavené delete rows. Zejména pokud dělá na projektu víc lidí, často si toho někde nemusí všimnout. Nemohly by tam předvolené možnosti zůstat?
https://monosnap.com/file/82H9d95JorwFkqiKRp3uVDxL1BdaMw
Je to podobné, jako když máte nastavený filtr na sloupec a jakmile začnete vybírat sloupce, co se mají do TR nahrát, nebo ten konkrétní odstraníte, filtr zmizí. I když zmizet nemá.

**Comment by ujovlado** [comment]
Rozdelme to na 2 casti:

> Vím, že delete rows option nedává smysl, pokud probíhá full load do výstupní tabulky, ale často někde máte incremental, jednorázově potřebujete přehrát všechna data a pak to na incremental vrátit. A v tu chvíli přijdete o nastavené delete rows. Zejména pokud dělá na projektu víc lidí, často si toho někde nemusí všimnout. Nemohly by tam předvolené možnosti zůstat?
> https://monosnap.com/file/82H9d95JorwFkqiKRp3uVDxL1BdaMw

toto sa mi zda trosku blbost ... potom v UI bude zobrazene nieco co by nesuhlasilo s tym, co je v konfiguracii

> Je to podobné, jako když máte nastavený filtr na sloupec a jakmile začnete vybírat sloupce, co se mají do TR nahrát, nebo ten konkrétní odstraníte, filtr zmizí. I když zmizet nemá.

Toto je ale spravne chovanie.... mam vybraty  data filter na stlpec "1" ... hore v Columns je nastavene "All columns will be imported". Akonahle vyberem do Columns stlpec "2", tak uz neplati, ze budu importovane vsetky, ale len "2", t.j. ten filter na "1" nedava zmysel. 

Ak si vsak vyberes do Columns najprv stlpec "1", tak ti ho nezrusi. 

Figel je v tom, ze to tam nemozeme nechat, lebo nevieme, ake stlpce si ides vybrat a keby sme to nezmazali, tak su nastavene filtre na stlpce, ktore sa neimportuju. ;)

**Comment by Matejkys** [comment]
1. Delete rows - chápu, ale mohlo by to být jako zašedlá pole. To jen tak na zamyšlenou.

2. Filter - v tomhle nemáš pravdu. Klidně si můžu vybrat do Columns sloupce 1, 2 a následně dát na sloupec 3 filtr. Je správně, že tohle můžu udělat. Nepotřebuju ten sloupec v transformaci. Jen podle něj potřebuju filtrovat řádky. A to chováni z toho dělá opruz. Nejdřív tam posílám všechny sloupce a mám nastavený filtr. Pak se rozhodnu nějaké vynechat a jakmile vyberu první, filtr mi zmizí. Ale já nechci aby zmizel. A je jedno, jestli tam ten soupec nakonec budu posílat nebo ne.

**Comment by ujovlado** [comment]
1. ok, mozno by sa s tym nieco dalo spravit.

2. a nebude to robit bordel? (mat filtre podla stlpcov,  ktore sa nedostanu "dnu")

**Comment by Matejkys** [comment]
2. Nebude. Zaprvé to jde nastavit i teď, akorát UI z toho občas dělá opruz :) Ale hlavně není důvod, aby tě KBC nutila posílat do Transformace sloupec, podle kterého chceš jen filtrovat. Stejně tak jako když máš SELECT s podmínkou WHERE, kde je sloupec, který ale není v samotném SELECTu.

**Comment by ujovlado** [comment]
Aha, tak to uz je jasnejsie. Oka, zmenim to tu, a skusime na to kuknut (nemam ale ETA)

**Comment by ujovlado** [comment]
To s tym filtrom poriesime v: https://github.com/keboola/kbc-ui/issues/3621
