### ISSUE TITLE
Orchestrator tasks - cannot add after removing

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1798]
Mám ve fázi 1 nějaký task, smažu jej a chci jej přidat do jiné fáze. Není v nabídce, musím reloadnout browser.

**Comment by natocTo** [comment]
@ondrejhlavacek  Stále aktuální? Zkouším reprodukovat a nedaří se. Pokaždé mám v nabídce na výběr stejné věci.

**Comment by ondrejhlavacek** [comment]
Potvrzuju, už to nedělá, díky!
