### ISSUE TITLE
react-select resets its input after jobs reload

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1807]
problem je detailne popisany v https://github.com/keboola/kbc-ui/pull/1805

V skratke input react-selectu sa resetne pri zmene props(po reloadu jobs) komponenty v ktorej sa rendruje. K resetu dojde po zmene referencie value prop react-selectu. Ak je value immutable object tak react-select za kazdym dostane inu referenciu pretoze sa vola toJS(). Ak je value string tak sa to neresetne

Riesenim je dopisat `shouldComponentUpdate(nextProps)` do tej komponenty. Dalsim mozny riesenim je rendrovat select s `onSelectResetsInput ={false}` co sposobi ze input sa nezmaze po vybrati hodnoty ale az po zavreti selectu.

#### Vyskyt Problemu

- [ ] U vsetkych komponent ktore maju generic mapping modaly v:
![image](https://user-images.githubusercontent.com/1412120/41776877-b1bc2a60-7629-11e8-965e-2be6d47920e9.png)

![image](https://user-images.githubusercontent.com/1412120/41776977-1ba36d26-762a-11e8-9f9c-a4d74cea089c.png)

- [ ] U `geneea.nlp-analysis-v2` app pri id, text, title, a lead columns selectoroch

**Comment by kacurez** [comment]
[ ] google drive extractor -> edit table -> set header select

**Comment by natocTo** [comment]
Toto je fixed? Koukám dvě věci merge. V Geneea jsem zkoušel nastavoval něco do selectu a zůstává to tam.
