### ISSUE TITLE
Nejde mi vůbec vlézt do TAPI

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#181]
![image](https://cloud.githubusercontent.com/assets/1427901/8249335/3fa51d6a-1669-11e5-8b25-a8fbe5f44073.png)

https://papertrailapp.com/groups/23635/events?q=transformation-cede2c8a69cc5cf70e6528e04fe9dee9

=> hlásí to, že tam není transformace, kterou jsem včera smazal ve starém UI. Takže nějaká cache, asi.

**Comment by padak** [comment]
ještě link: https://connection.keboola.com/admin/projects/258/transformations

**Comment by Halama** [comment]
fixnuto ručně smazáním konfigurace. Opravím ve starém ui ať správně maže transformační buckety zaregistrované.

**Comment by padak** [comment]
Na [Slevomat-CZ](https://connection.keboola.com/admin/projects/226/transformations) to taky failuje (transformation-48acd5e6452f1570820ef827c4e32da7) #fyi

**Comment by Halama** [comment]
taky jsem fixl

**Comment by Halama** [comment]
koukám že ve starém tr ui je to odregistrování implementované, zřejmě to teda bylo smazaný přímo ze SAPI konzole.

**Comment by Halama** [comment]
@ondrejhlavacek koukám že je to poměrně častý v projektech že je smazaný bucket a konfigurace zaregistrovaná, Asi by to teda bylo dobrý ošetřit v tom configs api callu at to ignoruje

**Comment by padak** [comment]
ted pri demování kbc jsem na to narazil na rohliku - je to vazne skoro vsude


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek


2015-06-22 12:12 GMT+02:00 Martin Halamíček <notifications@github.com>:

**Comment by Halama** [comment]
jj viděl jsem, proto jsem to otevřel znovu

**Comment by ondrejhlavacek** [comment]
@padak někdo tady musel obcházet UI :-(

**Comment by padak** [comment]
no, to doteď nebylo vyloženě problém, ne?

**Comment by padak** [comment]
jakože historicky toho bude kotel a otazka je, jestli to jde nějak "fixnout"

**Comment by ondrejhlavacek** [comment]
určitě to fixnu na backendu, ale vytvářet nový transformační buckety jen v SAPI nejde pěkně dlouho a od tý doby se nemělo používat SAPI na manipulaci s transformačníma bucketama vůbec.

**Comment by Halama** [comment]
imho to z nějakýho důvodu používali na mazání transformací a pak i bucketu.

**Comment by ondrejhlavacek** [comment]
V orchestraci bohužel budou tyhle smazaný buckety vidět furt. Budou se pak muset smazat ručním API callem přes /components v SAPI.

**Comment by ondrejhlavacek** [comment]
upraveno na backendu
