### ISSUE TITLE
TR phase numbers not aligned

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#1838]
S novým fontem jsou šoupnutá čísla fází v transformacích. A to najednou vypadá dost lame :)
@janmichek @jancermak 
![hello bank - transformations 2018-07-11 09-14-24](https://user-images.githubusercontent.com/12933713/42556182-1343121a-84eb-11e8-8b90-59542a2413ea.png)

**Comment by jancermak** [comment]
@Matejkys ahoj toto je hlavne na Jana - pingnul jsem ho.

**Comment by janmichek** [comment]
@Matejkys prikladm tu issue k dalsim nametum na tuning. Uplne presne nevim co ses mi snazil ukazat. Pripada mi ze to byla issue uz pred zmenou fontu.

**Comment by janmichek** [comment]
uz jsme to vykoukali, jde o vysku radku, ne zarovnani. Ze slova 'šoupnutá' jsem hned nevedel o co jde.
