### ISSUE TITLE
Search Hints

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#1840]
Since the search (jobs/files) is over ES, it could be useful to have a tooltip showing what can be searched (ie, the document structure)

ex: `+token.name:myEmail@keboola.com` etc...

**Comment by tomasfejfar** [comment]
@padak talked about this  - that it sucks for users (and padak as well) to search even though the search is quite powerful and only person who really knows how to use it is @Halama :) This could be a hotfix for the situation. It will not help normal users, but for power users it will be huge help. Or at least it's a step in good direction...

**Comment by Halama** [comment]
Related to https://keboola.productboard.com/feature-board/6270-status/features/32204/detail

**Comment by janmichek** [comment]
Duplicate: https://github.com/keboola/kbc-ui/issues/1823

**Comment by Halama** [comment]
Podobná věc už je v eventech, tak by to stačilo jenom dotáhnout.
![image](https://user-images.githubusercontent.com/903531/42633247-1ec5e748-85e0-11e8-8fed-a475965ab222.png)

**Comment by tomasfejfar** [comment]
No super! :) To v eventech je good enough. Vezmu si to na sebe po ZD.

**Comment by janmichek** [comment]
Ok, rozumim. Dodat tam nejaky textovy info to rozhodne udela pouzitelnym.
V dalsim kroku potom nejaky naseptavadlo to udela radost pouzivat.

**Comment by tomasfejfar** [comment]
Jo, našeptávadlo super, to už pak nechám na tobě.

**Comment by janmichek** [comment]
aha, chtel jsem to udelat spis naopak xD ale budiz
Navrhuju pouzit komponentu Popover z Bootstrapu na hover odkazu. https://indigo.keboola.com/?selectedKind=Bootstrap&selectedStory=Popover&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Da se z ni vykopirovat, a zaroven neni modalni, takze na ni muzes cumet a zaroven psat do searche

**Comment by janmichek** [comment]
@tomasfejfar Caj, jak to vypada s timto? Myslim ze je to za malo prace hodne uzivatelsky radosti .]

**Comment by tomasfejfar** [comment]
No, mě šlo spíš o to, jestli lokálně můžu spustit nějaký job :)

**Comment by tomasfejfar** [comment]
Ještě je potřeba to samé udělat ve files...

**Comment by ujovlado** [comment]
a ja tu skuamam, preco mi to nezavrelo tu issue :-D

**Comment by ujovlado** [comment]
Issue pre File Uploads: https://github.com/keboola/storage-api-console/issues/60

**Comment by ujovlado** [comment]
Doriesene aj File Uploads. Tu to zavrem. Dodatocny tuning doriesime v #1865
