### ISSUE TITLE
Orchestrator - Crontab every week/mont/year

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#1844]
Editace crontabu ulozi nastavene dny pro spusteni na pozici mesicu.
[Puvodni ticket #8754 v Zendesku](https://keboola.zendesk.com/agent/tickets/8754)

`0 1 2,3,4,5,6 *  *` vs. `0 1 * 2,3,4,5,6 *`

**Simulace**

1. Nastavit pole _"Every"_ na hodnotu: `Week`, `Month`, nebo `Year` a vybrat konkrétní dny, měsíce, nebo roky
2. Odebrat defaultni spouštění o půlnoci _(nastavit spouštění každou hodinu)_

![crontab](https://user-images.githubusercontent.com/1726727/42691767-a877cb90-86a9-11e8-8d1b-9a884ab4e579.gif)

**Comment by ondrejhlavacek** [comment]
Tohle jsem viděl, ale podle JT popisu to vypadalo, že to ještě uloží jako měsíce?

**Comment by ErikZigo** [comment]
Vsak jo. Ono se to posune jakoze o uroven vedle.

**Comment by ondrejhlavacek** [comment]
Jasne! V UI nejsou měsíce, toho jsem si před tím nevšiml, omg!
