### ISSUE TITLE
DB ex - own query off -> save

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1847]
If I have a DB ex cfg with custom SQL, turning "Create your own query using an SQL editor" off imply that cfg can't be saved.

via https://keboola.zendesk.com/agent/tickets/8796

**Comment by pivnicek** [comment]
I don't understand,  if I un-select the advanced query I can't save the configuration because it is invalid.
At minimum I must choose a table.

**Comment by padak** [comment]
yup, you're right! thx! p.
