### ISSUE TITLE
transformace - input mapping nejde přidat datový typ

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#185]
Pokud není žádný datový typ nastaven, nejde přidat nový.
Je to chyby backendu kdy se vrací místo prázdného objektu pole.
![image](https://cloud.githubusercontent.com/assets/903531/8250440/1e6a3b84-1674-11e5-9712-1b9041b4929d.png)

**Comment by ondrejhlavacek** [comment]
PHP no! zatroleně. 
budu to asi muset celé převést na pole, jinak z toho nevybruslím.

**Comment by Halama** [comment]
jakto? to pretypovani na objekt by melo stacit

**Comment by ondrejhlavacek** [comment]
bál jsem se, jak to půjde otestovat, ale phpunit to zvládne, takže dobrý
