### ISSUE TITLE
Tune job search hints a bit more

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1865]
Teraz je vlastne help len pre docker komponenty.

Chcelo by to doplnit aj navody napr. na orchestrator, transformacie a pod.

- `component:transformation durationSeconds:>10 AND -status:success`
- `component:orchestrator durationSeconds:>10 AND -status:success`

**Comment by ujovlado** [comment]
Related to: #1858

**Comment by ujovlado** [comment]
Este mi napadlo, ze mozno by si to zasluzilo aj nejaku podstrnku do dokumentacie, kde by tych prikladov mohlo byt este viac.

**Comment by janmichek** [comment]
Prezobavam navrhovane zmeny sem, na jedno misto
1. layout searchbaru je trochu jiny nez na ostatnich podstrankach (ex, wr, app)
2. nelibi se mi to nazvoslovi. Mame nekolik nazvu pro stejnou vec [search hints, quick help]

**Comment by ujovlado** [comment]
Doplnit potom info sem: https://help.keboola.com/management/jobs/ a kludne prelinkovat.

**Comment by ujovlado** [comment]
@tomasfejfar chcelo by sa ti to este dotiahnut a pripravit PR aj na dokumentaciu?

**Comment by tomasfejfar** [comment]
Jo, klidně se do toho pustím.

**Comment by ujovlado** [comment]
Super, myslim, ze bude stacit ak sa tam (do dokumentacie) prida par prikladov a potom na nu odkazeme z toho opopveru/modalu.

**Comment by janmichek** [comment]
Asi jsem slepej, ale nevidim, ze by vsechno bylo fixly, nebo se nad tim nejak diskutovalo.
https://github.com/keboola/kbc-ui/issues/1865#issuecomment-408828524

**Comment by ujovlado** [comment]
Dokumentacia doplnena v keboola/connection-docs#87, prelinkovanie #1888.

Ten layout sa trosku lisi, no skor mam pocit, ze je to zle v ostatnych sekciach (chyba border, lupa je natlacene moc dolava) ... to by som riesil v dalsich issues.

Neviem co si myslel tym nazvoslovim, kludne posli PR, ktory to zjednocuje.

Toto bola issue primarne kvoli https://github.com/keboola/kbc-ui/issues/1865#issue-345315640 ... tymi zmenami sa to doriesilo.

**Comment by janmichek** [comment]
Chapu, ze to byla issue na dokumentaci, prestoze jsi psal at to pichnu sem. https://github.com/keboola/kbc-ui/pull/1858#issuecomment-408827589

Cekal bych teda ze to prekopirujete, ne preskocite .]

Co se tyce searche v layoutu ostatnich podstranek - na Jobs je bohuzel jiny nez na ostatnich. Pred zmenami byl stejny na vsech podstrankach

**Comment by ujovlado** [comment]
> Chapu, ze to byla issue na dokumentaci, prestoze jsi psal at to pichnu sem. #1858 (comment)

aha, tak to mi uslo :) sorry ... proste nerad mixujem x veci dokopy ... spravme to teda prosim v dalsich issues.

> Co se tyce searche v layoutu ostatnich podstranek - na Jobs je bohuzel jiny nez na ostatnich. Pred zmenami byl stejny na vsech podstrankach

myslim, ze si to zmenil prave ty :) https://github.com/keboola/kbc-ui/pull/1858/commits/c68e46fa8e4e4e045efd0686689d2081787a73d1

takze ostalo to nazvoslovie ... stale neviem, kde je to nejdnotne, sprav asi issue/posli PR, ktory to zjednoti.
