### ISSUE TITLE
transformace - filtrovani tabulek sype chyby

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#187]

**Comment by Halama** [comment]
je to způsobený tím že description transformace je jako objekt `
![image](https://cloud.githubusercontent.com/assets/903531/8251671/c34eb26a-167e-11e5-8cf1-82def838f080.png)`

![image](https://cloud.githubusercontent.com/assets/903531/8251682/e9863138-167e-11e5-848d-30721ca4c104.png)

Moc teda nevím co s tím.

**Comment by ondrejhlavacek** [comment]
Jak se to tam dostalo? To by měl bejt text... Co to je za transformaci?

**Comment by Halama** [comment]
https://connection.keboola.com/admin/projects/226/storage#/tables/sys.c-transformation.googleDrive

**Comment by ondrejhlavacek** [comment]
maj tam nějakej custom atribut, kterej to zkurví ... to jim překopíruju jinam...
