### ISSUE TITLE
Allow orchestrator component when creating new token

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1876]
> Jestli to není moc složité, šlo by do UI, při zakládání API tokenů, přidat výběr na Orchestrace, by se tohle https://github.com/keboola/app-orchestrator-trigger#usage dalo naklikat rovnou v browseru?

Asi by stacilo do toho selectu, manualne pridat `orchestrator` komponentu.

**Comment by Halama** [comment]
+1 teď jsem Michalovi Procházkovi chtěl ukázat jak si v UI založí token kterým bude moct spouštět orchestrace ze skriptu, a pohořel jsem:)

**Comment by ujovlado** [comment]
ok, tak ja to rovno poriesim :)
