### ISSUE TITLE
nejsou vidět závislosti mezi transformacemi

### ISSUE THREAD

**Issue by tomastrnka** [keboola/kbc-ui#188]

**Comment by ondrejhlavacek** [comment]
?

**Comment by padak** [comment]
myslím že to je to samé co jsem psal v https://github.com/keboola/kbc-ui/issues/139

**Comment by ondrejhlavacek** [comment]
A to už je opravený (panel je vidět jen když je závislost vyplněná).

**Comment by Halama** [comment]
@tomastrnka můžeš to prosím upřesnit?
