### ISSUE TITLE
Data filter in input mapping "ne" not equal

### ISSUE THREAD

**Issue by matushy** [keboola/kbc-ui#1884]
Ahoj, ked si nastavim na input mappingu filter na Not in, tak je to zobrazene ako "ne" - treba si domysliet, ze to je "not equal". 

<img width="845" alt="screen shot 2018-08-01 at 21 29 45" src="https://user-images.githubusercontent.com/9285430/43544169-683118ce-95d2-11e8-99db-b8b44c1f2a44.png">

Najlepsie by to podla mna bolo zjednotit s moznostami, ktore mam pri edite input mappingu, na nieco taketo:
<img width="834" alt="screen shot 2018-08-01 at 21 30 25" src="https://user-images.githubusercontent.com/9285430/43544189-7b276e6a-95d2-11e8-93d8-7ab426f91344.png">

**Comment by janmichek** [comment]
@matushy Ahoj, Matusi diky za nahlaseni a navrhovane reseni. Prodiskutujeme a upravime to.
