### ISSUE TITLE
Project Invitations

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#1887]
- Místo současného přímého přídání uživatele do projektu chceme zavést systém pozvánek.
- Pozvánku musí uživatel potvrdit, teprve potom je přidaný do projektu.
- Pozvánku potvrzuje _(přijímá)_ přihlášený uživatel přímo v KBC.

Navrženo je to v PR zatím takto: https://github.com/keboola/connection/pull/1416
Jednotlivé části rozepíšu v komentářích.

**Comment by ErikZigo** [comment]
## Přidání do projektu
### Současný stav (bez pozvánek)
![image](https://user-images.githubusercontent.com/1726727/43586978-5e82b368-9669-11e8-92d2-44b0f76d8d15.png)
![aug-02-2018 15-36-07](https://user-images.githubusercontent.com/1726727/43587217-f122b7ea-9669-11e8-8e6a-d9218663530e.gif)

### S pozvánkama
- Tlačítko `Invite User` nahrazuje původní `New User` 
- Pozvánky se vypíšou pod přehledem uživatelů v projektu, je tam info i o tom kdo pozvánku vytvořil.

![image](https://user-images.githubusercontent.com/1726727/43587492-a3b70f5a-966a-11e8-8f12-9b7f1a19d552.png)
![aug-02-2018 15-41-29](https://user-images.githubusercontent.com/1726727/43587512-ae98df70-966a-11e8-8753-aa1c04f6c3ae.gif)

___
Martin k tomu měl připomínku, jestli by ty pozvánky neměly být spíš na samostatné stránce. https://github.com/keboola/connection/pull/1416#issuecomment-405484393

**Comment by ErikZigo** [comment]
## Seznam pozvánek
- Nová položka v `Your account` menu
- Samostatná stránka s výpisem všech pozvánek

![image](https://user-images.githubusercontent.com/1726727/43588691-576fb84c-966d-11e8-8f04-c2654ce04182.png)

Pozvánku jde přijmout nebo odmítnout.
- Přijmutí - Pozvánka se smaže, uživatel se přidá do projektu a dojde k přesměřování na detail overview v projektu
- Odmítnutí - Pozvánka se smaže

![image](https://user-images.githubusercontent.com/1726727/43588947-e982fc9e-966d-11e8-9269-5190b84b0ee2.png)

**Comment by ErikZigo** [comment]
## Notifikace v KBC
Je na stránce s přehledem všech projektů.

### Nově založený uživatel
Boxík v přehledu projektů _(odkaz na `Pending Invitations` stránku)_.
Je to obdoba `Promo Code` boxu.

![image](https://user-images.githubusercontent.com/1726727/43589312-b5e34f64-966e-11e8-80ff-41e6a398ae9b.png)

### Existující uživatel s projekty
Stejný box, jako u nově založeného uživatele.

![image](https://user-images.githubusercontent.com/1726727/43589457-0861c036-966f-11e8-93d7-c8db53fd34ba.png)

**Comment by ErikZigo** [comment]
## Notifikace emailem
### Současný stav (bez pozvánek)
Pokud mě někdo přidá do projektu, přijde mi zpráva: 

#### Nový uživatel
Link vede na formulář pro dokončení registrace a aktivace účtu.

![image](https://user-images.githubusercontent.com/1726727/43589925-0ad5aa16-9670-11e8-9cca-2280cc658621.png)

#### Existující uživatel
Link vede na overview projektu v KBC.

![image](https://user-images.githubusercontent.com/1726727/43590199-bc810954-9670-11e8-9aae-7e77caf57f42.png)

### S pozvánkama

#### Nový uživatel
Zůstává stejné, jako v současném stavu.

#### Existující uživatel
Link vede na stránku `Pending Invitations` v KBC.

![image](https://user-images.githubusercontent.com/1726727/43590453-4d51105a-9671-11e8-92df-e33a431f3226.png)

**Comment by ErikZigo** [comment]
Dneska jsme to téma probírali a vzešly z toho tyhle připomínky
- Tlačítko `Accept Invitation` zelené, místo modré
- Pokud mám víc pending pozvánek, tak po schválení jedné mě to hodí zpátky na přehled pozvánek.
- Pokud mám 1 pending pozvánku, tak po schválení mě to přesměřuje na Overview projektu
- Project users a project invitations dát do jedné tabulky
  - Sloučit sloupce user name, user email do jednoho (email na dalším řádku). Díky tomu vznikne volné místo a přidá se tam slupec s inviter name + email
  - Pozvánky budou podbarvené, stejně jako teď `Pending Accesss`, akorát asi méně agresivní barvou

**Comment by ErikZigo** [comment]
Tabulka users & invitations

Pár dalších věcí
- Joined + Expires - no-wrap u datumu
- Jméno - tučně, jako u pending access
- Inviter/Approver - Do stejného sloupce
- Reason - Přes tooltip do _Inviter/Approver_. Stávající slupec zmizí
- Inviter/Approver - Do stejného sloupce
- MFA - Not enabled  + Fix link - obojí no-wrap

**Comment by ErikZigo** [comment]
![image](https://user-images.githubusercontent.com/1726727/44153176-c33838c6-a0a7-11e8-8726-512ecd1c3f13.png)

**Comment by janmichek** [comment]
@ErikZigo predpokladam ze od nas mas vsechno pripadne si to doresis s Jackem.
Vidim ze ta issue je Closed ale v produkci zmeny nevidim. Tak nam jednom dej pls vedet v jakym je to stavu.  to samy je predpokladam pro MFA organizaci
