### ISSUE TITLE
UI & rozlišení 

### ISSUE THREAD

**Issue by tomastrnka** [keboola/kbc-ui#189]
Padák mi řekl, ať to sem napíšu, původně to bylo jen pro něj:

nechci být brán jako kverulant, ale celé nové ui je za mě trošku průšvih na rozlišení které je menší než full hd. Chápu, že na Karasově 2500x1900 monitoru to vypadalo hezky, ale 1200x800 je bolest

**Comment by Halama** [comment]
jj tohle je asi největší bolístka, nějak to poladíme

**Comment by Halama** [comment]
souvisí s https://github.com/keboola/kbc-ui/issues/165 tam jsem hodil i nějakej pokusnej fix

**Comment by Halama** [comment]
do Martina Lepky "Jinak v zasadě bych to shrnul ze bych cely UI zoom-outem zmenšil na 66%.  "

**Comment by tomastrnka** [comment]
:)) asi na tom fakt něco bude

On Jun 19, 2015 19:44, Martin Halamíček <notifications@github.com> wrote:
do Martina Lepky "Jinak v zasadě bych to shrnul ze bych cely UI zoom-outem zmenšil na 66%.  "

---

**Comment by ondrejhlavacek** [comment]
No tak a je vyřešeno, ne? :-D

**Comment by Halama** [comment]
no ale jak se to udělá? :)

**Comment by Halama** [comment]
Zjistím od Karase jak to zamýšlel a pak to bude asi na @JakubMatejka

**Comment by ondrejhlavacek** [comment]
`CMD -` :-)

**Comment by Halama** [comment]
od MK: "Tak jestli pujde jednodusse udelat nejaky zoom na cca 75% tak to bude asi nejlepsi reseni - ono by slo asi pripravit i variantu kde bude min white-space kolem elementu pro male rozliseni, ale to je asi zbytecne pracne ted.
"

**Comment by Halama** [comment]
fixnuto
