### ISSUE TITLE
Transformations backend labels

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1890]
Je tam nekolik mindfucku

1. label 'Snowflake' vypada pokazdy jinak
![image](https://user-images.githubusercontent.com/15363559/43600709-a2cca520-968b-11e8-9700-aa8098d4ea00.png)

2. cervena barva evokuje ze delam neco blbe
![image](https://user-images.githubusercontent.com/15363559/43600743-b97f39f4-968b-11e8-86ba-2e9c955184e2.png)

Navrhovana reseni. Pouzit loga backendu - podobne jako maji komponenty.

**Comment by Halama** [comment]
u tech tabulek (V tomhle pripade input mapping) ta informace o backendu je uz imho zbytecna. Davalo to smysl v dobe kdy projekty mely  mixovane backendy napr neco lezelo na mysql a neco na redshiftu. Takze tam bych to klidne dal pryc.

U backendu transformace to naopak ma byt zretelne a logo by mohlo byt fajn.

**Comment by janmichek** [comment]
followup -> https://github.com/keboola/kbc-ui/issues/1896
