### ISSUE TITLE
Stažení dat z Importního eventu nejde na poprvé

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1893]
Tlačítko "Prepare" co merguje data slicy, je potřeba zmáčknout opakovaně, než se změní na "Download". Tady je to nahraný: https://monosnap.com/file/u0EZXVtlXjdazcpHs00Ir3c7wMg8h4

P.S. Kdyby po tom stisknutí byl vidět nějakej progress

```
1/5 fetching slices...
2/5 running DataMerger...
3/5 merging slices...
4/5 compressing results...
5/5 uploading to S3
```
bylo by to dost cool, když je to veliký, dost to trvá a koukáš na šedivý tlačitko co vypadá jako mrtvý.

**Comment by Halama** [comment]
to vypadá na bug

**Comment by natocTo** [comment]
Toto by již nemělo být aktuální. Odzkoušeno a funguje to ok. Je tam i nějaký text aby tam nebyl pouze loader.
