### ISSUE TITLE
Transformations backend labels tuning

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1896]
cervena barva evokuje ze delam neco blbe
![image](https://user-images.githubusercontent.com/15363559/43822663-0ca7bec0-9aed-11e8-8354-1ce9da617654.png)

Navrhovana reseni. Pouzit loga backendu - podobne jako maji komponenty.
U backendu transformace to naopak ma byt zretelne a logo by mohlo byt fajn.

Tady je pravdepodobne zbytecne moc bilyho mista. Zjistit jestli se tam jeste neco nemuze vyrenderovat
![image](https://user-images.githubusercontent.com/15363559/43822638-f8d94a94-9aec-11e8-84d4-df953349b1c0.png)

**Comment by ujovlado** [comment]
> Tady je pravdepodobne zbytecne moc bilyho mista. Zjistit jestli se tam jeste neco nemuze vyrenderovat

- asi by som ten priestor nechal pre meno zdrojovej tabulky ... niekedy byvaju dlhsie
- a tiez stoji za zvazenie, ci by ta info o velkost nemala byt skor za menom zdrojovej tabulky

**Comment by janmichek** [comment]
odkladam odkazy:
R logo svg https://commons.wikimedia.org/wiki/File:R_logo.svg
Python logo svg https://commons.wikimedia.org/wiki/File:Python-logo-notext.svg
Open refine logo https://github.com/OpenRefine

**Comment by jancermak** [comment]
@janmichek @ujovlado — potrebujeme aby velikost tabulky byla tak moc viditelna? 
![image](https://user-images.githubusercontent.com/1826442/46068448-77358580-c179-11e8-9ed3-20a7a136202e.png)

**Comment by janmichek** [comment]
Myslim si ze nebude vadit, kdyz informace o velikosti bude v jinym nez v prvnim sloupci. Jestli to ma historicky duvod, nevim. Bude vedet spis Vlado.

**Comment by ujovlado** [comment]
@jancermak to si dal celkom pekne :100: :1st_place_medal: :tada: 

Osobne som za verzie bez tooltipov (na mobiloch a podobgnych zariadeniach si to neskrtne). Takze za mna:

- z prvej casti urcite VB (  + asi by som tam nezobrazoval vobec to info o "last import")
- z druhej casti V4 ... ostatne su imho moc vyrazne a V5 robi tie loga menej prehladne

**Comment by janmichek** [comment]
Fajnovy, za me vede V4 nebo V3 (ta lip kontrastuje v zebrovani)

**Comment by jancermak** [comment]
@ujovlado dekuju.
— tooltipy - vychazel jsem z toho ze uz je tam pouzivame a beru ze primarne cilime na desktop http://take.ms/4nT0J
— to info o last importu me prislo docela zajimavej napad. Martin mi rikal o flow, kdy to potrebuje vedet a musi postupne rozklikavat kazdy mapping a najizdet mysi na nazev tabulky aby se to dozvedel. Je to takovy improve.

**Comment by ujovlado** [comment]
K tym tooltipom nemam moc co dodat, no :)

Ohladom "last import" - tak potom ok ... nevedel som, ze je na to case - osobne som to nikdy nepotreboval (zvacsa som len kukal size - co tam je - ze preco nejaky import trval dlhsie alebo tak)

**Comment by janmichek** [comment]
Fajnovy, 
jeste bych pak zkusil sehnat svg loga pro vsechny backendy, at nemusime mit vic velikosti.
Tobe nevadi ten slabsi kontrast pozadi a labelu @jancermak  ? Asi to preziju, ale me to vizualne rozciluje .]

**Comment by jancermak** [comment]
—uvidis ja sem moc stesti s tema SVG u snowflejku a Open refine nemel
— @janmichek nevadi. Nepotrebuju aby to bylo vyrazny rychla orientace probehne pres ikonku backendu ten text beru jako doplnek kdyz nekdo nezna ikonu.

**Comment by janmichek** [comment]
ok, rozdelim to na 2 issues - loga  a layout

**Comment by janmichek** [comment]
Druha cast teto issue odpovida jiz vzniky issue. 
Abychom udelali layout nejak sikovne a nevyselo to v eteru, je potreba to zdokumentovat v indigu.
Takze budu pokracovat s upravou layoutu tady https://github.com/keboola/indigo-ui/issues/224
