### ISSUE TITLE
DB Writers - data preview fails if table has more than 100 columns

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#1900]
DB writery pouzivaji pri mapovani sloupcu data-preview pro nahled dat v tabulce.

Pokud ma zdrojova tabulka vic nez 100 sloupcu tak UI hazi chybu.

![image](https://user-images.githubusercontent.com/1726727/43839189-c9a2a62c-9b1d-11e8-8363-6302481d5778.png)

Je to diky tomu ze v preview se pouziva synch export z tabulky a ten je limitovany na 100 sloupcu kvuli alokaci pameti.

**Comment by Halama** [comment]
casem by to mel resit json data preview kde to proste budeme truncatovat https://github.com/keboola/connection/issues/1089#issuecomment-391317789

**Comment by ErikZigo** [comment]
@kacurez nechci se jim vrtat v konfiguraci ale edit mode mi prepnout jde a delat zmeny v datovych typech taky

**Comment by natocTo** [comment]
json data preview již nasazaný tak snad vyřešeno
