### ISSUE TITLE
wr-google-drive: different heights of inputs in input group

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#1903]
![Alt text](https://monosnap.com/image/FczbCba1DaCQgKUvXVGv2M1h0OGRZZ)

**Comment by MiroCillik** [comment]
Same as in `wr-google-sheets` https://github.com/keboola/kbc-ui/issues/1868

**Comment by natocTo** [comment]
Koukám v Chrome, Firefoxu a Edge a vše je v pořádku. Tak asi zavřu, nejspíš se to vyřešilo nějakým updatem.

![test](https://user-images.githubusercontent.com/12331181/48049382-ca4e1f80-e19e-11e8-9fd9-7487b6b27f6b.png)
