### ISSUE TITLE
Falied transformation - no link to transformation

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1910]
![image](https://user-images.githubusercontent.com/15363559/43900573-96864c80-9be5-11e8-8b1a-6f21abe3f7a2.png)

lze se prokliknout jen do bucketu. Kdyz tam mam hodne transformaci je to nepohodlny. Navic kontext jobu se tyka transformace, ne bucketu.

**Comment by janmichek** [comment]
@ondrejhlavacek Myslim ze na to mam reseni, zasekl jsem se u jedny veci.
Nedari se mi vystourat jmeno transformace. Respektive jmeno se zmeni po kliku na link.
Coz mi davalo indicii ze ta hodnota neni ready a je treba si ji predpripravit ze storu.
Coz jsem udelal, ale chovalo se to stejne. Nesetkal ses s necim podobnym?
![tf](https://user-images.githubusercontent.com/15363559/43956864-01cb3e18-9ca6-11e8-977d-6cba3c4700e2.gif)

**Comment by ondrejhlavacek** [comment]
@janmichek fixnuto v https://github.com/keboola/kbc-ui/pull/1915/commits/ba5a3e7b4ef2cc8a0a1b3766695511a2baa8c8e8

mám k tomu pár poznámek

- bylo by super, aby to ukázalo bucket i transformaci v detailu (obojí klikací)
- v listu by to taky mohlo ukázat jak bucket tak transformaci (bude potřeba přesunout ten můj fix v routě o úroveň výš)
- bylo by super, kdyby totéž šlo i pro ostatní configy (aspoň ty s config rows, kde to je sjednocený)

**Comment by janmichek** [comment]
Diky, premyslel jsem o tom podobne (link na obe urovne). Checknu si to.
