### ISSUE TITLE
Renaming configurations doesn't always work

### ISSUE THREAD

**Issue by pocin** [keboola/kbc-ui#1911]
using this UI element <img width="824" alt="screen shot 2018-08-09 at 16 58 43" src="https://user-images.githubusercontent.com/8642344/43907421-ae1f3f2c-9bf5-11e8-9425-9d440b4af631.png">

I always get an error (as in the pic) and the new name is not saved. Usually it takes couple of retries until the change propagates.

The network requests (PUT) look fine

<img width="1279" alt="screen shot 2018-08-09 at 17 01 40" src="https://user-images.githubusercontent.com/8642344/43907548-fd425094-9bf5-11e8-9deb-8023c9f80d50.png">

I am on Firefox 61.0.1, macOS 10.13.15.

Let me know if you need more info

**Comment by ujovlado** [comment]
I can confirm this is broken. Thanks for report, we'll fix it.

**Comment by ujovlado** [comment]
@pocin fix has been deployed. Could you confirm it's working for you?

**Comment by pocin** [comment]
looking good, thanks!
