### ISSUE TITLE
gooddata writer - browser error

### ISSUE THREAD

**Issue by mwong023** [keboola/kbc-ui#192]
Please see screenshare here:

https://s3.amazonaws.com/kbc-sapi-files/exp-180/806/files/2015/06/19/120179306.new_ui_error.mov

Happened 4 times in a row to me.

**Comment by padak** [comment]
here we have a screenshot:
![image](https://cloud.githubusercontent.com/assets/1427901/8266358/47c372a4-172b-11e5-9555-d799308f4f4c.png)
