### ISSUE TITLE
Hardlink eventu z jobu nefunguje

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1922]
Mám Job https://connection.eu-central-1.keboola.com/admin/projects/133/jobs/6614136?q= ve kterém chci někomu poslat konkrétní event. V mém případě po doloadování eventů (tlačítko `More`) je to tohle: https://connection.eu-central-1.keboola.com/admin/projects/133/jobs/6614136?q=&eventId=57914667

![image](https://user-images.githubusercontent.com/1427901/44139394-3a4f0e2a-a077-11e8-8d38-b35b9136f28a.png)

Pokud si to otevřu v novém okně, vidím tohle:

![image](https://user-images.githubusercontent.com/1427901/44139407-48ec34b2-a077-11e8-8f6d-3804e2e8eb57.png)

Vlastně stačí dát jen "Reload" pokud koukám na ten konkrétní detail eventu. Bylo by super, kdyby si to zkusilo doloadovat, jako když já dávám to tlačítko "`More`":

![image](https://user-images.githubusercontent.com/1427901/44139453-6f0b5682-a077-11e8-8963-3fe143ff0d31.png)

**Comment by Halama** [comment]
To je určitě bug. Jsem si skoro jistý že to dříve fungovalo.

**Comment by natocTo** [comment]
Testuji toto a vypadá že to již funguje podle představ. Dám detail eventu, zkusím reload nebo otevření v novém okno a detail eventu tam furt mám. Not found tam občas jen problikne na začátku pokud se asi musí donačíst. 

@ujovlado  můžeš ve volné chvíli ověřit? 

Ps: vidím tam nějaký render error výše občas, ale na Job jsem se chtěl více podívat až to nebude v coffee. Tak to teď nebudu řešit více a pak si na to vše podívám. Pokud by se to seklo na dýl tak určo mrknu dříve ať errory nejsou.

**Comment by ujovlado** [comment]
Podla mojich testov to nefici:

- najdi si nejaky job, v ktorom dole vidis "More", klikni tam
- klikni na nejaky event
- skopiruj si url a otvor nove okno ALEBO stlac hard reload

Mal by si vidiet:

![screenshot_2018-10-25_16-42-26](https://user-images.githubusercontent.com/419849/47508766-fc918000-d874-11e8-9b86-84936ce30ba0.png)

On to myslel tak, ze ked ten event nenajde (nema ako zobrzit detail), tak by mohlo "automaticky" ponacitavat dalsie, az kym sa ten event nenajde. Neviem ale do akej hlbky ist - moze nastat situacia, ze ich tam bude fakt vela.

Ine riesenie by bolo skusit nacitat len konkretny event.

**Comment by Halama** [comment]
Ono to dřív mělo fungovat tak že to zkusí načíst detail toho eventu podle id z url. Tzn nemusí listovat do historie.

**Comment by Halama** [comment]
K tomu by mělo sloužit tohle https://github.com/keboola/kbc-ui/blob/1ea801b3ed92b6a358c44b66898ea0fd6fe25e30/src/scripts/modules/sapi-events/EventsService.js#L66 zřejmě se to netrigruje?

**Comment by ujovlado** [comment]
Hm, a zdalo sa mi to ako blbost - chapal som to tak, ze potvrdzujes, to co pise Padak - ze sa to doloadovalo.

Ok, tak to bude rychly fix, asi vidim problem.

**Comment by Halama** [comment]
aha, ne. Jde čistě o to že když ti někdo pošle link na konkrétní event tak ať ho to zobrazí. Doloadování kolem se neřeší.
