### ISSUE TITLE
Search u configu - false match

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#1930]
Mám spoustu konfigurací a hledání mi ve filtru vrací i takové, kde zaboha nemůžu přijít na to proč.

![image](https://user-images.githubusercontent.com/1427901/44197062-ea40ea80-a13d-11e8-8f07-762477cca312.png)

Tady je příklad: https://connection.eu-central-1.keboola.com/admin/projects/25/extractors/keboola.ex-db-mysql

Zadám "CDC" a vrátí mi to jak cfg co to mají v názvu, tak ty co to mají v historii verzí (https://monosnap.com/file/kNWAXX1P354lnfxSlS4XUHEy4VZA4A), ale i ty, co ten search pattern vůbec nikde nemají (https://connection.eu-central-1.keboola.com/admin/projects/25/extractors/keboola.ex-db-mysql/424113). 

Jako uživatel bych nejradši viděl hlavně ty, co mají match na jménu konfigurace, pak na popisku, pak na jména config-rows a až úplně někde na posledním místě podle historie verzí. Ideální je to rozlišit něčím jako "search 'deeper'?" co by mi přidávalo výsledky.

**Comment by kacurez** [comment]
tu je fce ktora to vyhladava a nato pouziva fuzzy.match 
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/pages/component-detail/ComponentDetail.coffee#L79

asi by stacil obycajny case insensitive indexOf >= 0

**Comment by janmichek** [comment]
Jo, jasne  ten vyhledavaci algoritmus nemusi byt tak uvolneny. Obzvlast kdy tam zacnes mit vic obsahu, tim padem pouzivas vyhledavani, chces radeji prisnejsi vyhledavaci pravidlo.
Odeberu ten fuzzy, at to nedela tolik mismatchu.

**Comment by padak** [comment]
@janmichek teď jsem si ještě všiml, že když tam napíšu "MySQL", vidím všechny konfigurace týhle komponenty. Jakmile ale dám " " (mezeru), tak mi všechno zmizí a vrací mi to konfigurace S3 extraktoru, který mají v popisu napsaný "mysql". Nemám jasnej nápad na řešení (nevím co aktuálně umíme), ale jméno tý komponent by bylo fajn brát taky. Nahrál jsem tady screencast: https://monosnap.com/file/CGXdDTB5NnE6HcUqqmsFRK8iIZo549

Líbylo by se mi, že když napíšu "CDC", vrátí mi to tohle 

![image](https://user-images.githubusercontent.com/1427901/44256151-a0710680-a208-11e8-8a5d-4e18bad05b9b.png)

(screenshot / screencast schvalenej klientem k publikaci :)

**Comment by janmichek** [comment]
@padak ok, rozumim tomu. Vyresim to ale v separatni issue.
