### ISSUE TITLE
New configuration (default form) - badges

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1939]
![screenshot_2018-08-17_21-51-56](https://user-images.githubusercontent.com/419849/44286015-d396b280-a267-11e8-8de7-4d0ab9683375.png)

The form has been fixed (aligned). Now we can discuss those labels.

cc: @janmichek @pivnicek

**Comment by ujovlado** [comment]
Ako sa nam tie badges postupne rozsirovali, tak to trosku vyzera, akoby to tam nepatrilo. Povodne tam toho bolo ovela menej a ak sa nemylim, tak slo len o to upozornit usera, ze suhlasi s podmienkami vendora a, ze jeho data pojdu mimo connection napr.

Skusim k tomu najst nieco viac.

**Comment by ujovlado** [comment]
Takto to vyzeralo pred fixom: https://github.com/keboola/kbc-ui/issues/1937 ... najdem este nieco skorsie

**Comment by ujovlado** [comment]
Tam kde su flagy, tak tam bol este povodne label "Licence".

**Comment by ujovlado** [comment]
Da sa povedat, ze tam bolo len toto: https://github.com/keboola/kbc-ui/blob/182c75ccb8917e3dac361caeda4e56008c48fb93/src/scripts/modules/components/react/pages/new-component-form/DefaultForm.coffee#L97

A app info:
https://github.com/keboola/kbc-ui/blob/182c75ccb8917e3dac361caeda4e56008c48fb93/src/scripts/modules/components/react/pages/new-component-form/AppUsageInfo.coffee

A asi suhlasim, ze je to tam uz zbytocne a checkbox, ze user suhlasi by to mal pokryt (pripadne ho rozsirime)

**Comment by jancermak** [comment]
@ujovlado z cisty vody me napadli dve varianty reseni:

1) Smazat vse co je duplicitni s predchozí obrazovkou http://take.ms/0xglM
2) Ukazat jenom labely (popisky na tooltip) a pripadne vendora— http://take.ms/AWiUA

**Comment by ujovlado** [comment]
Osobne sa mi paci najviac 1.

Este by som sa asi spytal @padak, co si mysli - z hladiska nejakych legal reasons. Myslis, ze staci, ze by tam ostal ten checkbox a user by vlastne akceptoval "nieco" co moze byt aj na predchadzajucej obrazovke?

**Comment by ujovlado** [comment]
oka, v tom pripade by tam ostalo len Name, Description a "I agreee"

**Comment by jancermak** [comment]
@ujovlado @janmichek 

![1939 new configuration_default form_badges](https://user-images.githubusercontent.com/1826442/45758485-fc72e480-bc25-11e8-95f0-518ca4e72048.png)

**Comment by pivnicek** [comment]
no badges?

**Comment by janmichek** [comment]
Za me dobre, jsem ok s minimalistickou variantou. Ty labely se stejne duplikujou s predchozi podstrankou. To info by uzivatel prehlidnout nemel. Cim min css budeme mit, tim budeme stastnejsi. 
Pokud nikdo nic nema, prikrocim k dokumentaci do indiga a implmentaci.

**Comment by ujovlado** [comment]
Neviem ci je nutne aby to slo cez indigo, ale jo, kludne sa do toho pust. Asi jediny kompromis bude velkost ikony komponenty.

**Comment by janmichek** [comment]
Ok
step 1 - uprava v kbc, prototyp.
step 2 - presun do indiga, pokud to nebude mit zadny downside.

**Comment by ujovlado** [comment]
Takto, nie som proti, ze spravis v indigo story. Skor som myslel, ci nebude overkill robit z toho komponentu, ked sa jedna vlastne len o poskladanie standardnych komponent, co mame (modal, form, ...)

**Comment by janmichek** [comment]
Got it, zjistim.

**Comment by janmichek** [comment]
Ikony renderujeme ve 2 velikostech 32 a 64 px.
Takhle mi prijde ze jen tam az moc bilyho mista.
![image](https://user-images.githubusercontent.com/15363559/45836428-23581600-bd0d-11e8-87c6-78f14b0c8cef.png)

 - muzu zkusit ikonu horizontalne vystredit
- ted je ten grid layout 3/9. Zkusil jsem mrizku 2/10, ale ty labely jsou potom moc nalepeny.
- alternativne se da zuzit nebo rozsirit sirka modalu

**Comment by janmichek** [comment]
@jancermak 
S tema marginama u formulare neblbni covece xD
Jsem rad za precizni praci, nicmene by to znamenalu upravu vsech formu v aplikaci, nebo custom styly jen pro tento form. Zatim to bohuzel neresim.

**Comment by janmichek** [comment]
@jancermak Tady posilam za me upravenou verzi. Mrkni a pripadne udelame posledni vizualni upravy podle tebe.
- obrazek jsem vystredil ( protoze je 64x64 ). Zkousel jsem sirsi i uzsi modal - nelibilo se i to.
- sirka modalu standartni
- nekde jsem upravil marginy pocitove - opticky stred

![image](https://user-images.githubusercontent.com/15363559/45839022-7208ae80-bd13-11e8-8d3e-bfbd76662907.png)

![image](https://user-images.githubusercontent.com/15363559/45839029-75039f00-bd13-11e8-93dd-2f847861abcb.png)
