### ISSUE TITLE
Není vidět Latest Imports graf v SAPI

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#194]
Pokud nahraju něco do tabulky, neukazuje to graf, ten není vidět ani nikde jinde

![image](https://cloud.githubusercontent.com/assets/1427901/8273586/bdd77b12-1874-11e5-80b7-ac9014ce0344.png)

u některých tabulek to vidět je ([zde](https://connection.keboola.com/admin/projects-new/478/storage#/tables/in.c-ex-api-zendesk-keboola.tickets)) a u některých ne ([zde](https://connection.keboola.com/admin/projects-new/478/storage#/tables/in.c-ex-api-zendesk-keboola.ticket_comments)) - zjevně to není úplně o novém UI...

**Comment by Halama** [comment]
Graf se zobrazuje pouze pokud je tam více než dva importy, u té druhé je jenom jeden.
![image](https://cloud.githubusercontent.com/assets/903531/8277748/11deef0a-18c6-11e5-9ed4-c93da2a0bfac.png)
