### ISSUE TITLE
DetailedDiff

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#1946]
https://connection.keboola.com/admin/projects/232/transformations/bucket/430264131/versions

`#11 to #10`

![image](https://user-images.githubusercontent.com/497675/44456447-d810f180-a600-11e8-8595-ddb93815e2fa.png)

**Comment by kacurez** [comment]
ked si transformaciu zkopirujem bokom tak to robi tiez ale ked si iba zkopiruje query stringy do inej transformacie tak to nespadne vid
![image](https://user-images.githubusercontent.com/1412120/44457638-0d6b0e80-a604-11e8-8bbf-adff3350dd67.png)

vedel by si popisat ste-by-step ako to nasimulovat bez vykopirovania celej transformacie?

**Comment by kacurez** [comment]
podarilo sa mi to nasimulovat, bez krokov 4+5 ako pises, dik

**Comment by ujovlado** [comment]
Fixed in #1949
