### ISSUE TITLE
weird bread crumbs behaviour - missing names and icons

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#1950]
imho deje sa to len u niektorych custom uis:
- chybaju ikonky
- nazov sa zobrazi ako staticky bold text
- nazov uplne zmizne

![image](https://user-images.githubusercontent.com/1412120/44530016-c6f1de80-a6ed-11e8-8e1f-8f5100701959.png)
![image](https://user-images.githubusercontent.com/1412120/44530096-f6085000-a6ed-11e8-90c4-886362fa760e.png)
![image](https://user-images.githubusercontent.com/1412120/44530125-04ef0280-a6ee-11e8-8f32-c64f49a7489d.png)

**Comment by ujovlado** [comment]
Je to touto zmenou:
https://github.com/keboola/kbc-ui/commit/84a1ba10ab8fd00bc11d6d7757dfcf00029ce3e9

**Comment by ujovlado** [comment]
Ked zmazem:
https://github.com/keboola/kbc-ui/blob/68ec3887b5caaa3db1789c310df65c630ad0a261/src/scripts/stores/RoutesStore.coffee#L146-L150

tak sa to rozbehne
