### ISSUE TITLE
Feature request option

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1960]
Moznost vyzadat si nove featury do kbc je dana jen lidem co znaji link na product board https://portal.productboard.com/ltulbdlwnurf2accjn3ukkww

Radi bychom to zabudovali jako polozku do aplikace.

**Comment by jancermak** [comment]
@janmichek 

pridal jsem jeste upravu  - prejmenovani user & settings na "Project Configuration" nebo "Project Setup"

Ikonky jsem pouzil z font awesome:
class="fas fa-cog"
class="fas fa-tasks"

![1960 feature request option](https://user-images.githubusercontent.com/1826442/44852659-20b15600-ac64-11e8-904a-697c4ed8c442.png)

**Comment by janmichek** [comment]
Dik za navrh. Zpracuju to.
- Zatim bych se nepoustel do prejmenovavani do 'users & settings' - nepripada mi ze by to bylo v konfliktu s 'Keboola Roadmap'

- Pridam tedy polozku s ikonou a ExternalLinkem v novem okne

- Na tlacitku je label 'Keboola Roadmap' po kliku se dostanu na stranku ktera se jmenuje 'Keboola Connection - public roadmap'. Zas tak me to nesere ale jsem rad kdyz dostanu to na co klikam.

Spis by se mi libilio upravit PB stranku [pokud to jde] aby mela nadpis 'Keboola Roadmap' s description 'Feel free submit ideas for new features to Keboola Connection on this page .... ' 

@padak pokud by to melo viset takhle v aplikaci asi by PB chtel vetsi peci - nebo treba vyhodit tab 'Weekly status' - at si na sebe nesijeme zbytecne bic

**Comment by janmichek** [comment]
@padak tady ^^^

**Comment by padak** [comment]
@janmichek přejmenoval jsem to. Hele, trochu se bojím toho "roadmap" - je to dost příslib nějaký cesty, kterou bych rád fixnul nejdřív interně. Co kdyby to byl spíš Keboola Wishlist nebo Keboola Feature Request?

**Comment by janmichek** [comment]
Chapu, 'Keboola Wishlist' zni dostatecne alibisticky .] Prejmenuju ten label

**Comment by janmichek** [comment]
@padak ok, ta zmena je ready. Az si pofackujes ten PB, tak nam dej znameni. Muze to byt nasazeny celkem rychle.

Pokud by sel dat jeste nejaky description pod nadpis 'Keboola Wishlist' na PB strance, bylo by to ideal.
neco ve smyslu 'Feel free submit ideas for new features to Keboola Connection on this page .... '

**Comment by janmichek** [comment]
@padak Povedlo se ti pofackovat ty tasky v productboardu? Je to teda aktualni a ke zverejneni?

**Comment by padak** [comment]
@janmichek hodil jsem na to oko, trochu to pofackoval, ale myslím, že tu můžeme pustit

**Comment by ondrejhlavacek** [comment]
Je na to celá sekce na první stránce nápovědy - https://help.keboola.com/#your-tips-and-suggestions. Imho to není věc, která patří do hlavního menu, neobsluhuješ tím svůj projekt. Za mě - rozšířit sekci v nápovědě o popis, co a jak se v PB děje, uvést to mezi lidi postem na statusu, ale nedávat to do hlavního menu. Není to imho tak kulervoucí věc (jako třeba `Analytical Warehouse`), že by to muselo bejt lidem furt na očích. 

Kromě toho, nestačilo by jen `Wishlist` místo `Keboola Wishlist`? Jakej jinej wishlist než `Keboola Connection` (navíc!) by to měl bejt?

cc @padak @janmichek @jancermak

**Comment by janmichek** [comment]
S tim umistenim linku - dava mi smysl oboje. (help i sidebar). Zalezi jak moc to chceme bombit uzivatelum.
Nevim jestli wishlist neni moc obecny. Muj skromny navrh 'Feature Wishlist'.
Rozhodne jsem pro to aby finalni nazev štimoval s labelem odkazu a headerem na PB strance. Dostanu to na co kliknu

**Comment by padak** [comment]
Header v PB nastavíme na cokoliv, doufám

Dne st 19. 9. 2018 21:09 uživatel Jan Michek <notifications@github.com>
napsal:

**Comment by ondrejhlavacek** [comment]
Vzal byste si někdo na starost úpravu tý nápovědy a sladění nadpisů? Do nápovědy asi i doplnit, jak to funguje a co od toho maj / nemaj čekat? Dík :-)

**Comment by ujovlado** [comment]
Mozem dohliadnut na to, nech nezabudneme ten PR do connection :) Inac to je len zmena textov a owner tejto featury je asi Jan :stuck_out_tongue:

**Comment by janmichek** [comment]
Mkay, shrnu si to

- [ ] upravit sidebar polozku na 'Feature Wishlist'
- [ ] zmenit obsah help.keboola.com. Email wishlist@keboola.com  vymenit za link na PB
- [ ] zmenit header PB podstranky na 'Feature Wishlist'
- [ ] fixnout focus styl [low prio at neblokuje] https://github.com/keboola/indigo-ui/issues/269

**Comment by ujovlado** [comment]
> fixnout focus styl [low prio at neblokuje]

kludne to poriesi uplne mimo tohto, je to tam dlho

**Comment by janmichek** [comment]
Tady je PR do dokumentace. Zmena bude vypadat nasledovne
https://github.com/keboola/connection-docs/pull/92
![image](https://user-images.githubusercontent.com/15363559/45822624-2ee71500-bcec-11e8-9c7b-b0c563e89e81.png)

Jedu na dalsi zmeny.

BTW: trochu me prekvapuje ze jsem v dokumentaci nenasel link na FB komunitu. Muzu to doplnit v jinym PR, pokud to nema byt 'dark UX' xD

**Comment by janmichek** [comment]
Zmena labelu v KBC https://github.com/keboola/kbc-ui/pull/2069

**Comment by janmichek** [comment]
Pokud vse ok, muzeme nasadit. Focus bug resim paralelne.

**Comment by janmichek** [comment]
Upraveny focus styly https://github.com/keboola/indigo-ui/pull/273

**Comment by janmichek** [comment]
PR do Connection https://github.com/keboola/connection/pull/1540

**Comment by janmichek** [comment]
Fajn, header v PB uz je prejmenovany na 'Keboola Connection - Feature Wishlist', poprosil bych toto mergnout v nasledujicim poradi

1. https://github.com/keboola/kbc-ui/pull/2069 @ujovlado 
2. https://github.com/keboola/connection/pull/1540

a bude to hotovo
