### ISSUE TITLE
Retry job tuning

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1964]
- vyndat UI ze zabalovaciho panelu - vzdycky to chci videt.
- uchecknout checkboxy k prvnimu failnutymu jobu

**Comment by janmichek** [comment]
@ondrejhlavacek 
Nevis takhle z fleku proc mi v tyhle prop nechodi hodnota attributu 'status' ?

https://github.com/keboola/kbc-ui/blob/02ad417ddc44b7c21613a7e3db78a0b19bbac5c9/src/scripts/modules/orchestrations/react/components/TaskSelectTableRow.coffee#L42

Moje ocekavani bylo ze checkbox zaskrtnu dle stavu '@props.task.get('status')' a cau. Ja se v tom povrtam a nejak si to tam primerguju

**Comment by Halama** [comment]
task nema nic jako status

**Comment by Halama** [comment]
https://keboolaorchestratorv2api.docs.apiary.io/#reference/orchestrations/orchestration-tasks

**Comment by Halama** [comment]
asi tam chces status jobu ne?

**Comment by ondrejhlavacek** [comment]
Jak píše Martin, budeš na to muset jít trochu oklikou, ale zas tak hrozný to není. Někde to má jako parenta komponentu `JobRetryButton`, kde je detail jobu a v něm už jsou resulty po taskách.

![image](https://user-images.githubusercontent.com/497675/44910555-f3c47800-ad23-11e8-996f-3fd624c52d0b.png)

Ten job bych v komponentě `JobRetryButton` zpracoval a vytáhl, jaký tasky maj bejt selectnutý a tuhle informaci předal přes `modals/TaskSelect` do `components/TaskSelectTable`.
