### ISSUE TITLE
Disable individual transformations

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1966]
Z uzivatelsky feedbacku vypadlo ze uzivatelum chybi moznost podisablovat si jednotlivy transformace v orchestraci. Muzou disablovat jen cely bucket. Ma cenu to vic rozepisovat a udelat tuto moznost? @ondrejhlavacek ?

![image](https://user-images.githubusercontent.com/15363559/44843807-7d534780-ac49-11e8-953e-2bd8bef17071.png)

**Comment by ondrejhlavacek** [comment]
Ne, řekl bych, že bucket je nejmenší jednotka, kterou chceš v orchestraci pouštět. Stejně tak v orchestraci nenastavuješ jaký tabulky extraktoru budeš pouštět, ale pustíš extraktor. Pokud bychom se do něčeho takovýho chtěli pouštět, tak pro všechny komponenty. 

Chápu, že někdo zkonfiguruje extraktor a některý tabuky chce tahat jednou za hodinu a jiný denně. Měly by to bejt dvě konfigurace a pokud je překážka, že se jim nechce spravovat dvoje credentials, tak to bychom měli řešit přes nějakou centrání správu credentials. 

A jestli usecase byl v tom, že transformace trvá a při retry není potřeba jí pouštět celou, tak bych asi řekl, že pokud jde transformační bucket smysluplně pustit jen částečně, tak by to měly bejt dva oddělený buckety?

Celý to ber spíš jako názor, budu rád, když to bude někdo rozporovat. Nevíš přesnej důvod, proč jim to chybí?

**Comment by janmichek** [comment]
Taky mi to pripada jako blbost prave. Jeste to checknu.

**Comment by janmichek** [comment]
rozumim, jeste jednou jsem to prosel. myslim ze je to blbost
