### ISSUE TITLE
gooddata-writer: přetékání detail tabulky

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#197]
![image](https://cloud.githubusercontent.com/assets/903531/8277816/a7ad4676-18c6-11e5-98b7-b612459b2148.png)

**Comment by Halama** [comment]
@JakubMatejka tady by asi bylo dobrý aby to tu tabulku prostě roztáhlo. Bude se to hodit i kvůli #177

**Comment by JakubMatejka** [comment]
Jak se ti to podařilo? Nedaří se mi to nasimulovat, potřeboval bych vidět zbytek toho screenshotu.

**Comment by Halama** [comment]
tohle jsem udělal tím že jsem zmenšil okno browseru :) Ale TF to dělalo někde i na celou šířku

**Comment by JakubMatejka** [comment]
To jsem zkoušel ale nešlo to. Obzvlášť nechápu jak se ti podařilo dostat formát a dimenzi času na jeden řádek, jsou to dva bloky. Pod 900 px se mi to sice rozpadne, ale určitě ne jak tobě:
![development_-_writers___gooddata_-_gwc_test___table_out_c-main_products_and_bosch_art_26_sl___mall_cz](https://cloud.githubusercontent.com/assets/215660/8324750/dd7fcbd2-1a53-11e5-87c1-d3a2c58ff18c.png)

**Comment by Halama** [comment]
aha, sakra tak to bylo ještě asi předtím než jsem tu dimenzi dal na nový řádek.

**Comment by Halama** [comment]
Jinak původně to reportoval Martin Lepka tady https://docs.google.com/document/d/1MNKza_owQ9OZiTqN4I9iYBX8vlCeJ-BcCtvB8RPmObc/edit

Možná se to teda spravilo tímhle a můžeme zavřít

**Comment by Halama** [comment]
tak to mám tady https://connection.keboola.com/admin/projects/236/writers/gooddata-writer/Testovaci_2/table/out.c-main.entries

Je tam ale schválně dlouhej název sloupce, možná tohle zatím můžeme odložit.
