### ISSUE TITLE
Clicking on transformation mapping borks the browser

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2001]
There's some special case where clicking on an input mapping freezes the browser so badly that on chrome the tab can't even be destroyed.

Will check out the configuration to see what's up and update here shortly.

**Comment by ujovlado** [comment]
Probably too many options in react-select? I saw similar behavior while going through ex-db-teradata setup (many tables).

**Comment by pivnicek** [comment]
hmm, the configuration looks normal other than having `name`=""

@ujovlado Do you mean that their could be too many tables for the source table selector?

**Comment by pivnicek** [comment]
It's dispatching `TRANSFORMATION_UPDATE_EDITING_FIELD` millions of times

**Comment by pivnicek** [comment]
Interesting that the config row when retrieved from storage has name="", it has a name when presented in the UI

**Comment by ujovlado** [comment]
@pivnicek link to config?

**Comment by ujovlado** [comment]
@pivnicek do you have link to config?

**Comment by pivnicek** [comment]
closing this.  the bug is https://github.com/keboola/kbc-ui/issues/2008

**Comment by ondrejhlavacek** [comment]
Oh, didn't see this one! I always try to link zendesk tickets with github issues (on both ends).

**Comment by pivnicek** [comment]
Yeah, I do too, somehow this one slipped through, no worries.
