### ISSUE TITLE
Update/Remove react-radio group

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2007]
Throws warning which will block us when upgrading to newer React

```
Warning: RadioGroup.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.
```

**Comment by ujovlado** [comment]
@natocTo ked uz updatujes, nekukol by si sa co by sa dalo robit s tymto? :)

Mozno pre zaciatok zanalyzovat co s tym. Ak je to ale jasne, tak mozno rovno PR s updatom (alebo vyhodenim?)

**Comment by ujovlado** [comment]
```
grep src -ire "react-radio-group"
src/scripts/modules/apify/react/Index/TabbedWizard.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/wr-google-sheets/react/components/SpreadsheetTab.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/wr-google-sheets/react/components/SheetTab.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/gooddata-writer-v3/react/components/NewDimensionForm.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/wr-google-drive/react/components/ActionTab.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/wr-google-drive/react/components/FileTab.jsx:import RadioGroup from 'react-radio-group';
src/scripts/modules/transformations/react/modals/ConfigureSandboxModal.jsx:import RadioGroup from 'react-radio-group';
```

**Comment by natocTo** [comment]
Podívám se na to.

**Comment by natocTo** [comment]
Máte nasazenou verzi 1.1.0 a je k dispozici 3.0.3. I nejnovější verze je kompatibilní s Reactem 0.14.

Je to ovšem celé přepsané a musí se teda upravit i kód. Jsou tam tři hlavní změny:

**props value přejmenovaná na selectedValue**
Stačí přepsat a vyřešeno.

**props onChange rovnou vrací value místo event objektu**
Musí se upravit hendler z *e.target.value* na *value*.

**nová Radio komponenta (obyč input wrapper**
Toto je asi největší problém, protože již je použit wrapper on bootstrapu. Napadá mě nová props, něco jako useRadioGroup (bool) u toho vašeho Inputu (react/common/boostrap/Input), kde by se pak vypsal podobný radio input jako doposud, kde ale místé React-boostrap radio inputu by se použit ten z React-radio-group.

Jestli OK tak na to pošlu PR.

**Comment by ujovlado** [comment]
> props value přejmenovaná na selectedValue
> Stačí přepsat a vyřešeno.

Suhlas

> props onChange rovnou vrací value místo event objektu
> Musí se upravit hendler z e.target.value na value.

Suhlas

> nová Radio komponenta (obyč input wrapper
> Toto je asi největší problém, protože již je použit wrapper on bootstrapu. Napadá mě nová props, něco jako useRadioGroup (bool) u toho vašeho Inputu (react/common/boostrap/Input), kde by se pak vypsal podobný radio input jako doposud, kde ale místé React-boostrap radio inputu by se použit ten z React-radio-group.

Tu by som sa vykaslal na ten Input z KbcBootstrap a pouzil rovno `Radio`-> bude to imho cistejsie. Je to na 5 miestach ale nevidim v tom problem. Co ty na to?

**Comment by ujovlado** [comment]
Nebude ale robit problem `react-dom`?
https://github.com/chenglou/react-radio-group/blob/1430fa968b770cfe00dadb93f56a04db6970d8d5/package.json#L49

**Comment by natocTo** [comment]
Nejde o Input z KbcBootstrap, protože jediné co dělá je že načte Input (Radio) z "react-boostrap".

Radio z "react-boostrap" renderuje více než pouze <input />. Takže to tam kopíruji a nahrazuji input za ten Radio input.

Nahradit celý "react-boostrap Radio" tam (common/bootstrap/Input) nemůžu protože "Radio z react-radio-group" musí být obalen komponentou RadioGroup což ne každý Input je. Takže jsem myslel že to vyřeší ta nová props, kde řeknu zda je to obaleno tím nebo není.

**Comment by ujovlado** [comment]
Asi sa uplne nechapeme :) 

Rad by som to normalne pouzil ako:

```js
import {RadioGroup, Radio} from 'react-radio-group';

...
```

**Comment by natocTo** [comment]
No když tam je i ten react 0.14. Tak by mě překvapilo že by to vadilo. Ty dvě věci se navzájem vylučují nebo ne? Plugin jsem zatím nepsal tak nevím přesně jak ty peerDependencies fungujou, zkusím si něco přečíst.
Zkoušel jsem to ale instalovat a použít a fungovalo to.

**Comment by natocTo** [comment]
No problém je že..

```js
import {RadioGroup, Radio} from 'react-radio-group';

<Radio {...props} />
```

**Comment by ujovlado** [comment]
Bavme sa teda konkretnejsie, FileTab.jsx:

```js
<RadioGroup
            name="type"
            value={this.props.type}
            onChange={this.props.onSwitchType}
          >
            <Input
              type="radio"
              label="No"
              help="Create a new File, that will be updated on each run"
              wrapperClassName="col-sm-8"
              value="new"
            />
            <Input
              type="radio"
              label="Yes"
              help="Use existing File"
              wrapperClassName="col-sm-8"
              value="existing"
            />
          </RadioGroup>
```

Sa zameni za:

```js
<RadioGroup
            name="type"
            selectedValus={this.state.selectedValue}
            onChange={this.props.onSwitchType}
          >
            <Radio
              value="new"
            /> No
            <Input
              value="existing"
            />Yes
          </RadioGroup>
```

**Comment by ujovlado** [comment]
K tomu `react-dom`. Maju to tam v `peer-dependencies` aby sa nestalo, ze budes mat nainstalovany `react` alebo `react-dom` viackrat. Obavam sa, ze by sme potom mali 2x `react-dom`.

**Comment by ujovlado** [comment]
Este by boli dalsie moznosti:

- skusit starsiu verziu `2.2.0`
- alebo sa na to vykaslat a vyskladat si to normalne z `react-bootstrap` komponent (t.j. vyhodit `react-radio-group` uplne)

**Comment by ujovlado** [comment]
```
root@22465aa0a300:/code# yarn add react-radio-group
yarn add v1.9.4
warning package.json: No license field
warning kbc-ui@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > coffee-loader@0.7.2" has unmet peer dependency "coffee-script@1.x".
warning " > eslint-loader@2.1.0" has incorrect peer dependency "webpack@>=2.0.0 <5.0.0".
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
warning " > react-radio-group@3.0.3" has incorrect peer dependency "react-dom@>=15.5.4".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ react-radio-group@3.0.3
info All dependencies
└─ react-radio-group@3.0.3
warning kbc-ui@0.0.0: No license field
Done in 7.22s.
```

^ 
```
warning " > react-radio-group@3.0.3" has incorrect peer dependency "react-dom@>=15.5.4".
```

**Comment by natocTo** [comment]
Tady na tom odkazu: https://nodejs.org/en/blog/npm/peer-dependencies/

Se píše:
> UPDATE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. For all following versions of npm (starting with npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.

A u Yarnu je přepínač --peer který asi tyto závislosti instalují asi, jinak se samy neinstalují.

**Comment by natocTo** [comment]
Podle mě to je protože React udělal novou knihovnu. Normal se zadává třeba to >2.0.0 || <5.0.0. Ale jakmile React rozdělil knihovnu na React a React-dom tak je složité to tam zadat. 

Můžu zkusit poslat PR co mám připravené ať koukneš jak to vypadá.

**Comment by natocTo** [comment]
Verzi 2.2 jsem zkoušel a je tam stejný problém jako ve 3.0.3, ikdyž je to implementované trošku jinak.
Jinak react-radio-group se mi líbí, protože nemusíš vše opakovat u každého inputu, jako onChange a zda je selected nebo ne.

**Comment by ujovlado** [comment]
Este sa teda opravim. Nebude to tam 2x, akurat `react-radio-group` moze vyzadovat nieco s react-dom 15 a my mame 14.

**Comment by ujovlado** [comment]
No, typek tam pouziva stare context api vyzera to tak
https://github.com/chenglou/react-radio-group/blob/1430fa968b770cfe00dadb93f56a04db6970d8d5/index.jsx

**Comment by natocTo** [comment]
Já jsem teď musel odjet, ale navečer pošlu PR kde bude vidět vše upravené a bude lehčí se rozmyslet co s tím.

**Comment by ujovlado** [comment]
Fixed in #2016
