### ISSUE TITLE
Python / R transformations - show already installed packages

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2015]
https://keboola.zendesk.com/agent/tickets/9099

uživatel neví, který packages už jsou nainstalovaý, pokud jich je málo, tak rovnou vypsat, pokud víc, tak link do dokumentace?

@odinuv nebude stačit link na tohle? https://github.com/keboola/docker-custom-python/blob/500f8562d17501c68a24b76ae41e90ac10fd54e4/Dockerfile#L24-L41

pro tu `python-docker-application` by to ale chtělo zase link dál...

**Comment by odinuv** [comment]
> pro tu python-docker-application by to ale chtělo zase link dál...

 to nechapu

**Comment by odinuv** [comment]
nechapu to porad stejne, co s tim co ma `python-docker-application` ?

**Comment by odinuv** [comment]
je to nas package - treba na vytvareni manifestu

**Comment by ondrejhlavacek** [comment]
no jasně, ale uživatel ho v transformaci může použít, ne?

**Comment by odinuv** [comment]
furt nechapu z ceho bude uzivatel zmatenej a co dal linkovat

**Comment by ondrejhlavacek** [comment]
protože je instalovaná z nonpypi repa. představuju si, že bude mít někde napsanej seznam knihoven, když bude chtít vědět, jak funguje, hodí to do pypi searche a najde ji - ale ne tu naši.

**Comment by odinuv** [comment]
vubec to nechapu o co ti jde :) tuhle knihovnu do transformaci nainstalovat stejne nemuzes (prave proto, ze neni pypi), je proste naste "interni" a je to uz soucast transformaci a to je vsechno, vubec to imho s instalaci packagu nema co delat

**Comment by ondrejhlavacek** [comment]
ok, nechám to bejt :-)

**Comment by odinuv** [comment]
docs fixed in https://github.com/keboola/connection-docs/commit/d54ce0015f2fa9aad8db124569d339f4caef9c23

**Comment by ondrejhlavacek** [comment]
je něco takovýho i v Rku? v Dockerfilu jsem nic nenašel

**Comment by odinuv** [comment]
esteze jsem to nalinkoval https://github.com/keboola/connection-docs/commit/d54ce0015f2fa9aad8db124569d339f4caef9c23#diff-938e21be15768ab0619f5d2756898ff9L43 :)
