### ISSUE TITLE
support sydney region

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2030]
podla search `eu-central-1`(https://github.com/keboola/kbc-ui/search?q=eu-central-1&unscoped_q=eu-central-1)

by sa mal pridat region do:
- ex-storage
- wr-storage
- data takeout

ostatne(provisioning, gd writer) uz je poriesene

**Comment by ujovlado** [comment]
az sa to prida, potom by to chcelo dalsi PR, kde sa tieto konstatny tykajuce regionu hodia do jedneho suboru a vsetky ostatne si to odtial potiahnu. Pridanie dalsieho regionu potom bude otazka zmeny v jednom subore.
