### ISSUE TITLE
DB ex - netestuje credentials

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#204]
pokud vyplním credentials v DB-ex (MySQL) a dám test, dostanu faile - tvrdí to, že to není uložené. Pokud dám save a pak to otevřu znovu, test projde.

**Comment by Halama** [comment]
to je divný fakt se ti to chová takhle?

**Comment by Halama** [comment]
zjistil jsem že test credentials nefunguje vůbec na backendu :( ale to ui to předává správně i v rozeditovaném stavu

**Comment by Halama** [comment]
jednu věc ale vidím, nepošle to driver

**Comment by Halama** [comment]
omg. koukám že tam úplně chybí pole database

**Comment by Halama** [comment]
miro fixnul na backendu
