### ISSUE TITLE
[ex-db-generic] show data types of columns

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2040]
When selecting columns it would be helpful to see what datatype they are.  
That information is available already, it's a question of how to display it.  
In the select box as part of the item label would be my guess.

**Comment by janmichek** [comment]
The only visual style for datatype information i know about can be found in IM.
![image](https://user-images.githubusercontent.com/15363559/45618604-9005b300-ba76-11e8-90f3-af90b4e6484e.png)

Which does not look nice inside select option. Too colorful imho.
![image](https://user-images.githubusercontent.com/15363559/45618689-e2df6a80-ba76-11e8-9958-cb2bf1871411.png)

We also use this 'code' style for more entities.

So the minimalistic version could be plain - boxy brackets
![image](https://user-images.githubusercontent.com/15363559/45619485-bed15880-ba79-11e8-8f45-492c7f2d0044.png)

@pivnicek What do you think?

**Comment by pivnicek** [comment]
@janmichek I think that will be perfect! Thanks!
