### ISSUE TITLE
Tokens: reload after refreshing own token

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2042]
Když refreshnu vlastní token, přestena UI šlapat. Mohlo by to třeba rovnou reloadnout celou stránku.

**Comment by natocTo** [comment]
Při lokálním vývoji se nepracuje pod vlastním emailem koukám. Ani tam není ten label "Yours". Tak jak poznat, že obnovuji vlastní token.

**Comment by natocTo** [comment]
Jo dík. Ale i tak každý kdo chce měnit token na localhostu by musel měnit ten email. Což už je skoro stejné jako pak znovu zadat tu url po obnovení tokenu.
Nevím zda to chápu teda dobře.

**Comment by ujovlado** [comment]
Vysvetlim. Ide o produkciu.

Ked sa prihlasis do KBC tak (zjednodusene povedane) do stranky ti je vlozeny tvoj master token (ten s labelom `Yours`.

Ked pojdes do `https://connection.keboola.com/admin/projects/XXX/tokens` a tento token refreshnes, prestane ti slapat UI (kbc-ui), lebo ten vlozeny token prestane byt validny. A rozbehne sa to az ked refreshnes stranku.

**Comment by ujovlado** [comment]
Je tam nieco taketo, pride to zo servera, normalne v HTML stranke

```html
<script>
kbcApp.start({
   "data": "..."
   "rootNode": document.getElementById("kbc-main-app"),
   "locationMode": "history"
});
</script>
```
a niekde na konci v `data`, by si nasiel ten token.

**Comment by ujovlado** [comment]
a ked refreshned token, tak to nijako neovplyvni to, co je v `data`.

**Comment by ujovlado** [comment]
Ale ked tak nad tym uvazujem, nemuselo by to refreshovat stranku asi :)

**Comment by ujovlado** [comment]
Asi by stacilo ak application store zareaguje na refresh tokenu.

**Comment by ujovlado** [comment]
Poriesi sa v https://github.com/keboola/kbc-ui/issues/3620
