### ISSUE TITLE
Apify - SetupModal - Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2052]
https://sentry.io/keboola/keboola-connection-ui/issues/691269715/

```
TypeError: Cannot read property 'find' of undefined
  at Array.forEach (<anonymous>)
  at HTMLDocument.nrWrapper (/admin/projects/5055/jobs/445987210:5:11770)
```

**Comment by natocTo** [comment]
Nastane tak při pokusu editace nastavení.

https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/apify/react/Index/SetupModal.jsx#L69

```js
this.localState(['crawlers', 'data'])
```

Je v tuto chvíli undefined. Proto nejde volat "find". V tuto chvíli budou asi parametry dostupné v "paramsToSave" a mohli by se vzít tam.

**Comment by kacurez** [comment]
apify ui som robil ja, pozriem sa nato, dik za report

**Comment by ujovlado** [comment]
mozno by som pockal co povie @natocTo, ci to nahodou nefixuje :)

**Comment by ujovlado** [comment]
(ja to teda neriesim)

**Comment by natocTo** [comment]
Já se pak věnoval něčemu jinému a pak byl oběd. Tak to neřeším.

**Comment by kacurez** [comment]
ok pozriem sa nato
