### ISSUE TITLE
Transformations - Compare latest with only create event

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2064]
Pokud si založím novou transformaci, tak mám pouze jednu "událost" (Created transformations..).
Již v tuto chvíli je možnost kliknout na tlačítko *Compare latest*. Tam to chce vzít poslední dvě události a udělat diff. Existuje však pouze jedna, takže to dopadne takto.

1) Odešle se GET požadavek ve tvaru: "../versions/undefined" - vrátí to 404
2) Zobrazí se modal, kde je pro 2 stav: "#undefined (No description) a few seconds ago by unknown"

![transformations](https://user-images.githubusercontent.com/12331181/45805843-e1ed4980-bcbf-11e8-972d-2a719aa8f52e.png)

![undefined](https://user-images.githubusercontent.com/12331181/45805403-03016a80-bcbf-11e8-8fc3-8b5047a1c356.png)

Asi hned každý udělá nějakou další akci a tak se k tomuto stavu nedostane, ale i tak by se mohl opravit.
Napadají mě dvě řešení.

1) Pokud nemám alespoň 2 události nezobrazím vůbec "Compare Latest" tlačítko - nevím jak moc špatný to z hlediska UX je.
2) Daná komponenta má disabled stav. Takže bych mohl přidat stejnou podmínku a přepnout komponentu do stavu disabled. Tím pádem tam nic nebude mizet. Zase ten stav disabled není úplně jasný. Protože mi to neříká nic o tom proč je disabled, jen to prostě nic nedělá.
3) Modal zobrazit, ale vyřešit nějak ty texty (diff objektů mi přijde ok, ten text s undefined už tolik ne).

**Comment by janmichek** [comment]
Jo souhlas, dobrej postreh. Nejoptimalnejsi mi   ripada tvuj navrh c.1.
Tahle komponenta je taky zrala na zdokumentovani v Indigu.

**Comment by ujovlado** [comment]
@natocTo pls nepriraduj tie issues, nemusia to vzdy riesit ludia ktorych vyberes. Naopak, ked chces upozornit, mention mi vobec nevadi.

**Comment by natocTo** [comment]
Ok.

Jinak tu variantu č.1 můžu teda připravit.

**Comment by ujovlado** [comment]
Jo, priprav tu 1ku ... vo vypise verzii takisto nie je moznost porovnat jedinu verziu s "nicim".
