### ISSUE TITLE
Transformace: zarovnat input pole v editaci

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#207]

**Comment by ondrejhlavacek** [comment]
@JakubMatejka Jakube, můžu poprosit o pomoc? Jde o zarovnávání input fieldů a okolních elementů na jednu linii. Trochu tápu :-(

a) Description nelícuje (a nebo spíš opačně - nelícují ty dva řádky nahoře) 

https://connection.keboola.com/admin/projects/232/transformations/bucket/sys.c-tr-testsuite/transformation/mysql

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_mysql](https://cloud.githubusercontent.com/assets/497675/8318212/b4f9b5ac-19b7-11e5-85af-c7475b079df1.png)

b) Nelícují selectboxy a nápověda dole v detailu input mappingu

https://connection.keboola.com/admin/projects/232/transformations/bucket/sys.c-tr-testsuite/transformation/mysql

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_mysql](https://cloud.githubusercontent.com/assets/497675/8318194/98cf8a28-19b7-11e5-9817-7fa0dec5a4c1.png)

c) Obdobná situace v jiné transformaci

https://connection.keboola.com/admin/projects/232/transformations/bucket/sys.c-tr-testsuite/transformation/redshift

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_redshift](https://cloud.githubusercontent.com/assets/497675/8318260/174e2850-19b8-11e5-941b-e82a57e61938.png)

d) editované input / output mappingy mají dole moc velkej padding imho

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_redshift](https://cloud.githubusercontent.com/assets/497675/8318286/3307b28c-19b8-11e5-8d3e-ba5d4b1c8cfb.png)

e) celkově je ten rozpal mezi položkama formu moc velkej - obzvlášť mezi malejma inputama by mohl bejt o dost menší

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_redshift](https://cloud.githubusercontent.com/assets/497675/8318319/627fa808-19b8-11e5-966c-7562c06bacf1.png)

f) input type `number` nereaguje na velikost (libovolný input mapping)

![ondra_s_sandbox_-_transformations___bucket_sys_c-tr-testsuite___transformation_redshift](https://cloud.githubusercontent.com/assets/497675/8318336/7c3b12be-19b8-11e5-8e9c-3ce51ae58d6e.png)

**Comment by JakubMatejka** [comment]
a) - c) Hotovo
d) To je margin-bottom patřící tomu poslednímu `.form-group`. Vyselektoval jsem to jako '.panel-body > div > .row:last-child > .form-group' ale nevím jestli to zahrne všechny výskyty.
e) Nejsem si jistej co máš na mysli, rozpal je vyrovnání mezer mezi písmeny. ;o)
f) A co s tím chceš dělat? V Bootstrapu se tomu nastavuje padding i height přes `.form-control[type="number"]`, tak to je potřeba přetížit

**Comment by ondrejhlavacek** [comment]
Díky moc!

e) nemyslel jsem kerning, ale hromadu vertikálního bilýho prostoru
f) šlo by to přetížit v kbc-bootstrap? nebo se do toho mám pustit sám?

**Comment by JakubMatejka** [comment]
e) kerning je česky rozpal. ;o) Mně došlo co tím asi myslíš ale nevím kde se ti to nezdá. Mně přijde že jsou tak akorát - jestli teda právě myslíš tyhle:
![development_-_transformations___bucket_sys_c-tr-testsuite___transformation_mysql](https://cloud.githubusercontent.com/assets/215660/8350262/224739dc-1b24-11e5-9886-94ca83841b0a.png)

f) hotovo. Už jsem pochopil co s tím chceš vlastně udělat ;o)

**Comment by JakubMatejka** [comment]
Tak už jsem to asi pochopil. ;o) Stačí?
![development_-_transformations___bucket_sys_c-tr-testsuite___transformation_mysql](https://cloud.githubusercontent.com/assets/215660/8350395/9bb3820c-1b25-11e5-86fe-d5ad7309714d.png)

**Comment by ondrejhlavacek** [comment]
Super, díky!
