### ISSUE TITLE
Transformations - query parser

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2075]
It it unable to split this queries:

```sql
CREATE TABLE "arr_test" ("id" int, "nodes" text);

INSERT INTO "arr_test" VALUES (2, '{1,2}');
INSERT INTO "arr_test" VALUES (3, '{1,2}');
```

**Comment by natocTo** [comment]
Zkouším to teď na u sebe a rozdělilo mi to na 3 query. Nebo jak nasimuluji ten problém?

**Comment by ujovlado** [comment]
Hm, fici to aj mne. Prave rozmyslam, ci to nesuvisi nejako s tym workerom.
