### ISSUE TITLE
Transformation - bad tooltip placement for name edit input

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2081]
![transformation](https://user-images.githubusercontent.com/12331181/45939743-2ab14500-bfd5-11e8-8177-b14d65034df3.png)

Jde o typo, pošlu PR.

**Comment by janmichek** [comment]
Dik za fix, kdyz to leze takhle mimo viewport, tak je to blby. 
Jenom dodam ze nam chybi koncept na tooltipy, titly, hinty, helpy - pouzivame to ruzne.
