### ISSUE TITLE
Transformace: zmenšit editaci

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#209]
zkusit menší inputy / labely

**Comment by Halama** [comment]
Tam některé inputy zůstaly úmyslně velké? Nastavil bych je všechny stejně malé

**Comment by ondrejhlavacek** [comment]
Jo, vždycky ty hlavní / povinný

**Comment by Halama** [comment]
myslel jsem jestli by nebylo lepší aby všechny byly menší ale vlastně je to asi ok. Uvidíme co na to ostatní.
