### ISSUE TITLE
TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2114]
https://sentry.io/keboola/keboola-connection-ui/issues/709227182/

Move task between phases - press "DELETE" in react-select.

**Comment by ujovlado** [comment]
@natocTo nechcelo by sa ti kuknut toto? V orchestraciach vidim 2x pouzity react-select. 

1. MergePhasesModal
2. MoveTasksModal

Problem nastane, ked si vyberas phase a stlacis delete.

Ak by si nevedel, kde sa to nachadza v UI, popisem viac.

**Comment by natocTo** [comment]
Poslal jsem PR. Mířící teda pouze na ty dva selekty v těchto dvou komponentách.
