### ISSUE TITLE
Transformations - Index table CSS 

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2122]
1) Při kliknu na řádek transformace se mi odroluje dolů detail, ale hned naskočí dole slider.
2) Při kliknu na řádek transformace se mi odroluje dolů detail, kde naskočí 20px margin botom a odskočí border-bottom.

![connection keboola com_admin_projects_5194_transformations](https://user-images.githubusercontent.com/12331181/46410173-2ba24f00-c718-11e8-95d2-b2ffa9865ee2.png)

Oprava:
1) Tam je asi "typo" v CSS pošlu PR
2) Tady nevím zda to můžu obecně upravit tak, aby table neměl margin-bottom 20px. Ale zdá se mi to moc agresivní (mohlo by to ovlivnit něco jinde). Nebo zda tam přidat nějakou třídu a stylovat tu.

**Comment by ujovlado** [comment]
Ta 1. cast je sposobena:

```css
.kbc-main-content {
    overflow: auto;
}
```
... tusim som to tam kvoli nejakemu bugu pridaval ja (skus ked tak dohladat v indigo-ui)

2. netrufam si povedat, ci to potom bude vyzerat vsade ok.

**Comment by natocTo** [comment]
1) poslal jsem PR do Indigo.
2) Asi půjdu cestou nové třídy. Uvidím jak to bude působit.
