### ISSUE TITLE
Data sample cannot be displayed. Too many columns.

### ISSUE THREAD

**Issue by jirigrill** [keboola/kbc-ui#2129]
Is it possible to increase limit of displayed columns? In our business we have a lot flat tables which have over 100 columns.
<img width="901" alt="screen shot 2018-10-05 at 16 33 03" src="https://user-images.githubusercontent.com/12986457/46527937-b3c15980-c8bc-11e8-9a29-0e1f9fb27545.png">

**Comment by janmichek** [comment]
Related issue https://github.com/keboola/connection/issues/1529

**Comment by natocTo** [comment]
Také zavírám, ten limit byl tuším o dost navýšen.
