### ISSUE TITLE
Version buttons - copy / diff

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2130]
Koukám na issue #2070 
Ještě než jsem začal, tak mi přijde, že tam ty ikonky jsou nějak pomíchané. 

![copy](https://user-images.githubusercontent.com/12331181/46603057-43038280-caf2-11e8-910b-f093f2b34f32.png)
![diff](https://user-images.githubusercontent.com/12331181/46603058-43038280-caf2-11e8-8303-d3b95d698cfa.png)

Nejsou ty ikonky naopak? Pro ty dva listy bych předpokládal kopírování, a tam taková ta ikonka "git tree" bych čekal ten diff. Pokud to je vážně naopak, tak připravím PR. Ale ono to možná dává smysl i jak to je teď..

**Comment by janmichek** [comment]
Zajimavy postreh, dava to docela smysl co pises.
Tohle jsem teda netvoril ja, prisel jsem k hotovymu - takze si to vysvetluju po svym takhle:
Akce 'Compare with ...' - ve FA koukam neni zadny symbol pro 'diff' nebo 'compare'. Nejbliz je tomu ta ikona kterou vidis.
Akce 'Copy to new...' je jakoze rozvetveni, prestoze jde o linearni strukturu.
Asi to jde cestou nejmensiho zla, protoze neni moc na vyber. Ultimatni reseni by bylo, kdybychom si ikony nakreslit sami 😉 coz momentalne nevim jestli je mozny.

**Comment by janmichek** [comment]
Nebo mi pomoz najit vhodnejsi symboly pro akce ktery vidis.

**Comment by natocTo** [comment]
Já právě asi dříve viděl třeba tuto stránku:

![credentials](https://user-images.githubusercontent.com/12331181/46618570-28e09900-cb20-11e8-8a9e-79c45488e44c.png)

Kde je stejná ikonka jako tam, ale tu složí jako kopírování.

**Comment by janmichek** [comment]
Jasne, ta ikona vypada i se snad jmenuje 'copy'.

**Comment by natocTo** [comment]
Asi teda zavírám. Ikonky tam lepší asi moc nebudou no. A jen je prohodit by asi přineslo dost zmatků pro současné uživatele.

**Comment by ujovlado** [comment]
a co https://fontawesome.com/v4.7.0/icon/exchange ?

**Comment by ujovlado** [comment]
Pozerem napr. na php storm, ma to tak:

![screenshot_2018-10-25_09-50-14](https://user-images.githubusercontent.com/419849/47484278-9b998600-d83b-11e8-9d8a-daf1661e79a4.png)

**Comment by natocTo** [comment]
Pro jakou akci? Už asi podezřelé že se musím ptát a hned mě to netrkne. 

Mě akorýt přišlo že takový ta COPY ikonka je tak zažitá pro kopírování, že mi přišlo divné že tu složí pro diff no.

**Comment by ujovlado** [comment]
Pre diff.

**Comment by natocTo** [comment]
Pokud by to uvolnilo tu druhou ikonku pro kopírování tak jsem pro.
Mohlo by mrknout více lidí a říci co dává největší smysl pro danou akci.

**Comment by ujovlado** [comment]
Tu "copy" by som zachoval asi vyhradne na skopirovanie dos schranky - t.j. na "copy to new version" by ostal "fork".

**Comment by natocTo** [comment]
Tak to znovu otevřu. Než se to ujasní. Já se tu zeptal, dostal jsme i odpověď, nikdo jiný to nekomentoval, tak jsem myslel, že to příjde divné jen mě.

**Comment by natocTo** [comment]
Jo, když si to takto popsal, že to je vlastně jiná akce tak to dává smysl. A zmizla mi ta zažitá ikonka na zkopírování do schránky tu.

**Comment by ujovlado** [comment]
Jo, to je v poriadku. Si v tom produkte novy, je prave vitane, ze ti veci nesedia/nepacia sa ti. Ked uz budes na to zvyknuty, vobec ti to netrkne (lebo budes vediet, ze kliuknutim na copy zobrazis diff :-D )

**Comment by ujovlado** [comment]
Ked si das vyhladat `fa-files`, tak uvidis, ze je to len pri tych diffoch ... Podobne `fa-copy` je len v clipboarde. Takze ked posles PR, ktory tie `fa-files` zameni za ikonky diffu, myslim, ze to tam mozeme poslat a nic nepokazime ;)

**Comment by natocTo** [comment]
Dobře

**Comment by janmichek** [comment]
Myslim si, ze nejlepsi by bylo, kdyby nam na to Jack vysmrknul za par minut konkretni ikonu a nemuseli jsme vybirat nejmensi zlo z font awsome. Podobne jako Sandbox, nebo mappingy

**Comment by janmichek** [comment]
No psal jsi, ze si na to vyhradis zas a podivas se na muj navrh reseni, tak na to porad cekam .] Ja v tom mam celkem jasno

**Comment by ujovlado** [comment]
Ano, je tam na to issue/pr, stale to plati.
