### ISSUE TITLE
Přidání transformace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#214]
Dost mě mate, že když kliknu na tapi bucket, tak musím do jeho detailu 

![image](https://cloud.githubusercontent.com/assets/1427901/8305146/673499e6-19ac-11e5-9ef8-044637385d67.png)

a tam teprve můžu přidat transformaci. Co tu ikonku ">" v pravo nahradit "+" a tím do bucketu zakládat transformace?

**Comment by Halama** [comment]
jo udělám to dnes, jsem na to taky narazil. Přidám tam navíc to +
