### ISSUE TITLE
Get rid off support email

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2142]
replace by ZD widget
https://github.com/keboola/kbc-ui/search?q=%22support%40keboola.com%22&unscoped_q=%22support%40keboola.com%22

**Comment by ujovlado** [comment]
ASi nie je nutne aby kazdy z tych emailov bol nahradeny za "zendesk button". Mozno by stacilo len lepsie formuloavat, ze maju pouzite support button dole vlavo.

**Comment by ujovlado** [comment]
Pretoze ostatne komponenty nic taketo nemaju.

**Comment by janmichek** [comment]
aha, zatim jsem to neprojizdel, ted na to koukam. Zmenim dle kontextu.
Textovym navodum zmenit text, aktivnim prvkum zmenit akci.
