### ISSUE TITLE
missing description in orchestration tasks

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2152]
description:
![image](https://user-images.githubusercontent.com/4319320/46850447-3f267780-cdf4-11e8-9ed3-7d56b3169592.png)

description:
![image](https://user-images.githubusercontent.com/4319320/46850455-48afdf80-cdf4-11e8-93f4-144ce28aefdd.png)

description:
![image](https://user-images.githubusercontent.com/4319320/46850467-57969200-cdf4-11e8-921b-3ae37ff4b51a.png)

no-description:
![image](https://user-images.githubusercontent.com/4319320/46850480-68df9e80-cdf4-11e8-80d4-1934e1c4317c.png)

**Comment by janmichek** [comment]
ok, podivam se na to + se nechapu proc je jedna z tech descritpionu UPPERCASE. To taky poresim

**Comment by natocTo** [comment]
Koukám jak se to získává na detailu a vypadá to cca takto:

```js
InstalledComponentsStore.getConfig('orchestrator', orchestration.get('id').toString()).get('description')
```

Tak třeba tě to navede.
