### ISSUE TITLE
missing component type in orchestration tasks

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2153]
there is no way to tell whether mailchimp is writer or extractor:

![image](https://user-images.githubusercontent.com/4319320/46850690-27032800-cdf5-11e8-8a7e-a64e16418cce.png)

**Comment by natocTo** [comment]
@janmichek máš nápad jak to tu odlišit? První co mě napadne je použítvat pouze ty "default" obrázky zde. Ale je to asi radikální.
