### ISSUE TITLE
orchestration job display

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2156]
all fields are shown:

![image](https://user-images.githubusercontent.com/4319320/46869041-cc84be80-ce2a-11e8-801d-6ca77e39afe0.png)

show only the fields displayed in jobs:

![image](https://user-images.githubusercontent.com/4319320/46869073-e3c3ac00-ce2a-11e8-9dcd-54953139feb2.png)

things like `_index`, `lockname`, etc... have no place in the UI

**Comment by natocTo** [comment]
Tak u těch tasků v orchestraci taky zobrazit pouze ty "response.params" pokud jsou?
Jaký by byl v tom případě nadpis? Aby to tam nebylo "Parameters" a "Parameters".
Ještě přejmenuji "Params" v jobech na "Parameters" aby to bylo stejné.

**Comment by odinuv** [comment]
to, co je v parameters je to stejny, co je v params

**Comment by odinuv** [comment]
hm, to nedava smysl ta veta :), takhle: 

![image](https://user-images.githubusercontent.com/4319320/47289870-0b6dfd80-d5fd-11e8-8396-c24edcf2a393.png)

**Comment by natocTo** [comment]
Taky jsem viděl. Ale to první jsem myslel že se pojí k tomu endpointu nad tím. Tak aby to nemátlo že se tam posílá i mode apod. 

Nebo právě nevím zda existuje nějaký "valid" response objekt který bych mohl vytvořit a udělat tam nějaký průnik, aby se z response objevilo jen to co by mělo.

**Comment by odinuv** [comment]
udelal bych to co nejstejneji jako je to u jobu, anebo mozna radikalni myslenka - celej ten response vyhodit a nechat tam jen stava proklik na detail jobu?

**Comment by natocTo** [comment]
Já právě koukal na ten screen výše z Jobu a tam jsem viděl ty Parameters stejné jako jsou v tom reponse.params. Proto jsem to chtěl použít. Nebo co konkrétně znamená stejně jako v Jobs.

Rozhodnutí zda to půjde úplně pryč asi není na mě :) nevím zda sem někoho nepřihodit, kdo toto může rozhodnout.

**Comment by Halama** [comment]
klidne bych ten response vyhodil, taky se nad tim obcas zarazim. Takove low level vei jsou tam k nicemu.

**Comment by natocTo** [comment]
Tak připravím PR.
