### ISSUE TITLE
TAPI UI - napovídání

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#216]
nenapovídá to buckety, který existujou, ale neobsahujou tabulky

**Comment by Halama** [comment]
to je hádám feature, hledá to i v  bucketech, jejich description a všem

**Comment by padak** [comment]
tomu nerozumím - mám buckety a ty mi to nenašeptává - to je feature? :)

**Comment by Halama** [comment]
sakra nevsiml jsem si toho ne na zacatku nenapovida :)

**Comment by padak** [comment]
budu víc používat formátování :-)


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by Halama** [comment]
co vlastně myslíš tím napovídáním?

**Comment by Halama** [comment]
nějak mě to zmátlo a zkoumal jsem filtrování v seznamu transformací

**Comment by padak** [comment]
shit, nepopsal jsem to dobře!

napovídání při výběru output mappingu:
![image](https://cloud.githubusercontent.com/assets/1427901/8307628/d6b35bbe-19bf-11e5-92af-937232738db2.png)

(pokud je bucket prázdný - což na začátku často je - tak ho to neukazuje)

**Comment by Halama** [comment]
ono to totiž ukazuje jenom tabulky. Ten bucket chápu teda tak že by sis ho předvybral a za to dopsal jméno tabulky. Tohle nechám asi na najloše jestli to nevymyslí nějak lépe.

**Comment by padak** [comment]
Rozumím! No novej output mapping vždy děláš do neexistující tabulky. Takže
já vybírám existující tabulku a pak edituju je  její jméno

Sent from mobile
Dne 23. 6. 2015 4:06 PM napsal uživatel "Martin Halamíček" <
notifications@github.com>:

**Comment by ondrejhlavacek** [comment]
Dávalo by teda smysl tam mít i buckety?

**Comment by padak** [comment]
Imho jo

Sent from mobile
Dne 23. 6. 2015 6:02 PM napsal uživatel "Ondřej Hlaváček" <
notifications@github.com>:
