### ISSUE TITLE
Don't allow refresh of other people's master tokens

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2166]
In API Tokens an admin can refresh any token, but he should only be able to refresh his own or non-user tokens.

**Comment by ujovlado** [comment]
Is this really needed? AFAIK all users in a project has same level of permissions. You can remove any user from project and any user can remove you.

**Comment by ujovlado** [comment]
This is not needed. No need to disable token refresh if I can remove user from project completely.

**Comment by pivnicek** [comment]
mmt,  removing a user and refreshing the token are completely unrelated actions.

The issue here is impersonation.  I can refresh someone else's token and then use it to do any number of operations which all get logged as done by the other user.  I don't see how deleting a user has anything to do with this issue

**Comment by pivnicek** [comment]
Granted this issue may be more appropriate for the backend to solve

**Comment by ujovlado** [comment]
> removing a user and refreshing the token are completely unrelated actions.

Yes they are. I just mentioned it because if I want to piss user, I just remove him from project. :) Anyway, disabling refresh in UI still doesn't solve it. I can to it through API.

> Granted this issue may be more appropriate for the backend to solve

Yes, if this will not be supported on backend, we can remove it.

**Comment by ujovlado** [comment]
> but he should only be able to refresh his own or non-user tokens.

But you still didn't explain why. :) That's why I asked it it's needed. Users are on same level of permissions.

**Comment by pivnicek** [comment]
@ujovlado pls see https://github.com/keboola/connection/issues/1572
