### ISSUE TITLE
orchestrations - notifications - weird spacing

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2167]
![image](https://user-images.githubusercontent.com/4319320/46945792-1ca39100-d076-11e8-99a0-f67bd6d2610c.png)

the end of the edit field is unusuable

**Comment by natocTo** [comment]
Na toto bych se podíval více ze široka, když jsem si to rozkliknul.

@ujovlado @janmichek Tady bych se zeptal i Vás zda budou změny průchozí. 
1) Samo bude fajn upravit ten input aby tam nebyl ten padding 70px, respektive tam hodit tu ikonku. Koukám že jde o komponentu: common/ItemsListEditor která je použita pouze tu, dříve si nebyla protože má jiné default props apod ale teď je pouze tu. Je to podobná komponenta jako ty kde edituji popis nebo edituji název třeba writeru. Proto asi kulatý button apod. Myslím že by to ani takto kulatý být nemusel ale to je jiná. Spíše jen upravím ten základ + připravím to na tel (místo col-xs-4 předělám třeba na col-xs-12 col-sm-4 apod).

2) Pro přidání emailu by měl fungovat také enter. Přidal bych teda form.

3) Zvolené emaily se nečtou moc dobře. Myslím že by tam byla lepší jiná barva pozadí. Zkusím poslat jak vypadají defaul barvy z bootstrapu.
![emails](https://user-images.githubusercontent.com/12331181/46950730-06053600-d086-11e8-94d3-9a981ab7292f.png)
Myslím že modrá se čte nejlépe, nevím zda to sedí do ui, červená asi není ideální, dal jsem tam dolů i současnou pro porovnání.

4) Ikonka na mazání (cup) emailu taky není moc vidět a ani jsem neveděl co to udělá, přidal bych tam title + možná zkusit jiné ikonky.

5) Celkově ty emaily bych udělal vetší, tem tam je velikost pouze 10.5px.

**Comment by natocTo** [comment]
Tady budu řešit pouze 1ku ať v tom je pořádek. Ale zajímalo by mě i to ostatní.

**Comment by natocTo** [comment]
Původní

![now](https://user-images.githubusercontent.com/12331181/46952749-0f919c80-d08c-11e8-8548-39a81551af88.png)


Kdybych přidal několik CSS (nevím zda indigo nebo někam sem): Verze i s textem, případně bez ikonky.

![new1](https://user-images.githubusercontent.com/12331181/46952586-8f6b3700-d08b-11e8-857f-d8e9acd076e1.png)

![new2](https://user-images.githubusercontent.com/12331181/46952640-bb86b800-d08b-11e8-95ba-cf348f513dab.png)

![new3](https://user-images.githubusercontent.com/12331181/46952691-e113c180-d08b-11e8-81ec-93961b2fc70f.png)

**Comment by janmichek** [comment]
Diky za analyzu, ja bych se s tim kdovijak neparal, jenom bych to fixnul, at to nevypada 'rozpadle'. Cely je to zraly na nejaky redesign
Nemame v indigu zadnou UI komponentu, ktera by na to 100% sedla.
Kdybys tomu chtel dat nejakou jednotu, tak asi nejpodonejsi je tomu koncept New [entity] -> conf modal ->Create [entity], ktery obsluhuje pridavani entit.

**Comment by janmichek** [comment]
Btw proc vlastne ta inlineEditTextarea neni v Indigu, jako komponenta, kterou znovupouzivame?

**Comment by natocTo** [comment]
Modal apod bych tam nedával. Je to jednoduchá úloha a chci jít udělat co nejvíce přímo, navíc to vše pak musím ještě jednou uložit.

V tom issue tu bych primárně taky řešit ten problém s paddingem. Ale nebylo by špatný to trošku upravit i teď. Zabere to hodinku a zlepší to UI (třeba to odesílání enterem).Tady bych právě upravil CSS jen (jde asi o 10css pravidel). Přidal bych less soubor tu aby se to teda nedostalo do indigo (zbytečně) když pak bude třeba redesign. Plus to obalil formem. Nic víc.

**Comment by natocTo** [comment]
> Btw proc vlastne ta inlineEditTextarea neni v Indigu, jako komponenta, kterou znovupouzivame?

Vidím akorát toto připravené: https://github.com/keboola/indigo-ui/pull/271/files
Textarea pak bude obdobná.

**Comment by odinuv** [comment]
@janmichek na redesign je to zraly uz rok a je v nedohlednu, takze bych se celkem priklanel k tomu to trosku vylepsit (pokud to neni nekolik dni prace)

**Comment by janmichek** [comment]
https://github.com/keboola/indigo-ui/pull/271 OK
Nevim no, muze zacit vznikat koncepcni schyza, spis chceme sjednocovat.
Vytvoreni Orchestrace je taky jednoducha uloha, obslouzena stavajicim konceptem. Snazim se nam jen usetrit praci.

**Comment by janmichek** [comment]
Jako prijde mi to dobry co navrhujes, vim ze na vice mistech by bylo fajn jednodussi pridavadlo, ale chtelo by to nejdriv najit ty vyskyty, zanalyzovat, navrhnout, implementovat.

**Comment by natocTo** [comment]
Já to právě asi nepochopil s tím modalem.
Tady jako fix bych přidal třídu "kbc-inline-edit-compact" a přidal 6 css pravidel.
Plus ten form okolo. Tato komponenta je v současnosti pouze tu nikde jinde.

Velikost emailů a jejich pozadí bych založil třeba nové issue a vidělo by se jaká to je priorita.

**Comment by janmichek** [comment]
Ok, posli PR .] Navrhuju fixnout jen ten rozpadly vzhled. Do ovladani pridavani bych zatim nijak nevrtal.

**Comment by natocTo** [comment]
Aa měl jsem to nachystaná i s tím formem. Tak jsem to poslal takto. Budu muset odběhnout, ale klidně to pak oddělím ještě a pošlu zvlášť. Nechtěl jsem to teď brzdit.

**Comment by ujovlado** [comment]
Ja som kludne za to, aby sa to trosku vylepsilo. Ale postupne, vo viacerych PRs, s malymi zmenami.

Postupnost ako pises hore celkom dava zmysel.

1. input group (tak ako pise Jan v tom PR)
2. pridanie formulara, je samozrejmost ze to chcem odpalit enterom

zvysok je ale na debatu ... za mna:

3., 4. a 5. vobec by som tie emaily nevypisoval v riadku ale kludne tabulkou/listom (pricom v kazdom riadku by bol priestor na zmazanie. A tym padom by sa to pridavanie prehodilo nad tabulku.

Vyzeralo by takto - vsetko za standardneho pouzitia bootstrap (`table-condensed`):

![screenshot_2018-10-15_18-43-27](https://user-images.githubusercontent.com/419849/46965150-52626d00-d0aa-11e8-9ef6-e64358a85501.png)


zaroven by som s bodmi 3. 4. a 5. pockal na merge prepisu do js, bude sa s tym robit lepsie

**Comment by ujovlado** [comment]
^ ten input group som tam dal len na ilustraciu - viem ze uz to riesit v PR.

**Comment by ujovlado** [comment]
<details>
<summary>diff</summary>

```diff
diff --git a/src/scripts/react/common/ItemsListEditor.coffee b/src/scripts/react/common/ItemsListEditor.coffee
index fa5aef866..c3c6a491c 100644
--- a/src/scripts/react/common/ItemsListEditor.coffee
+++ b/src/scripts/react/common/ItemsListEditor.coffee
@@ -37,22 +37,25 @@ module.exports = React.createClass
     @props.onChangeValue(values)
 
   _renderLabels: ->
-    component = @
-    React.DOM.div {className: "well"},
-      @props.value.map((packageName, key) ->
-        React.DOM.span {key: key},
-          React.DOM.span {className: 'label label-default'},
-            React.DOM.span
-              className: "kbc-icon-cup"
-              onClick: ->
-                component._handleClickRemoveButton(key)
-            ' '
-            packageName
-          ' '
-      , @).toArray()
+    React.DOM.table className: 'table table-striped table-condensed',
+      React.DOM.tbody null,
+        @props.value.map((packageName, key) ->
+          React.DOM.tr {key: key},
+            React.DOM.td null,
+              packageName
+            React.DOM.td null,
+              React.DOM.button
+                className: 'btn btn-link'
+                onClick: =>
+                  @._handleClickRemoveButton(key)
+              ,
+                'Remove '
+                i
+                  className: "fa fa-trash"
+
+          ).toArray()
 
   _renderAddInput: ->
-    component = @
     React.DOM.div {className: "row"},
       React.DOM.div {className: "col-xs-4 form-inline kbc-inline-edit"},
         React.DOM.input
@@ -73,10 +76,10 @@ module.exports = React.createClass
 
   render: ->
     React.DOM.div {},
+      @_renderAddInput()
       if (@props.value.count())
         @_renderLabels()
       else
         React.DOM.div {className: "well"},
           React.DOM.small {},
             @props.emptyText
-      @_renderAddInput()
```

</details>

**Comment by janmichek** [comment]
Jo, souhlas vidim to stejne. Zaroven se to snazim zobecnit, abychom pro kazdou entitu nemuseli vymyslet novy zpusob ovladani.

Muj navrh je nasledujici:

**Simple CRD** 
Viz navrh vyse: 
Entitu muzes pridat, vylistovat odebrat. V entita nema detail.


kdyz uz 3 akce vyse nestaci, zacina byt cela vec komplexnejsi ->

**CRUD**
klasicky co uz mame v KBC (napr seznam konfiguraci)
- tvorit novou entitu (modal flow)
- vylistovat
- smazat
- prejmenovat
- vyhledavat
- jit na detail
- [libovolne akce]

**Comment by ujovlado** [comment]
Tak teraz celkom vaham.

Chvilku som sa kukal na tu tabulku (co som dal screenshot), a zda sa mi, ze as sa rozhodneme to vypisat tabulkou, potom mi dava vacsi zmysel, co pis Jan. Nad tabulkou vpravo pribudne "Add email" (alebo nieco podobne), otvori sa modal (autoFocus na email input), vpisem email, stlacim enter, modal sa zavre a nova polozka je v tabulke.

To inline pridavatko je pekne, ale asi tiez radsej uprednostnim jednotnost. ;)

**Comment by ujovlado** [comment]
No a este z ineho sudka. Super UX vylepsenie by bolo, keby to ponukalo emaily userov, ktori su projekte. Potom stoji za zvazenie, ci sa na to uplne nevykaslat a nezahodit ako input, tak aj tabulku a dat tam obycajny `react-select` (Creatable).

A potom by to pridavanie vyzeralo, cca takto: 

![screenshot_2018-10-15_19-53-04](https://user-images.githubusercontent.com/419849/46968613-f270c400-d0b3-11e8-9088-880cae1f3ded.png)

**Comment by Halama** [comment]
pozor lidi tam dávají třeba slack emaily. Dokud nemáme celkově pořádně vyřešené notifikace v  kbc tak by ta možnost tam měla zůstat.

**Comment by ujovlado** [comment]
Jo, to prave poskytuje, "react-select creatable" -> vybrat s existujuich + pridat vlastne.

**Comment by Halama** [comment]
tak pak ok

**Comment by natocTo** [comment]
React-select byla moje první myšlenka když jsem nad tím přemýšlel. Pak jsem si říkal že využiji spíš tu logiku co tam je abych poslal rychle fix na ten padding + odesílání enterem.
Pokud by tam byl modal, tak asi zase může zmizet ten mezistav na editování. Tím by se asi ta logika taky upravovala, takže už by rovnou šel použít ten react-select no.

**Comment by ujovlado** [comment]
Osobne vidim ako nalepsi pomer cena/vykon ren react-select.

- podobny koncept v UI mame (napr. Packages alebo Required transformations)
- netreba ziadne CSS zmeny
- vyhodi sa kus stareho kodu v podobe tejto nestandardnej "inline add" komponenty

**Comment by janmichek** [comment]
Za me ok, nevidim v tom zadny zadrhel.

**Comment by ujovlado** [comment]
A tie emaily userov to zatial ponukat nemusi, asi ich moc nemas odkial vytiahnut.
