### ISSUE TITLE
orchestration tasks

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2173]
this doesn't make sense:

![image](https://user-images.githubusercontent.com/4319320/46975059-f4dc1980-d0c5-11e8-97a2-9c2d1d9d3d1d.png)

either show configuration name, or do array_unique() on component name

**Comment by janmichek** [comment]
Je takova castecna informace vubec k necemu dobra? Jsem pro to to vyhodit

**Comment by odinuv** [comment]
vyhodit to je blbost, to by pak nebylo vubec videt ze tam je neco nastavene

**Comment by natocTo** [comment]
Pokud se příjme https://github.com/keboola/kbc-ui/pull/2197 , tak bych sem zkusil dostat ty názvy konfigurace. Mám to připravené, ale i tu může nastat ta N/A situace, takže s tím počkám.
