### ISSUE TITLE
poll.interval

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2183]
v routerech je někdy `5` a někdy `7`, asi by to chtělo sjednotit. low prio :-)

**Comment by ujovlado** [comment]
A prinesie to nieco? Pretoze napr. detail jobu to ma na 2s, ale napr. zoznam jobov na 10s.

**Comment by ujovlado** [comment]
Je to zjednotene povedal by som. Mame 5,10,15 a 20. na detaile jobu je vynimka 2s.
