### ISSUE TITLE
kontrast

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#219]
![image](https://cloud.githubusercontent.com/assets/903531/8315115/7fb9678e-19ee-11e5-897c-c74a112b4113.png)

http://juicystudio.com/services/luminositycontrastratio.php#specify
![image](https://cloud.githubusercontent.com/assets/903531/8315103/756eabea-19ee-11e5-8564-e0ddb02b93b9.png)

**Comment by ondrejhlavacek** [comment]
Chceš řešit kontrast pro barvoslepý?

**Comment by Halama** [comment]
chtěl bych aby to bylo čitelný.

**Comment by odinuv** [comment]
![clipboard01bb](https://cloud.githubusercontent.com/assets/4319320/8568252/74361126-256c-11e5-9b66-15f920df994a.png)

cim vic na to koukam, tim vic se mi zda tahle modra neprijemna na cteni, normalne celkem dobry, ale pokud mam unavene oci nebo nedobre svetlo, tak me to uplne taha za oci

**Comment by Halama** [comment]
zavírám
