### ISSUE TITLE
SQL parser not working locally

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2196]
Upravím SQL queries a parser se je pokouší rozbít na jednotlivý dotazy a vyfailuje

![image](https://user-images.githubusercontent.com/497675/47178417-7973a580-d31b-11e8-86c5-33972d9829c3.png)

**Comment by ujovlado** [comment]
jop, o tom vieme, tu je na to PR: https://github.com/keboola/kbc-ui/pull/2191

**Comment by ondrejhlavacek** [comment]
oh, danke! zavírám teda :)
