### ISSUE TITLE
[WIN?] Není vidět obsah selectů

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#220]
Vypadá to jakoby v nich nebylo nic vybrané, ale je. Při změně výběru tam pořád není nic vidět, ale změna se uskutečni, tj. select je funkční, jen není vidět, co je v něm vybrané. Nefunguje to v žádném prohližeči (Chrome, Firefox, Opera, IE), takže předpokládám, že to asi nějak způsobují widle?

Spolehlivě je to vidět třeba tady:
https://connection.keboola.com/admin/manage-apps#/apis
![clipboard01](https://cloud.githubusercontent.com/assets/4319320/8316476/9768422a-19f7-11e5-9f8d-169b4a04ffda.png)

ale i tady:
https://connection.keboola.com/admin/projects/578/application/?app=kbc.docToolRecipesApp#/rcp-distribution-groups/test
![clipboard02](https://cloud.githubusercontent.com/assets/4319320/8316655/b63b7aae-19f8-11e5-802f-7564fdc9c58b.png)

**Comment by odinuv** [comment]
Ještě doplním, že to *ne*dělá u všech selectů.

**Comment by Halama** [comment]
To by mohlo být to samé jako #221

**Comment by JakubMatejka** [comment]
Jj. vypadá to že řešení #221 pomůže
