### ISSUE TITLE
TypeError: Cannot read property 'getIn' of null

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2201]
https://sentry.io/keboola/keboola-connection-ui/issues/736110113/

```
TypeError: Cannot read property 'getIn' of null
  at Array.forEach (<anonymous>)
...
(45 additional frame(s) were not displayed)
```

**Comment by natocTo** [comment]
Tady jsem zkoušel 30min hledal případ kdy to takto dopadne a nepovedlo se.

Ukazuje to chybu ve funkci `mapTaskFn`. Kde teda `task` musel přijít jako nul. Nicméně toto se volá z jiné funkce kde je cca 
```js
phase.get('tasks').map((task) => {
   return mapTaskFn(task, configurations);
});
```

Tady nerozumím jak se tam právě dostane null. Zkoušet jsem označit tasky, pak je smazat a pak udělat move apod, a vše prošlo bez chyby.

Mohl bych tam přidat filter, ale lepší by bylo přijít na to jak se tam dostalo to co způsobilo error no. Já nevím.

**Comment by kacurez** [comment]
pozrel som nato a sa mi to na posledny pokus podarilo nasimulovat :)
v skratke ak odznacim jeden z oznacenych taskov a dam move tak to spadne, presnejsi postup:
1. start editing tasks
2. mark task `a`
3. mark task `b`
4. unmark task `a` or task `b`
5. click actions -> move tasks
6. select some phase and press move button

imho problem bude tu:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/orchestrations/react/pages/orchestration-tasks/TasksEditTable.jsx#L275

Zbytocne sa tam uklada null a na odznacenie fazy by stacilo zavolat `deleteIn` namiest `setIn(..., null)`

**Comment by natocTo** [comment]
Pecka, tak aspoň tobě :) Budeš to upravovat nebo na to mám mrknout?

**Comment by kacurez** [comment]
ak sa ti chce tak to mozes skusit, pozeram ze si tam uz nieco fixoval. Ja zatial mam nieco na praci(+zendesk) ale mozem sa k tomu dostat neskor tento tyzden.

**Comment by natocTo** [comment]
Já na to mrknu.
