### ISSUE TITLE
Quick hint pro search v jobech

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2206]
@janmichek měl bys nápad, kam dostat k search fieldu u jobů nějaký tlačítka, který předvyplní tři přednastavený hledání? Někam sem
![image](https://user-images.githubusercontent.com/1427901/47337574-d8774880-d694-11e8-8e1e-f6fe11d31046.png)

dát tři předvyplněný vyhledávání:
- My jobs `token.description:petr@keboola.com`
- My failed jobs `status:error AND token.description:petr@keboola.com`
- All long running jobs `durationSeconds:>7200`

Vedle toho jsem zkoušel ještě, jestli funguje něco jako `now-7d` do časovýho filteru, ale nejde mi to. Kdyby to šlo, dal bych "My failed jobs in last 7 days".

**Comment by janmichek** [comment]
Jasny, nejjednodussi mi to prijde takhle 
![image](https://user-images.githubusercontent.com/15363559/47348161-2306be00-d6b1-11e8-821a-454ba753947d.png)

Ten otaznik vedle searche vpravo je jen minimalni produkt, nema to moc UX. Vyhledove jsme chceme udelat chytrejsi search co ti bude napovidat, takze by si to naslo misto i pod searchem pozdeji.

Po rychlim progugleni koukam ze Elasticsearch podporuje date range, asi nebude problem to doimplementovat https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html . Neslibuju nic, nejsem na to expert xD Zkusim @tomasfejfar  se kterym jsem na tom predtim spolupracoval. Vedel bys jakou to ma cenovku, dodelat podobny date range search?

**Comment by Halama** [comment]
date range search to určitě umí už teď

**Comment by janmichek** [comment]
^^ Jeste predstava o ovladani je takova, ze kliknu na link z Recommended Actions -> predvyplni se mi vyrazem searchbar -> rovnou to vyhleda -> zmizne Quick Help

**Comment by tomasfejfar** [comment]
Já se v tom reactu tolik zas nevyznám - tj nevím takhle z patra, jestli půjde narvat do toho search fieldu ten search nějak "hezky". Ale tak jak to píšeš mi to přijde jako dobrý MVP. 

Date range to umí  `startTime:[now-7d TO now]`.

**Comment by tomasfejfar** [comment]
Funguje i `startTime:>now-3d`

**Comment by padak** [comment]
Nešlo by mít ty recommended actions na očích, ať nejsou schovaný v tom tooltipu? Rovnou koukám na joby, dám klik na "moje joby" a hned vidím moje joby?

**Comment by janmichek** [comment]
Jasne ze slo. Nejjednoduseji asi takhle. Uz to to samozrejme vizualne tezsi.

![bez-nazvu-1](https://user-images.githubusercontent.com/15363559/47353254-13d93d80-d6bc-11e8-8627-eb220fe097ca.jpg)

![bez-nazvu-2](https://user-images.githubusercontent.com/15363559/47353259-176cc480-d6bc-11e8-87d3-4ec612d2482b.jpg)

**Comment by janmichek** [comment]
Jeste comment k tomu. Jsou to 2 navrhy. Jeden s linkama, druhy s ikonou a linkama. 
Chtel jsem ukazat ze kdyz obsah bude moc dlouhy, tak se to zalomi - zalezi na sirce viewportu

**Comment by janmichek** [comment]
ok, zacnu to pripravovat

**Comment by janmichek** [comment]
@padak mam to pripraveny, jeste udelam kolecko code review.

Tady prikladam na cisto 2 verze. Vizualne me vic vyhovuje verze s ikonou per search. Tak nejak logicky mi pripada ze to patri k sobe, ze se jedna o jednotlivy search. Lupa na zacatku seznamu mi pripada ze toho moc nerekne. Nechavam na zhodnoceni

![image](https://user-images.githubusercontent.com/15363559/47443381-74e43c80-d7b4-11e8-8384-eed8c97abde6.png)

![image](https://user-images.githubusercontent.com/15363559/47443386-79105a00-d7b4-11e8-87e0-388b3df42d0e.png)

**Comment by padak** [comment]
Super! Souhlas, per search je to lepší!

Dne st 24. 10. 2018 17:49 uživatel Jan Michek <notifications@github.com>
napsal:

**Comment by ujovlado** [comment]
Co chceme povedat tou "ikonkou per search". Ved to vyzera hrozne. :)

**Comment by janmichek** [comment]
Diky za subjektivni nazor. Udelal jsem par navrhu vyse.

**Comment by ujovlado** [comment]
Nemas za co, tiez su subjektivne ;)

Mohlo by to bvyzerat napr. takto:

![screenshot_2018-10-24_18-46-55](https://user-images.githubusercontent.com/419849/47447187-41f27680-d7bd-11e8-8924-d59656813eea.png)

**Comment by janmichek** [comment]
Mel jsem puvodne stejny minimalisticky navrh tady https://github.com/keboola/kbc-ui/issues/2206#issuecomment-432184466

**Comment by ujovlado** [comment]
Jo, toho si sa mal drzat a nenechat sa zlakat na "ikonku per search", vobec to tam netreba. :)

**Comment by ujovlado** [comment]
ok, skus to tak ... mozno tam bude potrebne uprava tej search bar komponenty, vyzera, ze pri zmene query to nereaguje uplne idealne. ;)

**Comment by janmichek** [comment]
Jasny, no to jsem resil tady https://github.com/keboola/kbc-ui/pull/2219#discussion_r227850509 Vyzkousim, uvidim jestli se to tim vyresi

**Comment by tomasfejfar** [comment]
Klidně i "Predefined searches" jen - ať je to kratší.

**Comment by padak** [comment]
@janmichek bez ohledu na finální wording (s tím může pomoct @hhanova, ne?) posuneme to, ať nám nezůstávají věco rozdělané (než se znovuotevře https://github.com/keboola/indigo-ui/issues/190)?

**Comment by janmichek** [comment]
Jo, postrcim to. Zasekli jsme se na funkcionalite - propisovani query do searchbaru a clearovani.

**Comment by ujovlado** [comment]
Myslim, ze sme to uz odladili predminuly tyzden (nenasaadzoval som to, lebo som siel na dovo), dostanem sa k tomu dnes/zajtra.

**Comment by janmichek** [comment]
ok, super. Diky
