### ISSUE TITLE
[FF] Není vidět obsah textových polí

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#221]
U některých textových polí (ne u všech, ale u hodně) není vidět obsah. Pokud je pole prázdné, není v něm vidět placeholder, ale je tam vidět kurzor.
![clipboard03](https://cloud.githubusercontent.com/assets/4319320/8316832/dd7b13bc-19f9-11e5-9629-417087516df8.png)

Pokud je v něm něco napsané, není tam vidět ani kurzor:
![clipboard04](https://cloud.githubusercontent.com/assets/4319320/8316833/df7c7106-19f9-11e5-9107-5bb51bb92e85.png)

Dělá to v novém i starém UI:
![clipboard05](https://cloud.githubusercontent.com/assets/4319320/8316836/e123c270-19f9-11e5-8008-e2e50a24f7c5.png)

Dělá to ve Firefoxu a v IE, v Chrome a Opera funguje normálně.

**Comment by Halama** [comment]
Ve starém ui se ti nic takovýho neděje?

**Comment by odinuv** [comment]
Ne, nedeje. Pres https://connection.keboola.com/admin/projects-new/578/storage#/  to funguje bez problemu.

**Comment by Halama** [comment]
super tak ve FF mi to dělá taky

**Comment by Halama** [comment]
@JakubMatejka dělá to ten padding 
![image](https://cloud.githubusercontent.com/assets/903531/8317344/ffaa400e-19fc-11e5-9301-2374048b83c2.png)

**Comment by JakubMatejka** [comment]
Tak snad. Kdyžtak to prosím ještě prověř.
