### ISSUE TITLE
loadComponentConfigDataForce - wrong path when storing configuration?

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2217]
Related to #2197 

@natocTo si vsimoil, ze nefunguje `loadComponentConfigDataForce`

Ked sme sa v tom vrtali viac, zistili sme, ze to pravdepodobne uklada na zlu cestu (chyba `configurations`).

- https://github.com/keboola/kbc-ui/pull/2197#issuecomment-432569796
- https://github.com/keboola/kbc-ui/pull/2197#issuecomment-432571164

![screenshot_2018-10-24_10-42-14](https://user-images.githubusercontent.com/419849/47419667-f9b36400-d77c-11e8-85f8-cb881f0db5ce.png)

Slo by to upravit takto? Vieme zistit, kde sa to pouziva?

```diff
diff --git a/src/scripts/modules/components/stores/InstalledComponentsStore.coffee b/src/scripts/modules/components/stores/InstalledComponentsStore.coffee
index 72d2bac0c..5c20a1a33 100644
--- a/src/scripts/modules/components/stores/InstalledComponentsStore.coffee
+++ b/src/scripts/modules/components/stores/InstalledComponentsStore.coffee
@@ -411,7 +411,7 @@ Dispatcher.register (payload) ->
         store = store.deleteIn ['configDataLoading', action.componentId, action.configId]
         storePath = ['configData', action.componentId, action.configId]
         store = store.setIn storePath, fromJSOrdered(action.data.configuration)
-        storePath = ['components', action.componentId, action.configId]
+        storePath = ['components', action.componentId, 'configurations', action.configId.toString()]
         store = store.setIn storePath, fromJSOrdered(action.data)
         j = 0
         while j < action.data.rows.length
```

**Comment by ujovlado** [comment]
@ondrejhlavacek co si o tom myslis?

**Comment by ujovlado** [comment]
Heh, a prave som si uvedomil akou super vyhodou je mat unit testovany store (co nemame).

**Comment by natocTo** [comment]
Koukám se kde to je použito. Přímo použití je pouze v `MigrationsActionCreators.js`.

Pak ale existuje `loadComponentConfigData` které je použito na 100 místech, hlavně u rout. Tato funkce taky vždy deleguje práci na `loadComponentConfigDataForce`.

Ale co jsem koukal, tak snad všichni pak spoláhají na to že ty načtený data jsou ve `configData->componentId->configId`, to uložení do `components->componentId->configId` (kde je asi ta chyba), tam je spíše jako bonus navíc .) 

Tak myslím že by bylo bezpečné to upravit. Na druhou to asi nepřinese nic extra navíc, ale může to předejít problémům někdy v budoucnu.
