### ISSUE TITLE
Glitch - Vytvoření aliasu 

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#222]
Nenačítá se obrázek pro tlačítko pro zrušení vybraného sloupce:
![clipboard06](https://cloud.githubusercontent.com/assets/4319320/8317054/160418a4-19fb-11e5-98f6-ec8d1765e063.png)

a textový pole empty value je moc roztáhlý.
(chrome)

**Comment by Halama** [comment]
fixnuto
