### ISSUE TITLE
Interface Orchestrace

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2224]
Pustil bych se teda do sjednoceni interface orchestrace, jak jsem navrhnul v roadmape.

Celkove jde o:
- sjednoceni layoutu - vyhozeni master / detail (leve nabidky orchestraci)
- description a la komponenty
- graf umistit nahoru
- presunout akce doprava
- last runs - do praveho panelu
- updates do praveho panelu
- edit tasks, notifications, a scheduler v rozbalovacim panelu podobne jako mappingy - potreba nejdriv nakreslit
- vymyslet umisteni assigned token
- navrh vylepseni - klik na sloupec v grafu me prenese na detail

Vychazim z tohoto navrhu, ktery je treba updatovat. Jen orientacni
![image](https://user-images.githubusercontent.com/15363559/47494489-0fdf2400-d852-11e8-9a28-158fe187f3a9.png)

**Comment by ujovlado** [comment]
Pozor ale na jednu vec - detail jobu v orchestracii vyzera uplne inaksie ako standardny detail jobu. Detail jobu orchestracie ma Tasks. To treba zohladnit.

Asi by som sa v prvom kroku pustil len do zmeny toho layoutu detailu orchestracie. T.j.:

- vyhodis prepinatko orchestracii vlavo
- description je potom na spravnom mieste
- schedule - tak ako mas v navrhu, no pod nadpisom by bol len vypis a odkaz "edit schedule"
- assigned token doprava
- (optional) asi by mohla pribudbut aj info "Created by"
- updates doprava
- notificatons rovnako ako schedule
- tasks rovnako ako schedule
- buttony z hlavicky doprava, ok
- zoznam jobom imho musi ostat zatial na detaile, moze ist na spodok ako je to teraz.

Tato zmena by mala byt easy a po tejto zmene by to malo byt funknce a len preusporiadane. A az potom mozeme zacat s redesignom jendotlivych casti.

**Comment by janmichek** [comment]
Diky za commenty, zohlednim to v grafice

**Comment by janmichek** [comment]
V detailu jobu v orchestrace je jediny misto, kde mi pripada ze layout 'master / detail' opravdu vyznam ma. Tam to teda zatim zachovam

**Comment by odinuv** [comment]
pokud je to mozny, tak prosim jeste preusporadat podle flow orchestraci - (https://help.keboola.com/orchestrator/)
tasks -> run -> schedule -> notifiacations (nebo notifications -> schedule) tj. tasks jsou dnes vpravo dole i kdyz se jima zacina

**Comment by janmichek** [comment]
Stale jeste WIP


![orchnavrhnovycollapsed](https://user-images.githubusercontent.com/15363559/47517237-dc1ef100-d887-11e8-9442-1ae12b49dbc2.jpg)



![orchnavrhnovy](https://user-images.githubusercontent.com/15363559/47517239-dc1ef100-d887-11e8-8558-68713068307f.png)

**Comment by odinuv** [comment]
jsem myslel, ze ty notifications a schedule budou v modalech? nebylo by to takhle takovy k uscrollovani? just m2c

**Comment by ujovlado** [comment]
Imho by sme to v 1. kroku mali nechat na samostatnych podstrankach, len zmenit layout (https://github.com/keboola/kbc-ui/issues/2224#issuecomment-433011610) a az potom rozmyslat ako vylepsit jednotlive casti ako cron/notificatoions/atd

**Comment by janmichek** [comment]
@ujovlado @odinuv ok, chapu. Jako nejlevnejsi na implementaci a zaroven jednotnou variantu vidim toto 
![image](https://user-images.githubusercontent.com/15363559/48059122-997ae400-e1b8-11e8-8658-303bcb919e15.png)

**Comment by janmichek** [comment]
Pripadne se da vratit jeste seznam runu zpet z sidebaru do contentove casti, ale prislo mi ze je tam dost nevyuzityho mista.

**Comment by odinuv** [comment]
dal bych tomu grafu nejakej nadpis/popis a hura do implementace :)

**Comment by ujovlado** [comment]
> ok, chapu. Jako nejlevnejsi na implementaci a zaroven jednotnou variantu vidim toto

Myslim, ze ked to budu pre zaciatok odkazy (myslim tie buttony) na jednotlive podstranky bude to ok. Teda az na schedule, to ostane modal.
