### ISSUE TITLE
Clear search results when clicked on clear button

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2228]
Nektere searche filteruji live.
Nektere searche (v Jobs, Logs) vyhledavaji po submitu.
Uzivatelsky by bylo fajn po kliku na clear vyresetovat i vysledky vyhledavani.

souvisi s https://github.com/keboola/kbc-ui/pull/2219

**Comment by ujovlado** [comment]
Toto musi poriesit ten search bar sam, zavolat onsubmit.
