### ISSUE TITLE
[ex-db-generic] Display selected fully qualified table names

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2229]
Valid for al extractors but especially those with optional database/schema in connection parameters, the extractor should display the full table name `schema.table`

**Comment by pivnicek** [comment]
@janmichek I would like to display the fully qualified name of the source table in the db extractors (ex: `schema`.`table`.
My idea is to place it underneath the "name" of the configuration row here:
![image](https://user-images.githubusercontent.com/569139/47779864-70f77380-dcfa-11e8-89a3-9a5b4902d0d6.png)
and here:
![image](https://user-images.githubusercontent.com/569139/47779902-8bc9e800-dcfa-11e8-89b7-cabbc19aee86.png)
It could work in the first image, but I'm doubtful about the index listing page (second image).  
Could you please help me with this?  Cheers man.

**Comment by pivnicek** [comment]
Note that not all rows will have a source table listed, only those where they select a table and don't write their own query

**Comment by ujovlado** [comment]
Fixed
