### ISSUE TITLE
Transformace - prázdné plochy

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#223]
**Statická transformace**
Zbytečně velký padding prvního nadpisu `Requires`
![image](https://cloud.githubusercontent.com/assets/903531/8324747/d6024600-1a53-11e5-8a4c-3b8cb1722721.png)

**Editační režim**
Nadpisy sekcí zbytečně velký padding od té linky.
![image](https://cloud.githubusercontent.com/assets/903531/8324839/7c61bfe4-1a54-11e5-8f29-0b6f360c6808.png)

V obou případech se tam "zdvojují" marginy/paddingy. Jeden má nastavený row a druhý ten nadpis.

**Comment by JakubMatejka** [comment]
Jenže co s tím? Přes tu hromadu spanů ve kterých je ten nadpis zanořený se to ani nedá selektovat na "první nadpis pod `.kbc-row`". ;os

**Comment by Halama** [comment]
mrknu jestli jsou tam ty spany nezbytny

**Comment by Halama** [comment]
Tak se mi to povedlo pročistit. h2 je ve static i edit modu vždy přímo pod `.kbc-row`
