### ISSUE TITLE
Editační pole data samplu v Storage je hodně malý

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#224]
![screen shot 2015-06-24 at 11 32 45](https://cloud.githubusercontent.com/assets/497675/8338248/cec45656-1a64-11e5-87da-112a6bc395a1.png)

Poslední řádek je navíc skoro nepřístupnej myší, text se dá vybírat cca v horní 1/3 písmen.

**Comment by Halama** [comment]
fixnuto v konzoli
