### ISSUE TITLE
Jobs detail - removed transformation

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2248]
Pokud jdu na detail jobu transformace, která již byla vymazána a která je již byla odstraněna dostanu takový výsledek.

![job](https://user-images.githubusercontent.com/12331181/47657581-a16fce00-db91-11e8-8488-c4ee5d6f4db3.png)

Na začátku se snažím danou konfiguraci najít pomocí  `InstalledComponentsStore.getConfig`. Tam ale již nic není. Koukal jsme že ještě existuje `InstalledComponentsStore.getDeletedConfig`, takže bych mohl případně hledat i tam. Nevím zda je to 100% spolehlivé ale když jsem to zkoušel tak to šlo.

Když teda získám konfiguraci třeba z `getDeletedConfig` tak se to již vykreslí OK. Nicméně ty odkazy nikam nevedou. Respektive dostanu chybu že transformace nebyla nalezana, takže to není moc ideální řešení.

Myslím že lepší bude nehledat v `getDeletedConfig` ale rovnou napsat, že daná transformace již byla vymazána, nebo něco v tom smyslu.

Nebo nějaké lepší řešení? Daná komponenta je zrovna v procesu review v přepisu z coffee -> jsx, tak místo abych se vhrnul hned na nějakou úpravu jsem to sepsal, s tím že se třeba povede komponentu přehodit do JSX, než se to domluví ideální řešení.

**Comment by kacurez** [comment]
myslim ze by stacilo tam dat iba id tej transformacie tak ako to je riesene na tom screenshote uplne hore vpravo(label `Configuration`)
