### ISSUE TITLE
[Minor] Barva koleček orchestrací (apod.)

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#225]
Ahoj,

nešlo by změnit barvy success/error/processing na jednolitou? Jako v Yosemite. Ty přechody s obrysem vypadaj trochu jak z 10 let sterýho Performance stuida :)

![bata - multichannel - orchestrations 2015-06-25 08-00-51](https://cloud.githubusercontent.com/assets/12933713/8348265/9d7a75b4-1b11-11e5-9f75-039b33612125.jpg)

**Comment by Halama** [comment]
tohle zatím zavírám. Migrujeme issues do anglictiny, tak to kdyztak zaloz znovu pokud te to porad trapi :)
