### ISSUE TITLE
GoodData Writer v3 bugs

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2254]
Tato issue je na reporting bugov pre ui GoodData Writeru na linku:
https://connection.keboola.com/admin/projects/PROJECTID/writers/keboola.gooddata-writer/

**Comment by padak** [comment]
Zkouším založit nový writer a při zakládání projektu to hodí error:
![image](https://user-images.githubusercontent.com/1427901/47784567-47444980-dd06-11e8-9ef3-2600a3a1afd9.png)

**Comment by padak** [comment]
V detailu tabulky bych dal `Title` na první místo a k `Identifier` napsal ať na to nesaháš, pokud nevíš co to je :)

**Comment by kacurez** [comment]
@padak to `Error Invalid access token` sa mi nedari nasimulovat. Podarilo sa ti nakoniec vytvorit gooddata projekt?

**Comment by kacurez** [comment]
tak Padak to skusa v EU kbc a tam zrejme neni provisioning:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/gooddata-writer-v3/gooddataProvisioning/api.js#L6
zistim viac

**Comment by JakubMatejka** [comment]
Detail tabulky mi failuje: https://connection.keboola.com/admin/projects/313/writers/keboola.gooddata-writer/simpletest/table/out.c-main.categories 
<img width="600" alt="dev jakub - application error 2018-11-01 20-34-27" src="https://user-images.githubusercontent.com/215660/47875004-a04ed300-de15-11e8-982b-c0f0072fa765.png">
<img width="600" alt="dev jakub - application error 2018-11-01 20-36-22" src="https://user-images.githubusercontent.com/215660/47875086-dc823380-de15-11e8-87c4-c16aece8578c.png">

**Comment by kacurez** [comment]
@JakubMatejka pozeram ze ten konfig je stary a zakladal resp upravoval si ho rucne cez api ze? imo ta chyba bude sposobena tym ze to je nekonzistentne. Zaloz si ked tak novy konfig cez ui a skus to tam.

**Comment by kacurez** [comment]
toto zavriem, tie veci su pofixovane
