### ISSUE TITLE
sidebar šířka

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#226]
Šla by nějak zafixovat max. šířka toho sidebaru? Na velkém rozlišení je to zbytečně široké a ubírá to místo hlavnímu obsahu.

![image](https://cloud.githubusercontent.com/assets/903531/8353172/9363c83a-1b3b-11e5-9340-e39fefe866ed.png)

**Comment by JakubMatejka** [comment]
No, blbě. ;o( Od šířky 992px je to 20% vůči 80% (https://github.com/keboola/kbc-bootstrap/blob/master/less/kbc.less#L99) oproti normálnímu poměru 25%:75%, to bych mohl třeba ještě upravit. Nicméně fixní šířku sidebaru tam asi nedám, protože se pak nebude dát nastavit obsah natahovací, bude muset být fixní taky.

**Comment by JakubMatejka** [comment]
A jó, tak ne, zdá se že to nakonec půjde. Sice ne tak snadno jak by se mi líbilo, ale nejspíš jo ;o)

**Comment by Halama** [comment]
u toho soucasnyho ui jsem to nejak ohnul aby to tak fungovalo

**Comment by JakubMatejka** [comment]
Tak snad hotovo

**Comment by Halama** [comment]
@JakubMatejka V pravo se tam objevil nějaký prázdný prostor:
![image](https://cloud.githubusercontent.com/assets/903531/8426027/6afffc9a-1f0c-11e5-9603-573f57eed0ad.png)
