### ISSUE TITLE
When ssh credentials are undefined don't set default port in sync actions

### ISSUE THREAD

**Issue by Actimel** [keboola/kbc-ui#2260]
When running `testConnection` or `getTables` node `ssh` shouldn't exist at all when SSH is not configured. It's good for making troubles on backend only.

Reference in generic: https://github.com/keboola/kbc-ui/blob/1099168b42709638ddd460a1b39d70b10cb65ea5/src/scripts/modules/ex-db-generic/storeProvisioning.js#L161
There might be also script for specific extractors.

**Comment by ujovlado** [comment]
stare ... bol na to PR no doteraz to valilo, tak asi "wontfix"
