### ISSUE TITLE
Consider better icon for disabling transformation

### ISSUE THREAD

**Issue by simonvostry** [keboola/kbc-ui#227]
![image](https://cloud.githubusercontent.com/assets/13048454/8353353/37907718-1b3d-11e5-804c-dda94cb79ff5.png)

**Comment by Halama** [comment]
díky,
koukám že ty ikonky jsou prohozeně než je tomu ve starém ui. Opravím to takhle jak to je teď to nedává smysl.

**Comment by simonvostry** [comment]
bezva ;)
