### ISSUE TITLE
React-select - additional row (caused by input)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2280]
Toto som si uplne nevsimol kedy vzniklo, no ten "prazdny riadok" sme tam nemavali.

Chyba:

![screenshot_2018-11-05_16-59-48](https://user-images.githubusercontent.com/419849/48009589-53704280-e11c-11e8-832b-e99215334508.png)

Malo by byt:

![screenshot_2018-11-05_17-00-00](https://user-images.githubusercontent.com/419849/48009595-566b3300-e11c-11e8-998d-0d391a7c1d35.png)

**Comment by janmichek** [comment]
myslim ze uz to tam nejakou dobu visi .] podivam se na to

**Comment by pivnicek** [comment]
jo, ex-db-generic ma to stejne :/

**Comment by janmichek** [comment]
Ten fix je snadny, jenom ted potrebuju checknout radeji vsechy vyskyty, jestli to nezpusobuje nejaky bordel.

**Comment by ujovlado** [comment]
A nemame tam prave naviac to `width: 100%`?

**Comment by janmichek** [comment]
souvisi s https://github.com/keboola/kbc-ui/pull/1854
