### ISSUE TITLE
Version null for jobs with no configuration

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2297]
![image](https://user-images.githubusercontent.com/4319320/48133711-0ca75780-e298-11e8-9688-3e58569925cd.png)

**Comment by ujovlado** [comment]
@natocTo nekukol by si toto? zda sa mi, ze sme to vcera "pokazili" (ale mozno aj nie).

Ak nevieme k akemu konfigu to patri (napr. tam nie je alebo bol zmazany), nemali by sme zobrazovat verziu

**Comment by natocTo** [comment]
Jo mrknu.
