### ISSUE TITLE
Zprovoznit staré komponenty v novém ui

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#23]
Pojedou v nějakém "legacy" môdu.
Je potřeba zajistit:
 - [ ] Alespoň trochu zapadá do nového UI nejsou tam nějaké glitche
 - [x] Linkování z nového UI na staré tam kde zatím není komponenta v novém
 - [ ] Linkování ze starých UI na nové. Např. návrat na seznam extraktorů/writerů, link do SAPI tabulky, 
link na detail jobu. 
 - [ ] Spouštění/mazání konfigurací. Ve starém UI bylo přímo v seznamu konfigurací, v novém to tak není, bude potřeba dodělat do všech konfigurací nebo přidat do seznamu?

Jednak bude potřeba upravit embed aplikací v KBC a pak asi i samotní appky, různý drobnosti.

Otestovat:
 - [x] kbc.applications
 - [x] kbc.docTool - odstraněno
 - [x] kbc.doctoolAdmin
 - [x] kbc.docToolRecipes
 - [x] kbc.docToolTagging
 - [x] kbc.exDb - bude v novém UI 
 - [x] kbc.exGeneric
 - [x] kbc.exGoodData
 - [x] kbc.exGoogleAnalytics - bude v novém UI
 - [x] kbc.exGoogleDrive - v novém UI
 - [x] kbc.exSalesforce
 - [x] kbc.exSfdc
 - [x] kbc.exTelfa
 - [x] kbc.exTwitter
 - [x] kbc.exYoutube
 - [x] kbc.exZendesk
 - [x] kbc.gooddataWriter
 - [x] kbc.orchestrators - v novém UI
 - [x] kbc.pigeonImporter
 - [x] kbc.pingdom
 - [x] kbc.projectHome - v novém UI
 - [x] kbc.restbox
 - [x] kbc.sardine - používá se?
 - [x] kbc.storage
 - [x] kbc.syrupJobs - v novém UI
 - [x] kbc.transformations - v novém UI
 - [x] kbc.uiWrapper - v novém UI
 - [x] kbc.wrChartio
 - [x] kbc.wrDb
 - [x] kbc.wrTableau

**Comment by Halama** [comment]
U starých komponent je potřeba aby správně linkovaly. Týká se to hlavně URL jobů. Pro to je potřeba upgradnout angular-kb 0.15.8  na a pak udělat tuhle změnu https://github.com/keboola/kbc-ui-pigeon-importer/commit/8d8f803e465446679010954e3f096febe63bedea
KBC tam pak injectne správný template pro URL jobu

**Comment by tkacur** [comment]
admin ui sardine v novom ui funguje, nevrtal by som sa vtom moc, a riesil to reaktivne, ked niekto nareportuje.
Momentalne ma kazdy projekt svoju URL ktora sa pri spusteni na nove ui zmeni(iba cast projects-new na projects) takze sa to max oznami na statuse.

**Comment by tkacur** [comment]
ex-generic nieje aktivovany v sucasnom(starom) ui, preto pre nove ui neni potreba aby bezal a vytvori/zmigruje sa az bude pripraveny nezavisle natom ci bude nove ui releasnute alebo nie.

**Comment by tkacur** [comment]
dalsie 2 ui ktore neriesim v novom ui:
1. kbc.pingdom - nema ui(neni aktivovane) 
2. kbc.wrChartio - neni releasnute caka sa na opravu '.' bugu v chartio

**Comment by tkacur** [comment]
kbc.exSfdc je deprecated, nepodporujeme to dalej.

**Comment by tkacur** [comment]
nefunkcny zeroclipboard napr. tu:
https://connection.keboola.com/admin/projects-new/219/writer/?app=kbc.wrDb#/db-credentials?config=tomaspokus

**Comment by tkacur** [comment]
kbc.docToolTagging: nezobrazuju sa ikonky po rozkliknuti buketov a tabuliek napr tu:
https://connection.keboola.com/admin/projects/219/application?app=kbc.docToolTagging#/

v zdrojaku pozeram ze su tam glyph icons, to asi nove ui neinjectuje nie?
https://github.com/keboola/kbc-ui-doctool-tagging/blob/master/app/scripts/directives/tags-icons.coffee

**Comment by tkacur** [comment]
kbc.applications treba trocha ostylovat, ked sa zapne nove ui tak by som dal prec nazov Applications ktory tam je duplikovane:
https://connection.keboola.com/admin/projects/219/applications#/
