### ISSUE TITLE
followup to Use component icon 

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2308]
https://github.com/keboola/kbc-ui/pull/2283

storage actually has the transformations icon :)

![image](https://user-images.githubusercontent.com/4319320/48200715-4a6fb300-e360-11e8-86b6-47f5938aeed3.png)

**Comment by ujovlado** [comment]
It is actually the "other" icon :)

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/blob/0db0320ebd002009a7fa73e76899d17396bd8aa9/src/scripts/react/common/ComponentIcon.jsx#L8

**Comment by ujovlado** [comment]
Since this component it is not in devportal, we have to hack it "inline"
