### ISSUE TITLE
transformace - io mapping skrýt advanced věci

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#232]
Advanced věci rozkrýt až po kliknutí, zpřehlední se tím formulář.

**Comment by ondrejhlavacek** [comment]
Myslíš editaci nebo statickej pohled?

**Comment by Halama** [comment]
editaci

**Comment by ondrejhlavacek** [comment]
Hm, to by bylo rozklikávací nadvakrát, ale asi to dává smysl. Co myslíš, kdyby ty základní věci (source a destination) byly rozkliknutý furt - třeba i bez toho panelu?

Případně - něco jinýho než source a destiantion?

**Comment by Halama** [comment]
analytici rikali ze je ve vetsine pripadu zajima to source destination

**Comment by Halama** [comment]
to ze by byly rozkliknuty furt by asi taky slo

**Comment by ondrejhlavacek** [comment]
Tak hotovo, nedělal jsem tam automatickou detekci jestli to má bejt otevřený, když tam je něco vyplněný (to by byl megavelkej kód a nechtěl jsem to haluzit) ani jsem to nenechával defaultně otevřený, protože to je vidět přímo v tom nadpisu. Tak uvidíme.
