### ISSUE TITLE
Sample SQL transformace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2322]
Dneska v noci u zákazníka **spadl Orchestrační job protože externista přidal prázdnou transformaci**. Zapoměl ji disablovat ani ji nijak needitoval. Job pak spadl na sample query

```
CREATE TABLE "out_table" AS SELECT * FROM "in_table";
```

Navrhuju, aby SQL kód v transformaci nic nedělal a prázdná transformace tak byla vždy nedestruktivní. Třeba takhle:

```
-- This is a sample query.
-- Adjust accordingly to your input mapping, output mapping
-- and desired functionality.
/*CREATE TABLE "out_table" AS SELECT * FROM "in_table"; */
```

Vidět tu "pouhé" přidání transformace je tady https://connection.eu-central-1.keboola.com/admin/projects/154/transformations/bucket/2765661/versions (verze 205). Fail pak proběhl tady https://connection.eu-central-1.keboola.com/admin/projects/154/jobs/13919815?q=%2Bcomponent%3Atransformation%20%2Bparams.config%3A2765661.

![image](https://user-images.githubusercontent.com/1427901/48329403-ed6a4a80-e648-11e8-8ecb-2741476b40d7.png)

**Comment by janmichek** [comment]
Ok, podivam se na to.
