### ISSUE TITLE
WIN - divný fonty na tlačítkách

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#234]
![image](https://cloud.githubusercontent.com/assets/903531/8357730/ab01039c-1b5c-11e5-8324-3e044a9f7958.png)

**Comment by JakubMatejka** [comment]
Nejsem si jistý jestli to v tom Inspektoru vidím dobře, ale ty popisky tlačítek jsou uvnitř spanů s ikonkou? Jestli jo, tak to by být určitě neměly (a řekl bych že to je důvod toho divnýho fontu)

**Comment by Halama** [comment]
aha, je to tak. fixnu
