### ISSUE TITLE
Search v S3 extraktoru

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2341]
V S3 extraktoru nefunguje dobře search. Když tam napíšu jméno tabulky, dostanu match + spoustu odpovědí. V jednom náhodně vybraném rows jsem uvnitř ověřil, že tam hledaný string nikde není = usuzuju, že to hledá blbě. Pic je z projektu klienta - dávám ho teda radši jinam:

https://keboola.slack.com/archives/C02J3DKH3/p1542208914045100

![image](https://keboola.slack.com/files/U02CGJPNN/FE2QV1KNC/00_sap_erp.png)

**Comment by padak** [comment]
@ujovlado moc nevím jak to napsat jinak než "mělo by to tam být (jakkoliv) obsažené". V tom mým případě třeba:

`WHERE Col LIKE '%xxx%'`

- kde `xxx` je ten search co zadávám
- a `Col` je Name/Storage/Description sloupec

**Comment by kacurez** [comment]
tam sa vola `fuzzy.test` na `name` a `description` co tipujem ze je fuzzy match.

https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/configurations/react/components/ConfigurationRows.jsx#L47-L49

**Comment by kacurez** [comment]
pripravim fix

**Comment by ujovlado** [comment]
Hlada to teraz vyhradne v name a description. V tvojom screenshote si to mal zvyraznene aj v stlpci Storage. Tam to zatial nehlada, pretoze vo vacsine pripadov sa meno tabulky rovna menu tabulky v storage. Ak by to bol problem, mozeme to upravit v dalsej iteracii.
