### ISSUE TITLE
Nefunguje encryption v lokálím KBC-UI

### ISSUE THREAD

**Issue by yustme** [keboola/kbc-ui#2353]
Když si v lokálním KBC-UI dám zašiftovat např. heslo při uložení konfigurace, tak se zašifruje na `https://docker-runner.keboola.com`. Když pak chci spustit job, tak ten se spouští na `https://docker-runner.eu-central-1.keboola.com` a dostanu chybovou hlášku, že #password není zašifrovaná hodnota.

Když do /index.html zadám na řádek 166 místo `https://docker-runner.keboola.com` >>> `https://docker-runner.eu-central-1.keboola.com` tak to běží.

Nešlo by, aby se URL pro dockerRunner načítala dynamicky podle toho v jakém regionu jsem ?

**Comment by Halama** [comment]
Jenom doplním legacy  property [dockerRunnerUrl](https://github.com/keboola/kbc-ui/search?q=dockerRunnerUrl&unscoped_q=dockerRunnerUrl) bych úplně zrušil. A tam kde se teď používala by se URL měla natáhnout z .services. `ServicesStore.getService('docker-runner').get('url')`.

**Comment by ujovlado** [comment]
Fixnem to
