### ISSUE TITLE
SQL validation: do not validate MySQL transformations

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2366]
Jsou deprekovaný (v podstatě read only), SQLdep je neumí a stejně se validují

![image](https://user-images.githubusercontent.com/497675/48711534-d230a980-ec0b-11e8-8555-ee208dcfa056.png)

**Comment by ondrejhlavacek** [comment]
Na test například nějaký tady - https://connection.keboola.com/admin/projects/258/transformations/bucket/sys.c-tr-monitoring

**Comment by ujovlado** [comment]
Fixnute revertom SQL validacie (#2378)
