### ISSUE TITLE
Unify search method and use matchByWords when searching configurations

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2367]
vsade kde je search bar pouzit fci `matchByWords(string, query)` z https://github.com/keboola/kbc-ui/pull/2343

---
Doplnenie:

- search bar sa da najst podla komponenty z `indigo-ui` (napr. `import {SearchBar} from '@keboola/indigo-ui';`)
- malo by sa to doplnit len na miesta, kde sa hladaju konfiguracie, pripadne konkretne zaznamy v konfiguracii (napr. jednotlive queries a pod.)

**Comment by ujovlado** [comment]
Napr. to nie je spravene tu:
https://github.com/keboola/kbc-ui/blob/3448782cd06cd79fe54e10aaad880f5f3e6c4fef/src/scripts/modules/ex-mongodb/storeProvisioning.js#L230

Ak bude treba, upresnim dalsie miesta.
