### ISSUE TITLE
Akce v detailu API tokenu

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2379]
Na přehledu API tokenů v KBC projektu je v pravo 
- smazat token
- poslat token emailem
- refresh tokenu

Bylo by super, kdyby tyhle akce byly dostupné i z detailu tokenu.

**Comment by Halama** [comment]
Smazání a refresh tam určitě jsou, viz ten audit co jsem připravoval. poslání se může dodělat.

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/48827987-e214ce80-ed6e-11e8-8711-4277dc6876d7.png)

**Comment by padak** [comment]
Tak já je tam nevidím :) Nejde mi o eventy, ale aby šlo token refreshnout, když na něj koukáš. Typicky vyrobím token, všechno nastavím + připravím CURL příklady, ale chci, aby si owner toho tokenu (kterej je normální admin v KBC) ten token refreshl. Tak bych mu dal odkaz na token a tam by měl tlačítko "refresh". Teď to vypadá takhle:
![image](https://user-images.githubusercontent.com/1427901/48833363-784ef180-ed7b-11e8-98b1-6a39a5563fba.png)

Když tam není, tak ho musím poslat na přehled všech tokenů a tam se naviguje searchem v browseru - takže kdyby náhodou existovaly dva tokeny pod stejným jménem, tak by mohl refreshnout jinej, apod.
