### ISSUE TITLE
Komentáře konfigurací - Orchestrace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2384]
V přehledu TASKů se nerenderuje markdown:

![image](https://user-images.githubusercontent.com/1427901/48871827-a9184080-ede6-11e8-8108-61b9ad863f8e.png)

U konfigurace to vypadá takhle:

![image](https://user-images.githubusercontent.com/1427901/48871848-bcc3a700-ede6-11e8-8934-977fd24ed7b2.png)

**Comment by odinuv** [comment]
related https://github.com/keboola/kbc-ui/issues/2380
