### ISSUE TITLE
Založení nové orchestrace nebo aplikace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#240]
mě vrací na přehled orchestrací nebo aplikací. pokud se přepnu do starýho UI, je to v pohodě.

**Comment by Halama** [comment]
Tomuhle nerozumím. Nejde ti vůbec založit orchestrace nebo aplikace?

**Comment by Halama** [comment]
@padak ping

**Comment by padak** [comment]
Nejde vyrobit orchestrace. Pojmenuju ji a vrátí se mi to na formulář co
chce jméno. Zkusím to večer znovu.

Sent from mobile
Dne 3. 7. 2015 11:19 AM napsal uživatel "Martin Halamíček" <
notifications@github.com>:

**Comment by Halama** [comment]
ok, mě se to zatím nasimulovat nepovedlo ani jsem žádný podobný bug nefixoval

**Comment by padak** [comment]
Ok! Udělám screencast. Teď valíme na drabsky svetnicky.

Sent from mobile
Dne 3. 7. 2015 11:52 AM napsal uživatel "Martin Halamíček" <
notifications@github.com>:

**Comment by padak** [comment]
tak potvrzuju, že to teď funguje. zkusím to podchytit jakmile se mi to stane (viděl jsem to několikrát). díky za trpělivost!

**Comment by padak** [comment]
Tak se mi to povedlo natočit:

https://www.youtube.com/watch?v=e6ulPLSY-q8&feature=em-upload_owner

Děje se mi to docela často. Nevím ale jak to simulovat, někdy to jde a někdy ne. AdBlock mám vypnutej.

**Comment by ondrejhlavacek** [comment]
Jo, tak na tohle jsem narazil taky, děje se to, když zmáčkneš enter místo kliknutí myší!

**Comment by Halama** [comment]
aha tak to je ono :) fixnu
