### ISSUE TITLE
Init / Intro

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2402]
Tak ako sme sa uz bavili, @natocTo  by si zobral na starost preklopenie Storage Console do kbc-ui. Bude to urcite zaujimave (nepojde len o "bezduche prepisovanie"), realne sa tam da dost pochopit ako fici kbc-ui - bude tam dost prace so store, vela akcii (aj async), stahovanie/upload suborov a pod.

Vyhode je, ze je k tomu predloha (ako design tak kod - https://github.com/keboola/storage-api-console), a ide vlastne len o to napisat to efektivne a pekne, tak aby sme na tom mohli dalej stavat. Preklopenie na "react komponenty" aby sme to mali ready na chystany redesign. Nemalo by tam pribudnut zatial koncepcne nic nove. Zaroven sa chceme zbavit legacy kodu a trosku to unifikovat (formulare a pod.) - cize by to malo ladit s kbc-ui.

---

Rozdelil by som to na 3 vacsie celky - asi rovnako ako vyzera UI (Sekcia Storage). Z jednotlivych casti by mali povznikat mensie PRs. Dufam, ze ich bude okolo 50, pripadne trosku viac.

- Buckets and Tables (sekcia Tables, tu bude najviac prace)
- Files
- Jobs

Robil by som to v takomto poradi, v sekcii Files toho moc nebude, sekcia Jobs je zase najmenej dolezita (uz sme ju chceli aj vyhodit).

Chceme to davat asap do mastra, takze tie PR budeme normalne mergovat, nasadi sa to a kto bude vediet odkaz, kukne si to. 

Este k Storage Console. Technicky by som to riesil tak, ze vzdy ked sa mergne/preklopi nejaka cast v kbc-ui, tak ju odmazeme v nejakej branchi v https://github.com/keboola/storage-api-console, ktoru ale mergovat nebudeme. Tym bude zabezpecene, ze sa nestane, ze na nieco zabudneme. Niektore casti ale uz su prec (Tokeny), takze na to pozor, nech sa nieco nepreraba zbytocne.

---

## Init

- Preklikat si aktualnu Storage cast a povrtat sa v tom
- Init novej route (napr. `storage-explorer`), store, actions a pod. + Init Index komponenty (kde budu neskor pridane eventy)

#### Index

- List eventov (reload button je nekonzistente v title), moznost nacitat dalsie (Load more)
- Filtrovanie eventov
- Detail eventu (modal)

#### Sidebar

- Init sidebaru (vypis bucketov a tabuliek) + Reload
- Filtrovanie v sidebare
- Vytvorenie bucketu
-  nova tabulka (csv file uplad)
- nova tabulka (text input)
- nova aliasovana tabulka
- zmazanie bucketu
- detail bucketu

#### Detail

- Detail bucketu (atributy bucketu zatial neriesme)
- Description bucketu - prehodit rovno do detailu, tak ako mame napr. v konfiguraciach)

#### Detail - zdielanie 

- Zdielanie bucketu (z detailu bucketu)
- Zdielanie bucketu - change sharing type
- Zdielanie bucketu - vypnutie zdielania

#### List tabuliek 

- List tabuliek bucketu

#### Eventy

- Eventy bucketu

### Tables

- Detail tabulky (zfunkcni sa odkaz zo sidebaru, atributy zatial neriesme)
- Detail tabulky - nastavenie PK
- Detail tabulky - lastest imports graf
- Detail tabulky - vypis stlpcov
- Detail tabulky - pridanie stlpca a zmazanie stlpca
- Description tabulky - prehodit do detailu (usetrime tab)

#### Eventy tabulky

- List eventov

#### Data sample 

- Data sample

#### Graf

- Tab Graf tabulky

#### Snapshot a Restore

- Vypisy
- Vytvorenie snapshotu
- Zmazanie snapshotu
- Vytvorenie tabulky zo snapshotu
- Time travel restore

#### Akcie nad tabulkou

- Export tabulky
- Load do tabulky
- Truncate tabulky
- Zmazanie tabulky
- Odkazy na time travel restore a Create snapshot

#### Files

- List suborov (tu treba dorobit reload), moznost nasitat dalsie (Load more) + skopirovanie file URL do schranky
- Filtrovanie jobov (search bar + search hint)
- Upload noveho suboru (toto bude celkom zaujimave, je tam progress bar a pod.)
- Stiahnutie normalneho suboru (kbc-sapi-files)
- Stiahnutiue sliced suboru (opat zaujimavejsie, je tam Prepare Package az tak nasledny download)

#### Jobs

- List jobov (vpravo v tabulke je reload), moznost nacitat dalsie (Load more)
- Detail jobu (modal)

**Comment by ujovlado** [comment]
Tu je vlastne nastrel, co by mohli byt komponenty: https://github.com/keboola/storage-api-console/tree/3129d194f6a2b4b7e45d1be2e3de3495eb918561/app/scripts/directives. Netreba sa toho ale striktne drzat, urcite na niektore uz alternativy v kbc-ui mame.

**Comment by ujovlado** [comment]
Mozes si to pripadne skusit rozbehnut (https://github.com/keboola/storage-api-console), je to apka v coffee :trollface:  +Angular 1.

Len pre istotu - je to sekcia "Storage" v KBC, keby si chcel preklikavat (ta co pri lokalnom kbc-ui nefunguje).

**Comment by natocTo** [comment]
Vidím no, děsivá kombinace pro mě když ani jedno z toho neznám, ale něco z toho určo vykoukám.

Tam je odkaz na https://storage-api-console.keboola.com/ tak toto vlastně potřebuji dostat do KBC-ui (cca vzhledově)?

**Comment by ujovlado** [comment]
Ano, tak ako pises - ak by si to chcel kukat "standalone". Inac je to sekcia Storage, ked si pozeras projekt v KBC: 
https://connection.keboola.com/admin/projects/PROJECT_ID/storage#/

Momentalne je to technicky spravene tak, ze ked si prave na stranke Storage, tak je tam nacitana ina apka (https://github.com/keboola/kbc-ui-storage), ktora v sebe obsahuje `storage-api-console`.

Toho sa prave chceme zbavit a jedina apka, ktora sa ti bude nacitavat bude kbc-ui. Co bude dalsi krok k tomu aby sa z toho stale komplet sandalone SPA.

**Comment by ujovlado** [comment]
> Přemášlím zda nemám víc rád coffee nebo Angulár a myslím že Angulár vede :), vůbec se v tom nevyznám a furt musím hledal pomocí "find all", abych vůbec něco dohledal v tom projektu.

Ak by ti z toho islo "uthnut dekel", daj vediet, kludne ti s tym niekto pomoze ;). Tym, ze tam nic nevies najst sa netrap - ked som tam potrebvoal nieco dorobit/najst, robil som to uplne rovnako. Teoreticky sa v tom coffee nemusis hrabat. Myslel som to len ako doplnok (to mazanie, co som spominal), aby sme na nieco nezabudli

> Tady je teda potřeba co nejvíce se držet toho co je v originále? Nebo to může odevzdávat i trochu jiné a pak se domluví co jak bude.

Je to urcite na dohode. Nikto ta nebude cepovat za to, ze to nie je 1:1. Ide len o to zachovat klucovu funkcionalitu. T.j. ak tam bol search, musi byt aj v preklopenej casti - nemusi vsak byt 100% rovnaky.

> Jde mi o ty eventy, tam asi můžu částečně využít ty "sapi-events" z kbc-ui myslím. Tam se ten detail otevírá jinak, což si předělám u sebe na modal. Ale třeba to hledání nahoře má v originálu to help apod. To je potřeba taky přenášet? Nebo třeba ten search button. Když použiji SearchBar z Indiga tak ten tlačítko "Search" nemá tuším.

Ano, kludne vyuzi sapi-events, ak to pojde. Tie sa myslim reloaduju same a v Storage bol na to button. Detail eventu nemusis robit na modal. Ak tam osatne ta "informacia", kludne nech je to tak ako v kbc-ui. Cim viac existujucich komponent vyuzijeme, tym lepsie.

Kludne to rob tak, ako pises, ze nejasnosti sa doriesia v ramci reviews PR. Myslim, ze ten pomer zachovania funkcionality a ako to bude vyzerat budes vediet odhadnut celkom ok.

**Comment by natocTo** [comment]
Jo dík za info. Event už jsem včera začal do modalu tak to nechám tak do odevzdání případně pak upravím.
Ještě zkusím nějak obyč ten sidebar vlevo a pak bych odevzdal ten "init". Zatím to je jen "čtení" tak to jde docela ok.

**Comment by odinuv** [comment]
kdyz se to merguje po kouskach do mastra, bude to nejak pristupny pres ficuru?

**Comment by natocTo** [comment]
Tak kupa PR poslána. Doufám že to nebude totálně mimo a nebude potřeba vše předělat (nějak více). :)

Budou tam napříč PR nějaké duplicity. Nebo kód který bude fajn extrahovat do komponenty. Ale podle mě se to bude dělat daleko lépe až tam ten základ bude celý a bude se to ladit, ať už bugy nebo právě refaktoring aby to bylo lepší.

Ještě teda z toho základu furt něco chybí.
- modaly jako Nová tabulka nebo Export tabulky či Load to tabulky
- description jsem tu Bucketu i Table zatím nedělal
- ještě u Table mám poznámku něco o "synchronize columns"

Pak samo celé ty sekce Files a Jobs. Ale ty nebudu asi vůbec začínat dokud nebude většina toho základu.

**Comment by ujovlado** [comment]
> kdyz se to merguje po kouskach do mastra, bude to nejak pristupny pres ficuru?

@odinuv ak si spustis lokalne UI, tam je normalne odkaz v sidebare ... nemalo by to byt komplikovane

**Comment by ujovlado** [comment]
@natocTo super! ja tie PR skusim odbavit co najskor, vrhnem sa na to hned po Zendesku ;)

**Comment by natocTo** [comment]
Jak budou řešeny ty sekce Jobs a Files? Nějaký tam na indexu? Nebo jobs se nějak dostanou do těch co již v aplikaci jsou? Jakože nějaký checkbox tam (storage jobs nebo nevím).

**Comment by natocTo** [comment]
Na Files jsem si udělal novou routu (storage-explorer/files) tak ten základ pošlu tam. 
Ta komponenta se případně bude moci přehodit pak jinam.

**Comment by ujovlado** [comment]
Toto issue uz nebude treba, blizime sa ku koncu.
