### ISSUE TITLE
GD jobs

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#241]
Ať dělám co dělám, vždycky se rozbalí Tasks i když bych chtěl koukat na Storage Stats (https://connection.keboola.com/admin/projects/258/jobs/122063437?q=)

**Comment by Halama** [comment]
U writeru se defaultně otvírají Tasks. Měly by se otevírat spíš stats jako jinde? Nebo ti nejde se přepnout do stats vůbec?

**Comment by Halama** [comment]
už to vidím ono to znovu otevře pokud to zrovna běží, fixnem
