### ISSUE TITLE
Change in row does not automatically update version

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2413]
Updatenu něco v config rows komponentě (s3 extraktor třeba) a neupdatne se seznam posledních verzí. API call proběhne, eventy taky, takže bude asi někde chybět store mixin.

**Comment by natocTo** [comment]
To je stejné jako toto #2373 ?

**Comment by ondrejhlavacek** [comment]
haha, jo, díky, zavírám
