### ISSUE TITLE
Orchestration tuning

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2420]
Probrat, zda ma cenu zaimplementovat nasledujici navrhy
- tlacitka vprav by sli udelat cisteji - pri hoveru je videt, ze to nezabira celou sirku
- klikaci sloupce grafu, zkratit delay hoveru
- created by?
- vylepsit UI/UX scheduleru
- vylepsit UI/UX task editoru
- vylepsit UI/UX notifikaci
- updates doprava?
- token klikaci?

**Comment by Halama** [comment]
hlasoval bych určitě za zrušení editačních stavů tasků a notifikací. Pak to nastavení toho scheduleru by asi taky bylo fajn přesunout na samostatnou stránku nebo zakomponovat do současné? trochu překvapí že vyskočí v modalu narozdíl od zbytku:)

**Comment by janmichek** [comment]
Reaguju na to co vcera feedbackoval Fisa.
Navadi me to k puvodnimu navrhu, co jsem navrhoval tady https://github.com/keboola/kbc-ui/issues/2224#issuecomment-433128136

Vzal bych to iterativne pres to ze presuneme scheduler z modalu na podstranku a zrusime ty editacni stavy, respektive udelame je jako ve zbytku aplikace tedy takhle:

![image](https://user-images.githubusercontent.com/15363559/49220046-61d91380-f3d5-11e8-8cf1-e1e19682c448.png)


![image](https://user-images.githubusercontent.com/15363559/49220053-643b6d80-f3d5-11e8-878d-2d64922a5f65.png)


detto Tasks

**Comment by ujovlado** [comment]
Isiel by som na to postupne:

- PR na vyhodenie static stavu Notifications
- potom PR na vyhodenie edit stavu Tasks
- potom prehodenie Schedule na samostatnu podstranku

^ Ked to bude ready (vsetky tri casti sa budu editovat rovnako, na samostatnych podstrankach), mozeme sa pobavit co dalej. A ak sa rozhodenem urobit to stylom https://github.com/keboola/kbc-ui/issues/2224#issuecomment-433128136, tak to bude len preskupenie komponent.

Takze kludne zacni s tymi statickymi stavmi a presunom schedule z modalu.

**Comment by ujovlado** [comment]
A k tym ostatnym.

> tlacitka vprav by sli udelat cisteji - pri hoveru je videt, ze to nezabira celou sirku

tam asi staci btn block

> klikaci sloupce grafu, zkratit delay hoveru

to by som zatila neriesil

> created by?

kludne, ak ide

> vylepsit UI/UX scheduleru
> vylepsit UI/UX task editoru
> vylepsit UI/UX notifikaci

to sa uvidi podla toho ako sa podari zrusenie static. stavov

> updates doprava?

ved to uz je,nie?

> token klikaci?

kludne

**Comment by janmichek** [comment]
Tady jsem na to vytvoril issues
https://github.com/keboola/kbc-ui/issues/2424
https://github.com/keboola/kbc-ui/issues/2425
https://github.com/keboola/kbc-ui/issues/2426
https://github.com/keboola/kbc-ui/issues/2427
