### ISSUE TITLE
DB writers  - set datatypes from metadata

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#2421]
Pokud přidávám novou tabulku do konfigurace writeru mělo by to nastavit datové typy sloupců z metadat tabulky kterou přidávám pokud jsou metadata k dispozici.

![image](https://user-images.githubusercontent.com/903531/49205537-9508ac00-f3af-11e8-85f3-a9070d5a20cc.png)

Mělo by fungovat tedy stejně jako předvyplnění datových typů pro input mapping transformace https://github.com/keboola/kbc-ui/pull/2287

Pro každý typ writeru (MySQL, Snowflake, Pgsql) je potřeba namapovat [basetypes](https://github.com/keboola/php-datatypes#base-types) uložený v metadatech.
Příklad mapování Basetype -> Snowflake type https://github.com/keboola/kbc-ui/pull/2287/files#diff-2f88828d7fc5b6e35bc99bea5f8c4c2eR172

Pokud by se to releasovalo po jednotlivých writerech tak Snowflake by měl být první.

Metadata mají zatím nastavené hlavně tabulky vytvořené db extractory.

**Comment by kacurez** [comment]
davalo by zmysel take nieco dorobit aj do gooddata writer ui? napada ma mapping:
- `Date, TimeStamp` -> DATE
- `String` -> ATTRIBUTE
- `Integer, Numeric, Float, and Boolean` -> FACT

Stym ze by sa vynechali stlpce ktore su sucastou primarneho kluce, alebo by sa nastavili na connection point(ak by bol iba jeden stlpec v PK)

**Comment by Halama** [comment]
@pivnicek I've noticed you assigned this. But I know you have a lot of backend stuff in backlog now. Maybe it can be done by someone other?

**Comment by pivnicek** [comment]
@Halama yes, of course!

**Comment by Halama** [comment]
Zatím je to nasazené jenom pro Snowflake. Mělo by se to dodělat i pro další writery. Hodíte prosím issue?

**Comment by natocTo** [comment]
@kacurez ty si mi to PR #2607 hezky komentoval, takže asi víš o co gou a poradil by sis s tím, nebudeš mít někdy prostor na to mrknout? Myslím "pouze" to mapování. Já bych to pak napojil a rozjel podobně jako u Snowflake.

**Comment by kacurez** [comment]
@natocTo jedna sa o mapovanie **``keboola basetype -> specific db type``**
tu najdes zoznam specific datovych typov pre kazdy db writer
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/wr-db/templates/dataTypes.js
pre kazdy datovy typ daneho writeru(componentId) by mal byt urceny [keboola baseType](https://github.com/keboola/php-datatypes#base-types) teda jedna z moznosti `STRING, DATE, TIMESTAMP, INTEGER, NUMERIC, FLOAT, BOOLEAN`
takze to mapovanie bude vypadat podobne ako u snoflwake
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/transformations/Constants.js#L82

pozeram ze okrem Snowflake existuje opacne mapovanie tj specific db type -> keboola basetype pre:
- Mysql - https://github.com/keboola/php-datatypes/blob/master/src/Definition/MySQL.php#L225
- Redshift - https://github.com/keboola/php-datatypes/blob/master/src/Definition/Redshift.php#L250

Z toho to teda mozes resp musis zobrat pre mysql a redshift. Pre ostatne writere(Pgsql, Oracle..) sa to mapovanie imho v 95% da v pohode urcit hned alebo sa popytaj na slacku v `#db-extractor`. 

V tom "95%" myslim aj urcenie toho ze take mapovanie neexistuje(napr blob). V takom pripade by sa malo nastavit asi [default data type](https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/wr-db/templates/dataTypes.js#L202) alebo ignore, kedtak pozri do snowflake wr ako sa to tam riesi..

je to cajk?

**Comment by kacurez** [comment]
teda mozno to nebude az 95% ale urcite vacsina, kazdopadne mozes zacat tymi co su dane(mysql a redshift) kde si to cele nejake genericky vybudujes a potom sa pre ostatne len urci mapping :)

**Comment by natocTo** [comment]
Díky. Zítra na to mrknu a uvidím zda si s tím poradím.

**Comment by kacurez** [comment]
jasne, kludne sa pytaj viac ked tak. 
ad "neurcitelny data type mapping" - sudiac podla tohto sa im teda nastavuje ignore a nie default data type
https://github.com/keboola/kbc-ui/pull/2607/files#diff-6dad59a0a0b590adbdb8dd437cbc6163R51

**Comment by natocTo** [comment]
Pak ještě tu https://github.com/keboola/php-datatypes/blob/master/src/Definition/Snowflake.php vidím že třeba `TIMESTAMP_LTZ` má basetype `TIMESTAMP`. V mappingu https://github.com/keboola/kbc-ui/blob/9622da1169c87639b420174d6ab2b0e4927e5c94/src/scripts/modules/transformations/Constants.js#L114 ale žádný basetype není .. je to pro mě pak zmatené :) asi to nechápu dobře

**Comment by kacurez** [comment]
ja by som povedal ze smerodatny je ten switch v `php-datatypes`:
https://github.com/keboola/php-datatypes/blob/master/src/Definition/Snowflake.php#L187

Neviem preco to neni rovnako aj v tom ui module [ui transformations/Constants](https://github.com/keboola/kbc-ui/blob/9622da1169c87639b420174d6ab2b0e4927e5c94/src/scripts/modules/transformations/Constants.js#L114) . Pozeram ze to robil Marc(@pivnicek) tak by sme sa mohli opytat jeho ked sa vrati z dovolenky :) Mozno kvoli tomu ze sa to pouziva v IM transformacii je to take osekane ajked k tomu nevidim dovod, ale by som radsej pockal.

btw [templates/dataTypes.js](https://github.com/keboola/kbc-ui/blob/9622da1169c87639b420174d6ab2b0e4927e5c94/src/scripts/modules/wr-db/templates/dataTypes.js#L114) je len vycet vsetkych datovych typov ktore su podporovane v snowflake db a niektore nemusia mat basetype.

Ked tak zacni s MySQL a Redshift podla php-datatypes pretoze tam to je jasne dane a zbytok sa uvidi.

**Comment by natocTo** [comment]
Super. Díky. Připravím jen ty soubory na mapping jako super základ a pak se to dolatí a dořeší. Díky

**Comment by JakubMatejka** [comment]
@natocTo jak je tohle cca náročný? Teď nevím kolika komponent by se to mělo vlastně týkat, apod. Za chvíli to bude poslední věc k https://github.com/keboola/internal/issues/97 tak by bylo fajn, kdyby se to dalo odbavit. ;o)

**Comment by natocTo** [comment]
No tam sám nevím, toto pro mě bylo dost takové "nové". Jakože sám moc nevím jak komplikované to nakonec bude. Tam jsem musel začít tím že doplním ty basetypy pro ostatní writery. To jsem zkusil vykopnout hned. To je odesláno na review už déle.  #2938
Jakmile se to dostane do masteru, tak k tomu zkusím sednou na den a snad budu schopen lépe říci nějaký odhad.

**Comment by natocTo** [comment]
Tak nakonec to vypadá že pro ty DB-WR by to mělo být snadné implementovat. PR už je odeslaný.
Musí se asi ještě vyladit to úvodní mapování ale myslím že to bude brzo ready.
