### ISSUE TITLE
Cannot move deprecated configuration to trash

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2423]
The overview page tells me I have deprecated components, so I try to delete the configurations and get this

![image](https://user-images.githubusercontent.com/569139/49221163-a2865c00-f3d8-11e8-8fa0-9752e95930f6.png)

How can I get rid of deprecated components?

**Comment by Halama** [comment]
some of them are physically delete from syrup so you have to delete it using by api.
But restbox is still installed so you should be able to delete it. check the message in pt.

**Comment by pivnicek** [comment]
jo, it's more of a backend issue, you're right.  I'll make it elsewhere and close this.
