### ISSUE TITLE
Správa projektů - chybí okraje

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#243]
Když si rozkliknu nějakou organizaci s KBC projekty, na některých místech chybí nastavený padding (viz. obr.).
![keboola cz keboola connections 2015-06-29 08-59-52](https://cloud.githubusercontent.com/assets/12933713/8402654/9078155e-1e3d-11e5-8517-6716a51d1712.jpg)

**Comment by Halama** [comment]
čekáme na nařezání viz. #128

**Comment by Matejkys** [comment]
Ok, sorry za duplikát. Smazal bych to, ale nevim jak :)

**Comment by Halama** [comment]
v pohodě zavřu to pak až to bude hotový
