### ISSUE TITLE
Transformations - Clone input mapping

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#2430]
Dependent on https://github.com/keboola/transformation-bundle/issues/124
Fixes https://github.com/keboola/connection/issues/1632

![image](https://user-images.githubusercontent.com/497675/48843407-3fbd1100-ed97-11e8-9572-fc80f5dae102.png)

![image](https://user-images.githubusercontent.com/497675/48843412-49df0f80-ed97-11e8-8ebd-b1eac190aa70.png)

**Comment by Halama** [comment]
Ještě k tomu doplním že [clone mapping](https://keboola.docs.apiary.io/#reference/workspaces/load-data-using-clone/load-data-using-clone) nejde použít pro všechy tabulky:
- Podporuje pouze tabulky které leží ve Snowflake bucketu 
- Podporuje [aliasy](https://keboola.docs.apiary.io/#reference/table-aliases/create-table-alias/create-new-alias-table) které nemají nastavený filtr a mají nastaveno `aliasColumnsAutosync=true`

Myslím že by to normálně mělo nabízet všechny tabulky a při výběru jedné z výše popsaných pro CLONE mapping by to nemělo povolit uložit a mělo říct že daný typ tabulky není podporovaný

**Comment by Halama** [comment]
V konfiguraci bude nový nepovinný parametr load type který může mít jednu z hodnott `full` (defaut) a `clone` (nový typ im).
```json
{
          "output": [],
          "queries": [
            "-- This is a sample query.\n-- Adjust accordingly to your input mapping, output mapping\n-- and desired functionality.\n\n-- CREATE TABLE \"out_table\" AS SELECT * FROM \"in_table\";"
          ],
          "input": [
            {
              "source": "in.c-csv-import.nova",
              "destination": "nova",
             "loadType": "clone"
            }
          ],
          "name": "test",
          "packages": [],
          "requires": [],
          "backend": "snowflake",
          "type": "simple",
          "id": "468408317",
          "phase": 1,
          "disabled": false,
          "description": ""
        }
```

**Comment by ondrejhlavacek** [comment]
Ještě by se to mělo dát zvolit i v generickým sandboxu 

![image](https://user-images.githubusercontent.com/497675/49450250-eb755080-f7dc-11e8-8544-7661ca6cca17.png)

**Comment by Halama** [comment]
Backend by měl být nasazený dnes nebo zítra.

**Comment by Halama** [comment]
Ten generickej bych klidně udělal jako separátní issue.

**Comment by kacurez** [comment]
@martin nerozumiem tvojmu komentu v https://github.com/keboola/kbc-ui/issues/2430#issuecomment-443148308

>Myslím že by to normálně mělo nabízet všechny tabulky a při výběru jedné z výše popsaných pro CLONE mapping by to nemělo povolit uložit a mělo říct že daný typ tabulky není podporovaný

nemalo by to byt skor naopak tj `při výběru jine nez z výše popsaných pro CLONE mapping by to nemělo povolit uložit `

**Comment by Halama** [comment]
jo mělo, upravil jsem to. dík

**Comment by kacurez** [comment]
este mi z dokumentacie neni jasna jedna vec: https://keboola.docs.apiary.io/#reference/workspaces/load-data-using-clone/load-data-using-clone
> The cloned table will contain all columns of the source table (all of them as VARCHAR(1048576)) and a _timestamp system column 

je potreba nastavit vsetky columns na `VARCHAR(1048576)` alebo vyresetovat data types a skryt sekciu `Data types` ? a co ostatne inputy(Columns, Changed In Last,  Data Filter)? 

![image](https://user-images.githubusercontent.com/1412120/49518858-f6dd8000-f89f-11e8-9ecb-c5274f2caa4d.png)

**Comment by Halama** [comment]
@kacurez nic z toho tam nebude. Clone podporuje jenom source a destination.
