### ISSUE TITLE
Show full datetime on configuration versions list

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2431]
Currently when trying to match a job execution with a configuration version it shows in the versions list the relative date

![image](https://user-images.githubusercontent.com/569139/49230420-eafd4400-f3ef-11e8-888d-368533d6bdbf.png)

imho it would be more useful to show the updated timestamp.

**Comment by kacurez** [comment]
just a quick hint: if you set mouse pointer on the text or the calendar icon then after a while the timestamp should popup in a tooltip.

**Comment by pivnicek** [comment]
aha, I didn't know that:).  it doesn't completey help when you need to compare though, but thanks!
