### ISSUE TITLE
Duplicate metadata store

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2439]
https://github.com/keboola/kbc-ui/blob/14621a616d24b8cc7b6c55816ead2a40ccef9087/src/scripts/modules/components/stores/MetadataStore.js#L133-L145

^ I think this means, that whole `metadata` part from `MetadataStore` is duplication of what we alraedy have in `StorageTablesStore`

**Comment by pivnicek** [comment]
What is required here is translate the methods at the top of this store to access their data from the main storage store

**Comment by ujovlado** [comment]
Related to: #2436

**Comment by ujovlado** [comment]
Another one: it can be very useful to pass `table` object to some function and it will filter it and return metadata
