### ISSUE TITLE
Pole pro drobečkovou navigaci floatuje v prostoru

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#244]
Zkoušel jsem orchestrace, joby, extraktory, ...

![screen shot 2015-06-29 at 14 18 14](https://cloud.githubusercontent.com/assets/497675/8418689/b8e833bc-1e69-11e5-87d9-8fe08523a0cb.png)

![screen shot 2015-06-29 at 14 18 18](https://cloud.githubusercontent.com/assets/497675/8418692/bbf32314-1e69-11e5-857b-e4a41c70dda6.png)

**Comment by Halama** [comment]
je to tím že tam není updatnutý kbc-bootstrap, vrátil jsem předchozí verzi kbc-ui. Pak to aktivuju až nasadím ten nový bootstrap
