### ISSUE TITLE
Stránka projektů reaguje špatně na rozlišení

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#245]
Předtím to nedělalo, ale nyní se mi objevuje na stránce projektů horizontální scroll bar a vidím černé okraje vedle background image.
Zkoušeno na dvou prohlížečích, velkém monitoru a ntb display.
![your projects keboola connections 2015-06-30 13-58-49](https://cloud.githubusercontent.com/assets/12933713/8430385/2380e94a-1f31-11e5-84d4-fc2a1194cd5e.jpg)

**Comment by Halama** [comment]
@JakubMatejka Potvrzuju že mi to dělá taky pokud si zapnu scrollbary. Dělá to i v demo režimu http://localhost:8000/examples/projects-list.php

**Comment by Matejkys** [comment]
Vidím, že to Jakub dal closed a nenašel jsem podobný issue. Tak pro jistotu pro info dávám screen, že to mám pořdá špatně.

![your projects keboola connections 2015-07-01 09-43-22](https://cloud.githubusercontent.com/assets/12933713/8449911/e6d34600-1fd5-11e5-97dc-ef0bd6b64b97.jpg)

**Comment by Halama** [comment]
my tady ty issue zavíráme v moment kdy to je "naprogramovaný". U některých věcí ale nějakou dobu trvá než se dostanou do produkce, to bude asi tenhle případ. Dám vědět až to bude nasazený.

**Comment by Matejkys** [comment]
Ok, dobrý vědět :) Sorry za zdržování.

**Comment by Halama** [comment]
tak teď :)
