### ISSUE TITLE
spodní menu v projektu nejde scrollovat

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#246]
![image](https://cloud.githubusercontent.com/assets/1427901/8430709/b74204c8-1f33-11e5-9f16-8af8972a741d.png)

**Comment by Halama** [comment]
duplikuje #242

**Comment by Halama** [comment]
Proč se to ale rolluje dolu místo nahoru je mi ale záhadou. Chová se ti to takhle pořád?

**Comment by Halama** [comment]
Aha, tak už to mám dělá to na stránkách který nejsou součástí hlavní appky

**Comment by Halama** [comment]
fixnuto
