### ISSUE TITLE
Active/Disable tlačítka u tasků orchestrace

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#248]
Přijde mi divný, že u neaktivních tasků je křížek s nějakou modrou barvou, která se nikde jinde v UI nevyskytuje. Podle mě by to mělo být bílé jako u ostatního.
K tomu se váže ještě jedna věc. I když už jsem to dělal několikrát, mám neustálou tendenci na ty pousvníky klikat, abych to změnil (a to klidně několikrát za sebou, než mi dojde, že musim dát Edit). Obyčejná fafjka a křížek k tomu nelákaly.

![tasks 2015-07-01 09-23-34](https://cloud.githubusercontent.com/assets/12933713/8449606/401172d0-1fd3-11e5-9821-c75acc13ed05.jpg)

**Comment by Halama** [comment]
díky, z toho mám stejný pocit. Vrátím tám zatím asi ty křížky které jsou jinde. Tohle bych použil jenom tam kde to skutečně něco edituje.

**Comment by Halama** [comment]
nebo to použiju v editačním režimu, tak to imho vlastně bylo myšlený. cc @JakubMatejka
