### ISSUE TITLE
ex-db-generic strip processors from config for synch actions

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2480]
In preparing the config for synch actions `testConnection` and `getTables`, any extraneous configuration like processors should be excluded.

**Comment by natocTo** [comment]
I can look on this. But I have no clue what should be done. :) 

I tried log variable "params" of  "getSourceTables" function but there was only "params.configData.db and params.configData.tables[]". Can I found somewhere what are allowed "params"?

**Comment by ujovlado** [comment]
I think this should be done in extractor itself. If action is `testConnection`, it should ignore not related parts from config

**Comment by pivnicek** [comment]
Yes, I agree with you, I'll make issues in the appropriate repos and then close this.

**Comment by pivnicek** [comment]
ok, we'll solve this on the backend. dik.
