### ISSUE TITLE
Smaller margin on AlertBlock?

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2496]
Momentalne je tam 20px, tuna trosku vidno, ze to nesedi:
https://github.com/keboola/kbc-ui/pull/1871#issuecomment-415011974

Nemalo by tam byt menej? 16?

**Comment by ujovlado** [comment]
`IndexLegacyCompatibilityWrapper.jsx`

**Comment by janmichek** [comment]
Ok, zkusim prozkoumat tohle pouziti komponenty, ale sama o sobe zadny margin nema

**Comment by ujovlado** [comment]
teraz je tam:

```jsx
<div>
          <LegacyUIMigration />
          <GenericDockerDetail />
        </div>
```

a opravilo by sa to keby tam bolo:

```jsx
<div className="container-fluid">
          <LegacyUIMigration />
</div>
<GenericDockerDetail />
```

lebo:

```css
.kbc-main>.container-fluid {
    margin: 15px 15px 15px;
    padding: 0;
}
```


^ ale tex jsx nie je valid, takze to treba poriesit inak
