### ISSUE TITLE
Error: undefined

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2501]
https://sentry.io/keboola/keboola-connection-ui/issues/790493670/?referrer=github_plugin

```
Error: undefined
  at Array.forEach (<anonymous>)
...
(19 additional frame(s) were not displayed)
```

**Comment by ujovlado** [comment]
sqldep hodil 502

**Comment by natocTo** [comment]
Toto zavřu. Díky tomu PR co tu je zmíněné by ty hlášky měly být lepší.
