### ISSUE TITLE
V Transformacích nejde dělat fork

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2521]
Nejde ve verzích dělat fork do jiné cfg:

Tady je to vidět: https://connection.eu-central-1.keboola.com/admin/projects/290/transformations/bucket/11184791/transformation/11787756/versions

![image](https://user-images.githubusercontent.com/1427901/49795441-44dc0300-fd3a-11e8-8988-a83d91d1331b.png)

**Comment by ondrejhlavacek** [comment]
No nejde, zatím to u rows (transformace ani komponenty) v UI nepodporujeme.

**Comment by padak** [comment]
něco mi uniká? doteď jsme to používali, od kdy to nejde? 
(jediný kde to nešlo, byl orchestrator)

**Comment by ondrejhlavacek** [comment]
Doteď jsme to nepoužívali, verze transformací jsou tam teď asi týden nově - bacha, pleteš si to s bucketama a konfiguracema.

**Comment by padak** [comment]
V jiném projektu to funguje OK
![image](https://user-images.githubusercontent.com/1427901/49796268-840b5380-fd3c-11e8-8e72-64125543814f.png)

něco mi hrozně uniká :)

**Comment by ondrejhlavacek** [comment]
V tom druhým screenu se díváš na bucket.

**Comment by padak** [comment]
TVL, jo!! Díky :)
