### ISSUE TITLE
unused dependencies in UI

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2531]
Projel jsem  repozitar prikazem 'depcheck' a tohle mi vyjelo jako nepouzivany dependencies.
U tech devDependencies, to nepoznalo pouziti ve webpacku ale Unused dependencies mi pripada ze sedi. Cheme to nejak dal resit @ujovlado ?

C:\DEV\kbc-ui>depcheck
Unused dependencies
* depcheck
* intl
* react-addons-clone-with-props
* react-markdown
* remarkable
Unused devDependencies
* babel-core
* babel-jest
* babel-loader
* css-loader
* enzyme-to-json
* eslint-loader
* file-loader
* less
* less-loader
* react-hot-loader
* style-loader
* url-loader
* webpack-cli
* webpack-dev-server
* worker-loader
Missing dependencies
* find-cache-dir
* fbjs
* lodash
* worker-loader?inline!.
* qs

**Comment by ujovlado** [comment]
No treba to checknut ak to chces povyhadzovat :) Napr. na `react-addons-clone-with-props` uz je PR: https://github.com/keboola/kbc-ui/pull/2482

**Comment by janmichek** [comment]
Videl jsem prave ze to resite. Dobre, muzuto overit a postupne v PR povyhazovat.

**Comment by natocTo** [comment]
Jsem jen na telefonu, ale ten seznam je podezdřelí. Myslím že většina bude omyl a jsou potřeba, ale třeba se něco najde co je navíc. Jako je třeba to clone-with-props. :)

**Comment by janmichek** [comment]
tak jsem si to projel.

Nikde nevidim naimportovany tyto 2 package 'react-markdown' a 'remarkable'
Respektive 'remarkable' si stahne sam jako svoji dependecy 'react-remarkable', takze neni nutny to implicitne uvadet.

Vyzkousel jsem bez packagu a funkcionalita markdownu je zachovana.
![image](https://user-images.githubusercontent.com/15363559/49862856-56d3a980-fdff-11e8-91c1-77ab49c7dc07.png)

**Comment by janmichek** [comment]
Vyhodim teda ty 2 packages v PR co sem prilepim
