### ISSUE TITLE
GoodData title and Type not aligned

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#2534]
Název v GD a typ sloupce nejsou ve writeru zarovnané na střed, jako je název sloupce.
![table out c-main objednavky 2018-12-11 17-49-30](https://user-images.githubusercontent.com/12933713/49816074-6acecb00-fd6d-11e8-9579-6fa39cc332d3.png)

**Comment by ujovlado** [comment]
Nebudeme riesit. Na ceste je novy writer.
