### ISSUE TITLE
zobrazovadlo JSONů by mohlo skrývat citlivá pole

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#254]
začal bych s passwordem a pak budeme nějaký další přidávat, bude tam zámeček. když dělám screenshot, musím to začerňovat

**Comment by ondrejhlavacek** [comment]
@Halama mam to hotové, ale nemůžu publikovat do https://www.npmjs.com/package/kbc-react-components, můžeš mi tam přidat uživatele `najlos`?

**Comment by Halama** [comment]
@ondrejhlavacek jsi tam. Jinak uz jsem to releasnul
