### ISSUE TITLE
Event detail doesn't work for event above limit

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2540]
Detail eventu v detaile jobu.

![screenshot_2018-12-12_14-25-45](https://user-images.githubusercontent.com/419849/49872736-4aa91580-fe1a-11e8-8302-3b171357b194.png)

Problem vyzera byt v tom, ked sa tam da link na event, ktory je az za "Load more" a konkretny detail eventu sa prepise tym fetchom prvych eventov.

@natocTo viem, ze sme to riesili spolu, kukol by si to pls este raz?

**Comment by ujovlado** [comment]
Len pre istotu:

- v detaile jobu mam prvych X eventov ... kliknem na X., dam refresh, vsetko je ok ...
- v detaile jobu mam prvych X eventov  ... kliknem na Load more, potom kliknem X+1., dam refresh a nefici.

**Comment by natocTo** [comment]
Mrknu.
