### ISSUE TITLE
config rows TableColumnsEditor fail on nonexisting table

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2543]
ked si v config rows based writery(google big query, gooddata writer v3) nakonfigujurem tabulku, nasledne ju zmazem zo storage tak pri otvoreni stranky detailu config row-u to spadne kvoli neexistujucej tabulke

`TypeError: Cannot read property 'get' of undefined`:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/configurations/utils/createColumnsEditorSection.js#L43

**Comment by natocTo** [comment]
Toto sem asi nepatří ale jak teď přepisuji storage tak jsem se setkal ještě s tímto. 
Je dost pravděpodobné že to je správné chování ale toto co tu píšeš mi přišlo podobné tak to sepíši.

Založil jsem si Old Google Writer. Pak jsem ve Storage při přepisování smazal danou tabulku. Nyní nemůžu zobrazit detail toho writeru což je logické asi když jsem to smazal. Ale zároveň writer ani nejde smazat. Takže ho tam asi budu mít navěky :) 

`Wrong configuration: SYS bucket don't exists wr-google-drive-33015a025ec1dc8a3b852028d23c1b72`
