### ISSUE TITLE
GA url parsing bug

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#2547]
![hu](https://user-images.githubusercontent.com/15363559/49933945-5b669380-fecd-11e8-8a9e-ab843dab068c.gif)

**Comment by kacurez** [comment]
jn tam je problem ze vytvaras query bez dimenze, a to sa predpoklada ze tam bude inac je ta query nevalidna/nekompletna. Na druhu stranu by to ui malo aj taku neuplnu query vediet zparsovat, ajked to asi nebude bezny case.
