### ISSUE TITLE
OAuth Credentials migration

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#2549]
Update migration tool to allow migration of OAuth configurations to the new OAuth API v3.

- I want to create the migration as a page (not as a modal like in previous migrations).
![Alt text](https://monosnap.com/image/Ln0yxyBCe4jpUXNmOktSMF5QMTOh1e.png)

- On this page, there will be list of all configurations of all components that are using OAuth authorization.

- (?) user could select/deselect by checkboxes which configurations to migrate and which not

- Big button to migrate all the configurations

- (?) backend: Migrate all configurations in one job, job per compoennt or job per configuration?

- the page will also display status of the configurations and a link to migration job(s)

**Comment by MiroCillik** [comment]
Este som to konzultoval s Kacurezom.

Ten navrhol aj to, ze by tuto migraciu vobec uzivatel neriesil, ale ze by som to potichu zmigroval. Po projektoch napriklad. 

A potom ako aj vyssie pisem, rozmyslam, ze ci spravit jeden job pre vsetkych konfiguracie v projekte, alebo spravit tolko jobov kolko je konfiguracii, co moze byt dost vela..

**Comment by MiroCillik** [comment]
Pre niekolko komponent bude treba configy reautorizovat. Viz https://github.com/keboola/oauth-api/issues/100
 - esnerda.wr-zoho-crm
 - keboola.ex-twitter v EU
 - keboola.ex-github

Keby sme sa rozhodli pre "tichu" migraciu, tak by sme zobrazili warning (na overview, v komponente, v detaile konfigu), ze to ma deprekovany oauth a ze je nutne to reautorizovat

**Comment by ujovlado** [comment]
> Ten navrhol aj to, ze by tuto migraciu vobec uzivatel neriesil, ale ze by som to potichu zmigroval.

To je celkom dobry napad. Ak je to z pohladu usera transparenta zmena (ak vsetko bude fungovat a netreba jeho zasah), tak o tom vobec nemusi vediet.

Naopak, tam kde to treba reautorizovat by som to asi nechal prave na nich - nech si to zmigruju sami a reautorizuju. S tym, ze by na to mali nejaky cas (to by mohlo prave upozornovat UI). Po uplynuti toho casu, by sme to nakoniec zmigrovali my (reautorizacia by  ale stale bola na nich)

**Comment by Halama** [comment]
potichu nikdy nic nemigrujeme, vzdy by to mel odpalit uzivatel. Viz. třeba migrace na config rows. Je to změna v konfiguraci to nemůžeme jen tak přeprasit.

**Comment by Halama** [comment]
potichu jsme migrovali jenom interní věci které uživatel nemůže nijak ovlivnit jako jsou ES backendy apod. Tohle je ale uložené přímo v tom configu, do toho sahat nemůžeme ani na to naštěstí nemáme žádné prostředky jak to udělat.

**Comment by ujovlado** [comment]
Tak to som potom nepochopil. Myslel som, ze "potichu" => bez zmeny konfiguracie.

**Comment by MiroCillik** [comment]
No v konfiguracii sa zmeni len to, ze sa tam prida "oauth: v3".

**Comment by MiroCillik** [comment]
Spravim na to teda tu stranku ako pisem. Tie stavajuce migracie (ten modal) necham tak ako su.

A tato nova stranka sa pripadne moze znovu pouzit na nejake migracie v buducnosti.

**Comment by Halama** [comment]
jo udělej to tak jak to bylo připravené https://github.com/keboola/oauth-api/issues/83

**Comment by MiroCillik** [comment]
Dobre, len sa na to pre istotu pytam este raz. Tu som chcel riesit implementacne detaily tej migracnej stranky.

**Comment by MiroCillik** [comment]
Takze uzivatel uvidi na tej stranke zoznam vsetkych konfiguracii, ktorych sa ta migracia tyka.

Checkboxy tam davat nebudem, proste musi zmigrovat vsetko naraz. OK?

Chcel by som to zmigrovat v jednom jobe, aby som to nezahltil 100 migracnymi jobmi. 

V zozname konfiguracii bude stav migracie, co sa zisti z konfigu podla toho atributu `"oauth": "v3"`.

Keby nahodou ten job failol a zmigroval len niektore konfigy, uzivatel job spusti znovu a zmigruje to tie co nemaju v3.

Tym som si asi odpovedal na vsetky nejasnosti, napada vas k tomu este nieco plz?

**Comment by Halama** [comment]
jo já bych řekl že takhle dobrý. Potom bych bud tam nebo na statusu zmínil proč to děláme a co to přinese nového do budoucna. at to nevypadá jako nějaká migrace na prázdno:)

**Comment by ujovlado** [comment]
Tam by si to potom este mohol rozdelit do dvoch casti. Tie co netreba reautorzovat a tie co treba. Pripadne tie komponenty co treba reautorizovat, by sa mohli dat zmigrovat aj po jednej -> aby sa user neosral, ze vsetko zmigruje a ku "polovici" nebude mat moznost to rozbehat.

**Comment by MiroCillik** [comment]
Ok Ujo, v podstate tie co treba reautorizovat sa migrovat ani nebudu. Staci spravit tu reautorizaciu a ono sa to uz zalozi s tou novou verziou. Takze si to uzivatel spravi po jednom vlastne.

**Comment by MiroCillik** [comment]
- [ ] Preskocit komponenty, ktore nejdu zmigrovat
- [ ] Zobrazit "deprecated" box na stranke komponent a na overview
- [ ] Zobrazit loader a link na posledny job migracie
- [ ] Popis, preco migrujeme OAuth, umozni pridat nove featury ako refresh tokenov
