### ISSUE TITLE
gdrive ex editace detailu sheet

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#256]
když přejmenuju dst sapi tabulku, není to vidět v přehledu a musím dát reload

![image](https://cloud.githubusercontent.com/assets/1427901/8495079/fa3d7d64-216a-11e5-849d-d274fafbab5c.png)

po reloadu mu to začne zase psát první písmenko malejma - proč proboha? 

![image](https://cloud.githubusercontent.com/assets/1427901/8495092/1a95111c-216b-11e5-9b78-f9720998965f.png)

**Comment by kacurez** [comment]
neupdatovane premenovanie tabulky sa mi nedari nasimulovat:
@padak mozes to popisat?
http://youtu.be/_zaT8zGo39U

co sa tyka dekapitalizace prveho pismenka tak tiez neviem, som si isty ze UI to nijak neupravuje sama od seba, takze to bude asi chyba backendu.

**Comment by padak** [comment]
Přeměňuje tabulku, dám save a pak můžu jen drobečkovou navigaci zpět kde to
není reflektovane

Sent from mobile
Dne 3. 7. 2015 11:18 AM napsal uživatel "Tomas Kacur" <
notifications@github.com>:

**Comment by kacurez** [comment]
potom co das save tak sa toci kolecko, ty sa medzitym vratis zpet ale save este nedobehol tak ti ukazuje staru hodnotu, das reload a mas to tam
ak by si nedal reload a pockal na indexe este 3-4 sekundy tak to tam naskoci premenovane(dobehol save)
je to vidno vtom screencaste co posielam vyssie.

kazdopadne beriem to ako nedokonaly ux, skusim stym nieco vymysliet a upravim to.

**Comment by Halama** [comment]
mohlo by se u toho řádku v seznamu sheetů ukazovat že se to ještě ukládá ale nevím jestli to není zbytečný

**Comment by kacurez** [comment]
pridam to tam aby na indexe ukazovalo loader pri premenovani tabulky
