### ISSUE TITLE
Search v Orchestraci

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2562]
Když vybírám co se bude spouštět, vlezu do komponenty a vidím její cfg, tak tam není search. Pokud je hodně cfgs, tak je to nepohodlný:

![image](https://user-images.githubusercontent.com/1427901/50157717-7755a500-02d2-11e9-82d5-692f22062b39.png)

**Comment by janmichek** [comment]
Jo, to dava smysl. Napadlo me jestli by zatim nestacilo mit jeden search (tak jako ted) a rozsirit ho, aby hledal i v konfiguracich a vysledek zgroupoval. Stejne tak jak se to deje na seznamu komponent/tf ( jednotne chovani pro uzivatele)

**Comment by padak** [comment]
V proce #1  by pomohlo, kdyby ty `+` byly "přidej, ale nezavři okno", takže by sis to prolistoval jednou a jen klikal. Nebo multiselect.

**Comment by janmichek** [comment]
Rozumim, to by taky usetrilo nejaky klikani. Jako blocker ale vidim to, ze mas nabidku konfiguraci v modalu, takze nevidis co pridavas do editoru. To UX mi prijde dost kostrbaty, zvlastni pattern. Kdyby ty ovladaci prvky byly vedle sebe, tak to by byla jina, ale bylo by potreba to vic rozkopat. Zatim mi prijde ze by to bylo spis matouci. Ten multiselect by mozna fungoval lip, ale taky je potreba to promyslet. Kazdpoadne to exportuju do dalsi issue. Myslim ze ta moje pripravena zmena to zase o neco zprehledni
