### ISSUE TITLE
Revert react-datepicker update

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2570]
```
warning "react-datepicker > react-onclickoutside@6.7.1" has incorrect peer dependency "react@^15.5.x || ^16.x".
warning "react-datepicker > react-onclickoutside@6.7.1" has incorrect peer dependency "react-dom@^15.5.x || ^16.x".
```
neviem ci to niecomu vadi ale radsej budem, ked tento warning neuvidim.

**Comment by natocTo** [comment]
Jasný. Oni to tam mají celkově nějak špatně značený. Ukazují že i verze 0.60 má jet na reactu 14 a přitom již verze 0.48 píše třeba toto a 49 už ani nenajede.

**Comment by natocTo** [comment]
Pošleš to nebo to mám nachystat? Tam se nic neupravovalo. Pouze instalace jiné verze.

**Comment by ujovlado** [comment]
Uz to mam, diky
