### ISSUE TITLE
Use another datetime picker

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2576]
Nasiel som toto, vyzera to relativne ok:

https://github.com/YouCanBookMe/react-datetime/

deps vyzeraju tiez fajn (react 13+)
https://github.com/YouCanBookMe/react-datetime/blob/master/package.json

**Comment by ujovlado** [comment]
@natocTo chcelo by sa ti to skusit? Mame to na 2 miestach, takze by to mohlo ist fajn.

**Comment by natocTo** [comment]
Jo mrknu.
