### ISSUE TITLE
Nařezání "malé" notifikace

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#258]
Nakonec se nám asi budou hodit. Měly by být schopný se nějak řadit pod sebe.
![image](https://cloud.githubusercontent.com/assets/903531/8496397/1e479302-2175-11e5-9010-d4692aa639cb.png)

**Comment by JakubMatejka** [comment]
Tady jsou: http://kbc-bootstrap-jakub-devel.keboola.com/examples/orchestrations-list.php

**Comment by Halama** [comment]
super diky. Mozna tomu jenom lehce stahnu ten padding.

**Comment by Halama** [comment]
ještě bylo možná fajn kdyby neměli fixní šířku, zkusím si s tím pohrát.
