### ISSUE TITLE
AdForm ex - nejde zmáčknout SAVE button

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2590]
V cfg adform extraktoru není možné zmáčknout SAVE tlačítko. cfg je vybraná ze šablony - je validní, nic tam nesvítí. Vidět je to tady https://connection.keboola.com/admin/projects/1438/extractors/ex-adform/472668811 - do projektu je možné vlézt.

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/kbc-ui/issues/2589 !
