### ISSUE TITLE
keboola.wr-dropbox-v2 destination folder validation

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2616]
![image](https://user-images.githubusercontent.com/4319320/50735059-af048e00-11a8-11e9-87b3-f970fedf5747.png)

destination folder name must not start or end with slash - i.e.:
- `/test/` -> invalid
- `test/` -> invalid
- `/test` -> invalid
- `test` -> valid
- `test/test2` -> valid

**Comment by natocTo** [comment]
Koukám to se nastavuje jako "Configuration schema".

Minimálně by tam šlo přihodit `description` pro tu property `folder`, třeba v tom znění "Destination folder name must not start or end with slash."

Případně pokud to zle tak přihodit `pattern` něco jako "^[^\/].*[^\/]$" nebo "^[^/].*[^/]$", to mi označuje valid/indvalid dobře (pokud napíši jen třeba "a" tak to teda taky hodí error což při psaní není nic moc). Nelíbí se mi že pokud ta validace neprojde, vypíše se error jakože to nesplněuje regex, což není moc informativní pro uživatele.

Myslím min ten popis by tam byl fajn.

**Comment by odinuv** [comment]
Jezismarja, ja si vubec nevsim, ze to je configschema, regex tam davat nebudem - jak pises. Pridam aspon ten popis

**Comment by natocTo** [comment]
Super, koukám nastaveno tak zavírám.
