### ISSUE TITLE
dropbox - authorized hláška undefined

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#262]
![image](https://cloud.githubusercontent.com/assets/903531/8542504/79a9b378-2496-11e5-9c25-5ce97f407718.png)

**Comment by Halama** [comment]
dělá po autorizaci nového účtu

**Comment by Halama** [comment]
Nevím jestli si to fixoval ale teď mi to prošlo ok. Email jsem vyplnoval stejně jak předtím.
![image](https://cloud.githubusercontent.com/assets/903531/8545314/9196e3c2-24ad-11e5-939a-ac0596df09f8.png)

**Comment by Halama** [comment]
ale dělal jsem vlastně reautorizaci

**Comment by kacurez** [comment]
neviem otom zeby som to fixol :)
popravde sa to snazim teraz nasimulovat a nedari sa mi. Zakazdym dostanem tu hlasku v poriadku.

**Comment by Halama** [comment]
tak teď se mi to stalo znova. Zkus si založit úplně nový config dropboxu.
