### ISSUE TITLE
gooddata v3 writer

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2626]
- tlacitko disconnect project:

![image](https://user-images.githubusercontent.com/4319320/50791936-a48ae700-12c3-11e9-8dea-9362e5f45106.png)

@JakubMatejka nevi, co to dela a prej je to blbost :)

- pridani datumove dimenze:

![image](https://user-images.githubusercontent.com/4319320/50792005-dd2ac080-12c3-11e9-836d-1504cbe4f439.png)

preklepy, zatrzitko "Include" me prijde takovy divny

- identifier, u datumove dimenze je normalne videt, u tabulek na zatrzitko - stejne je hrozne moc videt na to jak moc lowlevel featura to je, takze takovy napad - nemohlo by se u te konfigurace nekde na uvodu zmacknout "Vim co delam a chci zobrazit identifery" - 1. takhle si tam celkem snadno nekdo muze neco napsat a rozdrbat projekt 2. ubylo by zatrzitko z konfigurace tabulky

**Comment by natocTo** [comment]
- vyhodit teda tlačítko Disconnect
- tak zkusím vyhodil ten label, respektive jeho text dát k tomu chechboxu, bude tam "[checkbox] Include Time" - možná nějaký popis by byl taky dobrý
- texty v modalu opravím
- U tabulky nevidím "identifier" vůbec při vytváření, a při editaci to tam vidím rovnou. Ještě máme componentu, kde můžu nastavení shovat pod panel který se musí rozkliknout tak nestačí tak? Pokud to bude pod tím panelem, tak tam asi už nemusí být napsáno "optional" ale spíš nějaký popis by byl lepší.

![remove_disconnect](https://user-images.githubusercontent.com/12331181/50818737-3debe480-1328-11e9-8c63-4bcb71ac9aa8.png)
![modal](https://user-images.githubusercontent.com/12331181/50818740-40e6d500-1328-11e9-9f2f-383a198191bd.png)
![modal_detail](https://user-images.githubusercontent.com/12331181/50818745-43492f00-1328-11e9-9e17-24001d9eef68.png)

**Comment by natocTo** [comment]
Pokud by to takto připravené bylo přínosem tak to pošlu.

**Comment by ujovlado** [comment]
toto bude skor na konzultaciu s @kacurez, on je autor :) ... za mna asi len to, ze si nie som isty, ci sa oplati skryvat jednu polozku pod "Show/Hide advanced settings"

**Comment by kacurez** [comment]
to stym disconnect tlacitkom nerozumiem - skusali ste vobec nato kliknut ked to navrhujete dat prec? :) 
zbytok cajk

**Comment by kacurez** [comment]
- **"disconnect button"** dava to moznost odpojit sa od gooddata projektu a zalozit si novy resp napojit sa na novy gooddata projekt s uz naklikanym modelom v tom konfigu. Tiez to umoznuje zmazat cely gooddata projekt, pretoze to sa pri zmazani gooddata writer konfigu neurobi. Alebo tam bude nejaky garbage collection casom? Ak vam pridu tie use cases zbytocne tak to dame prec no.

- **change button** je tam vtedy ked si napojeny na svoj resp keboola non provisioned projekt - v tom pripade ho provisioning nema pravo zmazat a tak sa jedine da nastavit zmenit jeho credentials v konfigu.

>vytvořit datumovou dimenzi přímo z editace...To je záměrně?

povodne ked to bolo ako config rows ui tak to technicky nebolo mozne, teraz uz sa to da ale som to po prerobeni z config rows zabudol urobit.

**Comment by natocTo** [comment]
Tak to taky upravím. Na detailu tabulku je stejný případ nebo to je již něco jiného? Taky tam vidím "Load Type".

Jak se jeví ta úprava "Identifier" pod "advanced setting"? 
Poslední věc zda ponechat ten Disconnect nebo ne. Respektive nemusí se vše vyřešit v jednom PR.

**Comment by kacurez** [comment]
add identifier - je tam este jeden input po zvoleni `custom` optiony:
![image](https://user-images.githubusercontent.com/1412120/50845039-4403b480-136c-11e9-9dd4-965db3bf67ac.png)
Neviem ci to bude sediet takto s identifier inputom..(treba vyskusat)

add Disconnect - @odinuv by to mohol viac rozvinut ak sa mu to tam nepaci :) Ak je problem v UX tak to podme navrhnut inak. Ja som to tam hodil surovo tak aby bolo vidno ake su moznosti, potom to prehnal cez Jana - ten ktomu nemal vyhrady a Jack sa k tomu nedostal.

**Comment by natocTo** [comment]
Je to tam takto teď.

![po](https://user-images.githubusercontent.com/12331181/50845982-672f6380-136e-11e9-8d18-c838a0045de6.png)

**Comment by odinuv** [comment]
me se na disconnect buttonu nepaci jenom to, ze @JakubMatejka rika, ze takova ficura nedava smysl :) tj. zajma me jen - "proc/kdy by na to mel uzivatel kliknout a ceho tim dosahne?" :)

**Comment by kacurez** [comment]
z casti som to "proc/kdy" popisal v https://github.com/keboola/kbc-ui/issues/2626#issuecomment-452233592 ale nejak ste nato nereagovali.
Typicky use case este moze byt ze si chcem provisionovany projekt prehodit na svoj(pretoze mam zrazu vlastnu zmluvu s GoodData) takze existujuci gd projekt odpojim z konfigu(pripadne aj zmazem) a potom napojim na svoj ktory som si vytvoril niekde bokom a poslem tam data. Alebo si zkopirujem konfigu a chcem ho napojit na novy gd projekt tak existujuci gd projekt z toho zkopirovaneho konfigu tymto odstranim(== odpojim).
Tiez sa v tom aztak nevyznam a nemusi to davat zmysel ale nikto to zatial nijak neoponoval tak neviem.

**Comment by JakubMatejka** [comment]
Hmm, jak tak čtu jak to popisoval Tomáš, tak ten Disconnect možná může být zajímavý. ;o) (To si někdo vyžádal?)

**Comment by JakubMatejka** [comment]
@padak by to mohl rozseknout. Nový Writer má u konfigurace tlačítko Disconnect (viz. https://github.com/keboola/kbc-ui/issues/2626#issue-396641157), který umožňuje todle: https://github.com/keboola/kbc-ui/issues/2626#issuecomment-452233592 Dává to tam smysl?

**Comment by kacurez** [comment]
>To si někdo vyžádal?

nie, to som si v podstate vymyslel ja :). Ale tak myslim ze by to malo byt v sulade s konceptom credentials v db writeroch kde je nieco podobne mozne.

**Comment by odinuv** [comment]
No ja zil v predstave, ze zapis do existujicho GD projektu je schovanej za velkou cedulkou "HERE BE LIONS". muze to treba fungovat tak, ze mam DEMO projekt a rozhodnu se z nej udelat produkcni projekt, tak disconnectnu writer a pak dam vytvorit novy produkcni projekt?

**Comment by JakubMatejka** [comment]
Soulad s dalšími writery mi přijde ok.

(Jinak z demo projektu se produkční udělá posláním ticketu na GD support. Stejně tak se dá převést projekt z našeho auth tokenu na klinetův, to je asi nejjednodušší varianta.)

**Comment by odinuv** [comment]
No tak kdyz je jednodussi zmenit projekt tokenu, tak k cemu je to prepojovani? Vytvorit druhy projekt se stejnym LDM? Jak to vlastne je s kopii konfigurace? - kdyz zkopiruju writer, tak budu mit dva writery co zapisuji do jednoho projektu, coz je spatne, takze pak se hodi ten disconnect? samy otazky :)

**Comment by JakubMatejka** [comment]
No, to nemusí být nutně špatně. Dokonce to tak měl jeden.. ehm.. českej klient se slovenskou pobočkou, která byla v samostatným kbc projektu. Ve slovenským měli kopii českýho writeru s napojením na českej projekt a updatovali v něm jeden dataset. A naopak.

**Comment by odinuv** [comment]
aha, to me treba vubec nenapadlo :) supr, to dava smysl

**Comment by odinuv** [comment]
Jeste me napadla uprava popisu:

![image](https://user-images.githubusercontent.com/4319320/50958124-42e39c00-14c0-11e9-851b-aebf8f4723a8.png)

1. Reference -> Source (column) / Source Connection Point
2. Date Dimensions ->Date Dimension
3. Reference -> Parent / Source (Attribute/Column)
4. Reference -> (Display) Label (Attribute/Column)

dava to smysl?

**Comment by kacurez** [comment]
ja osobne sa neviem rozhodnut u konkretnych variant, mozno by sa trebalo opytat analytikov. Kazdopadne miesto na vacsi popisok tam je.

**Comment by odinuv** [comment]
dalsi vec - ve starym writeru byla veticka `By creating a config, you agree with the GoodData terms and conditions.` v novym to neni
v starym writeru se link do gd projektu zobrazuje na hlavni strance, v novym je to az po rozbaleni gd project (klik navic)
a jeste jedna vec k tomu - disconnect buttonu -  nedela to tedka ve writeru diru? mam limit na dva projekty, zalozim projekt - disconnectnu, zalozim dalsi projekt - disconnectnu, zalozim dalsi projekt a mam tri projekty. Nebo to dokaze ten writer nejak poznat?

**Comment by kacurez** [comment]
- **1. `Ad veticka`** stary writer zakladal goodata projekt hned pri vytvarani konfigu. V novom to je v podstate az po kliku na create project modalu, tak by som tu veticku dal tam ci?
![image](https://user-images.githubusercontent.com/1412120/51027376-0469e200-1591-11e9-901d-cefe0a654f07.png)

- **2. `Ad link do gd projektu`** - ten link sa pre provisionovane projekty zobrazi az po enablnuti pristupu do projektu(click on Enable Access To Project button). Mi pride trocha divne cpat to do menu kde to stym co tam je (run/delete button) moc nesuvisi. Mozno by sa ten link mohol dat do hlavicky tej sekcie ak sa to bude dat ci? 
![image](https://user-images.githubusercontent.com/1412120/51028970-4ac14000-1595-11e9-9059-683fc89d736e.png)

- **3. `Ad disconnect button a dira`** - ak v disconnect modalu nezakliknes `Also remove GoodData Project` checkbox tak to moze vzniknut. Ale tak to vznikne aj keby tam ten button nebol a to zmaznim konfigov, zalozim config a projekt - zmazem konfig, zalozim konfig a projekt - zmazem projekt.. Ak stym bude problem tak tam mozme nato dorobit garbage collection.

**Comment by odinuv** [comment]
1. to je asi spis na @padak ?
2. no jestli to pujde, tak by to mozna bylo dobre
3. no to je prave to, ze na starym byl afaik garbage collect, kterej smaze (nami zalozenej) projekt bez writeru. Ale ted kdyz te to UI necha ten projekt odpojit a nesmazat ho, tak mi prijde, ze to jako uzivateli dava nadeji, ze tam ten projekt zustane, ne ze ho za 3 dny smazem tak jako tak :D

**Comment by kacurez** [comment]
3. ta mylna domnienka ze ti to zostane sa da "narovnat" vhodnou hlaskou :) Tiez by ta moznost odpojit projekt mohla byt viac skryta, takze ten button by sa volal `Reset provisioned project` a v modali by bol checkbox `remove gooddata project` by default zasrkntuty..?

**Comment by kacurez** [comment]
ad 3. `Disconnect project button` - bavil som sa otom s Padakom a dospeli sme k zaveru ze by sa ten button zobrazoval len pre nas kbc superadminov takze ak bezny uzivatel chce nejake machinacie s konfigom a gd projektom tak to bude riesit cez nas support a pre nas to bude jednoduche vdaka tomu buttonu. Tiez sme sa dohodli ze akce zmazanie konfigu tj `Move to trash` zmaze aj gd project ( zalozim nato issue). @odinuv @JakubMatejka zda sa vam to ok?

**Comment by kacurez** [comment]
rozhodil som vystupy z tejto issue do mensich issues a tu to zavriem
