### ISSUE TITLE
TBD - provide detailed info regarding GoodData writer migration

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2673]
este to tu budem dopisovat ale zatial je treba dopisat:
- ak migracny skript narazi na to ze gd projekt je nedostupny alebo neexistuje tak migraciu konfigu preskoci a pokracuje na dalsi konfig tj nefailne cela migracia viac infa v https://github.com/keboola/config-migration-tool/pull/45#issuecomment-454391050
- nemigruju sa klony 
- ak je v projekte gooddata extractor ktory odkazuje na stary writer tak sa updatne aj jeho konfig aby ukazoval na novy gd provisioning viac infa v https://github.com/keboola/config-migration-tool/pull/52

celkovo sa migracia riesi v https://github.com/keboola/internal/issues/60 issue takze dalsie info vyextrahovat z tohto

**Comment by kacurez** [comment]
1) the message in the migration box seems to say that orchestrations will be updated, but I don’t think that happens.
2) it lists `contains new extractors` `contains old extractors` in the status for orchestrations, maybe this should be components instead.

**Comment by pivnicek** [comment]
There is no description of the change caused by migration on the version of the old configuration.

![image](https://user-images.githubusercontent.com/569139/54277467-3fd45d00-4590-11e9-894c-c591237010e3.png)

Maybe `Migrated to V3` or something would be good

**Comment by pivnicek** [comment]
Also, once you migrate, it still let's you press the `migrate` button again.  Should that button only be enabled for non-migrated configs?

**Comment by kacurez** [comment]
> once you migrate, it still let's you press the migrate button again

I think that's always been like that - even though you click on migrate button, nothing will be migrated and there is a migration modal dialog that shows if all configurations have been migrated 

> There is no description of the change caused by migration on the version of the old configuration.

Good point I created PR to set the description https://github.com/keboola/config-migration-tool/pull/64

**Comment by kacurez** [comment]
btw if you have more issues with the migration please report it here https://github.com/keboola/internal/issues/60 - that's where we keep the track about the migration process

**Comment by JakubMatejka** [comment]
@kacurez v jakým je to stavu, ty texty už jsou, nebo je ještě třeba upravit?

**Comment by kacurez** [comment]
nedostal som sa k tomu ale myslim nato, najblizsie v pondelok. Pokial viem staci len poriadne zpisat cely ten proces.
