### ISSUE TITLE
Storage Explorer: Tune buckets sidebar

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2708]
Zislo by sa ho nejako "skomprimovat", nech to nema tolko na vysku.

A mozno vymysliet nieco s tym tlacitkom detailu - ja si stale myslim, ze tym sa mi to rozbali (tak to mame napr. v "project select").

A aktivny bucket by mohol byt rozbaleny ked som v nom (alebo v jeho tabulke)

**Comment by ujovlado** [comment]
Mozno aj nejako takto. Ale je to len nestrel. Par zmenami paddingov byt sme to stiahli este viac.

**Comment by ujovlado** [comment]
Ale kludne to mozem este poladit aj ja. Chvilku som rozmyslal, ci tam dokonca nehodime vlastnut Accordion komponentu.

**Comment by natocTo** [comment]
Jestli to máš nějak rozdělané tak na tom klidně makej :)
Já teď zkoumám ten bug při cestě na overview. Toto nemám otevřené.
