### ISSUE TITLE
Storage Explorer: Link shared bucket

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2709]
Zda sa mi, ze toto nikde namame.

**Comment by ujovlado** [comment]
![screenshot_2019-01-18_11-33-45](https://user-images.githubusercontent.com/419849/51381637-fb3ebf00-1b14-11e9-8edd-cf36747cdf17.png)

**Comment by natocTo** [comment]
Já to asi v angular appce nemám tak jsem to minul, musel jsem to přehlédnout i v kódu.

**Comment by ujovlado** [comment]
Mas to uz dostupne? Mozem ti ked tak vytvorit nejaky projekt alebo ti nieco nasharovat.

**Comment by natocTo** [comment]
Mrknu.

**Comment by natocTo** [comment]
Asi furt nemám.

**Comment by ujovlado** [comment]
Ok, mas to tam:

- `in.c-shared-to-org` zazdielane pre clenov organizacie (t.j. mozes si to linknut, len ked si clen organizacie)
- `in.c-shared-to-proj` zazdielane pre akykolvek v projekt v ramci organizacie (staci, ze je tvoj projekt v tej organizacii a mozes to linknut)

**Comment by ujovlado** [comment]
Do projektu som ta pozval.

**Comment by natocTo** [comment]
Dík. Odjel jsem na chatu tak se k tomu dostanu v pondělí. Tak kdybych něco nechápal napíšu. Jinak ten PR už je z větší části přichystány.
