### ISSUE TITLE
gooddata writer job

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#272]
Zobrazovat chybu tasku.
![image](https://cloud.githubusercontent.com/assets/903531/8548388/c25341c4-24c4-11e5-86bd-daea8ff1c0bd.png)
![image](https://cloud.githubusercontent.com/assets/903531/8548395/cc15f29c-24c4-11e5-8b7c-0ef2ee718650.png)

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/commit/6ea628bfc597ffc184b6cd7a23cf7dcd536cd580
