### ISSUE TITLE
Orchestration - run orchestration - Error: undefined

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#2729]
https://sentry.io/keboola/keboola-connection-ui/issues/846170695/?referrer=github_plugin

```
Error: undefined
  at None (webpack://kbcApp/./src/scripts/utils/request.js:21:27)
```

**Comment by ujovlado** [comment]
To bol get na joby orchestracie. Po novom by to malo byt zalogovane ako `Error: Server error` . (#2736)
