### ISSUE TITLE
GD Writer - timeout pri vyrabeni datumove dimenze

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#273]
divny - nic vic nez tohle nemam:
![image](https://cloud.githubusercontent.com/assets/1427901/8548449/1f14903e-24c5-11e5-8ac4-fae163f2e52d.png)

**Comment by Halama** [comment]
to je tam nastaveno globalne v ui, Mrknu na to proc to trva tak dlouho

**Comment by padak** [comment]
tak to vypada, ze to na pozadi ukladalo jmeno datasetu - a ja sel mezitim editovat tabulku
