### ISSUE TITLE
Storage Explorer - use urlTemplates when linking to project

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2738]

**Comment by natocTo** [comment]
Koukám že existují dokonce nějaké komponenty jako `ExternalProjectLink` a `ExternalBucketLink` ve "components/react/components". Ale tam to chce i nějakou props `stackUrl`.

Spíš bych teda zůstal o těch komponent co jsou ve storage jen je upravil. Tam jde o použití třeba `getProjectUrlTemplate`? Nebo tak je rovnou `getSapiTableUrl` či `getSapiBucketUrl` ale to je do stejného projektu.
