### ISSUE TITLE
Storage Explorer - link to table/bucket from table/bucket overview doesn't activate item in sidebar

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2744]
Ked tam mam napr. alias a react-router odkaz, neaktivuje mi to vlavo v bucket paneli a potom zrazu neviem kde som.

**Comment by natocTo** [comment]
Zkouším klikat u table overview na `Table aliases -> link` a pak třeba zpět `Source table -> link` a hezky se mi to levé menu aktualizuje. Nebo jaký odkaz myslíš?

**Comment by ujovlado** [comment]
Ty brdo, tak uz to neviem najst. Ked tak dam reopen. Sorry.
