### ISSUE TITLE
Google Analytics UI freeze

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2751]
Pokud v query v Google Analytics dám editovat datum a místo výběru pickerem ho zkusím napsat, tak jakmile zmáčknu "2" abych napsal 2019, tak mi totálně vymrzne browser. Do konzole to stihne napsat tohle:

![image](https://user-images.githubusercontent.com/1427901/51667371-3d0db080-1fc0-11e9-88b7-0ec664910e16.png)

**Comment by padak** [comment]
Reportuje mi to Tom z Digital360 (https://keboola.zendesk.com/agent/tickets/9719)

**Comment by kacurez** [comment]
je priraveny fix vid #2752
problem bol v react-datetime libke ktoru pouzivame ako date picker ktoru treba updatnut.
