### ISSUE TITLE
Error: Orchestration 478027282 has 1 waiting job. Current limit is 1.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2758]
https://sentry.io/keboola/keboola-connection-ui/issues/846170695/?referrer=github_plugin

```
Error: Orchestration 478027282 has 1 waiting job. Current limit is 1.
  at None (webpack://kbcApp/./src/scripts/utils/request.js:21:27)
```

**Comment by ujovlado** [comment]
Toto hodilo `409` (user error), nie je dovod aby to skoncilo v Sentry.

**Comment by natocTo** [comment]
Co je a co není user error se definuje tu:

https://github.com/keboola/kbc-ui/blob/master/src

Tak myslíš že stačí přidat tento kód? Mám to přidat?
