### ISSUE TITLE
Checking detail of IM table breaks adding new IM

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2761]
Zreprodukovat sa da takto:

- mas generic table IM komponentu (napr. nejake writer co ma generic docker ui)
- das si tam nejaku tabulku
- potom tu tabulku zmazes (ale v IM musi ostat)
- reloadni si UI (mozno netreba ale pre istotu)
- kukni si detail toho IM (neexist tabulka, zobrazi sa ti po novom readonly)
- zavri modal kliknutim mimo
- klikni na pridanie novej tabulky do IM
- v react-select vyberes tabulku, no ostane prazdny (toto je issue)

@natocTo neskusil by si to? vsimol som si to vcera, no nepodarilo sa mi zistit pricinu.

**Comment by natocTo** [comment]
Jo mrknu.

**Comment by ujovlado** [comment]
Takto: https://www.youtube.com/watch?v=SFBu8UCc0Gw (odskusane na mastri, kde su este render errory)

**Comment by natocTo** [comment]
Ono dokonce nezáleží jestli je tabulka smazané nebo ne. Ale už jsem asi našel proč to blbne. Pošlu PR, jen jsem tam zase namotal více věcí, ale mělo by to jít dyštak cherry picknout, kdyby to bylo moc špatný.

**Comment by ujovlado** [comment]
> jen jsem tam zase namotal více věcí

takze uz to robis vedome? 😆

**Comment by ujovlado** [comment]
Ja som sa v tom vcera vrtal skoro hodku, uz som bol niekde v store, pri akcii INSTALLED_COMPONENTS_CONFIGURATION_MAPPING_EDITING_CHANGE ale nenasiel som to - uz bolo neskoro :)

**Comment by natocTo** [comment]
To sepíšu do PR, já právě upravoval něco abych tam hodil třeba immutable-mixin aby se to nějak nepřekreslovalo apod, jestli to nepomůže a nic.. ale aspoň se pak přestalo re-renderovat modaly atd při načtení jobů tak jsem to nerevertoval, protože jsme si říkal že to bude lepší takto. Pokud jsem tam teda neudělal chybu při přepisu do JSX.
