### ISSUE TITLE
Error on Job details page

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#2774]
Every ~20s, it reports a timeout error

![timeouterror](https://user-images.githubusercontent.com/569139/51903567-c7895200-23bc-11e9-845b-c908cc2571c5.gif)

**Comment by natocTo** [comment]
Timeout 4000ms je docela krátký. Myslím že by nevadilo to hodit klidně na dvojnásobek. Nebo detekovat rychlost internetu a nastavit to podle toho. Jestli to je možné, mohlo by se to hodit na více místech. Typicky taky poll 2s na pomalém internetu je moc rychlé.

**Comment by ujovlado** [comment]
It's not a bug, but we'll increase that timeout to 10s in #2800
