### ISSUE TITLE
Chyba při užití blokového komentáře

### ISSUE THREAD

**Issue by jirigrill** [keboola/kbc-ui#278]
Dobrý den,
objevil se mi bug v query, když jsem použil koment pomocí /**/. Ve staré keboole blokové komentování nebyl problém.
<img width="1280" alt="screen shot 2015-07-08 at 16 03 34" src="https://cloud.githubusercontent.com/assets/12986457/8572302/15b632be-258c-11e5-82d3-d02695e214b9.png">

**Comment by Halama** [comment]
díky za report podíváme se na to.

**Comment by ondrejhlavacek** [comment]
sakra, to je chyba tady!
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/transformations/ActionCreators.coffee#L252

**Comment by ondrejhlavacek** [comment]
Tak jsem se to pokusil opravit, uvidíme! :-) Snad!

**Comment by Halama** [comment]
Tak to bohužel ještě není v pořádku, otevírám znovu.

**Comment by jiritobolka** [comment]
Potvrzuju pred chvili jsme resili stejny problem...

**Comment by ondrejhlavacek** [comment]
pokus číslo 2 :)
