### ISSUE TITLE
Create new alias from table

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2784]
Currently alias is created "from bucket" and source table is selected + table name filled.

Another way can be "from table" and destination bucket will be selected + table name filled.

**Comment by ujovlado** [comment]
Mozme sa nad tym zamysliet, no robit to budeme az po nasadeni prepisanej storage console.

**Comment by natocTo** [comment]
Nasazeno napůl máme :) tak mrknu na toto. Myslím že to může být užitečné. Nebo hoří něco více?
