### ISSUE TITLE
wr-redshift incorrect tooltip

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2789]
column edit:
![image](https://user-images.githubusercontent.com/4319320/52177637-2affef00-27c4-11e9-92cd-5445b2066834.png)

which is not true - it only sets the column as nullable (https://github.com/keboola/db-writer-redshift/blob/master/src/Keboola/DbWriter/Writer/Redshift.php#L130), empty strings are not converted, and 'null' values are completed to `null` (https://github.com/keboola/db-writer-redshift/blob/master/src/Keboola/DbWriter/Writer/Redshift.php#L93)

note: the same?? tooltip is used in wr-snowflake where it is correct - https://github.com/keboola/db-writer-snowflake/blob/master/src/Keboola/DbWriter/Writer/Snowflake.php#L132

**Comment by odinuv** [comment]
also incorrect for `keboola.wr-db-oracle` writer (https://github.com/keboola/db-writer-oracle/blob/master/src/Keboola/DbWriter/Writer/Oracle.php#L169)

**Comment by natocTo** [comment]
Asi to bude chtít rozseknout pro všechny WR-DB. 

Koukám že ta hláška tam je teď pro všechny stejná. Takže to chce říci kde to platí a kde ne.

**Comment by odinuv** [comment]
@natocTo nech to jeste chvilku byt, jeste me zbyva jeden writer, zatim mam 3 verze toho jak se to chova a priklanel bych se k tomu dat ten tooltip uplne dopryc

**Comment by odinuv** [comment]
takze plati to pro mysql, postgre, snowflake, mssql 
u oraclu je to jinak a u redshiftu je to taky jinak (i jinak nez u oraclu)
je to popsane tady https://help.keboola.com/writers/database/ (az to bude publishnute), tak nevim co je lepsi jestli tam ten tooltip mit jen kde plati nebo nemit vubec...

**Comment by natocTo** [comment]
@odinuv co kdyby ta ikonka byla odkaz do té dokumentace?

**Comment by odinuv** [comment]
necham to na tobe :)

**Comment by ujovlado** [comment]
Ja myslim, ze ak to ma viest na "home" stranku writerov, ten odkaz tam nemusi byt vobec - userovi to nijako nepomoze.
