### ISSUE TITLE
Trochu matouci tlacitko pri editaci transformace

### ISSUE THREAD

**Issue by jiritobolka** [keboola/kbc-ui#279]
Je to trochu matouci, to modre tlacitko ADD mam tendenci mackat namisto toho Save ktere je sice zelene, ale je uplne nahore. Prikladam screenshot, snad je to srozumitelny :) Chapu jak je to mysleny ale proste porad mackam vedle ....

<img width="979" alt="screen shot 2015-07-09 at 15 45 41" src="https://cloud.githubusercontent.com/assets/951201/8596814/ce2d634c-2651-11e5-9f82-4a11640110b9.png">

**Comment by Halama** [comment]
diky za feedback. Uz to par lidi zminovalo, budeme s tim muset neco udelat.

**Comment by Halama** [comment]
Přepracovali jsme transformace tak jak fungovali dřív
