### ISSUE TITLE
AWS S3 extractor - jobs reload resets select value

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#2791]
Když mám rozeditované jména sloupců a zrovna se reloadnou joby tak to smaže to co mám aktuáně rozepsané. Když jsem teď setupoval extractor s 10 sloupci tak se mi to stávalo neustále.

https://www.dropbox.com/s/94henfvxwsprghe/Screen%20Recording%202019-02-04%20at%2010.20.01.mov?dl=0

**Comment by natocTo** [comment]
Na to jsem zrovna posílal PR, akorát v jiném modulu https://github.com/keboola/kbc-ui/pull/2793
Asi se to bude muset upravovat takto v každém zvlášť, což teda není ideální. 
Jdu na to mrknout. Pak ještě mrknu zda by to nešlo nějak více obecně.
