### ISSUE TITLE
AWS S3 extractor - Enclosure default value

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#2797]
Mám [nastavený](https://connection.keboola.com/admin/projects/258/extractors/keboola.ex-aws-s3/481598116/rows/481598491) S3 extractor tak že má prázdný enclosure.
V UI to ale vypadá jako by to fallbackovalo na `"`.

![image](https://user-images.githubusercontent.com/903531/52202576-2e03e980-286f-11e9-8c48-ab09ca47957a.png)

To ale není pravda, v [logu jobu](https://connection.keboola.com/admin/projects/258/jobs/481611160?q=&eventId=1234057277) vidět že to skutečně použilo prázdný enclosure.

![image](https://user-images.githubusercontent.com/903531/52202601-45db6d80-286f-11e9-95a0-b1a39c26779b.png)

**Comment by ondrejhlavacek** [comment]
možná by stačilo udělat jinej placeholder v tom inputu?

**Comment by ondrejhlavacek** [comment]
nebo to vyřešit jako s hodnotama filtru v input mappingu?

![image](https://user-images.githubusercontent.com/497675/52203531-baafa700-2871-11e9-9aec-ff1b4fa9b39d.png)

**Comment by natocTo** [comment]
Ten placeholder úplně vyhodím. Tím se to vyřeší. Popis pod tím je, pokud bude nová konfigurace rovnou tam bude " takže to bude stejné. Jen pokud to vymažu nebude tam nic. Pošlu PR.

**Comment by Halama** [comment]
Tím pádem se může vyhodit i ten popis `Default value is "` ne?

**Comment by natocTo** [comment]
Jo asi pravda. Ono to pro novou tabulku sedí, protože to tam je "před" nastavené. Ale není potřeba to psát když to tam rovnou je. Zajímavé by to bylo pokud by tam bylo něco jako "pokud je to prázdné použije se toto" ale to není pravda. Prostě se použije to co je zadáno. 

Tak to vyhodím.

**Comment by Halama** [comment]
Super. Vyhodil bych to teda i pro delimiter kde je situace stejná.

**Comment by ujovlado** [comment]
Na toto sme dokonca mali niekde issue.

**Comment by ujovlado** [comment]
Aha, tak to bolo podobne: https://github.com/keboola/kbc-ui/issues/1822
