### ISSUE TITLE
Responsive UI on mobile

### ISSUE THREAD

**Issue by jiritobolka** [keboola/kbc-ui#280]
Bylo by super, aby nove UI bylo aspon trochu responsive. Na tom starem je super, ze se da na mobilu relativne dobre ovladat (restart orchestrace, list jobu, jejich status) takovy ty veci, ze neco pustis a des na  metro :) 

Mozna nejaky mobilni UI simple UI, to by bylo uplne super! Uz jsem jednou restartoval orchestraci v aute na krizovatce...

**Comment by ujovlado** [comment]
Uz je to scasti vyriesene a dalsi velky update UI to vyladi este viac - t.j. bude moznost to ovladat bez vacsich problemov na mobile.
