### ISSUE TITLE
Warning: a promise was created in a handler at webpack://kbcApp/./src/scripts/modules/components/InstalledComponentsActionCreators.js?:268:39 but was not returned from it, see

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2807]
![image](https://user-images.githubusercontent.com/497675/52272781-1ba9ae80-2948-11e9-8455-91ded3470f2d.png)

![image](https://user-images.githubusercontent.com/497675/52272800-2cf2bb00-2948-11e9-8181-9fea06c7562b.png)

**Comment by ujovlado** [comment]
toto by som asi nezakladal taketo issues (teda ak to nie je preto, ze to chces predebatovat) ... lebo tych warningov je tam "milion"

**Comment by ondrejhlavacek** [comment]
aha, pardon, jsem si dřív vůbec nevšiml, snažil jsem se vždycky, aby z PR nelezly žádné warningy.

**Comment by ujovlado** [comment]
No kludne to oprav (to som ta nechcel odradit). Tieto "problemy" tam boli aj doteraz, akurat sme zapli, nech ich bluebird vypisuje. ;)

**Comment by natocTo** [comment]
Konkrétně v tomto PR. https://github.com/keboola/kbc-ui/pull/2305
Původně jsem tam měl `warnings: false` což by zachovalo chování před updatem, ale nakonec se domluvilo že se to tam nebude dávat a že třeba takto postupně nějaký varování zpracujeme. Což už se i párkrát stalo.
