### ISSUE TITLE
Storage - tabs wrap

### ISSUE THREAD

**Issue by jiritobolka** [keboola/kbc-ui#281]
Kdyz rokliknu detail tabulky v SAPI tak je to tam spatne zalomene. Chapu, ze je to nejspis stare UI a bude se to menit, ale pro jistotu reportuju :)

Videno na Macbook 13" Retina

<img width="727" alt="screen shot 2015-07-09 at 16 06 23" src="https://cloud.githubusercontent.com/assets/951201/8597323/01bf864c-2655-11e5-803b-02a4c0ac0fdb.png">

**Comment by Halama** [comment]
Děláme na nové storage konzoli, takže zavírám.
