### ISSUE TITLE
Jest force exit reason?

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2814]
v nastaveni jestu mame `--forceExit` ... je to preto, ak by sa jest z nejakeho dovodu neukoncil korektne.

ak tak nieco take treba, znamena to problem s testami alebo tak.

Mozeme tu option skusit vyhodit. V pripade problemov sa zapne `--detectOpenHandles`, cim by sa malo dat zisti kde je problem.

cc @natocTo

**Comment by natocTo** [comment]
Já jsem pro. Ať se to min zkusí co to udělá.

**Comment by ujovlado** [comment]
Lokalne sa mi to nikdy nestalo, poslem PR na  vyhodenie z CI.

**Comment by ujovlado** [comment]
Fixed in #2815
