### ISSUE TITLE
Špatná query při přechodu mezi závislými transformacemi

### ISSUE THREAD

**Issue by jirigrill** [keboola/kbc-ui#282]
Dobrý den,
pokud přecházím mezi závislými transformacemi, tak se mi objeví v nové transformaci query z transforamce, z které tam jdu.
![fixer_query_ok](https://cloud.githubusercontent.com/assets/12986457/8615512/84095044-26f3-11e5-93ed-a7c491d2fe00.png) (správná query fixeru)
![fixer_query_z_inicializace](https://cloud.githubusercontent.com/assets/12986457/8615523/9c6d27d2-26f3-11e5-9592-8f016bbac4be.png) (pokud jdu do fixeru z inicializace, tak tam zůstane její query)
![inicializace_query_ok](https://cloud.githubusercontent.com/assets/12986457/8615533/bce86e22-26f3-11e5-98fb-15a2ddfe0691.png) (správná query inicializace)
![inicializace_query_z_fixeru](https://cloud.githubusercontent.com/assets/12986457/8615537/c698c606-26f3-11e5-9fa3-350ab7d9f1dd.png) (pokud jdu do inicializace z fixeru, tak tam zůstane její query)

Pokud chci ale danou transformaci editovat, tak se mi objeví správná query.

K tomu ze váže druhý problém, který se mi děje: když dám edit transformace, potom cancel/save a vlezu do závislé transformace, tak se mi rovnou spustí editování té transformace.
![inicializace_cancel_editu_ve_fixeru](https://cloud.githubusercontent.com/assets/12986457/8615598/5a627224-26f4-11e5-88a7-1204d7d09e40.png) (dal jsem edit/cancel ve fixeru a přešel do inicializační transformace)

Díky za vyřešení.

S pozdravem,
Jiří Grill

**Comment by Halama** [comment]
Zdravím a děkuji za report.
Obě chyby jsou opravené. Pokud máte stránku otevřenou nejprve jí prosím reloadněte.
díky
