### ISSUE TITLE
V TAPI UI nefunguje tlačítko co kopíruje SQL do schránky

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#283]

**Comment by Halama** [comment]
a v sapi konzoli nebo ve starém ui ti funguje? Je možný že nemáš flash?

**Comment by padak** [comment]
Good point. Flash jsem si vypnul.

Sent from mobile
Dne 10. 7. 2015 1:03 PM napsal uživatel "Martin Halamíček" <
notifications@github.com>:
