### ISSUE TITLE
Orchestrator - run button

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#2833]
Tlacitko pro spusteni orchestrace pouziva starsi verzi API endopointu

```
[POST] /orchestrator/orchestrations/{orchestrationId}/jobs
```

Od doby co umi orchestrator spoustet dalsi orchestrace jako tasky je dostupny novy endpoint, obdobne jako u ostatnich komponent.

```
[POST] /orchestrator/run

{
"config": {orchestrationId}
}
```

**Comment by ujovlado** [comment]
Ten stary sa ide deprekovat?

**Comment by ErikZigo** [comment]
Jo melo se to udelat uz davno. Nejak jsem na to zapomnel. Chci se toho zbavit v UI abych pak dokazal vycist kteri klienti to jeste pouzivaji ve svojich aplikacich.
