### ISSUE TITLE
Job fronta

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#284]
Šlo by mít v jobech link do konfigurace komponenty? V TAPI link na transformaci, v extrakci link do konkrétní konfigurace extraktoru, atd..

**Comment by Halama** [comment]
u většiny jobů tam ten link je. Zatím není u transformací (řeší se v https://github.com/keboola/syrup/issues/38) a tam kde se to volá nějak nestandardně např. je tam `account` místo `config` v params. Kdyžtak dávej konkrétní příklady prosím,

**Comment by MiroCillik** [comment]
ja som zvykol pouzivat `account` ale myslim, ze vo vacsine (mojich) komponent uz je `config`, pripadne funguje obidvoje. Ak to niekde uvidite dajte vediet a ja to upravim.

**Comment by Halama** [comment]
je  to podle me jenom v nekterych starsich orchestracich jako pozustatek, imho uz vsechny komponenty pracuji z config
