### ISSUE TITLE
Update sidebar link and components linking to tables

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2845]
Uprava laveho menu a odkazy tabuliek/bucketov na novu storage console (StorageApi{Bucket,Table}Link)

**Comment by natocTo** [comment]
Mrknu.

**Comment by ujovlado** [comment]
ved to uz je tu nie? https://github.com/keboola/kbc-ui/pull/2653

**Comment by ujovlado** [comment]
Len som skonvertoval note na issue :)

**Comment by natocTo** [comment]
:D fajn, mě to znělo jako sidebar v nové Storage předělat na nějaké komponenty místo "obyč" Linku, aby pak přehození na ty "nové" url bylo jednoduší. Dobrý tak nedělám nic tu :)
