### ISSUE TITLE
UI showing query as commented out even though it is not

### ISSUE THREAD

**Issue by kasrad** [keboola/kbc-ui#2848]
Hi, I encountered a bug in the UI today. Basically if you use a comment in KBC like this:
```
/* comment start /*
*/
select a from b
```
the select statement is also in grey font as if it was a comment too. however, the query is executed.

https://drive.google.com/file/d/1jD6qg-W4mMmQSm0l8gX9VC64F0rsbYIS/view

I understand that this is not correct usage of comments, however, if -by mistake- this occurs, it is _superconfusing_.

**Comment by natocTo** [comment]
Thank you for reporting this. I sent PR to fix the issue.
