### ISSUE TITLE
Use StorageApiBucketLink.jsx in ex-mongodb

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2849]
Je tam na to vlastna funkcia, mala by byt pouzita komponenta ktora je na to urcena

**Comment by ujovlado** [comment]
toto je teda zbytocne:

https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/ex-mongodb/react/components/LinkToBucket.jsx

**Comment by ujovlado** [comment]
@natocTo mala vec, ak chces kukni. Ide mi o to aby som potom zmenil link na bucket len na jednom miesta.

Ale mozem to fixnut aj ja, to je moje maslo :)

**Comment by natocTo** [comment]
Mrknu.
