### ISSUE TITLE
storage-explorer: can not create table right after creating bucket

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2861]
vytvorim si bucket, vleziem don a nemam moznost v nom vytvorit tabulku vid:
![image](https://user-images.githubusercontent.com/1412120/52566649-9b34f300-2e0a-11e9-91e5-7baab1f054bb.png)
Button `create table` sa zobrazi az potom co reloadnem stranku.

**Comment by kacurez** [comment]
takisto neni mozne zmazat ten bucket(az po reloade stranky):
![image](https://user-images.githubusercontent.com/1412120/52566763-e3ecac00-2e0a-11e9-8ba0-c2978f1cc73a.png)

**Comment by natocTo** [comment]
To bude souviset s těmi právy co chodí v tokenu, podívám se na to.
