### ISSUE TITLE
GoodData writer v3 - allow disconnect button only for superusers

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2866]
tento disconnect button 
![image](https://user-images.githubusercontent.com/1412120/52625948-6e3c1b00-2eb2-11e9-8be3-bc1a5402989c.png)
By sa mal zobrazit len "nam" kbc techu aby sa nam jednoduchsie supportoval gd writer provisioning v gd writer configu. Neviem uplne ci tam je taka moznost zistit ze user je superadmin, asi by to pripadne slo aj podla nejakej featury ktora by sa k tomu specialne dorobila.
Bavili sme sa otom tu https://github.com/keboola/kbc-ui/issues/2626#issuecomment-456820178

**Comment by ujovlado** [comment]
Mozno by to slo podla tokenu, v ktorom mas `isMasterToken`?
