### ISSUE TITLE
GoodData Writer V3: delete gd project on config removal

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#2867]
Padak odporucal aby sa na mazanie konfigu zmazal aj provisionovany project(ak je)
https://github.com/keboola/kbc-ui/issues/2626#issuecomment-456820178

To znamena zachytit mazanie konfigu:
- z listu konfigov na stranke detailu komponenty
- z listu konfigov na stranke writers
- z detailu konfigu komponenty

A zaroven vyhodit confirm Modal stym ze sa zmaze aj projekt. Z trashu by som nechal moznost to rollbacknut

**Comment by natocTo** [comment]
Při koukání na toto jsem narazil na jeden bug, který řeší toto PR #2883.
Až se to příjme nebo nějak uzavře tak se vrátím k tomuto.
