### ISSUE TITLE
Matouci job detail u transformace

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#287]
Jak jsou ty Imported Tables a Exported tables, dlouho mi trvalo, ze pojem "import/export" je z pohledu SAPI, nikoli TAPI (coz bych ocekaval spis...), tj. v Imported bych ocekaval seznam tabuli, co se importujou DO TAPI DB...

**Comment by Halama** [comment]
jo to mas asi pravdu. U transformaci by asi byl lepsi teda nejaky custom přehlede  ve kterém by se to mohlo jmenovat  *Input* a *Output* aby to drželo konvenci s transformacema.
