### ISSUE TITLE
[minor] overflow?

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2873]
tady to vypada jako ze to taky nejak pretika, ze ty pruhy jdou az do kraje?

![image](https://user-images.githubusercontent.com/4319320/52650453-9182bc80-2eea-11e9-950b-a1c5af0ef7fb.png)

**Comment by natocTo** [comment]
Toto je úmyslně. Původně když neexistovalo horní menu (buckets, files a jobs) tak mezi tím panelem vlevo a vpravo byla mezera šedá. Všechny tabulky i třabe detail na overview, tak byl přes celou šířku aby se tam toho vešlo co nejvíce. A to zůstalo i po tom co se přidalo horní menu a oddělala se ta šedá mezera. 

Je to tak třeba v modalu u tabulek, od kraje ke kraji.

Ten vzhled se asi bude předělávat pak celá podle nějakého návrhu.

**Comment by odinuv** [comment]
fair, serem na to
