### ISSUE TITLE
Graph and lineage of dependencies of a project within organization

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#2875]
_Internal: https://github.com/keboola/internal/issues/119_
UX návrh: https://projects.invisionapp.com/share/M4QD30LZ36Q#/screens/339603655_-35_-_Graf_-_Projektu_Organizace

V přehledu projektů organizace by měl být link `Overview` (sloupec `connected projects` bych zatím vynechal):

<img src="https://user-images.githubusercontent.com/215660/52938015-de3e1b80-3360-11e9-98ad-97b1b288191a.png">

a na stránce Overview bude lineage - to je vlastně jen seznam "rodičů" a "potomků" projektu. Rodič je projekt ze kterýho se sdílí bucket, potomek je projekt do kterýho se sdílí bucket.:

<img src="https://user-images.githubusercontent.com/215660/53474420-53020b80-3a6d-11e9-9b65-f5308330cc2b.png">

a graf, což je vizuální obdoba téhož:

![image](https://user-images.githubusercontent.com/215660/52664175-a110fe00-2f08-11e9-8c2a-7c1f39f19173.png)

Data se generují přes `GET` na `https://graph.keboola.com/organization` resp. `https://graph.eu-central-1.keboola.com/organization` se Storage tokenem v hlavičce jako obvykle, formát dat viz. https://github.com/keboola/graph#project-lineage-in-an-organization

Jde o závislosti podle sdílených bucketů, takže na šipkách by měl být id bucketu (zřejmě zdrojovýho a možná v nějakým tooltipu po hoveru by bylo dobrý vidět i ten target bucket). `isHighlighted` značí závislý projekty a měly by být od ostatních zvýrazněný, `isOrigin` značí tento konkrétní projekt na jehož graf se dívám.

Na týhle url je takový testovací udělátko, kde se dá s Shared Config tokenem vygenerovat sample graf pro jakoukoli organizaci: https://p7pjgem0zb.execute-api.eu-west-1.amazonaws.com/dev/preview?org=13&region=eu&token=258-... (ta organizace `13` v `EU` je současně prubířský kámen na kterým je třeba odladit přehlednost toho grafu.)

**Comment by jancermak** [comment]
@JakubMatejka — vzhled toho grafu potrebujes nakreslit? Ci na to pouzijes nejakou hotovou vec?

**Comment by Halama** [comment]
Jaký storage token to použije když to je na stránce organizace?

**Comment by Halama** [comment]
Co když ten člověk který na to kouká není členem žádného projektu organizace?

**Comment by Halama** [comment]
jo to se týká jednoho projektu, už vidím

**Comment by JakubMatejka** [comment]
Jj, ale mělo by se tam dát dokliknout vlastně odtud: https://connection.keboola.com/admin/organizations/1 Půjde dostat se tam k tomu tokenu, nebo ne? 😕

**Comment by Halama** [comment]
jo půjde, backend ho tam může poslat stejně jako když startuje hlavní UI. Je potřeba počítat s tím že to bude vyžadovat menší úpravy na connection.

Nepůjde to v moment kdy ten člověk co na to kouká není členem toho projektu, v takovém případě nemá token. Může se jím ale joinnout do toho projektu a pak to půjde.

![image](https://user-images.githubusercontent.com/903531/53589899-e2540f80-3b90-11e9-8b01-5d70bec3d7bd.png)

**Comment by ujovlado** [comment]
@JakubMatejka 

Len pre potvrdenie, v tomto issue sa ide riesit len ten overview projektu v admin casti, ano?

**Comment by ujovlado** [comment]
Priradil som to mne a Jakubovi. Ja nachystam ten zaciatok a potom by som to prehodil na neho :)

**Comment by JakubMatejka** [comment]
Jj. Je to vlastně overview organizace, respektive přehled závislostí toho danýho projektu v organizaci.

Btw. Pokud byste potřebovali změnit formát z API kvůli tý grafový knihovně, tak to není problém.

**Comment by ujovlado** [comment]
^ linkol som sem nejake issues, kde popisujem ako to poriesit.

v skratke:

- v connection pribudne project/overview stranka, ktora injectne `parts`
- nasledne vyrenderuje jednu React komponentu (ProjectGraph) ktora uz si poriesi, ci sa zobrazi lineage alebo graf (nejake taby alebo tak)

@Halama myslis, ze to takto bude stacit?

**Comment by Halama** [comment]
@ujovlado jo řekl bych že dobrý.

**Comment by natocTo** [comment]
@JakubMatejka koukám na ty data teď a moc se v tom neorientuji, dám sem mini příklad z mého projektu, a prosím jen o rozbor jak z toho udělat ten lineage, s tím začínám.

```js
0: {id: 5194, distance: 1, role: "parent"}
1: {id: 5194, distance: 1, role: "child"}
2: {id: 5651, distance: 1, role: "parent"}
3: {id: 5651, distance: 2, role: "parent"}
```

Ještě si říkám, že by asi bylo fajn, kdyby tu rovnou přišel taky název projektu, pokud dělám jen odkaz, tak budu potřeboval právě ID + název.

Jestli to dobře chápu tak právě ten `lineage` objekt bude sloužit na ten lineage výpis. A ty další dva objekty `links` a `nodes` budou sloužit na ten graf.

**Comment by JakubMatejka** [comment]
@natocTo Aha, jasně! Názvy dodám. jo, links a nodes jsou pro graf. Ta data pro lineage by tam měla jít cca takto:
![image](https://user-images.githubusercontent.com/215660/54598925-dba31480-4a39-11e9-89e9-42e528fa1f32.png)

Akorát tam máš nějak divně duplikovaný ty idčka, měly by být určitě unikátní. To je projekt 5194? Podívám se na to, asi tam mám nějaký bug.

**Comment by natocTo** [comment]
Jo projekt 5194. Díky za popis.

**Comment by natocTo** [comment]
Teď už mi chodí jen:

```js
0: {id: 5651, distance: 1, role: "parent"}
```

To si stihl upravit? :)

**Comment by JakubMatejka** [comment]
Né. I když to zkusíš znovu? Já tam vidím: https://take.ms/6HNcB A ty duplicity tam budou asi kvůli tý smyčce. To je tam naschvál?
![image](https://user-images.githubusercontent.com/215660/54601295-f88e1680-4a3e-11e9-8a15-92fdf9256be2.png)

**Comment by natocTo** [comment]
To nevím jak se mi povedlo.

Může to být tím, že jsem si ve Snowflake extractoru hodit credentials ze sandboxu?

**Comment by JakubMatejka** [comment]
Bucket https://connection.keboola.com/admin/projects/5194/storage-explorer/in.c-keboola-ex-db-snowflake-469551086 je nalinkovanej do in.c-Shared2 v tom samým projektu. Ale to je teda vlastně asi legální. ;o)

**Comment by natocTo** [comment]
Tento týden na tom budu dělat už více tak snad s tím pohnu.

Tu logiku na lineagre už tam dostanu teď. To i když případně budeš měnit tu logiku když je ten nějaký usecase legální, tak struktura pak zůstane stejná že.

Divné je, že jak to zkouším, tak mi fakt chodí občas různé výsledky (teda pouze 2). 

Někdy mi příjde:
```js
0: {id: 5194, distance: 1, role: "parent"}
1: {id: 5194, distance: 1, role: "child"}
2: {id: 5651, distance: 1, role: "parent"}
3: {id: 5651, distance: 2, role: "parent"}
```

A pak najednou z ničeho nic jen:
```js
0: {id: 5651, distance: 1, role: "parent"}
```

**Comment by JakubMatejka** [comment]
Hm, divný. Prověřím to, ale na struktuře dat z API to nic měnit nebude, takže na tom klidně můžeš zatím dělat.

**Comment by natocTo** [comment]
@JakubMatejka dneska ještě dostávám 404ku, přitom myslím že jsem na api nic neměnil (doufám). Něco se tam mění?

**Comment by JakubMatejka** [comment]
@natocTo kua, někdo odsdílel tabulky ze Shared Configu, nebo co (a ani by to neměla být 404ka). Zkusím fixnout

**Comment by JakubMatejka** [comment]
Jo tak to jsem byl já, sorry. ;o) Už je to zpět + dám si issue na ten typ chyby, měla to být 500ka

**Comment by natocTo** [comment]
Super, jede to.

**Comment by natocTo** [comment]
Dnes pošlu nějaký první draft, grafika atd nebude stejná jako na obrázku výše ale inspirovaný to bude dost. Určo se to bude ještě ladit.

Na graph vypadá že půjde použít `dagre-d3` co už v projektu máme což je super. Dokonce asi půjde využít i `Graph` komponenta co tam máme. Pokud by se pak dělalo více úprav tak se to může zkopírovat a poupravit více na tento usecase, prozatím využívám tu z `common`.

Ta grafika výše je jen vzor nebo vše co tam je by mělo být také v realiaci? Zatím tam nemám ty počty záznamů pro každý level + skupiny (label 4 apod), implementace bude jednoduchá, spíše mě to tam moc nesedělo. Ale zatím jsem to testovat na mém pidi projektu tak možná na větším to je užitečnější.

Přemýšlím jak udělám odkaz na "overview", co jsem koukal, tak když jdu ve svém projektu na produkci třeba na notifikace, tak url vypadá `admin/account/notifications`. Vůbec tam ID projektu není.

Jinak jsem koukal že chodí věci jako `isOrigin` a `isHighlighted` tak to tam nějak používám. Odlišuji origin projekt (modrý), highlighted projet (modrý okraj) a ostatní projekty (šedý okraj). S tím že pokud `source` a `target` projekt je `highlighted` tak udělám modrou také tu spojnici.

Mezi projekty vidím nějaký text. Prozatím tam zkouším dostat oba buckety (`sourceBukcet | targetBucket`). To je ok nebo co tam má být?

**Comment by JakubMatejka** [comment]
@natocTo mně to připadá ok

Url stránek organizací jsou https://connection.keboola.com/admin/organizations/1 tak by to mělo jít(?)

Pokud vím, tak složitější graf má Mall (https://connection.eu-central-1.keboola.com/admin/organizations/13)

**Comment by natocTo** [comment]
Super, URL teda přidám.

**Comment by JakubMatejka** [comment]
@natocTo jak to prosím tě vypadá?

**Comment by natocTo** [comment]
Vlado mě minulý týden Zendesk, tento už řeší jedno UI PR za druhým, tak se určo dostane i k tomuto.
Za mě to R4R, ještě se mi teda povedlo kompletně aktualizovat grafické knihovny v KBC-UI, ale taky zatím to není v masteru, tak jedině bych pak chtěl ještě tu udělat rebase a poladit aby vše jelo na D3 v4.

**Comment by ujovlado** [comment]
Tak uz sa to da pozera vsade. `https://connection.keboola.com/admin/projects/XXX/overview`

**Comment by JakubMatejka** [comment]
Paráda 👍 Jdu to napsat do global slacku

**Comment by natocTo** [comment]
Nasazeno tak zavírám.
