### ISSUE TITLE
Storage Explorer

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2880]
1) Chybí mi vyhledávání tabulek, buckety jsou dost často k ničemu.
2) Nejde klikat na celej řádek s názvem tabulky, musím sniperovat pouze název.
3) Při kliku na vyhledanou tabulku se kompletně ztratí celej kontext, co jsem do té doby dělal (https://take.ms/R6G09)
4) V detailu tabulky se ihned načítá Graph, nešlo by to až po otevření záložky?
5) Detail bucketu - nešlo by třeba sloučit záložky overview a tables?
6) `Search event` -> `Search events` nebo `Filter events`? 
![image](https://user-images.githubusercontent.com/497675/52703820-7e6dfc00-2f7f-11e9-9d84-d77aa9bf2d87.png)
7) `Search bucket` -> `Search buckets` nebo `Filter buckets`?

**Comment by natocTo** [comment]
4) Tam je nedostatek v těch tabech. Kde jak jsou vypnuté animace už teď nevím přesně proč. Tak nefunguje mountOnEnter. Takže se vše inicializuje hned no. To mi taky přijde špatný. Ne jen že se načítá graph, ale taky eventy, data sample a prostě vše co je v těch tabech.

Na to zkusím ještě mrknout. Plus na nějaké ty další body.

**Comment by natocTo** [comment]
Ta 3. je divná. To už jednou reportoval @ujovlado ale pak se to zavřelo protože jsme psal že se to neděje. A možná teda děje. Ale u mě to funguje dobře. Tabulka na kterou kliknu zůstane otevřené taky po načtení.
