### ISSUE TITLE
Remove small table preview, use "full page" modal

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2881]
Momentalne vidno ten modal na celu stranku, len ked mas featuru `ui-devel-preview`. Chceme to dat pre vsetkych.

Nemalo by to nijako ovplyvnit to, ze mame v  "preview mode" prepisanu console.

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/blob/8b5d5990e8efa8f71471d5c38b9fe7498f5360e9/src/scripts/modules/components/react/components/StorageApiTableLinkEx.jsx#L252

**Comment by natocTo** [comment]
Mrknu.
