### ISSUE TITLE
moc klikani

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#289]
je to vic klikani, nez bylo predtim, napr input/output mapping transformace: stary ui: 2 kliky (tab, edit danyho mappingu, novy ui 3 kliky (edit tr., rozbalit, show details…), navic neustale musim scrollovat. Ty taby byly lepsi / rychlejsi / prehlednejsi

**Comment by Halama** [comment]
diky za feedback! 
tady zrejme probehnou nejake zmeny v te editaci viz. napr #279  smerem k tomu jak to bylo predtim.
Hromadna editace teda zrejme zmizi. U tech tabu vs. scrollovani je to tak pul na pul, mozna tady pomuze jenom lepe tam poskladat ty io mappingy.

**Comment by Halama** [comment]
Přepracovali jsme transformace tak jak fungovali dřív
