### ISSUE TITLE
Storage Explorer - long file name displaying

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2899]
Mohli by sme tam pridat jednu z tych nasich classes, nech to zalomi file name, aby tam nebol horizontalny scrollbar,

**Comment by ujovlado** [comment]
Aj ked v jobs myslim nic take nemame a je Table ID pekne zalomene :)

**Comment by natocTo** [comment]
V nové Storage bude všude použitý "responsive" prop u tabulek. Což obaluje tu tabulky responsive třídou s bootstrapu. To "povolí" ten horizontální scrollbar. Aby bylo vše líp čitelné.

Pokud by se pro třeba soubor povolilo zalomování, tak to asi nebude fungovat moc dobře. protože ostatní údaje se zalomovat moc nebudou a tak ten název se bude zalomovat extrémně, zkoušel jsme si to u jobs 
a nedopadne to dobře.

![break](https://user-images.githubusercontent.com/12331181/52940368-ac2fb800-3366-11e9-9125-27d3dd346983.png)

Myslím že podobné by to bylo i u těch files. By se spíš musela zakázat ta responsivita, a to nevím zda chceme. Nebo něco jinak uspořádata tam i informace, do jiných sloupců. Ať má název souboru více místa.

**Comment by odinuv** [comment]
nemohly by to byt takovy ty dvouradkovy radky? 
```
in.c-keboola.blabbalbalbablabalbalbal
   6877195 tableimport success 16s 244b
```

**Comment by natocTo** [comment]
Máme to někde abych si udělal lepší představu jak je to myšleno?

Ono je "problém" že ty tabulky třeba nebo soubory nemají v názvu žádné mezery no, takže není lehké je donutit se zalamovat. Jediné přímo tím css kde řeknu že se může zalamovat na každém písmenku, ale to pak jde do extrémů právě.

**Comment by natocTo** [comment]
Já si říkal že bych třeba ty sloupce: Public, Encrypted, Permanent mohl dát do jednoho a pod sebe.
Copy URL by mohlo být přímo u názvu souboru. Velikost skoro taky, to už tak někde je.
Tím by zmizelo 5 sloupců a zase by to bylo lepší, ikdyž by nějaký nový zase přibyl.

**Comment by odinuv** [comment]
nevim, asi to nikde nemame - je to proste tak, ze ten prvni sloupec je to dlouhe jmeno, ale vytahne se jako z te prvni bunky a zobrazi se na samostatnem radku, nevim jak to presneji popsat, nemuzu to ted nikde  najit ale urcite jsem to nekdy nekde videl :)

**Comment by natocTo** [comment]
Jo už asi rozumím. Zkusím to. 
Ještě zkouším nějak zredukovat ty ostatní sloupce a pošlu pak oba screenshoty třebas, jak to dopadlo.

**Comment by natocTo** [comment]
No tak nevím zda jsme to pochopil úplně ale zkusil jsme to teda hodit na samostatný řádek. Asi by to chtělo ještě ladit ale pro představu: Zkoušeno na šířce 1600px.

Současný vzhled:
![original](https://user-images.githubusercontent.com/12331181/52944376-8f4bb280-336f-11e9-81aa-73ffc1347492.png)

Pak ten samostatný řádek pro název:
![other](https://user-images.githubusercontent.com/12331181/52944401-983c8400-336f-11e9-93fa-6df1cfa6869f.png)

A ještě nějaké to přeskládání: (koukám vypadlo mi COPY tlačítko - bych doplnil)
![1600px](https://user-images.githubusercontent.com/12331181/52944412-9ecafb80-336f-11e9-9bde-dddcb474ed99.png)

**Comment by odinuv** [comment]
v ty verzi na samostatnym radku to pruhovani musi byt ob radek

**Comment by natocTo** [comment]
Zkusím.

**Comment by ujovlado** [comment]
Najlepsie je imho to posledne. Tie "setting" este mozeme poladit - moze to byt bez checkboxov. Zobrazis Public/Private. Zobrazis Encrypted alebo nic (myslim ale ze encrypted je asi vsetko). No a zobrazis Expiration (ak nejaka je, tak asi rovno datum) alebo Expired, ked uz vyexspiroval.

Ten samostatny riadok na file name podla mna zavera zbytocne vela miesta.

**Comment by natocTo** [comment]
Jen teda pro představu, vůbec to není stopro, tu by se muselo ladit CSS více.

![tworows](https://user-images.githubusercontent.com/12331181/52945935-2bc38400-3373-11e9-854b-0b516f501173.png)

**Comment by natocTo** [comment]
Ty 3. variantu pošlu teda jako PR, ať se s tím dá třeba ještě hrát. Já si odběhnu na oběd tak kdyby si dělal UI tak to klidně upravuj. Nebo to doupravím až dorazím hned.

**Comment by odinuv** [comment]
no taky nevim, ale v te 2. variante to celkem zabira 3 radky :) takze jeste vic mista, mimochodem neni to encrypted uz deprecated?

**Comment by natocTo** [comment]
encrypted vypadá že se furt "používá". Mám tam soubory staré 14 dní třeba které nejsou encrypted.
