### ISSUE TITLE
jobs: transformation detail

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#291]
defaultne nechat collapsnutou sekci import / export

**Comment by Halama** [comment]
jako zabalenou? Z jakeho duvodu, protoze te zajimaji log spis?

**Comment by radovanjirka** [comment]
presne:-)

RJ
---
Radovan Jirka
radovan.jirka@bizztreat.com
@xjirkar
+420 608 052 066

**Comment by ujovlado** [comment]
toto zatial nebudeme menit
