### ISSUE TITLE
Storage explorer - slow description edit

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#2915]
Pokud edituju description tabulky v projektu kde je více tabulek, např. [Shared Config](https://connection.keboola.com/admin/projects/258/storage-explorer/in.c-keboola-ex-papertrail-471162637/events) tak je psaní textu dost zpomalené.

Možná tam správně neořezává někde purerender a volá to render nad celým stromem při změne?

**Comment by ujovlado** [comment]
Tam je hodne divne, ze to nejde cez interny state tej komponenty ale cez store. Na taketo male veci mi to pride riadny overkill.

**Comment by natocTo** [comment]
S kombinací s tímto to může být zabiják no.

https://github.com/keboola/kbc-ui/blob/5859e733a2a29e4bdfd385bfd72db4e31ceea965/src/scripts/stores/RoutesStore.js#L354

Situace je třeba taková MetaDescription komponenta updatuje svůj metadata store. RoutesStore díky tomuto vždy emituje změnu, i když stav je stejný. Všechny componenty co mají v mixinu RoutesStore se budou aktualizovat, abychom alespoň zastavily render pak když je vše stejné, musíme nasadit nějaký PureRenderMixin nebo ImmutableRenderMixin. Myslím že by stálo za to se podívat proč to takto přesně je, a zkusit to vyřešit jinak.

**Comment by natocTo** [comment]
Pokud by se ale edit stav nepřenášel do Storu, bylo by to podle mě taky fajn. S kombinací s tímto PR #2762 by to znamenalo, že by celý metadatastore a souvysející věci mohly jít pryč.
