### ISSUE TITLE
disablovany projekty

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#292]
https://www.evernote.com/l/AErk4YBeVFpEv6pWe_IlQpN9HYmY56N-o50 ale ja jsem je nesmazal? Resp. u toho "Robert" jsem pozadal o smazani Padaka, zbyly 2 by mely bejt normalne k dispozici... ?

**Comment by Halama** [comment]
ve starem ui to vidis jinak?

**Comment by radovanjirka** [comment]
jj. projekt Robert je smazany a ty zbyly jsou normalne pristupny...

**Comment by Halama** [comment]
ahoj,
zkontroloval jsem to a je to ok. Z nejakeho duvodu byly disablovane (tim zatim resime smazani).
Pokud nemaji byt disablovane/smazane hod to prosim normalne na support@keboola.com

Nemelo by to souviset s novym ui, v obou verzich to vidim stejne.
diky
