### ISSUE TITLE
Nová Storage: Link bucket

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2920]
Při linkování bucketu vytékají jména ven z okna a oproti původnímu to postrádá search:

![image](https://user-images.githubusercontent.com/1427901/53077243-e11c4600-34f1-11e9-80a0-c3dbf1c7b47f.png)

(vím že jde hledat, ale když píšeš, tak nevidíš co jsi napsal a vyhledat na mém screenshotu "gd" a pak to opravit na "proj" je nemožné)

**Comment by natocTo** [comment]
Přemášlím co s tím tu. Bohužel React-Select 1.3 neumí optgroup. Asi prostě připojít název projektu ke každé možnosti a vypíšu to jako klasické možnosti do react-selectu. Až bude nový React a react-select v2 půjde použít i optgroup.
