### ISSUE TITLE
Nová Storage: table search

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2922]
Při hledání se suprově rozbalí buckety co jsou matchnuté:

![image](https://user-images.githubusercontent.com/1427901/53077438-4b34eb00-34f2-11e9-93db-ab539f2073d6.png)

a v momentě kliknutí na tabulku to zmizí. Bylo by fajn to nechávat, protože já si takhle najdu bucket a pak si chci prohlídnout pár tabulek a musím to psát znovu a nebo se přeorientovat na drobečkovou navigaci co se nově objeví kliknutím na tabulku, kliknout v drobečkové navigaci na bucket a nově vybírat tabulky co jsem chtěl prozkoumat v pravé části.

**Comment by ujovlado** [comment]
@padak tym, ze si klikol na jednu tabulku, mal by ti vlavo ostat ten bucket otvoreny (t.j. nestratit kontext). Vidim, ze je to shared config, pozrem sa.

**Comment by ujovlado** [comment]
Jo, uz vidim. Ono to ostalo, akurat ten bucket je dole v prdeli. Mam monitor na vysku, no aj tak to vidim az po 3 strankach :)

**Comment by natocTo** [comment]
Něco takového už ready bylo, ale nakonec se nepoužilo. Klidně to připravím znovu.

**Comment by ujovlado** [comment]
Nj, ta navigacia, ked mas viac bucketov a chces preklikavat medzi tabulkami je pain. Detail bukcetu -> tabulka -> detail bucketu -> tabulka. A dookola.

@natocTo kuknem sa na PR, kde sme to riesili
