### ISSUE TITLE
Nová Storage: validace před odesláním

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2923]
Šlo by validovat inputy když je zadáváš? Abys nezjistil po odeslání co je blbě?

![image](https://user-images.githubusercontent.com/1427901/53078637-efb82c80-34f4-11e9-94b0-fcd5ce7dcca5.png)

**Comment by ujovlado** [comment]
Novy bucket a tabulku asi vieme vyriesit ako hotfix. Inac by som sa na to chcel pozriet univerzalnejsie: #1580

**Comment by natocTo** [comment]
Není těch znaků povolených více? Třeba také `-`.

**Comment by natocTo** [comment]
A ještě mě zajímá, když dám třeba název `test` a stage `in`. tak výsledek je `in.c-test`, to C tam je vždy? Nebo nemusí?

**Comment by ujovlado** [comment]
Je to tam vzdy.

**Comment by ujovlado** [comment]
Je to nejaky historicky pozostatok :)

**Comment by natocTo** [comment]
Díky 👍 A ten regex povolený pro name je teda jaký? Aby to odpovídalo backendu, já než bych to tam dohledal.

**Comment by ujovlado** [comment]
`c-` ti tam doplni vzdy

**Comment by ujovlado** [comment]
Kuknem, w8

**Comment by ujovlado** [comment]
Z backendu:

```php
array(
    'pattern' => '/^[a-zA-Z0-9_-]+$/',
   'messages' => 'Only alphanumeric characters and underscores are allowed in bucket name',
 )
```

**Comment by natocTo** [comment]
super, tak použiji to samé.. já tam měl právě \w a přitom jsem viděl že ostatní buckety mají také pomlčky.

**Comment by ujovlado** [comment]
A taky isty je na table name.

**Comment by ujovlado** [comment]
+ tabulka moze mat min 1  a max 64

**Comment by ujovlado** [comment]
a tabulka nemoze zacinat `_`

**Comment by ujovlado** [comment]
A kukam, ze uz tam nieco je `validateStorageTableId.js` :)

**Comment by ujovlado** [comment]
tak asi mozes rozsirit to, pripadne to rozbit na validaciu table/bucket/buckat&table. A doplnit testy atd

**Comment by natocTo** [comment]
Já to dělal spíše jako ten hotfix teď jak si psal. Že snad brzy pak začneme používat něco obecného na vše možné. Teď jsem chtěl přidat jen kontrolu těch znaků + jsem si říkal že bude fajn hlídat název obecně (duplicitu) protože je škoda uploadovat třeba veliké CSV na novou tabulku a pak dostat chybu že tabulska se jménem XY již existuje. No uvidíš v PR, dyštak to ale rozšířím ještě.

**Comment by ujovlado** [comment]
jo, to bude vpohode imho :)
