### ISSUE TITLE
Python transformations - missing link to config (in detail)

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#2932]
![Alt text](https://monosnap.com/image/XcaiamvLcVRjZ4unZ069diY7SmErI3.png)

**Comment by MiroCillik** [comment]
Aj ked ta "parent" transformacia ho ma, zislo by sa to mat aj tu nie?

**Comment by natocTo** [comment]
Mrknu.

**Comment by MiroCillik** [comment]
![Alt text](https://monosnap.com/image/7lxkbXpHQrInenCeXQnmVozZQ6nyKW.png)

**Comment by ujovlado** [comment]
Toto bude teda len pre detail.

**Comment by ujovlado** [comment]
A https://github.com/keboola/kbc-ui/issues/2932#issuecomment-465595526 sa poriesi v ramci #1027
