### ISSUE TITLE
Odstranění MySQL transformací

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2946]
![image](https://user-images.githubusercontent.com/497675/53180872-c5e72e80-35f6-11e9-8b91-5ff39c276f63.png)

MySQL transformace se stále zobrazují, ale už nejdou pustit ani přidat. Je kvůli tomu v kódu docela dost věcí, mohlo by se to vyhodit a MySQL transformace zobrazovat už třeba jen jako JSON a nebo default jako u nepodporovaných typů

![image](https://user-images.githubusercontent.com/497675/53181963-d8fafe00-35f8-11e9-81fc-5f86a6d90cb3.png)

Neznámé typy transformací taky mají špatnou ikonku/label

![image](https://user-images.githubusercontent.com/497675/53182003-ea440a80-35f8-11e9-825e-98d40608ac71.png)

**Comment by ujovlado** [comment]
Zakazal by som ist do detailu:

https://github.com/keboola/kbc-ui/blob/bde9b6abc3f0198a2efe46e7ee6756fbc5618122/src/scripts/modules/transformations/react/components/TransformationRow.jsx#L87

A jedine co sa bude dat s takou transformaciou spravit je zmazat ju (teda na zozname)

Ak by sa niekto predsalen na detail dostal, tam by bolo, co mas v 2. screehshote (not supported). A v sidebare len moznost zmazat.
