### ISSUE TITLE
storage explorer jobs refresh

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2950]
when there is a processing job, the counter keeps changing, which gives the impression that the page is reloading but it is not

![image](https://user-images.githubusercontent.com/4319320/53192640-44e86100-360f-11e9-8be0-080d4f611d40.png)

i don't mind if it doesn't reload automatically, but it should not like that it does

**Comment by ujovlado** [comment]
Neviem ci sa toto oplati riesit. Reloadovat to nechceme. Ale zase ked skryjem ten cas, bude ti vadit, preco to svieti "processing", ked sa to nereloaduje :)

**Comment by odinuv** [comment]
no takhle se to taky nereloaduje, akorat je tam cas a ubiha 1:34 5:40 pak si rekenes, to neni mozny, das reload stranky a heleho 30s...

**Comment by odinuv** [comment]
tak at aspon ten cas neubiha, pak bude videt, ze se to nereloaduje

**Comment by odinuv** [comment]
tak at aspon ten cas neubiha, pak bude videt, ze se to nereloaduje

**Comment by ujovlado** [comment]
A ze ti tam bude "cakat" waiting/processing, to neva? (ale ok, to vieme vyhodit razdva)

**Comment by odinuv** [comment]
primarne me vadi, ze se to tvari, ze se to refreshuje a nerefreshuje se to
sekundarne me vadi, ze se to nerefreshuje :D

tak jo, myslim, ze kdyz se to vyhodi, ze to bude lepsi (= jasnejsi)

**Comment by Halama** [comment]
proč to nechceme reloadovat jinde to tak je ne?

**Comment by ujovlado** [comment]
No zda sa mi, ze tam bol so storage jobmi nejaky problem, ze to bolo pomalsie, tak sme to nechceli reloadovat.

**Comment by Halama** [comment]
o tom nevim, kdyz tam das jednou za 30 sec nebo tak neco tak to imho problem nebude. Myslim ze jsem byl jenom linej to v te stare angular konzoli udelat.
