### ISSUE TITLE
storage explorer - distinguish between expanded and open bucket

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#2951]
![image](https://user-images.githubusercontent.com/4319320/53198062-cb0aa480-361b-11e9-988b-e69c3a485646.png)

vypadaji stejne, ale jeden z nich jde sbalit a druhy ne, protoze ten druhy je rozbaleny proto, ze mam otevreny detail bucketu (coz je logicky), coz neni videt, kdyz jsem odscrolovany nekde v haji. Je to celky takovy pofiderni, ale kdyby slo ten rozbeleny od otevrenyho bucketu nejak zvyraznit, tak bych se ho asi nesnazil sbalovat.

**Comment by ujovlado** [comment]
Viem si predstavit, ze by ten aktualny mal lavy border, tak ako v menu:

![screenshot 2019-02-22 at 09 25 32](https://user-images.githubusercontent.com/419849/53229168-d2659880-3683-11e9-8dac-ff0d18175493.png)

Ale viac by som to neladil, ide sa to coskoro redesignovat podla Jackovho navrhu.

**Comment by odinuv** [comment]
urcite bych to neladil
