### ISSUE TITLE
Reload storage/jobs and files automatically

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2958]
Related to #2950

**Comment by natocTo** [comment]
Myslím že by to teda mohlo být stejné taky pro Files.

**Comment by natocTo** [comment]
Jinak klidně se toho ujmu, než mrkneš na nějaký review :) ale jestli už na tom děláš tak dobrý.

**Comment by ujovlado** [comment]
Kludne. Pozeram, ze normalne jobs reloadujeme kazdych 10s, tak daj `poll.interval` kludne dvojnasobok. Na files asi detto.

**Comment by natocTo** [comment]
ok
