### ISSUE TITLE
Stránka projektů - černé okraje

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#296]
Ahoj,

nemohly by ze stránky s projekty zmizet vedle obrázku ty černé okraje? Vypadá to ošklivě. Navíc když celá KBC má pak width 100%.

![your projects keboola connections 2015-07-14 07-21-50](https://cloud.githubusercontent.com/assets/12933713/8667007/89a9988e-29f9-11e5-878c-e5565cb02e7a.jpg)

**Comment by JakubMatejka** [comment]
To bohužel nemohly, je to konec té fotky. Můžu tam maximálně místo té tmavé (není to černá ale barva toho kopce vpravo dole) dát světle šedou z horního okraje fotky ale bude to úplně stejně oseknutý.

**Comment by padak** [comment]
A nesezeneme si nějaký jiný (větší) fotky, který bysme tam rotovali?
Dne 14. 7. 2015 9:39 napsal uživatel "Jakub Matějka" <
notifications@github.com>:
