### ISSUE TITLE
BigQuery Writer OAuth not working

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2966]
![image](https://user-images.githubusercontent.com/497675/53290017-d803d100-379e-11e9-8cf1-d2d1c75e0bc8.png)

Pak jsem jednou udělal autorizaci na google drive a pak to začalo chodit. 

![image](https://user-images.githubusercontent.com/497675/53290049-1f8a5d00-379f-11e9-9ad4-76f9bb8f1a29.png)

**Comment by MiroCillik** [comment]
Bol tam bug, DynamoDB scan pri vacsom pocte dat zacne strankovat, co tam nebolo vyriesene :(
https://keboola.slack.com/archives/C069TGKT7/p1551034381002300

Tu to zatvaram.
