### ISSUE TITLE
Search u projektů - diakritika

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#297]
Ahoj,

nemohl by search na stránce výběru projektu a v levém panelu ignorovat diakritiku?
Např. začu psát "ce" a vyjede mi to i Českou Spořitelnu.
![select sheets 2015-07-15 10-42-55](https://cloud.githubusercontent.com/assets/12933713/8694337/8fce7e6a-2ade-11e5-91d9-6e95f70eab6e.jpg)
![select sheets 2015-07-15 10-45-26](https://cloud.githubusercontent.com/assets/12933713/8694348/9fead67c-2ade-11e5-8205-c487794e9a8b.jpg)

**Comment by Matejkys** [comment]
Teď teda koukám, že nevím, proč mi "ce" našlo např. Baťu a Home Credit

**Comment by Halama** [comment]
jo s tou diakritikou je je to dobrý napad.

Pro "ce" ti to našlo tyhle věci protože to vyhledává "fuzzy" i sekvence znaku, tady. teda CrEdit
