### ISSUE TITLE
Add missing icons (Storage Explorer)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2972]
Este som si vsimol, ze v tych dropdownoch "actions" nad tabulkou a bucketmi nam chybaju ikony.

**Comment by ujovlado** [comment]
Je to mala vec, ale aspon to bude jednotne

**Comment by ujovlado** [comment]
A posledny task. Chutovecka 🍒

**Comment by natocTo** [comment]
Jdu na to.
