### ISSUE TITLE
Link existing oauth credentials

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2976]
Myslim, ze by bolo fajn, aby sme fixli situaciu, ked user spravi Rollback na verziu, ked nema credentials, no napriek tomu sa mu tam zobrazuje, ze ma.

Da sa to uplne lahko nasimulovat takto:

1. vytvoris config
2. autorizujes
3. ides do Versions, das Rollback na verziu 1
4. prejde do detailu.
5. UI ti napriek tomu, ze si spravil Rollback, ukaze, ze to mas autorizovane.

Pokracovat sa da tak, ze das Run (alebo nejaku sync akciu). A ten job skonci chybou. Povies si WTF? Ved mam autorizovane.

Opravit by to slo tak, ze nebudem ukazovat, ze mam autorizovane, ked nemam.

Ale ponukli by sme mozno userovi linknut si tie credentials nanovo, alebo nastavit nove. Napr. nejako takto:

![screenshot 2019-02-25 at 16 59 37](https://user-images.githubusercontent.com/419849/53350773-170d6000-3920-11e9-9187-21fa82ad11fa.png)

Opravilo by to tie nejasnosti s autorizaciou pri Rollbacku a pod.

**Comment by natocTo** [comment]
Když uživatel 1 udělá konfiguraci, pak udělá rollback a teda mu zmizí. Je v pohodě uživateli 2 co přijde do stejné konfigurace ve stejném projektu, aby mu to nabídlo připojit tu původní autorizaci co udělal uživatel 1? Moc se mi to nezdá, ale radši se ptám. Případně to můžu teda asi hlídat podle ID uživatele.

**Comment by odinuv** [comment]
> Když uživatel 1 udělá konfiguraci, pak udělá rollback a teda mu zmizí. Je v pohodě uživateli 2 co přijde do stejné konfigurace ve stejném projektu, aby mu to nabídlo připojit tu původní autorizaci co udělal uživatel 1

me to prijde uplne v pohode. To je stejny jak kdyz je to jednou autorizovany, tak taky muze nekdo jiny prijit a zacit se v tom "hrabat" a porad pouzivat cizi credentials. Takze naopak asi i chceme zduraznit, ze to je nejakym zpusobem sdileny a pokud si autorizujes svuj osobni google driv plnej domaciho porna, tak jsi blbec. (hlidat na UI id uzivatele nema smysl, protoze to muzes vzdych obejit pres API).

**Comment by natocTo** [comment]
Fajn, to dává smysl. Pak to teda nemusím upravovat tuším.
