### ISSUE TITLE
reloading sapi jobs prevents going back to history

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#2983]
potřebuju se na stránce jobů ve storage proklikat ke staršímu jobu, ale každejch 20 vteřin se mi list vyresetuje a začínám od začátku

**Comment by natocTo** [comment]
Mrknu. Já tam dopľnoval search, ale limit tam je asi furt stejný no. Opravím.

**Comment by Halama** [comment]
Musíš bejt rychlej :)

**Comment by ondrejhlavacek** [comment]
@Halama jsem rychlej, api je pomalý! furt jen čekám, než se načte další stránka :D

**Comment by padak** [comment]
Několik lidí mi řeklo, že by bylo super, kdyby šlo najednou načíst všechno.

**Comment by natocTo** [comment]
V PR co je připravený (čeká na review) je nový query parametr `limit`, ten teda funguje pouze pro ten auto reload, ale i tak by to šlo použít pro nějaké "větší" hromadné načtení upravením URL, což teda nemá nic společného s UX nebo tak, ale může se hodit. Než by se přidalo něco konkrétního na tuto featuru.

**Comment by Halama** [comment]
@padak co myslíš načíst všechno najednou? Těch jobů můžou být stovky tisíc

**Comment by padak** [comment]
@Halama měl jsem líp číst. nešlo o načtení všech jobů, ale všech eventů u jednoho jobu, abys nemusel klikat 15x na tlačítko `More` abys našel eventy ze začátku běhu. Sorry za topic-mix :(
