### ISSUE TITLE
Search in new console

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2986]
Marcus and Fisa commented that new search should hide tables which doesn't match the search keyword. Bigger projects has very unreadable result if you're 'shopping' for relatively common table name. This is example from https://connection.keboola.com/admin/projects/405/storage-explorer

Enjoy the scrolling :) In the project, list of results has about next 40% more :)

![search](https://user-images.githubusercontent.com/1427901/53449976-6c7a6780-3a1b-11e9-8f76-e5b3eb5de793.png)

**Comment by natocTo** [comment]
Tam byl tuším problém takový, že to hledá jak mezi buckety, tak mezi tabulky. Takže pokud by to hledání odpovídalo názvu bucketu, ale už ne žádné tabulce, bylo by to prázdné. Nebo by to muselo kombinovat to že pokud odpovída bucket, tak už to nebude filtrovat tabulky, ale si zas možné člověk bude říkat že se to chová podivně že jednou to něco nezobrazuje pak zas jinde jo apod.

**Comment by padak** [comment]
Tuším, že to je záměr. Myšlenka nového (budoucího) searche je, že tam něco napíšeš a dostaneš zbytek akcí. Jako ve Slacku. Takže bys napsal "user" a ono to filtrovalo jen tabulky a někde bokem by vyskočilo ovládání vyhledávání kde bys měl volbu "search for bucket name" + další. Zkus si to ve slacku - jen dej hledat třeba "hovno", zmáčkni enter a v pravo máš na jeden klik redukování. 

Tak s touhle logikou bych se tomu blížil tím, že bych hledal teda jen tabulky a pro hledání ve jménu bucketu bych tam měl nějakej jeden rychlej klik, zatím klidně kolem toho vyhledávání. A nebo bych se na jména bucketů vyprd?

**Comment by natocTo** [comment]
Na to redukování mrknu. Rovnou vyhodit hledání v bucket name si netroufnu, to se případně zítra poptám na slacku. Ale nejdříve to zkusím upravit.

**Comment by padak** [comment]
@natocTo jasně! Teď je čas na spaní a ne na workaroundy :)

**Comment by ujovlado** [comment]
To redukovanie by som teraz neriesil. Myslim, ze na to bude priestor, ked budeme aplikovat ten novy design (odhadujem tak za 2-3 tyzdne), tam sa s tym moze niekto bavit dlhsie.

**Comment by ujovlado** [comment]
Aktualne to mozeme fixnut tak ze to skryje veci ktore neobsahuju ten string.

- najskor by to vyhladavalo v tabulkach
- ak sa tabulka najde, je to jasne, zobrazime ten bucket a len matchnute tabulky v nom
- ak to nematchne ziadnu tabulku, kukneme, ci to nematchne bucket
- ak to matchne bucket, zobrazime ho zbaleny a budes moct ist do jeho detailu

Dava to zmysel?

Nestane sa ti teda, ze mas 5 bucketov, ktore maju v mene “test”, kazdy ma 50 tabuliek, a ty uvidis 250 tabuliek.

**Comment by natocTo** [comment]
Zkusím.

**Comment by ujovlado** [comment]
Skusil som to este v tom projekte 405. je to uz cajk, nema to kilometer. 👍
