### ISSUE TITLE
Zmizelo tlačítko edit/save TR query

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#299]
Chválím, že teď můžu kliknout na jednotlivé transformační query a zůstane mi tam přesně kurzor.
Ale vrátil bych zpět tlačítka edit/save do pravého horního rohu na lištu, která se drží na vrchu stránky. Bylo ideální, že jsem mohl například něco v půlce stránky vykopírovat a pak dát jen cancel, nebo tam něco změnit a dát save. Taky často nahraju data do sandboxu, dám v TR edit, cmd+a, cmd+c a pak jsem mohl rovnou dát cancel, ale teď musím zase scrollovat až dolu.
![transformation multichannel 2015-07-16 15-25-40](https://cloud.githubusercontent.com/assets/12933713/8723621/70c3d334-2bcf-11e5-9fdb-a988258f3c7c.jpg)

**Comment by Halama** [comment]
Nasazené bude za pár minut

**Comment by Halama** [comment]
nasazeno
