### ISSUE TITLE
Nesmazatelná notifikace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#2996]
Uživateli radek.hajek@kofola.cz svítí v EU 6 měsíců stará notifikace o smazání KBC projektu (261). Pokud ji označí jako přečtenou, tak po reloadu ji vidí zase zpět. Viděl jsem to f2f na jeho kompu.

**Comment by odinuv** [comment]
https://github.com/keboola/connection/issues/1121

**Comment by ujovlado** [comment]
Ma to issue na connection, tu to zavrem.
