### ISSUE TITLE
orchestration - handle non-existent tasks gracefuly

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3016]
- create configuration C1
- create orchestration
- add C1 to orchestration tasks
- delete C1
- go to orchestration tasks
- click detail -> application error

http://youtu.be/ppf_lI8jG2s?hd=1

**Comment by natocTo** [comment]
Když jdu takto podle instrukcí tak už v orchestraci nemám odkaz ale jen `N/A`. Ale nevím jestli něco nedělám špatně.

A tam jde aby to nebyl odkaz?

Jinak obecně jsem přemýšlel že by na Overview mohl být nějaký Alert kde by bylo info že třeba transformace má v IM smazaný tabulky, nebo že orchestrace obsahuje smazaný konfigurace apod no. Že by to uživateli uskladnilo mít v projektu "pořádek". Ale nevím zda jde vše hned vyčíst z načtených dat na začátku.

**Comment by odinuv** [comment]
ha! pardon, ja to asi udelal v jinym vokne, tak to je asi v poho

no tech alertu by tam mohlo byt vic a neresil bych to v tyhle issue, zaviram to

**Comment by natocTo** [comment]
Jasné, dobrý. Tamto si promyslím a zkusím někdy ve volnější chvíli.
