### ISSUE TITLE
Div.container na stránce bez sidebaru

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#302]
Nemůže tam být `div.container` protože má od bootstrapu fixní šířku, měl by to být `div.container-fluid`

<img width="1215" alt="ui_applications_settings___keboola_connections" src="https://cloud.githubusercontent.com/assets/215660/8743136/d0ab4ce4-2c6c-11e5-8076-026dc9023335.png">

**Comment by Halama** [comment]
fixnuto
