### ISSUE TITLE
Wishlist modal

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/kbc-ui#3029]
Related: https://github.com/keboola/internal/issues/117

Related: https://github.com/keboola/connection/pull/1865

Potřeboval bych, aby mi to poslalo do KBC "form data" podobně jako https://github.com/keboola/kbc-ui/blob/73743ab69a763d7769767d733c5ef10a7440651e/src/scripts/modules/home/actions.js#L6. 

Musí to poslat `title`, `description` a `xsrf`. Zpátky to vrátí buď HTTP 201 - wishlist poslán nebo 422 a pole `{errors: {element:[error messages]}}`. 

Zkusil jsem to vykopnout, ale je to 💩 - kdyžtak, kdyby to nejelo, tak si to nějak doladím. Kdyby něco jsem ready na dotazy....

**Comment by tomasfejfar** [comment]
Moje práce je tady: https://github.com/keboola/kbc-ui/pull/3030

**Comment by ujovlado** [comment]
@natocTo neviem ale ci to budes mat ako overit, idealne je mat na test funkcny connection backend.

Ak chces, sprav to nejako "na slepo", ja to potom doladim. Alebo to kludne nechaj na mna.

**Comment by tomasfejfar** [comment]
S connection to otestuju já. Pullnu si to a zkusím co to udělá...
