### ISSUE TITLE
Get rid of KbcBootstrap proxy

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3031]
Je tam 55 pouziti. Spravme to tak, ze si to nejako rozdelime. Chceli sme sa toho zbavit uz davno a toto je vhodna prilezitost.

Idealne, ked v jednom PR nebude viac ako 5-6 zmenenych importov.

@ujovlado

- [x] src/scripts/modules/app-snowflake-dwh-manager/react/components/Credentials.jsx
- [x] src/scripts/modules/app-snowflake-dwh-manager/react/components/Configuration.jsx
- [x] src/scripts/modules/ex-db-generic/react/pages/credentials/SSLForm.jsx
- [x] src/scripts/modules/ex-db-generic/react/pages/credentials/CredentialsForm.jsx
- [x] src/scripts/modules/geneea-nlp-analysis-v2/react/Index.jsx

@natocTo 

- [x] src/scripts/modules/transformations/react/modals/NewTransformation.jsx
- [x] src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx
- [x] src/scripts/modules/transformations/react/components/mapping/input/RedshiftDataTypesAddForm.jsx
- [x] src/scripts/modules/transformations/react/components/mapping/InputMappingRowRedshiftEditor.jsx
- [x] src/scripts/modules/transformations/react/components/mapping/InputMappingRowDockerEditor.jsx

@ujovlado

- [x] src/scripts/modules/transformations/react/components/mapping/OutputMappingRowEditor.jsx
- [x] src/scripts/modules/transformations/react/components/CreateDockerSandboxForm.jsx
- [x] src/scripts/modules/ex-aws-s3/react/components/Credentials.jsx
- [x] src/scripts/modules/ex-aws-s3/react/components/Configuration.jsx
- [x] src/scripts/modules/gooddata-writer/react/components/TableLoadType.jsx

@natocTo 

- [x] src/scripts/modules/gooddata-writer/react/components/NewDimensionForm.jsx
- [x] src/scripts/modules/gooddata-writer/react/pages/table/DatasetColumnEditorRow.jsx
- [x] src/scripts/modules/ex-adform/react/CredentialsForm.jsx
- [x] src/scripts/modules/wr-db/react/pages/table/ColumnRow.jsx
- [x] src/scripts/modules/wr-db/react/pages/credentials/CredentialsForm.jsx

@ujovlado

- [x] src/scripts/modules/provisioning/react/components/RedshiftCredentials.jsx
- [x] src/scripts/modules/limits/EditLimitModal.jsx
- [x] src/scripts/modules/wr-google-sheets/react/components/SheetTab.jsx
- [x] src/scripts/modules/wr-google-sheets/react/components/InputMapping.jsx
- [x] ~src/scripts/modules/components/react/components/DropboxAuthorizeModal.jsx~

@natocTo 

- [x] src/scripts/modules/components/react/components/RuntimeConfigurationEdit.jsx
- [x] src/scripts/modules/components/react/components/generic/FileOutputMappingEditor.jsx
- [x] src/scripts/modules/components/react/components/generic/TableInputMappingEditor.jsx
- [x] src/scripts/modules/components/react/components/generic/TableOutputMappingEditor.jsx
- [x] src/scripts/modules/components/react/components/generic/FileInputMappingEditor.jsx

@ujovlado

- [x] src/scripts/modules/components/react/pages/new-component-form/GoodDataWriterForm.jsx
- [x] src/scripts/modules/components/react/pages/new-component-form/DefaultForm.jsx
- [x] src/scripts/modules/components/react/pages/new-component-form/AppVendorInfo.jsx
- [x] src/scripts/modules/ex-s3/react/components/Advanced.jsx
- [x] src/scripts/modules/ex-s3/react/components/Settings.jsx

@natocTo 

- [x] src/scripts/modules/ex-s3/react/components/Credentials.jsx
- [x] src/scripts/modules/csv-import/react/components/Settings.jsx
- [x] src/scripts/modules/data-takeout/Form.jsx
- [x] src/scripts/modules/ex-google-analytics-v4/react/components/QueryEditor/ProfileSelector.jsx
- [x] src/scripts/modules/ex-mongodb/react/pages/credentials/CredentialsForm.jsx

@ujovlado

- [x] src/scripts/modules/ex-http/react/components/Credentials.jsx
- [x] src/scripts/modules/ex-http/react/components/Configuration.jsx
- [x] src/scripts/modules/wr-google-drive/react/components/InputTab.jsx
- [x] src/scripts/modules/wr-google-drive/react/components/FileTab.jsx
- [x] src/scripts/modules/ex-twitter/react/Wizard.jsx

@natocTo 

- [x] src/scripts/modules/ex-ftp/react/components/SourcePath.jsx
- [x] src/scripts/modules/tde-exporter/react/pages/Destination/TableauServerCredentialsModal.jsx
- [x] src/scripts/modules/tde-exporter/react/pages/Table/Table.jsx
- [x] src/scripts/modules/ex-google-bigquery/react/Index/ProjectsManagerModal.jsx
- [x] src/scripts/modules/wr-aws-s3/react/components/Credentials.jsx

@ujovlado

- [x] src/scripts/react/layout/NewProjectModal.jsx
- [x] src/scripts/react/common/CopyVersionModal.jsx
- [x] src/scripts/react/common/CsvDelimiterInput.jsx
- [x] src/scripts/react/common/SshTunnelRow.jsx
- [x] src/scripts/react/common/NonStaticSshTunnelRow.jsx

**Comment by ujovlado** [comment]
@ujovlado
src/scripts/modules/app-snowflake-dwh-manager/react/components/Credentials.jsx
src/scripts/modules/app-snowflake-dwh-manager/react/components/Configuration.jsx
src/scripts/modules/ex-db-generic/react/pages/credentials/SSLForm.jsx
src/scripts/modules/ex-db-generic/react/pages/credentials/CredentialsForm.jsx
src/scripts/modules/geneea-nlp-analysis-v2/react/Index.jsx

@natocTo 
src/scripts/modules/transformations/react/modals/NewTransformation.jsx
src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx
src/scripts/modules/transformations/react/components/mapping/input/RedshiftDataTypesAddForm.jsx
src/scripts/modules/transformations/react/components/mapping/InputMappingRowRedshiftEditor.jsx
src/scripts/modules/transformations/react/components/mapping/InputMappingRowDockerEditor.jsx

@ujovlado 
src/scripts/modules/transformations/react/components/mapping/OutputMappingRowEditor.jsx
src/scripts/modules/transformations/react/components/CreateDockerSandboxForm.jsx
src/scripts/modules/ex-aws-s3/react/components/Credentials.jsx
src/scripts/modules/ex-aws-s3/react/components/Configuration.jsx
src/scripts/modules/gooddata-writer/react/components/TableLoadType.jsx

@natocTo 
src/scripts/modules/gooddata-writer/react/components/NewDimensionForm.jsx
src/scripts/modules/gooddata-writer/react/pages/table/DatasetColumnEditorRow.jsx
src/scripts/modules/ex-adform/react/CredentialsForm.jsx
src/scripts/modules/wr-db/react/pages/table/ColumnRow.jsx
src/scripts/modules/wr-db/react/pages/credentials/CredentialsForm.jsx

@ujovlado 
src/scripts/modules/provisioning/react/components/RedshiftCredentials.jsx
src/scripts/modules/limits/EditLimitModal.jsx
src/scripts/modules/wr-google-sheets/react/components/SheetTab.jsx
src/scripts/modules/wr-google-sheets/react/components/InputMapping.jsx
src/scripts/modules/components/react/components/DropboxAuthorizeModal.jsx

@natocTo 
src/scripts/modules/components/react/components/RuntimeConfigurationEdit.jsx
src/scripts/modules/components/react/components/generic/FileOutputMappingEditor.jsx
src/scripts/modules/components/react/components/generic/TableInputMappingEditor.jsx
src/scripts/modules/components/react/components/generic/TableOutputMappingEditor.jsx
src/scripts/modules/components/react/components/generic/FileInputMappingEditor.jsx

@ujovlado:
src/scripts/modules/components/react/pages/new-component-form/GoodDataWriterForm.jsx
src/scripts/modules/components/react/pages/new-component-form/DefaultForm.jsx
src/scripts/modules/components/react/pages/new-component-form/AppVendorInfo.jsx
src/scripts/modules/ex-s3/react/components/Advanced.jsx
src/scripts/modules/ex-s3/react/components/Settings.jsx

@natocTo 
src/scripts/modules/ex-s3/react/components/Credentials.jsx
src/scripts/modules/csv-import/react/components/Settings.jsx
src/scripts/modules/data-takeout/Form.jsx
src/scripts/modules/ex-google-analytics-v4/react/components/QueryEditor/ProfileSelector.jsx
src/scripts/modules/ex-mongodb/react/pages/credentials/CredentialsForm.jsx

@ujovlado:
src/scripts/modules/ex-http/react/components/Credentials.jsx
src/scripts/modules/ex-http/react/components/Configuration.jsx
src/scripts/modules/wr-google-drive/react/components/InputTab.jsx
src/scripts/modules/wr-google-drive/react/components/FileTab.jsx
src/scripts/modules/ex-twitter/react/Wizard.jsx

@natocTo 
src/scripts/modules/ex-ftp/react/components/SourcePath.jsx
src/scripts/modules/tde-exporter/react/pages/Destination/TableauServerCredentialsModal.jsx
src/scripts/modules/tde-exporter/react/pages/Table/Table.jsx
src/scripts/modules/ex-google-bigquery/react/Index/ProjectsManagerModal.jsx
src/scripts/modules/wr-aws-s3/react/components/Credentials.jsx

@ujovlado:
src/scripts/react/layout/NewProjectModal.jsx
src/scripts/react/common/CopyVersionModal.jsx
src/scripts/react/common/CsvDelimiterInput.jsx
src/scripts/react/common/SshTunnelRow.jsx
src/scripts/react/common/NonStaticSshTunnelRow.jsx

**Comment by natocTo** [comment]
Okei.

**Comment by natocTo** [comment]
Chceme to přepisovat přímo do Bootstrapu, nebo uděláme nějaké komponenty aby se zachovalo api?

```js
<Input
  type="text"
  value={this.state.data.get('name')}
  autoFocus={true}
  onChange={this.handleChange.bind(this, 'name')}
  placeholder="Name"
  label="Name"
  ref="name"
  labelClassName="col-sm-4"
  wrapperClassName="col-sm-6"
/>
```

Přepsat na něco jako
```js
<TextInput
  value={this.state.data.get('name')}
  autoFocus
  onChange={this.handleChange.bind(this, 'name')}
  placeholder="Name"
  label="Name"
  ref="name"
  labelClassName="col-sm-4"
  wrapperClassName="col-sm-6"
/>
```

Nebo úplně něco jako
```js
<FormGroup>
    <Col sm={3} componentClass={ConrolLabel}>Name</Col>
    <Col sm={9}>
           <FormControl
              type="text"
              value={this.state.data.get('name')}
              autoFocus={true}
              onChange={this.handleChange.bind(this, 'name')}
              placeholder="Name"
           />
    </Col>
</FormGroup>
```

**Comment by natocTo** [comment]
Mě se více líbí ta 2ka, sice více kódu ale zase jasné.

**Comment by ujovlado** [comment]
Siel by som cestou cisteho bootstrapu. Tej “proxy” sa chceme zbavit, nie zaviest nove.

Alebo sa ti to nepozdava?

V ramci .ednotlivych komponent mozu byt ale napr, text inputy obsluzene pomocnou render metodou, ak ich je vela.

**Comment by natocTo** [comment]
Právě se mi to pozdává :) ta 2 byla jako ta druhá nabízená varianta.

**Comment by ujovlado** [comment]
To sme splachli celkom rychlo, idem to pomergovat.

**Comment by ujovlado** [comment]
Este pripravim PR na vyhodenie tych proxy ;)
