### ISSUE TITLE
Display data types in storage

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#3038]
re: https://github.com/keboola/internal/issues/136

We should list relevant metadata in the storage console starting with column data types.

Step 2 will be to allow users to define column data types themselves.

**Comment by natocTo** [comment]
We will be showing some informations here?
![columns](https://user-images.githubusercontent.com/12331181/54435384-a85a4000-4730-11e9-8354-6020dd31c0f4.png)

I can prepare this first step. Which metadata we want to show here? We have basetype, type, nullable, length and some more.

**Comment by natocTo** [comment]
It is bad idea just show all available metadata in popover? Or we want show just few of them? 

![metadata](https://user-images.githubusercontent.com/12331181/54520182-69aeca80-4968-11e9-886b-c0042ea67238.png)

Or there should be only a button which open metadata editor?

**Comment by pivnicek** [comment]
@natocTo ,  I was putting it in an on-click accordian, where there would be markdown for `description`, and select box for `baseType` and text box for length (if baseType supports length).  I'd like it do display the current metadata for these keys with the `provider`, and allow adding values by the user (provider: `user`)

**Comment by pivnicek** [comment]
This is my very beginning of PR https://github.com/keboola/kbc-ui/pull/3102

**Comment by natocTo** [comment]
Ok, thank you for explanation. 
I am working now on UI new prototype but later today I look to your PR.
