### ISSUE TITLE
Orchestrace - notifikace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#306]
Vyhodil jsem se z notifikací a stejně mi přišel email:

![image](https://cloud.githubusercontent.com/assets/1427901/8764813/e87d2ebc-2def-11e5-942c-5e80fdead8c1.png)

**Comment by padak** [comment]
(https://connection.keboola.com/admin/projects/724/orchestrations/104635909/notifications)

**Comment by Halama** [comment]
diky, mrknem na to

**Comment by ErikZigo** [comment]
Fixnul jsem to, to padak doplnovalo ze starych notifikaci.
