### ISSUE TITLE
File uploading is different from the old console

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#3075]
In the old console it used the import service: https://github.com/keboola/storage-api-console/blob/master/app/scripts/controllers/file-upload-controller.coffee#L25

But in the new console it is uploading direct to S3 using file_prepare etc...
https://github.com/keboola/kbc-ui/blob/6cbd2c52cc0dc348298121a93dc8b9c09870639d/src/scripts/modules/components/StorageActionCreators.js#L906

The result is a difference in behaviour as the returned links are different and have different behaviours, redirect vs download.

**Comment by ujovlado** [comment]
It is a "browser thing" - browser decides if download or show file.

And it decides by `Content-Type`. In one case it is `Content-Type: application/octet-stream` and in other `Content-Type: image/png`.

So we need to turn on "detect encoding" somewhere.

**Comment by pivnicek** [comment]
Beautiful
