### ISSUE TITLE
Don't offer linked buckets (read-only) in output mappings

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#3096]
You can't write to linked buckets so they shouldn't be selectable for output mappings.

**Comment by natocTo** [comment]
Where we have such a selects? I am still sometime lost where I should locate something. Thanks :)

**Comment by pivnicek** [comment]
:-)  definitely transformations, but also extractors may use this component too.  it's a shared component.

**Comment by pivnicek** [comment]
`DestinationTableSelector` is what is used in transformations
