### ISSUE TITLE
generické ui konfigurace komponenty

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#310]
Možnost editovat `configurationData` konfigurací přímo v ui.
Komponenty které to podporují a nemají vlastní ui označíme nějakým flagem v Manage Applications.

![image](https://cloud.githubusercontent.com/assets/903531/8776716/8256db7e-2ef3-11e5-8afa-1bb5d12147b2.png)

**Comment by odinuv** [comment]
kdyz vidim :"genericky UI" - bude to nejak souviset s UI pro recepty? imho by melo, protoze to uz je jedno genericky UI a imho docela dobry

**Comment by Halama** [comment]
tohle bude zatim uplny zaklad pro veci co nemaj ui a pouzivaji konfiguracni rozhrani, pak do toho asi pribude nejaka podpora template
