### ISSUE TITLE
Orchestrator tasks: unsorted and missing items

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#3107]
Když chci do orchestrace vložit další orchestraci, tak v popupu na přidání tasku jsou orchestrace neseřazené podle abecedy 

![image](https://user-images.githubusercontent.com/497675/54588605-c4f1c300-4a23-11e9-9f4c-a8df9c6e96ff.png)

a navíc mi tam některé orchestrace úplně chybí, např. https://connection.keboola.com/admin/projects/232/orchestrations/251422387 v tom listu nedokážu najít.

**Comment by natocTo** [comment]
Je tu nachystaný jeden PR který tento modal docela upravuje, nevím zda tam je vše vyřešeno https://github.com/keboola/kbc-ui/pull/2572

Zkusím pak mrknout.

**Comment by natocTo** [comment]
Tak jsem to projel a ještě trochu upravil, ten PR #2572 tam bude mít hledání + to bude sortováno.

Zkoumal jsem navíc ty chybějící orchestrace a ona tam je jedna podmínka, díky které tam není vše. Ale asi to je schválně, proč by to tam jinak bylo. Jde o to že v tom seznamu se ukazují jen takové orchestrace, které nemají nastavený žádný `crontabRecord`. Dává to smysl?

**Comment by ondrejhlavacek** [comment]
aha, to mě nenapadlo, asi jo! :-)

**Comment by natocTo** [comment]
Třeba by bylo lepší je tam mít, ale disabled (plus title s důvodem).
