### ISSUE TITLE
velikost ikonek v sidebaru

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#312]
Zdá se mi že se s nima po updatu kbc-bootstrap něco stalo. Jakoby se od shora dolů zvětšovali :)

![image](https://cloud.githubusercontent.com/assets/903531/8801687/beccba5a-2fbc-11e5-9b32-99613703bddb.png)

**Comment by JakubMatejka** [comment]
omg, nějak se mi rozjel ten font, už jsem to fixnul

**Comment by Halama** [comment]
zajímavej bug :)
