### ISSUE TITLE
Logo Connection

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#313]
Nemělo být takovým tím tučnějším Keboola fontem?
![image](https://cloud.githubusercontent.com/assets/903531/8801710/e7843d1a-2fbc-11e5-833b-58c978bf4ecc.png)

**Comment by JakubMatejka** [comment]
To asi ne, je to celý i s logem v svg, mlžu to akorát zvětšovat n. zmenšovat

**Comment by Halama** [comment]
Aha já celou dobu myslel že to bude tímhle fontem :)
![image](https://cloud.githubusercontent.com/assets/903531/8811380/f4611538-2ff5-11e5-90b0-a8bdb5af46b6.png)

**Comment by Halama** [comment]
Asi jsem si zvykl

**Comment by JakubMatejka** [comment]
;o) Můžem se zeptat Karáska jestli by to nebylo lepší tučně

**Comment by Halama** [comment]
Jestli jsme to vlastně nechtěli mít sjednocené s tím co je v projektu a co je na té uvodní stránce ze seznamem projektů?

**Comment by Halama** [comment]
Nebo prostě :)
![image](https://cloud.githubusercontent.com/assets/903531/8824496/8b0f7e4a-3076-11e5-9919-fcb0a6b49c08.png)

**Comment by JakubMatejka** [comment]
Já bych byl klidně pro. Dejme tam Keboolu a uvidíme jestli s tím někdo bude mít problém. ;o)

**Comment by Halama** [comment]
ok dám jí tam. Musím to první udělat na backendu a pak v ui.
