### ISSUE TITLE
Tooltip not working reliable

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3139]
Koukám že náš common `Tooltip` nefunguje vždy spolehlivě.

Příklad:
```jsx
<Tooltip tooltip="Describe link">
    <ExternalLink href="http://www.example.com">Example</ExternalLink>
</Tooltip>
```

Jde o to že Tooltip potřebuje předat nějaké props do `children`. A když je to komponenta jako `ExternalLink` kde máme jasně definované co se předá, tak to pak nefunguje. 
Workaround fix je jednoduchý.

```jsx
<Tooltip tooltip="Describe link">
    <span>
        <ExternalLink href="http://www.example.com">Example</ExternalLink>
    </span>
</Tooltip>
```

Otázka spíš zda je to dobře je to potřeba to takto udělat. 
Fix by mohl být rovnou v komponentě Tooltip.

```jsx
<OverlayTrigger placement={this.props.placement} overlay={tooltip}>
    <span>
        {this.props.children}
    </span>
</OverlayTrigger>
```

Což ale zas přidá úplně všude span navíc. Kde na hodně místech už je, kdyby bylo nějaké nešťastné stylování může to rozbít i nějaký vzhled.

Teď co je nejlepší varianta, prostě vědět že musím použít kolem span když mám nějakou komponentu typu `ExternalLink` nebo to upravit pro všechny tooltipu najednou. Ale našlo mi to 114 případů což je dost.

Nebo ještě nějaká kontrola ve `Tooltip` komponentě, co je zač ten `children` a podle toho se rozhodnout zda kolem toho hodím span nebo ne. 

Nebo možná přidat props kde dám vědět, že posílám nějakou "vlastní" komponentu a to by dalo signál to obalit spanem, to se mi možné líbí nejvíc. Protože to jako default bude fungovat stejně jako doposud a jen nově budu mít možnost dát vědět.

**Comment by ujovlado** [comment]
Kukal som to. Povolil som nakoniec vsetky props v ExternalLink, je tam na to PR.
