### ISSUE TITLE
Nový seznam komponent

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#314]
Přijde mi ten padding mezi konfiguracemi zbytečně velký.

![image](https://cloud.githubusercontent.com/assets/903531/8801797/631276cc-2fbd-11e5-8af6-d7c42a14d52e.png)

Takhle to vypadá když ho zmenším na 6px. 

![image](https://cloud.githubusercontent.com/assets/903531/8801818/7e96c574-2fbd-11e5-853c-c19f47ce10f7.png)

Není to lepší?

**Comment by Halama** [comment]
Ten samotnej font na jméno konfigurace mi taky přijde hrozně velkejch asi bych ho zmenšil třeba na takovou velikost jako je v seznamu orchestrací.

**Comment by Halama** [comment]
Není matoucí že tady není klikací celý řádek a všude jinde jo? (transformace, orchestrace, query extraktorů, data sety writeru, ...

**Comment by JakubMatejka** [comment]
Snažím se upravit aby řádek byl klikací, ale pořád nějak bojuju s odsazováním v CoffeeScriptu. ;o) Podíval by ses prosím na to a řekl mi co je blbě? - https://github.com/keboola/kbc-ui/commit/0db6c03f1440651c4fe34d25bf7d8e0a6f6c4db9 Mělo by to být takto: `div.table > a.tr > span.td`

**Comment by Halama** [comment]
@JakubMatejka asi nemas checkoutnutou poslení verzi protože jsem to dnes předělal do JSX

**Comment by Halama** [comment]
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/pages/ConfigurationRow.jsx

**Comment by Halama** [comment]
sorry, ted jsem si vsimnul ze jak jsem to opisoval do jsx tak jsem tam pak zapomnel smazat ten puvodni kod. Takze to co si editoval se uz vubec nespoustelo :) https://github.com/keboola/kbc-ui/commit/2e31f33ec57f34f8ffa290ae52f9bbc3cb64320e

**Comment by JakubMatejka** [comment]
Aha, a já si říkal že se mi nemění markup a webserver nehlásí žádný chyby. ;o) Ještě bych potřeboval do toho odkazu dostat `class="tr"` ale `<ConfigurationLink componentId={this.props.componentId} configId={this.props.config.get('id')} className="tr">` nefunguje

**Comment by Halama** [comment]
Poslal jsem do master upravu kdy ten className pro ten link zacne fungovat https://github.com/keboola/kbc-ui/commit/435a063cb2de111d6648e66b274fc01071ddb504

**Comment by JakubMatejka** [comment]
Ok, tak je to hotový v tý branchi. Mám to rebasnout do masteru?

**Comment by Halama** [comment]
diky, mergnu to

**Comment by Halama** [comment]
nasazeno
