### ISSUE TITLE
Storage Writer špatně uložil ID remote projektu

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#3146]
Tady https://connection.keboola.com/admin/projects/258/writers/keboola.wr-storage/479465006 je link do projektu kam Storage writer zapisuje. Ten link vede na https://connection.keboola.com/admin/projects/565/storage#/buckets/in.c-raw_data zatímco správná cesta je https://connection.keboola.com/admin/projects/5657/storage-explorer/in.c-raw_data - vypadla tam `7` z čísla projektu.

**Comment by odinuv** [comment]
ulozeny je spravne, backend vraci `{"projectId":5657,"projectName":"Keboola Internal - KBC Projects Stats","bucket":"in.c-raw_data"}`

**Comment by odinuv** [comment]
krome toho by tam teda melo byt taky `storage explorer` misto `storage`
