### ISSUE TITLE
Writer - klikací řádek celé konfigurace

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#315]
Mohl by být u Writerů klikací celý řádek, abych se dostal do dané konfigurace? Místo toho, abych musel klikat pouze přesně na název.
![h1 - writers 2015-07-22 13-09-39](https://cloud.githubusercontent.com/assets/12933713/8824122/27d346de-3073-11e5-847d-3fe22764f177.jpg)

**Comment by Halama** [comment]
Zrovna se builduje, tak za 3 minuty to bude nasazené

**Comment by Halama** [comment]
Je to tam, předtím refreshi okno v browseru
