### ISSUE TITLE
Very long (reasonable though) description breaks transformation page

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/kbc-ui#3165]
When transformation has description (linked in slack) https://keboola.slack.com/archives/C02J3DKH3/p1554210685014900 the transformations and bucket overview pages won't load. 

Warning: Make sure you have the transformation detail opened in other tab or something so that you don't have to change the decription back via API.

**Comment by tomasfejfar** [comment]
Please ping back to https://keboola.zendesk.com/agent/tickets/10168 when solved.

**Comment by ujovlado** [comment]
Bol to bug v remove-markdown, akonahle tam bolo viac medzier, stranse dlho to processovalo.
