### ISSUE TITLE
Duplikace output mappingu po editaci.

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#317]
Sorry, jeslti jste to už vyřešili, ale neimplementovali. Ale jak mluvil MH o nasazení do produkce, radši hlásim.

Editoval jsem Output mapping TR (https://connection.keboola.com/admin/projects/772/transformations/bucket/sys.c-tr-transformers1/transformation/pocasi1) a když jsem ho dal uložit, objevil se nový, místo přespání starého.

![transformation pocasi1 2015-07-24 08-51-27](https://cloud.githubusercontent.com/assets/12933713/8869212/90e8297c-31e1-11e5-9144-40a3f57996db.jpg)

**Comment by Matejkys** [comment]
Když jsem chtěl tu původní smazat, klikl jsem na delete a místo ní mi to smazalo jiný mapping (refresh okna nic nedělá).

![transformation pocasi1 2015-07-24 08-55-39](https://cloud.githubusercontent.com/assets/12933713/8869273/1a5c758c-31e2-11e5-9e37-6ae58cd600b8.jpg)

**Comment by Matejkys** [comment]
A děje se to i ve starym UI (tam teda alespoň jdou ty mappingy smazat).

**Comment by Matejkys** [comment]
Teď se stalo, že jsem editoval jeden input mapping, dal jsem save a přepsalo mi to jiný, který tam byl.
![transformation companies 2015-07-28 13-10-35](https://cloud.githubusercontent.com/assets/12933713/8930017/48289b58-352a-11e5-8f7f-fa665e236286.jpg)

**Comment by ondrejhlavacek** [comment]
Díky moc za report, bylo to způsobený řazením input a output mappingů podle abecedy. Necháme je řazený tak, jak byly přidávaný.
