### ISSUE TITLE
project limits

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3174]
ted budeme nekolika projektum nastavovat limity:
`sandbox.dockerMemoryReservationMBytes`
`sandbox.dockerMemoryLimitMBytes`

bylo by myslim fajn, aby byly videt na strance limitu projektu, klidne jen tak vypsane bez moznosti editace, otazka je jestli tak nezobrazit treba uplne vsechny limity?

**Comment by natocTo** [comment]
@odinuv mohl by si mi taky nějaký limit nastavit pro 5194 pro test?

V limits dělám něco poprvé tak zkoumám jak to funguje a jak se to vypisuje vůbec. Nevím zda ty data čtu se správného místa atd, tak by bylo fajtn to mít nastavení.

**Comment by odinuv** [comment]
si je nastav sam :) - to se divim, ze jsi nepotreboval u zendesku :) https://keboolamanagementapi.docs.apiary.io/#reference/projects/project-limits/set-project-limits ocekava to manage token, kterej si vygenerujes v account settings https://connection.keboola.com/admin/account/access-tokens

**Comment by natocTo** [comment]
To jsem si vystačil s tím co jde nastavit přímo v projektu. Díky

**Comment by odinuv** [comment]
aha jo, no to tam pak ale clovek musi lezt

**Comment by natocTo** [comment]
Jen pro doplnění, smazat to jde? Na to tam nevidím endpoint.

**Comment by odinuv** [comment]
myslim, ze nejde :)
