### ISSUE TITLE
strange loading of events

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3175]
the event `Exported table out.c-adaptive.out to CSV` is never shown until the page is reloaded

http://youtu.be/7RdhUCm6bUE?hd=1

configuration https://connection.keboola.com/admin/projects/901/writers/keboola.wr-db-snowflake/493465505

**Comment by natocTo** [comment]
Fixed #3242

**Comment by ujovlado** [comment]
Toto sme ale nefixli, nie? :)

**Comment by natocTo** [comment]
To já myslel že jo, nebo tamto nakonec nepomohlo? Já když si ten PR testoval tak jsme to tam vždy viděl pak.
