### ISSUE TITLE
Disabled project

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#318]
Pokud vlezu v novem UI na disablovany projekt (znám URL - proklik z emailu), tak mě to hodí na seznam projektů a nic to nenapíše. Staré UI udělá to samé, ale napíše to 
![image](https://cloud.githubusercontent.com/assets/1427901/8893020/3f5c0d24-337d-11e5-8de5-62ed7d5c2e46.png)

**Comment by Halama** [comment]
fixnuto
