### ISSUE TITLE
Project Graph Prilepek

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3183]
navazuje na https://github.com/keboola/kbc-ui/issues/3069

Ke grafu je prilepeny zobrazeni "stavu" projektu. Na strance organizace (prehled projektu) je k tomu  API call https://github.com/keboola/graph/blob/master/apiary.apib#L67 - ktery poskytuje reliability score a pocet issues. Score by se melo zobrazovat jako nejakej "teplomer" - ma to takovehle rozlozeni https://github.com/keboola/predictive-support/issues/14#issuecomment-477918477
cili:

-  > 0.9 - perfect
- 0.7 - 0.9 - good
- 0.5 - 0.7 - average
- < 0.5 - poor

pocet issues je nejakej "badge", detail je videt az uvnitr konkretniho projektu

Uvnitr konkretniho projektu se pak daji zobrazit detaily, na ktere je tento API call https://github.com/keboola/graph/blob/master/apiary.apib#L87
kterej vraci pole polozek - napr.:

```
[
    {
        "time": "2019-04-04 04:29:14",
        "reason": "deprecated-components",
        "data": [
            "rcp-next-event"
        ]
    },
    {
        "time": "2019-04-04 04:29:14",
        "reason": "inactive-tokens",
        "data": [
            "47628",
            "31493"
        ]
    },
    {
        "time": "2019-04-04 04:29:14",
        "reason": "outdated-transformations",
        "data": [
            {
                "configuration_id": "405524817",
                "row_id": "457815292"
            },
            {
                "configuration_id": "405524817",
                "row_id": "468355427"
            }
        ]
    },
    {
        "time": "2019-04-04 04:29:14",
        "reason": "orchestrations-without-tasks",
        "data": [
            "488483222"
        ]
    }
]
```

momentalne implementovane `reason` jsou:

- orchestrations-without-notifications
- orchestrations-without-tasks
- deprecated-components
- outdated-transformations
- inactive-tokens
- dead-project
- failed-orchestrations
- failed-jobs
- configuration-issue

backend je hotovej, fantazii se meze nekladou :)

major issue https://github.com/keboola/internal/issues/13

**Comment by JakubMatejka** [comment]
Jak to vypadá tady? (je to poslední blocker pro https://github.com/keboola/internal/issues/13 ;o)

**Comment by natocTo** [comment]
Toto je nasazené. První verze. Je to součástí toho "overview". Asi se to může zavřít.

**Comment by JakubMatejka** [comment]
Wow, už to vidím 👍

**Comment by natocTo** [comment]
Jde to tento PR: https://github.com/keboola/kbc-ui/pull/3192
Jen doplním aby to tu bylo.
