### ISSUE TITLE
editace input mappingu má miliony bugů - nepoužitelné

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#321]
Cus, otestujte si input mapping, ale děje se to, že když např. něco mažu z in mappingu, ve skutečnosti se nesmaže nic nebo se smaže něco úplně jinýho. Ještě horší se to editací. Myslím, že něco edituju a ve skutečnosti se updatne uplně jinnáý vstup.:-(((

**Comment by padak** [comment]
nemůžou za to ty Najlošovi cache?

**Comment by ondrejhlavacek** [comment]
Nemůžou, bude to tím, jak se to celý předělávalo z toho inline editu, ale mrknu na to!

**Comment by ondrejhlavacek** [comment]
Díky moc za report, bylo to způsobený řazením input a output mappingů podle abecedy. Necháme je řazený tak, jak byly přidávaný.
