### ISSUE TITLE
Password validation in configuration schema on iPhone Safari does not work

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#3227]
Na Androidu to v Chromu funguje ok, ale podle videa jim to zřejmě fakt nejde. Viz. https://keboola.zendesk.com/agent/tickets/10258 (jde o https://connection.keboola.com/admin/projects/[ID]/extractors/kds-team.ex-reviewtrackers)

**Comment by ujovlado** [comment]
Je to problem komponenty.

S skratke:

- mali tam configuration schema, kde bolo `#password`, toto vyplnili, ulozili
- potom zmenili configuration schema, kde je `password` (co je fail a nechapem to)
- nasledne, ked to chces ulozit, uprednostnime sifrovanu hodnotu pred nesifrovanou, a tak to zmizne

Ta komponenta imho nemala byt publikovana.
