### ISSUE TITLE
Transformation queries editor behaves weirdly on saving query with error

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#3229]
Když uložím query s chybou, např. `CREATE TABLE users1 (id INT, name VARCHAR(128"));` (je tam navíc ta uvozovka), editor ji smaže a všechno před ní, zůstane tam jen `));`

**Comment by natocTo** [comment]
Zkouším nějakou hloupou validaci po rozdělení stringu na jednoduché query, ale vůbec se mi to nelíbí. Třeba zrovna tento příklad co píšeš by to zachytilo ale jinak by to nebylo vůbec spolehlivé. 

Podle mě toto bude oříšek. Dnes nad tím chci ještě chvilku sedět, ale ani jsem nenašel nějakou knihovnu co by s tou validací pomohla, tak to bude asi docela oříšek.
