### ISSUE TITLE
detail prubehu transformace prehraje zvuk (uspech/neuspech) pouze, kdyz dostane tab focus

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#323]
pokud je tab schovany, zvuk se neprehraje, resp. se prehraje az kdyz tab dostane focus

**Comment by Halama** [comment]
Ahoj,
teď to zkouším a zařve mi to i když jsem mezitím v jíném tabu.
Jaký používáš browser?
díky
M

**Comment by radovanjirka** [comment]
Safari


RJ
---
Radovan Jirka
radovan.jirka@bizztreat.com
@xjirkar
+420 608 052 066

On 03 Aug 2015, at 16:45, Martin Halamíček <notifications@github.com> wrote:

Ahoj,
teď to zkouším a zařve mi to i když jsem mezitím v jíném tabu.
Jaký používáš browser?
díky
M

—
Reply to this email directly or view it on GitHub
<https://github.com/keboola/kbc-ui/issues/323#issuecomment-127265502>.

**Comment by Halama** [comment]
jo tak to potvrzuju, v Safari mi to dela taky. Bohuzel nevim jestli se to podari fixnout, ale zkusim to. 
Jinak v Chrome to funguje.

**Comment by Halama** [comment]
tak bohuzel  v Safari se to zprovoznit nepodarilo, workaround je pouzit Chrome. Monza zkusime tam zaintegrovat primo desktop notifikace jako ma treba Trello
