### ISSUE TITLE
project limits

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3236]
followup to https://github.com/keboola/kbc-ui/issues/3174

new limits added to a bunch of projects:

runner.keboola.r-transformation.memoryLimitMBs
runner.keboola.python-transformation.memoryLimitMBs
sandbox.dockerInstanceSizeGroupLarge (values 0,1)

**Comment by ujovlado** [comment]
@natocTo este to "extra large sandbox" nejako nefici ... neposiela to `limitValue`

to mozes normalne testnut aj na localhoste a kuknut co je vo Form Data.

**Comment by ujovlado** [comment]
![Screenshot 2019-04-17 at 17 58 31](https://user-images.githubusercontent.com/419849/56302605-6f035e80-613a-11e9-8e72-bc7381736368.png)

je tam len toto + xsrf

**Comment by natocTo** [comment]
Ještě dnes mrknu.

**Comment by natocTo** [comment]
Už vidím, chybí tam name u checkboxu. Jsem na tel tak to dystak opravím doma pak.

Většinou name nepoužívané ale tu to je řešeno koukám přes form action. To mě nenapadlo.

**Comment by ujovlado** [comment]
Mozem to fixnut kludne.
