### ISSUE TITLE
User data types not available in transformation IM for manually created tables (no component involved)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3247]
Este nez mergnem ten refaktoring, vsimol som si takyto bug.

![Screenshot 2019-04-23 at 17 40 06](https://user-images.githubusercontent.com/419849/56595396-dd3e9a00-65ee-11e9-9ac4-46e2a5e4b54e.png)

![Screenshot 2019-04-23 at 17 39 37](https://user-images.githubusercontent.com/419849/56595395-dca60380-65ee-11e9-8485-dbee2d9aa829.png)

**Comment by natocTo** [comment]
Mrknu.

**Comment by ujovlado** [comment]
To sa muselo pokazit v najakom PR po tom hlavnom, kuknem bisect.

**Comment by ujovlado** [comment]
Alebo to nefungovalo :)

**Comment by natocTo** [comment]
To já tam vidím že se to upravilo:

![columns](https://user-images.githubusercontent.com/12331181/56596698-5212d380-65f1-11e9-9dc5-9ba8b2fa48cb.png)
![mapping](https://user-images.githubusercontent.com/12331181/56596701-53440080-65f1-11e9-930e-cd31bbdef911.png)

Vidím jinou věc. Ve storage můžu nastavovat velikost Integeru, v IM nemůžu a ani nevidím tu nastavenou.

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/blob/389e1d573241f6146de530b26d69a58d7e626c2a/src/scripts/modules/components/stores/MetadataStore.js#L122

takze to postihuje tabulky ktore neboli updatnute ziadnou komponentou ... t.j. manualne nahrate alebo tak
