### ISSUE TITLE
Scripts sometimes disappear in transformation

### ISSUE THREAD

**Issue by toshi2135** [keboola/kbc-ui#3248]
Hi team,

We are experiencing an issue on UI that sometimes the script does not appear fully in the transformation like this:

![](https://lh3.googleusercontent.com/-CrcVxrLksUw/XL_cqVfV8cI/AAAAAAAAANQ/bL1xmDXXLgcxKjNI03_cjCGX4j8i0DWGgCK8BGAs/s0/Capture.PNG)

When we click into the script, it appears again. Could you please take a look at this issue?
Thank you in advance.

P/s: other pictures for references:
Before:
![image](https://user-images.githubusercontent.com/26113921/56632034-1542ed00-6682-11e9-8ec7-49536c854d8a.png)
After:
![image](https://user-images.githubusercontent.com/26113921/56632047-2ab81700-6682-11e9-9fc7-dd6216d5911c.png)

Best regards,

**Comment by natocTo** [comment]
Thank you for reporting this. I already work on a fix.

**Comment by toshi2135** [comment]
Hi team,

I checked today and still have this issue. Could you please check it again?
Before
![image](https://user-images.githubusercontent.com/26113921/58866367-a88c2b00-86e2-11e9-86d9-3a1ef4dee8cb.png)
After
![image](https://user-images.githubusercontent.com/26113921/58866412-be99eb80-86e2-11e9-96d0-678346383dcd.png)

Thank you in advance.

Best regards,

**Comment by ujovlado** [comment]
Hi @toshi2135, we need to check it in the affected project, I'll let you know via our support channel.
