### ISSUE TITLE
Use Roboto font

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3250]
Ked ho pridame (connection), mozeme ho pouzit.

Asi to bude hodne o uprave v indigo-ui.

**Comment by ujovlado** [comment]
Tuna to bude asi len o pridani toho fontu do index.html (ako v connection)

**Comment by ujovlado** [comment]
Este je tam vlastne aj Guide mode, kde je Gotham. Takze bude treba checknut aj to. Ak to tam zapasuje, mozeme to zamenit aj tam.

**Comment by natocTo** [comment]
Myslíš jako zkusit jak to bude vypadat pokud Gotham nahradím Robotem?

**Comment by ujovlado** [comment]
Ano, on tam bol tusim len kvoli nejaky nadpisom a pod. (Guide.less)

**Comment by natocTo** [comment]
Vložím sem jak to vypadá teď, pak sem vložím to samé když to upravím.

Současný vzhled:
![overview](https://user-images.githubusercontent.com/12331181/56656438-c901a800-6695-11e9-983f-442fd139b705.png)
![modal](https://user-images.githubusercontent.com/12331181/56656435-c7d07b00-6695-11e9-8680-9a49aaf0c972.png)
![step](https://user-images.githubusercontent.com/12331181/56656429-c4d58a80-6695-11e9-957b-a85ad57797f2.png)

**Comment by natocTo** [comment]
Takto to vypadá s roboto. Občas tam byl `font-weight: 300` tak jsem místo toho dal 400. A zase kde bylo 500 jsem dal 700. Aby ty poměry byly jakž takž stejné.

![roboto-overview](https://user-images.githubusercontent.com/12331181/56657177-aec8c980-6697-11e9-99f7-7853bbcd0dae.png)
![roboto-modal](https://user-images.githubusercontent.com/12331181/56657180-b0928d00-6697-11e9-8056-df41c6ddbcf8.png)
![roboot-step](https://user-images.githubusercontent.com/12331181/56657182-b1c3ba00-6697-11e9-8811-21899ce08eba.png)

Pokud to je takto OK tak to pošlu.

**Comment by ujovlado** [comment]
Jo, cajk.
