### ISSUE TITLE
Transformation sandbox job - show sandbox credentials

### ISSUE THREAD

**Issue by radovanjirka** [keboola/kbc-ui#326]
https://www.evernote.com/l/AEo0JmjiW5lDoYD9hshTjZIHoatorQXeDBs

**Comment by ondrejhlavacek** [comment]
Ty credentials jsou vidět před vytvořením toho jobu. V jobu nemáme žádnou možnost zjistit, jestli už nejsou náhodou vytvořený nový nebo jestli jsou relevantní k tomu jobu.

![screen shot 2015-07-30 at 14 11 36](https://cloud.githubusercontent.com/assets/497675/8995220/f2592a66-36c4-11e5-9db7-e734a26d4794.png)

**Comment by radovanjirka** [comment]
Z hlediska UX je to ale neprijemny, protoze ty credentials potrebujes, az se sb vytvori  a ne na zacatku, kdy ti takhle "probliknou" a pak ses hned redirectovanej na detail toho jobu...

**Comment by Halama** [comment]
souhlasim, jeste se na to podivame

**Comment by ondrejhlavacek** [comment]
@radovanjirka Tomu rozumím. Bohužel nemáme spojený credentials nebo obsah databáze s konkrétním jobem, jak bys tohle řešil z hlediska UX? Příklad: divám se na nějakej job, u kterýho teda mám zobrazený sandbox credentials. Jenže na backendu ani na frontendu nevíme, jestli v tý databázi je výsledek toho sandbox jobu (mohl bejt přepsanej nějakým jiným jobem), jestli ten sandbox je vůbec platnej. Časoprostorový line jobů a sandbox credentials jsou úplně nezávislý a nepropojený, mně to tam vytváří spoustu otazníků. Já bych čekal, že když se mi u sandbox jobu zobrazej credentials, tak tam budu mít výsledek toho jobu.

**Comment by radovanjirka** [comment]
stary UI to umelo… ten eventlog toho jobu byl ve stejnym okne…

RJ
---
Radovan Jirka
radovan.jirka@bizztreat.com
@xjirkar
+420 608 052 066

**Comment by Halama** [comment]
Jeste jsem se o tom bavil s TT a dost si na to stezuji, na Datagirls na tom prej vsichni dost pohorely :)

Co to teda udelat radsi tak jak to byvalo? Das create sandbox, uvidis modal kde se objevi credentials. Kdyz kliknes na run zustane otevreny a objevi se info o progresu (treba i eventy) a link na job. V tuhle chvili muzes pockat az to dobehne nebo ten modal zavrit a jit uz treba do sandboxu.

V budoucnu bych rad aby se joby ktere clovek nahodi shodily do nejakeho traye kde by si videl co si spustil a v jakem to je stavu. 

cc @tomastrnka

**Comment by ondrejhlavacek** [comment]
A jde jen o sandbox, nebo transformace nebo všechny joby obecně?

2015-10-21 18:09 GMT+08:00 Martin Halamíček <notifications@github.com>:

> Jeste jsem se o tom bavil s TT a dost si na to stezuji, na Datagirls na
> tom prej vsichni dost pohorely :)
>
> Co to teda udelat radsi tak jak to byvalo? Das create sandbox, uvidis
> modal kde se objevi credentials. Kdyz kliknes na run zustane otevreny a
> objevi se info o progresu (treba i eventy) a link na job. V tuhle chvili
> muzes pockat az to dobehne nebo ten modal zavrit a jit uz treba do sandboxu.
>
> V budoucnu bych rad aby se joby ktere clovek nahodi shodily do nejakeho
> traye kde by si videl co si spustil a v jakem to je stavu.
>
> cc @tomastrnka <https://github.com/tomastrnka>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/326#issuecomment-149845419>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by Halama** [comment]
podle mě jenom o sandbox. Jinde takováhle situace imho není.

**Comment by tomastrnka** [comment]
jj, jen sandbox

**Comment by ondrejhlavacek** [comment]
OK! Mám si to zapsat do trella (mám ho teď docela plný) nebo to mám nechat
tu?

On Wed, Oct 21, 2015 at 7:44 PM, tomastrnka <notifications@github.com>
wrote:

> jj, jen sandbox
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/326#issuecomment-149863214>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by Halama** [comment]
vemu si to

**Comment by Halama** [comment]
tak za 4 minuty az dobehne tohle https://travis-ci.org/keboola/kbc-ui/builds/86630932 to bude v produkci. Pak prosim reloadnete okno a dejte vedet jestli to je ok.

**Comment by padak** [comment]
když to doběhne, mělo by imho tlačítko Create bejt Close - teď jsem to nevědomky pustil znovu

![image](https://cloud.githubusercontent.com/assets/1427901/10670768/ff628586-789b-11e5-995a-e594f04dfb73.png)

**Comment by padak** [comment]
nic se na tom nezměnilo - doběhne transformace, svítí tam "Create" tlačítko a to ji pustí znovu.

**Comment by tomastrnka** [comment]
Super připomínka, nicméně mega pochavala Halamovi, je to parádní.
On Oct 22, 2015 18:05, Petr Simecek <notifications@github.com> wrote:Reopened #326.

**Comment by Halama** [comment]
tohle jsem fixoval, zaviram. Tlacitko tam zustava, meni se text.
