### ISSUE TITLE
Tune "auth" layout

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3263]
Pokracovanie k #3201 

Tak uz je deploynuty ten layout connection. Je mozne si kuknut ako sa to cca chova:

https://connection.keboola.com/admin/auth/login/?layout=new-ui

Popisem par veci, ktore by sme tam mohli doladit:

- ta "nativna validacia" vyzera trosku divne -  napr. Chrome:

![Screenshot 2019-04-27 at 22 19 52](https://user-images.githubusercontent.com/419849/56854664-9926fe80-693a-11e9-8594-fb94f44ccb52.png)

- potom tam je situacia, ked uz mam nieco vyplnene ale nie je to validne:

![Screenshot 2019-04-27 at 22 20 54](https://user-images.githubusercontent.com/419849/56854681-bd82db00-693a-11e9-9d74-323211099ae8.png)

  - 1. problem je ten label a hodnota ktora tam ostala (to bude asi easy)
  - 2. je novy, zapol som tam hlasky k jendotlivym fieldom (povodne bol nejaky sumar hore, ktory nic nehovoril) ... oni by mali podla figmy byt cervenym a hore ... ostylovat ich moze ale ak maju byt hore asi to bude chciet este poladit v connection

- region selector pls upravme tak, aby sa vybratim aktivneho regionu nespravil redirect - t.j. nech sa nerobi US -> US

- no a ostava este doriesit tu pravu stranu, hod tam ten obrazok ako background, nech to nie je prazdne. ale nedavajme tam ten text ohladom noveho dashboardu (lebo to nie je pravda)

Potom napis, ak by tam chodili z toho backendu blbosti, mozeme to pripadne poladit. Alebo sa kukni pre lepsiu orientaciu kludne v connection.

**Comment by Halama** [comment]
To že ten modrý pruh nepokračuje dolu je záměr?
![image](https://user-images.githubusercontent.com/903531/56860656-52b4bc80-6999-11e9-9409-42bf9b53baff.png)

**Comment by natocTo** [comment]
Není, v jakém prohlížeči to máš prosím?

**Comment by natocTo** [comment]
@ujovlado ten error stav jsem dělal podle Figmy 
- error je místo Labelu (to jsem počítal že bude vždy právě jeden error když to bylo tam)
- s tím že input má další třídu "has-error" aby se aplikovalo CSS pro ten label

Celý error input vidíš v KBC-UI zakomentovaný, jsem to tam dával na ukázku všechno co bylo hotové.
Takto to nepůjde řešit?

**Comment by Halama** [comment]
`Version 74.0.3729.108 (Official Build) (64-bit)`. Stačí si zmenšit okno tak aby se objevil vertikální scrollbar a pak sescrollovat dolů a objeví se tam ta šedá plocha.

**Comment by natocTo** [comment]
Jo máš pravdu. To ani nemusím testovat a vím že to tak bude. Upravím díky.

**Comment by ujovlado** [comment]
Ok, skusim novalidate a pozriem sa  na tie errory teda - snad to bude ok.

Ten obrazok praveze chcem ako background, tom mi pride fajn. Ci nechces to tak?

Region selector funguje ok, akurat ak som v US a vyberem US, je blbost robit redirect.

**Comment by natocTo** [comment]
Jasný, už ten select chápu, upravím to.

No spíš jak to chceš ty, já jen psal důvod proč bych preferoval obrázek. Protože pokud se tam postupně bude ten text vracet, asi by se to zpět předělávalo na obrázek, aby to bylo hezky pod sebou (obrázek + pod ním text). Ale klidně to upravím pokud myslíš že background lepší.

**Comment by ujovlado** [comment]
Jaj, jasne, ked to dame ako bg, bude horsia praca s textom. Ale mohlo by to byt pozadie divu, ktory ma presnu vysku.

Moja motivacia za tym bola, ze by sme nemuseli ziskavat na backende tu cestu = menej zmien.

Tak este to nechaj teda, pozrem to aj tam.
