### ISSUE TITLE
New UI, auth-layout, placeholders

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3271]
Nesedi mi tam jedna vec. Nikde nemame pouzite placeholders (netvrdim, ze mi chybaju), a tak sa potom stane, ze sa ten formular pri nejakom error stane vcelku neprehladny.

Dovodom je to, ze sa label zameni za error.

Priklad: Vytvaram si account, vyplnil som zly email, prazdne meno a ok hesla (tie hesla sa potom resetli, lebo cely form nie je valid)

![Screenshot_2019-04-30_23-41-44](https://user-images.githubusercontent.com/419849/56995257-8e21d780-6ba1-11e9-87a2-9c3c0d8ec833.png)

**Comment by ujovlado** [comment]
Prvy field ma vcelku ok hlasku, tam sa este dovtipim, ze sa jednalo o email. Potom je to ale uz horsie s menom.

Nemali by sme predsalen tie errory zobrazovat pod jednotlivymi fieldami a nechat tam labels?

**Comment by natocTo** [comment]
Uvidíme co navrhne Kari no. Je pravda že to druhé je složité.
Asi buď label, nebo upravit chybové hlášky, aby i pro ten "obyč" povinné položky byl doplněn název inputu, jakože "Input {inputName} is required and can´t be empty".

**Comment by ujovlado** [comment]
Napada mi, ci by sme tam label nenechali a error hlasku dali pod input.

Momentalne som to v connection upravil tak, ze vzdy ne zobrazena len jedna hlaska, cize by to nalo byt cajk.

**Comment by ujovlado** [comment]
Da sa to kuknnut napr. tu:
https://connection-testing.us-east-1.keboola.com/admin/auth/login?layout=new-ui

Nic nevyplnim len dam submit:

![Screenshot 2019-05-02 at 12 55 56](https://user-images.githubusercontent.com/419849/57071086-a563e080-6cd9-11e9-90f3-cb6260b33775.png)

Asi by to vyriesili placeholdery, no aj tak len ciastocne, pretoze, ked tam nieco vyplnim, placeholder uz nevidno a stava sa to opat nejasne. Takze by som tam rad nechal tie labels.

**Comment by karimartin** [comment]
Koukam na to a spis bych se zeptal jestli to neni jen o wordingu + zachovat placeholders, ktere usera navedou k tomu, aby jeste lepe pochopil co tam ma dat.

![Screenshot 2019-05-02 at 14 32 47](https://user-images.githubusercontent.com/720530/57075536-558c1600-6ce7-11e9-8d45-337533fa086a.png)

**Comment by ujovlado** [comment]
Jo, tie placeholdery tomu pomozu, ked nie je vyplnene nic. Skor ma teda trapi ta druha cast, t.j. ked uz mam nieco vyplnene.

Tych hlasok som sa moc nechcel chytat, ale tak uvidime, pripadne ich mozeme malicko poladit.

Zatial teda vratim s5 placeholders, diky.

**Comment by natocTo** [comment]
Tady asi ani nemusím dodělavat do kbc-ui ne?
Tam v tom "testu" mám i error stav pouze zakomentovaný.
Jinak to bude tak, že pokud mám value nebo error, zobrazím tam placeholdery. 
Pokud nemám errory tak to je první načtení tak nezobrazím.
