### ISSUE TITLE
New UI, project-select layout init

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3272]
Uz je pripraveny aj project-select layout (vid. Figma), mozeme to pripravit. V connection to bude vyuzivat jedna stranka - zoznam projektov po prihlaseni.

---

### Aktualny stav

Project list stranke je tiez server render a potom samostatne React okomponenty. To musim zatial zachovat. Najlepsie to vidno ked si otvoris v produkcii React devtools a tam vidis, ako to je spravene.

![Screenshot 2019-05-06 at 11 51 59](https://user-images.githubusercontent.com/419849/57218349-5f6a8d80-6ff5-11e9-93fa-823f3d6ed3bf.png)

Niekedy to bolo tak, ze sa zoznam projektov (z totoznym markupom) renderoval aj na backende, no potom som to vyhodil a je tam len loader/spinner.

Su tam dve komponenty. User a List.

Tieto komponenty sa nasledne vyuzivaju aj v lavom menu (uz ked si v projekte). A potom este v admin casti (hore v menu, ale len to user menu).

Cele je to trosku ohackovane pomocou CSS a je problematicke tam cokolvek zmenit.

### New UI

Chcel by som aby sme na project-list pripravili tieto 2 komponenty nanovo. Mozu mat zachovane props, no mali by to byt 2 nove komponenty.

Aby sa dali potom pouzit na viac miestach, mozeme tam mat pripravenu nejaku prop `placement`, kde by bolo `projects-list`, `project-detail` a pod. A podla toho by to dostalo prislusnu css class. 

Vo vysledku tam teda budu 3 (tie 2 nove + region selector).

Este rozmyslam nad dummy contentom, ktory tam vyrenderujeme predtym. To sa spytam Kariho.

**Comment by natocTo** [comment]
Asi bych začal rovnou s tímto, ať máme další část nové UI. Tak mi to tu klidně pak popiš. Zatím ještě mrknu na nějaké issues.

**Comment by ujovlado** [comment]
Za chvilku sa na to vrhnem, ok.

**Comment by ujovlado** [comment]
Este poslem jeden PR predtym, co som spominal, mam to tu WIP

**Comment by ujovlado** [comment]
Updatol som popis. Asi by sa to mohlo spravit do novej dev page (projects-list-new). Kludne pis, ak je nieco nejasne.

**Comment by natocTo** [comment]
Díky, mrknu po obědu hned.

**Comment by natocTo** [comment]
Ok, já si udělám nějaký základ ala Login a (start-login) a pak to tam k tomu připravím.

**Comment by natocTo** [comment]
Ještě koukám na původní komponentu a má tam třeba "new project" tlačítko. Což tady asi nebude to je v poho, jen zmiňuji. Pak tam je ale řešené pokud je má project flag `isDisabled`, tak nevím zda to bude i tu případně jak graficky. To samé u organizace tam může být `hasAccess` jako false tak co pak.

Jinak hledání se asi hledá přímo v názvu projektu jen že.

**Comment by natocTo** [comment]
Pak ještě, co když tam těch projektů bude hodně? Bude tam nějaký scrollbar nebo to prostě půjde dál a dál ten seznam?

**Comment by ujovlado** [comment]
> Ještě koukám na původní komponentu a má tam třeba "new project" tlačítko. Což tady asi nebude to je v poho, jen zmiňuji.

to je ok, zatial ho tam nedavaj ... lebo ak ho tam dame, musel by sa myslim poladit aj design modalov, do coho sa v tejto casti asi pustat nechcem

> Pak tam je ale řešené pokud je má project flag isDisabled, tak nevím zda to bude i tu případně jak graficky. To samé u organizace tam může být hasAccess jako false tak co pak.

toto kludne ako nejaky text-muted alebo tak, ved uvaz.

> Pak ještě, co když tam těch projektů bude hodně? Bude tam nějaký scrollbar nebo to prostě půjde dál a dál ten seznam?

neviem ako tam bude vyzerat scrollbar ale mozno sa to moze hybat cele a len ten obrazok bude mat "position: fixed"? (ale len hadam)
