### ISSUE TITLE
Add custom backendUrl to GoodData Writer

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#3274]
Přidat políčko custom backend url někam sem:
![image](https://user-images.githubusercontent.com/215660/57013584-79c6f480-6c0c-11e9-91f6-a76f8686d13f.png)
Do konfigurace se to ukládá pod `project.backendUrl`

**Comment by ujovlado** [comment]
@JakubMatejka v statom tam este vidim aj field "Name of your domain", to uz nie je potrebne?

**Comment by ujovlado** [comment]
V configu to nevidim (domenu), takze asi ok :)
