### ISSUE TITLE
Login screen na velkém monitoru...

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#328]
...obsahuje bílý místo
![image](https://cloud.githubusercontent.com/assets/1427901/9107627/116f7018-3c29-11e5-9ee1-72c1c3b44a2f.png)

**Comment by Halama** [comment]
děje se ti to pořád? já to všude vidím ok.

**Comment by padak** [comment]
děje, dám logout a zmenší se to


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by Halama** [comment]
dělalo to Gooddata extension :)
