### ISSUE TITLE
gdwr - přidat tlačítko Synchronize dataset do Writeru

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#330]
Nejlépe asi sem: 
<img width="392" alt="_dev__jakub_-_writers___gooddata_-_gwc_test___table_out_c-main_big" src="https://cloud.githubusercontent.com/assets/215660/9111946/9fc697c0-3c4b-11e5-97c7-6c92e18394d8.png">

Je to POST call `/sync-datasets` s parametry `writerId` a `tables=["tableId"]` (viz. http://docs.keboolagooddatawriter.apiary.io/#post-%2Fgooddata-writer%2Fsync-datasets)

**Comment by padak** [comment]
jj!


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by Halama** [comment]
Nasazeno.
![image](https://cloud.githubusercontent.com/assets/903531/9112858/9f83e0e6-3c51-11e5-8bf2-a9ffe0401e7a.png)

**Comment by Halama** [comment]
btw. do toho modalu by asi bylo dobrý i popsat co ta feature vlastně dělá (to se týká asi i tech ostatních z toho menu). Já vlastně nevím co dělá ta `synchronize` operace a k čemu by mohla být dobrá, to bysme tam asi měli napsat.

**Comment by JakubMatejka** [comment]
Tý jo, to byla rychlost. ;o) Díky

--
Jakub Matějka
Developer | Keboola Prague
www.keboola.com

On 6 Aug 2015 at 15:42:44, Martin Halamíček (notifications@github.com) wrote:

btw. do toho modalu by asi bylo dobrý i popsat co ta feature vlastně dělá (to se týká asi i tech ostatních z toho menu). Já vlastně nevím co dělá ta synchronize operace a k čemu by mohla být dobrá, to bysme tam asi měli napsat.

**Comment by padak** [comment]
oba jste mega! SYNC. je popsaný tady https://developer.gooddata.com/article/maql-ddl#synchronize jen bych to linkoval

**Comment by Halama** [comment]
jsem se nechtel poustet do niceho velkeho tak mi takovahle prkotina po tom prezrani prisla vhod :)
Super, ten link tam da https://developer.gooddata.com/article/maql-ddl#synchronize Doufam ze bude mi nejakou zivotnost ...
