### ISSUE TITLE
Prev page v browseru neresetuje podobu tlačítka

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#331]
Jsem na stránce extractorů, kliknu na "New Extractor", tím pádem se tlačítko "zmáčkne". Ze stránky s výberem nových extractorů dám v browseru back to previous page a tlačítko je pořád zmáčknuté.
Zůstane tam asi předchozí hover a následně se duplikuje, protože když najedu na to "stále zmáčknuté" tlačítko, ztmaví se ještě víc. Platí i pro Writer.
![ilinky - 1188 - extractors 2015-08-07 13-22-36](https://cloud.githubusercontent.com/assets/12933713/9134791/18066a6e-3d08-11e5-8769-9b8328c67c5b.jpg)

**Comment by Halama** [comment]
dobrej postřeh :) mrknu na to
