### ISSUE TITLE
simple export of storage documentation to markdown

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#3322]
internal reference https://github.com/keboola/internal/issues/148#issuecomment-490049143
Uzivatelovi sa po kliknuti na tlacitko "export to markdown" otvori "save as" dialog, vyberie subor do ktoreho sa v markdowne vyexportuje storage documentation.
### Format vystupneho csv

```
## <bucket name>
<bucket description>
### <table name>
<table description>
#### <column name>
<column description>
```
### How to "save file"
Pozeral som po moznostiach "save file on client side" a narazil na tieto 2 libky:
- 1. `FileSaver` https://github.com/eligrey/FileSaver.js
- 2. `StreamSaver` https://github.com/jimmywarting/StreamSaver.js

Predtym nez sa pustim(e) do implementacie by som to rad tuto prediskutoval, @ujovlado @natocTo dava vam to zmysel?

**Comment by natocTo** [comment]
Myslím že ok.

`FileSaver` používám v Kbc-diagram a funguje v pohodě. Tam exportuji to json ale myslím že MD bude úplně v pohodě. 

Pak mě spíš napadá že by se s tím dalo vyhrát ve smyslu otevřu modal. Tam bude checkbox "export all". Když to doškrtnu tak tam bude multi select box kde vyberu buckety které chci exportovat třeba. Ale to jsou už jen funkce pak navíc.

Další plusová funkce by bylo ještě vygenerovat "obsah" nahoru. Odkazy na jednotlivé části markdownu (bucket, table). Jde to vůbec? :) To by se asi muselo generovat spíš jako html nebo tak co, to je asi blbost teda.

**Comment by natocTo** [comment]
Jinak markdown je přímo požadovaný jo? Kdo to bude používat ten export?
Mě přijde markdown takovej ne moc user frindly. Ale on to asi normal otevře i textový editor že.

**Comment by kacurez** [comment]
zatial by som to urobil co najjednoduchsie tj vyexportovat vsetko, nevieme ci ma zmysel resp nejaku vyhodu to generovat selektivne. Preto aj ten markdown, ak by sme narazili ze to je nedostatocne tak nebude zlozite doimplementovat iny export(napr pdf). Ten export by mal byt pre ludi mimo kbc - ja mam taku predstavu ze si to niekde budu ukladat a napr sledovat zmeny a nato ten markdown je lepsi nez nejake pdf a asi aj html, na druhu stranu je pravda ze markdown format nepodporuje vela desktopovych notepadov a podobnych apiek(aspon co som nahodne skusal u seba).

**Comment by kacurez** [comment]
bavil som sa otom este s Padakom a sme dosli k rieseniu ze sa ta dokumentacia bude z ui snapshotovat do permanentych file uploadov vo forme markdownu. Priravim PR.

**Comment by natocTo** [comment]
Dobrý nápad.
