### ISSUE TITLE
Rozvržení stránek na MB retina 13"

### ISSUE THREAD

**Issue by jirigrill** [keboola/kbc-ui#334]
Ahoj,
takhle se mi to rozbrazuje na MB retině 13"
<img width="1278" alt="screen shot 2015-08-10 at 10 17 46" src="https://cloud.githubusercontent.com/assets/12986457/9163252/99d28d50-3f49-11e5-92a0-230a34be3a77.png">
Šlo by s tím něco udělat?

**Comment by Halama** [comment]
zdravím,
díky za report. Mrknem na to.
