### ISSUE TITLE
[transformations]: IM changedSince still set when switched back to Clone

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#3355]
Mám dve transformácie v jednom buckete. 
Každá ma v input mappingu jednu a tú istú tabulku.
Jednu nastavím ako "clone" druhú ako "copy" a nastavím jej "changed in last" na povedzme "30 days".
Zmením druhú transformáciu tiež na "clone" aby som mal rovnaké input mappingy pre jednu tabulku, kedže sa IM mergujú.
Obidve transformácie teraz majú totožný IM, ale pri spustení dostanem chybu:

<img width="1126" alt=" Job 507288944 2019-05-24 21-07-22" src="https://user-images.githubusercontent.com/1488015/58351047-f180eb80-7e67-11e9-8d43-061053bc8670.png">

Zrejme tam teda ostane uložený ten "changedSince" atribut. Ale aj keď som prepol druhý input mapping späť na "copy", changed since zrušil a znovu prepol na "clone", tak dostanem prezmenu takýto error. Takže chyba možno nie je len v UI.

<img width="1103" alt=" Job 507290671 2019-05-24 21-09-56" src="https://user-images.githubusercontent.com/1488015/58351169-4ae91a80-7e68-11e9-8cd0-315c4f95a925.png">

Zendesk ticket:
https://keboola.zendesk.com/agent/tickets/10602

Tu to mám nasimulované:
https://connection.keboola.com/admin/projects/219/transformations/bucket/1

**Comment by ujovlado** [comment]
@MiroCillik ten fix uz je nasadeny, vies potvrdit, ze to fici ako ma?

Tu druhu situaciu sa mi uplne nepodarilo nasimulovat a uz mi to konci vzdy na `load type does not match`

**Comment by MiroCillik** [comment]
@ujovlado pozriem na to

**Comment by MiroCillik** [comment]
@ujovlado tak ta druha chyba s tym nesuvisi. Ja v tej transformacii mam `select * ...`. A ono to tam prida `_timestamp` stlpec, ktory potom nevie zapisat naspat do SAPI, lebo je tam podtrzitko `_`. To asi tak ma byt :) Takze cajk 👍
