### ISSUE TITLE
Snowflake writer - Nullable is not propagated from storage types to IM

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#3357]
Kdyz si u tabulky ve storage nastavim rucne datovy typ tak se `nullable` uklada jako "false" a "true". 

Naproti tomu metadata co nastavuje extractor ukladaji `nullable` jako "1" a "0".

UI input mappingu ve writeru pocita jen s tou druhou variantou, takze userem definovany `nullable` se nezpropaguje.

Zalozil jsem testovaci projekt kde se to da vyzkouset: 
https://connection.keboola.com/admin/projects/6261/storage-explorer/in.c-user-defined/test

https://connection.keboola.com/admin/projects/6261/writers/keboola.wr-db-snowflake/507952953/table/in.c-user-defined.test

**Comment by ErikZigo** [comment]
Vlado to v minulosti fixoval, ale jen u transformaci https://github.com/keboola/kbc-ui/issues/3210

**Comment by ujovlado** [comment]
To uz mozeme presunut do nejakych "utils" https://github.com/keboola/kbc-ui/pull/3211#pullrequestreview-225099587

**Comment by natocTo** [comment]
Mrknu.

**Comment by ujovlado** [comment]
@ErikZigo tak je to tiez fixed, pockaj si na release :)

**Comment by ErikZigo** [comment]
funguje diky
