### ISSUE TITLE
Snowflake writer - Scale for numbers is not propagated from storage datatypes to IM

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#3358]
UI writeru neumi pracovat s datovyma typama ktery maji definici s desetinnymi misty. 

- Ve Storage si u tabulky nastavim ciselny datovy typ s presnosti na desetinny mista `NUMERIC(10,2)`.
- Input mapping writeru s tim ale neumi pracovat a zalozi mi tabulku s `NUMBER(10)`.

K otestovani:
https://connection.keboola.com/admin/projects/6261/storage-explorer/in.c-user-defined/test

https://connection.keboola.com/admin/projects/6261/writers/keboola.wr-db-snowflake/507952953/table/in.c-user-defined.test

**Comment by ujovlado** [comment]
@ErikZigo je to opravene (do 10 min. bude nasadene). Mozes pls potvrdit, ze to fici ako ma?

**Comment by ErikZigo** [comment]
Jj jeste jsem v kanclu a asi i dlouho budu. Tak ja na to kouknu. Diky

**Comment by ErikZigo** [comment]
@ujovlado zvladnes zkontrolovat jeste https://github.com/keboola/kbc-ui/pull/3360 ?
Oboji mi reportoval matejkys v jednom issue, tak aby se to pripadne fixnulo najednou.

**Comment by ujovlado** [comment]
jj, riesim to prave (#scm)

**Comment by ErikZigo** [comment]
funguje diky
