### ISSUE TITLE
Bucket can't be deleted?

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#3365]
the button is grey, also it's not possible to create a new table - no idea why

![image](https://user-images.githubusercontent.com/4319320/58436826-9c431500-80c7-11e9-898d-a3204f93dfd3.png)

https://connection.keboola.com/admin/projects/572/storage-explorer/out.c-keboola-python-transformation-507988669

**Comment by ujovlado** [comment]
To bude tym, ze nesedia bucket permissions, ktore boli nacitane na zaciatku. Po refreshi to pojde.

Mali by sme tie bucket permissions nejako reloadnut. To iste plati pre tabulky.

Myslim, ze sme sa o to bavili, ked sme prepisovali storage console, no asi sa to nedotiahlo.

**Comment by odinuv** [comment]
aha, jj po reloadu se to spravilo

**Comment by natocTo** [comment]
Ony se načítání na začátku a pak při vytvoření bucketu ve storage-explorer.
Dále se vyvolá akce načítaní vždy když se jde do storage-exploreru, ale tam se to nedokončí pokud už nějaký data mám, takže to nepomůže. Nevím zda to tam hodit vždy na znovunačtení, aby to nebylo zas moc často.
Nebo bych to mohl přidat k té "Reload akci" co tam máme. Ale to není moc intuitivní, jakože nemůžu nic dělat zkusím reload, nevím zda by to tak někdo udělal. Ale asi to tam může zas být. Když už reload tak více věcí co souvisí s tím na co koukám.

**Comment by ujovlado** [comment]
Ja myslim, ze by tam stacilo dat verify token (tak sme sa tusim o tom bavili), ak nesedi pocet bucketov co mam v bucket permissions a store. Ale este som to do detailu nekukal :)

**Comment by natocTo** [comment]
Jo mrknu. Asi to hodím i do toho reloadu, ale nějak takto "chytře" by to taky mohlo byt ok a lepší.

**Comment by ujovlado** [comment]
Ono sa to typicky stane vtedy, ked uz si bol v storage, mas to nacitane, spustis nejaku konfiguraciu a v ramci behu jobu je vytvoreny bucket. Ty ides do detailu ale nemas bucket permissions.
