### ISSUE TITLE
New user login

### ISSUE THREAD

**Issue by milanveverka** [keboola/kbc-ui#337]
A user without any administration rights still has the "add project" button available (such as new user who just registered but isn't invited anywhere). The experience from that moment on is quite confusing :).

There should be no add button unless I have at least one organization, and a user with no such privileges and no project should see a welcome message instead, something like "Welcome to Keboola Connection! Contact us to get started".

**Comment by Halama** [comment]
yes, it is a bug.

**Comment by Halama** [comment]
![image](https://cloud.githubusercontent.com/assets/903531/9302616/5fc80cae-44d8-11e5-964b-7a49a0217b1f.png)
