### ISSUE TITLE
GoogleDrive_ex configuration editing

### ISSUE THREAD

**Issue by milanveverka** [keboola/kbc-ui#338]
If I edit a configuration (such as target table) in the UI, the changes I made are ignored (after pushing "save", it goes back to where it was in the UI - it does, however, change it in the configuration). Also when I return to the Extractors menu, a new configuration doesn't show until I reload the page. Probably the same problem.

**Comment by Halama** [comment]
Hi, I confirm first issue. But I am not able to simulate the second one.

**Comment by kacurez** [comment]
fixed, it was an issue of the backend.
