### ISSUE TITLE
New UI - flash messages for auth pages (design)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3383]
Vo figme vidim, ze je na toto nejaky nastral, no radsej som zalozil issue, nech to pripadne nemusime prerabat.

Jedna sa napr. o reset hesla, kde oznamujeme, ze sme poslali link na reset hesla:

![Screenshot_2019-05-30_08-57-11](https://user-images.githubusercontent.com/419849/58614568-01119180-82b9-11e9-9ed5-020ece28767a.png)

Alebo ked sa nepodari  login:

![Screenshot_2019-05-30_08-57-33](https://user-images.githubusercontent.com/419849/58614587-138bcb00-82b9-11e9-8b11-e91105663562.png)

**Comment by ujovlado** [comment]
Alebo ked sa nepodari aktivacia:

![Screenshot_2019-05-30_08-59-43](https://user-images.githubusercontent.com/419849/58614656-4fbf2b80-82b9-11e9-886b-f0d472fd1289.png)

**Comment by ujovlado** [comment]
@karimartin myslim, ze by nam stacili 3-4 stavy, ktore by sme takto vedeli pouzit. Bootstrap to ma cca takto

- danger (cerveny)
- warning (oranzovy)
- success (zeleny)
- info (modry)

Neviem ako velmi budeme (a ci) vyuzivat info messages, ale asi danger/warning/success by sa nam zislo.

Chceme to nejako riesit alebo zobrat zatial toto z Figmy a ohnut si to?

![Screenshot_2019-05-30_09-21-16](https://user-images.githubusercontent.com/419849/58615806-4be0d880-82bc-11e9-85cc-4b9a683dffc0.png)

**Comment by karimartin** [comment]
@ujovlado 
Dodelal jsem zelenou a modrou info message, Figma link tu https://www.figma.com/file/PJr8wRmwn9WxiUf7ZfqeMtzd/New-UI?node-id=928%3A18

![Messages](https://user-images.githubusercontent.com/720530/58631357-9bd29600-82e2-11e9-9349-115d660f5864.png)

Plus jsem nahodil jak by mel vypadat message v loginu
https://www.figma.com/file/PJr8wRmwn9WxiUf7ZfqeMtzd/New-UI?node-id=847%3A733

![LoginMessage](https://user-images.githubusercontent.com/720530/58631579-51054e00-82e3-11e9-873b-57dd11e63608.png)
