### ISSUE TITLE
New UI - invitations and promo code

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3385]
Na project select stranke su este 2 veci.

### pozvanky

![Screenshot_2019-05-30_10-29-47](https://user-images.githubusercontent.com/419849/58619958-3ec8e700-82c6-11e9-9c1f-42d2bdcbc509.png)

Tie by sa imho dali vyriesit prave tym, co je uz vo Figme:

![Screenshot_2019-05-30_10-34-26](https://user-images.githubusercontent.com/419849/58620290-01188e00-82c7-11e9-9f0f-ab39fe61c56f.png)

### promo kody

![Screenshot_2019-05-30_10-31-28](https://user-images.githubusercontent.com/419849/58620053-733ca300-82c6-11e9-95d3-d82504536eb3.png)

Co by som vyriesil podobne a asi by sa na to prave hodil nejaky "info" styl. Ale zatial to mozeme vyriesit rovnakym stylom (toto sa pouziva minimalne)

**Comment by karimartin** [comment]
@ujovlado 
Takto tedy prosim :)

![Project Select](https://user-images.githubusercontent.com/720530/58636123-e27abd00-82ef-11e9-8176-45f12df4e937.png)

**Comment by ujovlado** [comment]
parada, diky, vidim aj tie flash messages.

**Comment by ErikZigo** [comment]
pekny porno
