### ISSUE TITLE
Contact support for 0 projects, hide searchbar.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3401]
Momentalne tam zobrazime searchbar a pod aj ked user nema projekty.

V povodnom tam bolo:

- pending invitations (to uz mame)
- link na promo kody (zatial som to tam nedaval, overim ci sa to vobec pouziva este)
- a dole odkaz na support

Ak by som tam mal dat, co tam bolo predtym, tak toto:

![Screenshot_2019-05-31_17-42-51](https://user-images.githubusercontent.com/419849/58717447-89805700-83cb-11e9-801c-675da3910332.png)

Myslim, ze sa to moze poriesit v ramci ProjectsList. A je tam odkaz na support.

**Comment by ujovlado** [comment]
Mozno by sa tam hodil aj nejaky h1, no neviem co by tam malo byt, ked "Welcome"  uz je na login screen :)

**Comment by natocTo** [comment]
Pokud se vymyslí nějaký grafika tak to určo zpracuji. 
Mě se teda líbí i takto jednoduše jak to tam máš na screenu.

**Comment by ujovlado** [comment]
Kludne to asi sprav tak, ja tom tam nevymyslal vlastne nic nove, len som vytiahol co je aktualne v produkcii.

**Comment by ujovlado** [comment]
![Screenshot_2019-05-31_17-54-23](https://user-images.githubusercontent.com/419849/58718124-24c5fc00-83cd-11e9-8bf8-d8f29ead1b54.png)

^ s tym, ze tie promokody tak ako som spominal (pojdu asi prec, overim)
