### ISSUE TITLE
Color for anchors, font-size

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3403]
Na token retrieval page to mam este v starych farbach, zislo by sa tam doladit farby odkazu pripadne velkost fontu. (vid. linknute issue)

**Comment by natocTo** [comment]
Ty velikosti fontu nevím jaké jsou základní moc. 14px asi obyč text ale pak už moc nevím. Kor ten login page to je ještě takové stránka "mimo".
