### ISSUE TITLE
Init modal styling

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3404]
V par catiach uz budeme mat aj modaly. Asi by bolo fajn tam dat len nejaky zaklad, nech to sedi s designom.

![Screenshot_2019-05-31_20-46-48](https://user-images.githubusercontent.com/419849/58729388-97dd6b80-83e9-11e9-9401-0bdaa721d5bc.png)

**Comment by ujovlado** [comment]
Schvalne pisem init, nemusi to but komplet cele, vobec by som asi neriesil nejako extra inputy. Asi staci len buttony, ten krizik na zavretie a mozno este nieco. Ale necham to na teba :)

**Comment by natocTo** [comment]
Zkusím. Koukám do Figmy a asi moc krom těch tlačitek a křižku nevymyslim no.

**Comment by ujovlado** [comment]
Tam asi len aby to uplne netrcalo. Potom ich doladime, ked sa bude robit ta druha cast. Toto vlastne stale bude "skryte" pod `new-ui` class.

**Comment by natocTo** [comment]
Jop. Zachvilku tam pošlu úpravu.

Jsem zvědavej jak to celé nakonec zapadne do sebe, čím víc koukám do té Figmy tím víc si říkám že to bude docela mazac :)

**Comment by ujovlado** [comment]
Toto je ta horsia cast, lebo sa mixuje "backend" a "frontend render" (ak sa to tak da nazvat). Potom to bude trosku lahsie, lebo sa to bude dat ladit v kbc-ui (ale zase bude toho viac). Cielom ale je tych veci na connection postupne zbavovat, alebo minimalne pouzit len cisty bootstrap.
