### ISSUE TITLE
Gooddata writer - label with datatype

### ISSUE THREAD

**Issue by yustme** [keboola/kbc-ui#3409]
## Problém
Aktuální s GD writeru při volbě "LABEL" nemáme možnost vybrat datový typ a bereme automaticky VARCHAR (nejspíš). Pokud zdrojový sloupec má ale ty `int`, tak se to vysype při nahrávání dat.

## Řešení
U políčka s typem "LABEL" přibude select na datový typ, jako má například "ATTRIBUTE"
![gd-writer (1)](https://user-images.githubusercontent.com/5272798/58800118-5aeec000-8607-11e9-8a3b-f8fb03256ad1.png)

**Comment by natocTo** [comment]
Koukám že v UI se u labelu vůbec neurčuje typ. Tam se prostě jen ukládá reference na jaký attribut třeba to je napojeno.  Tak myslím že ta logika ohledně typu bude mimo UI.

Zkouším hledat kde se dá. Tady podle toho to vypadá že pokud neuvedu žádný datatype tak je default 
asi VARCHAR(128). https://help.gooddata.com/doc/en/building-on-gooddata-platform/data-modeling-and-logical-data-model/xae-product-introduction/maql-ddl

Tady nevím zda se sestavuje ten modal a pro hyperlink se tam dává VARCHAR(255), ale jinak nic tak možné tam skončí ten default. Nevím zda někam sem by nešla přidat ta logika aby se to zjistilo podle te reference. Jaký typ nastavit. https://github.com/keboola/gooddata-writer/blob/31c87e3d46cd036a29c9532402dc318d1f4a3c87/GoodData/Model.php#L193

Zase tady to vypadá že pokud bych to tam měl tak to použiji https://github.com/keboola/gooddata-writer/blob/31c87e3d46cd036a29c9532402dc318d1f4a3c87/GoodData/Model.php#L204
Tak nevím zda to dodělat na UI. Příjde mi divný aby uživatel musel dvakrát zadávat to samé. Myslím že by se to mělo doplnit samo podle te reference když to má být stejné.

**Comment by JakubMatejka** [comment]
Právě jde o to, že by v ui měla být možnost nastavit typ u labelu. Writer to nastavuje (řešme jen nový Writer, takže přesnější bude odkaz sem: https://github.com/keboola/gooddata-writer-v3/blob/master/src/Model.php#L105 resp. sem: https://github.com/keboola/gooddata-writer-v3/blob/master/src/Model.php#L249), tak nic nebrání tomu aby to šlo nastavit i v ui.(?)

**Comment by natocTo** [comment]
Jej tak se omlouvám za špatný odkazy. Jsem si říkal že když mám Atribut kde mám nastavený INT a pak mám LABEL který odkazuje na daný Atribut. Tak už bez uživatele vím jaký datatyp mám nastavit. Ten co je u toho Atributu. Proč by to uživatel zadával znovu.

Ale asi to bude nejjednodušší to hodit do UI pro začátek a případně pak oddělat a dělat to jen na pozadí.

**Comment by JakubMatejka** [comment]
No ale atribut a jeho label (případně víc labelů) jsou dva různý sloupce ve Storage a každý může mít jiný typ, to je úplně legální situace i potom v GD

**Comment by natocTo** [comment]
Jo díky za vysvětlení :) tak na to mrknu.
