### ISSUE TITLE
TableSelectorForm - trim or validate value

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#3410]
**TableSelectorForm** umoznuje nastavit nevalidni hodnotu pro ID tabulky. 

https://github.com/keboola/kbc-ui/blob/master/src/scripts/react/common/TableSelectorForm.jsx

Napriklad pokud si odnekud zkopiruju a vlozim id tabulky s mezerou na konci. Tak v UI to na prvni pohled neuvidim a extractor pak konci user/app errorama.

Mohlo by to provadet trim, nebo jeste lepe zobrazit chybovou hlasku. Neco podobneho uz mame ve Storage pro zalozeni tabulky/bucketu

![image](https://user-images.githubusercontent.com/1726727/58800442-1f082a80-8608-11e9-89e7-82c55de9e828.png)

**Comment by natocTo** [comment]
Asi připravím ten trim. Alert by byl lepší asi ale tím jak je to generická komponenta zobrazena na více místech tak by se to muselo řešit na každém takovém místě zvlášt. Pokud tabulka nemůže mít mezery tak myslím už super užitečný to trimovat.
