### ISSUE TITLE
RStudio, Jupyter - new sandbox error

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3412]
https://keboola.slack.com/archives/C02CGK5CL/p1559555343017300

**Comment by odinuv** [comment]
co to?

**Comment by natocTo** [comment]
Jdu mrknout zda to je aktuální, dělo se u mě, že jsem měl přej nějak špatně nastavené limity.

**Comment by odinuv** [comment]
myslis ten large sandbox?

**Comment by natocTo** [comment]
Měl jsem nějak popletené velikosti RAM psal Vojta. Pak jsme to zase zkoušel nastavit zpět. 
Teď startuji local abych zkusil zda už mi půjde vytvořit sandbox nebo ne.

**Comment by odinuv** [comment]
ty limity uz jdou smaznout https://keboolamanagementapi.docs.apiary.io/#reference/projects/remove-project-limit/remove-project-limit takze si to muzes vyresetovat do defaultu

**Comment by natocTo** [comment]
Dobrý už mi to jde. Ale i tak si to pak asi promažu. Tak tady zavírám.
