### ISSUE TITLE
New UI - 404 page

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3418]
Kari este nachystal 404 stranku:

![404](https://user-images.githubusercontent.com/720530/58876107-6c020480-86cd-11e9-9aaa-66dd02cf8f2c.png)

Tam by to malo byt easy, len pls pouzi asi nejake zanorenie `.new-ui .error-page` (namiesto `.new-ui .login-page`), lebo to bude uplne novy layout. Ale to je myslim jasne:)

**Comment by natocTo** [comment]
To bude pouze na backendu? Že bych styly hodil inline zase. 
Jen ještě nevím ten odkaz tam (jestli to je odkaz) "Or let us..." Tam mám k dispozici zendesk widget?

**Comment by ujovlado** [comment]
To je cisto backend vec, takze asi to moze byt inline. Akurat teda ten obrazok by sme mohli servovat z indigo-ui, takze niekde by bolo fajn ho mat (podobne ako mame ten vpravo).

Kontakt je obyc email, neloadoval by som tam nic viac.
