### ISSUE TITLE
Google Analytics Extractor cannot be modified through UI

### ISSUE THREAD

**Issue by adam-hu** [keboola/kbc-ui#343]
Hello,

In GA-ex, when you have an already configured extraction, but want to make a change, for example, change profile from [customer x] to [--all--],

![screen shot 2015-08-20 at 12 43 31 pm](https://cloud.githubusercontent.com/assets/13881102/9376000/e5dda1c4-4739-11e5-8a7a-e2f09f985de0.png)

the UI allows this and actually saves.

Even when you run the job, it shows "success" but if you look at imported table, it only imported "profile" and not the actual endpoints being requested:

![screen shot 2015-08-20 at 12 47 35 pm](https://cloud.githubusercontent.com/assets/13881102/9376013/069dc768-473a-11e5-9ab5-044a93c032bf.png)

Only way to fix this is the use ga explorer and regenerate URL. The result works:
![screen shot 2015-08-20 at 12 47 42 pm](https://cloud.githubusercontent.com/assets/13881102/9376022/190d9a90-473a-11e5-8c46-47e52ded887b.png)

I guess if URL is the correct way to do this, then the elements in UI should be "read only" because right now it looks like you should be able to edit it directly by adding/subtracting dimensions or changing profiles.

Otherwise, perhaps the URL being generated by changing the UI is incorrect, but it's also not showing an error message which is problematic because orchestration does not generate error notification.

**Comment by kacurez** [comment]
@adam-hu it is fixed but you have to reset the profile to [--all--] option again

**Comment by adam-hu** [comment]
Great thats really cool.
In this case we already used GA explorer but next time.
We run into this a few times already. So I'm sure this fix will be used
soon!

Thank you v much.
