### ISSUE TITLE
Component - documentation link

### ISSUE THREAD

**Issue by natocTo** [keboola/kbc-ui#3440]
Nedávno jsem přijali PR, který zobrazuje snad vždy odkaz do dokumentace, pokud nějaká existuje. 
Dříve to tak nebylo, byla kupa podmínek díky kterým se to nezobrazovalo. To vedlo asi hodně tvůrců komponent aby přidaly informaci o dokumentaci třeba (často) jako první řádek popisku.

Současná situace teda je, že u hodně komponent je informace o dokumentaci duplikována. Zbytečně to zabírá místo tak by bylo fajn to projet a upravit. Nevím zda je blbé upravovat "cizí" komponenty.

![1](https://user-images.githubusercontent.com/12331181/59494027-918ccc00-8e8c-11e9-9045-39e9540e1b5c.png)

Stačí mrknout na `v2/storage` a vidím že takto to je na hodně místech.

**Comment by odinuv** [comment]
u 3rd party komponent bych se tim nezabyval, to je jejich byznys si udrzovat description, pokud je to u nasich (nemelo by), tak pryc s tim

**Comment by odinuv** [comment]
ostatne to bude vedet @hhanova jestli to nekde mame

**Comment by natocTo** [comment]
No oni to tam právě asi dali protože my to nezobrazovali, přestože tam tu URL oni měli.

Možná by to mohlo jít na status, že nově to zobrazuje vždy pokud ten link existuje. Pak bych to už nechal na nich zda to upraví, ale dám jim vědět.

**Comment by odinuv** [comment]
uz to slo http://status.keboola.com/week-in-review-january-9-2017 ale klidne muzem napsat, ze se to ted zobrazuje jeste vic :D

**Comment by natocTo** [comment]
Daty domluveno že to půjde na status. Tak zavírám.
