### ISSUE TITLE
wr-db - credentials error handling

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#345]
![image](https://cloud.githubusercontent.com/assets/903531/9384418/b218ed32-4750-11e5-9954-6ff144f9b9c8.png)

Edit mode should be opened after save error.

**Comment by Halama** [comment]
and also default port should be prefilled

**Comment by Halama** [comment]
It should return to config index after creating credentials. Please follow the behaviour of ex-db

**Comment by Halama** [comment]
Nejak mi to nefunguje, nemam aktivni save tlacitko
![image](https://cloud.githubusercontent.com/assets/903531/9408359/8d5996fa-4812-11e5-99ce-0931b715ba2e.png)

**Comment by kacurez** [comment]
fixol som to: 1994198dc73a193acdb3d084fe6db71b44de9237
