### ISSUE TITLE
Nefungující "Run" button v seznamu writerů

### ISSUE THREAD

**Issue by Joelino** [keboola/kbc-ui#346]
V novém UI některé writery nelze spustit tlačítkem "Run" na stránce s [výpisem writerů](https://connection.keboola.com/admin/projects/490/writers) (konkrétně jde o "GoodData - elogistics", projekt E-commerce Holding). Po kliknutí na tlačítko se normálně zobrazí modal s potvrzením a po odsouhlasení se prostě nic nestane.
Na Chrome, Version 44.0.2403.155 m, Windows 8.1

**Comment by Halama** [comment]
díky za report,
potvrzuju chybu, fixnem.
