### ISSUE TITLE
Allow refresh after getTables timeout.

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3461]
Ked som tesoval #3284, vsimol som si, ze ked sa nepodari getTables (uplynie 60s), vyhodiu sa mi notifikacie, ostane to v  "loading" stave a nemam moznost to refereshnut znovu.

Predpokladam, ze len niekde chyba `finally` na zrusenie loading state.

![Screenshot 2019-06-20 at 11 40 28](https://user-images.githubusercontent.com/419849/59838999-3b1e0280-9350-11e9-91fc-a80262645bd9.png)

**Comment by pivnicek** [comment]
Wait, wasn't there always a link to fetch again?  There used to be.

**Comment by natocTo** [comment]
The reload button is hidden during reloading.

**Comment by pivnicek** [comment]
aha, right! I mis-read ujo's description :-) sorry
