### ISSUE TITLE
gooddata writer v3: support readModel sync action

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#3480]
PR  https://github.com/keboola/gooddata-writer-v3/pull/39

Jedna sa o pridanie podpory nacitania LDM modelu z gd projektu cez sync akci kde writer po zadani credentials a  dalsich parametrov nacita gd projekt, vytvori vystupne tabulky v zvolenom buckete a updatne dany konfig o nacitany model.

V UI by sa malo jednat o upravu modelu pripojenia sa na existujuci gd projekt:
![image](https://user-images.githubusercontent.com/1412120/60162894-c1c45b00-97fa-11e9-8456-a0ba79680e03.png)

- sync akce: `readModel`, inputy https://github.com/keboola/gooddata-writer-v3/blob/master/README.md#read-model
- oproti akci pripojenia sa na existujuci konfig je tam naviac select pre bucket

**Comment by JakubMatejka** [comment]
@kacurez tím myslíš, že se to bude moct volat kdykoli? Nenecháme to jen na vytvoření konfigurace při volbě "z existujícího projektu"? (Tím budou credentials už vyplněný a do ui by stačil jen checkbox že se má načíst i model a ui by nejdřív vytvořilo konfiguraci a potom zavolalo tuhle sync akci. Nebo je to v něčem lepší takto?)

**Comment by kacurez** [comment]
aha good point! to by slo, tak to bude vlastne jedoduchsie potom. Upravil som popis issue.
btw novy konfig sa nemusi vytvarat, v case ked sa nastavuje pripojenie na gd projekt(resp vytvorenie noveho) je uz konfig vytvoreny, takze len updatne existujuci konfig

**Comment by JakubMatejka** [comment]
Ještě je to nějaký divný tady: https://connection.keboola.com/admin/projects/313/writers/keboola.gooddata-writer/516340487/table/in.c-gd-read-model.products

Nevíte ja se tam dostaly tyhle sloupce?
![image](https://user-images.githubusercontent.com/215660/60362635-bed78f00-99e1-11e9-975a-854c55bba9c2.png)
Nejsou v konfiguraci ani v mappingu:
![image](https://user-images.githubusercontent.com/215660/60362759-06f6b180-99e2-11e9-96b5-d9b9d463ed3a.png)

**Comment by JakubMatejka** [comment]
Kua, beru zpět. Napojil jsem to na bucket který už měl stejně pojmenovaný tabulky, ale jinak sloupce. 🙄 To asi není úplně ideální. Nebylo by lepší, kdyby ten bucket nesměl existovat a Writer ho vytvořil?
