### ISSUE TITLE
Warning if there's any table with "last import date" when running single item in writer

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3485]
Momentalne tam mame warning, ktory sa zobrazi len ked idem pustat jeden riadok a ten ma "Automatic Incremental Load".

![Screenshot 2019-06-27 at 12 45 40](https://user-images.githubusercontent.com/419849/60260294-7df45300-98d9-11e9-941b-6e0c6e9bfab3.png)

Avsak ked idem pustit iny, ktory automaciky load nema, uz sa mi to nezobrazi ale resetne mi to state toho predosleho (a vlastne aj vsetkych ostatnych).

Podla mna by to malo zobrazit warning vzdy ked idem pustit jeden riadok a mam co i len jeden zaznam o last import date v state.

Potom by to vyzeralo cca takto:

![Screenshot 2019-06-27 at 12 57 10](https://user-images.githubusercontent.com/419849/60260983-22c36000-98db-11e9-8f88-eeebddc4b583.png)

cc @ondrejhlavacek

**Comment by odinuv** [comment]
je to dlouhy, ten caution bych dal na zacatek a ta druha veta to muze vysvetlovat

**Comment by ujovlado** [comment]
dobry point, skor chcem aby si precitali to druhe ... bude to tam teda len do casu, kym to nebude na config rows
