### ISSUE TITLE
Stránky mimo projekt

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#35]
* [x] Login
 * [x] Registrace
 * [x] Lost Password
 * [x] New Password
 * [x] Změna hesla a nastavení uživatele
 * [x] Aktivace uživatele
 * [x] Seznamy - projekty, organizace atd... ceka na nakresleni
 * [x] Chybová stránka 500, 404
 * [x] Error neautorizovaný přístup do projektu
 * [x] Token retrieve

**Comment by Halama** [comment]
Dodat linky na terms and conditions

**Comment by JakubMatejka** [comment]
Chybová stránka: http://kbc-bootstrap-jakub-devel.keboola.com/examples/error.php (nevím jak s tím číslem, jestli ho tam nechávat)
Seznam projektů: http://kbc-bootstrap-jakub-devel.keboola.com/examples/projects-list.php

**Comment by Halama** [comment]
To číslo tam imho má být, překrývá mi ale to Keboola logo:
![image](https://cloud.githubusercontent.com/assets/903531/7934253/f8a9bf74-0925-11e5-98a4-34a13995887e.png)

**Comment by JakubMatejka** [comment]
Logo opravím. S tím číslem spíš jde o to že v psd je to obrázek (je to průsvitný, s nějakýma filtrama a zeštíhlený víc než dokáže CSS). Udělal jsem to textem a ostyloval abychom mohli kód měnit. Nebo to je jen pro 404ky a mám to nechat v obrázku?

**Comment by Halama** [comment]
Možná je to celý myšlený že by to mělo bejt jenom jakoby v pozadí za tím čtvercem i logem. Klidně bych tam asi nechal jenom 404, imho je to takový ilustrační spíš.

**Comment by Halama** [comment]
Možná by to mohlo být už přímo v tom obrázku s pozadím?

**Comment by JakubMatejka** [comment]
Jasně, dal jsem to do pozadí

**Comment by Halama** [comment]
Máme stránku maintainera/organizace ...

![image](https://cloud.githubusercontent.com/assets/903531/8333177/2b6cedfa-1a92-11e5-8c05-afea30828e1e.png)

**Comment by JakubMatejka** [comment]
Stránka mimo projekt: http://kbc-bootstrap-jakub-devel.keboola.com/examples/single-page.php

Kostra html vypadá cca takto:
```html
<body class="kbc-single-page">
  <nav class="navbar navbar-fixed-top kbc-navbar">
    <div class="col-xs-10">
      <div>
        ...
      </div>
    </div>
  </nav>
  <div class="container-fluid col-xs-10">
    <h1 class="kbc-title">
        Title
    </h1>
    <div class="kbc-main">
      <div class="container-fluid kbc-main-content">
        ...
      </div>
    </div>
  </div>
</body>
```

**Comment by Halama** [comment]
super díky, zkusím to tam nasadit.

**Comment by Halama** [comment]
@JakubMatejka Tak jsem to nasadil. Jediny co tam bude potřeba dostylovat jsou imho ty panely.
![image](https://cloud.githubusercontent.com/assets/903531/8431864/8adf8e56-1f3c-11e5-88c0-dff44ca63f1e.png)

**Comment by JakubMatejka** [comment]
@Halama No, pokud by se ty panely obalily jakože tabulkou (`div.table>div.tr>div.td>`), tak to bude ok, nicméně bylo by lepší to vyřešit pořádně. Problém je že všude jinde (např. `#/transformations`, `#/writers/gooddata-writer/rctest`, `#/jobs/122032240`) ten `.panel-header` obsahuje `.panel-title` ač by neměl (http://getbootstrap.com/components/#panels-heading), šlo by ho (`.panel-title`) odstranit? Nevím jak to funguje, generuje se tam nějak automaticky.

**Comment by Halama** [comment]
Takhle to renderuje panel z `react-bootstrap`. http://react-bootstrap.github.io/components.html#panels
Pokud je header čistý string tak tam tu class `panel-title` nedá, pokud je header html element obalí to tím `panel-title`. Takže s tím asi moc neuděláme.

**Comment by JakubMatejka** [comment]
To mi přijde že by to mělo být spíš naopak. ;o) Ale ok, vymyslím to nějak jinak. Bude se tam muset stejně dát nějaký markup navíc, přidal bych tam třeba `.kbc-panel-heading-content`. Bude to vypadat takto:
![organization_-_kbc_testing___keboola_connections](https://cloud.githubusercontent.com/assets/215660/8457124/d997abea-200f-11e5-9d9a-0380cd14bf9e.png)

**Comment by Halama** [comment]
jo přidat markup tam nebude problém, jsou to v podstatě jenom dvě stránky. Maintainer a organizace.

**Comment by Halama** [comment]
Koukám že si to tam přidal https://github.com/keboola/kbc-bootstrap/commit/62bd41433b8b912713b1a6464cf985315eb892a0, updatnu teda bootstrap a upravím ten markup. díky
