### ISSUE TITLE
Can not see organization I am administrator of

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#350]
Hi,

when I am an administrator of an organization in KBC and I am not invited into any projects of this organization, it will not show up and I can not invite myself in them. But I can still make a project in this organization.

Here is a list of organizations in the overview of my account:

<img width="538" alt="snimek obrazovky 2015-08-25 v 12 14 18" src="https://cloud.githubusercontent.com/assets/13956703/9458696/1ece8a3c-4b24-11e5-98bd-ecdb98bc20ad.png">

And here is a list of organizations I can create project in:

<img width="538" alt="snimek obrazovky 2015-08-25 v 12 14 18" src="https://cloud.githubusercontent.com/assets/13956703/9458700/31fa481c-4b24-11e5-95c8-14117c5ed037.png">

I think organization should be visible even if I have not yet been invited to the projects as I can invite myself as an administrator. Do you agree?

**Comment by Halama** [comment]
Hi,
yes I agree it is a bug. It'll be fixed soon, thanks for report.
