### ISSUE TITLE
New UI menu release steps

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3502]
Len pre evidenciu. Pri `kbc-ui` a `connection` myslim nezalezi na poradi

#### indigo-ui

- [x] mergnut a otagovat https://github.com/keboola/indigo-ui/pull/389
- [x] ^ loadnut do `indigo-ui-kbc` a checknut lokalne (pripadne aj v produkcii)
  - je to verzia `v201906171456.0.0-2-gb75c070`
  - https://connection.keboola.com/admin?indigoUiVersion=v201906171456.0.0-2-gb75c070
- [x] release `indigo-ui-kbc` -> tym padom su CSSka v produkcii

#### kbc-ui

- [x] checknut hlavny PR https://github.com/keboola/kbc-ui/pull/3494, pozret si to lokalne a na tagnutom builde
  - verzia `?kbcVersion=build-3494.1-0-g27bf01e`
- [x] merge

#### connection

- [x] este raz prejst a sfinalizovat https://github.com/keboola/connection/pull/2080 (nebol tam este dummy markup)
- [x] kontrola na testingu
- [x] mergnut moznost zapnut `new-ui-menu` na featuru
- [x] skontrolovat, ci to fici pre projekty, co maju tu featuru
- [x] pustit pre vsetkych https://github.com/keboola/connection/pull/2093

#### post na posthaven

- [x] pripravit post na status
- [x] publikovat

**Comment by ujovlado** [comment]
Ta verzia je vystupom kazdeho tagnuteho alebo master release `indigo-ui-kbc`
https://travis-ci.org/keboola/indigo-ui-kbc/jobs/555738355#L497

**Comment by ujovlado** [comment]
`indigo-ui` a `indigo-ui-kbc` poriesene

**Comment by ujovlado** [comment]
`kbc-ui` uz je tam tiez :tada: ... takze este ten backend, post a mame to :)

**Comment by ujovlado** [comment]
Post na status je ready.

**Comment by natocTo** [comment]
Ještě připravím čístku v UI po spuštění všem.

**Comment by ujovlado** [comment]
Release dobehol, post som publikoval.
