### ISSUE TITLE
Notifications badge count

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3504]
![D3FB6789-281B-404A-8623-8319A5E34195](https://user-images.githubusercontent.com/419849/60886232-b5f08400-a251-11e9-8f21-8df0068f0059.png)

**Comment by ujovlado** [comment]
Neriesil by som, ze to musit zobrazit 10000. Akonahle ich je viac ako 99, dal by som tam 99+.

T.j. priestor vzdy na max 3 cislice

**Comment by natocTo** [comment]
Ok mrknu.
