### ISSUE TITLE
Title for icons

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#3505]
Nebyl jsem si jistý jestli tím košem nesmažu projekt, mělo by to myslím ukazovat alespoň v title o co jde.

![image](https://user-images.githubusercontent.com/903531/60886526-842bed00-a252-11e9-9286-b25da0619fc3.png)

**Comment by ujovlado** [comment]
Pridam tam zatial `title` atribut. To by malo staci. AK by to bolo malo, mozeme este zvazit tooltip. Ale tie v menu moc nepouzivame.

**Comment by Halama** [comment]
obyč `title` je imho ok.

**Comment by ujovlado** [comment]
![Peek 2019-07-09 14-39](https://user-images.githubusercontent.com/419849/60888576-64e38e80-a257-11e9-9f42-7db577cc4145.gif)
