### ISSUE TITLE
Input Mapping data types from Oracle

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#3529]
By default `NaN` are appended to numeric data types provided by Oracle Extractor.

Default Input Mapping:
![image](https://user-images.githubusercontent.com/903531/61635290-826f1a00-ac93-11e9-8f13-242cb973145d.png)

Column metadata:
![image](https://user-images.githubusercontent.com/903531/61635488-fb6e7180-ac93-11e9-9501-8617627e957d.png)

If default Input Mapping isn't change it throws error on execution:
`Invalid data type definition for column DEMO_COLUMN: '44,NaN' is not valid length for NUMBER`

**Comment by natocTo** [comment]
To je na minutku. Opravím hned.

**Comment by Halama** [comment]
Nemáš mít dovolenou? :)

**Comment by natocTo** [comment]
Však mám, jen se taky chvilku relaxuji u PC :) abych nedostal úpal venku

**Comment by Halama** [comment]
super, jinak jsem si nebyl úplně jistý jestli to je na UI tak jsem ještě hodil dotaz sem https://keboola.slack.com/archives/C035LGNK5/p1563801596008800

**Comment by natocTo** [comment]
Jop, bude to UI. Hned jsem tušil kde je problém a při simulaci se to ukázalo. Opravu jsem poslal na review.

**Comment by Halama** [comment]
Zrovna se objevil další ticket na to samé ale s daty od MSSQL https://keboola.zendesk.com/agent/tickets/11064
Jak koukám na ten tvůj fix tak by ale měl fixovat oboje to vypadá.

**Comment by ErikZigo** [comment]
Nahodou jsem prisel na to ze ten atribut length = 22 co generuje DB extractor je blbost https://github.com/keboola/db-extractor-oracle/issues/81
