### ISSUE TITLE
Copy transformation results in warning

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#3548]
When I copy a transformation config, I get the multiple users editing warning

![image](https://user-images.githubusercontent.com/569139/62133445-11f17a00-b2df-11e9-92eb-fb8c59e515e7.png)

**Comment by natocTo** [comment]
Are this happening every time you copy a transformation or randomly? I am trying reproduce the warning but with no luck. I think it is some timing issues. I will keep trying.
