### ISSUE TITLE
Missing padding in Create table window

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#355]
Ahoj,

při vytváření nové tabulky v SAPI není u "Create from" nastavený padding, tak je to přitisklý k okrajům. Viz. screenshot.

![image](https://cloud.githubusercontent.com/assets/12933713/9470619/feb05022-4b4c-11e5-9612-cf5cf14d06bb.png)

**Comment by ujovlado** [comment]
This issue was moved to keboola/indigo-ui#247
