### ISSUE TITLE
Concurrent editting detection

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#3552]
Pokud založím cfg od Google Drive extraktoru a provedu autorizaci (která je v modal okně), tak po proběhnutí autorizace mě to vrátí na stránku Extraktor CFG a hned vyskočí warning, že probíhá konkurentní editace:

![image](https://user-images.githubusercontent.com/1427901/62216909-f0a99000-b3a9-11e9-9cbb-c96c8844735f.png)

**Comment by natocTo** [comment]
Zkouším a zatím se nepovedlo reprodukovat. Což je dobře i špatně :) nezobrazuje se to tam všem pokaždé to je dobrý, jde spíše zase o načasování asi. To bude horší na debug. Mrknu na to více.
