### ISSUE TITLE
Source table metadata fallback

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#3555]
Parent: https://github.com/keboola/internal/issues/299

U alias tabulek [začneme nově vracet](https://github.com/keboola/connection/issues/2141) u reference na jejich zdrojovou tabulku i metadata zdrojové tabulky a jejich sloupců.

Díky tomu by mělo být možné dostat metadata např. o datových typech do projektů kam jsou tabulky linkované.

Protože metadata zdrojové tabulky budou v novém atributu bude v ui potřeba implementovat fallback na tyto metadata tam kde se s metadaty pracuje:
- Input mappingy
- Zobrazení metadat ve storage

![image](https://user-images.githubusercontent.com/903531/62362511-67b36580-b51d-11e9-885a-fafbcbd4644b.png)

**Comment by Halama** [comment]
@ujovlado @natocTo mrkli byste na to prosím jestli by to takhle šlo udělat a jak by to bylo náročný?

**Comment by natocTo** [comment]
Ve storage by to bylo jednoduchý. Úprava skoro na jedne řádek. Pokud i platí že by ty metadata alias tabulky byly pouze read only.

Pro IM to vypadá dost podobně. Nevidím nic kde by se to mohlo zaseknout.

**Comment by natocTo** [comment]
Máme to teda rozházená všude možně tu práci s metadaty, takže je možný že se něco ukáže. Chtělo by to pak nějak učesat :) člověk nachází logiku kolem column metadata ve 4 různých utils souborech.
