### ISSUE TITLE
Missing animation when opening modal w/o specific content

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3577]
Bude to bug react-bootstrap, ked sa pouzije s React 16 ...

https://github.com/keboola/kbc-ui/pull/3470#issuecomment-519511361

**Comment by ujovlado** [comment]
Opravit by to slo manualnym pridavanim `autoFocus` ale je to nesystemove a iba by sme si zaniesli do kodu bordel. A tiez je mozne, ze je to s tym autoFocus nahoda.

**Comment by natocTo** [comment]
Tak to je náš bug :) připravím PR
