### ISSUE TITLE
faster access to sandbox

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#359]
Přístup do sandboxu (přes transformace) - za mě normálně do levého menu, ať to mám hned po ruce, pracuju s tím pokaždý když tam vlezu (nedalo se moc otestovat, padal mi load tabulek)

**Comment by ujovlado** [comment]
Sandboxes/Workspaces sa este budu riesit. Toto je ale myslim no-go, pretoze uz lave menu nemame :)
