### ISSUE TITLE
Missing icon in component detail

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3611]
Nespominam si na 100% ci tam bola ale zda sa mi, ze sme ju tam prave nedavno pridavali.

Je mozne, ze sme to vyhodili s updatom React Router 3?

![Screenshot 2019-08-13 at 18 10 46](https://user-images.githubusercontent.com/419849/62957765-b1416180-bdf5-11e9-955c-c1692fcc3322.png)

**Comment by natocTo** [comment]
Mrknu.
