### ISSUE TITLE
transformations - informations about last runs

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#363]
Přímo ve výpisu transformací mít informace o posledním vykonání (stav, trvání, datum posledního spuštění) - podstatná věc řeším optimalizaci, nebo implementuji nové věci. Jobs dobrá věc, ale je to úplně na jiným místě, v případě doklikání se do orchestrátoru a přechod zpět je to ještě horší.

**Comment by ondrejhlavacek** [comment]
Je nutný uložit informaci o jobu v API

**Comment by Halama** [comment]
souvisí s https://github.com/keboola/syrup/issues/38

**Comment by ondrejhlavacek** [comment]
@Halama ještě nad tím dál přemýšlím a bude to komplikovanější ... Přes api můžu spustit bucket / fáze / transformace, info o posledním spuštění bude  v detailu transformace? Nedokíážu jednoduše určit, kolik času z jobu celýho bucketu trvala jedna transformace. Když ten job bude třeba jen na nějaký fáze, budu muset kontrolovat i fázi (a co když jí přesunu?). Vyřešilo by to, kdybych si u každýho jobu ještě uložil všechny transformace, který se pouštěly (nějaký pole) - půjde v tom pak vyhledávat?

**Comment by Halama** [comment]
uplne nevim jestli to davat do transformace. To by bylo pak potreba k nim nejaky specialni api ktery by to merglo s informaci z jobu nebo z keenu.

Jinak tohle jako napad spis. Nepsal jsem to ja ale pastnul jsem to sem z nejake sady pripominek od nekoho.

**Comment by Halama** [comment]
jo jinak to ze by u jobu po jeho dobehnuti bylo indexovany pole co to spustilo by asi bylo fajn

**Comment by Halama** [comment]
jenom nevim kam to dat, mame tam parameters a results. Nevim cemu je mozne nastavit custom mapovani. Nebo tam na to zavest neco jineho?

**Comment by ondrejhlavacek** [comment]
Zkusím na to odchytit Jakuba a Mira, maj větší znalosti Syrupu a podobná věc by mohla být i ve writerech.

**Comment by Halama** [comment]
j. Jinak další možnost je že si to tapi bude samo spravovat někde bokem (třeba keen) a pak to bude vracet nějakým api callem.

**Comment by ondrejhlavacek** [comment]
No, to je taky možnost, ale ve writerech vidět datum posledního uploadu datasetu je taky užitečná a ten problém je plus mínus identickej.

**Comment by ondrejhlavacek** [comment]
převedeno do productboardu, uzavírám
