### ISSUE TITLE
UI - unable to delete facebook extractor config from ui 

### ISSUE THREAD

**Issue by tomasferko** [keboola/kbc-ui#366]
example proj id: 433

Error. Application errorContact support@keboola.com and attach this exception id. Exception id: ex-facebook-9873a1e7ac55dd4486135c4a8e262dfb

**Comment by ondrejhlavacek** [comment]
Fixed, thanks, can you try again please? Thanks!

**Comment by tomasferko** [comment]
tested with google analytics extractor. seems to be working flawlessly

**Comment by ondrejhlavacek** [comment]
this issue was exclusive to the facebook extractor. everything else was ok.


On Tue, Oct 6, 2015 at 4:36 PM, tomasferko <notifications@github.com> wrote:

> tested with google analytics extractor. seems to be working flawlessly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/366#issuecomment-145783572>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by tomasferko** [comment]
ok, let me have another go with the facebook ads extractor in particular.

**Comment by ondrejhlavacek** [comment]
facebook ads is a different app too, only ex-facebook aka facebook insights
:-)

On Tue, Oct 6, 2015 at 4:41 PM, tomasferko <notifications@github.com> wrote:

> ok, let me have another go with the facebook ads extractor in particular.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/366#issuecomment-145784689>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by tomasferko** [comment]
ok

**Comment by tomasferko** [comment]
still failing

Error. Application errorContact support@keboola.com and attach this exception id. Exception id: ex-facebook-5a55266c5b65ab0d3b1769dabd584f98

**Comment by tomasferko** [comment]
testing in project 476 btw

**Comment by ondrejhlavacek** [comment]
can you please point me to the project where it's happening? ideally in zendesk, thanks!

**Comment by tomasferko** [comment]
476

**Comment by Halama** [comment]
I have received this alert now 
An error recurred. View details.
Uncaught Error: Application error
----------------
in an inline script on https://connection.keboola.com/admin/projects/476/extractors

I'll check it http://errorception.com/projects/54e3526a24f538015600008c/errors/5582ba30fef012911baa2cd4

**Comment by ondrejhlavacek** [comment]
can I try deleting the main config?

**Comment by ondrejhlavacek** [comment]
Sorry guy, I deployed another app by accident. Redeployed, can you try again please? Thanks!

**Comment by tomasferko** [comment]
problem solved buddy. works like a charm

**Comment by ondrejhlavacek** [comment]
cool, thanks!
