### ISSUE TITLE
gooddata-writer - exported status not consistent

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#369]
Tables and dimensions has flag which tells if it is exported to gooddata, it is presented in not consistent way in UI.

Exported status is important because there cannot be performed some operations for resources which are already exported.
## Tables list - exported status is not present at all

![image](https://cloud.githubusercontent.com/assets/903531/9661711/412e231e-525c-11e5-9842-f1f3c36216e0.png)
## Table detail - icon in page header

Not exported:
![image](https://cloud.githubusercontent.com/assets/903531/9661723/519953b8-525c-11e5-8956-1539ddf4ef8d.png)

Exported:
![image](https://cloud.githubusercontent.com/assets/903531/9661730/5e4f1ebc-525c-11e5-990e-c15284a03a71.png)

Date dimensions - disabled upload icon for datasets which are exported:
![image](https://cloud.githubusercontent.com/assets/903531/9661759/799abc4e-525c-11e5-9577-48219179fb59.png)
## Solution

Add `Exported` column to tables and date dimensions list with check icon?

**Comment by ujovlado** [comment]
Stary writer.
