### ISSUE TITLE
gooddata-writer - date dimensions templates

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#370]
Describe purpose of templates and specify each template - maybe link to some documentation page about date dimension.
![image](https://cloud.githubusercontent.com/assets/903531/9661850/eef73968-525c-11e5-8d96-80070ce27bb3.png)

**Comment by odinuv** [comment]
in progress
![image](https://user-images.githubusercontent.com/4319320/50729801-408be580-1140-11e9-985e-8c31bdd331fc.png)

**Comment by ujovlado** [comment]
Stary writer.
