### ISSUE TITLE
gooddata-writer - naming consistency

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#372]
`GoodData Title` vs `Title`. Both is the same and represents the title in GoodData.
![image](https://cloud.githubusercontent.com/assets/903531/9662003/ad8a3f74-525d-11e5-84bb-b58287ea229b.png)

![image](https://cloud.githubusercontent.com/assets/903531/9662022/cd7ecb10-525d-11e5-9848-313ffa990999.png)

Maybe hints could be helpful #371

**Comment by ujovlado** [comment]
Stary writer.
