### ISSUE TITLE
GDrive extrenal authorization - processing icon padding

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#375]
Hi,

the dotted circle probably doesn't have padding, so it's displayed right next to the Generate button.
![google drive extractor](https://cloud.githubusercontent.com/assets/12933713/9717777/a299a1e8-5575-11e5-95a0-11298f7ad1a5.jpg)

**Comment by kacurez** [comment]
fixed in dbef0aff566ab660c36ab6b4d33f723890d4ac40
