### ISSUE TITLE
TAPI - bucket delete

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#382]
Its not possible to delete empty TAPI bucket Padak (see here https://connection.keboola.com/admin/projects/894/transformations). 

![ice_mobile_poc_-_transformations](https://cloud.githubusercontent.com/assets/1427901/9760466/b53c5116-56f5-11e5-8434-e45a1ecc2a96.jpg)

**Comment by Halama** [comment]
Smazal jsem ho ručně. Konfigurace nešla smazat protože bucket za ní byl smazanej přímo z konzole.

**Comment by padak** [comment]
jde zjistit, kdo to smazal? Já bych dal ruku do ohně, že jsem to nebyl. skoro by stalo za to tomuhle nějak předcházet (že to třeba v KBC nebudeme by-default ukazovat), co?

**Comment by Halama** [comment]
kontroloval jsem to, mazal to Radovan. Tohle zmizi jakmile vyresime configy takze to zatim nechavam.
