### ISSUE TITLE
Minor formatting problem on error page

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#387]
<img width="539" alt="" src="https://cloud.githubusercontent.com/assets/215660/9905320/a0d2b35c-5c84-11e5-95cb-1bf8bb6b6500.png">

Maybe it would be nicer to also reformat it for example like this:
<img width="492" alt="" src="https://cloud.githubusercontent.com/assets/215660/9905296/781ecb3a-5c84-11e5-9063-faf35dcb8b8f.png">

I would do it myself but I couldn't find where to find it in source code. ;o)

**Comment by Halama** [comment]
Myslím že to je fixnutý:
![image](https://user-images.githubusercontent.com/903531/31767719-89238482-b4cc-11e7-91f9-857257d2eeb2.png)
