### ISSUE TITLE
KBC projects search - wrong behaviour

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#388]
Searching in project page is filtering out results which are matching the clause (in some cases it doesn't care about diacritics and in some cases it does).
![ba](https://cloud.githubusercontent.com/assets/12933713/9929111/f4e8b6ac-5d2a-11e5-8af8-cceb95d572f1.jpg)
![bat](https://cloud.githubusercontent.com/assets/12933713/9929140/21576dc8-5d2b-11e5-82be-7b84f029e9f9.jpg)

**Comment by kacurez** [comment]
Searching is done via what is called a fuzzy matching(not exact matching), in this case search for `bat` will skip  `Baťa - Emailing` because it does not contain character `t` which in contrary `Baťa - Reatil` does contain. This is in terms of fuzzy matching correct behaviour.
