### ISSUE TITLE
edit link in R tapi

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#390]
this is super tricky to find it
![image](https://cloud.githubusercontent.com/assets/1427901/10001710/5e0c9132-60a3-11e5-82f3-735e292779e8.png)

is it possible to move "Edit R Script" out of script area?

**Comment by ondrejhlavacek** [comment]
That's weird! Shouldn't be there. Will fix it.

**Comment by ondrejhlavacek** [comment]
fixed by #4fd0a631c0561fc988f60512bbf328c7f622d033
