### ISSUE TITLE
Wrong link in orchestration error on mobile phone

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#391]
When I recieve an orchestration error notification and click on the link on my mobile phone, I'll get redirected to the wrong page.
https://drive.google.com/a/keboola.com/file/d/0B3XLSQBGT909Zzd1ZnBOTkhjODA/view?usp=sharing

**Comment by Halama** [comment]
can you paste here the target link? The link is in notification email?

**Comment by Matejkys** [comment]
https://connection.keboola.com/admin/projects/486/orchestrations/49297843/jobs

**Comment by Halama** [comment]
@Matejkys přepošli mi prosím celý ten mail co ti přišel od orchestratoru. dik

**Comment by Halama** [comment]
tak to děla redirect když uživatel není přihlášený. fixnu

**Comment by Halama** [comment]
je to fixnutý
