### ISSUE TITLE
Fixes in GD Writer

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#392]
I would like to have identifiers of columns hidden by default and show them after clicking on some button, for example like this:
<img width="1183" alt="gdwr-identifiers" src="https://cloud.githubusercontent.com/assets/215660/10013675/c6975820-6113-11e5-9a0b-bb2c9d74f155.png">
(And move them to the end of the table, after the preview icon)

Second thing is that input for GoodData title shouldn't be visible for types IGNORE, DATE and REFERENCE.

**Comment by JakubMatejka** [comment]
Please also add validation on the identifiers fields:
Allowed characters: lowercase and uppercase letters, numbers, underscore "_" and dot "."

**Comment by JakubMatejka** [comment]
Pěkně prosím o zapracování v nějaké dohledné době pokud je to možný ;o) @kacurez @Halama

**Comment by JakubMatejka** [comment]
Je prosím na tohle nějaký dohledný termín?
Ještě se dívám (respektive klient reklamuje) že se nedá nastavovat `identifierLabel`, nemá vůbec input. Měl by být povolen jen pro connection pointy a atributy.

**Comment by kacurez** [comment]
DONE:
- [x] Allowed characters: lowercase and uppercase letters, numbers, underscore "_" and dot "." 
- [x] Second thing is that input for GoodData title shouldn't be visible for types IGNORE, DATE and REFERENCE.

**Comment by JakubMatejka** [comment]
Super, díky
