### ISSUE TITLE
Underscores in writer's name

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#394]
I created writer called `new_config` using UI and it has the same name there but the underscore had been stripped when create writer API call had been called to Writer and so it saved it as `newconfig`.

<img width="616" alt="_dev__jakub_-_writers___gooddata_-_new_config" src="https://cloud.githubusercontent.com/assets/215660/10017711/08d59acc-6131-11e5-8320-fab9a9d84699.png">

**Comment by Halama** [comment]
To je feature, nemelo by to nicemu vadit ne?

**Comment by JakubMatejka** [comment]
No tak vadí to tomu že jsem založil writer `new_config` a když tedy potom (mimo UI) zavolám API Writeru se stejným parametrem `writerId`, tak to nefugnuje

**Comment by Halama** [comment]
Tam ale nezadáváš id ale jméno.

**Comment by Halama** [comment]
To id se z něj jenom nějak odvodí ale klidně by to mohlo být číslo.

**Comment by JakubMatejka** [comment]
Aha, a jak se teda dozvím jaký writerId mám použít když chci z ui odejít a začít volat API cally mimo ně?

**Comment by Halama** [comment]
V tom ui zatím taková  ta podpora že by ti to pomohlo generovat API cally není. Takže id buď z URL nebo:
![image](https://cloud.githubusercontent.com/assets/903531/10017971/0f4c5682-6133-11e5-8ce5-a6ea99f14885.png)
