### ISSUE TITLE
Transformation UI - Edit button rather than floating pencil beside each query

### ISSUE THREAD

**Issue by adam-hu** [keboola/kbc-ui#395]
I'd like to suggest an "Edit" button where the "Save Query" button appears in edit mode.

Sometimes there's a very long query and you have to scroll down a significant way to find the "midway" point and the very small floating edit button. I think it would be a lot easier to have it at the top of the query. (And keep existing)

![screen shot 2015-09-23 at 10 02 57 am](https://cloud.githubusercontent.com/assets/13881102/10052221/a0036060-61da-11e5-9bef-6913374cf357.png)

**Comment by padak** [comment]
+1


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by ondrejhlavacek** [comment]
Můžeš to teda prosím probrat s Padákem, ať nelitam jako hadr? :-)
