### ISSUE TITLE
Queries edit sticky buttons

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#400]
https://github.com/keboola/kbc-ui/tree/queries-edit
## Static mode

![image](https://cloud.githubusercontent.com/assets/903531/10188661/67396126-6761-11e5-8613-ee1a43d158b6.png)
## Edit mode - fix editor height and move buttons to bottom?

Similar to github editor.
## Edit mode - use sticky for large scripts?

**Without sticky**

![image](https://cloud.githubusercontent.com/assets/903531/10188875/1565c8e2-6763-11e5-9b70-2c14102697f5.png)

**With sticky**

![image](https://cloud.githubusercontent.com/assets/903531/10189122/a9480b50-6764-11e5-9e91-dd5bdbd8dbf2.png)

![image](https://cloud.githubusercontent.com/assets/903531/10189154/df4a87b4-6764-11e5-8373-c719683c50d8.png)

**Comment by ondrejhlavacek** [comment]
Nevím, kam to mám psát, tak to nechám tady...

Přeskočení toho tlačítka na horní menu mi přijde jako by to tlačítko měnilo kontext (mate mě to a imho je to špatně). Co když budou na stránce dvě takový komponenty, co se má stát?

Souhlasím s tím, že mít ho nad nebo pod queries je nešikovný, ale aspoň se to tlačítko drží u položky, ke který patří. Původní chování, že bude fixně nahoře v tom okně mi přijde skoro nejlepší, kdyby nelezlo do těch queries (byl by tam nějakej padding), ale bude to mega oser na implementaci. Řešení, že by to okno s queries skrolovalo uvnitř mi přijde taky debilní :-/

**Comment by Halama** [comment]
V tom static mode jsme  ukazal to zarovnani, to by bylo dobry tak udelat ted je tam obrovska mezera.

Dve takovy komponenty na strance nikde nemame. Takze tohle reseni myslis?
![image](https://cloud.githubusercontent.com/assets/903531/10189154/df4a87b4-6764-11e5-8373-c719683c50d8.png)

**Comment by ondrejhlavacek** [comment]
Mně by se asi nejvíc líbilo, kdyby save buttony byly u toho elementu a ne v nadpisu, a ten element by teda mohl bejt na vejšku omezenej a nemuselo by nic nikam přeskakovat. Ale vnímám to vytržený z kontextu a mám jetlag, takže možná haluz :)

**Comment by Halama** [comment]
jo s tim omezenim na vejsku by to pak asi zrejme slo. vyzkousime

**Comment by ujovlado** [comment]
Zatvaram, toto uz bolo fixnute (to ze to zmizlo doriesime v #1177)
