### ISSUE TITLE
Sys bucket of Drive extractor remains in SAPI without any config

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#401]
When I delete my configuration of Drive extractor and there are no others, empty sys bucket is still in SAPI.
![cetelem - storage keboola connections 2015-10-02 11-58-10](https://cloud.githubusercontent.com/assets/12933713/10244067/19c4f2be-68fd-11e5-9daf-06e2fa246c11.jpg)

When I create new configuration with the same name, it's already authorized to the same person as the original one.

**Comment by kacurez** [comment]
I have failed to reproduce such behaviour.
