### ISSUE TITLE
Orchestrations hang in SAPI after deleting

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#404]
When I delete an orchestration, the config table remains in SAPI. Then it's hard to maintain it (i.e. when editing phases). SAPI would also look cleaner.

6 orchestrations vs. 19 config tables:
![h1 - orchestrations 2015-10-07 09-17-25](https://cloud.githubusercontent.com/assets/12933713/10331274/54fe7712-6cd4-11e5-8620-710b95bbb37d.jpg)

![h1 - storage keboola connections 2015-10-07 09-14-20](https://cloud.githubusercontent.com/assets/12933713/10331253/3277b262-6cd4-11e5-99e2-11131ab4beca.jpg)

**Comment by ErikZigo** [comment]
You should use orchestrator API instead of editing SAPI table (to prevent some errors and mistakes)
http://docs.keboolaorchestratorv2api.apiary.io/#reference/orchestrations/orchestration-tasks

Phases support in UI will be avaiable in few weeks

**Comment by Matejkys** [comment]
Thanks Erik. But anyway, it would be nice if there are no redundant config tables in SAPI.

**Comment by ErikZigo** [comment]
Old issue. Tables was deleted on April 2016 :-) http://status.keboola.com/orchestrator-table-deletion-announcement
