### ISSUE TITLE
Answer "why" to stay w/ old UI :)

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#405]
![image](https://cloud.githubusercontent.com/assets/1427901/10410895/f0b709e8-6f50-11e5-8e89-602346e56f11.png)

**Comment by Halama** [comment]
@JakubMatejka mohl by si na to prosim kouknout? Imho to chce si zapnout ty scrollbary.

**Comment by odinuv** [comment]
Přidám pro zichr screen:

![clipboard01bbbb](https://cloud.githubusercontent.com/assets/4319320/10604374/25db4ab4-7724-11e5-9fa3-2a62ad78d7ec.png)

**Comment by Halama** [comment]
fixnuto
