### ISSUE TITLE
GD writer link to docs

### ISSUE THREAD

**Issue by Pabu01** [keboola/kbc-ui#407]
I've tried to start new GD writer. God a warning which points to "docs" but no link there.

"The writer is missing GoodData project configuration. You cannot perform any GoodData operations. See the docs please."

**Comment by Halama** [comment]
Ahoj,
mrknem na to. Tahle hlaska ve skutecnosti znamena v tomhle pripade ze writer se pripravuje. Po reloadu je to ok.

@JakubMatejka Zobrazuju to tam z toho co vraci API writeru 
![image](https://cloud.githubusercontent.com/assets/903531/10633752/1c3a36ae-77ed-11e5-9734-f20f2297bd8f.png)

API call `gooddata-writer/writers?config=demo_rijen`. Mohlo by to v tomhle pripade kdy writer ceka na zalozeni vracet nejaky jiny status nez error treba `creating`? 
diky

**Comment by JakubMatejka** [comment]
Ahoj, vím o tom a mám to v todolistu. Bohužel to není o změně jedné chybové hlášky, bude to trvat.

**Comment by Pabu01** [comment]
Super! Jen hlasim co najdu :)

**Comment by JakubMatejka** [comment]
To už je nějakou dobu opravené, zavírám
