### ISSUE TITLE
Sort DB Extractor queries by Name

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#408]
Is it possible to sort queries in DB extractor by their name? It would be much easier to find the one you're looking for (w/o using search field).
![database - cortex 2015-10-21 10-39-14](https://cloud.githubusercontent.com/assets/12933713/10631772/670fb7f6-77e0-11e5-81c7-1d25a3646d87.jpg)

**Comment by Halama** [comment]
je to fixnuty. Zaroven i seznam konfiguraci komponent se radi podle nazvu. Postupne to fixnem i u dalsich extraktoru a writeru kde to tak neni.
diky za report
