### ISSUE TITLE
flawed accordion style

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#41]
accordion sa nejak divne zobrazuje, priklad:
https://connection.keboola.com/admin/projects/305/extractor/?app=kbc.exTwitter#/?config=test

tu je pouzity ako panel z react-bootstrap:
https://connection.keboola.com/admin/projects/219/extractors/ex-google-analytics/tomas/profiles

**Comment by Halama** [comment]
oboje pofixovano
