### ISSUE TITLE
Orchestrations - crontab edit - default value for minutes

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#413]
New UI has as default value "every minute" in minutes input.
I think, that in old UI default value was "0 minute"

Problem is if user click on "x" to empty input and then save. Orchestration will run in every minute in hour, instead of specified hour.

![image](https://cloud.githubusercontent.com/assets/1726727/10758346/2e010868-7cb1-11e5-829a-8017b23fcb3e.png)

![image](https://cloud.githubusercontent.com/assets/1726727/10758358/3f64a68c-7cb1-11e5-883c-2a6988ea2f48.png)

**Comment by ujovlado** [comment]
That's fine. UI will display next schedules. Anyway, we cannot change this to something other after 3 years :-P. Closing.
