### ISSUE TITLE
Generic docker UI - configuration data editor

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#416]
It is possible to edit configuration data without going to edit mode - by inserting from clipboard. The result is confusing:

http://youtu.be/evmzmTDz1IA?hd=1

**Comment by Halama** [comment]
diky, koukam ze je to bug codemirror a uz to fixnuli v novejsi verzi. Upgradnu to.

**Comment by Halama** [comment]
fixnuto
