### ISSUE TITLE
Pick emails for notifications from list

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#419]
This is rather a feature. But it woudl be nice, if orchestration's notification UI would provide a list of email addresses of the project's admins, so you don't need to look up and type/copy the whole email address to the notifications.
![notifications 2015-11-05 11-02-55](https://cloud.githubusercontent.com/assets/12933713/10965467/6019510e-83ad-11e5-80f2-a6c7ce9d76da.jpg)

**Comment by ujovlado** [comment]
Vyriesene. Ponuka to email admina + emaily tych, co orchestraciu editovali. Vsetkych clenov projektu tam zatial dodat nejde.
