### ISSUE TITLE
missing icon in application detail for genericDockerUI components

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#423]
![image](https://cloud.githubusercontent.com/assets/1412120/11300711/6ece624e-8f91-11e5-87c5-95ec27c854fe.png)

**Comment by ondrejhlavacek** [comment]
some applications have the icon

https://www.evernote.com/l/AAXnoJsM6ctJgqCg3P1Wt36TngpGFIa6VKM

**Comment by Halama** [comment]
fixnuto, ale tahle cast parovani komponent, routy a hlavicek je dost peklo ktery jsem tam vytvoril :) 
To nekdy zkusim nejak procistit
