### ISSUE TITLE
šifrování - při uložení konfigurace není hned vidět zašifrovaná hodnota, ale až po refreshi

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#427]

**Comment by Halama** [comment]
to je divny tohle by melo slapat, vim ze to slapalo protoze jsem to fixoval, mrknu na to

**Comment by Halama** [comment]
zkouším u adform a ex-generic a šlape to v pohodě. Kde ti to dělalo?

**Comment by Halama** [comment]
Jo už to vidím dělají to nastavené které volají `saveComponentRawConfigDataParameters`.
Což je celkově zvláštní věc, už jsem na to párkrát koukal. Šlo by to dát pryč?

**Comment by ondrejhlavacek** [comment]
Zjistim! Některý komponenty to imho používají

**Comment by Halama** [comment]
jinak mam asi fix, jenom jsem ho nestihl pred obedem poslat

**Comment by ondrejhlavacek** [comment]
ha, super, díky!

On Tue, Nov 24, 2015 at 8:50 PM, Martin Halamíček <notifications@github.com>
wrote:

> Closed #427 <https://github.com/keboola/kbc-ui/issues/427> via 684fbd9
> <https://github.com/keboola/kbc-ui/commit/684fbd99aadf26b30e89df5864fdfd570d607b3b>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/427#event-473250633>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by vokurka** [comment]
Ahoj,

narazil jsem opet na nesifrovani hesel :/ OS X, aktualni Chrome, nekolikrat cisty refresh, Silverpop extractor.

Prijdu, edituju konfiguraci - pridam # pred password, ulozim a nic se nedeje. Ani po obnoveni.

Muzu to nejak lip popsat nebo nejak pomoct?

**Comment by Halama** [comment]
Ahoj,
silverpop neměl povolené šifrování, teď jsem to nastavil. Reloadni browser, dej save a mělo by to šlapat.

**Comment by vokurka** [comment]
Aha! Diky moc!

Btw: nebylo by dobry schovat tu hlasku "muzete sifrovat heslo pomoci krizku" kdyz je vyple sifrovani u komponenty? :)

**Comment by Halama** [comment]
bylo :) Hodis na to sem prosim nove issue? dik
