### ISSUE TITLE
genericDockerUI vs genericUI

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#429]
Není jasné co se má dávat do pole Configuration Data:

Silverpop (genericDockerUI)

![image](https://cloud.githubusercontent.com/assets/903531/11399240/5809a6b0-9386-11e5-817e-51da4c82f686.png)

Generic (genericUI)

![image](https://cloud.githubusercontent.com/assets/903531/11399271/7640805e-9386-11e5-95cc-e1aa00f11bb2.png)

Mozna to nema cenu resit a vyresi se to tema template. Taky by to v tuhle chvili mela mit komponenta  v dokumentaci ktera tam musi byt nalinkovana.

https://keboola.zendesk.com/agent/tickets/4178

**Comment by ondrejhlavacek** [comment]
Liší se to podle flagu, genericUI (ex-generic) a genericDockerUI (ex-silverpop) - pro ten ex-generic by asi mohlo být genericDockerUI taky

**Comment by Halama** [comment]
j to vim, ale to ui pak vypada uplne stejne takze nevis co tam dat

**Comment by ondrejhlavacek** [comment]
jj, to se liší a to by měla říct dokumentace příslušný komponenty

**Comment by Halama** [comment]
j to jsem myslel, tak pak byme meli to dokumentaci vynucovat :)

**Comment by kacurez** [comment]
napadlo ma pre genericDockerUI premenovat nazov `Configuration Data` na `Parameters`, trocha by sa to zprehladilo imho. Inac samozrejme najviac tomu pomoze dokumentacia.

**Comment by Halama** [comment]
jo to zni dobre

**Comment by Halama** [comment]
@ondrejhlavacek dava ti smysl teda to tam kde se vyplnuji parameters to prejmenovat na `Parameters`?

**Comment by ondrejhlavacek** [comment]
Jo, jasně!
