### ISSUE TITLE
ex-dropbox - issues

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#433]
## Prázdnej stav kdy je komponenta autorizovaná a nejsou přidány žádné soubory

![image](https://cloud.githubusercontent.com/assets/903531/11497745/61173c60-981b-11e5-8e3c-f40101d42981.png)
## Layout v moment kdy jedno už tam jsou nějaké soubory

![image](https://cloud.githubusercontent.com/assets/903531/11498095/9ec93246-981d-11e5-87be-d14cb2b18d2b.png)
## Mazací loader

![image](https://cloud.githubusercontent.com/assets/903531/11497751/79837520-981b-11e5-9142-5f4c9f4aafd5.png)
## Confirm buttons modalu

Sjednoť je prosím s tímhle
![image](https://cloud.githubusercontent.com/assets/903531/11505219/a3aed0f0-9849-11e5-9001-09e262d2f102.png)

Můžeš na to použít komponentu ConfirmButtons https://github.com/keboola/kbc-ui/blob/fadbddd45b7479bdc5af8807ede0f0273cef4305/src/scripts/react/common/ConfirmButtons.coffee#L13

A její použití v js kodu je vidět např. tady https://github.com/keboola/kbc-ui/blob/fadbddd45b7479bdc5af8807ede0f0273cef4305/src/scripts/modules/components/react/components/generic/FileInputMappingModal.jsx#L36
## Funkce Configure Files

Po vzoru ostatních extraktorů (google-drive, ex-db) bych to upravil na "+ Add Files". Tzn ten modal bude vždy prázdný a uživatel tam bude moci přidat další soubory. Tam bude ale asi trochu problém s tím input bucket.

**Comment by ujovlado** [comment]
Stara vec, tieto veci ex-dropbox ma
