### ISSUE TITLE
Generic Templates - provázání API + CONFIG

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#455]
1) oddělit editaci / ukládání API + CONFIG (co udělat s tou sticky lištou, když budou rozeditovaný oba, ask Halama)
2) při uložení / načtení API části načíst co je uloženýho v `requiredHeaders` a itemy tam uložit do rootu schematu `config`u jako atributy `{"type": "string"}`

**Comment by kachnitel** [comment]
baseUrl` a `authentication` muzou obsahovat objekt `{"attr": "$ATTR_NAME"}`, coz musi byt reflektovany v `config.$ATTR_NAME`

Takze bude potreba najit rekurzivne objekt s klicem "attr", a jeho hodnotu pozadovat v rootu configu

**Comment by ondrejhlavacek** [comment]
Nedělat tohle u nonDefault komponent! tohle je JEN pro default! nonDefault komponenty to budou muset mít ručně uvedený ve schématu.

**Comment by ondrejhlavacek** [comment]
@kachnitel u `authentication` žádnej objekt nevidím, připravils mi někde pls ten příklad, o kterým jsme se bavili, na kterým to můžu odladit

![screen shot 2016-01-22 at 14 44 56](https://cloud.githubusercontent.com/assets/497675/12512149/c85a17c0-c116-11e5-8d3f-5e2f1b82c67b.png)

**Comment by ondrejhlavacek** [comment]
aha, to jde přes function? :-)

**Comment by ondrejhlavacek** [comment]
solved by e97fcdc
