### ISSUE TITLE
newlines in event messages

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#456]
![mnd_-_jobs___job_166466391](https://cloud.githubusercontent.com/assets/497675/12269670/d8e73346-b952-11e5-9974-9f409b85c4f1.png)

**Comment by Halama** [comment]
Fix:
![image](https://cloud.githubusercontent.com/assets/903531/14385642/d403930e-fda1-11e5-8456-b854f7db3a41.png)

**Comment by ondrejhlavacek** [comment]
pecka!!!!

**Comment by Halama** [comment]
jeste je trochu naprd ze kdyz jde vic erroru za sebou tak splyvaji, chtelo by to dva odstiny cerverne:)
