### ISSUE TITLE
Change of disclaimer in 3rd party components

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#462]
Hi,

would you, please, consider changing the disclaimer in extractor description? Now it says this:

<img width="512" alt="snimek obrazovky 2016-01-08 v 16 01 54" src="https://cloud.githubusercontent.com/assets/13956703/12354793/8643ab18-bb98-11e5-8709-ff5ac4a0ca31.png">

My proposition is like this:

Support for this extractor is provided by its author according to his ToS, not Keboola

This is because the original statement feels like there is some level of support included with use of extractor. But not always it is the case.

Thanks!

**Comment by ujovlado** [comment]
Fixed
