### ISSUE TITLE
Fact Grain setting

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#463]
Add Fact Grain (https://developer.gooddata.com/article/set-fact-table-grain) setting to the modal of incremental load in GoodData Writer.

Fact Grain is something like compound index on dataset without connection point and has these rules:
- It can be set only if the dataset has no connection point
- It is a set of columns which have type `ATTRIBUTE`, `REFERENCE` or `DATE`

Could look like this:
- There is one select with "placeholder" by default
- If you choose column in first select, second select appears to choose another column, etc
<img width="993" alt="_dev__jakub_-_writers___gooddata___new_config___table_out_c-main_products" src="https://cloud.githubusercontent.com/assets/215660/12397224/39431062-be0c-11e5-9b14-6b150335c6d4.png">

**Comment by kacurez** [comment]
@JakubMatejka co sa stane ak ma user nastaveny nejake grain a prida connection point a posle do GD? skonci to user errorom alebo nejakou katastrofou? ide mi oto ci je potreba sledovat tu zmenu connection point alebo napr zmenu stlpca ktory bol atribut(a patril do grainu) a user ho potom prenastavil na IGNORE alebo FACT..

**Comment by JakubMatejka** [comment]
Vyfailuje to user errorem, v ui bych to asi neřešil.

--
Jakub Matějka
Developer | Keboola Brno
www.keboola.com

On 20 May 2016 at 15:35:23, Tomas Kacur (notifications@github.com) wrote:

@JakubMatejka co sa stane ak ma user nastaveny nejake grain a prida connection point a posle do GD? skonci to user errorom alebo nejakou katastrofou? ide mi oto ci je potreba sledovat tu zmenu connection point alebo napr zmenu stlpca ktory bol atribut(a patril do grainu) a user ho potom prenastavil na IGNORE alebo FACT..
