### ISSUE TITLE
ui for adwords extractor

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#466]
New AdWords Extractor in Docker needs link which generates and shows refresh token. Url to retrieve the token is `https://syrup.keboola.com/oauth/auth20?api=ex-adwords-v2&token=&id=` and it redirects user to Google and then back with response like:
```
{
  "status": "ok",
  "access_token": "ya29.bgI...",
  "token_type": "Bearer",
  "expires_in": 3600,
  "refresh_token": "1/zR_l6ZyE..."
}
```

The link should be accompanied with such description:
> You will be redirected to Google Sign In where you should login to Google account with access to the AdWords campaigns and allow our app to use it.
> Please note that refresh token is bound to this Google account and will stop working if someone changes it's password.

**Comment by Halama** [comment]
jenom si poznamenavam pro rychlejsi prepinani https://github.com/keboola/adwords-extractor

**Comment by Halama** [comment]
Takže to zatím uděláme tím způsobem jak popisuješ. Bude tam tlačítko `Get Refresh Token` s popisem výše, po jeho kliknutí to uživatele provede oauth redirectem a nakonec zobrazí získaný `refresh token` ke zkopírování.

**Comment by Halama** [comment]
A tohle generickému ui aktivujeme přes nějakou feature třeba `genericUi-oauth2`. cc @ondrejhlavacek

**Comment by ondrejhlavacek** [comment]
ok, to by šlo, ale bacha na šifrování! oauth-bundle bude response šifrovat (jako string) a rozšifruje se až v komponentě.

**Comment by Halama** [comment]
tohle uz funguje, bundle nesifruje vubec nic. Jdu k nemu nahodit nejaky issues co jsem dnes nasel.

**Comment by Halama** [comment]
@ondrejhlavacek nebo mluvis o nejake budouci verzi oauth bundle?

**Comment by ondrejhlavacek** [comment]
@Halama jj, oauth bundle by měl začít tu response šifrovat, rozhodně by neměla bejt volně přístupná komukoliv v projektu

**Comment by kacurez** [comment]
neni tam problem ze oauth bundle zasifruje inym klucom ako sa to potom ta komponenta bude snazit rozsifrovat takze to nepojde?

**Comment by Halama** [comment]
j tak to je potreba cele projit protoze tim padem prestane fungovat vse soucasne. Je k te uprave nekde nejaky popis?

**Comment by ondrejhlavacek** [comment]
@kacurez oauth-bundle to zašifruje přes api tý komponenty (ví, pro kterou komponentu to dělá)
jedinej popis je asi tady - https://keboola.slack.com/archives/docker/p1446513049000026, zbytek bude vědět @kachnitel 

oauth-bundle by si mohl držet plaintext tý odpovědi, ale bacha, ty odpovědi vůbec nejsou standardizovaný, někdy je to plaintext, jindy JSON, takže obecně tohle řešit moc nejde :-/

**Comment by ondrejhlavacek** [comment]
proč je potřeba zobrazovat refresh token v UI? aby ho uživatel vložil do jiného formu? můžem celou tu oauth odpověď injectnout do konfigurace docker appky při spouštění. refresh tlačítko v UI bejt může, ale zase jen uloží zašifrovanou odpověď, kterou si docker appka vyzvedne.

**Comment by Halama** [comment]
jdu nekam popsat jak to ted funguje, stravil jsem rozpletanim toho dopoledne. A pak by k tomu bylo dobry teda nacrtnout jak by mela vypadat ta spoluprace s komponentama.

**Comment by ondrejhlavacek** [comment]
@Halama jj, to flow je docela komplikovaný, možná bude lepší to nějak nakreslit, chceš na to sednout ve dvou?

**Comment by Halama** [comment]
Prosli jsme to tady v kanclu, najlos nahodi issue kde bude popsane jak se to bude resit na urovni docker-bundle a oauth bundle

**Comment by Halama** [comment]
https://github.com/keboola/oauth-bundle/issues/1

**Comment by JakubMatejka** [comment]
Chápu to dobře že se čeká až bude ten oauth bundle?

**Comment by Halama** [comment]
jj, ten uz je ted se ceka jeste podporu v docker bundle

**Comment by ondrejhlavacek** [comment]
Chtěl jsem to dělat přes PHP Clienta, ale ten k tomu novýmu neexistuje.
Můžu ho u toho vytvořit a nebo toho klienta nechat na Kachnu, co myslíte?

On Wed, Feb 3, 2016 at 8:06 AM, Martin Halamíček <notifications@github.com>
wrote:

> jj, ten uz je ted se ceka jeste podporu v docker bundle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/466#issuecomment-179054218>.
>



-- 
Ondrej Hlavacek
Developer, Keboola
+420 777 930 888
@keboola

**Comment by Halama** [comment]
@ondrejhlavacek Nechal bych to asi na kachnu. Ted bych dotahl ty notifikace.

**Comment by ondrejhlavacek** [comment]
aha, teď čtu, že to udělá, sorry! jsem neprošel slack :-) jak bude ten klient, můžu se do toho pustit

**Comment by JakubMatejka** [comment]
Má to nějaký ETA? @kachnitel

**Comment by kacurez** [comment]
zatvaram vid #495
