### ISSUE TITLE
Hide link to GoodData project in case it does not exist yet

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#468]
See https://github.com/keboola/gooddata-writer/issues/12

**Comment by Halama** [comment]
@JakubMatejka zkoumám podle čeho mám detekovat jestli se writer ještě připravuje a všiml jsem si u nového writeru tohodle:

![image](https://cloud.githubusercontent.com/assets/903531/13530273/e3a08548-e220-11e5-85a2-c812970f597e.png)

Čekal bych že `ready` bude až v moment kdy bude mít přiřazený projekt. Je to bug nebo feature? :)

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/gooddata-writer/commit/0282eb22964cc1f97195dca906dce56e10831611
