### ISSUE TITLE
credentials v redshift writeru

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#476]
Popis problému

Když vytvořím READ credentials (POST request na provisioning API), jsou u nich fixně uložený oprávnění ke schématům a tabulkám (neumí wildcard na tabulky ve schématu). Když writer do schématu zapíše tabulku, vygenerované READ credentials NEMAJÍ přístup k tý tabulce. Je potřeba poslat znova POST request pro READ credentials, aby se oprávnění refreshnula. 

Jestli se to udělá tak, že na stránce s credentials se budou pokaždé načítat z API nebo tam bude tlačítko refresh je celkem jedno.

![screen shot 2016-01-29 at 09 44 09](https://cloud.githubusercontent.com/assets/497675/12671063/8257158c-c66d-11e5-8b51-e0e1d16aaedd.png)

**Comment by kacurez** [comment]
Bol to bug(featura) ze ak GET read credentials vratilo kredence tak ich UI znova nevytvaralo(nevolalo POST read credentials)
Upravil som to tak ze v `Reset Credentials` u redshiftu furt vola POST read credentials.
Rozmyslal som ze nato pridam zvlast tlacitko(reload/ refresh credentials) ale prislo mi to matuce pretoze vo vysledku sa credentials nezmenia(zmenia sa len ich prava co sa na ui nezobrazuje).

**Comment by kacurez** [comment]
nakoniec sa to upravilo tak ze redshift writer vzdy zobrazuje write credentials tj nezobrazi readonly credentials ako to je u mysql napr.
Dovod je ten ze POST na read credentials sa musel zavolat az po loadu dat do db co sa neda trigrovat automaticky a z ux hladiska je to sptane
