### ISSUE TITLE
Form focus in keboola.ex-zendesk

### ISSUE THREAD

**Issue by kachnitel** [keboola/kbc-ui#487]
The form in any configuration in `keboola.ex-zendesk` repeatedly loses focus while editing a field.
https://connection.keboola.com/admin/projects/232/extractors/keboola.ex-zendesk
If I try to delete multiple characters using backspace, a few of them get deleted and after a few seconds the form loses focus so another backspace goes a step back in the browser.

**Comment by Halama** [comment]
tohle by mělo být fixnutý
