### ISSUE TITLE
wr-redshift: credentials provisioning for non redshift projects

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#490]
Redshift writer can not provide keboola provisioned redshift credentials if the project does not have redshift backend - should not give option and force user to only specify own redshift credentials.

**Comment by ErikZigo** [comment]
It si working :-/ But some tables in out bucket must exists.
Some descrition in UI while button is disabled would be fine

**Comment by kacurez** [comment]
fixed: user gets message saying that the project needs redshift backend to get keboola provisioned credentials.
