### ISSUE TITLE
Notifications ordering

### ISSUE THREAD

**Issue by milanveverka** [keboola/kbc-ui#492]
Show unread on top :)

Currently I don't think I even see all the unread stuff, because the page is full of read ones.

M.

**Comment by Halama** [comment]
yes it is a bug caused by migration notifications for  users in many projects. We'll fix it.

**Comment by milanveverka** [comment]
hey, this makes notifications pretty much useless... When I'm trying to keep up with the migrations etc. Just sayin'

**Comment by Halama** [comment]
we are aware of the issue and we are working on fix

**Comment by Halama** [comment]
It will be fixed by showing only unread notifications by default:
![image](https://cloud.githubusercontent.com/assets/903531/13668646/67eb0174-e6be-11e5-9803-8b6a7f94dacf.png)

**Comment by Halama** [comment]
I've deployed two bugfixes:
 - there was a bug when you entered project you received old notifications from project (this caused the mess in notifications). It is now fixed.
- mark all as read button now mark all notifications as read. Previously it marked as read only currently displayed notifications.
