### ISSUE TITLE
Transformation Input Mapping - data filter comma bug

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#493]
Jinak chci nahlasit ze mi nejde napsat carka v "Data filter" na vic hodnot. Nakopirovat jde.
![image](https://cloud.githubusercontent.com/assets/903531/13136848/3922ecbe-d61d-11e5-8bf6-6cf579eab047.png)

**Comment by odinuv** [comment]
Udelat to jako:
![clipboard01](https://cloud.githubusercontent.com/assets/4319320/13572126/d6d0fe2e-e478-11e5-82b8-97d9c1bf8709.png)

Vyresi se tim i to, aby sli zadat hodnoty jako `''`, `' '`, `' pokus'`, `'hokus '`, `'pokus, hokus'`

**Comment by ondrejhlavacek** [comment]
@odinuv jak tím vyřešíš prázdnou hodnotu?

**Comment by ondrejhlavacek** [comment]
fixnuto
