### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#5]
* not found pages
* errors during api communication
* JS errors - notify user, report to server, sourcemaps etc.

**Comment by Halama** [comment]
Handlování chyb by mělo být vyřešené. Uživateli se zobrazují jenom "uživatelské" chyby při interní chybě hláška ať reloadne browser a chyba se pošle na server. Testuju na to https://errorception.com/projects/54e3526a24f538015600008c/

Zendesk zatím funguje stejně jako ve starém. Po maintainerech to rozdělíme v další fázi.

**Comment by ondrejhlavacek** [comment]
Bylo by super do errorception dodat source maps (http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/).

**Comment by Halama** [comment]
Source maps tam jsou, ale jsou zatim asi nejaky drbly
![image](https://cloud.githubusercontent.com/assets/903531/6306774/9e4f7d5a-b936-11e4-8590-d06a01a44ee9.png)
Ztravil jsem tim ted asi 2 dny abych to zprovoznil ale uz to je snad blizko :)
