### ISSUE TITLE
Chybějící grafika

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#50]
- TAPI - detail transformace
- TAPI - editace transformace

**Comment by Halama** [comment]
Detail transformace
![image](https://cloud.githubusercontent.com/assets/903531/7153482/901b8a5e-e34c-11e4-8554-26a2e3392a6e.png)

**Comment by Halama** [comment]
Detail transformace
![screencapture-connection-keboola-com-admin-projects-155-transformations-bucket-sys-c-transformation-transformation-entries-1429080635077](https://cloud.githubusercontent.com/assets/903531/7153498/bacbfd42-e34c-11e4-98f2-26711d5df7d0.png)

**Comment by Halama** [comment]
Editace transformace
![screencapture-connection-keboola-com-admin-projects-155-transformations-bucket-sys-c-transformation-transformation-entries-1429080783782](https://cloud.githubusercontent.com/assets/903531/7153519/fa882e1a-e34c-11e4-844c-6bc3a78fdb16.png)

**Comment by JakubMatejka** [comment]
řek bych že cca hotovo
