### ISSUE TITLE
GoodData Writer - new writer

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#504]
![image](https://cloud.githubusercontent.com/assets/903531/13570083/6116d958-e46c-11e5-93dd-83654949b836.png)

Enable Access to project should be disabled when the writer is preparing.

![image](https://cloud.githubusercontent.com/assets/903531/13570098/788b5e06-e46c-11e5-962c-a06dd60990fd.png)

Writer should be also auto refreshed while in preparing state.

**Comment by ujovlado** [comment]
Stary writer.
