### ISSUE TITLE
OAuth credentials removed by saving config that was formerly empty

### ISSUE THREAD

**Issue by kachnitel** [keboola/kbc-ui#511]
When I create a config for OAuth enabled ex-generic component (keboola.ex-twitter), authorize the config and then edit the config data, the `authorization` object is lost from the config.
If I first edit the config, and then authorize, everything works well, **until** i edit the config data, then the auth. object is lost again.

**Comment by kacurez** [comment]
problem(+riesenie) ktory to sposobuje je popisany tu:
https://github.com/keboola/storage-api-php-client/issues/58

**Comment by kacurez** [comment]
Docasne riesenie autorizovat sa az po ulozeni konfigu(ako posledny krok konfiguracie) tj:
1. Ulozit nieco do konfigu, aby nebosahoval prazdny objekt napr `{"a": 1}`
2. Potom sa autorizovat

**Comment by ujovlado** [comment]
Stare
