### ISSUE TITLE
Loading table from `gmail-extractor` freezes the UI

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#512]
~~There is problem with some "characters" in `parts` table probably.~~

//cc: @pivnicek

**Comment by ujovlado** [comment]
Related to:
- https://github.com/keboola/storage-api-console/commit/559b1954760e936375ae04990771d98b817ecdeb
- https://github.com/keboola/storage-api-console/commit/44f61ee40495e4f34bd5044427a5eaf44b16170c

**Comment by ondrejhlavacek** [comment]
@ujovlado any chance to sniff the response in developers console?

**Comment by Halama** [comment]
marcuv fix https://github.com/keboola/storage-api-console/commit/44f61ee40495e4f34bd5044427a5eaf44b16170c

**Comment by ondrejhlavacek** [comment]
the UI might trim the cells before rendering (if it gets there)

**Comment by pivnicek** [comment]
So, setting a table attribute to let the ui know that a table will have a very large column (like email body) was one way too work around this.  Once components can decorate tables themselves, this may be a decent solution.

**Comment by ujovlado** [comment]
closing this, no longer an issue (note about clever data sample is already in productboard)
