### ISSUE TITLE
Wrong button label in Generic File Outputmapping

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#514]
![file-output-1](https://cloud.githubusercontent.com/assets/4319320/13829046/24454fb8-ebc5-11e5-9619-22ecf374ef56.png)

probably caused by this?
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/components/generic/FileOutputMappingHeader.coffee#L12

or this?
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/components/generic/FileOutputMappingDetail.coffee#L14

**Comment by ondrejhlavacek** [comment]
fixed by 0626e989dfc560ef560a62bca0328a12dd81dde3
