### ISSUE TITLE
GD Writer - Load: Incremental true days

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#515]
Nějaký UI glitch v GD Writeru. Nahoře v typu loadu to píše tu haluz zprávu _Load: Incremental **true** days._
Když jsem dal edit, tak byl zvolený increment a žádné číslo. Možná i to mohlo za nějaké problémy s uploadem do GD (byly nějaké tikety, kde jsme nedokázali najít důvod proč to je na piču). Takže možná další problém spojený s migrací.
![table out c-adwords stats 2016-03-17 13-07-35](https://cloud.githubusercontent.com/assets/12933713/13845832/c5b6bb8e-ec42-11e5-9387-097623bcb671.jpg)

**Comment by Halama** [comment]
díky za report. Vypadá to na bug writeru, fixneme.

**Comment by Halama** [comment]
https://github.com/keboola/gooddata-writer/issues/16

**Comment by Halama** [comment]
@Matejkys bugy (i podezření na bugy) prosím hlaš vždy na support ať nám to přijde do zendesku, tam to nezapadne a člověk který tam sedí se postará o co nejrychlejší debug a předání k fixu.

**Comment by Matejkys** [comment]
@Halama jo, sorry. Najloš říkal, že ideální bude GitHub. ale až když jsem to psal, došlo mi, že to možná bude bug a ne jen hloupost v UI. polepším se :)

**Comment by JakubMatejka** [comment]
Je to fixnutý, díky za report.
