### ISSUE TITLE
This project will expire in NaN days.

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#516]
Hi guys,

this is what I see on overview: 

<img width="494" alt="snimek obrazovky 2016-03-21 v 11 11 39" src="https://cloud.githubusercontent.com/assets/13956703/13910051/2e01db58-ef57-11e5-8211-08fbc5c6e8cf.png">

On the other hand, in settings I see everything all right.

Can you look at this? Thanks!

**Comment by padak** [comment]
what is your project number, please?
Padak


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by vokurka** [comment]
Problem is in all projects of the organization 51. For example: 912, 1125, 724

**Comment by janmichek** [comment]
@ujovlado tenhle task je tusim k uzavreni. Prosim over to a zavri
