### ISSUE TITLE
ex-db - primary key, oracle query hint

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#517]
![novaleasing_-_extractors___database___nova_step___query_i100_keb_smlouvy](https://cloud.githubusercontent.com/assets/497675/13920922/b8d710f4-ef75-11e5-8973-f3169a1b1fee.png)

upravit v novém i starém UI 

a) pro vstup PK použít komponentu /react/common/Select, která je použitá např v output mappingu transformací a zabraňuje nechtěné mezeře v PK (string se splituje podle mezery a už se netrimuje)

b) pouze pro oracle tam napsat, že query nesmí obsahovat středník na konci, jinak to vyfailuje

`Do not leave semicolon at the end of the query.`

**Comment by ErikZigo** [comment]
Mam to rozpracovany ve svoji branchi:
https://github.com/keboola/kbc-ui/tree/ex-db-pk-edit

Jediny s cim mam problem, jak premapovat data ze starych konfiguraci. Tam PK nebyl pole, ale string:-/
Jsem dohodly s @kacurez ze mi s tim zkusi pomoct.

**Comment by kacurez** [comment]
ak je v starych konfiguraciach novych ex-db v PK string tak extrakce nebude fungovat a vzdy vyfailuje. Opravil som to tak aby tam bolo vzdy pole, a ak je tam ulozeny string tak ukaze prazdny pk a bude treba resave konfigu. imo by sa to mohlo nasadit.

**Comment by kacurez** [comment]
stare ex-db by som nemenil pretoze tam je PK ako string a ajtak to planujeme deprekovat a zmigrovat stare konfigy do novych("dockerovych") konfigov

**Comment by ErikZigo** [comment]
Tak to se tyka jen toho noveho UI. Se starym bych nedelal nic.
Jestli si to vyresil takhle, tak je to imho v pohode. Porotoze kdo mel nastaveny PK, tak tomu stejne EX nefungoval. Slo jen o to vyresit, aby kvuli tomu nepadalo UI. Diky

**Comment by ErikZigo** [comment]
Koukam, ze uz to je nasazeny, tak to zaviram
