### ISSUE TITLE
Distinguish admin tokens in console

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#520]
![image](https://cloud.githubusercontent.com/assets/903531/13956268/59495204-f048-11e5-91b1-0a33e2445e96.png)

Mělo by být zřejmý že token je svázán  s adminem a jeho životnost je řízena životností admina v projektu.

**Comment by pivnicek** [comment]
Closing this as it should get covered by: https://github.com/keboola/kbc-ui/issues/1201
