### ISSUE TITLE
errorception

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#521]
vyhodit, nahradit třeba https://trackjs.com/, https://getsentry.com, https://raygun.com/products/crash-reporting, možná http://docs.honeybadger.io/lib/javascript.html (stačil by micro plan pro 1 appku)

**Comment by ujovlado** [comment]
je takych appiek hodne, nasiel som este napr. https://rollbar.com/ ... a myslim, ze keby sme si nainstalovali sentry u seba, tak to mame to for free :wink: https://github.com/getsentry/sentry

**Comment by ujovlado** [comment]
fixlo to sentry, zatvaram
