### ISSUE TITLE
Transformations - Cannot delete bucket with transformations

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#525]
![image](https://cloud.githubusercontent.com/assets/903531/14184228/7f1dfeac-f774-11e5-9b64-d13b22b5de8f.png)

@ondrejhlavacek to omezeni bylo jenom kvuli tomu ze to neumel storage ne?

**Comment by ondrejhlavacek** [comment]
@Halama jojo, to by šlo vyhodit! dík za postřeh
