### ISSUE TITLE
Table preview - event detail

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#527]
Nejde otevřít detail eventy, nevím tak např. jestli import byl inkrementální. 
![image](https://cloud.githubusercontent.com/assets/903531/14273597/208c8aca-fb0c-11e5-866c-f5ab97fec993.png)

**Comment by kacurez** [comment]
konkretne to ci bol import inkrementalny je naznacene priamo u eventu(v pripade ze bol inkrementalny import) vid obrazok:
![events](https://www.evernote.com/l/ADAX_LABCWFPpIK6KndaVQ83Gn5h_UvYfkYB/image.png)

**Comment by ujovlado** [comment]
Fixed by #1108
