### ISSUE TITLE
Align columns in orchestration tasks

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#530]
Ahoj,

minoritní věc, ale vypadalo by asi líp, kdyby byly fáze a časy v detailu orchestrace nějak zarovnané.
![job 181041439 2016-04-07 14-35-25](https://cloud.githubusercontent.com/assets/12933713/14351222/5b4fcffa-fcce-11e5-9843-9eb1530219e6.jpg)

M

**Comment by janmichek** [comment]
Ne zcela ultimatni, ale o mnoho lepsi .]
