### ISSUE TITLE
Job detail does not pull last events when the job finishes

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#533]
Když jsem na stránce s jobem a sleduju ho a skončí, tak tam dost často chybí poslední eventy. Reload stránky je načte. Pravděpodobně automatickej poller eventů skoční jakmile doběhne job, ale měl by se spustit ještě jednou.

**Comment by Halama** [comment]
tohle už jsem jednou tuším ladil, bude tam chtít dát ještě větší zpoždění v  pollování potom co job zkončí

**Comment by Halama** [comment]
mrknu na to
