### ISSUE TITLE
weird typo ligatures

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#534]
List of projects 

![your_projects___keboola_connection](https://cloud.githubusercontent.com/assets/497675/14457296/d8d09642-00a9-11e6-87a2-8ab60de109d3.png)

In project detail everything looks ok

![screen shot 2016-04-12 at 12 27 24](https://cloud.githubusercontent.com/assets/497675/14457313/f65c1af6-00a9-11e6-88d4-7b4bbf3009af.png)

**Comment by Halama** [comment]
nechápu :)

**Comment by Halama** [comment]
přijde mi že to vypadá ok

**Comment by ondrejhlavacek** [comment]
v tom searchi a seznamu je `ť` a `a` od sebe moc daleko, bude to nějaký nastavení fontu, někdy na to mrknu. `ťa`  má vypadat skoro stejně jako `ta`, bez zásadně větší mezery mezi písmenama

**Comment by janmichek** [comment]
Zda se ze to uzralo a opravilo se to samo xD zkousel jsem FF, Chrome i Safari (Win), vsude ok 

![untitled-3](https://cloud.githubusercontent.com/assets/15363559/25485210/5d09af46-2b5d-11e7-816d-1c1cf868ae78.png)

**Comment by ondrejhlavacek** [comment]
Teď jsem na to mrknul na Macu v Chromu a taky už ok! Vlado tuším nějak šermoval s fontama, tak se to fixlo?
