### ISSUE TITLE
sandbox: load data modal validation

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#535]
do not enable run button when no data is specified

![ondra_s_sandbox_-_transformations___sandbox](https://cloud.githubusercontent.com/assets/497675/14465968/404b2168-00d5-11e6-860f-fc53fb1f922b.png)

**Comment by natocTo** [comment]
Koukal jsem na issue různé a toto vypadá že není aktuální, nebo stále je?
Mysql Sanbox teda nevidím, tak nevím jak je to tam. U Snowflake je button disabled, když nevyberu data.

**Comment by janmichek** [comment]
Mysql backend jsme uz z kbc vykopali. Mozna tam budou jsete nejaky relikty v podobe sablon.
Checknul jsem loadovani Snowflake sandboxu, tam to validuje spravne.
