### ISSUE TITLE
[cosmetic] search icon alignment in extractor list

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#542]
Visible only when focused

![renderbug2](https://cloud.githubusercontent.com/assets/4319320/14535003/f4f0b19a-026b-11e6-8b27-07f55fb2f935.png)

**Comment by ondrejhlavacek** [comment]
když jí posunu, tak je sice trochu symetricky v tom focusovaným input elementu, ale zase nelícuje s tím spodkem? co myslíš?

![screen shot 2016-08-04 at 15 02 58](https://cloud.githubusercontent.com/assets/497675/17402657/a3245c90-5a54-11e6-9530-6c76d7f4f630.png)
![screen shot 2016-08-04 at 15 03 14](https://cloud.githubusercontent.com/assets/497675/17402658/a33e55fa-5a54-11e6-9f10-4bf4e37a0f7f.png)

**Comment by natocTo** [comment]
Kontroluji a toto již není aktuální. Zavírám.
