### ISSUE TITLE
[cosmetic] Notification email input size

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#543]
In Orchestrations - notification settings - edit

![renderbug](https://cloud.githubusercontent.com/assets/4319320/14535082/7a6a2978-026c-11e6-9279-e96ec3910dff.png)

**Comment by ondrejhlavacek** [comment]
Furt ti to vypadá tak chujovsky? Mám to takhle, hnusný, ale aspoň to tlačítko sedí na paddingu input elementu

![screen shot 2016-08-04 at 15 05 30](https://cloud.githubusercontent.com/assets/497675/17402728/ecff6ed6-5a54-11e6-9ecf-49862b4259cb.png)

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/kbc-ui/issues/2167
