### ISSUE TITLE
wr-db copy empty credentials bug

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#546]
copying empty credentials to clipboard reports 
`clipboard-action.js:62 Uncaught Error: Missing required attributes, use either "target" or "text"`

**Comment by natocTo** [comment]
Není již aktuální. Pokud nemám zadané credentials, je tam "nothing to copy", po zadání tam kopírování funguje, nebo pokud není nic zadaného není tam ikonky na kopírování ani zobrazená.
