### ISSUE TITLE
db-extractor-common: Encrypt password by default

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#554]
Dve male veci:
- myslim, ze by sme hesla mali sifrovat by default (ak nie, tak potom asi pridat support pre oboje)
- UI si mysli, ze nemam nastavene DB credentials, ked mam heslo ulozene sifrovane

Related to: https://github.com/keboola/db-extractor-common/issues/3

**Comment by kacurez** [comment]
treba to najprv urobit na backendu, s @MiroCillik sme sa otom bavili uz davnejsie ale este to neurobil:
https://keboola.slack.com/archives/db-extractor/p1458294606000009

**Comment by MiroCillik** [comment]
nj, este neurobil :) spravim

**Comment by ujovlado** [comment]
myslim, ze toto je done, zatvaram
