### ISSUE TITLE
Prehled orchestraci - prazdny sloupec Last Run

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#558]
Souvisi s timhle issue
https://github.com/keboola/orchestrator-bundle/issues/10

Nacita se tam "lastScheduledtime", ktery ale nezamena cas naposledy spustenyho jobu. Je to cas naposledy vytvorenyho jobu planovacem.
Lepsi bude do tohodle sloupce pouzit "lastExecutedJob.startTime"

**Comment by ErikZigo** [comment]
Koukal jsem do kodu, nacita se tam end time. Proto to je pri behu prazdny

**Comment by Halama** [comment]
nasazeno
