### ISSUE TITLE
ex-db-generic featuring ex-mongo

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#559]
braindump:
#### outputTable vs name:

ex-db-generic taha za sebou legacy workflow ked sme este nechavali uzivatela vybrat tabulku a jej bucket, 
mongo-ex uz ide po novom a nechava uzivatela zadat len meno query a z toho sa vygeñeruje prislusna tableId.
Ex-db pouziva **outputTable** a ui generuje ku kazdej query jej id(integer) - tu by stacilo pouzit outputTable ako id query a tym zamedzit ze sa 2 query ulozia do jednej tabulky
Ex-mongo pouziva iba query **name** a defaultBucket  takze user musi zadat meno query aby bolo tableId compliable(webalizovane) alebo sa webalizuje na backendu. 
UI musi vediet ake je tableId pre danu query(aby moholo referencovat na tabulku)
Problem: ako na ui rozlisovat jednoznacne query ak ex-db pouziva id(alebo outputTable) a ex-mongo iba name. Mozno riesenie asi pouzit iba `id` query aj pre ex-mongo a pre mongo nezobrazovat outputTable text input a urobit custom text input pre name. 
#### query:

ex-db pouziva obycajny string
ex-mongo pouziva javascriptovy object(nie JSON) a dalsie polia pre specifikovanie fieldov(same as pk),  limit(text input)
problem: ako to popisat/rozlisovat. Mozne riesenie - custom query detail.
#### inkremental / primaryKey:

ex-db dava moznost zadat primary key/inkremental pre kazdu query.
ex-mongo ma by default pre kazdy dokument interne id co by sa natvrdo dalo pouzit ako pk a vzdy nastavit inkremental=true. 
Problem: Ako to odkomunikovat na ui: by default nastavit id a inkremental ale nechat uzivatelovi moznost to vypnut.
#### credentials:

tu je to cele rovnake vcetne ssh tunelu akoze no problem.

**Comment by ujovlado** [comment]
@kacurez ja to chapem takto (len pre istotu, nech potom neriesime, ze je to inak :wink: )

**`outputTable` vs `name`**

- bavili sme sa, ze `id` je vlastne zbytocna vec a ak by sa na identifikaciu query dalo pouzit `outputTable` bolo by to fajn. Avsak do UI by sa muselo dorobit, ze zadanie `outputTable` bude unikatne -> t.j. nezadas 2x to iste `outputTable`
- mongoex nepouziva `outputTable` ale `name` + default bucket (cize v UI by som si "skopcil" funkcionalitu unikatnosti `outputTable` a aplikoval ju na `name` (riesenim ale moze byt aj to, ze `name` premenujem na `outputTable`, uvidim)

**`query`**

- tu problem nevidim, mongoex stejne bude pridavat dalsie fieldy, cize to bude musiet byt "custom query detail":
  - `collection`: obyc. input
  - `query`: "mongo json" textarea (+ asi codemirror)
  - `sort`: "mongo json" textarea (+ asi codemirror)
  - `limit`: obycajny input
  - `fields`: obycajny input na vymenovanie fields (alebo podobny "input na polia" ako je pri PK)

**incremental, PK**

- kedze vo vacsine pripadov existuje `_id` field, nastavili by sme defaultne PK na `_id` a `incremental: true`  (v UI by to znamenalo vyplneny "array input" PK s jednou polozkou `_id` + zaskrtnuty checkbox incremental)

Takze na ex-db-generic asi treba poriesit len tu "unikatnost", zvysok je myslim cajk a budem to musiet napasovat v mongoex.

**Comment by kacurez** [comment]
@ujovlado dik za refinement ja som to pisal dost zhruba ala hemingway mode:)
  k **`outputTable` vs `name`**
Mal som problem s jednoznacnym identifikovanim query, u ex-db je to prave `id` a u ex-mongo `name` a tak ma napadlo to zjednotit a nechat `id` aj pre mongo lebo inac by sa to dost skomplikovalo, raz rozlisovat `name` a druhykrat `outputTable` by bol dost brainfuck. Ale ked si spomenul ze by si `name` premenoval na `outputTable` tak by to slo tj furt pouzit len `outputTable` ajked v pripade mongo by to bol zwebalizovany nazov tabulky, a v ex-db by to bolo cele tableId.

**Comment by kacurez** [comment]
@ujovlado upravil som ui aby pouzivalo outputTable namiesto id query, je to zatial bokom v tomto branchi, mozes nato nadzviazat s upravami pre ex-mongo
https://github.com/keboola/kbc-ui/tree/ex-db-mongo

Obavam sa ze vyhybka pre mongo v suvislosti s pouzitim len `outputTable`(bez `name`) bude dost velky brainfuck nakodit, ze by som odporucil pouzit oba parametre nakoniec.
