### ISSUE TITLE
Missing "back to template selection" button

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#560]
Všiml jsem si toho u FlexiBee extractoru.
Pod accountem, loginem a heslem si můžu vybrat template. Vpravo vidím tlačitko "switch to JSON config", abych se dostal k manuální editaci. Zvědavě jsem na něj kliknul bez výběru template a přehodil omě to do tuční editace. Jenže teď už není cesty zpět k výběru template. Jedinou možnotí je dát cancel a pak znovu edit config.
![keboola ex-flexibee - keboola czech 2016-05-03 13-45-58](https://cloud.githubusercontent.com/assets/12933713/14982437/8decf29a-1136-11e6-951a-d3953db66660.jpg)

**Comment by ondrejhlavacek** [comment]
Jo, tak to je, protože tě nemám vrátit do jaký šablony, když tam nejsou žádný data (= jsou to data, který nejsou v žádný šabloně). Uznávám, že je to nešikovný, ale líp to teďka neumím :-(.

**Comment by Matejkys** [comment]
No ale na začátku jsem taky mimo šablonu. Do toho "momentu" mě to vrátit nemůže?
![keboola ex-flexibee - keboola czech 2016-05-03 15-32-01](https://cloud.githubusercontent.com/assets/12933713/14984680/36fc6fb6-1144-11e6-92e1-fe5135d395d5.jpg)

**Comment by ondrejhlavacek** [comment]
Zejtra na tom budu něco dělat, pokusím se to vymyslet!

On Tue, May 3, 2016 at 3:32 PM, Matejkys <notifications@github.com> wrote:

> No ale na začátku jsem taky mimo šablonu. Do toho "momentu" mě to vrátit
> nemůže?
> [image: keboola ex-flexibee - keboola czech 2016-05-03 15-32-01]
> <https://cloud.githubusercontent.com/assets/12933713/14984680/36fc6fb6-1144-11e6-92e1-fe5135d395d5.jpg>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/kbc-ui/issues/560#issuecomment-216528455>
>



-- 
Ondrej Hlavacek
Developer, Keboola
+420 777 930 888
@keboola

**Comment by ujovlado** [comment]
Stare
