### ISSUE TITLE
nlp geneea ux bugs

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#565]
1. kdyz nastavis dataColumn = text a soucasne primaryKey = text tak by to asi nemelo dovolit, ale aspon by to melo napsat rozmnou chybu.
2. do 'Output Table Prefix' se da zadat neco jako `out.c.biggus.dickus.` coz vede k chybe Output source 'out.c.biggus.dickus.hashtags' does not seem to be a valid table identifier, either set output-mapping for table stored in 'out.c.biggus.dickus.hashtags.csv' or make sure that the file name is a valid storage table identifier. Protoze to ma prilis mnoho tecek

**Comment by ujovlado** [comment]
stara vec ... napr. output table tam uz ani nemame.
