### ISSUE TITLE
 ex-google-analyitcs-v4 review

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#568]
Nove ui google analytics v4, podporuje:
- oauth-v2 offline pre autorizaciu google accountu
- vyber google analytics profilov cez google api js knihovnu(vyzaduje temp autorizaciu)
- prednacitane info o metrikach a dimenziach z google public api

zber failov, ux failov, chybajuce pixely ale aj napady na zlepsenie piste do komentov.

**Comment by padak** [comment]
Poznámky:

### externí autorizace
 1. do externí autorizace bych chtěl dopsat poznámku, kterou uvidí ten kdo bude pro mě dělat autorizaci (někde kolem https://cloudup.com/ckZxyKH-jtu)
 1. při samotné autorizaci třetí osobou (via externí link) tam zase leze popup s "Authorize For" (https://cloudup.com/c-_v31j_mLf)
 1. autorizující nemůže vybrat profily - to je blbě, hodí nám to na hlavu, musí mít třetí strana kontrolu nad tím co nám dávají
 1. navíc já pak musím v KBC zvolit profil, ale nemám k němu právo!

### query builder

 1. možnost vybrat dst tabulku? (přepsat bucket? pokud ne, tak tam nepiš to jméno kam to přijde)
 1. při výběru metrik a dimenzí zobrazovat víc jak tři našeptání (https://cloudup.com/cs5RYTcUbGY)
 1. k Filters Expressions bych dal nějakej otazník s příkladem, odkazem na help.keboola.com, apod.
 1. **date ranges** by mohly nabízet pár příkladů (poslední týden, poslední měsíc, apod.) který když vybereš, tak to tam nasypou + mít date picker, aby bylo jasný v jakým formátu tam má datum bejt
 1. schází mi tam práce s state{} - abych prostě řekl pro init load za jaký období stáhnout data a pak to jelo jen to co schází - nechci dělat 3x denně "-7 days ago" a zároveň pokud to nejede, tak nemyslet na to jakou tam mám díru, co ty na to?

**Comment by kacurez** [comment]
#### ad externa autorizace:

**`1.`**(Externa poznamka): good point! neni nato priama podpora backendu(oauth-v2) ale slo by to cez description sapi temp tokenu ktory sa tam generuje. 
**`2.`**: jasne
**`3. a 4.`**(Externy vyber profilov):
otom viem, napadaju ma 2 mozne riesenia:
- Riesenie 1: autorizujici(dalej len Eva) povoli spracovi kbc konfigu(dalej len Adam) profily(cez nastavenia google analytics) ktore potom Adam dodatocne po autorizacii prida v konfigu(Setup Profiles) cez svoj google ucet.
- Riesenie 2: upravi sa externa autorizacna apka tak aby umoznovala Eve okrem autorizacie vybrat svoje profily. 
btw uplne rovnaky problem bude u google drive extraktoru(by sa to riesenie mohlo zjednotit).

#### add **query builder**
**`1.`**(menit dst table) Chceme minimalizovat moznost userom menit dst tabulku: imho user by sa nemal starat oto kam to pride ale zaroven by mal vediet kde to najde, beriem to ako pripravu prostredia na metadata - taka prenatalna faza metadat :). Este som zvazoval ze tu moznost uplne zakazeme, menit meno tabulky mi zatial pride ako dobry kompromis.
**`2. - 4.`** jasne
**`5.`** vyuzit `state{}` na dotahavnie dat je super napad! budem to konzultovat s @MiroCillik 
**`6`** sample dat tam urcite chceme mat a nic tomu neprekaza. S @MiroCillik sme sa uz otom bavili. Ak sa to do public releasu nestihne tak docasne tam mozme nalinkovat ten query exlorer.

**Comment by padak** [comment]
Super! Řešení 2 se mi líbí asi víc

**Comment by MiroCillik** [comment]
@kacurez Este ti tam chyba vypis jobov a mohol by si pridat "segments"? Bude to pole:

```
{
   ...
    "segments": [{
        "segmentId": "gaid::-5"
    }]
}
```

To *gaid::-5* je nejake id segmentu a moze ich byt viac.

**Comment by MiroCillik** [comment]
Tomas, este par drobnosti by som v tom UI zmenil:

- namiesto `Account authorized for miro@keboola.com` by som dal len `Authorized for miro@keboola.com`

- namiesto `Available Profiles` by som dal `Registered profiles` (je to zoznam uz vybranych profilov, nie zoznam dostupnych profili, z ktorych by mohol vyberat)

- a na screene je ste vyznaceny ten chybajuci zoznam jobov

![syrup_-_extractors___google_analytics_v4___migration-test-2](https://cloud.githubusercontent.com/assets/1488015/16839208/284769cc-49ce-11e6-857a-f3e8a807e455.png)

**Comment by kacurez** [comment]
### komenty od @ondrejhlavacek 

**`1.`**  rozsypane ako lego:
![image](https://cloud.githubusercontent.com/assets/1412120/17626384/6776f3b0-60ad-11e6-9da0-526669d6d608.png)
https://keboola.slack.com/archives/general/p1471004625000073

**`2.`** když se přepnu tabem mezi inputy datepickeru
![image](https://cloud.githubusercontent.com/assets/1412120/17626460/9fff78ce-60ad-11e6-92ca-9d56c2bb3912.png)

**`3.`** male pismo u date range modalu
![image](https://cloud.githubusercontent.com/assets/1412120/17626487/b9020288-60ad-11e6-8a05-2a0b0247f9f4.png)
https://keboola.slack.com/archives/general/p1471005174000077

**`4.`** - date picker otvoreny by default
https://keboola.slack.com/archives/general/p1471005107000076

**Comment by kacurez** [comment]
tu to zatvorim, ked tak sa urobi novy zber ux issues k google analytics ex ui
