### ISSUE TITLE
[wrgd] updates to create writer modal

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#574]
1. Rename section "GoodData Access token" to "Auth token"
2. Instead of passing real tokens to parameter `authToken` use placeholders `keboola_production` and `keboola_demo`
3. Section for setting up custom domain should be added, see the screenshot. 
  - This form could be hidden by default
  - It is usable for both, creating of new project and using existing one
  - Domain name, login and password are required
4. Using of existing project so does not need inputs username and password and should contain checkbox for filling configuration from project model (on by default)

See API docs for exact parameter names: 
- http://docs.keboolagooddatawriterv2.apiary.io/#reference/writers/writers/create-writer-with-empty-project
- http://docs.keboolagooddatawriterv2.apiary.io/#reference/writers/writers/create-writer-from-existing-project

![_dev__jakub_-_writers___gooddata](https://cloud.githubusercontent.com/assets/215660/15315390/97f9715a-1c17-11e6-9a0b-b716f836b78a.jpg)

**Comment by JakubMatejka** [comment]
Akorát moc nevím jak si poradit s tím loginem a heslem, teď je na tom screenshotu vlastně dvakrát. Pokud zakládáš writer z existujícího projektu, musíš zadat jméno a heslo admina co do něj má přístup. Pokud je ale projekt v custom doméně, tak musíš (místo toho) zadat jméno a heslo doménovýho admina.

Možná dát k nadpisu custom domain přepínač (který současně zobrazí ten formulář, jinak je skrytý) a při jeho zapnutí se disablují ty inputy na jméno a heslo? Takhle nějak? (v tom případě bych ale asi prohodil pořadí těch inputů a pid dal jako první)

<img width="614" alt="screenshot_17_05_16_10_23" src="https://cloud.githubusercontent.com/assets/215660/15315693/76a260f0-1c19-11e6-83a5-9d917dbac56b.png">

**Comment by kacurez** [comment]
@JakubMatejka : dotaz k **`2.`**: plati to aj pre custom user tokeny ze sa maju predavat do `authToken ` property?

**Comment by JakubMatejka** [comment]
jj. to je ten samý parametr, jen v něm Writer kontroluje, jestli náhodou neobsahuje placeholder ze slovníku a ten pak případně přeloží

**Comment by kacurez** [comment]
done in https://github.com/keboola/kbc-ui/pull/580
