### ISSUE TITLE
[wrgd] bug on writer's removal

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#575]
Ui deletes configuration from SAPI upon writer's removal which causes malfunction of the Writer (Removal is asynchronous and so it tries to read the configuration which does not exist any more. Mostly it is not a problem but in situation of writers with custom domain Writer needs to read some additional data from the configuration to be able to delete the writer). 

Possible solution is to call delete of the writer and wait for it's finish instead of deleting the configuration from SAPI directly.

**Comment by kacurez** [comment]
na ui sa neda zabezpecit aby sa config zmazal potom co dobenhne remove writer async call. 
Jedine co ma napada je do toho remove writer callu zkopirovat aktualny konfig(do tela delete requestu) a inak nic nemenit, je to ok?

**Comment by JakubMatejka** [comment]
No mně šlo spíš o to, že by to ui mazat nemělo vůbec. To by šlo? Writer tu konfiguraci smaže sám na konci toho async tasku.

**Comment by kacurez** [comment]
ak user ostane na tej stranke writeru alebo sa na nu stihne vratit tak to bude problem ked ju nacita a spadne mu to, nebude to v konzistentnom stave(race conditions..)
mohol by sa zadisablovat pristup cez flag v konfigu(napr `scheduledToRemove: true`) ale pride mi to riesenie trocha zlozitejsie

**Comment by JakubMatejka** [comment]
Hm, to jo. No mně se moc nechce předávat do parametrů jobu heslo toho doménovýho admina. Ale asi to teda bude nejlepší řešení.

**Comment by ujovlado** [comment]
Stary writer. V novom sa maze uz inak.
