### ISSUE TITLE
ex-db-generic: Can't edit credentials (user, database, IP, etc.) without knowing password

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#582]
Nemozem editovat udaje o pripojeni, pokial nepoznam heslo.

Malo by to myslim fungovat tak, ze v inpute na heslo, sa to heslo objavi zasifrovane.

**Comment by kacurez** [comment]
otazka je ci ma zmysel ukazovat to zasifrovane heslo. Ja som myslel ze by sa to dalo zmenit akokeby v jednom kroku naviac, ze klik na protected ikonku -> zobrazi sa modal s prazdnym inputom -> user zada nove heslo, inak to vzdy posle to posledne zasifrovane co tam ma.

**Comment by ujovlado** [comment]
@kacurez to ze to posle posledne zasifrovane, co tam ma, je myslim ok
