### ISSUE TITLE
ex-db-generic: readonly bucketId of outputtable

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#586]
user neriesi bucketId pre outputTable, mal by zadat iba meno query a moznost updatovat meno tabulky

**Comment by ondrejhlavacek** [comment]
@kacurez tohle by měl řešit defaultBucket

**Comment by ujovlado** [comment]
Toto je fixed. Pri manualnom pridavani query sa destination generuje automaticky, potom to user moze zmenit.
