### ISSUE TITLE
Transformation: query editor mismatched quotes

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#588]
Missing a closing ' will mess with the editor and it will store strange values.

Maybe it should produce a syntax error warning for this case?

**Comment by ondrejhlavacek** [comment]
@pivnicek managed to reproduce the issue

the queries string is split into separate queries using this regexp - https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/transformations/utils/parseQueries.js#L10

i'll try to make a validation using the same regexp and if it's not valid, disable saving. linter for sql is not available in codemirror (it is available for JSON and we're using it)

if this fails, I'll stop splitting the queries and will let the backend do it (that will probably fail somehow too)

**Comment by ondrejhlavacek** [comment]
stupid thing is, that the query with unmatched single quotes is partially deleted when split

**Comment by pivnicek** [comment]
yeah.  the partial deletion of the query was what triggered the error report.

omg @ that regexp btw

**Comment by ondrejhlavacek** [comment]
If you have any other idea how to split a chunk of sql code into separate
queries I'm all ears! Regexp sucks.

**Comment by pivnicek** [comment]
Not really without separate inputs or force introducing some sep comments standard or something.  I think that regexp works pretty amazingly well, all things considered.

**Comment by pivnicek** [comment]
maybe we can use the fact that it partially deletes the unmatched ' query as a weapon in defense here.

We could maybe validate a the original string against the re-joined splitted queries?

**Comment by ondrejhlavacek** [comment]
That was my battle plan. Not sure if we're doing it right at all though :-)
but multiple query windows is a no go. I wonder how others do it...

**Comment by ondrejhlavacek** [comment]
okay, gave it a try!
fixed by 49178aa4b5e1cc3a42d182a749d877892ee73991

**Comment by pivnicek** [comment]
nice one!
