### ISSUE TITLE
bug v info o expiraci projektu

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#599]
https://www.evernote.com/shard/s32/sh/08230af1-7848-4a3d-a936-fbbef33f17bd/fa0b89e7665d50fe/res/c20e86c5-7ec5-45ca-8164-e48f4b16e1e4/skitch.png?resizeSmall&width=832

Reportoval Milan v https://connection.keboola.com/admin/projects/1199. Nepodařilo se mi to ale nasimulovat, teď tam vidím "10"

**Comment by ujovlado** [comment]
Islo pravdepodobne o zle nastavenu exspiraciu - nieco ako `0000-00-00 00:00:00`.

Kontroloval som to, exspiracia sa myslim uz vsade riesi spravne, nemalo by sa to opakovat.

**Comment by ujovlado** [comment]
Anyway, duplicate of #516
