### ISSUE TITLE
Bold table name in Delete column dialogue

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#607]
Ahoj,

bylo by fajn, kdyby při mazání sloupce ve Storage byl jeho název tučně, aby uživatel hned věděl, že maže opravdu ten správný sloupec.
![bata - multichannel - storage keboola connection 2016-07-08 10-08-22](https://cloud.githubusercontent.com/assets/12933713/16681393/b46192d6-44f4-11e6-9ad9-a5a908789c9c.jpg)

**Comment by ujovlado** [comment]
Myslim, ze toto fixol novy font. Kazdopadne, uz je to fixed.
