### ISSUE TITLE
DB extractor SSH tunel without keys

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#611]
Asi by to mohlo pro rozkliknuti SSH hned vygenerovat credentials a aktivovat test credentials jenom kdyz jsou vygenerovane? Tahle hlaska je jinak trochu matouci

![image](https://cloud.githubusercontent.com/assets/903531/16868989/e81c1250-4a7a-11e6-9a7c-c081b6cabd5e.png)

**Comment by ujovlado** [comment]
Toto uz funguje ako popisujes - t.j. pokial mam povoleny ssh tunnel a nemam vsetko vyplnene, nemozem dat Test Credentials (ani Save)
