### ISSUE TITLE
generic ui mapping destination overflow

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#614]
![image](https://cloud.githubusercontent.com/assets/1412120/17023240/a9754a3a-4f52-11e6-97bb-52ff58ae5db8.png)

**Comment by ujovlado** [comment]
Duplicate of #882

**Comment by ondrejhlavacek** [comment]
To není duplikát, jsou to dvě jiný UI komponenty

**Comment by ujovlado** [comment]
bug je rovnaky, fix by to mal poriesit vsade
