### ISSUE TITLE
URLs in Transformation grahps

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#619]
Posílá se tam `name` místo `id`

Napr:
https://connection.keboola.com/admin/projects/578/storage#/tables/in.c-afnhk.diagnozy

generuje v grafu
https://connection.keboola.com/admin/projects/578/transformations/bucket/Test/transformation/1
misto
https://connection.keboola.com/admin/projects/578/transformations/bucket/2/transformation/1

a

https://connection.keboola.com/admin/projects/578/transformations/bucket/fnhk/transformation/fnhk---pouzite-diagnozy
misto
https://connection.keboola.com/admin/projects/578/transformations/bucket/sys.c-tr-fnhk/transformation/fnhk---pouzite-diagnozy

**Comment by ondrejhlavacek** [comment]
fixed by https://github.com/keboola/transformation-bundle/commit/4c9fae091ae0c0dbc0b5ab2fdc842b3270a95089
