### ISSUE TITLE
Table lists not updating

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#622]
- udelej novou tabulku pomoci transformace
- prejdi do konfigurace writeru - neni tam videt
http://youtu.be/qxRjjYXO96Q?hd=1

- kdyz se tabulka vytvori pomoci storage console, tak je videt hned

**Comment by ondrejhlavacek** [comment]
fixed by e4de19a8c37f2793dc30b9722200b4553b347f50
