### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#627]
autoRemove flag was removed as it didn't work at all

setting timeout to 9999 is the only viable way to keep the notification open, but until you mouseover it, then it disappears in 10 secods

**Comment by Halama** [comment]
vsechny notifikace by mely mizet co vim

**Comment by Halama** [comment]
takze jestli tam byl autoRemove flag tak se jenom zapomnel smazat, fungovat urcite nemel :)

**Comment by ondrejhlavacek** [comment]
No když uploadujes 1GB soubor, tak to máš někde na pozadí a ta notifikace
zmizí než jí stihneš zaregistrovat. Do jobu to rozumně dát nejde - tam by
šel dát až load do Storage. Notifikace mi přišly vhodný, tak by to měl bejt
spíš nějakej samoststnej element na stránce?

**Comment by Halama** [comment]
nahodit ty browser notifikace?

**Comment by Halama** [comment]
tim ze to nestihnes postrehnout si myslel ze si mezitm v jinem tabu treba a ono probehne kdyz neni aktivni?

**Comment by ondrejhlavacek** [comment]
Jj, nebo prostě jdeš pryč, protože na to čekáš a trvá to,  není tam
feedback v podobě toho jobu.

**Comment by Halama** [comment]
jo rozumim tak v takovem pripade by asi davalo smysl aby tam zustala
