### ISSUE TITLE
Missing last runs in FB Ads ex

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#629]
I když běhá FB Ads ex pravidelně, v UI nejsou vidět poslední joby (pravděpodobněve všech projektech)
![fb extractor 2016-08-10 14-42-29](https://cloud.githubusercontent.com/assets/12933713/17553935/b73a99d4-5f08-11e6-976c-99584b24e9b2.jpg)

**Comment by ondrejhlavacek** [comment]
Ahoj, je to stará komponenta, už si nezaslouží fixování, lepší bude věnovat energii přepisu do genericu. WONTFIX, sorry!
