### ISSUE TITLE
tapi ui - bug editace R

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#63]
https://errorception.com/projects/54e3526a24f538015600008c/errors/5554f97f82151582d4156c3c

Chtěl jsem to fixnout ui ale imho je to věc backendu, u R transformací co jsem z toho pochopil by to mělo vracet `packages`  a mozna nejaky dalsi veci.

![image](https://cloud.githubusercontent.com/assets/903531/7648537/5160f858-fae4-11e4-81ce-f5a6c23f86fe.png)

**Comment by ondrejhlavacek** [comment]
opraveno
