### ISSUE TITLE
sync transformation most up-to-date config

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#632]
problem: ked user preklikava  v konfigu transformace(dalo by sa to zobecnit na vsetky komponenty) tak by mal vidiet jeho co najviac up-to-date stav.
riesenie:  vzdy forcenut load configu na pozadi zmeny routy podobne ako tu:
https://github.com/keboola/kbc-ui/commit/e4de19a8c37f2793dc30b9722200b4553b347f50

**Comment by ondrejhlavacek** [comment]
super nápad!!!

**Comment by kacurez** [comment]
fixnute v
https://github.com/keboola/kbc-ui/commit/1d352e31da907d4f04287e45e520f5b00265699c

**Comment by ondrejhlavacek** [comment]
Zůstal ti tam console.log :-)

**Comment by kacurez** [comment]
jj uz som to precistil ;)
