### ISSUE TITLE
[input mapping] days filter warning with empty value

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#633]
![screen shot 2016-08-16 at 11 34 31](https://cloud.githubusercontent.com/assets/497675/17694711/78c0cc04-63a5-11e6-805b-2bcb2daacc4e.png)

**Comment by natocTo** [comment]
Nevidím tam ani "days filter" v aktuální verzi. Možné je místo toho ten selectbox. 
Každopádně issue se asi čase vyřešilo.
