### ISSUE TITLE
[firefox] renaming phases

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#637]
Dobrý den, narazila jsem na chybku, že v prohlížeči Firefox nelze editovat název fáze při editování tasků pro Orchestraci. 

A zároveň jsme si všimla, že u Chrome to tlačítko „Rename phase“ vyjede vedle tužky, kdežto v tom Firefoxu překryje tužku a v tom asi bude ten problém, že na to nejde kliknout. Zkoušela jsem i na velkém monitoru, abych vyloučila, že je to způsobené zobrazením na mém ultrabooku.

**Comment by kacurez** [comment]
hmm mne to funguje(osx firefox 48):
![image](https://cloud.githubusercontent.com/assets/1412120/17769895/36fa5898-653b-11e6-94a3-8d2d49666434.png)
![image](https://cloud.githubusercontent.com/assets/1412120/17769927/5e8b2194-653b-11e6-9eaf-313c456c89d1.png)

by bolo dobre to otestovat na windowsoch

**Comment by janmichek** [comment]
Zkousim to na W10, FF53 a vse se chova dle ocekavani. Pokud si nikdo jiny nestezoval, navrhuju uzavrit @ondrejhlavacek

**Comment by ondrejhlavacek** [comment]
Souhlas, fáze stejně budou mizet :-) Uzavírám.
