### ISSUE TITLE
[firefox] [ex-google-analytics] - emptying datepicker

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#640]
když vyprázdním datepicker v google analytics extraktoru ve firefoxu, tak hodí do konzole chybu
v chromu se to neděje

![screen_shot_2016-08-19_at_14_41_45__2_](https://cloud.githubusercontent.com/assets/497675/17810119/60593e6c-661b-11e6-8428-413116bc4a87.png)

https://app.getsentry.com/keboola/keboola-connection-ui/issues/151206699/

**Comment by kacurez** [comment]
nedari sa mi to fixnut - imo to je bug datepicker npm knihovny, z jej zdrojakov:
```
handleChange: function(event) {
    var date = moment(event.target.value, this.props.dateFormat, true);
    this.setState({
      value: event.target.value
    });
...
```
Tu zrejme firefox posle null event namiesto prazdneho stringu v event.target.value.
Vsimol som si ze datepicker aj po zalogovani erroru je stale pouzitelny.
Mozno by pomohol update na novy react a tym update na novy picker..

**Comment by ondrejhlavacek** [comment]
jj, je to použitelný a je to firefox, takže lowprio, dík! :-)
