### ISSUE TITLE
git pre-commit hook

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#646]
lint odstranit a dát do watche

**Comment by ondrejhlavacek** [comment]
zatím jsem odstranil pre-commit hook a nechal to jen na travisu
upravil jsem no-console eslint rule na error

coffeescript se v travisu vůbec nekontroluje, zatím to nechávám být

**Comment by ondrejhlavacek** [comment]
kbc-ui používá https://github.com/lewie9021/coffeelint-loader kterej je zafixovanej na 1.9.* verzi coffeelintu, ve které není možné kontrolovat `console.log` pomocí `no_debugger` (jde to až o verzi později - http://www.coffeelint.org/#changelog)

**Comment by ujovlado** [comment]
vyhodil som to uplne https://github.com/keboola/kbc-ui/pull/647, az to zbehne mergnem to
