### ISSUE TITLE
Create new writer - page not found

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#659]
![image](https://cloud.githubusercontent.com/assets/903531/18590156/1674c6f8-7c2e-11e6-94a4-f8291220ef44.png)

Redirect pro založení writeru občas skočí na not found page, jindy ale funguje. Musí fungovat vždy :)

**Comment by kacurez** [comment]
problem je vtom ze vytvorenie gd writeru je asynchronny job - UI v domneni ze vola sync call create config tak vola POST na gooddata-writer/v2 co vrati 202 a az v naslednom async jobe sa konfig vytvori cez components api(ak este eneexistuje). UI obecne pri kazdej komponente po create config calle presmeruje na novovytvoreny konfig co v pripade gooddata writeru spadne pretoze este na components api neni vytvoreny. 
Problem vznikol po tejto uprave https://github.com/keboola/kbc-ui/commit/e69f5c46c27a319d7ffc7a9fa7a856afe26089a2
Predtym sa vzdy po POST na gooddata-writer/v2 volal create config na components api s rovnakym id vygenerovanym na ui.
Mozna oprava je vytvorit config na components api a az potom volat create gd writer api tj
POST components/configs -> POST gooddata-writer/v2

**Comment by Halama** [comment]
aha, už to vidím jak to fixnout. Té speciální cesty pro gooddata writer jsem si předtím vůbec nevšiml
