### ISSUE TITLE
Stats for new projects from their creation time

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#672]
For new projects use "project creation time" instead of default 17.8. (date from stats are available)
(low priority)

**Comment by ujovlado** [comment]
Tvl, toto som zalozil ako riadny pacient.

Tyka sa to ten tabulky, co je vpravo hore na stranke "Project Power" (vid. screenshot).

![screenshot_2017-01-30_11-10-52](https://cloud.githubusercontent.com/assets/419849/22419253/e2dc2402-e6dc-11e6-9c2e-88aaf973a03f.png)

**Comment by janmichek** [comment]
@ujovlado Tomu nerozumim, ten popis neodpovida screenshotu. Nikde nevidim 17.8.
Muj projekt je pomerne novy a taky nikde nevidim 17.8. Vse vypada dle ocekavani.
Jestli me neco sere, tak to jsou ruzny formaty data napric aplikaci xD

![untitled-2](https://cloud.githubusercontent.com/assets/15363559/25441442/8a89a2b6-2aa2-11e7-9fbc-fae9387e90b0.png)

**Comment by ujovlado** [comment]
Tam islo o to, aby tam neboli tie spodne prazdne riadky:
> For new projects use "project creation time" instead of default
