### ISSUE TITLE
Redshift WR provisioned credentials - copy password

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#676]
V případě použití "Keboola provided database credentials" nejde zkopírovat heslo, API ho ale vrací.

![image](https://cloud.githubusercontent.com/assets/903531/19036168/60028f60-896e-11e6-9580-55890f3fd540.png)

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/commit/25a292cc91ce1023fbde2697f0358e5d996684d9
