### ISSUE TITLE
blbej čas u autorizace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#677]
Ahoj,

Twitter ex ma nejakej problem s casovejma zonama. Kdyz jsem zridil novou konfiguraci, tak tvrdi ze prej ji udelam az za devet hodin (rozdil mezi CET a PST): https://www.evernote.com/l/ACDZJbeDbtVCe57E8ttHFlKkCVuyA70SqGA

Díky,
Padak

**Comment by padak** [comment]
(originálně je to nahlášený tady https://keboola.zendesk.com/agent/tickets/5527)

**Comment by ujovlado** [comment]
Toto bude asi na oauth.

**Comment by ujovlado** [comment]
Duplicate of #550
