### ISSUE TITLE
Keboola ikonka u userů

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#682]
Matůš má Keboola ikonku u svýho jména - to bych asi dal pryč. Mate to.
![image](https://cloud.githubusercontent.com/assets/1427901/19195436/f308fc22-8cb1-11e6-81c2-ffbdd4a0d969.png)

**Comment by Halama** [comment]
sakra to je divny jaktoze tam ma docasny pristup

**Comment by ondrejhlavacek** [comment]
koukám jak ty se na ten reason peče :-)

**Comment by kacurez** [comment]
to mi pride tiez divne ze tam ma docasny pristup, som myslel ze to je len pre nas na debug, preto je tam ikonka.

**Comment by pivnicek** [comment]
kurva, moje chyba.

**Comment by padak** [comment]
asi solved
