### ISSUE TITLE
TR configs in orchestration tasks

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#688]
Když chci pustit jen nějaké transformace v orchestraci, špatně se hledá, které to jsou, protože tam není uveden název, ale id TR bucketu (což je u nových číslo).
![job 211380369 2016-10-22 12-46-52](https://cloud.githubusercontent.com/assets/12933713/19618839/e1a645a2-9855-11e6-940b-966f5a807cb4.jpg)

**Comment by Halama** [comment]
duplicitni k https://github.com/keboola/kbc-ui/issues/696 
fixneme, diky
