### ISSUE TITLE
[RS Writer] - Cannot select table for writing by typing few characters

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#693]
Hi,

I have difficulty with selecting table to be written in RS Writer (V2 Beta). My scenario:
1. I create new configuration, set up credentials
2. Click on add table and I can see the form for selecting the table
3. When I type few letters (lets say "out"), after 1 second or less after I write it it gets removed from the field. 

Can you, please, take a look at it? Thanks!

**Comment by Halama** [comment]
this should be fixed
