### ISSUE TITLE
[ORCHESTRATOR] show config names instead of ids in edit tasks dialog

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#696]
![screenshot](https://cloud.githubusercontent.com/assets/497675/19826398/a5f2701a-9dbb-11e6-957b-ce588892e294.png)

**Comment by janmichek** [comment]
Zda se ze tohle je vyreseny, ani jsem pro to nemusel nic delat. Je to mozny?

**Comment by janmichek** [comment]
@ondrejhlavacek @Halama  id configu na podstrance nevidim, naopak nazev vidim. Prosim zvalidujte a pripadne uzavrete
