### ISSUE TITLE
Sort columns in input mapping

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#699]
Bylo by fajn, kdyby byly sloupce v input mappingu transformace řazeny nějakým rozumným způsobem (abecedně?). Pokud je nadefinovaných sloupců hodně, dost špatně se v tom orientuje.
![platby 2016-10-31 15-21-00](https://cloud.githubusercontent.com/assets/12933713/19857469/124bf11e-9f7e-11e6-82dc-813e7e65dbee.jpg)

**Comment by janmichek** [comment]
duplicate od https://github.com/keboola/kbc-ui/issues/888
