### ISSUE TITLE
copy to clipboard not working in create sandbox modal

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#700]
V detailu transformace po kliku na `Create Sandbox` vyskoci modal ktory naloaduje a zobrazi credentials, ked kliknem na copy to clipboard button tak vyhodi tooltip hlasku `copied` ale nezkopiruje nic
![image](https://cloud.githubusercontent.com/assets/1412120/19898106/fb6bf740-a05a-11e6-86cc-82d375ce919d.png)

na inej stranke `transformations/sandbox` to kopirovanie funguje - tam sa vsak credentials nezobrazuju v modal dialogu.

Skusal som update react-clipboard-js knihovny na 1.0.0 ale nepomohlo.

Kopirovanie credentials som v tom modal dialogu skryl v tomto commite:
https://github.com/keboola/kbc-ui/commit/1fc9cce28aae5d8296481c159da7fe31a320b0a0

**Comment by MiroCillik** [comment]
Uz to hlasi aj Martin Lepka.
https://keboola.zendesk.com/agent/tickets/5721

Napriklad v db writeroch to ale tiez funguje.

**Comment by MiroCillik** [comment]
@kacurez jo ty si ich skryl, ale len pre MySQL sandbox, pri Snowflaku stale su a nefunguju.
