### ISSUE TITLE
[jobs] add component type

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#702]
![screen shot 2016-11-06 at 17 21 11](https://cloud.githubusercontent.com/assets/497675/20036534/7d0732b8-a445-11e6-8786-1ba1a7daca6c.png)

=> slack extractor job

**Comment by janmichek** [comment]
@ondrejhlavacek nerozumim tomu co se po me chce, pls porad.

**Comment by ondrejhlavacek** [comment]
@janmichek když pustím job tlačítkem play, napíše to `Slack job has been scheduled` nebo `Google Sheets job has been scheduled`, a protože Google Sheets máme extraktor i writer, dodal bych tam typ komponenty, tj. `Google Sheets extractor job has been scheduled` nebo `Google Sheets writer job has been scheduled`. Jakej to je typ má komponenta uložený u sebe.

**Comment by ondrejhlavacek** [comment]
A dával bych to tam asi jen pro extraktory, writery (a aplikace), pro ostatní asi ne... Transformace tam maj generický `Transformations job has been scheduled` a to asi stačí
