### ISSUE TITLE
[CSV IMPORT] editable configuration name and description layout

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#703]
![data_takeout_recovery_-_master_-_extractors___csv_import___accounts](https://cloud.githubusercontent.com/assets/497675/20043599/d3d14176-a4ca-11e6-9bb6-b4e3aac58964.png)

**Comment by janmichek** [comment]
Pripada mi to vyresene. Jmeno konfigurace je editovatelne a popis konfigurace je nalepeny vpravo. Ne ze by to byla nejaka designova pecka xD ale vypada to stejne jak v ostatnich extraktorech.

**Comment by ondrejhlavacek** [comment]
Tak pak vyřešeno! Díky
