### ISSUE TITLE
[Python Transformations] Bad help message in Stored Files

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#708]
Hi guys,

Python (and other) transformations that have Stored Files section have misleading help message:

"The latest file with a given tag will be saved to /data/in/user/{tag}."

Because the filepath /data/in/user/{tag} is actually error - now it is in /data/in/user/ID_filename

Would be good to change it, hmm? 

Thanks a lot and have a great day!

**Comment by janmichek** [comment]
Udelal jsem podle navodu, ale nedokazu overit funkcnost linku. Zatim nevim jak si mam naklikat tu transformaci aby to neco delalo

**Comment by vokurka** [comment]
Ahoj,

uz je to nejspis fixnute - soubory se nahravaji spravne podle napovedy. Muzes zavrit :)

**Comment by ujovlado** [comment]
je to cajk
```
ls -la /data/in/user

drwxrwxr-x 2 501 501 59 May 5 08:16 .
drwxrwxr-x 5 501 501 63 May 5 08:16 ..
-rw-r--r-- 1 root root 127 May 5 08:16 test-issue-708
-rw-r--r-- 1 root root 290 May 5 08:16 test-issue-708.manifest

```
