### ISSUE TITLE
Redshift Writer - can't show hidden ignored columns when no one has been set yet

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#709]
Když založím v RS writeru novou tabulku, kde jsou všechny slupce ignored a dám Hide ignored, vše zmizí a nikde není možnost je zase zobrazit.
![out c-quicksight campaign 2016-11-16 13-11-31](https://cloud.githubusercontent.com/assets/12933713/20346799/7cb958d4-abfe-11e6-9ff3-6c76379dd6dd.jpg)

**Comment by ujovlado** [comment]
Uz bolo opravene. A vsetky sa uz nedaju nastavit na IGNORE (nepovoli ti to ulozit)
