### ISSUE TITLE
Redshift writer - test credentials error

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#711]
- Spustit test credentials
- Loader zůstane kousnutý a v konzoli je chyba:

![image](https://cloud.githubusercontent.com/assets/903531/20477459/04709b0e-afd6-11e6-87ea-ad47f69e232a.png)

**Comment by natocTo** [comment]
Prověřuji a zdá se již v pořádku (taky to jsou dva roky). Ono taková důležitá věc se asi opravovala co nejdříve to šlo. Tak zavírám, pokud o ověřuji špatně tak znovu zapnout samo + třeba popsat cestu k erroru.
