### ISSUE TITLE
Náš Vertica GD Token

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#715]
By bylo super, kdyby nebyl vedenej jako "Custom" a nemohl si ho kdokoliv v UI zobrazit kliknutím na zámeček:
![image](https://cloud.githubusercontent.com/assets/1427901/20617771/a3dbd27c-b2eb-11e6-9b45-827695391132.png)

**Comment by JakubMatejka** [comment]
To není problém, přidám ho do "slovníku" v db. Akorát kde prosím tě zjistím ten token? (v sites není: https://sites.google.com/a/keboola.com/devel/kbc/writery/gd-writer/gooddata-authtokeny)

**Comment by padak** [comment]
@JakubMatejka díky! Doplnil jsem to do Sites!

**Comment by JakubMatejka** [comment]
Už by to mělo fungovat(?)

**Comment by padak** [comment]
Boží!
