### ISSUE TITLE
Cancelled orchestration start date invalid

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#721]
If an orchestration is terminated before it begins, the start date shows `Invalid Date`.  Should probably be "N/A" I guess.

![image](https://cloud.githubusercontent.com/assets/569139/21042994/0ed1a958-bdf5-11e6-80be-dd1e91370923.png)

**Comment by janmichek** [comment]
packed with similar fix https://github.com/keboola/kbc-ui/issues/835
