### ISSUE TITLE
Orchestrator: config names in job retry

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#722]
tady by měly bejt jména místo idček

![screen shot 2016-12-09 at 23 21 38](https://cloud.githubusercontent.com/assets/497675/21066537/526419b4-be66-11e6-9530-0d21a5d008b3.png)

**Comment by Matejkys** [comment]
Hoj. Je tu nějaký posun? Je to pořád totálně matoucí, pokud mám víc configurací jedné komponenty.

**Comment by ondrejhlavacek** [comment]
Čus, zatím ne, ale pokusím se s tím pohnout asap :-). Matoucí to je, to je zřejmý...
