### ISSUE TITLE
Neloaduje zoznam tabuliek v Chrome

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#725]
Zvlastny bug, pri ktorom obcas nejde nacitat zoznam tabuliek v GD writeri:
https://cloudup.com/cYvQlCvhafO

Z chyby v konzoli to vyzera na problem s nejakou extensionov v Chrome.

Low prio.

**Comment by SvetlanaM** [comment]
K tomu ak ste to ešte nedebagovali je to spôsobené novou verziu Google chrome (55) , je neodladená a má veľa bugov a najmä bugy s cachovaním . Na našej strane veľmi neodladíme, kým si to nefixne google, maximálne poradiť klientom nech downgradujú

**Comment by Halama** [comment]
Tvl @MiroCillik jak si to debugoval, a jeste low prio. Ja jsem si tohodle issue vsimnul ted v tydnu a pekne me to sralo. Akorat jsem si nevsiml ze uz to je opravene, kazdopadne uz jsem to fixnul.

https://github.com/keboola/kbc-ui/commit/b45135745edc888b50636a473dee3bdc806f6895
