### ISSUE TITLE
[err] Redshift Writer - Application error on deleting table

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#727]
Hi,

I can see an error happening (Safari and Chrome) while trying to delete table from configuration of Redshift Writer. See screenshot for more info. After page reload the table is not there, however it is a bit confusing.

<img width="1406" alt="snimek obrazovky 2016-12-19 v 16 17 02" src="https://cloud.githubusercontent.com/assets/13956703/21317712/9cd0e656-c606-11e6-8d23-244b9582d1e1.png">

**Comment by janmichek** [comment]
@vokurka Cao, ja to tady zkousim nasimulovat a vse projde ok. Chyby v konzoli nevidim, tabulka po smazani zmizi z listu bez reloadu.
Zkousel jsem pridavat a odebirat tabulky a namatkove nejake krkolomnosti.
Predpokladam ze jde o novejsi verzi redshift writeru.
Je na to nejaka magicka konstelace?

**Comment by vokurka** [comment]
Ahoj,

tohle uz je tak stary bug, ze byl nejspis fixnut. Najlos pridaval tagy bug a ready, coz mi mozna napovida, jestli bug nepotvrdil a neopravil on? Zkusis se ho zeptat?

Diky, pekny den!

**Comment by janmichek** [comment]
@ondrejhlavacek ?

**Comment by ondrejhlavacek** [comment]
Už je to asi fixnutý, díky! :-)
