### ISSUE TITLE
[err] No names of configurations in Job Retry in Orchestrations

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#729]
No names :/ See screenshot - it is very hard to navigate now.

<img width="889" alt="snimek obrazovky 2016-12-23 v 15 12 05" src="https://cloud.githubusercontent.com/assets/13956703/21455643/5112c058-c922-11e6-9f61-a18eff185802.png">

**Comment by ondrejhlavacek** [comment]
duplicate #722
