### ISSUE TITLE
add link to help.keboola.com

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#735]
somewhere in the UI, perhaps under 'support' link ?

**Comment by Halama** [comment]
https://projects.invisionapp.com/share/V98PFGOY4#/screens/191118651

![image](https://cloud.githubusercontent.com/assets/903531/21609798/c4ab4b8e-d1c4-11e6-828f-be1a41c50b82.png)

![image](https://cloud.githubusercontent.com/assets/903531/21609802/caffd3ec-d1c4-11e6-933c-18bb7ff10dfe.png)
