### ISSUE TITLE
Looks like google lib is not loaded correctly sometimes

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#768]
![screenshot_2017-01-20_10-42-37](https://cloud.githubusercontent.com/assets/419849/22144225/47025c86-defd-11e6-926d-fbfc15f68931.png)

... ako keby nastala chyba pri nacitani google lib, potom to hodi error.

**Comment by ondrejhlavacek** [comment]
duplicita k #767

**Comment by ondrejhlavacek** [comment]
Sorry, přehlídl jsem se

**Comment by ujovlado** [comment]
Fixed by 9a6493f1fb4684325e1801013ca735357c765c9a
