### ISSUE TITLE
Nová check ikona?

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#77]
https://github.com/keboola/kbc-ui/commit/e5f7d1821b9f8ed27ebf7d72285620098720114f

**Comment by JakubMatejka** [comment]
jj. to je ta obrázková:
![development_-_tasks](https://cloud.githubusercontent.com/assets/215660/7903179/8fd109aa-07d4-11e5-843d-c9aee27c9514.png)

**Comment by Halama** [comment]
To vypadá ale jako tlačítko, nemá takhle být spíš v editačním režimu?

**Comment by JakubMatejka** [comment]
No nevím, možná na obou místech? Ale půjde to vyměnit za checkbox? Potom bych je v tomto statickým zobrazení nejspíš zesvětlal aby bylo vidět že jsou neaktivní.

**Comment by Halama** [comment]
Zatím bych to teda nechal spíš takhle
