### ISSUE TITLE
Huge amount of transformations kill the chrome tab

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#770]
Here you can find the example: https://connection.keboola.com/admin/projects/1218/transformations In Chrome, you'll wait a minutes; Safari behaves much faster. [Here we have a screenshot](https://keboola.slack.com/archives/ui/p1484997477000075) (which is not publicly available, so I'm not posting it here).

**Comment by ondrejhlavacek** [comment]
Řešení by bylo sejmout ty akční tlačítka - vyhodil jsem je a brutálně se to zrychlilo. Všechny akce na bucketech/transformacích jsou stejně dostupný v detailu bucketu, kde už toho tolik na zobrazování není

Before:

![image](https://cloud.githubusercontent.com/assets/497675/22181778/613c863e-e093-11e6-892d-137a91798acb.png)

After: 

![image](https://cloud.githubusercontent.com/assets/497675/22181783/863d1e58-e093-11e6-9394-ad7d41d30e41.png)

**Comment by ondrejhlavacek** [comment]
Trochu bych to i přeskládal, a podle mě to vypadá celý čistší, co ty na to @padak?

**Comment by ondrejhlavacek** [comment]
No, asi to rovnou udělám, vlastně není moc nad čím přemýšlet :-)

**Comment by ondrejhlavacek** [comment]
Tak teď to trvá 5-10 vteřin pro těch cca 300 bucketů. Je to přijatelný? Ještě bych to mohl zkusit dál ořezat. 

Díval jsem se do profileru a nebrzdí to žádný náš kód.

**Comment by ujovlado** [comment]
Zatvaram, aktualne vidim, ze je to ako v 2. screenshote.
