### ISSUE TITLE
MySQL ex default out bucket doesn't include config name

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#776]
Ahoj.

Bylo by fajn, kdyby byl součástí názvu default output bucketu v MySQL ex rovnou i název konfigurace. Lidi nemají moc potřebu to přejmenovávat, ale jsou k tomu nuceni, pokud mají dva a více configů.
![new query 2017-01-26 11-16-29](https://cloud.githubusercontent.com/assets/12933713/22327881/ccb9c6a0-e3b9-11e6-90eb-942788f38dea.jpg)

**Comment by ujovlado** [comment]
je to generovane a dava sa tam ID konfiguracie
