### ISSUE TITLE
Sandboxes TTL info

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#778]
u každýho sandboxu napsat, za jak dlouho od vytvoření bude smazanej

**Comment by janmichek** [comment]
@ondrejhlavacek zdravim, mam 2 dotazy: 1. u jakeho sandboxu by mela byt informace TTL? Udajne jsou v aplikaci 2 typy sandboxu.  2. Vypada to ze u objektu sandboxu neni informace o case vytvoreni/expirace. Pls rozved torchu ideu.

**Comment by ondrejhlavacek** [comment]
MySQL, R a Python, u Snowflake a Redshiftu to zatím neumíme, jdu to hodit do Productboardu

![screencapture-connection-keboola-admin-projects-232-transformations-sandbox-1491298733172](https://cloud.githubusercontent.com/assets/497675/24650834/dc3e7d1c-192b-11e7-93ee-0222d74bc35e.png)

**Comment by ondrejhlavacek** [comment]
RStudio a Jupyter si zapneš přes `docker-sandbox` admin featuru

**Comment by Halama** [comment]
To feature nastavim. Takže tam stačí jen napsat tech 5 dní nebo to vrací backend kolik dní zbývá?

**Comment by ondrejhlavacek** [comment]
Backend to zatím nevrací, mohl by, ale pak by musel přibýt ještě api call na prodloužení. Takhle se prodlužuje při každým requestu na credentials (tj. při každým načtení týhle stránky). 

Napsal bych tam něco jako `If not used, the sandbox will be deleted after # days`.  V dokumentaci pro MySQL je napsáno `Also, your sandbox might be deleted after 14 days of inactivity; make sure not to use it as a permanent data storage!`

**Comment by ondrejhlavacek** [comment]
To, že ty sandboxy můžou zmizet kdykoliv, když spadnou spoty, zatím zamlčujem :-) To nevím moc jak popsat :-/
