### ISSUE TITLE
Úprava ikony pro popup menu uživatele

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#78]
Půjde vyměnit ikonka pro rozbalení menu uživatele? (vyměnit `span.caret` za `span.kbc-icon-picker`)
Taky by bylo dobrý kdyby se menu rozbalilo i po kliknutí na jméno a nejspíš i ikonku.

![overview_psd___200___top_info__rgb_8___and_development_-_job_112211042](https://cloud.githubusercontent.com/assets/215660/7933278/64c291b6-091e-11e5-9696-263f7eba56b6.png)

**Comment by Halama** [comment]
ok to asi půjde, vemu si to

**Comment by Halama** [comment]
tak ještě není fixnutý, musím změnit tu ikonku

**Comment by Halama** [comment]
Tak už by to mělo být fixnuté. V CSS ještě bude potřebovat přidat pointer cursor na celý `div.kbc-user`.
Taky by se ta šipka při hoveru možná neměla podtrhávat?

**Comment by JakubMatejka** [comment]
Jasně, hotovo. Díky.
