### ISSUE TITLE
snowflake writer - add table loader

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#784]
Kouslo se mi na:
![image](https://cloud.githubusercontent.com/assets/903531/22417354/19046fe8-e6d4-11e6-9314-1a4a78d0cf26.png)

Jak nasimulovat:

- Založit nový snflk writer
- Nastavit credentials jako keboola provisioned
- Ze stránky credentials přejít na stránku konfigurace writeru
- Vybrat `Add table`

**Comment by Halama** [comment]
stejně se chová i pro Redshift.

**Comment by kacurez** [comment]
trocha strielam od boku ale myslim ze to bude tymto:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/components/SapiTableSelector.coffee#L40
link na diskusiu kde sme to preberali a rozhodli sa pre to riesenie ^^
https://keboola.slack.com/archives/ex-google-drive/p1483362799000002

**Comment by Halama** [comment]
jestli zitra nebude nejaky srumec na zendesku tak na to zkusim mrknout
