### ISSUE TITLE
Přepracovat list-groups v detailu transformace na tabulky

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#79]
Stačí `<table><tbody><tr><td></td><td></td></tr></tbody></table>`, zbytek dostyluju

![development_-_transformation_nova](https://cloud.githubusercontent.com/assets/215660/7946780/068cbb0c-0979-11e5-8938-500ce554d65f.png)

**Comment by ondrejhlavacek** [comment]
@JakubMatejka proč tabulky? z tabulek na listgroups jsem to předělával před pár dny a přišlo mi to lepší - tabulky neumí udržet stejnou šířku sloupců a adaptují se - dva input mappingy pod sebou jsou pak rozlítaný

**Comment by JakubMatejka** [comment]
No dobře no. Tak jako ty informace v tom sémanticky nejsou zrovna seznam a tabulky už mám pěkně nastylovaný (a zafixovat šířku sloupců není problém) ale budiž, nastyluju todle. ;o)

**Comment by ondrejhlavacek** [comment]
Klidně tam vrátím ty tabule, když mi poradíš, jak zafixovat jejich šířku. Sémanticky to není ani tabulka (to bys potom mohl říkat tabulka jakýmukoliv key-value), nejvíc mi to připomíná statický pole formuláře, nemam to teda udělat z nich?
