### ISSUE TITLE
[keboola.ex-facebook] query modal

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#792]
![image](https://cloud.githubusercontent.com/assets/497675/22505223/970443b2-e87a-11e6-9e71-bc3fc1dbe08d.png)

a) `advanced` tam vizuálně vůbec nepatří
b) u všeho jsou otazníky na tooltipy, ty bych vyházel a místo toho to dal jako nápovědu pod příslušný inputy; pokud se tím formulář zvětší, mohl by být na samostatné stránce a advanced bejt jako záložka
c) fields je zdánlivě moc velký?
d) mechanismus výběru ze šablony je zvláštní
e) chybí tam placeholdery pro všechny inputy

**Comment by ondrejhlavacek** [comment]
na tom template se mi nelíbí to, že ho vyberu a zůstane tam vidět, i když hodnoty změním. vůbec nevím, jestli se ta hodnota toho dropdownu uloží nebo ne. imho by to neměla bejt součást formuláře, ale nějakej např. `<DropdownButton />`

**Comment by ondrejhlavacek** [comment]
![image](https://cloud.githubusercontent.com/assets/497675/22505421/b75e5282-e87b-11e6-8333-3d1a6dc134db.png)
-> `Edit query`

**Comment by ondrejhlavacek** [comment]
![ondra_s_sandbox_-_extractors___facebook__beta___](https://cloud.githubusercontent.com/assets/497675/22505475/02c41702-e87c-11e6-89ef-7c79f3037c63.png)

**Comment by ondrejhlavacek** [comment]
![image](https://cloud.githubusercontent.com/assets/497675/22505518/2c65a6de-e87c-11e6-983c-486299b2ff33.png)

nešlo by to, aby se to editovalo bez poskočení layoutu? a nebo přes modál jako editace transformační fáze - bude tam prostor i pro vysvětlení, co to znamená, link na dokumentaci, atd...

![image](https://cloud.githubusercontent.com/assets/497675/22505539/4ccaeef2-e87c-11e6-99ff-12ca68ba7994.png)

**Comment by kacurez** [comment]
u fb ads bola poziadavka stiahnut vsetky ads accounty a tam je prave potreba dat `None` do ids, podobne to moze byt aj u fb

**Comment by ondrejhlavacek** [comment]
Tomu moc nerozumím, jakože `All` nestáhne všechny a `None` jo?

**Comment by kacurez** [comment]
je to parameter requestu fb api - `ids`. Ak je query `get me/accounts` a zaroven zadas parameter `ids` tak ti fb api vrati chybu. `All` robi to ze do `ids` nacpe vsetky vybrate accounty. `None` parameter `ids` z requestu vynecha.

**Comment by ondrejhlavacek** [comment]
A jakej v tom je teda rozdíl? Bude potřeba to v UI vysvětlit... Může ten popis bejt `Do not include ids param` nebo něco takovýho

**Comment by kacurez** [comment]
to skor vidim na vysvetlenie v dokumentaci nez na tom formulari.

**Comment by kacurez** [comment]
tak upravil som:
- --all-- na All Pages a --non-- na None
- edit query tooltips a spol
- medzera medzi pages a modify buttonom
- velkost fields inputu

chystam sa:
- [ ] skusim dropdown button namiesto selectu pri vybere template
- [ ] vyhodit tooltipy a nahradit textom + placeholderom

nevyjasnene:
- show advanced .. ?
- facebook api version set - mohol by tam byt modal s ponukou vsetkych verzi(tusim od v2.2 do v2.8) alebo ciste edit input?

**Comment by ondrejhlavacek** [comment]
Vysvětlení `None` na formuláři může bejt o tom to pojmenovat jako `Do not include parameter` nebo tak něco...

Show Advanced - po vzoru twitteru a s3 extraktoru bych volil variantu vlastní záložky s advanced nastavením, každej input na vlastní řádek a k tomu nápovědu, co to znamená přímo k inputu

Version - pokud chceme updatovat UI pokaždé když zvednou / odstraní verzi, tak asi dropdown, ale jinak bych to nechal jako textovej input s popiskem, co tam máš dát, link na aktuální seznam verzí a popis, co se může stát, když updatuješ verzi existující konfigurace

**Comment by kacurez** [comment]
este chybaju placeholdery ale zatial to mam takto
![image](https://cloud.githubusercontent.com/assets/1412120/22518102/b11bd5fe-e8ab-11e6-97a8-1b32648f3b95.png)

**Comment by padak** [comment]
Ta šablona na nastavení je super!!

**Comment by kacurez** [comment]
pridal som placeholdre a trocha este upravil:
![image](https://cloud.githubusercontent.com/assets/1412120/22547997/9e81a204-e944-11e6-8e10-5880f1c2fc49.png)

By som to uzavrel, co sa tyka nastavenia api-version tak nato vytvorim novu issue.
diky za komenty!

**Comment by ondrejhlavacek** [comment]
ještě tři drobnosti 
 - účaří textu tlačítka a nadpisu tabu (u S3 extraktoru mi to vyšlo na `top: 37px`)
 - trochu bych změnil poměr labelu a inputu ve formu, 1-11 je moc nahečmaný vlevo, zkus 2-10 nebo 3-9
- Zmizela nápověda k `Pages`, takže furt nevím, co je `None`. Co tu volbu přejmenovat na `Ignore 'ids' parameter` a All změnit na `Include all pages in 'ids' parameter` nebo vrátit zpět popisek? Bacha, v tom popisku by mělo bejt `Graph API`, ne `Graph api`

![ondra_s_sandbox_-_extractors___facebook__beta___](https://cloud.githubusercontent.com/assets/497675/22549001/7990ec5c-e949-11e6-9ff0-c781cbccb933.png)

**Comment by kacurez** [comment]
sa to predtym nezbuildovalo takze si pozeral na neaktualny obrazok, sorry..
pomer je 2:10 ale upravil som to účaří(huste slovo:)) a Graph Api.
Je(aj bola) tam napoveda k Pages a to imo staci: `Specifies page that will be applied to the query. Could be either none, all or one of the selected pages. It is represented by Facebook Graph Api nested request parameter ids.`

**Comment by ondrejhlavacek** [comment]
aha, tak to jsem si teda mohl všimnout, že koukám na něco jiného, sorry! na tom tvým obrázu to 2-10 vypadá líp.

API
![image](https://cloud.githubusercontent.com/assets/497675/22550804/2f748a1c-e952-11e6-9b49-8da996f54bab.png)
:-)

**Comment by kacurez** [comment]
allright upravil som to na API :)

**Comment by Halama** [comment]
Chybi k jejich public release ještě něco? Co jsem tak minulý týden sledoval tak to vypadá že to šlape i konfiguruje se ok.

**Comment by Halama** [comment]
![image](https://cloud.githubusercontent.com/assets/903531/22642174/e8c90830-ec59-11e6-9f3c-0aacc8e38204.png)

Tady k tomu loaderu bych dal nejaky popisek jako `Fetching pages from Facebook...` aby ta pomalo st byla na ne:)
