### ISSUE TITLE
new component configuration modal

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#793]
![image](https://cloud.githubusercontent.com/assets/497675/22508966/6e6200ea-e88c-11e6-98ea-68edc894bcc1.png)

==> `My S3 Extractor` dle typu komponenty

**Comment by JohnyFreeze** [comment]
nerozumim

**Comment by ondrejhlavacek** [comment]
Je tam placeholder, který u S3 extraktoru říká `My S3`, ale měl by říkat `My S3 extractor`, u writeru by měl říkat `My S3 writer`, atd...

**Comment by janmichek** [comment]
fixed here ->  https://github.com/keboola/kbc-ui/pull/900
