### ISSUE TITLE
configuration detail page - bottom blank margin

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#796]
![ondra_s_sandbox_-_extractors___itunes___abcd_and_aws-s3_and___coding_connection-docs_ _ondra_ondrejs-macbook-pro_ ___nnection-docs_ _-zsh](https://cloud.githubusercontent.com/assets/497675/22543000/c6fb5074-e92e-11e6-8d30-c3a7ae7308a1.png)

**Comment by janmichek** [comment]
Neni to uplne nejcistejsi fix, ale funguje to prijeatelne. Nechce se mi kopat do celyho layoutu. Vzhledem k nadchazejicim zmenam to ani nedava smysl.

**Comment by ujovlado** [comment]
Fixed in https://github.com/keboola/indigo-ui/commit/a2a729eac3fec4bc14977588ad8bef18744e6191
