### ISSUE TITLE
transition between limits and project power reloads page

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#799]
![image](https://cloud.githubusercontent.com/assets/903531/22552451/49ded3ba-e959-11e6-96b8-f7cb41479d9d.png)

Zřejmě tam není použitý React Router Link a neaplikuje se tak push state.

**Comment by JohnyFreeze** [comment]
pouze u Limits a Project Power ? protoze users a settings nejsou definovane routy

**Comment by Halama** [comment]
jj pouze u tehle dvou, ty ostatni jsou renderovany jenom backendem proto nemaji routy
