### ISSUE TITLE
Přesunout tlačítko editace transformace

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#80]
Jako v orchestracích (http://kbc-bootstrap-jakub-devel.keboola.com/examples/orchestrations-list.php)

![development_-_transformation_nova](https://cloud.githubusercontent.com/assets/215660/7946827/6852c340-0979-11e5-882b-092b3db74ccf.png)

**Comment by JakubMatejka** [comment]
V editaci taky, prosím pěkně:

![development_-_transformation_rko](https://cloud.githubusercontent.com/assets/215660/7964611/eea67c62-0a18-11e5-998f-c2f6547465c9.png)

**Comment by ondrejhlavacek** [comment]
@JakubMatejka provedu! díky!
