### ISSUE TITLE
[kbc-ui-templates-api] jako komponentu a url v UI načítat z listu komponent

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#803]

**Comment by Halama** [comment]
Seznam komponent jsme přestali používat jako "DNS" vše co není reálná komponenta jsem odtamtud v rámci přípravi multi-region vyhodil. šlo o synchronní akce  a externí služby.
Co má být přesně tohle?

**Comment by Halama** [comment]
Možná by to mohlo být v `services`? Ale pokud je to globální služba (nemá vlastní endpoint pro region) tak to může být zahardcodovano v ui jako např. `external.keboola.com`
![image](https://cloud.githubusercontent.com/assets/903531/22638920/a8539d78-ec4b-11e6-93e9-33fa739d37a4.png)

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/blob/3ab3bd88a2dc195a06b5a408c7722c2da4e21a7d/src/scripts/modules/components/TemplatesApi.coffee#L11

posledně jsme se bavili o tom, že ty tam tohle zahardcodovaný bejt nemělo

**Comment by ondrejhlavacek** [comment]
jinak to asi můžu refactorovat do sync akce standardní komponenty, aby to nebyla taková osamocená věc a dalo se to deployovat do regionů

**Comment by Halama** [comment]
bych to tam nechal jak to je.

**Comment by Halama** [comment]
jsem to tam nedávno naopak vracel https://github.com/keboola/kbc-ui/commit/4336b2bb7069fd97ef4c3717ebf937127d42eb31#diff-b5a49150f9f549fcc58ea75e827a811c

**Comment by ondrejhlavacek** [comment]
no tak ok :-) dík
