### ISSUE TITLE
FB Ads a FB insights extraktor - drobnost do UI

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#806]
Je to malý krůček pro nás a velký pro lidstvo! Do výběru metrik bych moc prosil doplnit linky do FB dokumentace a k endpointům ideálně rozbalovací list (nebude jich víc jak pár).

![image](https://cloud.githubusercontent.com/assets/1427901/22682196/c8829164-ed11-11e6-95a0-352da7a968a7.png)

A na Advanced tab bych strčil předvyplněné šablony s pár 'handy' časy:

![image](https://cloud.githubusercontent.com/assets/1427901/22682386/ae7868c4-ed12-11e6-98b3-8eea87e3e09c.png)

Pokud existuje popis těch datumových definicí (jak udělám třeba previou month?), tak tam dát prosím odkaz. Jako když je v GitHubu popis "Mastering Markdown" - ať to nemusí nikdo hledat.

Jinak to vypadá super, díky!!

Padák

**Comment by ondrejhlavacek** [comment]
`Select from a template` => `Select template` 
ten dropdown se teda asi bude muset strčit dovnitř tabu aby do druhýho tabu mohl dropdown s datumama

a ty dropdowny by si neměly udržovat vybranou hodnotu, měl by to nastavit a zmizet

**Comment by kacurez** [comment]
1. pridat link na dokumentaciu FB api mam v plane ale rozmyslal som ze to prelinkujem cez dokumentaciu ex fb tj bude tam link na help.keboola.com na ktorom bude link na doku fb api
2. zoznam endpointov by mohol byt ako autosuggest input namiesto selectu, pretoze endpoint moze byt prazdny. Nieco ako ma ex google analytics ked zadavas metriku alebo dimenziu.
 3. `fields` su zlinearizovane parametre requestu na fb api teda je to skor obecny pojem a je pre kazdy endpoint iny. Ak poznas fb api nested-request tak by mala stacit dokumentacia endpointu a si schopny `fields` zostavit, napr tu je doku pre endpoint `feed` https://developers.facebook.com/docs/graph-api/reference/v2.8/page/feed
na zostavenie fields pre page insights potrebujes 2 stranky doku:
https://developers.facebook.com/docs/graph-api/reference/page/insights
https://developers.facebook.com/docs/graph-api/reference/v2.8/insights
4. na popis datumovy definicii sa pouziva znama PHP fce `strtotime`a mame to podobne na viac miestach(napr ex google analytics) takze mat help stranku "Mastering date ranges" by bodlo.
5. dropdown pre select date range - tak ako pise Najlos zeby mal byt vo vnutri kazdeho tabu zvlast.
6. select template dropdown nechcem uplne schovavat lebo user moze mat tendenciu preklikavat templaty v snahe pochopit ako to funguje.

Teraz hlavne napisem dokumentaciu prelinkujem stym dialogom a "rozbijem" dropdowny do tabov.

**Comment by kacurez** [comment]
- pridal som odkaz na help pre `endpoint` a `fields` kde su odkazy na ex fb endpointy a dalsie stranky dokumentace fb api.
- do advanced tabu som pridal dropdown pre select date ranges ktorymi sa naplni since a until, v general tabe je select na query template

Neviem ci ma zmysel dalej fabulovat otom co sa tam hodi, by som to takto nasadil a pockal na feedback. Myslim ze minimalne 80% pripadov je pokrytych sablonami a vyzaduje minimalne usilie/znalost na konfiguraciu. Zbytok by sa mal dat vydedukovat z helpu.
