### ISSUE TITLE
Úprava editace transformace

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#81]
Šlo by takto přesunout to mazací tlačítko mappingů? (to nový už jsem tam vyrobil)
![development_-_transformation_rko](https://cloud.githubusercontent.com/assets/215660/7982928/a362818a-0abb-11e5-834c-e856f116cd46.png)

**Comment by JakubMatejka** [comment]
BTW. editace RS transformace mi failuje na `InputMappingRowRedshiftEditor.coffee:182`: `Uncaught TypeError: Cannot read property 'get' of undefined`

**Comment by ondrejhlavacek** [comment]
Díky, dneska opravím!

**Comment by ondrejhlavacek** [comment]
@JakubMatejka tu chybu nemůžu najít, mohl bys mi poslat odkaz nebo říct jakej projekt + transformace to dělá?

**Comment by ondrejhlavacek** [comment]
(Uzavření se týká jen přesunu tlačítka)

**Comment by JakubMatejka** [comment]
@ondrejhlavacek  Jasně, je to v projektu 236 (KBC Paymo TAPI UI clone) ve všech co jsem tam našel, např. tady: `#/transformations/bucket/sys.c-transformation/transformation/neco`

**Comment by ondrejhlavacek** [comment]
@JakubMatejka neklikals ještě někam? Otevřu editaci a nic... 
![screen shot 2015-06-05 at 10 42 40](https://cloud.githubusercontent.com/assets/497675/8011695/b021c908-0b6f-11e5-9353-c6e130fd5600.png)

**Comment by JakubMatejka** [comment]
Mně se ty chyby objevují ale jen u Redshiftových transformací, dívám se že na screenshotu máš Rkovou.

**Comment by ondrejhlavacek** [comment]
Ehm,  nojo
