### ISSUE TITLE
Sklik ex shows password in error message

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#813]
UI zašifruje heslo, které vložíte do Sklik ex. Ale když mi to pak spadne na erroru, v jobu je heslo vidět  (jako argument loginu):
![job 236539859 2017-02-14 11-42-04](https://cloud.githubusercontent.com/assets/12933713/22925984/0a14e944-f2ab-11e6-9c5e-ef9ba8595ca3.jpg)

**Comment by kacurez** [comment]
to bude na backend vytvoril som tam issue ^^

**Comment by ujovlado** [comment]
v extractore uz fixnute, zatvaram
