### ISSUE TITLE
transformation delete

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#817]
smazání transformace provede redirect na stránku bucketu, ale nereloadne se bucket/nesmaže se transformace ze storu, furt tam visí

![transformation delete](https://cloud.githubusercontent.com/assets/497675/23059724/f47bbe80-f4fa-11e6-9670-7c86457e5e13.gif)

**Comment by kacurez** [comment]
tiez som nato narazil a imho problem bude tu:
https://github.com/keboola/kbc-ui/blob/467dabde8c82a4da0ce9db708b42ada1ff6a72ac/src/scripts/modules/transformations/react/pages/transformation-detail/TransformationDetail.coffee#L74-L79
po zmazani transformacie sa to pred zavolanim `transitionTo` pokusa vyrendrovat null transformaciu, co vyhodi vynimku a nestihne sa zavolat refresh.

![image](https://user-images.githubusercontent.com/1412120/29874239-703ff03e-8d96-11e7-96ef-2339eff56465.png)

**Comment by ondrejhlavacek** [comment]
když to debuguju a stepuju, tak dostávám tohle pořadí event

```
STORAGE_TABLES_LOAD_SUCCESS
TRANSFORMATION_DELETE
ROUTER_ROUTE_CHANGE_START
INSTALLED_COMPONENTS_CONFIGSDATA_LOAD
VERSIONS_LOAD_START
VERSIONS_LOAD_SUCCESS
INSTALLED_COMPONENTS_CONFIGSDATA_LOAD_SUCCESS
ROUTER_ROUTE_CHANGE_SUCCESS
TRANSFORMATION_DELETE_SUCCESS
```

a když to nestepuju, tak tohle

```
TRANSFORMATION_DELETE
ROUTER_ROUTE_CHANGE_START
INSTALLED_COMPONENTS_CONFIGSDATA_LOAD
VERSIONS_LOAD_START
VERSIONS_LOAD_SUCCESS
TRANSFORMATION_DELETE_SUCCESS
VERSIONS_LOAD_START
INSTALLED_COMPONENTS_CONFIGSDATA_LOAD_SUCCESS
ROUTER_ROUTE_CHANGE_SUCCESS
VERSIONS_LOAD_SUCCESS
```

imho je to tím, že INSTALLED_COMPONENTS_CONFIGSDATA_LOAD_SUCCESS proběhne před TRANSFORMATION_DELETE_SUCCESS, nebo nějaká podobná race condition
