### ISSUE TITLE
Snowflake - query statement timeout info

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#818]
If we deliver our Snowflake Schema for customer, via Snowflake Writer, it would be handy to add there information about credentials limits. Just to write it somewhere, ideally right next to existing credentials - to be sure that user has to read it while copy&pasting his credentials. 

There should also be an call to action button, saying that we can extend this timeout for additional $$ (kbc credits in future).

**Comment by ondrejhlavacek** [comment]
tenhl text by nestačil?

![image](https://user-images.githubusercontent.com/497675/28033841-5b54aed0-6564-11e7-8be4-52910e62ea15.png)

**Comment by kacurez** [comment]
outdated
