### ISSUE TITLE
Generické component UI

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#82]
- místo aktuálních **Applications**
- podobně jako Extractors / Writers, jen filtrované na komponenty, které mají u sebe flag `componentsUI`
- později by to mohlo být filtrovatelné podle typu/textu/tagů
- budou tam teď recepty, geneea, docker-xls2csv, table-importer

**Comment by Halama** [comment]
tak koukám že tohle vlastně už udělal @kacurez  :)
