### ISSUE TITLE
Dummy component UI

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#83]
Možnost pracovat s komponentami, které nemají žádné UI

- pro všechny konfigurace komponent, pokud nemají vlastní UI, zobrazit stránku, kde je možné konfiguraci spustit a smazat
- pokud má komponenta flag `allowGenericEdit`, detail konfigurace zobrazovat obsah konfigurace a bude umožňovat editovat JSON konfigurace (textarea) - čtení z a zápis do `/components/.../configs/...`

**Comment by Halama** [comment]
Udělám před releasem alespň tu první část aby šlo pustit a smazat ty komponenty bez UI
