### ISSUE TITLE
Dropbox Writer (and probably others too), console error after new config creation and deletion

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#831]
There's an error in console, immediately after new config creation:

![screenshot_2017-02-24_17-31-05](https://cloud.githubusercontent.com/assets/419849/23311688/37366196-fab7-11e6-903a-545a334c8c55.png)

**Comment by kacurez** [comment]
to by malo byt len vo wr-dropboxe, ten pouziva stary oauth a tam tusim platilo ze credentialsId == configId takze si ui na zaciatku skusa ci ma oauth credentials k danemu konfigu

**Comment by ujovlado** [comment]
nj, nie je to blocker, vsimol som si to nahodou ... a robi to aj tde-exporter ... mozno by sme si mohli v configu drzat, ci je authorized

**Comment by ujovlado** [comment]
tde-exporter to nerobi :)

**Comment by ujovlado** [comment]
vedel som, ze som to este niekde videl ... takze `ex-dropbox`

**Comment by ujovlado** [comment]
Applies also to deletion:

![screenshot_2017-02-24_21-06-29](https://cloud.githubusercontent.com/assets/419849/23319015/256210d2-fad5-11e6-9550-9a56ce02f588.png)

**Comment by janmichek** [comment]
Ja zkousim smazat dropbox extractor i writer ruznymi zpusoby a do konzole mi zadnou chybu nevypisuje.

**Comment by ujovlado** [comment]
Nejdeme riesit. Su to validne kontroly, ci nieco existuje. Podobne sa spravaju napr. transformacne sandboxy.
