### ISSUE TITLE
Unify dropbox auth modals

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#832]
There are 2:
- `src/scripts/modules/ex-dropbox/react/DropboxAuthorizationModal.jsx`
- `src/scripts/modules/components/react/components/DropboxAuthorizeModal.coffee`

**Comment by janmichek** [comment]
@ujovlado  Dobra tedy... predpokladam ze chceme pouzit ten .jsx kod. Bude potreba prepsat do ES6 i ten nadrazeny kod, odkud se vola modal v `src\scripts\modules\wr-dropbox\react\pages\index\Index.coffee` a `src\scripts\modules\tde-exporter\react\pages\Destination\DropboxRow.coffee ` ???

**Comment by ujovlado** [comment]
@janmichek neviem, ktory z nich je lepsi ... asi by som tam nechal ten, ktory sa pouziva jednoduchsie (ak to bude coffee, ok, netreba ho nutne prepisat do jsx - to je na tebe. Ak je tam komplikovanejsia logika, kludne to nechaj tak.

Tie nadradene (odkial sa vola) by som urcite nechal tak a neprepisoval ich do jsx.
