### ISSUE TITLE
[low prio] Icon blur

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#834]
![blur](https://cloud.githubusercontent.com/assets/497675/23329484/d45a2ffc-fb39-11e6-9c45-51ca7d00b0a8.gif)

není to vždycky na stejnejch místech, mění se to
ale nenašel jsem to zatím u jinejch ikonek

**Comment by janmichek** [comment]
Na tohle znam odpoved.
1. Rozostreni se deje kvuli DPI displaye
2. Browser antialiasuje - webkity sou znamy ze neumi moc hezky aliasovat fonty (kazdej znak jinak), v tomhle ma Firefox navrch. Na znaky to funguje dobre, ikony kvuli tomu zlobi

![image](https://cloud.githubusercontent.com/assets/15363559/24762542/fffd9a16-1aee-11e7-9bc8-102e4ed57a7f.png)
.

Ma to vic reseni -> https://github.com/blog/1135-the-making-of-octicons

**Comment by ondrejhlavacek** [comment]
Takhle se jebat s každou ikonkou ve Font Awesome asi nechcem :-)

**Comment by ujovlado** [comment]
oznacil by som to ako 3rd party bug, imho to nemusime riesit

**Comment by ujovlado** [comment]
@ondrejhlavacek mozes este skusit odfajcit `.fa-fw` ... to je asi jedina custom vec co tam mame

**Comment by ondrejhlavacek** [comment]
Potom ty ikony lítaj kam se jim zachce :-(

**Comment by ujovlado** [comment]
Prechadzal som "3rd party" issues a toto by som zavrel, pretoze sa s fixovanim babrat nejdeme a pravdepododobne sa to fixne prechodom na novsi icon set (napr. nova verzia font-awesome). A tiez, je to extra minor issue
