### ISSUE TITLE
freshly started orchestrator shows Invalid date in Start

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#835]
![image](https://cloud.githubusercontent.com/assets/497675/23329802/f32e2fd6-fb3f-11e6-8a68-7de134319bc4.png)

**Comment by janmichek** [comment]
@ondrejhlavacek me se to nedari nasimulovat - 'invalid date' nikde nevidim.

Postupuju takhle -> vytvorim a nakonfiguruju tasky pro novou Orchestraci -> Save -> Run -> Run (v modalu) -> klikam na detail v konfiguraci.

Potom vidim datum dle ocekavani.
Jako ted vidim ze za par milisekund to preblikne z invalid na realny datum. To je ta issue?

**Comment by Halama** [comment]
@janmichek Musis hodne rychle prekliknout na ten job te orchestrace. Chvili to tam problikne.

**Comment by Halama** [comment]
Tak vim jak to nasimulovat lepe. Staci spustit vickrat po sobe jednu orhcestraci ktera bezi dele a pak kliknout na waiting job tam je ta chyba.

![image](https://cloud.githubusercontent.com/assets/903531/24756948/f433068c-1add-11e7-81c8-5b07a3b43b23.png)

**Comment by janmichek** [comment]
boyz, me se nadari nakonfigurovat nejaka mega-cpu-killa-orchestrace. NEvim ktery tasky sou tak narocny aby orchestrace trvala hodiny, dal jsem  maximalne minuty. Muzete me priradit do nejakyho projektu, kde najdu takovou konfiguraci orchestrace, prosim?

**Comment by Halama** [comment]
Melo by to jit nasimulovat i stou co mas u tebe v tom projektu.

**Comment by Halama** [comment]
pust tuhle dvakrat hned po sobe a mas to https://connection.keboola.com/admin/projects/2376/orchestrations/253397080

**Comment by Halama** [comment]
![image](https://cloud.githubusercontent.com/assets/903531/24948064/62b93dd0-1f69-11e7-852f-2c8e35b33735.png)

**Comment by janmichek** [comment]
extended with Marc's suggestion https://github.com/keboola/kbc-ui/issues/721
