### ISSUE TITLE
db writers: encrypt DB password for databases provided by Keboola

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#836]
![image](https://cloud.githubusercontent.com/assets/1726727/23330833/f5f0dcaa-fb58-11e6-8330-f694a3498f88.png)

Pri pouziti se ulozi do konfigurace nezasifrovane heslo

**Comment by ErikZigo** [comment]
Je to tak u vsech DB WR

**Comment by kacurez** [comment]
to je spravne, ako sa potom user propoji do nami poskytnutej db ak dostane heslo zasifrovane? :)

**Comment by ErikZigo** [comment]
Jsem myslel ze to funguje obdobne jako sandboxy, ze ty credentials vidi jen ten kdo je vytvoril.

**Comment by Halama** [comment]
zaviram
