### ISSUE TITLE
kbc-ui-doctool-recipes migrace

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#84]
Zmigrovat současné UI tak (fork!), aby pracovalo s konfiguracema v `/components/.../configs` na načítání obsahu konfigurace (zbytek se furt načitá z doctool bucketu v shared configu). Domluvit s Odinem, jak to bude spolupracovat s backendem (backend už by měl být ready).

**Comment by kacurez** [comment]
toto sa moze zavriet imo.
