### ISSUE TITLE
Predefined AW bucket

### ISSUE THREAD

**Issue by Matejkys** [keboola/kbc-ui#848]
V našem pojetí bucketů je trochu divné, že předvyplněný bucket pro AW ex je OUT, i když to jsou zdrojová data. Podle mě by to mělo být v IN stage.
![bata 2017-03-03 11-13-56](https://cloud.githubusercontent.com/assets/12933713/23547209/adccb80a-0002-11e7-851d-0987d9ed6ab2.jpg)

**Comment by ujovlado** [comment]
Schema uz je zmenena a predvyplnene tam uz nie je nic.

![screenshot_2017-10-19_22-10-24](https://user-images.githubusercontent.com/419849/31791855-5a48f716-b51a-11e7-909a-20356fd9e5bf.png)
