### ISSUE TITLE
GoodData writer - missing params in job object

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#849]
1. List gdwr configs
2. Click "play" 
3. Notification shows, go to job detail

-> job has not enough properties (5 instead of 15)

job "reload" didn't happen for some reason

**Comment by Halama** [comment]
![image](https://cloud.githubusercontent.com/assets/903531/25693742/496bcfb6-30ab-11e7-930c-536abfd01841.png)

**Comment by Halama** [comment]
tohle se mi děje pořád, mohl by to prosím někdo fixnout?
