### ISSUE TITLE
Left menu is not working properly 

### ISSUE THREAD

**Issue by jiritobolka** [keboola/kbc-ui#85]
Apps menu item is hidden and others are very big. See the screenshot attached...

![screen shot 2015-06-05 at 13 37 11](https://cloud.githubusercontent.com/assets/951201/8005243/01b3029c-0b88-11e5-8e34-442a016eeb3a.png)

**Comment by JakubMatejka** [comment]
That's not a bug I'm afraid. ;o) The left menu is scrollable.
