### ISSUE TITLE
Gooddata writer - switching between modes

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#852]
Warning in console
`The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`

file: `TableLoadType.coffee`

![screenshot_2017-03-04_11-53-08](https://cloud.githubusercontent.com/assets/419849/23578188/477412e0-00d1-11e7-92bd-21231ef7db24.png)

**Comment by ujovlado** [comment]
Toto sa deje aj inde a skor je to problem react + input type number

Minor vec, nicomu nevadi, zatvaram

**Comment by janmichek** [comment]
@ujovlado rychlej napad - nevyresim by to react-bootstrapi FormControl mist html inputu? Muzu to vyzkouset.

**Comment by ujovlado** [comment]
No kludne skus ak chces. ALe imho jeto low-prio. Nasimulujes to tak, ze tam napises nieco ine ako cislo (napr. `aaa`).
