### ISSUE TITLE
db-writer - reset credentails vymaze

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#863]
Mam konfiguraci writeru s vlastni DB.
Kdyz v `credentilas` kliknu na tlacitko `reset`, tak me to hodi na editacni formular a vsechny pole jsou prazdny. Nemam moznost editace.

![image](https://cloud.githubusercontent.com/assets/1726727/23927420/de89c99a-0919-11e7-8a5c-fa72eeb1cd1c.png)

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/pull/868
