### ISSUE TITLE
transformation phase - 404 documentation link

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#869]
![image](https://cloud.githubusercontent.com/assets/903531/23990177/820b49a6-0a35-11e7-807f-47729d66ecff.png)

**Comment by janmichek** [comment]
+ je slusnost to otevirat v novem okne

**Comment by ondrejhlavacek** [comment]
https://help.keboola.com/manipulation/transformations/#phases

V novým okně s CTRL/SHIFT :-)

**Comment by Halama** [comment]
jj tim vynucenim otevreni do noveho okna seberes uzivateli moznost volby.
I kdyz je pravda ze u nekterych linku to taky vynucujeme napr. sandbox nebo `explore in console`
