### ISSUE TITLE
Chyba kdy můj Google účet nemá přístup do Google Analytics

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/kbc-ui#87]
Asi by to neměla být Application Error
![development_-](https://cloud.githubusercontent.com/assets/215660/8033653/8408558a-0de0-11e5-9da1-867f0fae37e4.png)

**Comment by kacurez** [comment]
Ahoj,

chyba je na backendu, zadal som to Mirovi do zendesku ako ticket #3404

Tomas

**Comment by kacurez** [comment]
nakoniec sa urobila uprava na UI - nevypisuje ze to je Application Error alebo iba Error- z dalsieho kontextu je jasne ze to je User Error. 
Status code toho fialnuteho requestu je 400.

zatvaram
