### ISSUE TITLE
Not found links (transformations: r, python)

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#875]
- https://github.com/keboola/kbc-ui/blob/0f1dab32647487e3681b9e12956e85bedf6ed939/src/scripts/modules/transformations/react/pages/transformation-detail/ScriptsEdit.jsx#L47
- https://github.com/keboola/kbc-ui/blob/0f1dab32647487e3681b9e12956e85bedf6ed939/src/scripts/modules/transformations/react/pages/transformation-detail/ScriptsEdit.jsx#L40

**Comment by ondrejhlavacek** [comment]
To už je fixnutý
