### ISSUE TITLE
wr-google-drive console errors

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#880]
Toto je odo mna Chromium (picker sa nacita)
![screenshot_2017-03-23_23-41-27](https://cloud.githubusercontent.com/assets/419849/24273380/52247f9e-1022-11e7-9621-fa0651f13b51.png)

- prvy err je, ze nematchuju origins (to by sme mozno vedeli dotunit skrz CSP
- ten druhy err, je kvoli neplatnej hlavicke:
`x-frame-options:ALLOW-FROM https://connection.keboola.com` -> tak to posle google (nevieme to nastavit?)

@kacurez skusme to nejako debugnut, este dodam viac info, no vyzera, ze ten picker v niektorom browseri nefunguje. Neskusil by si Safari, ci ti spravne ten picker bezi resp. ake da errory?

**Comment by ujovlado** [comment]
Firefox (detto, zobrazi error, picker sa nacita):
![screenshot_2017-03-23_23-54-10](https://cloud.githubusercontent.com/assets/419849/24273714/2949d5f4-1024-11e7-8ad7-590033c22acb.png)

**Comment by kacurez** [comment]
kde to presne nefunguje? o tych chybovych hlaskach viem a nepodarilo sa mi ich odstranit, no kedze picker fungoval tak som to nikdy velmi neriesil. Na safari mi to funguje a tiez hadze tie hlasky:
![image](https://cloud.githubusercontent.com/assets/1412120/24283624/43987012-1067-11e7-85ce-2cf7c0d90928.png)

btw rovnaky picker je pouzity aj v google drive extraktore
