### ISSUE TITLE
Saving empty ruintime section (in custom science) right after configuration creation causes runtime section noneditable

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#884]
This is the cause:

```json
{
  ...
 "configuration": {
    "runtime": []
  },
  ...
}
```

**Comment by janmichek** [comment]
@ujovlado Caj, potreboval bych vic informaci. Nejakej gif by hodne pomohl .]

**Comment by janmichek** [comment]
@ujovlado muzes se prosim podivat jestli tahle validace staci?
Kdyz napisu pismeno a smazu ho, tak uz to ulozit jde. Objekt ale mezitim ziska aspon prazdny string "".
Je to tak ok?

**Comment by janmichek** [comment]
Prej "ruintime" xD co to jako ma bejt? Nejaka party?

**Comment by ujovlado** [comment]
Toto sa uz muselo fixnut s niecim inym, vracia mi to dobre `configuration: {runtime: {}}`. Zatvaram.
