### ISSUE TITLE
Thrash - load

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#885]
Při vstupu na stránku koše nejdříve problikne prázdný koš a pak se teprve objeví data.
Má to být tak že se stránka zobrazí až má připravená data.

**Comment by Halama** [comment]
Mělo by to jít pořešit tady v `requireData` https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/trash/routes.js#L14

**Comment by ErikZigo** [comment]
ok kouknu na to

**Comment by ErikZigo** [comment]
Muzes na to prosim kouknout? Uplne nevim, jak to otestovat, aniz bych to nasadil. Z localu pri vyvoji mi to nedela

**Comment by Halama** [comment]
mrknu behem odpol

**Comment by ErikZigo** [comment]
https://github.com/keboola/kbc-ui/pull/891

Nasazeno a fixnuto
