### ISSUE TITLE
Smazání komponenty - odstranění confirmu

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#889]
Vyhodit confirm pro smazani konfigurace, pokud dana komponenta podporuje "Revert delete".

![image](https://cloud.githubusercontent.com/assets/1726727/24403679/3e1d44e6-13be-11e7-924f-788db1aa9ee4.png)

Je to tam zbytecny. V notifikaci o smazani konfigurace mame dialog, ktery umozni vratit akci zpet.

![image](https://cloud.githubusercontent.com/assets/1726727/24403752/9ca4b094-13be-11e7-8429-20aae2825994.png)

**Comment by janmichek** [comment]
@ErikZigo jak prosimte poznam jestli dana komponenta podporuje "Revert delete"? hledam nejakej json, kde je to vyjmenovany, nebo tak neco. Nemuzu to najit

**Comment by ErikZigo** [comment]
@ujovlado Tady je na to metoda
https://github.com/keboola/kbc-ui/blob/80da765dbd80596992e788d255c043d865ce8411/src/scripts/modules/trash/utils.js#L4

pokud pro komponentu vraci `true`, tak komponenta revert nepodporuje
(napriklad GD Writer, Orchestrator)

**Comment by Halama** [comment]
hotovo
