### ISSUE TITLE
Dostylování - seznam projektů

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#89]
V devel režimu si to spustíš pomocí `npm run start-projects-list`
Vstupní soubor je tady https://github.com/keboola/kbc-ui/blob/91adc1030209e606f550dcca9aa4f5c4946d339e/src/scripts/projectsList.coffee Ten se ale pak na produkci nepoužívá tam se to vyrenderuje do tohodle samého vygenerovaného serverm.

To co bude potřeba poeditovat (pokud nebudou stačit css změny) jsou tyhle 2 komponenty 
https://github.com/keboola/kbc-ui/blob/91adc1030209e606f550dcca9aa4f5c4946d339e/src/scripts/projectsList.coffee#L11

**Zakulacení ikonky pomocí CSS**
![image](https://cloud.githubusercontent.com/assets/903531/8054342/3e006c36-0e98-11e5-9491-7bfbda87aec7.png)

**Prázdnej search**
![image](https://cloud.githubusercontent.com/assets/903531/8054348/4b732b38-0e98-11e5-800a-70900167a998.png)

**Navigace šipkama**
Přidává se tam classa `active` pro aktuální projekt (Je to stejné jako výběr projektů v projektu), stačí asi nějak nastylovat.
![image](https://cloud.githubusercontent.com/assets/903531/8054383/9e7beff4-0e98-11e5-8543-7471b8457643.png)

**Keboola vs Connection**
Tady si nejsem jistej jestli by tam nemělo být connection, ale zase to takhle vypadá imho dobře.
![image](https://cloud.githubusercontent.com/assets/903531/8054429/e6e6d222-0e98-11e5-8ce7-d32e584b8df0.png)

**Comment by JakubMatejka** [comment]
No jo, s tím logem těžko říct. To bude možná spíš na rozhodnutí Padáka. Ale spíš mi přijde že by to mělo být jednotný, buď všude Keboola, nebo všude Connection. (Connection by ale bylo rozhodně hezčí v tom Keboolím fontu)

**Comment by Halama** [comment]
jj Connection v Keboola fontu by mohlo být fajn

**Comment by Halama** [comment]
Nadhodím to někde ve slacku
