### ISSUE TITLE
DB2 pro Baťu má ikonku bez transparentního pozadí

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#890]
![image](https://cloud.githubusercontent.com/assets/1427901/24443829/7880e1e6-1464-11e7-9fdd-440f79e4395a.png)

... je to hnusný :)

**Comment by ondrejhlavacek** [comment]
tak to bude pravděpodobně i u ostatních DB2

**Comment by ErikZigo** [comment]
bizztreat.ex-fedger a keboola.ex-gcalendar maj rozbitou malou ikonku

![image](https://cloud.githubusercontent.com/assets/1726727/24509971/2967fc3e-1568-11e7-83ef-47e0212ceef8.png)

![image](https://cloud.githubusercontent.com/assets/1726727/24510032/50be3690-1568-11e7-8f55-99d3f103ea92.png)

**Comment by janmichek** [comment]
Fixed, ikony nahrány do cloudfront cdn.
Fedger měl dokonce nový logo

**Comment by ondrejhlavacek** [comment]
Nahrávals to přímo do CDN/S3 nebo přes developer portal?

**Comment by Halama** [comment]
pres DP, jinak to uz nenahravame

**Comment by ondrejhlavacek** [comment]
👍
