### ISSUE TITLE
Generic Components Simple Editing State

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#894]
https://keboola.productboard.com/feature-board/6271-planning/features/316199

hromadně se dá snadno vyřešit

 - [x] editace skriptu / queries v transformacích
- [ ] JSON schémata
 - [ ] šablony
  - [ ] editace JSONu v genericu

**Comment by ondrejhlavacek** [comment]
šablony by se mohly sfoukout s https://github.com/keboola/kbc-ui/issues/897

**Comment by Halama** [comment]
@ondrejhlavacek co kdyby si nektery z tehle vzal @janmichek po zahrivacich issues?

**Comment by ondrejhlavacek** [comment]
Jo, to by klidně šlo :-)

**Comment by janmichek** [comment]
@ondrejhlavacek potreboval napovedet ohledne tech sablon. Ten link na productboard mi nefunguje.

**Comment by ondrejhlavacek** [comment]
Změnil jsem ti práva, už tam můžeš. 

Jde o změnu fungování editace - příklad zde

https://connection.keboola.com/admin/projects/232/extractors/ex-generic-v2/currency-44

teď to funguje takhle

![](http://g.recordit.co/HXslSNNMhu.gif)

a mělo by to fungovat takhle

![](http://g.recordit.co/LMeRCOdEno.gif)

**Comment by ondrejhlavacek** [comment]
@janmichek https://github.com/keboola/kbc-ui/pull/902
commity https://github.com/keboola/kbc-ui/pull/902/commits/06c941d0e09c667274cf534fd221288e9a6f208b a https://github.com/keboola/kbc-ui/pull/902/commits/38a9b0dfad721cb28d65a7325a05ddfb6d0bb942
dělaj defakto totéž, ale pokaždý v jiný části transformaci
asi nejsložitější, co se tam děje (kromě přesouvání tlačítek na save o hierarchii výš) je že se tam do storu, kde se udržuje obsah editačního pole, přidá položka, která udržuje info, jestli editační položka byla změněná (to je pro stav ukládacích tlačítek).
- codemirror pak jako `value` zobrazuje buď změněnej editační stav (pokud je) nebo hodnotu z konfigurace (pokud není změněnej editační stav) - https://github.com/keboola/kbc-ui/pull/902/commits/06c941d0e09c667274cf534fd221288e9a6f208b#diff-bed54ecdd93c8bf44d2c474e762eff7dR395
- změněnej editační stav (upravený JSON) se naplní při prvním `onChange` (teď se naplnil při `onEditStart`, tahle metoda jde úplně pryč)
- `onEditCancel` kromě smazání rozeditovanýho stavu smaže i ten flag, jestli byla konfigurace změněná
- `onEditSubmit` totéž, taky smaže ten příznak (obsahy těch metod jsou vidět https://github.com/keboola/kbc-ui/pull/902/commits/06c941d0e09c667274cf534fd221288e9a6f208b#diff-bed54ecdd93c8bf44d2c474e762eff7dR398, jestli to bude v akcích nebo ve storu nebo v komponentě je celkem jedno, spíš ať to drží konzistenci)
