### ISSUE TITLE
FB ex - pages modify

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#898]
Pokud dám "Modify" ve FB ex, abych přidal další stránku
![image](https://cloud.githubusercontent.com/assets/1427901/24589783/dd9380b4-17e0-11e7-98a5-90ad59cd4943.png)
pamatuje si to nastavení a je nutné dát reload.

**Comment by kacurez** [comment]
tomu nerozumiem: imho to je spravne spravne - ak chces pridat stranku tak to ze si to pamata predtym nacitane fb stranky nicomu nevadi nie? alebo

**Comment by padak** [comment]
Ono to ukáže ty zvolené, ne ty co jsou k dispozici

**Comment by kacurez** [comment]
v tom pripade to je bug ale nedari sa mi ho nasimulovat. Mal by ukazat aj tie ktore su k dispozicii akurat si ich drzi nacitane po prvom vybrati stranky, ale to by imho nemalo nicomu vadit. Ked si 2.krat otvorim ten modal cez modify button tak nalavo vidim tie ktore su k dispozici a napravo tie ktore som si zvolil a ulozil. Tiez je mozne ze si mal len jednu fb stranku pod sebou..

obrazok je z ex fb ads ale princip je rovnaky:
![image](https://cloud.githubusercontent.com/assets/1412120/24615432/8379c9ea-188e-11e7-9ede-05003cb0c2a4.png)

**Comment by kacurez** [comment]
toto zatvorim, mam zato ze sme to dnes so Zuzkou vyriesili.
