### ISSUE TITLE
Advanced parameters for Geneea NLP app

### ISSUE THREAD

**Issue by mudrunka** [keboola/kbc-ui#899]
The UI for Geneea NLP analysis app (`geneea.nlp-analysis-v2`) should support a field for advanced parameters, where the user could specify arbitrary parameters as a JSON.

For example, if the user would specified a JSON value `{"advanced_param_1": "one", "advanced_param_2": "two"}`, the config JSON of the app would be updated as follows.

```
{
  "storage": {
    ...
  },
  "parameters": {
    ...
    "advanced_param_1": "one",
    "advanced_param_2": "two"
  }
}
```

**Comment by kacurez** [comment]
mame json editor ui komponentu  a by som navrhoval to dat pod jeden `advanced` objekt v `parameters` takze by konfig vyzeral:
```
{
  "storage": {
    ...
  },
  "parameters": {
    ...
    "advanced: {
       "param_1": "one",
       "param_2": "two"
  }
}
```

@mudrunka je to ok z pohladu backendu?

**Comment by mudrunka** [comment]
@kacurez to by slo, jen bude nutne backed trochu upravit

**Comment by kacurez** [comment]
to bude lepsie pretoze mohlo by sa stat ze user v tom json vyplni param ktory sa zaroven nastavuje cez inu ui komponentu

**Comment by kacurez** [comment]
@mudrnka tak uz som to nasadil, akurat problem je ze nase api uklada prazny objekt `{}` ako prazdny array `[]` takze aby stym backend pri zpracovani `advanced` property pocital. Inac je to samozrejme neprazdny objekt `{"param": "value"}`

**Comment by ondrejhlavacek** [comment]
@kacurez ukládá to `{}` jako `[]` furt? docela jsme  to dřív řešili a snad jsme to fixli? kde se to děje?

**Comment by kacurez** [comment]
@najlos deje sa to stale 

**PUT request:**
![image](https://cloud.githubusercontent.com/assets/1412120/24709785/630e3f54-1a1b-11e7-8c6c-5cff4b791451.png)
**response**:
![image](https://cloud.githubusercontent.com/assets/1412120/24709713/264a7830-1a1b-11e7-9427-0cd555841fc1.png)
https://connection.keboola.com/admin/projects/219/applications/geneea.nlp-analysis-v2

**Comment by ondrejhlavacek** [comment]
hm, mrknu na to - v connection se to už fixovalo
https://github.com/keboola/connection/issues/135

**Comment by Halama** [comment]
hmm, to je dost divny. v SAPI by to měl pokrývat tenhle test https://github.com/keboola/storage-api-php-client/blob/ebad4b1cc2f9d84fd9fb5976a633d6b191359d5a/tests/Common/ComponentsTest.php#L333

**Comment by kacurez** [comment]
je mozne ze SAPI to vrati spravne ako prazdny objekt ale docker-runner to obrati na prazdne pole..?

**Comment by ondrejhlavacek** [comment]
Jo, a v Docker Runneru na to test není, takže to bude asi tam, mrknu na to.

**Comment by ondrejhlavacek** [comment]
Update - do `Keboola\StorageApi\Components::updateConfiguration` pošlu objekt a v návratový hodnotě metody je pole.

**Comment by ondrejhlavacek** [comment]
A v Connection je správně uložený objekt.

**Comment by kacurez** [comment]
jasne a do config.json/yml pri pusteni docker containeru sa teda dostane spravne prazdny objekt? ze problem je vlastne len v response `Keboola\StorageApi\Components::updateConfiguration`?

**Comment by ondrejhlavacek** [comment]
Nareportoval jsem to u nás - https://github.com/keboola/storage-api-php-client/issues/126 a mezitím to fixnu v UI

**Comment by ujovlado** [comment]
Je opravene, zatvaram.
