### ISSUE TITLE
back navigation from writer credentials page

### ISSUE THREAD

**Issue by pivnicek** [keboola/kbc-ui#916]
After you make credentials for your writer, there is no obvious navigation to continue setting up your config

![pasted image at 2017_04_06 12_58](https://cloud.githubusercontent.com/assets/569139/24751644/af2f1480-1aca-11e7-95c6-22c2fe9fc091.png)

**Comment by ondrejhlavacek** [comment]
To bude chtít pořešit asi ještě s Jackem v #uiux, jak na to

**Comment by jancermak** [comment]
@pivnicek  try this https://invis.io/NCBERIGK2#/230248269_snowflake-Credentials_Copy_4

![snowflake-credentials copy 4](https://cloud.githubusercontent.com/assets/1826442/25312472/f056f548-2819-11e7-8e7b-d468e298c33e.png)
![snowflake-credentials copy 5](https://cloud.githubusercontent.com/assets/1826442/25312471/f055e068-2819-11e7-8c2b-3d1b9a81c8e9.png)

**Comment by janmichek** [comment]
I can implement this @pivnicek, or you already doing this?

**Comment by pivnicek** [comment]
@janmichek be my guest! :-)
