### ISSUE TITLE
Detail jobu - label

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#92]
Ten label "error" je obrovskej a takovej mázlej, snažil jsem se s tím něco uděla a nepodařilo se mi.
![image](https://cloud.githubusercontent.com/assets/903531/8057074/79382990-0eae-11e5-9454-6a0368f0b9b6.png)

**Comment by JakubMatejka** [comment]
Ten by tam IMHO být ani neměl, sjednotil bych to spíš s jobama u orchestrací, co myslíš?

![development_-_job_109139881](https://cloud.githubusercontent.com/assets/215660/8061149/bda56a96-0ec9-11e5-8618-e4bb195018aa.png)

**Comment by Halama** [comment]
jo jasně, to bude nejlepší tak jak říkáš
