### ISSUE TITLE
[transformations] add ZSTD compression for Redshift transformations in input mapping

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#920]
https://aws.amazon.com/blogs/aws/data-compression-improvements-in-amazon-redshift/

https://keboola.slack.com/archives/C02CMFLDG/p1491556964139798

a určitě prodat ve weekly postu :-)

**Comment by janmichek** [comment]
pridal jsem moznost na frontu = ZSTD do selectbox v input mappings
https://github.com/keboola/kbc-ui/tree/ZSTD-input-mapping

Dalsi napojeni bude na nekom z vas, databaze nejsou moje domena
