### ISSUE TITLE
Configurations list - search bar

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#921]
https://keboola.productboard.com/inbox/features/322727

Na strance extraktoru mi chybi moznost rychle ofiltrovat seznam jako mame jinde. Dost casto to delam tak ze tam lezu radsi pres stranku noveho extraktoru.

Bude to vypadat a fungovat stejne jako u transformaci:

![image](https://cloud.githubusercontent.com/assets/903531/24795990/98daadc2-1b8b-11e7-9e78-d61c740bc923.png)

## Implementace
Stejné jako u transformací, hodnota filtru bude ležet ve store, měnit se bude akcí.

https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/transformations/react/pages/transformations-index/TransformationsIndex.coffee#L36

**Comment by ondrejhlavacek** [comment]
To by se podle mě hodilo i na detail komponenty (seznam jejích konfigurací), pokud bude mít víc než `N` konfigurací.

**Comment by ondrejhlavacek** [comment]
Jenom doplním, že u transformací to filtruje tak, že pokud to matchne bucket (=komponentu), tak se zobrazí všechny její konfigurace, pokud jen konfiguraci, tak pouze tu v rámci komponenty.
