### ISSUE TITLE
Time ago - show full datetime on hover

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#923]
Všude kde se zobrazuje `2 days ago` by se po hover mělo v obyčejném `title` zobrazit celé datum s časem.

Příklady kde to nefunguje:
![image](https://cloud.githubusercontent.com/assets/903531/24802248/88a24994-1ba7-11e7-896d-74fd18519214.png)

![image](https://cloud.githubusercontent.com/assets/903531/24802264/99700270-1ba7-11e7-8409-033b14d3f549.png)

![image](https://cloud.githubusercontent.com/assets/903531/24802275/9e265c4c-1ba7-11e7-9b19-fb97e0efb956.png)

Tady to je jenom po najetí na kalendář (a je to v tooltipu, to je zbytečný)
![image](https://cloud.githubusercontent.com/assets/903531/24802306/c8e04bfa-1ba7-11e7-8b15-c4f22a9b7869.png)

**Comment by janmichek** [comment]
Predelano nebo pridelano na titly - jeste to testnu v mobilu co to vlastne dela.
AKtivni plocha hoveru rozsirena i na text.

Na jinych mistach aplikace jsem uz casove info nenasel.
U toho diffovatka jsem si dovolil pridat ikonu s kalendarem, aby bylo jasny ze je to neco navic nez jen plain text.

V ramci konzistence bych tenhle vizual s ikonama (doba, cas od vytvoreni, cas vytvoreni na hover) rozsiril i na seznam jobu a detail jobu.

**Comment by Halama** [comment]
ha, tenhle komentar jsem prehledl. Taky jsem si rikal jestli to nejak nesjednotit v tom seznamu jobu. V tom detailu je ale nekolik casovych informaci a tam by ten relativni udaj nedaval moc smysl.

**Comment by janmichek** [comment]
Koukam ze jsem neprohnal datum formatorem, fixnu hned, at je to citelnejsi
