### ISSUE TITLE
Inline edit

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#93]
Nebylo to modrý podsvícení myšlený jenom při hoveru?
![image](https://cloud.githubusercontent.com/assets/903531/8057836/1bbe32c6-0eb5-11e5-9abb-e49aa9c66c78.png)

**Comment by Halama** [comment]
Při rozeditování to taky celé lehce poskočí nahoru

**Comment by JakubMatejka** [comment]
No mně to taky přišlo divný ale v psdčku to je takhle a nic o hoveru se ani ve vrstvách nepíše. Ještě se zeptám

**Comment by Halama** [comment]
Tak poskakování dělají font-ikonky např. u ex-db tam kde jsou obrázkové je to ok.
Vyřešíme to #110
