### ISSUE TITLE
Search bar for configurations in component detail

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#940]
Search v detailu komponenty (seznam jejích konfigurací), pokud bude mít víc než N konfigurací.

**Comment by Halama** [comment]
+1 všude jinde je a tady chybí.
![image](https://user-images.githubusercontent.com/903531/41961160-f5a990fc-79f1-11e8-9f77-b2c3fc5eddb6.png)

**Comment by janmichek** [comment]
Tady je funkcni demo gif
Searchbar se objevi pro 3 a vice konfiguraci pro ex, wr, app.
Hleda se podle nazvu, popisu, id.
Poresil jsem prazdny stav - zadne konfigurace nenalezeny
![confilter](https://user-images.githubusercontent.com/15363559/42823862-e9661f84-89de-11e8-8879-525d54f3dbdb.gif)

**Comment by janmichek** [comment]
Jeste muzu zkusit odladit Placeholder Searchbaru, aby uzivatele vedeli podle ceho hledat. ( je potreba rozsirit komponentu.

Taky se mi moc nelibi to UI. Lepsi by byl button vedle searchbaru a oddeleni hranici. Zatim na to nemame nejaku UI koncept, tak to budu muset nejak custom vymyslet ./
