### ISSUE TITLE
Reset or Revert?

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui#942]
Revert seems more appropriate to me:

![image](https://cloud.githubusercontent.com/assets/4319320/24969352/ca9f6216-1fb0-11e7-8102-a8250e9e9468.png)

Because it *reverts* to the last saved version. Reset evokes that it will remove everything?

**Comment by pivnicek** [comment]
omg, I feel a very strong pull to comment here:)

I agree with @odinuv regarding `reset` that it would be closer in meaning to `clear`.  But I also agree with @ondrejhlavacek that `revert` would indicate some sort of versioning mechanism.

So I vote strongly for `cancel`, which in this context means to me "forget everything I've just said".

**Comment by ujovlado** [comment]
For me, reset is OK ... I think revert means "undo" something which already has been applied.

Anyway, if we look back, there was (or still is) `<input type="reset">` ... so I vote for reset :)

**Comment by ujovlado** [comment]
Reset to intiial state is native behavior:

```html
<form>
  <input type="text" value="123">
  <input type="reset">
</form>
```

**Comment by odinuv** [comment]
And how about "Undo" ?

**Comment by pivnicek** [comment]
to me, undo is ctrz, a letter at a time
but cancel is saying "sorry, wrong number"

**Comment by odinuv** [comment]
@ujovlado If I had a cent for every angry user who clicked the reset button expecting something different from it - I would be building garage for my Ferrari :)

**Comment by Halama** [comment]
"Undo" is something different, "Revert" too.
"Reset" or "Cancel" is ok for me.

**Comment by ujovlado** [comment]
Davam ako "wontfix", mozeme sa k tomu vratit v ramci nejakej unifikacii UI alebo tak. :)
