### ISSUE TITLE
Show query number in SQL Editor

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#946]
Chceme aby sql editor ukazoval cisla queries, ne cisla radku (nehlede na to kolik ma query radku).
Tak jako to fungovalo nedavno.

Soucasny stav -> 
![image](https://cloud.githubusercontent.com/assets/15363559/25006301/b8473718-205c-11e7-9ab5-3c811e1cd4e8.png)

**Comment by ondrejhlavacek** [comment]
Řešili jsme to ještě tady - https://keboola.slack.com/archives/C02J3DKH3/p1492092850192306

**Comment by ondrejhlavacek** [comment]
řešení - číslo query skrýt v UI, do error message dát query excerpt a nalinkovat přímo detail query, který doskroluje a zvýrazní vyfailovanou query

**Comment by ujovlado** [comment]
Toto uz mame, v error message je query, ktora spadla a preklik do transformacie ju zvyrazni.
