### ISSUE TITLE
gooddata writer - trim identifier

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-ui#947]
Pokud se uloží `identifier` datasetu s mezerou na konci tak upload pak končí chybou.
Při uložení by se to asi mělo trimovat.

![image](https://cloud.githubusercontent.com/assets/903531/25074324/923eebc6-22f8-11e7-9bf7-b4bea9df02e2.png)

![image](https://cloud.githubusercontent.com/assets/903531/25074333/bac16010-22f8-11e7-9d64-c2f9ba79d417.png)

**Comment by janmichek** [comment]
Nazev identifier se nyni pri ulozeni trimuje. Tenhle json jsem teda nikde nenasel ale na strance jobu jsem kouknul ze uz se nazev propisuje bez mezer
