### ISSUE TITLE
Error: Schedule of Orchestration not refreshed after switching Orchestration

### ISSUE THREAD

**Issue by vokurka** [keboola/kbc-ui#948]
Hello guys,

our client from Australia gave us a shout on one problem with Orchestrations.

Steps to reproduce: 

1. Go to Orchestrations and select one Orchestration.

2. Click on Edit Schedule, remember what is showing. Click cancel.

3. Switch to another Orchestration in the same browser window using the menu on the left side. 

4. Click on Edit schedule. You will see the the schedule from the Orchestration before, not current one. (my amateur guess - bad refresh of the modular window while switching orchestrations?)

Confirmed on newest OS X and latest Chrome.

Let me know in case of questions, thanks!

**Comment by ondrejhlavacek** [comment]
fixed by https://github.com/keboola/kbc-ui/pull/951
