### ISSUE TITLE
[Transformace] Editační okno na mobilu

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#949]
via http://status.keboola.com/transformations-ui-update

On the other hand, strech of the editor area on the mobile (iPhone) would be highly appreciated. Its often one needs to change a tiny thing and only on the phone at the moment. With current area its almost impossible, viz photo http://imgur.com/CEys0gy

**Comment by janmichek** [comment]
A je v pohode to ze na mobilu je misto radkovaneho editoru cista textarea?
Zatim jsem nezjistoval proc to tak je, ale kdyz jdu v mobilu na http://codemirror.net/mode/sql/
vidim i v mobilnim browseru editor dle ocekavani

**Comment by ondrejhlavacek** [comment]
To asi taky není, ale v případě nouze to je furt ok.

**Comment by janmichek** [comment]
Fixnuto, ale mam to overeny jenom v simulatoru, ne na realnym devicu.
Pravdepodobne to ani ve vetsine mobilnich browseru nijak snadno nepujde http://caniuse.com/#search=resize
Nemame treba pristup do BrowserStacku?

Alespon jsem rozsiril textareu, horsi to urcite nebude .]

**Comment by ondrejhlavacek** [comment]
Fixed by https://github.com/keboola/kbc-ui/pull/952
