### ISSUE TITLE
link transformation detail with documentation

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#957]
transformacie su pomerne komplexne popisane v dokumentacii tu:
https://help.keboola.com/manipulation/transformations/
bolo by fajn dostat tento link na stranku transformacii aby sa user zaciatocnik pri pochybach vedel zorientovat a dost do povedomia moznosti transformacii. Typicky link na dokumentaciu stranky/komponenty sa zvykne davat do menu v pravo napr:
![image](https://cloud.githubusercontent.com/assets/1412120/25138068/cd036022-2459-11e7-9dc7-f99abef5f084.png)

**Comment by janmichek** [comment]
Dobra, muzu to porobit. Predpokladm ze screenshot z extractoru je just for show, abych vedel kam to umistit u transformaci

**Comment by ondrejhlavacek** [comment]
Jj, u každýho typu transformací by to ještě mohlo vést na svoji vlastní stránku...
