### ISSUE TITLE
[transformations]: delete transformation does not reload list of transformations

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#958]
Smazaná transformace tam zůstává furt viset

![](http://g.recordit.co/6YQtrDnryQ.gif)

**Comment by ondrejhlavacek** [comment]
@janmichek poslal jsem ti pozvánku do projektu, kde se to děje (2390). podle mě je to způsobený špatným chainováním requestů na API. nasimuloval jsem to tak, že jsem tam vytvoři pár bucketů s pár transformacema, do kterejch jsem dal trochu větší množství textu. tím se prodlouží nějaký request a předběhne ho jiný a způsobí to to chování, co popisuju.

zkusil bys tomu přijít na kloub?

**Comment by janmichek** [comment]
Zatim jsem na nic neprisel, ale udelal jsem tu samou operac nad tvoji db a nad moji skromnou db. Podivej se pls na tenhle spojenej screenshot, jestli z toho poradi API callu z fleku vidis neco? 
![untitled-5](https://cloud.githubusercontent.com/assets/15363559/25187003/233d6e74-2522-11e7-9c3a-5a0fc5762aa3.png)

**Comment by ujovlado** [comment]
Related to #817, Fixed by #1114 and #1116
