### ISSUE TITLE
support button indentation

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#959]
![image](https://cloud.githubusercontent.com/assets/497675/25176798/c40653b6-24ff-11e7-9f0d-dcfb7c7f5ad6.png)

ten nápis je nějak vpravo

**Comment by ujovlado** [comment]
Fixed by https://github.com/keboola/indigo-ui/commit/bfcafa9c31529eaa7720c3ec5f7882924a6e7a63
