### ISSUE TITLE
orchestration run button disabled

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#960]
na stranke orchestraci ked dam run tak nasledny confirm dialog obsahuje disabloveny run button a tym padom sa nedaju spusti orchestracie z tej stranky.
![image](https://cloud.githubusercontent.com/assets/1412120/25181605/58121420-2512-11e7-9819-e17bf5eb5de0.png)
pustit konkretnu orchestraciu z detailu jej stranky ide.

**Comment by kacurez** [comment]
problem je v tomto commite: https://github.com/keboola/kbc-ui/commit/9ebba73ffc541e091c1adc7f0cd3cf2eb1826d4d
index orchestracii nema nacitane tasky k jednotlivym orchestraciam - to sa deje az po kliku na detail orchestracie a tak filter na activeTasks vtomto pripade vzdy vrati prazdne tasky takze button je always disabled.
Dalo by sa forcnut aby sa na indexe vzdy pustila orchestracia bez taskov(== orchestrator si nacita vsetky tasky) ale potom imho disablovat/enablovat funkcne ten isty button na stranke detailu orchestracie nedava zmysel.

**Comment by ondrejhlavacek** [comment]
Hm, tak to jsem nezkontroloval :-(
