### ISSUE TITLE
Yarn watcher bug

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#963]
Na W10 se mi deje tenhle bug. Deje se to pomerne casto a zdrzuje me to.
Ukazka je s autosavem (kterej se stane pri focusoutu), ale deje se to i pri Ctrl+S savu.
Zatim jsem nenasel nic s cim by to souviselo.

![wwwww](https://cloud.githubusercontent.com/assets/15363559/25344195/ae7d4890-2911-11e7-90a3-9d72118a544c.gif)

**Comment by ujovlado** [comment]
@janmichek skus pls, ci nepomoze vypnut "safe write":
http://webpack.github.io/docs/webpack-dev-server.html#working-with-editors-ides-supporting-safe-write

**Comment by janmichek** [comment]
aha, diky za tip. Vypnul jsem safe write. Ted to budu chvili sledovat a zareaguju jak to dopadlo.

**Comment by janmichek** [comment]
chvilku to pouzivam a pripada mi ze se to tim 'safe writem' vyresilo. Dik za rady
