### ISSUE TITLE
Delete GoodData writer confirm better info

### ISSUE THREAD

**Issue by kacurez** [keboola/kbc-ui#964]
Ak dam delete na GoodData Writer config tak v confirm dialogu chyba informacia ze ajked sa config presunie do kosa tak sa uz neda restornut. Imho to moze byt past:
![image](https://cloud.githubusercontent.com/assets/1412120/25345015/1bd0f124-2914-11e7-85e5-252896ae5a86.png)

**Comment by janmichek** [comment]
Pravda, to upozorneni by se hodilo. Doplnim k ten warning k nerevertnutelnym komponentam.

**Comment by janmichek** [comment]
Skoda ze do stringu nesel propasovat break line ani ikona. Tak jen takhle textove .]
