### ISSUE TITLE
wr-db vypis tabuliek - lepsie nazvy stlpcov

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#967]
![zonky_-_writers___oracle___blaze_prod](https://cloud.githubusercontent.com/assets/1488015/25423780/2e570c54-2a66-11e7-8fcd-1894f5916d15.png)

**Comment by Halama** [comment]
to si uplně nemyslím, tohle jsme sjednocovali myslím právě takhle.

**Comment by MiroCillik** [comment]
Naozaj? Mne to prave prislo dnes trochu matuce. `Database name` posobi ako ze je to nazov databaze :)

**Comment by ujovlado** [comment]
Duplicate of #1259

**Comment by ujovlado** [comment]
Fixed in #1476
