### ISSUE TITLE
Pozice "describe" tlačítka

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#979]
Více popsané v Productboardu: https://keboola.productboard.com/inbox/notes/330908

---

- [x] tde exporter #1195 
- [x] google analytics #1221 
- [x] all db extractors #1097 

Zvysne sa spravia v ramci dalsieho PR (#1286):

- [x] db writers
- [x] ex google bigquery
- [x] ex google drive
- [x] ex mongo db
- [x] good data wr
- [x] google drive wr
- [x] google sheets wr

**Comment by janmichek** [comment]
Zatim tady odkladam kde jsem vsude videl bug
extraktor: BigQuery, MongoDB, Mysql, Sql Server,
writeru: Snowflake, Redshift, SQL server, Google drive, Dropbox

**Comment by ujovlado** [comment]
Nieco z tohto sa fixne v #1097, zvysok by som doriesil manualne na takyto stav (samostatny riadok pre description):

![screenshot_2017-10-18_19-33-26](https://user-images.githubusercontent.com/419849/31733212-3c216762-b43b-11e7-957b-3d8b9fc781c0.png)

**Comment by ujovlado** [comment]
kde sme to fixli a kde treba (doplnene podla https://github.com/keboola/kbc-ui/issues/979#issuecomment-302080227)

- [x] tde exporer
- [ ] google analytics
- [ ] ...

**Comment by ujovlado** [comment]
Updatol som popis issue, kde to este treba fixnut. Vyriesi sa to tak, ze description bude mat vzdy samostatny riadok ako je to vo vacsine komponent.
