### ISSUE TITLE
GooData Writer: fact grain vs full load

### ISSUE THREAD

**Issue by MiroCillik** [keboola/kbc-ui#982]
Disallow switching to `full load` from `incremental load`, when there is some `fact grain` configured.

> Příklad může být tabulka Prices: 
https://connection.keboola.com/admin/projects/555/writers/gooddata-writer/CCS/table/out.c-srovnani_cerpani.prices 
Když si rozklikneš mód loadu, je vidět, že předtím tam byly nastavené tři atributy jako fact grain. 
Pak jsem to přepnul na full load a v tu chvíli při update model nastane problém, protože to fact grain, dle mého, očekává, ale najednou tam není. V tu chvíli je rozhašený model a nepomůže ti ani load bez update model. 
Synchronize s preserve data ti neprojde a musíš to dát bez preserve (na to jsi přišel minule)."

**Comment by JakubMatejka** [comment]
To je blbost. ;o) Full load je i v případě nastavenýho grainu úplně legální požadavek. Navíc přepnutí z inkrementu na full load nijak nezmění model, a ani nesmaže grain.

**Comment by MiroCillik** [comment]
Ja do toho moc nevidim :) Len som to prepisal zo Zendesk ticketu.

**Comment by ujovlado** [comment]
Zatvaram, Jakub pisal, ze je to blbost.
