### ISSUE TITLE
Google Drive Writer - nefunguje autorizace ani pridani nove tabulky

### ISSUE THREAD

**Issue by ErikZigo** [keboola/kbc-ui#987]
![image](https://cloud.githubusercontent.com/assets/1726727/25613708/7af7b4c8-2f2f-11e7-8405-bc1dccbb0143.png)

**Comment by ErikZigo** [comment]
Jedna se o stary google drive writer.


Warningy se spatne definovanyma props jsem fixnul. Je to ve vlatni branchi. (https://github.com/keboola/kbc-ui/tree/fix-wr-google-drive)


Add table ale stale nefunguje.

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/pull/991
