### ISSUE TITLE
input mapping styling

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#988]
![image](https://cloud.githubusercontent.com/assets/497675/25619197/4ef424e0-2f4a-11e7-9897-31194e66ec98.png)

a) days input has left margin
b) select inputs are bigger than the others
 

check in 

1) `InputMappingRow[MySql|Redshift|Snowflake|Docker]Editor`
2) `TableInputMapping`

**Comment by janmichek** [comment]
Premejslim jak to udelat. Samozrejme jsem si toho vsiml a podobnych veci je v aplikaci spoustu.
Moznost 1. - naprasit to custom pro tuhle podstranku, doufat ze me to nikde nevytrolli, casem to udelat poradne.
Moznost 2. - vyresit problem, tim ze se postupne sjednoti formulare a formularove prvky napric aplikaci. Coz pro me samotnyho jsou mesice prace.

**Comment by ondrejhlavacek** [comment]
Pokud existuje nějaká snadná (=laciná) cesta, jak ten vizuál srovnat, tak bych volil variantu 1. Víc energie bych tomu teď nevěnoval, je dost možný, že bude ještě varianta 3, která bude obsahovat úplný předělání formuláře, kde tenhle problém může přestat existovat :-)

**Comment by janmichek** [comment]
Hele jo, nasel jsem celkem quickfix ktery neni prasarna.
Myslel jsem ze to bude vic zamotany.
Srovnal jsem vsechny formularovy prvku na vysku 36px.
Dokladam tady par screenu, nicmene budu rad za proklikani jinych casti aplikace, kde je podezreni na nejednotu. Neni v mych silach proklikat vsechny podstranky.

OM pred
![om-old](https://user-images.githubusercontent.com/15363559/43127740-7d489e88-8f30-11e8-925b-06186d1e73e6.PNG)


OM po
![om-nex](https://user-images.githubusercontent.com/15363559/43127745-81829260-8f30-11e8-85cd-b278a20924e0.PNG)


IM pred
![im-old](https://user-images.githubusercontent.com/15363559/43127761-8e6f5eae-8f30-11e8-839f-12d212dd45ff.PNG)



IM po
![im-new](https://user-images.githubusercontent.com/15363559/43127768-93a02f3e-8f30-11e8-803b-239d4a66025d.PNG)



AWS S3 pred
![aws-old](https://user-images.githubusercontent.com/15363559/43127797-9e16b4ec-8f30-11e8-9889-be2c633c24c3.PNG)



AWS S3 po
![aws-new](https://user-images.githubusercontent.com/15363559/43127805-a48684ba-8f30-11e8-96cc-9f5e576e8c31.PNG)



Token pred
![tok-old](https://user-images.githubusercontent.com/15363559/43127813-aa6c3c76-8f30-11e8-9120-504f3c1a7ac8.PNG)


Token po
![token-new](https://user-images.githubusercontent.com/15363559/43127828-b15ab4b8-8f30-11e8-8fb3-91cf73c10d92.PNG)
