### ISSUE TITLE
output mapping styling

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#989]
![image](https://cloud.githubusercontent.com/assets/497675/25619336/c712e5a6-2f4a-11e7-9541-a5e18614e65a.png)

a) select is larger than the other inputs

check

1) `OutputMappingRowEditor`
2) `TableOutputMappingEditor`

**Comment by natocTo** [comment]
Toto je již stejné. Podobné issue jsem zavíral pár dní zpět. Asi se to upravovalo.

**Comment by janmichek** [comment]
Jj, to jsem upravoval uz driv, diky
