### ISSUE TITLE
input/output mapping review

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#990]
![image](https://cloud.githubusercontent.com/assets/497675/25619645/ee1b179e-2f4b-11e7-9072-55d215f5782c.png)

projít UX kolečkem, jestli to nejde udělat jinak. transformace a docker appky

nahradí #988 #989

**Comment by ujovlado** [comment]
Toto sa myslim fixlo a ten IM je relativne odladeny. Ak sa rozhodneme to prehodit na vlastnu stranku, tak v novom issue.
