### ISSUE TITLE
Sandbox Modal

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui#998]
![image](https://cloud.githubusercontent.com/assets/497675/25659878/2166fd2a-300a-11e7-9dd9-67bae3c462f9.png)

a) help block (note) alignment
b) typos (missing space before more, extra space before three dots)

![image](https://cloud.githubusercontent.com/assets/497675/25659940/4c318700-300a-11e7-9d42-949708e2a943.png)

a) missing space here too

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/48580141-a6b57280-e91e-11e8-8750-b67f855b9825.png)

Furt to tam je - v detailu transformace klikni na `New Sandbox` vpravo

![image](https://user-images.githubusercontent.com/497675/48580190-d3698a00-e91e-11e8-9716-8ae689ac1616.png)

Tři tečky bych úplně vyhodil a nahradil je jednou, to zarovnání `Note` furt platí.

**Comment by natocTo** [comment]
Díky za navedení. Koukal jsem jinam.
